ALTER SESSION SET current_schema = CONSINCO; -- Adicionado Similaridade

SELECT ORIGEM, A.SEQPRODUTO, B.DESCSEGMENTO,  MAX(A.DTAHORALTERACAO) DATAHR_ALTERACAO, USUALTERACAO, 
       A.PRECO, CASE WHEN A.APROVADOREPROVADO IS NULL THEN 'Ainda não aprovado' ELSE A.APROVADOREPROVADO END STATUS,
       A.QTDEMBALAGEM, TO_CHAR((A.PRECO / A.QTDEMBALAGEM), 'FM99G999D00') Preco_Unitario, A.VLRCUSTO
FROM CONSINCO.MAD_PRODLOGPRECO A JOIN CONSINCO.MAD_SEGMENTO B ON A.NROSEGMENTO = B.NROSEGMENTO
     LEFT JOIN MAP_PRODSIMILAR C ON A.SEQPRODUTO = C.SEQPRODUTO
     WHERE -- CRITÉRIOS
      -- C.SEQSIMILARIDADE = 726
      -- SEQPRODUTO IN (206477 )
      -- AND QTDEMBALAGEM = 1
      -- AND B.NROSEGMENTO = 1
      -- AND NROEMPRESA = 51
      --AND A.QTDEMBALAGEM = 1
      
GROUP BY ORIGEM, B.DESCSEGMENTO,A.SEQPRODUTO,  A.PRECO, APROVADOREPROVADO, USUALTERACAO, A.QTDEMBALAGEM,(A.PRECO / A.QTDEMBALAGEM), VLRCUSTO
ORDER BY 4 DESC
