ALTER SESSION SET current_schema = CONSINCO;

SELECT ORIGEM, MAX(DTAHORALTERACAO), PRECO, USUALTERACAO 
FROM CONSINCO.MAD_PRODLOGPRECO
     WHERE SEQPRODUTO =           52573
       AND PRECO      =           9.98
       AND APROVADOREPROVADO = 'A'
GROUP BY ORIGEM, PRECO, USUALTERACAO
ORDER BY 2 DESC
