ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

 SELECT ODR X_REPETE, SEQPRODUTO, SEQFAMILIA, DESCCOMPLETA, 'ATIVO' STATUSVENDA
   FROM (SELECT SUBSTR(A.SEQPRODUTO, 0, LENGTH(A.SEQPRODUTO) - 1),
                ROW_NUMBER() OVER(PARTITION BY SUBSTR(A.SEQPRODUTO, 0, LENGTH(A.SEQPRODUTO) - 1) ORDER BY SUBSTR(A.SEQPRODUTO, 0, LENGTH(A.SEQPRODUTO) - 1))  ODR,
                A.*
           FROM MAP_PRODUTO A
          INNER JOIN MAP_FAMILIA B
             ON A.SEQFAMILIA = B.SEQFAMILIA
          WHERE PESAVEL = 'S'
            AND B.PMTDECIMAL = 'S'
            AND EXISTS (SELECT 1 FROM MRL_PRODEMPSEG X WHERE X.SEQPRODUTO = A.SEQPRODUTO AND X.STATUSVENDA = 'A')) TAB
  WHERE ODR > 1
    
  ORDER BY 
   SEQPRODUTO
