ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT Z.CODACESSO COD_PRODUTO, Z.SEQPRODUTO PLU, DESCCOMPLETA, F.CODNBMSH COD_NCM, F.CODCEST COD_CEST,
       NVL(UC.CFOPESTADO,(SELECT CGO.CFOPESTADO FROM MAX_CODGERALOPER CGO WHERE CGO.CODGERALOPER = 610)) CFOP, 
       U.SITUACAONF CST_ICMS, F.SITUACAONFPISSAI CST_PIS, F.SITUACAONFCOFINSSAI CST_COFINS, F.SITUACAONFIPISAI CST_IPI, NULL CST_ISS,
       U.PERALIQUOTA ALIQ_ICMS, 
       CASE WHEN F.SITUACAONFPISSAI = '01' THEN 1.65 ELSE 0 END ALIQ_PIS, 
       CASE WHEN F.SITUACAONFCOFINSSAI = '01' THEN 7.60 ELSE 0 END ALIQ_COFINS, 
       NVL(F.PERALIQUOTAIPI,0) ALIQ_IPI,
       NVL(NULLIF(PRECOVALIDPROMOC,0), PRECOVALIDNORMAL) PRECO_VDA

  FROM MAP_PRODCODIGO Z INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = Z.SEQPRODUTO
                        INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                        INNER JOIN MAP_FAMDIVISAO D ON D.SEQFAMILIA = F.SEQFAMILIA
                        INNER JOIN MAP_TRIBUTACAOUF U ON U.NROTRIBUTACAO = D.NROTRIBUTACAO
                         LEFT JOIN MAX_CODGERALCFOP UC ON UC.NROTRIBUTACAO = D.NROTRIBUTACAO AND UC.CODGERALOPER = 610
                         LEFT JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = Z.SEQPRODUTO AND S.NROEMPRESA = 50 AND NROSEGMENTO = 2 AND S.QTDEMBALAGEM = 1
                         LEFT JOIN DIM_CATEGORIA@CONSINCODW CT ON CT.SEQFAMILIA = P.SEQFAMILIA
                         LEFT JOIN MAX_COMPRADOR CP ON  CP.SEQCOMPRADOR = D.SEQCOMPRADOR
                        
 WHERE (EXISTS ( SELECT 'T' FROM NAGT_BAKE50 T WHERE T.CODACESSO = Z.CODACESSO)
       -- Desconsidera o De/Para e usa os filtros do Thoome via Teams
            OR TIPCODIGO = 'E'
           AND Z.INDUTILVENDA = 'S'
           AND Z.INDEANTRIBNFE = 'S'
           AND EXISTS (SELECT 1 FROM MRL_PRODUTOEMPRESA AA WHERE AA.DTAULTVENDA > SYSDATE - 60 AND AA.NROEMPRESA = S.NROEMPRESA AND AA.SEQPRODUTO = Z.SEQPRODUTO)
           AND (CT.CATEGORIAN4 = 'PICOLE'
            OR COMPRADOR IN ('DEBORAH','REBECA','EVELLYN NUNES'))) 
  
  AND U.UFEMPRESA = 'SP'
  AND U.UFCLIENTEFORNEC = 'SP'
  AND U.NROREGTRIBUTACAO = 0
  AND U.TIPTRIBUTACAO = 'SN' 
  
  ORDER BY 3
