ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT Z.CODACESSO COD_PRODUTO, Z.SEQPRODUTO PLU, DESCCOMPLETA, F.CODNBMSH COD_NCM, F.CODCEST COD_CEST,
       NVL(UC.CFOPESTADO,(SELECT CGO.CFOPESTADO FROM MAX_CODGERALOPER CGO WHERE CGO.CODGERALOPER = 610)) CFOP, 
       U.SITUACAONF CST_ICMS, F.SITUACAONFPISSAI CST_PIS, F.SITUACAONFCOFINSSAI CST_COFINS, F.SITUACAONFIPISAI CST_IPI, NULL CST_ISS

  FROM MAP_PRODCODIGO Z INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = Z.SEQPRODUTO
                        INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                        INNER JOIN MAP_FAMDIVISAO D ON D.SEQFAMILIA = F.SEQFAMILIA
                        INNER JOIN MAP_TRIBUTACAOUF U ON U.NROTRIBUTACAO = D.NROTRIBUTACAO
                         LEFT JOIN MAX_CODGERALCFOP UC ON UC.NROTRIBUTACAO = D.NROTRIBUTACAO AND UC.CODGERALOPER = 610
                        
 WHERE EXISTS ( SELECT 'T' FROM NAGT_BAKE50 T WHERE T.CODACESSO = Z.CODACESSO)
  
  AND U.UFEMPRESA = 'SP'
  AND U.UFCLIENTEFORNEC = 'SP'
  AND U.NROREGTRIBUTACAO = 0
  AND U.TIPTRIBUTACAO = 'SN'
