-- View CONSINCO.NAGV_APURACAOVENDAS

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.NROEMPRESA, ME.FANTASIA, ROUND(SUM(CTO1),2) CUSTO, SUM(VLR1) VENDA

FROM (

SELECT  MF.NROEMPRESA,fBuscaCustoLiquidoProd(MFI.SEQPRODUTO, MF.NROEMPRESA) * SUM(MFI.QUANTIDADE) CTO1,
        SUM(MFI.VLRITEM
      + NVL( MFI.VLRDESCSF, 0 )
      - NVL( MFI.VLRDESCITEM, 0 )
      - NVL( MFI.VLRFUNRURALITEM, 0 )
      + CASE WHEN MF.INDCONSIDFRETEDESPTRIB = 'N' THEN
             NVL( MFI.VLRDESPTRIBUTITEM, 0 ) + NVL( MFI.VLRFRETENANF, 0 )
        ELSE NVL( MFI.VLRDESPTRIBUTITEM, 0 ) END
      + NVL( MFI.VLRDESPNTRIBUTITEM, 0 )
      - NVL( MFI.VLRDESCSUFRAMA, 0 )
      + NVL( MFI.VLRIPI, 0 )
      + NVL( MFI.VLRICMSST, 0 )
      + NVL( MFI.VLRFCPST, 0 )
    ) / SUM(MFI.QUANTIDADE) VLR1
    
  FROM CONSINCO.MLF_NOTAFISCAL     MF,
       CONSINCO.MLF_NFITEM         MFI
      
WHERE MFI.NUMERONF         = MF.NUMERONF
  AND MFI.SEQPESSOA        = MF.SEQPESSOA
  AND MFI.SERIENF          = MF.SERIENF
  AND MFI.TIPNOTAFISCAL    = MF.TIPNOTAFISCAL
  AND MFI.NROEMPRESA       = MF.NROEMPRESA
  AND NVL( MFI.SEQNF, NVL( MF.SEQNF, 0 ) ) = NVL( MF.SEQNF, 0 )
  AND MF.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
  AND MF.NROEMPRESA < 300
  AND MF.DTAEMISSAO = '08-FEB-2023'
  GROUP BY MF.NROEMPRESA, SEQPRODUTO

UNION ALL

SELECT MD.NROEMPRESA, CONSINCO.fBuscaCustoLiquidoProd(MDI.SEQPRODUTO, MD.NROEMPRESA) * SUM(QUANTIDADE) CTO2,
       SUM((MDI.VLRITEM - (NVL(MDI.VLRDESCONTO,0) - NVL(MDI.VLRDESCBONIFABC,0))
     + NVL( MDI.VLRACRESCIMO, 0 ))) VLR2
     
FROM   CONSINCO.MFL_DOCTOFISCAL   MD,
       CONSINCO.MFL_DFITEM        MDI
WHERE MD.NUMERODF        = MDI.NUMERODF
  AND MD.SERIEDF         = MDI.SERIEDF
  AND MD.NROSERIEECF     = MDI.NROSERIEECF
  AND MD.NROEMPRESA      = MDI.NROEMPRESA
  AND NVL(MD.SEQNF, 0)   = NVL(MDI.SEQNF, NVL(MD.SEQNF, 0))
  AND MD.NROEMPRESA < 300
  AND MD.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
  AND MD.DTAMOVIMENTO = '08-FEB-2023'
    GROUP BY MD.NROEMPRESA, SEQPRODUTO 
  
  ) X INNER JOIN CONSINCO.MAX_EMPRESA ME ON X.NROEMPRESA = ME.NROEMPRESA
  
GROUP BY X.NROEMPRESA, ME.FANTASIA

ORDER BY 1 ASC 
  
