-- Confere produtos:
       -- Com estoque e inativos para venda
       -- Com estoque e preço unitário zerado

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;
SELECT DISTINCT NROEMPRESA, XX.SEQPRODUTO, DESCCOMPLETA, ESTOQUE, PRECO, STATUS_VENDA FROM (

SELECT X.NROEMPRESA, X.SEQPRODUTO, QTDESTQLOJA ESTOQUE, PRECOVALIDNORMAL PRECO,
       DECODE((SELECT DISTINCT(STATUSVENDA) FROM MRL_PRODEMPSEG Z WHERE Z.SEQPRODUTO = X.SEQPRODUTO AND Z.NROEMPRESA = X.NROEMPRESA AND NROSEGMENTO = 
                        (SELECT NROSEGMENTO FROM CONSINCO.MAX_EMPRESASEG Y WHERE Y.NROEMPRESA = X.NROEMPRESA AND Y.STATUS = 'A' AND Y.NROSEGMENTO NOT IN (1,5,8)) 
               AND Z.QTDEMBALAGEM = 1), 'A', 'ATIVO', 'INATIVO') STATUS_VENDA

  FROM CONSINCO.FATO_ESTOQUE X LEFT JOIN CONSINCO.MRL_PRODEMPSEG P ON P.SEQPRODUTO = X.SEQPRODUTO AND P.NROEMPRESA = X.NROEMPRESA AND P.NROSEGMENTO NOT IN (1,5,8) AND STATUSVENDA = 'A' AND P.QTDEMBALAGEM = 1

 WHERE DTAESTOQUE = TRUNC(SYSDATE) - 1
   AND X.NROEMPRESA < 100
   
       ) XX INNER JOIN CONSINCO.MAP_PRODUTO M ON XX.SEQPRODUTO = M.SEQPRODUTO
            INNER JOIN CONSINCO.MAP_FAMILIA F ON F.SEQFAMILIA = M.SEQFAMILIA
       
 WHERE (ESTOQUE > 0 AND STATUS_VENDA = 'INATIVO' OR ESTOQUE > 0 AND PRECO = 0)
   AND XX.SEQPRODUTO NOT IN (SELECT DISTINCT SEQPRODUTOBASE FROM MAP_PRODUTO BASE WHERE BASE.SEQPRODUTOBASE IS NOT NULL) -- Tira produtos que possuem relaiconados
   AND DESCCOMPLETA NOT LIKE '%INS%'
   AND DESCCOMPLETA NOT LIKE '%CONS%'
   AND DESCCOMPLETA NOT LIKE '%USO%'
   AND DESCCOMPLETA NOT LIKE '%SACOLA%'
   AND DESCCOMPLETA NOT LIKE '%MP%'
   AND DESCCOMPLETA NOT LIKE '%ROT%'
   AND DESCCOMPLETA NOT LIKE '%LEGUME%'
   AND PESAVEL = 'N'
   AND SEQPRODUTOBASE IS NULL
   
 ORDER 
    BY ESTOQUE DESC
    
     
     
