ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT SEQIDENTIFICA PLU, DESCCAMPO, USUAUDITORIA USUALTERACAO, Z.NOME, DTAAUDITORIA DTAALTERACAO
  FROM MAP_AUDITORIA X LEFT JOIN GE_USUARIO Z ON X.USUAUDITORIA = Z.CODUSUARIO
  
  WHERE TABELA = 'MRL_PRODUTOEMPRESA' AND CAMPO = 'LOCSAIDA' AND VLRATUAL LIKE '%386%'
