SELECT DISTINCT X.SEQPRODUTO PLU,
                DESCCOMPLETA,
                USUARIOINCLUSAO,
                TO_CHAR(DTAHORINCLUSAO, 'DD/MM/YYYY') DTAHORINCLUSAO,
                FORNEC,
                MAX(NVL(A.PALETELASTRO,0)) ARM_LASTRO, MAX(NVL(A.PALETEALTURA,0)) ARM_ALTURA,
                MAX(NVL(E.PALETELASTRO,0)) END_LASTRO, MAX(NVL(E.PALETEALTURA,0)) END_ALTURA,
                MAX(NVL(E.QTDEMBALAGEM,0)) EMB
  FROM (
        
        SELECT A.SEQPRODUTO,
                A.DESCCOMPLETA,
                COUNT(B.CODESPECENDERECO) CONTADOR,
                A.USUARIOINCLUSAO,
                A.DTAHORINCLUSAO,
                GE.SEQPESSOA || ' - ' || NOMERAZAO FORNEC
        
          FROM CONSINCO.MAP_PRODUTO A LEFT JOIN CONSINCO.MAD_PRODESPENDERECO B ON (B.SEQPRODUTO = A.SEQPRODUTO) AND NROEMPRESA = 501
                                     INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = A.SEQFAMILIA
                                     INNER JOIN MAX_COMPRADOR C  ON C.SEQCOMPRADOR = F.SEQCOMPRADOR
                                     INNER JOIN MAP_FAMFORNEC FF ON FF.SEQFAMILIA = A.SEQFAMILIA
                                     INNER JOIN GE_PESSOA GE     ON GE.SEQPESSOA = FF.SEQFORNECEDOR
        
         WHERE A.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2
               AND COMPRADOR IN (#LS1)
               AND SEQFORNECEDOR = :NR1
        
         GROUP BY A.SEQPRODUTO,
                   DESCCOMPLETA,
                   A.USUARIOINCLUSAO,
                   A.DTAHORINCLUSAO,
                   GE.SEQPESSOA || ' - ' || NOMERAZAO) X INNER JOIN MRL_PRODEMPRESAWM   A ON A.SEQPRODUTO = X.SEQPRODUTO
                                                         INNER JOIN MLO_PRODESPENDERECO E ON E.SEQPRODUTO = X.SEQPRODUTO
                   
 WHERE CONTADOR < 10

GROUP BY X.SEQPRODUTO, DESCCOMPLETA, USUARIOINCLUSAO, TO_CHAR(DTAHORINCLUSAO, 'DD/MM/YYYY'), FORNEC

 ORDER BY 2
