SELECT SEQIDENTIFICA COD_REND,
       ORIGEM,
       CAMPO,
       DESCCAMPO,
       TO_CHAR(DTAAUDITORIA, 'DD/MM/YYYY') DATA_ALTERACAO,
       VLRANTERIOR,
       VLRATUAL,
       USUAUDITORIA USUARIO,
       IDENTIFICADOR PRODUTO,
       OSUSER NOME_USUALT
       
  FROM MAP_AUDITORIA X

 WHERE DTAAUDITORIA BETWEEN :DT1 AND :DT2
   AND ORIGEM = 'RECEITA/RENDIMENTO'
   AND SEQIDENTIFICA = '10230'

 ORDER BY X.DTAHORAUDITORIA DESC
