ALTER SESSION SET current_schema = CONSINCO;

select  *                                          
from  consinco.MAP_PRODCODIGO A
where  CODACESSO LIKE   '%00000085827'
and  TIPCODIGO in ('B', 'E', 'D', 'F') 
and  A.CGCFORNEC = 07526557

SELECT NOMERAZAO, SEQPESSOA, SUBSTR(NROCGCCPF,0,8) CGC, NROCGCCPF||DIGCGCCPF FROM GE_PESSOA WHERE NROCGCCPF LIKe '%34274233%' 
ORDER BY 1
