/*SELECT  fBuscaEANProdutomaior(A.seqproduto) EAN, A.PRODUTO, A.MARCA,
        CASE WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSCOMPRA = 'A') THEN 'ATIVO' 
            WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSCOMPRA = 'S') THEN 'SUSPENSO'
            ELSE 'INATIVO' END STATUS_COMPRA,
       CASE WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSVENDA = 'A') THEN 'ATIVO' 
            WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSVENDA = 'S') THEN 'SUSPENSO'
            ELSE 'INATIVO' END STATUS_VENDA 

FROM QLV_PRODUTO@CONSINCODW A 

ORDER BY 2 ASC*/

SELECT DISTINCT A.SEQPRODUTO PLU, B.CODACESSO EAN, A.DESCCOMPLETA NOME,F.MARCA,
                CASE WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSCOMPRA = 'A') THEN 'ATIVO' 
                WHEN A.SEQPRODUTO      IN (SELECT Z.SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSCOMPRA = 'S') THEN 'SUSPENSO'
                ELSE 'INATIVO' END STATUS_COMPRA,
                CASE WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSVENDA = 'A')  THEN 'ATIVO' 
                ELSE 'INATIVO' END STATUS_VENDA,
                NVL(SUM(EP.ESTQLOJA),0) ESTOQUE_LOJA,     NVL(SUM(EP.ESTQDEPOSITO),0) ESTOQUE_CD,  NVL(SUM(EP.ESTQTROCA),0) ESTOQUE_TROCA,
                NVL(SUM(EP.ESTQTERCEIRO),0) ESTOQUE_TERC, NVL(SUM(EP.ESTQOUTRO),0) ESTOQUE_OUTROS, NVL(SUM(EP.QTDRESERVADAVDA),0) ESTOQUE_RESERVA,
                MF.QTDEMBALAGEM QUANTIDADE, MF.EMBALAGEM, MF.QTDUNIDEMB QTDE_UNID_EMB, MF.FATORCONVEMBNFE FATOR_CONV_EMB_NFE, MF.STATUS, QL.APELIDO COMPRADOR,
                TO_CHAR(MAX(A.DTAHORINCLUSAO),   'DD-MM-YYYY')          DATA_CADASTRO,
                TO_CHAR(MAX(EP.DTAULTCOMPRA),    'DD-MM-YYYY')          DATA_ULT_COMPRA,
                TO_CHAR(MAX(A2.DTAHORFECHAMENTO),'DD-MM-YYYY')          DATA_ULT_PEDIDO,
                TO_CHAR(MAX(EP.DTAULTENTRADA),   'DD-MM-YYYY')          DATA_ULT_ENTRADA,
             --  (SELECT SUM(QTDOPERACAO) FROM FATOG_VENDADIA@CONSINCODW X WHERE X.SEQPRODUTO = A.SEQPRODUTO AND CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911) AND DTAOPERACAO > SYSDATE - 180) VDA_ULTIMO_SEMESTRE
               (SELECT SUM(X.QTDVDA) FROM CONSINCO.MRL_CUSTODIA X WHERE X.SEQPRODUTO = A.SEQPRODUTO AND X.DTAENTRADASAIDA > SYSDATE - 180) VDA_ULTIMO_SEMESTRE
       
FROM MAP_PRODUTO A
       LEFT JOIN CONSINCO.MAP_PRODCODIGO B      ON A.SEQPRODUTO  = B.SEQPRODUTO AND B.TIPCODIGO = 'E' AND B.QTDEMBALAGEM = 1 --EAN
       LEFT JOIN CONSINCO.MAP_FAMILIA PA        ON PA.SEQFAMILIA = A.SEQFAMILIA
       LEFT JOIN CONSINCO.MAP_MARCA F           ON F.SEQMARCA    = PA.SEQMARCA
       LEFT JOIN CONSINCO.MRL_PRODUTOEMPRESA EP ON EP.SEQPRODUTO = A.SEQPRODUTO
       LEFT JOIN CONSINCO.MAP_FAMEMBALAGEM MF   ON MF.SEQFAMILIA = A.SEQFAMILIA
       /*LEFT JOIN (SELECT I.SEQPRODUTO, MAX(I.DTAULTCOMPRA) DTAULTCOMPRA, MAX(I.DTAULTENTRADA) DTAULTENTRADA FROM CONSINCO.MRL_PRODUTOEMPRESA I WHERE I.STATUSCOMPRA != 'I'
       GROUP BY SEQPRODUTO) II                  ON II.SEQPRODUTO = A.SEQPRODUTO*/
       LEFT JOIN (SELECT SEQPRODUTO, BB.DTAHORFECHAMENTO, BB.SITUACAOLOTE, BB.TIPOLOTE FROM CONSINCO.MAC_GERCOMPRAITEM AA 
       LEFT JOIN CONSINCO.MAC_GERCOMPRA BB      ON AA.SEQGERCOMPRA = BB.SEQGERCOMPRA WHERE BB.SITUACAOLOTE = 'F' AND BB.TIPOLOTE IN ('E', 'T') /*AND AA.SEQPRODUTO = A.SEQPRODUTO*/) A2 ON A2.SEQPRODUTO = A.SEQPRODUTO
       LEFT JOIN QLV_CATEGORIA@CONSINCODW QL    ON QL.SEQFAMILIA = A.SEQFAMILIA
   
--WHERE A.SEQPRODUTO NOT IN (SELECT DISTINCT SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.STATUSCOMPRA = 'I')

GROUP BY A.SEQPRODUTO, B.CODACESSO, A.DESCCOMPLETA, MARCA, MF.QTDEMBALAGEM, MF.EMBALAGEM, MF.QTDUNIDEMB, MF.FATORCONVEMBNFE, MF.STATUS, QL.APELIDO
         
ORDER BY 3 ASC;

