ALTER SESSION SET current_schema = CONSINCO;

SELECT P.SEQPRODUTO PLU, E.CODACESSO EAN, F.OBSEMERGENCIAL

FROM CONSINCO.MAP_PRODUTO P INNER JOIN CONSINCO.MAP_FAMILIA F ON P.SEQFAMILIA = F.SEQFAMILIA AND F.OBSEMERGENCIAL LIKE '%Mercadoria%'
LEFT JOIN CONSINCO.MAP_PRODCODIGO E ON P.SEQPRODUTO = E.SEQPRODUTO AND E.TIPCODIGO = 'E' ;
