SELECT * FROM CONSINCO.MAP_FAMDIVCATEG A LEFT JOIN CONSINCO.MAP_CATEGORIA B ON A.SEQCATEGORIA = B.SEQCATEGORIA
WHERE A.SEQFAMILIA IN(466318) AND STATUS = 'A' 
AND B.ACTFAMILIA = 'S'

UPDATE CONSINCO.MAP_FAMDIVCATEG A SET A.SEQCATEGORIA = 20004
 WHERE A.SEQFAMILIA = 466318 AND A.SEQCATEGORIA = 11070 AND A.STATUS = 'A'
       
INSERT INTO CONSINCO.MAP_FAMDIVCATEG F 

       SELECT 68826, 20004, D.NRODIVISAO, D.STATUS, D.INDREPLICACAO, D.INDGEROUREPLICACAO, D.DTABASEEXPORTACAO, D.NROBASEEXPORTACAO,
                            D.DATAHORAALTERACAO, D.DATAHORAINTEGRAECOMMERCE, D.USUARIOALTERACAO, D.SEQCORRESPONDENCIA
       FROM CONSINCO.MAP_FAMDIVCATEG d LEFT JOIN CONSINCO.MAP_CATEGORIA B ON D.SEQCATEGORIA = B.SEQCATEGORIA
       WHERE D.SEQFAMILIA IN(466318) AND D.STATUS = 'A' 
       AND B.ACTFAMILIA = 'S';

COMMIT;

INSERT INTO CONSINCO.MAP_FAMDIVCATEG F 

       SELECT 68799, 20004, D.NRODIVISAO, D.STATUS, D.INDREPLICACAO, D.INDGEROUREPLICACAO, D.DTABASEEXPORTACAO, D.NROBASEEXPORTACAO,
                            D.DATAHORAALTERACAO, D.DATAHORAINTEGRAECOMMERCE, D.USUARIOALTERACAO, D.SEQCORRESPONDENCIA
       FROM CONSINCO.MAP_FAMDIVCATEG d LEFT JOIN CONSINCO.MAP_CATEGORIA B ON D.SEQCATEGORIA = B.SEQCATEGORIA
       WHERE D.SEQFAMILIA IN(466318) AND D.STATUS = 'A' 
       AND B.ACTFAMILIA = 'S';

COMMIT;

INSERT INTO CONSINCO.MAP_FAMDIVCATEG F 

       SELECT 7896228101406, 20004, D.NRODIVISAO, D.STATUS, D.INDREPLICACAO, D.INDGEROUREPLICACAO, D.DTABASEEXPORTACAO, D.NROBASEEXPORTACAO,
                            D.DATAHORAALTERACAO, D.DATAHORAINTEGRAECOMMERCE, D.USUARIOALTERACAO, D.SEQCORRESPONDENCIA
       FROM CONSINCO.MAP_FAMDIVCATEG d LEFT JOIN CONSINCO.MAP_CATEGORIA B ON D.SEQCATEGORIA = B.SEQCATEGORIA
       WHERE D.SEQFAMILIA IN(466318) AND D.STATUS = 'A' 
       AND B.ACTFAMILIA = 'S';

COMMIT;
