SELECT DISTINCT A.SEQPRODUTO PRODUTO_SKU, E.PRECOBASENORMAL, A.SEQFAMILIA PRODUTO_FAMILIA, B.SEQSIMILARIDADE, S.DESCSIMILARIDADE DESC_SIMILARIDADE, DESCCOMPLETA PRODUTO_DESCRICAO, 
       CATEGORIA_NIVEL_1 CATEGORIA, CATEGORIA_COMPLETA ARVORE, COMPRADOR
  FROM MAP_PRODUTO A LEFT JOIN MAP_PRODSIMILAR B ON B.SEQPRODUTO = A.SEQPRODUTO
                     LEFT JOIN MAP_SIMILARIDADE S ON S.SEQSIMILARIDADE = B.SEQSIMILARIDADE
                     LEFT JOIN QLV_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = A.SEQFAMILIA    
                     LEFT JOIN MAP_FAMDIVISAO X ON A.SEQFAMILIA = X.SEQFAMILIA 
                     LEFT JOIN QLV_COMPRADOR@CONSINCODW Z ON Z.SEQCOMPRADOR = X.SEQCOMPRADOR 
                     LEFT JOIN MRL_PRODEMPSEG E ON A.SEQPRODUTO = E.SEQPRODUTO AND NROEMPRESA = 8 AND NROSEGMENTO = 2 AND E.QTDEMBALAGEM = 1
                     
                     WHERE CATEGORIA_NIVEL_1 = :LS1   
                       AND S.TIPOSIMILARIDADE = 'S' 
                     
                     ORDER BY 3 
