-- Ticket 519417

SELECT PLU, COD_FAMILIA, DESCCOMPLETA, DESC_HUMANIZADA FROM (
SELECT SEQPRODUTO PLU, P.SEQFAMILIA COD_FAMILIA, DESCCOMPLETA, P.NOMEPRODUTOECOMM DESC_HUMANIZADA,
       CASE WHEN P.NOMEPRODUTOECOMM IS NULL THEN 'Sem DH' ELSE 'Com DH' END POSSUI_DH
  FROM MAP_PRODUTO P INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA 
 WHERE EXISTS (SELECT 1 FROM MRL_PRODEMPSEG X WHERE X.NROEMPRESA = 8 AND X.NROSEGMENTO = 2 AND X.STATUSVENDA = 'A') 
   AND F.FINALIDADEFAMILIA = 'R')
  
 WHERE POSSUI_DH IN (#LS1)
