SELECT A.SEQPRODUTO,
       A.CODACESSO,
       B.DESCCOMPLETA,
       A.TIPCODIGO,
       A.INDEANTRIBNFE, B.DTAHORINCLUSAO DATA_INCLUSAO, B.USUARIOINCLUSAO
FROM CONSINCO.MAP_PRODCODIGO A INNER JOIN CONSINCO.MAP_PRODUTO B ON (A.SEQPRODUTO = B.SEQPRODUTO)
WHERE A.INDEANTRIBNFE = 'N'
AND A.TIPCODIGO = 'E'
AND B.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2
ORDER BY TO_CHAR(B.DTAHORINCLUSAO, 'DD/MM/YYYY') DESC
