ALTER SESSION SET current_schema = CONSINCO;
SELECT * FROM (
SELECT TO_CHAR(DTAALTERACAO, 'DD/MM/YYYY') DATA, COUNT(1) COUNT, USUALTERACAO FROM CONSINCO.GE_PESSOA B 
WHERE  USUALTERACAO IS NOT NULL
  AND  DTAALTERACAO > DATE '2022-12-01'
GROUP BY TO_CHAR(DTAALTERACAO, 'DD/MM/YYYY'), USUALTERACAO) WHERE COUNT > 1000

ORDER BY 1 ASC 
