ALTER SESSION SET current_schema = CONSINCO;


SELECT DISTINCT SEQRECEITARENDTO COD_RECEITA,RECEITARENDTO DESC_RECEITA,
                SEQPRODUTOCOMP COD_COMPONENTE, PRODUTOCOMP DESC_COMPONENTE, 
                TO_CHAR(QTDUTILIZADA,'9G990D999')          QTD_UTILIZADA,
                SEQPRODUTOFINAL COD_PRODUTOFINAL, PRODUTOFINAL DESC_PRODUTOFINAL, 
                TO_CHAR(QTDUNIDPRODUZIDA, '9G990D999')     QTD_PRODUZIDA

FROM CONSINCO.MRLV_COMPONENTESRECEITA

WHERE INDRECEITARENDTO ='C' 

ORDER BY 1; 


SELECT DISTINCT A.SEQRECEITARENDTO COD_RECEITA,RECEITARENDTO DESC_RECEITA,
                SEQPRODUTOCOMP COD_INICIAL, PRODUTOCOMP DESC_PRODUTOINICIAL, 
                TO_CHAR(QTDUTILIZADA,'9G990D999')          QTD_PRODUTOINICIAL,
                B.SEQPRODUTO COD_PRODUTOFINAL, C.DESCCOMPLETA DESC_PRODUTOFINAL, 
                B.PERCRATEIOQTDE PORC_RATEIO

FROM CONSINCO.MRLV_COMPONENTESRECEITA A LEFT JOIN MRL_RRPRODUTOFINAL B ON A.SEQRECEITARENDTO = B.SEQRECEITARENDTO, MAP_PRODUTO C

WHERE INDRECEITARENDTO = 'N'
AND B.SEQPRODUTO = C.SEQPRODUTO

ORDER BY 1;


