-- Ativa compra dos itens que estão ativos para varejo

ALTER SESSION SET current_schema = CONSINCO;

update mrl_produtoempresa a
set a.statuscompra = 'A'
where a.seqproduto IN (SELECT DISTINCT I.SEQPRODUTO FROM MRL_PRODEMPSEG I LEFT JOIN MAP_PRODUTO K ON I.SEQPRODUTO = K.SEQPRODUTO
 WHERE I.NROEMPRESA = 54 AND STATUSVENDA = 'A' AND I.NROSEGMENTO = 7 AND  PRECOBASENORMAL != 0 AND I.SEQPRODUTO IN (
SELECT J.SEQPRODUTO FROM MRL_PRODEMPSEG J WHERE J.NROEMPRESA = 54 AND J.NROSEGMENTO = 7 AND STATUSVENDA = 'A' AND J.QTDEMBALAGEM > 1))
AND NROEMPRESA = 54;


UPDATE MAP_PRODEMPRSTATUS SET STATUSCOMPRA = 'A',
                              DTAHORALTERACAO = SYSDATE,
                              USUARIOALTERACAO = 'GIGOMES',
                              INDREPLICACAO = 'S',
                              INDGEROUREPLICACAO = NULL
          WHERE MAP_PRODEMPRSTATUS.SEQPRODUTO IN (SELECT DISTINCT I.SEQPRODUTO FROM MRL_PRODEMPSEG I LEFT JOIN MAP_PRODUTO K ON I.SEQPRODUTO = K.SEQPRODUTO
 WHERE I.NROEMPRESA = 54 AND STATUSVENDA = 'A' AND I.NROSEGMENTO = 7 AND  PRECOBASENORMAL != 0 AND I.SEQPRODUTO IN (
SELECT J.SEQPRODUTO FROM MRL_PRODEMPSEG J WHERE J.NROEMPRESA = 54 AND J.NROSEGMENTO = 7 AND STATUSVENDA = 'A' AND J.QTDEMBALAGEM > 1))
   AND NROEMPRESA = 54;

COMMIT;
