ALTER SESSION SET current_schema = CONSINCO;
SELECT DISTINCT A.SEQPRODUTO PLU, B.CODACESSO EAN, A.DESCCOMPLETA DESCRICAO, 'ATIVO' STATUS_COMPRA,
                TO_CHAR(A.DTAHORINCLUSAO,'DD-MM-YYYY')             DATA_CADASTRO,
                TO_CHAR(II.DTAULTCOMPRA,'DD-MM-YYYY')          DATA_ULT_COMPRA,
                TO_CHAR(MAX(A2.DTAHORFECHAMENTO),'DD-MM-YYYY')     DATA_ULT_PEDIDO,
                F.MARCA,D.NOMERAZAO FORNECEDOR,
                (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 1)) Nivel_1, 
                (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 2)) Nivel_2, 
                (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 3)) Nivel_3,
                (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 4)) Nivel_4,
                (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 5)) Nivel_5,
                TO_NUMBER('0') VENDAS_ULTIMO_TRIMESTRE,
                SUM(EP.ESTQLOJA) ESTOQUE_LOJA, SUM(EP.ESTQDEPOSITO) ESTOQUE_DEP, SUM(EP.ESTQTROCA) ESTOQUE_TROCA
FROM MAP_PRODUTO A
       LEFT JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO AND B.TIPCODIGO = 'E' AND B.QTDEMBALAGEM = 1
       LEFT JOIN (SELECT I.SEQPRODUTO, MAX(I.DTAULTCOMPRA) DTAULTCOMPRA FROM MRL_PRODUTOEMPRESA I WHERE I.STATUSCOMPRA != 'I'
       GROUP BY SEQPRODUTO) II ON II.SEQPRODUTO = A.SEQPRODUTO
       LEFT JOIN (SELECT SEQPRODUTO, BB.DTAHORFECHAMENTO, BB.SITUACAOLOTE, BB.TIPOLOTE FROM MAC_GERCOMPRAITEM AA 
       LEFT JOIN MAC_GERCOMPRA BB ON AA.SEQGERCOMPRA = BB.SEQGERCOMPRA WHERE BB.SITUACAOLOTE = 'F' AND BB.TIPOLOTE = 'E') A2 
       ON A2.SEQPRODUTO = A.SEQPRODUTO
       LEFT JOIN MAP_FAMFORNEC C  ON C.SEQFAMILIA = B.SEQFAMILIA AND C.PRINCIPAL = 'S'
       LEFT JOIN MAP_FAMILIA PA ON PA.SEQFAMILIA = A.SEQFAMILIA
       LEFT JOIN GE_PESSOA D ON D.SEQPESSOA = C.SEQFORNECEDOR
       LEFT JOIN MAP_MARCA F ON F.SEQMARCA = PA.SEQMARCA
       LEFT JOIN (SELECT H.SEQCATEGORIA, MC.CAMINHOCOMPLETO, H.SEQFAMILIA, H.STATUS FROM MAP_FAMDIVCATEG H 
       LEFT JOIN MAP_CATEGORIA MC ON MC.SEQCATEGORIA = H.SEQCATEGORIA WHERE H.STATUS = 'A' AND MC.ACTFAMILIA = 'S' AND MC.TIPCATEGORIA = 'M') H 
       ON H.SEQFAMILIA = A.SEQFAMILIA
       LEFT JOIN MRL_PRODUTOEMPRESA EP ON EP.SEQPRODUTO = A.SEQPRODUTO 

WHERE A.DTAHORINCLUSAO BETWEEN DATE '2022-01-01' AND DATE '2022-05-01'
      AND EP.STATUSCOMPRA != 'I'
      AND EP.DTAULTVENDA < SYSDATE - 180

      
HAVING SUM(EP.ESTQLOJA) = 0      
   AND SUM(EP.ESTQDEPOSITO) = 0
   AND SUM(EP.ESTQTROCA) = 0
GROUP BY A.SEQPRODUTO, B.CODACESSO , A.DESCCOMPLETA, 
               TO_CHAR(A.DTAHORINCLUSAO,'DD-MM-YYYY'),
               TO_CHAR(II.DTAULTCOMPRA,'DD-MM-YYYY'), MARCA, NOMERAZAO,
               (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 1)) , 
               (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 2)) , 
               (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 3)) ,
               (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 4)) ,
               (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 5)) 
ORDER BY 3
