ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.SEQFAMILIA COD_FAMILIA, FAMILIA, Z.QTDEMBALAGEM, Z.EMBALAGEM, Z.MULTEQPEMB, Z.MULTEQPEMBALAGEM, 
       TO_CHAR(X.DTAHORINCLUSAO, 'DD/MM/YYYY HH24:MI') DTA_INCLUSAO, X.USUARIOINCLUSAO
  FROM MAP_FAMILIA X INNER JOIN MAP_FAMEMBALAGEM Z ON Z.SEQFAMILIA = X.SEQFAMILIA
 WHERE 1=1
   AND COALESCE(Z.MULTEQPEMBALAGEM, TO_CHAR(Z.MULTEQPEMB)) IS NULL
   AND X.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2
 
