ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT M.SEQPRODUTO PLU, M.DESCCOMPLETA DESCRICAO, X.SEQFAMILIA, 'INATIVO' STATUS_VENDA_54, F.DESCRICAO FINALIDADE, M.USUARIOINCLUSAO, M.DTAHORINCLUSAO
FROM MAP_FAMDIVISAO X LEFT JOIN MAP_PRODUTO M ON M.SEQFAMILIA = X.SEQFAMILIA
                      LEFT JOIN MAP_FINALIDADEFAMILIA F ON F.FINALIDADEFAMILIA = X.FINALIDADEFAMILIA
WHERE M.SEQPRODUTO IN (SELECT DISTINCT SEQPRODUTO FROM MRL_PRODEMPSEG Y WHERE Y.NROSEGMENTO = 7 AND Y.NROEMPRESA = 54 AND Y.STATUSVENDA = 'I' AND QTDEMBALAGEM = 1)
AND X.FINALIDADEFAMILIA = 'R'

ORDER BY 2
