SELECT DISTINCT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ A.SEQPRODUTO SKU, 'Predeterminado' DIVISAO, DESCCOMPLETA DESC_PROD,
      (SELECT MAX(CODACESSO) FROM MAP_PRODCODIGO CC WHERE CC.SEQPRODUTO = A.SEQPRODUTO AND CC.TIPCODIGO = 'E') EAN,
       'https://assetsmn.s3.us-east-1.amazonaws.com/assets/ofertas/'||A.SEQPRODUTO||'.jpg' URL,
       'BRASIL' PAIS, 'São Paulo' ESTADO, 'Fabricante' TIPO_ORIGEM, B.CODORIGEMTRIB||' - '||D.DESCRICAO COD_ORIGEM, 
       SUBSTR(C.CODNBMSH,1,4)||'.'||SUBSTR(C.CODNBMSH,5,2)||'.'||SUBSTR(C.CODNBMSH,7,2) NCM,
       SUBSTR(C.CODCEST,1,2) ||'.'||SUBSTR(C.CODCEST,3,3) ||'.'||SUBSTR(C.CODCEST,6,2) CEST,
       C.SITUACAONFIPI IPI, UF.SITUACAONF ICMS, C.SITUACAONFPISSAI PIS, C.SITUACAONFCOFINSSAI COFINS,
       NULL REABASTECIMENTO, ROUND(S.CMULTVLRNF,2) CUSTO_NF,
       fBuscaCustoLiquidoProd(a.seqproduto, se.nroempresa) CUSTO_GER, 
      (SELECT ROUND(MGMPRECOVALIDO,2) FROM MAXV_MGMBASEPRODSEG X WHERE X.SEQPRODUTO = A.SEQPRODUTO AND X.NROEMPRESA = S.NROEMPRESA AND X.NROSEGMENTO = SE.NROSEGMENTO AND X.QTDEMBALAGEM = SE.QTDEMBALAGEM) MARGEM,
       SE.PRECOVALIDNORMAL PRECO_VENDA, 1 MIN_COMPRA, 1 MULT_COMPRA,
       NULL CONAMA, NULL ANVISA, NULL MAPA, DECODE(HE.EMBALAGEM, 'CX','Caixa','FD','Fardo') FORM_FATURA, TO_NUMBER(HE.QTDEMBALAGEM) UNI_FORM_FATURA,
       E.MARCA, COALESCE(CATEGORIAN4, CATEGORIAN3, CATEGORIAN2) LINHA, 
       CASE WHEN H.QTDEMBALAGEM = 1 AND C.PESAVEL != 'S' THEN 'Unidade'
            WHEN H.QTDEMBALAGEM = 1 AND C.PESAVEL  = 'S' THEN 'KG'
              ELSE 'Caixa' END FORM_VENDA, TO_NUMBER(H.QTDEMBALAGEM) UNIDADE_EMB,
       I.PESOLIQUIDO PESO_UNI, 'g' UNID_PESO, NULL SABOR, NULL TIPO_EMB, 
       NULL LIVRE_ACUCAR, NULL LIVRE_GLUTEN, NULL VEGANO, NULL ORGANICO, A.NOMEPRODUTOECOMM DESCRICAO, NULL MODELO, NULL CONSERVACAO,
       I.PESOLIQUIDO QUANTIDADE, 'g' TIPO_UNI, A.PZOVALIDADEDIA VALIDADE, 'Dias' UNID_VALIDADE, NULL KIT, AM.PALETELASTRO, AM.PALETEALTURA
       
  FROM MAP_PRODUTO A INNER JOIN MAP_FAMDIVISAO B ON A.SEQFAMILIA = B.SEQFAMILIA
                     INNER JOIN MAP_FAMILIA    C ON C.SEQFAMILIA = B.SEQFAMILIA 
                     LEFT JOIN  MAX_ATRIBUTOFIXO D ON D.LISTA = B.CODORIGEMTRIB AND D.TIPATRIBUTOFIXO = 'ORIGEMMERCADORIA'
                     LEFT JOIN  MAP_MARCA      E ON E.SEQMARCA = C.SEQMARCA
                     LEFT JOIN  DIM_CATEGORIA@CONSINCODW F ON F.SEQFAMILIA = C.SEQFAMILIA
                     LEFT JOIN  MAP_PRODCODIGO H ON H.SEQPRODUTO = A.SEQPRODUTO AND H.INDUTILVENDA = 'S'
                     INNER JOIN  MAP_FAMEMBALAGEM I ON I.SEQFAMILIA = A.SEQFAMILIA AND I.QTDEMBALAGEM = H.QTDEMBALAGEM
                     INNER JOIN MRL_PRODUTOEMPRESA S ON S.SEQPRODUTO = A.SEQPRODUTO AND S.NROEMPRESA = 14
                     INNER JOIN MRL_PRODEMPSEG SE ON SE.SEQPRODUTO = A.SEQPRODUTO AND SE.NROEMPRESA = S.NROEMPRESA AND NROSEGMENTO = 2 AND SE.QTDEMBALAGEM = H.QTDEMBALAGEM
                     INNER JOIN  MAP_FAMEMBALAGEM HE ON HE.SEQFAMILIA = A.SEQFAMILIA AND HE.EMBALAGEM IN ('CX','FD')
                     INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = C.SEQFAMILIA
                     INNER JOIN  MAP_TRIBUTACAOUF UF ON UF.NROTRIBUTACAO = FD.NROTRIBUTACAO AND UF.TIPTRIBUTACAO = 'SC' AND UF.UFEMPRESA = 'SP' AND UF.UFCLIENTEFORNEC = 'SP' AND UF.NROREGTRIBUTACAO = 0
                     INNER JOIN MRL_PRODEMPRESAWM AM ON AM.SEQPRODUTO = A.SEQPRODUTO AND AM.NROEMPRESA = S.NROEMPRESA 
                     
 WHERE S.STATUSCOMPRA = 'A' AND SE.PRECOVALIDNORMAL > 0 AND I.QTDEMBALAGEM = 1 
