SELECT * FROM (
SELECT SEQPRODUTO PLU, DESCCOMPLETA, X.USUARIOINCLUSAO, TO_CHAR(DTAHORINCLUSAO, 'DD/MM/YYYY') DTAINCLUSAO,
      (SELECT MAX(STATUSVENDA) FROM CONSINCO.MRL_PRODEMPSEG N WHERE QTDEMBALAGEM = 1 AND NROSEGMENTO = 2 AND X.SEQPRODUTO = N.SEQPRODUTO 
              AND EXISTS (SELECT 1 FROM CONSINCO.MAX_EMPRESASEG Z WHERE Z.NROEMPRESA = N.NROEMPRESA AND Z.NROSEGMENTO = N.NROSEGMENTO AND Z.STATUS != 'I')) VDA_NAG_SP,
      (SELECT MAX(STATUSVENDA) FROM CONSINCO.MRL_PRODEMPSEG N WHERE QTDEMBALAGEM = 1 AND NROSEGMENTO = 3 AND X.SEQPRODUTO = N.SEQPRODUTO
              AND EXISTS (SELECT 1 FROM CONSINCO.MAX_EMPRESASEG Z WHERE Z.NROEMPRESA = N.NROEMPRESA AND Z.NROSEGMENTO = N.NROSEGMENTO AND Z.STATUS != 'I')) VDA_RJ,
      (SELECT MAX(STATUSVENDA) FROM CONSINCO.MRL_PRODEMPSEG N WHERE QTDEMBALAGEM = 1 AND NROSEGMENTO = 4 AND X.SEQPRODUTO = N.SEQPRODUTO
              AND EXISTS (SELECT 1 FROM CONSINCO.MAX_EMPRESASEG Z WHERE Z.NROEMPRESA = N.NROEMPRESA AND Z.NROSEGMENTO = N.NROSEGMENTO AND Z.STATUS != 'I'))  VDA_MIXTER,
      (SELECT MAX(STATUSVENDA) FROM CONSINCO.MRL_PRODEMPSEG N WHERE QTDEMBALAGEM = 1 AND NROSEGMENTO = 7 AND X.SEQPRODUTO = N.SEQPRODUTO
              AND EXISTS (SELECT 1 FROM CONSINCO.MAX_EMPRESASEG Z WHERE Z.NROEMPRESA = N.NROEMPRESA AND Z.NROSEGMENTO = N.NROSEGMENTO AND Z.STATUS != 'I')) VDA_NAG_HIB,
      (SELECT MAX(STATUSVENDA) FROM CONSINCO.MRL_PRODEMPSEG N WHERE QTDEMBALAGEM = 1 AND NROSEGMENTO = 5 AND X.SEQPRODUTO = N.SEQPRODUTO
              AND EXISTS (SELECT 1 FROM CONSINCO.MAX_EMPRESASEG Z WHERE Z.NROEMPRESA = N.NROEMPRESA AND Z.NROSEGMENTO = N.NROSEGMENTO AND Z.STATUS != 'I')) VDA_ECOMM_SP,
      (SELECT MAX(STATUSVENDA) FROM CONSINCO.MRL_PRODEMPSEG N WHERE QTDEMBALAGEM = 1 AND NROSEGMENTO = 8 AND X.SEQPRODUTO = N.SEQPRODUTO
              AND EXISTS (SELECT 1 FROM CONSINCO.MAX_EMPRESASEG Z WHERE Z.NROEMPRESA = N.NROEMPRESA AND Z.NROSEGMENTO = N.NROSEGMENTO AND Z.STATUS != 'I')) VDA_ECOMM_MIX    
      
  FROM CONSINCO.MAP_PRODUTO X WHERE X.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2) V
  
  WHERE VDA_NAG_SP    = 'I'
     OR VDA_RJ        = 'I'
     OR VDA_MIXTER    = 'I'
     OR VDA_NAG_HIB   = 'I'
     OR VDA_ECOMM_SP  = 'I'
     OR VDA_ECOMM_MIX = 'I'  

