SELECT A.TIPO ATRIBUTO, A.SEQPRODUTO CODPRODUTO, P.DESCCOMPLETA, B.CODACESSO CODIGO, B.TIPCODIGO, DESCRICAO DESC_ATRIBUTO
  FROM MAP_PRODDESCESP A INNER JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
                         INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO
INNER JOIN MAP_DESCESP E ON E.TIPO = A.TIPO
 WHERE A.TIPO = :LS1
   AND B.TIPCODIGO != 'F';
