ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT F.SEQFAMILIA, FAMILIA, SEQFORNECEDOR FORNEC, TIPFORNECEDORFAM TIP_FORNEC, 'Familia do Prod. EX sem parametrização de Industria (Fornec 502/503)' CRITICA
  FROM MAP_FAMFORNEC FC INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = FC.SEQFAMILIA
           WHERE FC.SEQFORNECEDOR IN (502,503) 
             AND NVL(FC.TIPFORNECEDORFAM, 'X') != 'I'
             AND EXISTS (SELECT 1 FROM MAP_FAMFORNEC EX INNER JOIN GE_PESSOA G ON G.SEQPESSOA = EX.SEQFORNECEDOR
                                 WHERE EX.SEQFAMILIA = FC.SEQFAMILIA
                                   AND UF = 'EX') 
