SELECT SEQIDENTIFICA COD_PRODUTO, DESCCOMPLETA, DESCCAMPO, ORIGEM, CAMPO, FD.DESCRICAO DESC_FINALIDADE,
       NVL(SUBSTR(VLRATUAL, 0,INSTR(VLRATUAL, ' -') -1), VLRATUAL) VALOR, TO_CHAR(X.DTAAUDITORIA, 'DD/MM/YYYY') DTA_AUDITORIA, X.USUAUDITORIA
       
  FROM MAP_AUDITORIA X INNER JOIN MAP_PRODUTO P ON X.SEQIDENTIFICA = P.SEQPRODUTO AND ORIGEM IN ('FAMILIA','PRODUTO')
                       INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA
                       INNER JOIN MAP_FINALIDADEFAMILIA FD ON FD.FINALIDADEFAMILIA = F.FINALIDADEFAMILIA
 WHERE CAMPO = 'CODACESSO' AND DESCCAMPO IN ('Inclusão do código de acesso', 'Exclusão do código de acesso')
   AND TRUNC(X.DTAAUDITORIA) BETWEEN :DT1 AND :DT2
   
 UNION /* Une os logs de alt em familia */
   
SELECT P.SEQPRODUTO COD_PRODUTO, DESCCOMPLETA, DESCCAMPO, ORIGEM, CAMPO, FD.DESCRICAO DESC_FINALIDADE,
       NVL(SUBSTR(VLRATUAL, 0,INSTR(VLRATUAL, ' -') -1), VLRATUAL) VALOR, TO_CHAR(X.DTAAUDITORIA, 'DD/MM/YYYY') DTA_AUDITORIA, NVL(X.USUAUDITORIA, OSUSER) USUAUDITORIA
       
  FROM MAP_AUDITORIA X INNER JOIN MAP_PRODUTO P ON X.SEQIDENTIFICA = P.SEQFAMILIA AND ORIGEM IN ('FAMILIA','PRODUTO')
                       INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA
                       INNER JOIN MAP_FINALIDADEFAMILIA FD ON FD.FINALIDADEFAMILIA = F.FINALIDADEFAMILIA
 WHERE 1=1 
   AND TRUNC(X.DTAAUDITORIA) BETWEEN :DT1 AND :DT2
   AND CAMPO IN ('PALETELASTRO','PALETEALTURA');
