SELECT X.SEQPRODUTO PLU,
       DESCCOMPLETA,
       X.SEQFAMILIA COD_FAMILIA,
       TO_CHAR(E.PESOBRUTO,
               'FM999G999G990D990',
               'NLS_NUMERIC_CHARACTERS='',.''') PESOBRUTO,
       TO_CHAR(E.PESOLIQUIDO,
               'FM999G999G990D990',
               'NLS_NUMERIC_CHARACTERS='',.''') PESOLIQUIDO,
       TO_CHAR(X.DTAHORINCLUSAO, 'DD/MM/YYYY') DTA_INCLUSAO,
       X.USUARIOINCLUSAO
  FROM MAP_PRODUTO X INNER JOIN MAP_FAMEMBALAGEM E ON E.SEQFAMILIA = X.SEQFAMILIA
 WHERE DESCCOMPLETA LIKE '%500G%'
       AND E.PESOLIQUIDO != 0.500
       AND E.QTDEMBALAGEM = 1
       AND X.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2

 ORDER BY 2
