-- Confere produtos com estoque e inativos para venda

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT * FROM (

SELECT NROEMPRESA, X.SEQPRODUTO, QTDESTQINICIAL - QTDSAIDA ESTOQUE,
       DECODE((SELECT DISTINCT(STATUSVENDA) FROM MRL_PRODEMPSEG Z WHERE Z.SEQPRODUTO = X.SEQPRODUTO AND Z.NROEMPRESA = X.NROEMPRESA AND NROSEGMENTO = 
                        (SELECT NROSEGMENTO FROM CONSINCO.MAX_EMPRESASEG Y WHERE Y.NROEMPRESA = X.NROEMPRESA AND Y.STATUS = 'A' AND Y.NROSEGMENTO NOT IN (1,5,8)) 
               AND Z.QTDEMBALAGEM = 1), 'A', 'ATIVO', 'INATIVO') STATUS_VENDA
  
  FROM CONSINCO.MRL_CUSTODIA X LEFT JOIN CONSINCO.MAP_PRODUTO M ON X.SEQPRODUTO = M.SEQPRODUTO
 WHERE DTAENTRADASAIDA = TRUNC(SYSDATE)
   AND NROEMPRESA < 100
   AND DESCCOMPLETA NOT LIKE '%INS%'
   AND DESCCOMPLETA NOT LIKE '%CONS%'
   AND DESCCOMPLETA NOT LIKE '%USO%'
       )
       
  WHERE ESTOQUE > 0 AND STATUS_VENDA = 'INATIVO' 
