ALTER SESSION SET current_schema = CONSINCO;

SELECT P.SEQPRODUTO PLU, P.DESCCOMPLETA DESCRICAO, CASE WHEN 
  (SELECT COUNT(NROEMPRESA)
  FROM GE_EMPRESA A WHERE NROEMPRESA  IN (
  SELECT DISTINCT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' 
  AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1)) = 0
  THEN 'Ativo em Todas as Lojas!' 
  WHEN 
  (SELECT COUNT(NROEMPRESA)
  FROM GE_EMPRESA A WHERE NROEMPRESA IN (
  SELECT DISTINCT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = 157773 AND B.STATUSVENDA = 'I' 
  AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1)) IN(64,67)  THEN 'Inativo em Todas as Lojas!' ELSE 'Inativo em algumas Lojas:' END STATUS, '-' i
  FROM MAP_PRODUTO P WHERE P.SEQPRODUTO IN (157773)

UNION ALL

SELECT NULL, NULL, NULL, '-' i FROM DUAL

UNION ALL

SELECT DISTINCT C.SEQPRODUTO PLU, C.DESCCOMPLETA DESCRICAO, D.FANTASIA EMPRESA, NULL FROM
   MAP_PRODUTO C 
   INNER JOIN MRL_PRODEMPSEG B ON C.SEQPRODUTO = B.SEQPRODUTO LEFT JOIN GE_EMPRESA D ON B.NROEMPRESA = D.NROEMPRESA
   
WHERE C.SEQPRODUTO IN (157773) AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1

ORDER BY 4,1,3

