ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT A.SEQPRODUTO PRODUTO_SKU, A.SEQFAMILIA PRODUTO_FAMILIA, B.SEQSIMILARIDADE, DESCCOMPLETA PRODUTO_DESCRICAO, CATEGORIA_NIVEL_1 CATEGORIA, COMPRADOR
  FROM MAP_PRODUTO A LEFT JOIN DIM_PRODSIMILAR@CONSINCODW B ON B.SEQPRODUTO = A.SEQPRODUTO
                     LEFT JOIN QLV_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = A.SEQFAMILIA    
                     LEFT JOIN MAP_FAMDIVISAO X ON A.SEQFAMILIA = X.SEQFAMILIA 
                     LEFT JOIN QLV_COMPRADOR@CONSINCODW Z ON Z.SEQCOMPRADOR = X.SEQCOMPRADOR 
                     
                     WHERE CATEGORIA_NIVEL_1 =:LS1    
                     
                     ORDER BY 2
                     
 
