ALTER SESSION SET current_schema = CONSINCO;

UPDATE GE_PESSOA A SET STATUS = 'A', USUALTERACAO = 'IMPORTACAO', A.DTAALTERACAO = SYSDATE    

WHERE --A.DTAALTERACAO, USUALTERACAO FROM GE_PESSOA A WHERE SEQPESSOA IN (1586520)

TO_CHAR(A.DTAALTERACAO, 'DD/MM/YYYY') = '20/12/2022' AND
USUALTERACAO = 'IMPORTACAO' AND A.NOMERAZAO NOT LIKE '%API%' AND STATUS = 'P' 
/* 

-- Demais cadastros além do dia 20/12 que tiveram os status alterados

AND SEQPESSOA IN (

SELECT SEQIDENTIFICA FROM GEV_PESSOALOGALTERACAO B 
 WHERE USUALTERACAO = 'IMPORTACAO' AND HISTORICO LIKE '%Status%' 
   AND DTAHORALTERACAO BETWEEN DATE '2022-11-27' AND DATE '2022-12-21') */
   ;
   COMMIT ;
   
