SELECT F.SEQFAMILIA, FAMILIA, TO_CHAR(E.QTDEMBALAGEM) QTD_EMB_FAM, E.INDGERASEPARACAO GERA_SEP, TO_CHAR(Z.PADRAOEMBCOMPRA) EMB_PAD_COMP
  FROM MAP_FAMILIA F INNER JOIN MAP_FAMEMBALAGEM E ON E.SEQFAMILIA = F.SEQFAMILIA
                     INNER JOIN MAP_FAMDIVISAO Z   ON Z.SEQFAMILIA = E.SEQFAMILIA
 WHERE NVL(E.INDGERASEPARACAO, 'N') = 'S'
   AND E.QTDEMBALAGEM > Z.PADRAOEMBCOMPRA
   
 ORDER BY 2
