-- Ticket 498419
-- Giuliano em 16/10/2025
-- Barra Prod com Cod nao vinculado que foi importada por 'gato' rs

SELECT DISTINCT (X.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                X.NUMERONF,
                X.NROEMPRESA,
                0   AS SEQAUXNFITEM,
                'L' AS BLOQAUTOR,
                91  AS CODINCONSISTENC,
               NULL MENSAGEM,
               V.SEQPRODUTO, 
               'Prod. '||V.DESCPRODUTO||' Nao cadastrado. '||DADOSXML

  FROM MLF_AUXNOTAFISCAL X INNER JOIN MRLV_NFEIMPORTACAOITEM V ON V.CHAVEACESSO = X.NFECHAVEACESSO AND V.NROEMPRESA = X.NROEMPRESA

WHERE 1=1
 AND CODGERALOPER IN (SELECT CGO_LIST FROM NAGV_BASE_CGO_FINALIDADE C WHERE TIPO = 'C')
 --AND X.DTAEMISSAO >= SYSDATE - 30
 AND NVL(V.SEQPRODUTO,0) = 0;
 
