ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT X.NROEMPRESA EMPRESA, M.SEQFAMILIA, X.SEQPRODUTO PLU, 
       CASE WHEN STATUSVENDA = 'I'        THEN 'Inativo no Segmento: '||Z.SEGMENTO       ELSE 'OK' END STATUS_VENDA,
       DECODE (STATUSCOMPRA, 'I', 'Inativo', 'S', 'Suspenso', 'OK')                                    STATUS_COMPRA,
       CASE WHEN PRECOBASENORMAL = 0      THEN 'Preço Zerado no Segmento: '||Z.SEGMENTO  ELSE 'OK' END PRECO

FROM MRL_PRODEMPSEG X LEFT JOIN MON_SEGMENTO Z ON X.NROSEGMENTO = Z.NROSEGMENTO
                      LEFT JOIN MON_EMPRESASEGMENTO Y ON Y.NROSEGMENTO = Z.NROSEGMENTO AND Y.NROEMPRESA = X.NROEMPRESA
                      LEFT JOIN MRL_PRODUTOEMPRESA  E ON X.NROEMPRESA  = E.NROEMPRESA  AND X.SEQPRODUTO = E.SEQPRODUTO
                      LEFT JOIN MAP_PRODUTO M ON X.SEQPRODUTO = M.SEQPRODUTO
                      
  WHERE X.SEQPRODUTO IN (
 SELECT SEQPRODUTO FROM MAP_PRODUTO WHERE SEQFAMILIA IN (
        SELECT DISTINCT (REGEXP_SUBSTR (VLRATUAL, '(\S*)')) FROM MAP_AUDITORIA X 
                  WHERE CAMPO = 'SEQFAMILIA' AND DESCCAMPO = 'SEQFAMILIA' AND DTAHORAUDITORIA BETWEEN DATE '2023-03-20' AND SYSDATE ))
    AND QTDEMBALAGEM = 1
    AND X.NROEMPRESA NOT IN (301,501,502,503,504,505,506,600,601,602,603,999)
    AND (STATUSVENDA = 'I' OR PRECOBASENORMAL = 0 OR STATUSCOMPRA IN ('I','S'))
    AND Y.ATIVO = 'S'

 GROUP BY X.NROEMPRESA, Z.SEGMENTO, X.SEQPRODUTO, M.SEQFAMILIA, STATUSVENDA, STATUSCOMPRA, PRECOBASENORMAL     
       
ORDER BY 2,1
