SELECT X.SEQPRODUTO,
       DESCCOMPLETA,
       NOMEPRODUTOECOMM,
       DECODE(NVL(X.INDINTEGRAECOMMERCE, 'N'), 'N', 'NAO', 'S', 'SIM') INTEGRA_ECOMM,
       'SIM' EXISTE_UTIL_VENDA,
       DECODE(STATUSCOMPRA, 'A', 'ATIVO', 'I', 'INATIVO', 'S', 'SUSPENSO') STATUSCOMPRA

  FROM MAP_PRODUTO X
 INNER JOIN MRL_PRODUTOEMPRESA Z
    ON Z.SEQPRODUTO = X.SEQPRODUTO
       AND NROEMPRESA = 8

 WHERE X.NOMEPRODUTOECOMM IS NULL
   AND EXISTS (SELECT 1
                 FROM MAP_PRODCODIGO C
                WHERE C.SEQPRODUTO = X.SEQPRODUTO
                  AND C.INDUTILVENDA = 'S')
