-- View para analise de produtos com inconsistencia no pedido de venda

ALTER SESSION SET current_schema = CONSINCO;

SELECT G.NROPEDVENDA NRO_PEDIDO, G.NROEMPRESA EMPRESA, G.SEQPRODUTO PLU, (SELECT DESCCOMPLETA FROM MAP_PRODUTO WHERE SEQPRODUTO = G.SEQPRODUTO) DESCRICAO,
       CASE WHEN G.SEQPRODUTO IN (SELECT DISTINCT A.SEQPRODUTO FROM MAP_PRODUTO A WHERE A.SEQPRODUTO = G.SEQPRODUTO AND A.SEQFAMILIA IN
                      (SELECT DISTINCT B.SEQFAMILIA FROM MAP_FAMDIVISAO B
                      LEFT JOIN CONSINCO.MAP_TRIBUTACAO C ON B.NROTRIBUTACAO = C.NROTRIBUTACAO

WHERE (UPPER(TRIBUTACAO) LIKE '%IMP%' OR UPPER(TRIBUTACAO) LIKE '%IM.D%')    AND CODORIGEMTRIB IN (0,4,5,6,7) AND UPPER(TRIBUTACAO) NOT LIKE '%LIMP%'
   OR UPPER(TRIBUTACAO) LIKE '%IMP.LIMP%' AND CODORIGEMTRIB IN (0,4,5,6,7))) THEN 'Tributação divergente da origem da mercadoria. Verificar com o Departamento Comercial'
      ELSE 'Ok' END SITUACAO
       
FROM mad_pedvendaitem G LEFT JOIN MAD_PEDVENDA H ON G.NROPEDVENDA = H.NROPEDVENDA
WHERE G.NROPEDVENDA IN (
SELECT DISTINCT G.NROPEDVENDA FROM mad_pedvendaitem G LEFT JOIN MAD_PEDVENDA H ON G.NROPEDVENDA = H.NROPEDVENDA
WHERE G.SEQPRODUTO IN 
  (SELECT DISTINCT A.SEQPRODUTO FROM MAP_PRODUTO A WHERE A.SEQPRODUTO = G.SEQPRODUTO AND A.SEQFAMILIA IN
                      (SELECT DISTINCT B.SEQFAMILIA FROM MAP_FAMDIVISAO B
                      LEFT JOIN CONSINCO.MAP_TRIBUTACAO C ON B.NROTRIBUTACAO = C.NROTRIBUTACAO

WHERE (UPPER(TRIBUTACAO) LIKE '%IMP%' OR UPPER(TRIBUTACAO) LIKE '%IM.D%')      AND CODORIGEMTRIB IN (0,4,5,6,7) AND UPPER(TRIBUTACAO) NOT LIKE '%LIMP%'
   OR UPPER(TRIBUTACAO) LIKE '%IMP.LIMP%' AND CODORIGEMTRIB IN (0,4,5,6,7))))

  AND G.NROPEDVENDA = :NR1
  AND G.NROEMPRESA  = :NR2;
