SELECT DISTINCT X.SEQPRODUTO PLU, X.DESCCOMPLETA, 
       1 QTD_UNI,
       TO_NUMBER(Z.QTDEMBALAGEM) QTD_EMB_PACK, Z.CODACESSO EAN_PACK,
       /*DECODE(S.STATUSVENDA, 'A', 'ATIVO', 'I', 'INATIVO') STATUS_VENDA_PACK,*/
       TO_CHAR(X.DTAHORINCLUSAO, 'DD/MM/YYYY') DTA_INCLUSAO
       
  FROM MAP_PRODCODIGO Z INNER JOIN MAP_PRODUTO X    ON X.SEQPRODUTO = Z.SEQPRODUTO
                                              
                                                   
                        INNER JOIN (SELECT SEQPRODUTO, CODACESSO, QTDEMBALAGEM FROM MAP_PRODCODIGO Z2 
                                     WHERE Z2.QTDEMBALAGEM = 1
                                       AND Z2.TIPCODIGO = 'E' 
                                       AND Z2.INDUTILVENDA = 'S') ZZ ON ZZ.SEQPRODUTO = Z.SEQPRODUTO
 WHERE Z.QTDEMBALAGEM > 1
   AND Z.INDUTILVENDA = 'S'
   AND TIPCODIGO = 'E'
   
ORDER BY 2,4
