SELECT A.SEQFORNECEDOR, B.NOMERAZAO, A.INDRECEBVENCVLRLIQ FROM MAF_FORNECEDOR A LEFT JOIN GE_PESSOA B ON A.SEQFORNECEDOR = B.SEQPESSOA

WHERE A.INDRECEBVENCVLRLIQ = 'S' -- Consulta Fornecedores com recebimento XML valor liquido
