 SELECT DISTINCT
        SEQIDENTIFICA, B.SEQPRODUTO, B.DESCCOMPLETA, B.DESCREDUZIDA, X.VLRANTERIOR, X.VLRATUAL, 
        DECODE(CAMPO, 'DESCCOMPLETA', 'COMPLETO', 'DESCREDUZIDA', 'REDUZIDA') CAMPO_ALT, X.DTAHORAUDITORIA
   FROM CONSINCO.MAP_AUDITORIA X INNER JOIN MAP_PRODUTO B ON SEQPRODUTO = X.SEQIDENTIFICA
   
  WHERE X.CAMPO IN ('DESCREDUZIDA', 'DESCCOMPLETA')
    AND TABELA  IN ('MAP_PRODUTO',  'MAP_FAMILIA')
    -- Apenas mais recentes
    AND X.DTAAUDITORIA > SYSDATE - 100
    -- Apenas os que houveram movimentações antes da alteracao
    AND EXISTS (SELECT 1 FROM CONSINCO.MRL_LANCTOESTOQUE Z
                        WHERE Z.SEQPRODUTO = X.SEQIDENTIFICA 
                          AND Z.DTAENTRADASAIDA < X.DTAAUDITORIA)
    -- Desc Completa != Vlr Atual ou Desc Reduzida != Vlr Atual
    AND REGEXP_SUBSTR(REPLACE(DECODE(CAMPO, 'DESCCOMPLETA', B.DESCCOMPLETA, 'DESCREDUZIDA', B.DESCREDUZIDA),'-',' '), '(\S*)(\s)',1,1) !=  REGEXP_SUBSTR(REPLACE(VLRATUAL,'-',' '), '(\S*)(\s)',1,1)

    ORDER BY DTAHORAUDITORIA DESC
