ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Ticket 504513

SELECT X.DESCCOMPLETA DESCRICAO_PRODUTO, X.SEQFAMILIA COD_FAMILIA, X.SEQPRODUTO COD_PRODUTO,
       MAX(NVL(A.PALETELASTRO,0)) ARM_LASTRO, MAX(NVL(A.PALETEALTURA,0)) ARM_ALTURA,
       MAX(NVL(E.PALETELASTRO,0)) END_LASTRO, MAX(NVL(E.PALETEALTURA,0)) END_ALTURA, 
       MAX(NVL(E.QTDEMBALAGEM,0)) EMB,
TO_CHAR(X.DTAHORINCLUSAO , 'DD/MM/YYYY') DTA_INCLUSAO
       
  FROM MAP_PRODUTO X INNER JOIN MRL_PRODEMPRESAWM   A ON A.SEQPRODUTO = X.SEQPRODUTO
                     INNER JOIN MAP_FAMDIVISAO      F ON F.SEQFAMILIA = X.SEQFAMILIA AND F.FINALIDADEFAMILIA = 'R'
                     INNER JOIN MLO_PRODESPENDERECO E ON E.SEQPRODUTO = X.SEQPRODUTO AND E.NROEMPRESA = A.NROEMPRESA
                     
 WHERE 1=1
   AND EXISTS (SELECT 1 FROM MRL_PRODUTOEMPRESA M WHERE STATUSCOMPRA = 'A' AND NROEMPRESA = 8 AND M.SEQPRODUTO = X.SEQPRODUTO)
   AND X.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2
   
 GROUP BY X.DESCCOMPLETA, X.SEQFAMILIA, X.SEQPRODUTO, TO_CHAR(X.DTAHORINCLUSAO , 'DD/MM/YYYY')
 ORDER BY 1

