-- Ticket 530147

SELECT P.SEQPRODUTO   PLU,
       P.DESCCOMPLETA DESC_PRODUTO,
       A.SEQFAMILIA,
       A.FAMILIA      DESC_FAMILIA,
       B.MARCA,
       B.SEQMARCA,
       LISTAGG(CODACESSO||' - '||EM.EMBALAGEM||' '||E.QTDEMBALAGEM, ', ') WITHIN GROUP (ORDER BY E.QTDEMBALAGEM, E.SEQPRODUTO) EAN
       
  FROM CONSINCO.MAP_FAMILIA A INNER JOIN CONSINCO.MAP_MARCA B ON A.SEQMARCA = B.SEQMARCA
                              INNER JOIN MAP_PRODUTO P ON P.SEQFAMILIA = A.SEQFAMILIA
                               LEFT JOIN MAP_PRODCODIGO E ON E.SEQPRODUTO = P.SEQPRODUTO AND E.TIPCODIGO = 'E'
                               LEFT JOIN CONSINCO.MAP_FAMEMBALAGEM EM ON EM.SEQFAMILIA = A.SEQFAMILIA AND EM.QTDEMBALAGEM = E.QTDEMBALAGEM
 WHERE B.MARCA = :LS1
GROUP BY P.SEQPRODUTO, P.DESCCOMPLETA, A.SEQFAMILIA, A.FAMILIA, B.MARCA, B.SEQMARCA
