-- Valida cod interno ja existente com 1 digito a menos

SELECT DISTINCT X.*, PP.SEQPRODUTO, PP.DESCCOMPLETA FROM (
SELECT 
    P.SEQPRODUTO,
    Z.CODACESSO AS COD_REDUZIDO,
    P.DESCCOMPLETA AS DESC_CODREDUZIDO,
    (SELECT MAX(X.CODACESSO)
     FROM MAP_PRODCODIGO X
     WHERE X.TIPCODIGO = 'B'
       AND SUBSTR(X.CODACESSO, 0, LENGTH(X.CODACESSO) - 1) = Z.CODACESSO
    ) AS COD_INTEIRO
FROM 
    MAP_PRODUTO P
INNER JOIN 
    MAP_PRODCODIGO Z
    ON Z.SEQPRODUTO = P.SEQPRODUTO
WHERE 
    Z.TIPCODIGO = 'B'
    AND EXISTS (
        SELECT 1
        FROM MAP_PRODCODIGO X
        WHERE X.TIPCODIGO = 'B'
          AND SUBSTR(X.CODACESSO, 0, LENGTH(X.CODACESSO) - 1) = Z.CODACESSO
    )) X INNER JOIN MAP_PRODCODIGO ZZ ON X.COD_INTEIRO = ZZ.CODACESSO
         INNER JOIN MAP_PRODUTO PP ON PP.SEQPRODUTO = ZZ.SEQPRODUTO;
 
