ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT SEQIDENTIFICA, TABELA, VLRANTERIOR, VLRATUAL, USUAUDITORIA, DTAAUDITORIA
  FROM MAP_AUDITORIA X
 WHERE 1 = 1
   AND USUAUDITORIA = 'APICADASTRO'
   AND IDENTIFICADOR LIKE '%EAN%'
   AND EXISTS (SELECT 1
          FROM MAP_PRODUTO A
         WHERE EXISTS (SELECT 2
                  FROM MAP_FAMILIA Z
                 WHERE PESAVEL = 'S'
                   AND Z.SEQFAMILIA = A.SEQFAMILIA)
           AND A.SEQPRODUTO = SEQIDENTIFICA)
   AND EXISTS (SELECT 3 FROM MAP_PRODCODIGO C WHERE C.TIPCODIGO = 'E' AND C.SEQPRODUTO = X.SEQIDENTIFICA)
 
 ORDER BY 6 DESC
