
SELECT DISTINCT D.APELIDO COMPRADOR,
       A.SEQPRODUTO PLU,
       B.DESCCOMPLETA,
       C.FANTASIA EMP,
       A.MOTIVOAPROVREPROV,
       DECODE(A.APROVADOREPROVADO, 'A','Aprovado', 'R', 'Reprovado', 'Pendente') SITUACAO,
       A.MOTIVOSOLICITAINATIVACAOCOMPRA,
       TO_CHAR(A.DTAHORASOLICITACAO, 'DD/MM/YYYY') DTA_SOLICITACAO,
       A.USUSOLICITACAO, 
       TO_CHAR(A.DTAHORAAPROVREPROV, 'DD/MM/YYYY') DTA_APROVREPROV, A.USUAPROVREPROV USUAPROVREPROV
  FROM MRL_ANALISEINATIVACAOCOMPRA A,
       MAP_PRODUTO                 B,
       MAX_EMPRESA                 C,
       MAX_COMPRADOR               D

 WHERE A.SEQPRODUTO = B.SEQPRODUTO
   AND A.NROEMPRESA = C.NROEMPRESA
   AND A.SEQCOMPRADOR = D.SEQCOMPRADOR
   AND TRUNC(A.DTAHORASOLICITACAO) BETWEEN :DT1 AND :DT2
   AND DECODE(A.APROVADOREPROVADO, 'A','Aprovado', 'R', 'Reprovado', 'Pendente') IN (#LS1)
       
       ORDER BY 3,5

