SELECT CASE WHEN X.NROEMPRESA < 100 THEN 'LJ'||LPAD(X.NROEMPRESA,2,0) ELSE 'CD'||X.NROEMPRESA END
       EMPRESA, X.FANTASIA, X.RAZAOSOCIAL, X.ENDERECO, Z.ENDERECONRO, X.BAIRRO, X.CEP, X.CIDADE, ESTADO, 
       X.UF,LPAD(X.NROCGC,12,0)||LPAD(X.DIGCGC,2,0) CNPJ, INSCRICAOESTADUAL, G.FONEDDD1 DDD, G.FONENRO1 FONENRO, G.EMAIL
       
  FROM CONSINCO.MAX_EMPRESA X INNER JOIN CONSINCO.GE_EMPRESA Z ON X.NROEMPRESA = Z.NROEMPRESA
                              INNER JOIN CONSINCO.GE_PESSOA G ON G.SEQPESSOA = X.NROEMPRESA
 WHERE 1=1       
   AND X.NROEMPRESA NOT IN (999,500)

       ORDER BY X.NROEMPRESA
       
