ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT SEQPESSOA, STATUS, NOMERAZAO, DTAHORAINCLUSAO
  FROM CONSINCO.GE_PESSOA X
 WHERE EXISTS (
        SELECT 1
          FROM MAP_FAMFORNEC Z
         WHERE EXISTS (
                SELECT 2
                  FROM MAP_FAMDIVISAO F
                 WHERE F.SEQCOMPRADOR = 13 -- FLV
                   AND F.SEQFAMILIA = Z.SEQFAMILIA
         AND Z.SEQFORNECEDOR = X.SEQPESSOA))
         
         AND X.DTAHORAINCLUSAO BETWEEN DATE '2023-01-01' AND DATE '2023-12-31'
         
ORDER BY 4 

-- Or

WITH CTE_FAM_FLV AS (SELECT DISTINCT SEQFORNECEDOR
                       FROM MAP_FAMFORNEC Z
                      WHERE EXISTS (SELECT 2
                                      FROM MAP_FAMDIVISAO F
                                     WHERE F.SEQCOMPRADOR = 13
                                       AND F.SEQFAMILIA = Z.SEQFAMILIA))

SELECT SEQPESSOA, STATUS, NOMERAZAO, DTAHORAINCLUSAO
  FROM CONSINCO.GE_PESSOA X INNER JOIN CTE_FAM_FLV Y ON X.SEQPESSOA = Y.SEQFORNECEDOR
  
 WHERE X.DTAHORAINCLUSAO BETWEEN DATE '2023-01-01' AND DATE '2023-12-31'
         
ORDER BY 4 
