ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT X.SEQPRODUTO PLU, DESCCOMPLETA, X.SEQFAMILIA COD_FAMILIA, FAMILIA, 
       X.USUARIOINCLUSAO, TO_CHAR(X.DTAHORINCLUSAO, 'DD/MM/YYYY') DTA_INCLUSAO

  FROM MAP_PRODUTO X INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = X.SEQFAMILIA
                     
  WHERE NVL(F.PMTMULTIPLICACAO, 'N') != 'S'
    AND X.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2
