SELECT F.SEQFAMILIA, FAMILIA, TO_CHAR(E.QTDEMBALAGEM) QTD_EMB_FAM, E.INDGERASEPARACAO GERA_SEP, TO_CHAR(Z.PADRAOEMBCOMPRA) EMB_PAD_COMP, TO_CHAR(F.DTAHORINCLUSAO, 'DD/MM/YYYY') DTAINCLUSAO, F.USUARIOINCLUSAO
  FROM MAP_FAMILIA F INNER JOIN MAP_FAMEMBALAGEM E ON E.SEQFAMILIA = F.SEQFAMILIA
                     INNER JOIN MAP_FAMDIVISAO Z   ON Z.SEQFAMILIA = E.SEQFAMILIA
 WHERE NVL(E.INDGERASEPARACAO, 'N') = 'S'
   AND E.QTDEMBALAGEM > Z.PADRAOEMBCOMPRA
   AND TRUNC(F.DTAHORINCLUSAO) BETWEEN :DT1 AND :DT2
  
 ORDER BY 2
