SELECT DISTINCT X.SEQPRODUTO PLU, DESCCOMPLETA, X.SEQFAMILIA COD_FAMILIA, FAMILIA, 
       X.USUARIOINCLUSAO, TO_CHAR(X.DTAHORINCLUSAO, 'DD/MM/YYYY') DTA_INCLUSAO,
       CASE WHEN (NVL(F.INDMERCENQUADST, 'X') != 'S' AND NVL(F.INDUSADADOSREGCGO, 'X') != 'S') THEN 'Sem flag Controle Estq ST e Regime CGO' 
            WHEN (NVL(F.INDMERCENQUADST, 'X') != 'S' AND NVL(F.INDUSADADOSREGCGO, 'X') = 'S')  THEN 'Sem flag Controle Estq ST'
            WHEN (NVL(F.INDMERCENQUADST, 'X') = 'S'  AND NVL(F.INDUSADADOSREGCGO, 'X') != 'S') THEN 'Sem flag Usa Dados do Regime do CGO..' END PROBLEMA

  FROM MAP_PRODUTO X INNER JOIN CONSINCO.MAP_FAMDIVISAO F ON F.SEQFAMILIA = X.SEQFAMILIA 
                     INNER JOIN CONSINCO.MAP_FAMILIA Z ON X.SEQFAMILIA =Z.SEQFAMILIA

 WHERE 1=1 
   AND (NVL(F.INDMERCENQUADST, 'X') != 'S'
    OR NVL(F.INDUSADADOSREGCGO, 'X') != 'S')
    
   AND X.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2

ORDER BY 2
