SELECT A.SEQPRODUTO PLU, DESCCOMPLETA, A.SEQFAMILIA COD_FAMILIA, COMPRADOR, DESCATRIBUTO ATRIBUTO
       
  FROM MAP_PRODUTO A INNER JOIN MAP_FAMDIVISAO C ON C.SEQFAMILIA = A.SEQFAMILIA
                     INNER JOIN MAX_COMPRADOR CC ON CC.SEQCOMPRADOR = C.SEQCOMPRADOR
                     LEFT JOIN MAP_FAMATRIBUTO D ON D.SEQFAMILIA = A.SEQFAMILIA
                     
WHERE CC.COMPRADOR = 'IMPORTADOS'
   OR D.DESCATRIBUTO = 'Produto Importado'
   
ORDER BY 2
