ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT SEQIDENTIFICA SEQFAMILIA, FAMILIA, PESAVEL, OSUSER, TO_CHAR(DTAHORAUDITORIA, 'DD/MM/YYYY') DTAAUDITORIA
  FROM MAP_AUDITORIA X LEFT JOIN MAP_FAMILIA Z ON X.SEQIDENTIFICA = Z.SEQFAMILIA
 WHERE ORIGEM = 'FAMILIA' AND X.OSUSER = 'thiago.antony'
