ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DESCCOMPLETA DESCRICAO, B.CODACESSO EAN, C.CODACESSO DUN, A.SEQPRODUTO PLU, E.COMPRADOR
       
  FROM MAP_PRODUTO A LEFT JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO AND B.TIPCODIGO = 'E'
                     LEFT JOIN MAP_PRODCODIGO C ON A.SEQPRODUTO = C.SEQPRODUTO AND C.TIPCODIGO = 'D'
                     LEFT JOIN MAP_FAMDIVISAO D ON D.SEQFAMILIA = A.SEQFAMILIA
                     LEFT JOIN MAX_COMPRADOR  E ON E.SEQCOMPRADOR = D.SEQCOMPRADOR
                     
                     WHERE E.COMPRADOR IN (#LS1)
                     
                     ORDER BY A.SEQPRODUTO 
