SELECT DISTINCT (A.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                A.NUMERONF,
                A.NROEMPRESA,
                B.SEQAUXNFITEM AS SEQAUXNFITEM,
                'L' AS BLOQAUTOR,
                71111115 AS CODINCONSISTENC,
                'Produto Cod.: '||B.SEQPRODUTO||' - Não possui Cod, Fornecedor/Referencia Vinculado na Consinco - Cod no XML: '||L.M014_CD_PRODUTO MENSAGEM
  FROM CONSINCO.MLF_AUXNOTAFISCAL A INNER JOIN CONSINCO.MLF_AUXNFITEM B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                    INNER JOIN TMP_M000_NF K ON (K.M000_NR_CHAVE_ACESSO = A.NFECHAVEACESSO)
                                    INNER JOIN TMP_M014_ITEM L ON (L.M000_ID_NF = K.M000_ID_NF AND L.M014_NR_ITEM = B.SEQITEMNFXML)
                                     LEFT JOIN MAP_PRODCODIGO X2 ON X2.SEQPRODUTO = B.SEQPRODUTO AND X2.TIPCODIGO = 'E' AND LPAD(X2.CODACESSO,13,0) = LPAD(NVL(L.M014_CD_EAN_TRIB,0),13,0)

WHERE NOT EXISTS (SELECT 1 FROM MAP_PRODCODIGO X 
                   WHERE X.SEQPRODUTO = B.SEQPRODUTO 
                   AND X.CODACESSO = L.M014_CD_PRODUTO
                   AND X.TIPCODIGO = 'F')
           
        
--AND A.CODGERALOPER = 1
  AND A.SEQPESSOA > 999
  AND DTAEMISSAO > SYSDATE - 50
