SELECT * FROM (

SELECT DESCCOMPLETA DESCRICAO, B.CODACESSO EAN, C.CODACESSO DUN, A.SEQPRODUTO PLU, E.COMPRADOR, 
                CASE WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSCOMPRA = 'A') THEN 'ATIVO' 
                WHEN A.SEQPRODUTO      IN (SELECT Z.SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSCOMPRA = 'S') THEN 'SUSPENSO'
                ELSE 'INATIVO' END STATUS_COMPRA,
                CASE WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSVENDA = 'A')  THEN 'ATIVO' 
                ELSE 'INATIVO' END STATUS_VENDA
       
  FROM MAP_PRODUTO A LEFT JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO AND B.TIPCODIGO = 'E'
                     LEFT JOIN MAP_PRODCODIGO C ON A.SEQPRODUTO = C.SEQPRODUTO AND C.TIPCODIGO = 'D'
                     LEFT JOIN MAP_FAMDIVISAO D ON D.SEQFAMILIA = A.SEQFAMILIA
                     LEFT JOIN MAX_COMPRADOR  E ON E.SEQCOMPRADOR = D.SEQCOMPRADOR
                     
                     WHERE E.COMPRADOR IN ('FABIANO')
                       
                     ORDER BY A.SEQPRODUTO 
                     )
                     
          WHERE STATUS_VENDA  LIKE (DECODE(:LS2, '','%%',:LS2))
            AND STATUS_COMPRA LIKE (DECODE(:LS3,'', '%%',:LS3))

