SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       DISTINCT G.SEQPESSOA||' - '||NOMERAZAO FORNEC, B.SEQPRODUTO PLU, E.SEQFAMILIA,
                C.DESCREDUZIDA,
                L.M014_DM_ORIG_ICMS XML,
                D.CODORIGEMTRIB C5,
               (SELECT COUNT(SEQPRODUTO) FROM MAP_PRODUTO Z WHERE Z.SEQFAMILIA = E.SEQFAMILIA) QTD_PROD_FAM,
               CASE WHEN (SELECT COUNT(SEQPRODUTO) FROM MAP_PRODUTO Z WHERE Z.SEQFAMILIA = E.SEQFAMILIA) =
                          (SELECT COUNT(SEQPRODUTO) FROM MAP_PRODUTO Z WHERE Z.SEQFAMILIA = E.SEQFAMILIA AND Z.SEQPRODUTO IN(
                          
                          SELECT DISTINCT B.SEQPRODUTO
                            FROM CONSINCO.MLF_AUXNOTAFISCAL A INNER JOIN CONSINCO.MLF_AUXNFITEM B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                                              INNER JOIN CONSINCO.MAP_PRODUTO C ON B.SEQPRODUTO = C.SEQPRODUTO
                                                              INNER JOIN CONSINCO.MAP_FAMILIA E ON E.SEQFAMILIA = C.SEQFAMILIA
                                                              INNER JOIN CONSINCO.MAP_FAMDIVISAO D ON D.SEQFAMILIA = E.SEQFAMILIA
                                                              INNER JOIN TMP_M000_NF K ON (K.M000_NR_CHAVE_ACESSO = A.NFECHAVEACESSO)
                                                              INNER JOIN TMP_M014_ITEM L ON (L.M000_ID_NF = K.M000_ID_NF AND L.M014_NR_ITEM = B.SEQITEMNFXML)
                                                              INNER JOIN GE_PESSOA G ON G.SEQPESSOA = A.SEQPESSOA
                                    
                              WHERE NVL(L.M014_DM_ORIG_ICMS,1) != NVL(D.CODORIGEMTRIB,2)
                                AND NVL(D.FINALIDADEFAMILIA, 'X') NOT IN ('U','A', 'O')
                                AND A.SEQPESSOA > 999
                                AND A.DTAEMISSAO > SYSDATE - 50
                                AND DECODE(NVL(L.M014_DM_ORIG_ICMS,1), 5, 'X', 0, 'X', 1) 
                                !=  DECODE(NVL(D.CODORIGEMTRIB,2)    , 5, 'X', 0, 'X', 2) 
                                AND NOT EXISTS (SELECT 1 FROM DIM_CATEGORIA@CONSINCODW DC WHERE DC.SEQFAMILIA = C.SEQFAMILIA AND DC.CATEGORIAN1 = 'HORTIFRUTI')
                                 OR EXISTS (SELECT 1 FROM DIM_CATEGORIA@CONSINCODW DC WHERE DC.SEQFAMILIA = C.SEQFAMILIA AND DC.CATEGORIAN1 = 'HORTIFRUTI')
                                AND A.SEQPESSOA > 999
                                AND A.DTAEMISSAO > SYSDATE - 50
                                AND(NVL(L.M014_DM_ORIG_ICMS,1) IN (2,3,8)   AND NVL(D.CODORIGEMTRIB,2) IN (0,4,5,7)
                                 OR NVL(L.M014_DM_ORIG_ICMS,1) IN (0,4,5,7) AND NVL(D.CODORIGEMTRIB,2) IN (2,3,8))
                                AND NVL(D.FINALIDADEFAMILIA, 'X') NOT IN ('U','A', 'O')
                                  
                          ))
                     THEN 'Alteração de Cod Origem da Familia' ELSE 'Separação de Produtos na Família' END TIPO_ALT,
                TO_CHAR(MIN(A.DTAEMISSAO), 'DD/MM/YYYY')DTAEMISSAO_ULTNOTA,
LISTAGG(NUMERONF || ' - ' || NROEMPRESA, ', ') WITHIN GROUP (ORDER BY NUMERONF) NOTAS_EMP

  FROM CONSINCO.MLF_AUXNOTAFISCAL A INNER JOIN CONSINCO.MLF_AUXNFITEM B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                    INNER JOIN CONSINCO.MAP_PRODUTO C ON B.SEQPRODUTO = C.SEQPRODUTO
                                    INNER JOIN CONSINCO.MAP_FAMILIA E ON E.SEQFAMILIA = C.SEQFAMILIA
                                    INNER JOIN CONSINCO.MAP_FAMDIVISAO D ON D.SEQFAMILIA = E.SEQFAMILIA
                                    INNER JOIN TMP_M000_NF K ON (K.M000_NR_CHAVE_ACESSO = A.NFECHAVEACESSO)
                                    INNER JOIN TMP_M014_ITEM L ON (L.M000_ID_NF = K.M000_ID_NF AND L.M014_NR_ITEM = B.SEQITEMNFXML)
                                    INNER JOIN GE_PESSOA G ON G.SEQPESSOA = A.SEQPESSOA
                                    
WHERE NVL(L.M014_DM_ORIG_ICMS,1) != NVL(D.CODORIGEMTRIB,2)
  AND NVL(D.FINALIDADEFAMILIA, 'X') NOT IN ('U','A', 'O')
  AND A.SEQPESSOA > 999
  AND A.DTAEMISSAO > SYSDATE - 50
  AND DECODE(NVL(L.M014_DM_ORIG_ICMS,1), 5, 'X', 0, 'X', 1) 
  !=  DECODE(NVL(D.CODORIGEMTRIB,2)    , 5, 'X', 0, 'X', 2) 
  AND NOT EXISTS (SELECT 1 FROM DIM_CATEGORIA@CONSINCODW DC WHERE DC.SEQFAMILIA = C.SEQFAMILIA AND DC.CATEGORIAN1 = 'HORTIFRUTI')
   OR EXISTS (SELECT 1 FROM DIM_CATEGORIA@CONSINCODW DC WHERE DC.SEQFAMILIA = C.SEQFAMILIA AND DC.CATEGORIAN1 = 'HORTIFRUTI')
  AND A.SEQPESSOA > 999
  AND A.DTAEMISSAO > SYSDATE - 50
  AND(NVL(L.M014_DM_ORIG_ICMS,1) IN (2,3,8)   AND NVL(D.CODORIGEMTRIB,2) IN (0,4,5,7)
   OR NVL(L.M014_DM_ORIG_ICMS,1) IN (0,4,5,7) AND NVL(D.CODORIGEMTRIB,2) IN (2,3,8))
  AND NVL(D.FINALIDADEFAMILIA, 'X') NOT IN ('U','A', 'O')
   
   
   
   GROUP BY B.SEQPRODUTO, E.SEQFAMILIA, DESCREDUZIDA, L.M014_DM_ORIG_ICMS ,
                D.CODORIGEMTRIB, G.SEQPESSOA||' - '||NOMERAZAO
   ORDER BY 3
