CREATE TABLE CONSINCO.MAP_FAMFORNEC_BACKUP AS

SELECT * FROM CONSINCO.MAP_FAMFORNEC;

UPDATE CONSINCO.MAP_FAMFORNEC A SET A.INDCONSIDTIPFORNCGO = 'S'
                           WHERE NVL(INDCONSIDTIPFORNCGO, 'N') = 'N'
                           --AND INDREPLICACAO = 'S' 
                           AND LENGTH(SEQFAMILIA) < 13
                           ;--AND ROWNUM < 2;

COMMIT;

SELECT COUNT(1) FROM CONSINCO.MAP_FAMFORNEC A WHERE NVL(INDCONSIDTIPFORNCGO, 'N') = 'N'
