ALTER SESSION SET current_schema = CONSINCO;

SELECT P.SEQPRODUTO PLU, P.DESCCOMPLETA DESCRICAO, CASE WHEN 
  (SELECT COUNT(NROEMPRESA)
  FROM GE_EMPRESA A WHERE NROEMPRESA  IN (
  SELECT DISTINCT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' 
  AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA !=301)) = 0
  THEN 'Ativo em Todas as Lojas!' 
  WHEN P.SEQPRODUTO NOT IN (SELECT DISTINCT SEQPRODUTO FROM MRL_PRODEMPSEG WHERE STATUSVENDA = 'A')  THEN 'Inativo em Todas as Lojas!' ELSE 'Inativo nas Lojas:' END STATUS,
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 1) IS NULL THEN NULL ELSE 1||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 2) IS NULL THEN NULL ELSE 2||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 3) IS NULL THEN NULL ELSE 3||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 4) IS NULL THEN NULL ELSE 4||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 6) IS NULL THEN NULL ELSE 6||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 7) IS NULL THEN NULL ELSE 7||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 8) IS NULL THEN NULL ELSE 8||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 9) IS NULL THEN NULL ELSE 9||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 10) IS NULL THEN NULL ELSE 10||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 11) IS NULL THEN NULL ELSE 11||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 12) IS NULL THEN NULL ELSE 12||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 13) IS NULL THEN NULL ELSE 13||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 14) IS NULL THEN NULL ELSE 14||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 15) IS NULL THEN NULL ELSE 15||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 16) IS NULL THEN NULL ELSE 16||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 17) IS NULL THEN NULL ELSE 17||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 18) IS NULL THEN NULL ELSE 18||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 19) IS NULL THEN NULL ELSE 19||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 20) IS NULL THEN NULL ELSE 20||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 21) IS NULL THEN NULL ELSE 21||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 22) IS NULL THEN NULL ELSE 22||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 23) IS NULL THEN NULL ELSE 23||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 24) IS NULL THEN NULL ELSE 24||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 25) IS NULL THEN NULL ELSE 25||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 26) IS NULL THEN NULL ELSE 26||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 27) IS NULL THEN NULL ELSE 27||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 28) IS NULL THEN NULL ELSE 28||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 29) IS NULL THEN NULL ELSE 29||',' END||      
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 30) IS NULL THEN NULL ELSE 30||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 31) IS NULL THEN NULL ELSE 31||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 32) IS NULL THEN NULL ELSE 32||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 33) IS NULL THEN NULL ELSE 33||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 34) IS NULL THEN NULL ELSE 34||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 35) IS NULL THEN NULL ELSE 35||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 36) IS NULL THEN NULL ELSE 36||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 37) IS NULL THEN NULL ELSE 37||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 38) IS NULL THEN NULL ELSE 38||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 39) IS NULL THEN NULL ELSE 39||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 40) IS NULL THEN NULL ELSE 40||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 41) IS NULL THEN NULL ELSE 41||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 42) IS NULL THEN NULL ELSE 42||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 43) IS NULL THEN NULL ELSE 43||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 44) IS NULL THEN NULL ELSE 44||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 45) IS NULL THEN NULL ELSE 45||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 46) IS NULL THEN NULL ELSE 46||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 47) IS NULL THEN NULL ELSE 47||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 48) IS NULL THEN NULL ELSE 48||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 49) IS NULL THEN NULL ELSE 49||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 50) IS NULL THEN NULL ELSE 50||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 51) IS NULL THEN NULL ELSE 51||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 52) IS NULL THEN NULL ELSE 52||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 53) IS NULL THEN NULL ELSE 53||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 54) IS NULL THEN NULL ELSE 54||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 55) IS NULL THEN NULL ELSE 55||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 500) IS NULL THEN NULL ELSE 500||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 501) IS NULL THEN NULL ELSE 501||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 502) IS NULL THEN NULL ELSE 502||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 503) IS NULL THEN NULL ELSE 503||',' END||    
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 504) IS NULL THEN NULL ELSE 504||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 505) IS NULL THEN NULL ELSE 505||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 600) IS NULL THEN NULL ELSE 600||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 601) IS NULL THEN NULL ELSE 601||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 602) IS NULL THEN NULL ELSE 602||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 603) IS NULL THEN NULL ELSE 603||',' END||
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 300) IS NULL THEN NULL ELSE 300||',' END||
 /* CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 301) IS NULL THEN NULL ELSE 301||',' END||*/
  CASE WHEN (SELECT NROEMPRESA FROM MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = P.SEQPRODUTO AND B.STATUSVENDA = 'I' AND B.NROSEGMENTO != 5 AND QTDEMBALAGEM = 1 AND NROEMPRESA = 999) IS NULL THEN NULL ELSE 999 END
  
  Lojas_Inativas
  FROM MAP_PRODUTO P WHERE TO_DATE(P.DTAHORINCLUSAO, 'DD-MM-YY') :DT1 AND :DT2 
  AND SEQPRODUTO NOT IN (SELECT DISTINCT SEQPRODUTO FROM MRL_PRODEMPSEG WHERE SEQPRODUTO = P.SEQPRODUTO AND STATUSVENDA = 'A')
  
ORDER BY 2
