/*SELECT SEQIMPORTACAO, A.NRODOCUMENTO, A.DESCFORNECEDOR, A.DTAVENCIMENTO, A.VALORCOMDESCONTO, A.VALORABATIMENTO, A.SEQTITULO, A.NROCNPJCPF||A.DIGCNPJCPF CNPJ
FROM CONSINCO.FIV_DDATITULOSBUSCA A 
WHERE A.SEQTITULO IN (SELECT SEQTITULO FROM CONSINCO.FI_TITULO B WHERE B.NRODOCUMENTO = 200928 AND NROEMPRESA = 51 ) 

SELECT SEQIMPORTACAO, A.NRODOCUMENTO, A.DESCFORNECEDOR, A.DTAVENCIMENTO, A.VALORCOMDESCONTO, A.VALORDESCONTO1 DESCONTO, 
       A.VALORABATIMENTO, A.SEQTITULO, A.NROCNPJCPF||A.DIGCNPJCPF CNPJ

FROM CONSINCO.FIV_DDATITULOSBUSCA A 
WHERE A.DTAVENCIMENTO > SYSDATE AND  DESCFORNECEDOR LIKE '%SVP%' AND NRODOCUMENTO LIKE '%1684591%' */

SELECT B.DESCCOMPLETA, CODACESSO FROM CONSINCO.MAP_PRODCODIGO A LEFT JOIN MAP_PRODUTO B ON A.SEQPRODUTO = B.SEQPRODUTO 
       LEFT JOIN CONSINCO.ETLV_CATEGORIA D ON B.SEQFAMILIA = D.SEQFAMILIA
WHERE DESCCOMPLETA NOT LIKE '%CARNE%' AND TIPCODIGO = 'B' AND A.SEQPRODUTO IN (SELECT DISTINCT SEQPRODUTO FROM CONSINCO.MRL_PRODEMPSEG WHERE STATUSVENDA = 'A'
      AND NROEMPRESA = 54 AND NROSEGMENTO = 7)
      AND D.CATEGORIACOMPLETA LIKE '%FRIOS%'
      AND DESCCOMPLETA NOT LIKE '%1%'
      AND DESCCOMPLETA NOT LIKE '%45%'
     ORDER BY 1

-- Por Departamento


SELECT DISTINCT A.SEQPRODUTO, CODACESSO, C.DESCCOMPLETA fROM CONSINCO.MRL_PRODUTOEMPRESA  A LEFT JOIN CONSINCO.MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
                                                                   LEFT JOIN CONSINCO.MAP_PRODUTO C ON A.SEQPRODUTO = C.SEQPRODUTO
WHERE A.NROEMPRESA=54 AND NRODEPARTAMENTO = 6 AND B.TIPCODIGO = 'B' AND C.DESCCOMPLETA NOT LIKE '%1%'
ORDER BY 3

-- Geral

SELECT DISTINCT A.SEQPRODUTO PLU, B.DESCCOMPLETA, CODACESSO CODIGO_BALANCA, D.categoriaN1 CATEGORIA
FROM CONSINCO.MAP_PRODCODIGO A 
       LEFT JOIN MAP_PRODUTO B ON A.SEQPRODUTO = B.SEQPRODUTO 
       LEFT JOIN CONSINCO.ETLV_CATEGORIA D ON B.SEQFAMILIA = D.SEQFAMILIA
       LEFT JOIN CONSINCO.MAP_FAMILIA F ON B.SEQFAMILIA = F.SEQFAMILIA
WHERE TIPCODIGO = 'B' 
      AND F.PESAVEL = 'S'
      AND DESCCOMPLETA NOT LIKE '%1%'
      AND DESCCOMPLETA NOT LIKE '%45%'
      AND DESCCOMPLETA NOT LIKE 'ZZ%'
      AND DESCCOMPLETA NOT LIKE '%EXCLUIR%'
     ORDER BY 1
