ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT TO_CHAR(CD) CD,
       TO_CHAR(NF) NF,
       TO_CHAR(NRO_CARGA) CARGA,
       DTG DATA_GERACAO,
       USUGERACAO USUARIO_GEROU,
       DTL DATA_LIBERACAO, 
       USULIBERACAO USUARIO_LIBEROU,
       TO_CHAR(X_DIAS) QTD_DIAS_DIF
       
  FROM (

 SELECT X.NROEMPRESA CD, TO_CHAR(A.NUMERONF) NF, X.NROCARGARECEB NRO_CARGA, 
        TO_CHAR(X.DTAHORGERACAO  , 'DD/MM/YYYY HH24:MI') DTG, X.USUGERACAO, 
        TO_CHAR(X.DTAHORLIBERACAO, 'DD/MM/YYYY HH24:MI') DTL, X.USULIBERACAO,
        TO_CHAR(NVL(TRUNC(X.DTAHORLIBERACAO), TRUNC(SYSDATE)) - TRUNC(X.DTAHORGERACAO)) X_DIAS
 
   FROM CONSINCO.MAD_CARGARECEB X INNER JOIN MLF_NOTAFISCAL A ON A.NROINTERNORECEB = X.NROCARGARECEB
   WHERE 1=1
     AND TRUNC(X.DTAHORGERACAO) != NVL(TRUNC(X.DTAHORLIBERACAO), DATE '1996-12-10')
     AND X.USUCANCELAMENTO IS NULL
     AND TRUNC(X.DTAHORGERACAO) = TRUNC(SYSDATE)
     AND X.NROEMPRESA IN (501,502,503,506,507,508)
      
UNION

 SELECT X.NROEMPRESA CD, TO_CHAR(A.NUMERONF) NF, X.NROCARGARECEB NRO_CARGA, 
        TO_CHAR(X.DTAHORGERACAO  , 'DD/MM/YYYY HH24:MI') DTG, X.USUGERACAO, 
        TO_CHAR(X.DTAHORLIBERACAO, 'DD/MM/YYYY HH24:MI') DTL, X.USULIBERACAO,
        TO_CHAR(NVL(TRUNC(X.DTAHORLIBERACAO), TRUNC(SYSDATE)) - TRUNC(X.DTAHORGERACAO)) X_DIAS
 
   FROM CONSINCO.MAD_CARGARECEB X INNER JOIN MLF_AUXNOTAFISCAL A ON A.NROINTERNORECEB = X.NROCARGARECEB
   WHERE 1=1
     AND TRUNC(X.DTAHORGERACAO) != NVL(TRUNC(X.DTAHORLIBERACAO), DATE '1996-12-10')
     AND X.USUCANCELAMENTO IS NULL
     AND TRUNC(X.DTAHORGERACAO) = :DT1
     AND X.NROEMPRESA IN (501,502,503,506,507,508)
     
 ORDER BY 3)
 
 UNION ALL
 
 SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL
 
 UNION ALL
 
 SELECT * FROM (
SELECT TO_CHAR(CD) CD, 'Subtotal: ' I, TO_CHAR(COUNT(NUMERONF)) QTD_NFS, NULL DTAHORGERACAO, NULL USUGERACAO, NULL DTAHORLIBERACAO, NULL USULIBERACAO, NULL X_DIAS

FROM (

SELECT X.NROEMPRESA CD, A.NUMERONF, X.NROCARGARECEB NRO_CARGA, X.DTAHORGERACAO, X.USUGERACAO, X.DTAHORLIBERACAO, X.USULIBERACAO,
        TRUNC(X.DTAHORLIBERACAO) - TRUNC(X.DTAHORGERACAO) X_DIAS
 
   FROM CONSINCO.MAD_CARGARECEB X INNER JOIN MLF_NOTAFISCAL A ON A.NROINTERNORECEB = X.NROCARGARECEB
   WHERE 1=1
     AND TRUNC(X.DTAHORGERACAO) != NVL(TRUNC(X.DTAHORLIBERACAO), DATE '1996-12-10')
     AND X.USUCANCELAMENTO IS NULL
     AND TRUNC(X.DTAHORGERACAO) = :DT1
     AND X.NROEMPRESA IN (501,502,503,506,507,508)
      
UNION

 SELECT X.NROEMPRESA CD, A.NUMERONF, X.NROCARGARECEB NRO_CARGA, X.DTAHORGERACAO, X.USUGERACAO, X.DTAHORLIBERACAO, X.USULIBERACAO,
        TRUNC(X.DTAHORLIBERACAO) - TRUNC(X.DTAHORGERACAO) X_DIAS_PARADA
 
   FROM CONSINCO.MAD_CARGARECEB X INNER JOIN MLF_AUXNOTAFISCAL A ON A.NROINTERNORECEB = X.NROCARGARECEB
   WHERE 1=1
     AND TRUNC(X.DTAHORGERACAO) != NVL(TRUNC(X.DTAHORLIBERACAO), DATE '1996-12-10')
     AND X.USUCANCELAMENTO IS NULL
     AND TRUNC(X.DTAHORGERACAO) = :DT1
     AND X.NROEMPRESA IN (501,502,503,506,507,508)
     )
     
     GROUP BY CD
     ORDER BY CD)
     
     UNION ALL
 
 SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL
 
 UNION ALL
 
 SELECT * FROM (
SELECT NULL CD, 'Total: ' I, TO_CHAR(COUNT(NUMERONF)) QTD_NFS, NULL DTAHORGERACAO, NULL USUGERACAO, NULL DTAHORLIBERACAO, NULL USULIBERACAO, NULL X_DIAS

FROM (

SELECT X.NROEMPRESA CD, A.NUMERONF, X.NROCARGARECEB NRO_CARGA, X.DTAHORGERACAO, X.USUGERACAO, X.DTAHORLIBERACAO, X.USULIBERACAO,
        TRUNC(X.DTAHORLIBERACAO) - TRUNC(X.DTAHORGERACAO) X_DIAS
 
   FROM CONSINCO.MAD_CARGARECEB X INNER JOIN MLF_NOTAFISCAL A ON A.NROINTERNORECEB = X.NROCARGARECEB
   WHERE 1=1
     AND TRUNC(X.DTAHORGERACAO) != NVL(TRUNC(X.DTAHORLIBERACAO), DATE '1996-12-10')
     AND X.USUCANCELAMENTO IS NULL
     AND TRUNC(X.DTAHORGERACAO) = :DT1
     AND X.NROEMPRESA IN (501,502,503,506,507,508)
      
UNION

 SELECT X.NROEMPRESA CD, A.NUMERONF, X.NROCARGARECEB NRO_CARGA, X.DTAHORGERACAO, X.USUGERACAO, X.DTAHORLIBERACAO, X.USULIBERACAO,
        TRUNC(X.DTAHORLIBERACAO) - TRUNC(X.DTAHORGERACAO) X_DIAS_PARADA
 
   FROM CONSINCO.MAD_CARGARECEB X INNER JOIN MLF_AUXNOTAFISCAL A ON A.NROINTERNORECEB = X.NROCARGARECEB
   WHERE 1=1
     AND TRUNC(X.DTAHORGERACAO) != NVL(TRUNC(X.DTAHORLIBERACAO), DATE '1996-12-10')
     AND X.USUCANCELAMENTO IS NULL
     AND TRUNC(X.DTAHORGERACAO) = :DT1
     AND X.NROEMPRESA IN (501,502,503,506,507,508)
     )
     
)
