SELECT SEQPRODUTO, DESCCOMPLETA, NROCARGA, NROEMPRESA, EMBALAGEM, QUANTIDADEEMB, DESCTIPESPECIE, TIPOCARGA,
       TIPOETIQUETA
       
FROM consinco.MLOV_CONTROLEETQSORTER A WHERE A.NROCARGA = 1728687
