ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT B.NROEMPRESA, A.SEQPRODUTO PLU, DESCCOMPLETA, NVL(ROUND(CMULTVLRNF,2),0) CUSTO 
  FROM MAP_PRODUTO A LEFT JOIN MRL_PRODUTOEMPRESA B ON A.SEQPRODUTO = B.SEQPRODUTO
 WHERE NROEMPRESA IN (#LS1) AND B.STATUSCOMPRA = 'A' 
 AND NVL(CMULTVLRNF,0) > 0
 
 ORDER BY 2 
