ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT A.SEQPRODUTO PLU, DESCCOMPLETA, NVL(ROUND(CMULTVLRNF,2),0) CUSTO 
  FROM MAP_PRODUTO A LEFT JOIN MRL_PRODUTOEMPRESA B ON A.SEQPRODUTO = B.SEQPRODUTO
 WHERE NROEMPRESA = 501 AND B.STATUSCOMPRA = 'A'
 
 ORDER BY 2
