ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT B.NROEMPRESA, A.SEQPRODUTO PLU, DESCCOMPLETA, C.PADRAOEMBCOMPRA, NVL(ROUND(CMULTVLRNF,2),0) CUSTO_UNI, C.PADRAOEMBCOMPRA * NVL(ROUND(CMULTVLRNF,2),0) CUSTO_EMB
  FROM MAP_PRODUTO A LEFT JOIN MRL_PRODUTOEMPRESA B ON A.SEQPRODUTO = B.SEQPRODUTO
                     LEFT JOIN MAP_FAMDIVISAO    C ON C.SEQFAMILIA = A.SEQFAMILIA
 WHERE NROEMPRESA IN (#LS1) AND B.STATUSCOMPRA = 'A' 
 AND NVL(CMULTVLRNF,0) > 0
 
 ORDER BY 2 
