SELECT X.NROEMPRESA, NUMERONF, SEQPESSOATOMADORNFSE||' - '||G.NOMERAZAO TOMADOR, TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO,
       NVL(REGEXP_SUBSTR(
        OBSERVACAO,
         ' CARGA[[:space:]]+([0-9]+)', 
         1, 1, NULL, 1
       ),
       REGEXP_SUBSTR(
        OBSERVACAO,
         ' CG[[:space:]]+([0-9]+)', 
         1, 1, NULL, 1
       )) CARGA, FVALORTOTALNF(X.ROWID, 'N') VALOR, X.OBSERVACAO
  FROM MLF_NOTAFISCAL X INNER JOIN GE_PESSOA G ON G.SEQPESSOA = SEQPESSOATOMADORNFSE
 WHERE CODGERALOPER = 11
   AND NROEMPRESA IN (#LS1)
   AND STATUSNF != 'C'
   AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2
