SELECT A.NROEMPRESA CD, A.NOMEARQUIVO CARGA,
       A.DTAHORREJEICAO, B.MENSAGEMERRO,
       NVL(C.SEQPRODUTO, D.SEQPRODUTO) PLU, NVL(C.QTDEMBALAGEM, D.QTDEMBALAGEM) QTDEMBALAGEM, NVL(C.QTDSOLICITADA, D.QTDDOCUMENTO) QTD
  FROM MLO_LOGIMPORTACAO A INNER JOIN MLO_MENSAGEMERRO B ON A.SEQUENCIAERRO = B.SEQUENCIAERRO
                            LEFT JOIN MLO_XCARGAEXPPROD C ON C.NROCARGA = A.NOMEARQUIVO AND B.MENSAGEMERRO LIKE '%'||C.SEQPRODUTO||'%'
                            LEFT JOIN MLO_XCARGARECPROD D ON D.NROCARGA = A.NOMEARQUIVO AND B.MENSAGEMERRO LIKE '%'||D.SEQPRODUTO||'%'
 WHERE A.NROEMPRESA IN (#LS1)
   AND NVL(INDEXCLUIREPROC, 'N') = 'N'
 ORDER BY TIPIMPORTACAO, DTAHORREJEICAO, A.NOMEARQUIVO
