--Tentando alterar para otimizar

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT A.NROEMPRESA EMP_CD, F.TIPESPECIE EMP_DEST, A.NROCARGA,
       TO_CHAR(A.DTAHORGERACAO, 'DD/MM/YYYY') DTA_ETIQUETA,
       /*A.DTAHORLIBERACAO,*/
       C.SEQPRODUTO PLU, M.DESCCOMPLETA DESC_PROD, DECODE(X.TIPOETIQUETA, 'M', 'Master: ') || X.CODBARRAETQ ETIQUETA,
       SUBSTR(X.SITUACAOETIQUETA, 1, 250) STATUS_ETIQUETA, 
       DESCTIPOCARGA TIPO_CARGA
       
  FROM MLO_CARGARECEB A INNER JOIN MLO_PARAMRECEB B ON A.NROEMPRESA = B.NROEMPRESA AND A.TIPCARGARECEB = B.TIPCARGARECEB
                        INNER JOIN MLO_PALETE F ON F.NROCARGARECEB = A.NROCARGA AND F.NROEMPRESA = A.NROEMPRESA 
                        INNER JOIN CONSINCO.NAGV_MLOV_CONTROLEETQSORTER X ON X.NROCARGA = F.NROCARGARECEB 
                                                                    AND X.NROEMPRESA = F.NROEMPRESA AND X.TIPESPECIE = F.TIPESPECIE
                                                                    AND NVL(X.SITUACAOETIQUETACOD,'X') NOT IN ('MO', 'EC', 'CG', 'FT', 'AG')
                                                                                            --     IN ('NC','AM') 
                                                                                                 AND X.SEQPRODUTO = F.SEQPRODUTO
                                                                                                 
                          
                        INNER JOIN MLO_CARGARECPROD C ON C.NROCARGA = A.NROCARGA AND C.NROEMPRESA = A.NROEMPRESA AND C.SEQPRODUTO = F.SEQPRODUTO
                        INNER JOIN MLO_TIPESPECIE D ON D.TIPESPECIE = C.TIPESPECIE AND D.NROEMPRESA = A.NROEMPRESA AND D.UTZPROCESCARROSSEL IN ('S', 'O')
                        INNER JOIN MAP_PRODUTO M ON M.SEQPRODUTO = C.SEQPRODUTO
                      /*INNER JOIN MLO_PRODUTO M ON M.SEQPRODUTO = C.SEQPRODUTO AND M.NROEMPRESA = C.CODDEPOSITANTE*/
 WHERE 1=1
   
   AND A.NROEMPRESA IN (501,506)
   AND F.TIPESPECIE IN ('1') --(#LS1)
   AND TRUNC(A.DTAHORGERACAO) BETWEEN SYSDATE -5 AND SYSDATE -4 -- :DT1 AND :DT2
  
ORDER BY A.NROEMPRESA, F.TIPESPECIE, TO_CHAR(A.DTAHORGERACAO, 'DD/MM/YYYY'), A.NROCARGA, C.SEQPRODUTO



-- Old

SELECT DISTINCT A.NROEMPRESA EMP_CD, X.DESCTIPESPECIE EMP_DEST, A.NROCARGA,
       TO_CHAR(A.DTAHORGERACAO, 'DD/MM/YYYY') DTA_ETIQUETA,
       /*A.DTAHORLIBERACAO,*/
       C.SEQPRODUTO PLU, M.DESCCOMPLETA DESC_PROD, DECODE(X.TIPOETIQUETA, 'M', 'Master: ') || X.CODBARRAETQ ETIQUETA,
       SUBSTR(X.SITUACAOETIQUETA, 1, 250) STATUS_ETIQUETA, DESCTIPOCARGA TIPO_CARGA
       
  FROM MLO_CARGARECEB A INNER JOIN MLO_PARAMRECEB B ON A.NROEMPRESA = B.NROEMPRESA AND A.TIPCARGARECEB = B.TIPCARGARECEB
                        INNER JOIN MLO_PALETE F ON F.NROCARGARECEB = A.NROCARGA AND F.NROEMPRESA = A.NROEMPRESA 
                        INNER JOIN MLOV_CONTROLEETQSORTER X ON X.NROCARGA = F.NROCARGARECEB AND X.NROEMPRESA = F.NROEMPRESA AND X.TIPESPECIE = F.TIPESPECIE
                                                           AND NVL(X.SITUACAOETIQUETACOD,'X') NOT IN ('MO', 'EC', 'CG', 'FT', 'AG') AND X.SEQPRODUTO = F.SEQPRODUTO
                        INNER JOIN MLO_CARGARECPROD C ON C.NROCARGA = A.NROCARGA AND C.NROEMPRESA = A.NROEMPRESA AND C.SEQPRODUTO = F.SEQPRODUTO
                        INNER JOIN MLO_TIPESPECIE D ON D.TIPESPECIE = C.TIPESPECIE AND D.NROEMPRESA = A.NROEMPRESA AND D.UTZPROCESCARROSSEL IN ('S', 'O')
                        INNER JOIN MAP_PRODUTO M ON M.SEQPRODUTO = C.SEQPRODUTO
                      /*INNER JOIN MLO_PRODUTO M ON M.SEQPRODUTO = C.SEQPRODUTO AND M.NROEMPRESA = C.CODDEPOSITANTE*/
 WHERE 1=1
      
   AND A.NROEMPRESA IN (501,506)
   AND X.TIPESPECIE IN (#LS1)
   AND TRUNC(A.DTAHORGERACAO) BETWEEN  :DT1 AND :DT2
   
ORDER BY A.NROEMPRESA, X.DESCTIPESPECIE, TO_CHAR(A.DTAHORGERACAO, 'DD/MM/YYYY'), A.NROCARGA, C.SEQPRODUTO
/*
SELECT * FROM MLOV_CONTROLEETQSORTER XX WHERE XX.NROCARGA = 2222588 AND TIPESPECIE = 1
SELECT * FROM MLO_CARGARECEB ZZ WHERE ZZ.NROCARGA = 2222588
SELECT * FROM MLO_PALETE F WHERE F.NROCARGARECEB = 2222588 AND SEQPRODUTO = 253090
*/ 
