ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT NROEMPRESA EMPRESA, ETQPALETECARREG ETIQUETA, DESCTIPESPECIE LOJA, TO_CHAR(DTAHORINIMONT, 'DD/MM/YYYY') DATA_MONTAGEM, USUMONTAGEM USUARIO, DESCSTATUSCARREG STATUS,
       TO_CHAR(:DT1, 'DD/MM/YYYY') DTA_INICIO, TO_CHAR(:DT2, 'DD/MM/YYYY') DTA_FIM

FROM (

SELECT  NROEMPRESA,
        MIN(XXX.ETQPALETECARREG)||' - '||Min(XXX.ETQPALETECARREGAGRUPAMENTO)         ETQPALETECARREG, 
        MIN(XXX.DESCTIPESPECIE)          DESCTIPESPECIE,
        MIN(XXX.DTAHORINIMONTMASTER)     DTAHORINIMONT,
        MIN(XXX.USUMONTAGEMMASTER)       USUMONTAGEM,
        MIN(XXX.DESCSTATUSCARREGMASTER)  DESCSTATUSCARREG                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

FROM  (SELECT  MLO_PALETECARREG.NROEMPRESA, A1.TIPOETQPALETECARREG || A1.SEQPALETECARREG AS ETQPALETECARREGAGRUPAMENTO,
    A1.TIPOETQPALETECARREG AS TIPOETQPALETECARREGAGRUP,
    A1.SEQPALETECARREG AS SEQPALETECARREGAGRUPAMENTO,
    MLO_PALETECARREG.TIPOETQPALETECARREG || MLO_PALETECARREG.SEQPALETECARREG AS ETQPALETECARREG,
    MLO_PALETECARREG.TIPOETQPALETECARREG AS TIPOETQPALETECARREGMASTER,
    MLO_PALETECARREG.SEQPALETECARREG, 
    MLO_TIPESPECIE.DESCTIPESPECIE,
    A1.DTAHORINIMONT AS DTAHORINIMONTAGRUP,
    A1.DTAHORFINALMONT AS DTAHORFINALMONTAGRUP,
    A1.USUMONTAGEM AS USUMONTAGEMAGRUP,
    A1.DTAHORINICARREG AS DTAHORINICARREGAGRUP,
    A1.DTAHORFIMCARREG AS DTAHORFIMCARREGAGRUP,
    A1.USUCARREG AS USUCARREGAGRUP,
    (
 CASE WHEN A1.STATUSCARREG = 'C' THEN 'Carregada'
      WHEN A1.STATUSCARREG = 'E' THEN 'Em Montagem'
      WHEN A1.STATUSCARREG = 'M' THEN 'Montada'
      WHEN A1.STATUSCARREG = 'N' THEN 'Cancelada'
      WHEN A1.STATUSCARREG = 'R' THEN 'Em Carregamento'
      WHEN A1.STATUSCARREG = 'T' THEN 'TransferÃªncia Entre Ãreas'
      WHEN A1.STATUSCARREG = 'A' THEN 'Em Agrupamento'
      WHEN A1.STATUSCARREG = 'B' THEN 'Agrupada'
      WHEN A1.STATUSCARREG = 'D' THEN 'Em ExpediÃ§Ã£o'
      WHEN A1.STATUSCARREG = 'I' THEN 'ExpediÃ§Ã£o'
      WHEN A1.STATUSCARREG = 'U' THEN 'Em Auditoria'
      ELSE NULL
    END
    ) AS DESCSTATUSCARREGAGRUP,
    MLO_PALETECARREG.DTAHORINIMONT AS DTAHORINIMONTMASTER,
    MLO_PALETECARREG.DTAHORFINALMONT AS DTAHORFINALMONTMASTER,
    MLO_PALETECARREG.USUMONTAGEM AS USUMONTAGEMMASTER,
    MLO_PALETECARREG.DTAHORINICARREG AS DTAHORINICARREGMASTER,
    MLO_PALETECARREG.DTAHORFIMCARREG AS DTAHORFIMCARREGMASTER,
    MLO_PALETECARREG.USUCARREG AS USUCARREGMASTER,
    (
 CASE WHEN MLO_PALETECARREG.STATUSCARREG = 'C' THEN 'Carregada'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'E' THEN 'Em Montagem'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'M' THEN 'Montada'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'N' THEN 'Cancelada'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'R' THEN 'Em Carregamento'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'T' THEN 'TransferÃªncia Entre Ãreas'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'A' THEN 'Em Agrupamento'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'B' THEN 'Agrupada'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'D' THEN 'Em ExpediÃ§Ã£o'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'I' THEN 'ExpediÃ§Ã£o'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'U' THEN 'Em Auditoria'
      ELSE NULL
    END
    ) AS DESCSTATUSCARREGMASTER,
    MLO_TIPESPECIE.SEQCLIENTE

  FROM  MLO_PALCARREGAGRUPAMENTO,
    MLO_PALETECARREG A1,
    MLO_PALETECARREG,
    MLO_PALCARREGRF,
    MLO_PALETE,
    MLO_TIPESPECIE,
    MLO_PALETEQTDE

  WHERE MLO_PALCARREGAGRUPAMENTO.SEQPALETECARREGAGRUPAMENTO = A1.SEQPALETECARREG
  AND MLO_PALCARREGAGRUPAMENTO.SEQPALETECARREG = MLO_PALETECARREG.SEQPALETECARREG
  AND MLO_PALCARREGRF.SEQPALETECARREG = MLO_PALETECARREG.SEQPALETECARREG
  AND MLO_PALETE.SEQPALETERF = MLO_PALETEQTDE.SEQPALETERF
  AND MLO_PALETE.SEQPALETERF = MLO_PALCARREGRF.SEQPALETERF
  AND MLO_PALETEQTDE.SEQPALETEQTDE = MLO_PALCARREGRF.SEQPALETEQTDE
  AND MLO_TIPESPECIE.TIPESPECIE = MLO_PALETE.TIPESPECIE
  AND MLO_TIPESPECIE.NROEMPRESA = MLO_PALETE.NROEMPRESA

  
AND MLO_PALETECARREG.NROEMPRESA IN (501,504,505,506)             
AND TRUNC( MLO_PALETECARREG.DTAHORINIMONT ) >= :DT1                                    
AND TRUNC( MLO_PALETECARREG.DTAHORINIMONT ) <= :DT2                 
AND MLO_PALETECARREG.STATUSCARREG IN ('M','B')                     
AND MLO_PALETECARREG.STATUSCARREG LIKE (DECODE(:LS1, 'Montada','M','Agrupada','B','%%'))

  GROUP BY
    A1.TIPOETQPALETECARREG || A1.SEQPALETECARREG,
    A1.TIPOETQPALETECARREG, MLO_PALETECARREG.NROEMPRESA,
    A1.SEQPALETECARREG,
    MLO_PALETECARREG.TIPOETQPALETECARREG || MLO_PALETECARREG.SEQPALETECARREG,
    MLO_PALETECARREG.TIPOETQPALETECARREG,
    MLO_PALETECARREG.SEQPALETECARREG,
    MLO_TIPESPECIE.DESCTIPESPECIE,
    A1.DTAHORINIMONT,
    A1.DTAHORFINALMONT,
    A1.USUMONTAGEM,
    A1.DTAHORINICARREG,
    A1.DTAHORFIMCARREG,
    A1.USUCARREG,
    (
 CASE WHEN A1.STATUSCARREG = 'C' THEN 'Carregada'
      WHEN A1.STATUSCARREG = 'E' THEN 'Em Montagem'
      WHEN A1.STATUSCARREG = 'M' THEN 'Montada'
      WHEN A1.STATUSCARREG = 'N' THEN 'Cancelada'
      WHEN A1.STATUSCARREG = 'R' THEN 'Em Carregamento'
      WHEN A1.STATUSCARREG = 'T' THEN 'TransferÃªncia Entre Ãreas'
      WHEN A1.STATUSCARREG = 'A' THEN 'Em Agrupamento'
      WHEN A1.STATUSCARREG = 'B' THEN 'Agrupada'
      WHEN A1.STATUSCARREG = 'D' THEN 'Em ExpediÃ§Ã£o'
      WHEN A1.STATUSCARREG = 'I' THEN 'ExpediÃ§Ã£o'
      WHEN A1.STATUSCARREG = 'U' THEN 'Em Auditoria'
      ELSE NULL
    END
    ),
    MLO_PALETECARREG.DTAHORINIMONT,
    MLO_PALETECARREG.DTAHORFINALMONT,
    MLO_PALETECARREG.USUMONTAGEM,
    MLO_PALETECARREG.DTAHORINICARREG,
    MLO_PALETECARREG.DTAHORFIMCARREG,
    MLO_PALETECARREG.USUCARREG,
    (
    CASE  WHEN MLO_PALETECARREG.STATUSCARREG = 'C' THEN 'Carregada'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'E' THEN 'Em Montagem'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'M' THEN 'Montada'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'N' THEN 'Cancelada'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'R' THEN 'Em Carregamento'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'T' THEN 'TransferÃªncia Entre Ãreas'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'A' THEN 'Em Agrupamento'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'B' THEN 'Agrupada'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'D' THEN 'Em ExpediÃ§Ã£o'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'I' THEN 'ExpediÃ§Ã£o'
      WHEN MLO_PALETECARREG.STATUSCARREG = 'U' THEN 'Em Auditoria'
      ELSE NULL
    END
    ),
    MLO_TIPESPECIE.SEQCLIENTE
  ) XXX
GROUP BY
  SEQPALETECARREGAGRUPAMENTO, nroempresa,
ROLLUP( SEQPALETECARREG )

UNION ALL

SELECT  MLO_PALETECARREG.NROEMPRESA, MLO_PALETECARREG.TIPOETQPALETECARREG || MLO_PALETECARREG.SEQPALETECARREG AS ETQPALETECARREG, 
  MLO_TIPESPECIE.DESCTIPESPECIE, 
  MLO_PALETECARREG.DTAHORINIMONT,
  MLO_PALETECARREG.USUMONTAGEM,
  (
CASE WHEN MLO_PALETECARREG.STATUSCARREG = 'C' THEN 'Carregada'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'E' THEN 'Em Montagem'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'M' THEN 'Montada'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'N' THEN 'Cancelada'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'R' THEN 'Em Carregamento'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'T' THEN 'TransferÃªncia Entre Ãreas'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'A' THEN 'Em Agrupamento'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'B' THEN 'Agrupada'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'D' THEN 'Em ExpediÃ§Ã£o'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'I' THEN 'ExpediÃ§Ã£o'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'U' THEN 'Em Auditoria'
     ELSE NULL
    END
  ) AS DESCSTATUSCARREG

FROM  MLO_PALETECARREG,
  MLO_PALCARREGRF,
  MLO_PALETE,
  MLO_TIPESPECIE,
  MLO_PALETEQTDE

WHERE MLO_PALCARREGRF.SEQPALETECARREG = MLO_PALETECARREG.SEQPALETECARREG
AND MLO_PALETE.SEQPALETERF = MLO_PALETEQTDE.SEQPALETERF
AND MLO_PALETE.SEQPALETERF = MLO_PALCARREGRF.SEQPALETERF 
AND MLO_PALETEQTDE.SEQPALETEQTDE = MLO_PALCARREGRF.SEQPALETEQTDE
AND MLO_TIPESPECIE.TIPESPECIE = MLO_PALETE.TIPESPECIE
AND MLO_TIPESPECIE.NROEMPRESA = MLO_PALETE.NROEMPRESA
AND NOT EXISTS(
  SELECT  1
  FROM   MLO_PALCARREGAGRUPAMENTO X1
  WHERE  X1.SEQPALETECARREG = MLO_PALETECARREG.SEQPALETECARREG
  )

AND MLO_PALETECARREG.NROEMPRESA IN (501,504,505,506)             
AND TRUNC( MLO_PALETECARREG.DTAHORINIMONT ) >= :DT1                                        
AND TRUNC( MLO_PALETECARREG.DTAHORINIMONT ) <= :DT2                                      
AND MLO_PALETECARREG.STATUSCARREG IN ('M','B')                     
AND MLO_PALETECARREG.STATUSCARREG LIKE (DECODE(:LS1, 'Montada','M','Agrupada','B','%%'))

GROUP BY
  MLO_PALETECARREG.TIPOETQPALETECARREG || MLO_PALETECARREG.SEQPALETECARREG,
  MLO_PALETECARREG.TIPOETQPALETECARREG, MLO_PALETECARREG.NROEMPRESA,
  MLO_PALETECARREG.SEQPALETECARREG,
  MLO_TIPESPECIE.DESCTIPESPECIE,
  MLO_PALETECARREG.DTAHORINIMONT,
  MLO_PALETECARREG.DTAHORFINALMONT,
  MLO_PALETECARREG.USUMONTAGEM, MLO_PALETECARREG.NROEMPRESA,
  MLO_PALETECARREG.DTAHORINICARREG,
  MLO_PALETECARREG.DTAHORFIMCARREG,
  MLO_PALETECARREG.USUCARREG,
  (
CASE WHEN MLO_PALETECARREG.STATUSCARREG = 'C' THEN 'Carregada'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'E' THEN 'Em Montagem'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'M' THEN 'Montada'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'N' THEN 'Cancelada'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'R' THEN 'Em Carregamento'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'T' THEN 'TransferÃªncia Entre Ãreas'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'A' THEN 'Em Agrupamento'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'B' THEN 'Agrupada'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'D' THEN 'Em ExpediÃ§Ã£o'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'I' THEN 'ExpediÃ§Ã£o'
     WHEN MLO_PALETECARREG.STATUSCARREG = 'U' THEN 'Em Auditoria'
     ELSE NULL
  END
  ),
  MLO_TIPESPECIE.SEQCLIENTE )
  
ORDER BY STATUS, EMPRESA

