-- Adicionado por Giuliano em 02/12/2025
-- Crítica TAE

SELECT DISTINCT (X.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
       X.NUMERONF,
       X.NROEMPRESA,
       XI.SEQAUXNFITEM AS SEQAUXNFITEM,
      'L' AS BLOQAUTOR,
       97 AS CODINCONSISTENC,
       'Ped.: '||S.NROPEDIDOSUPRIM||' - Aco.: '||TAE.NRO_ACORDO||' Vinculado ao item '||XI.SEQPRODUTO||' Encontra-se '||
       CASE WHEN UPPER(TAE.STATUS) LIKE '%AGUARDANDO%' THEN 'Aguardando Assinatura' 
            WHEN UPPER(TAE.STATUS) LIKE '%REJEITADO%'  THEN 'Rejeitado' 
            WHEN UPPER(TAE.STATUS) LIKE '%FINALIZADO%' THEN 'Finalizado' END ||' no TAE! Entre em contato com Depto Comercial - Comp.: '||INITCAP(TAE.COMPRADOR) MENSAGEM
       
  FROM MLF_AUXNOTAFISCAL X INNER JOIN MLF_AUXNFITEM XI ON X.SEQAUXNOTAFISCAL = XI.SEQAUXNOTAFISCAL
                           INNER JOIN MSU_PSITEMRECEBIDO P ON P.SEQAUXNOTAFISCAL = XI.SEQAUXNOTAFISCAL AND P.SEQPRODUTO = XI.SEQPRODUTO
                           INNER JOIN MSU_PEDIDOSUPRIM S ON S.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM AND S.NROEMPRESA = X.NROEMPRESA
                           INNER JOIN MAC_GERCOMPRA G ON G.SEQGERCOMPRA = S.SEQGERCOMPRA
                           INNER JOIN MSU_ACORDOPROMOC ACO ON ACO.SEQFORNECEDOR = X.SEQPESSOA AND (REGEXP_REPLACE(DESCACORDO, '[^0-9]', '') = G.SEQGERCOMPRA AND ACO.NROPEDIDOSUPRIM IS NULL 
                                                                                               OR ACO.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND S.NROEMPRESA = ACO.NROEMPRESA)
                           INNER JOIN NAGV_TAE_ACORDOS_V4 TAE ON TAE.NRO_ACORDO = ACO.NROACORDO AND TAE.NRO_EMPRESA = ACO.NROEMPRESA AND TAE.COD_FORNECEDOR = ACO.SEQFORNECEDOR
                           
WHERE 1=1 
  AND TAE.STATUS != 'Envelope finalizado'
  AND 1=2
