SELECT COD_PROMOC, DESC_PROMOCAO, DTAINICIO, DTAFIM, PLU, EAN, DESC_PROD, 
       TO_CHAR(SUM(VALOR_TOTAL_BRUTO),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_BRUTO,
       TO_CHAR(SUM(TOTAL_DESCONTO) ,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_DESCONTO,
       TO_CHAR(SUM(VALOR_TOTAL_COM_DESC),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_COM_DESC, 
       SUM(QTD_DESC) QTD_DESC, 
       SUM(QUANTIDADE_TOTAL) QUANTIDADE_TOTAL
       
       FROM (
SELECT 
    P.SEQPROMOCPDV COD_PROMOC,
    P.DESCRICAO DESC_PROMOCAO,
    TO_CHAR(P.DTAINICIO, 'DD/MM/YYYY') DTAINICIO,
    TO_CHAR(P.DTAFIM, 'DD/MM/YYYY') DTAFIM, 
    DI.SEQPRODUTO PLU,
    DI.CODPRODUTO EAN, 
    PR.DESCCOMPLETA DESC_PROD,
    (DI.VLRITEM) VALOR_TOTAL_BRUTO, 
    (VLRDESCONTO) TOTAL_DESCONTO, 
    ((DI.VLRITEM - DI.VLRDESCONTO)) VALOR_TOTAL_COM_DESC,
    /*TRUNC((TRUNC(SUM(DI.QUANTIDADE)))/ (SELECT SUM(QTDITEMGRUPO) FROM MFL_PROMOCPDVGRUPO AA WHERE AA.SEQPROMOCPDV = P.SEQPROMOCPDV)) QTD_DESC,*/
    CASE WHEN VLRDESCONTO > 0.01 THEN ROUND(VLRDESCONTO / (VLRITEM / DI.QUANTIDADE)) ELSE 0 END QTD_DESC,
    (DI.QUANTIDADE) QUANTIDADE_TOTAL
    
FROM 
    MFL_PROMOCAOPDV P 
    INNER JOIN MFL_DFITEM DI ON DI.SEQPROMOCPDV = P.SEQPROMOCPDV AND DI.STATUSITEM != 'C' 
    INNER JOIN MFL_DOCTOFISCAL D ON D.SEQNF = DI.SEQNF
    INNER JOIN MFL_PROMOCPDVITEM PI ON PI.SEQPROMOCPDV = P.SEQPROMOCPDV AND PI.SEQPRODUTO = DI.SEQPRODUTO AND PI.TIPOITEMPROMOC = 'P'
    INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = DI.SEQPRODUTO

WHERE 1=1
   AND P.SEQPROMOCPDV = :NR1
   AND DI.NROEMPRESA IN (#LS1)
   AND D.DTAMOVIMENTO BETWEEN :DT1 AND :DT2
   )
   GROUP BY COD_PROMOC, DESC_PROMOCAO, DTAINICIO, DTAFIM, PLU, EAN, DESC_PROD

UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
  FROM DUAL
   
   
UNION ALL

SELECT COD_PROMOC, DESC_PROMOCAO, DTAINICIO, DTAFIM, NULL, NULL, NULL,
       TO_CHAR(SUM(VALOR_TOTAL_BRUTO),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_BRUTO,
       TO_CHAR(SUM(TOTAL_DESCONTO) ,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_DESCONTO,
       TO_CHAR(SUM(VALOR_TOTAL_COM_DESC),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_COM_DESC, 
       SUM(QTD_DESC) QTD_DESC, 
       SUM(QUANTIDADE_TOTAL) QUANTIDADE_TOTAL
       
       FROM (
SELECT 
    P.SEQPROMOCPDV COD_PROMOC,
    P.DESCRICAO DESC_PROMOCAO,
    TO_CHAR(P.DTAINICIO, 'DD/MM/YYYY') DTAINICIO,
    TO_CHAR(P.DTAFIM, 'DD/MM/YYYY') DTAFIM, 
    DI.SEQPRODUTO PLU,
    DI.CODPRODUTO EAN, 
    PR.DESCCOMPLETA DESC_PROD,
    (DI.VLRITEM) VALOR_TOTAL_BRUTO, 
    (VLRDESCONTO)TOTAL_DESCONTO, 
    ((DI.VLRITEM - DI.VLRDESCONTO)) VALOR_TOTAL_COM_DESC,
    /*TRUNC((TRUNC(SUM(DI.QUANTIDADE)))/ (SELECT SUM(QTDITEMGRUPO) FROM MFL_PROMOCPDVGRUPO AA WHERE AA.SEQPROMOCPDV = P.SEQPROMOCPDV)) QTD_DESC,*/
    CASE WHEN VLRDESCONTO > 0.01 THEN ROUND(VLRDESCONTO / (VLRITEM / DI.QUANTIDADE)) ELSE 0 END QTD_DESC,
    (DI.QUANTIDADE) QUANTIDADE_TOTAL
    
FROM 
    MFL_PROMOCAOPDV P 
    INNER JOIN MFL_DFITEM DI ON DI.SEQPROMOCPDV = P.SEQPROMOCPDV AND DI.STATUSITEM != 'C' 
    INNER JOIN MFL_DOCTOFISCAL D ON D.SEQNF = DI.SEQNF
    INNER JOIN MFL_PROMOCPDVITEM PI ON PI.SEQPROMOCPDV = P.SEQPROMOCPDV AND PI.SEQPRODUTO = DI.SEQPRODUTO AND PI.TIPOITEMPROMOC = 'P'
    INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = DI.SEQPRODUTO

WHERE 1=1
   AND P.SEQPROMOCPDV = :NR1
   AND DI.NROEMPRESA IN (#LS1)
   AND D.DTAMOVIMENTO BETWEEN :DT1 AND :DT2
   )
   GROUP BY COD_PROMOC, DESC_PROMOCAO, DTAINICIO, DTAFIM;
   
