SELECT P.SEQPROMOCPDV COD, TO_CHAR(DI.NROEMPRESA) LOJA,
       P.DESCRICAO DESC_PROMOCAO,
       TO_CHAR(P.DTAINICIO, 'DD/MM/YYYY') DTAINICIO,
       TO_CHAR(P.DTAFIM, 'DD/MM/YYYY') DTAFIM, 
       DI.SEQPRODUTO PLU,DI.CODPRODUTO EAN, PR.DESCCOMPLETA DESC_PROD,
       TO_CHAR(SUM(DI.VLRITEM) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_BRUTO, 
       TO_CHAR(SUM(DI.VLRDESCONTO) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_DESCONTO, 
       TO_CHAR((SUM(DI.VLRITEM) - SUM(DI.VLRDESCONTO)) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_COM_DESC,
       SUM(DI.QUANTIDADE) QUANTIDADE_TOTAL

  FROM MFL_PROMOCAOPDV P INNER JOIN MFL_DFITEM DI ON DI.SEQPROMOCPDV = P.SEQPROMOCPDV AND DI.STATUSITEM != 'C'
                         INNER JOIN MFL_PROMOCPDVITEM PI ON PI.SEQPROMOCPDV = P.SEQPROMOCPDV AND PI.SEQPRODUTO = DI.SEQPRODUTO
                         INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = DI.SEQPRODUTO

 WHERE 1 = 1
   AND VLRDESCONTO > 0
   AND P.SEQPROMOCPDV = :NR1
   AND DI.NROEMPRESA IN (#LS1)

GROUP BY P.SEQPROMOCPDV, P.DESCRICAO, P.DTAINICIO, P.DTAFIM, DI.SEQPRODUTO, PR.DESCCOMPLETA, DI.CODPRODUTO, DI.NROEMPRESA

UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

UNION ALL

SELECT P.SEQPROMOCPDV COD, 'Total ' LOJA,
       P.DESCRICAO DESC_PROMOCAO,
       TO_CHAR(P.DTAINICIO, 'DD/MM/YYYY') DTAINICIO,
       TO_CHAR(P.DTAFIM, 'DD/MM/YYYY') DTAFIM, 
       DI.SEQPRODUTO PLU,DI.CODPRODUTO EAN, PR.DESCCOMPLETA DESC_PROD,
       TO_CHAR(SUM(DI.VLRITEM) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_BRUTO, 
       TO_CHAR(SUM(DI.VLRDESCONTO) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_DESCONTO, 
       TO_CHAR((SUM(DI.VLRITEM) - SUM(DI.VLRDESCONTO)) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_COM_DESC,
       SUM(DI.QUANTIDADE) QUANTIDADE_TOTAL

  FROM MFL_PROMOCAOPDV P INNER JOIN MFL_DFITEM DI ON DI.SEQPROMOCPDV = P.SEQPROMOCPDV AND DI.STATUSITEM != 'C'
                         INNER JOIN MFL_PROMOCPDVITEM PI ON PI.SEQPROMOCPDV = P.SEQPROMOCPDV AND PI.SEQPRODUTO = DI.SEQPRODUTO
                         INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = DI.SEQPRODUTO

 WHERE 1 = 1
   AND VLRDESCONTO > 0
   AND P.SEQPROMOCPDV = :NR1
   AND DI.NROEMPRESA IN (#LS1)

GROUP BY P.SEQPROMOCPDV, P.DESCRICAO, P.DTAINICIO, P.DTAFIM, DI.SEQPRODUTO, PR.DESCCOMPLETA, DI.CODPRODUTO
