-- Qrp em https://github.com/GiulianoGMS/QRPs/blob/main/RelEncartesCustom.QRP

SELECT SEQENCARTE,
       SEGMENTO, 
       INFO_ENCARTE, 
       DTA_INICIO, 
       DTA_FIM,
       CASE WHEN OBS IS NULL THEN PAG +1 ELSE 0 END PAG, 
       CASE WHEN OBS IS NULL THEN DESC_PAG ELSE 'Divergentes' END DESC_PAG, 
       COMPRADOR, PLU, EAN, 
       CASE WHEN OBS IS NULL THEN NULL ELSE 'OBS: '||OBS||' - PLU: '||SEQPRODUTO||' - ' END||DESCRICAO DESCRICAO,
       PRECO_ATUAL, PRECO_ENCARTE, PRECO_CARTAO, LEGENDA, OBS
  FROM (

SELECT DISTINCT X.SEQENCARTE, :LS1 SEGMENTO,
       'Cod. Encarte: '||X.SEQENCARTE||' - Desc. Encarte: '||X.DESCRICAO INFO_ENCARTE,
       TO_CHAR(NVL(XI.DTAVIGENCIAINI, X.DTAINICIO), 'DD/MM/YYYY') DTA_INICIO,
       TO_CHAR(NVL(XI.DTAVIGENCIAFIM, X.DTAFIM), 'DD/MM/YYYY') DTA_FIM,
       DECODE(XI.NROPAGINA,8,0,XI.NROPAGINA) PAG,
       ' Pagina: '||DECODE(XI.NROPAGINA,8,0,XI.NROPAGINA)||' - '||NVL(G.NOMEPAGINA, 'SEM_DESC') DESC_PAG,
       CO.COMPRADOR, XI.SEQPRODUTO PLU, 
      (SELECT LISTAGG(CODACESSO, ' ') WITHIN GROUP(ORDER BY SEQPRODUTO)
         FROM MAP_PRODCODIGO E 
        WHERE E.SEQPRODUTO = XI.SEQPRODUTO 
          AND E.TIPCODIGO = 'E') EAN,
       CASE WHEN XI.TIPODESC = 'P' THEN
                                NVL(P.DESCENCARTE, DECODE('G', 'C', P.DESCCOMPLETA,
                                                      NVL(P.DESCGENERICA,P.DESCCOMPLETA)))
            ELSE
                                NVL(F.DESCENCARTE, DECODE('G', 'C', P.DESCCOMPLETA,
                                                      NVL(P.DESCGENERICA,P.DESCCOMPLETA))) END DESCRICAO,
      'R$ '||TO_CHAR(NVL(PC.PRECOVALIDNORMAL, PC.PRECOBASENORMAL), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') PRECO_ATUAL,
      CASE WHEN :LS1 = 'Nagumo SP'       THEN
      'R$ '||TO_CHAR((SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 2), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
           WHEN :LS1 = 'Rio de Janeiro'  THEN
      'R$ '||TO_CHAR((SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 3), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
           WHEN :LS1 = 'Mixter'          THEN
      'R$ '||TO_CHAR((SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 4), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
           WHEN :LS1 = 'Hibrido'         THEN
      'R$ '||TO_CHAR((SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 7), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
      END PRECO_ENCARTE,
      CASE WHEN :LS1 = 'Nagumo SP'       THEN
      'R$ '||TO_CHAR((SELECT PP.PRECOCARTAO FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 2), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
           WHEN :LS1 = 'Rio de Janeiro'  THEN
      'R$ '||TO_CHAR((SELECT PP.PRECOCARTAO FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 3), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
      END PRECO_CARTAO,
      P.OBSENCARTE LEGENDA,
      CASE WHEN NVL(PC.PRECOVALIDNORMAL, PC.PRECOBASENORMAL) < 
      CASE WHEN :LS1 = 'Nagumo SP'       THEN
      (SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 2)
           WHEN :LS1 = 'Rio de Janeiro'  THEN
      (SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 3)
           WHEN :LS1 = 'Mixter'          THEN
      (SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 4)
           WHEN :LS1 = 'Hibrido'         THEN
      (SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 7)
      END
      THEN 'Preço Normal Maior que Oferta' 
      WHEN
        CASE WHEN :LS1 = 'Nagumo SP'       THEN
      (SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 2)
           WHEN :LS1 = 'Rio de Janeiro'  THEN
      (SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 3)
           WHEN :LS1 = 'Mixter'          THEN
      (SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 4)
           WHEN :LS1 = 'Hibrido'         THEN
      (SELECT PP.PRECOPROMOC FROM MRL_ENCARTEPRODUTOPRECO PP    WHERE PP.SEQENCARTE   = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO AND PP.NROAGRUPAMENTO = 7)
      END = 0
      THEN 'Preco de Oferta Zerado'
        ELSE NULL END OBS, XI.SEQPRODUTO
      
  FROM MRL_ENCARTE X INNER JOIN MRL_ENCARTEPRODUTO XI         ON XI.SEQENCARTE   = X.SEQENCARTE
                     INNER JOIN MAP_PRODUTO P                 ON P.SEQPRODUTO    = XI.SEQPRODUTO
                     INNER JOIN MAP_FAMILIA F                 ON F.SEQFAMILIA    = P.SEQFAMILIA
                     INNER JOIN CONSINCO.MRL_ENCARTENOMEPAG G ON G.SEQENCARTE    = X.SEQENCARTE AND G.NROPAGINA = XI.NROPAGINA
                     INNER JOIN MAP_FAMDIVISAO C              ON C.SEQFAMILIA    = P.SEQFAMILIA
                     INNER JOIN MAX_COMPRADOR CO              ON CO.SEQCOMPRADOR = C.SEQCOMPRADOR
                     INNER JOIN MAX_EMPRESA EMP               ON EMP.NROEMPRESA  = DECODE(:LS1, 'Nagumo SP',8 ,
                                                                                                'Mixter'   ,41,
                                                                                                'Hibrido'  ,54,
                                                                                                'Rio de Janeiro',36)
                     INNER JOIN MRL_PRODEMPSEG PC             ON PC.NROEMPRESA   = DECODE(:LS1, 'Nagumo SP',8 ,
                                                                                                'Mixter'   ,41,
                                                                                                'Hibrido'  ,54,
                                                                                                'Rio de Janeiro',36)
                                                             AND NROSEGMENTO = EMP.NROSEGMENTOPRINC 
                                                             AND PC.QTDEMBALAGEM = XI.QTDEMBALAGEM 
                                                             AND PC.SEQPRODUTO = XI.SEQPRODUTO
   WHERE 1 = 1
     AND X.SEQENCARTE = :NR1
   ORDER BY PAG, 11) XX
   
   WHERE PRECO_ENCARTE != 'R$ 0,00'
   
   ORDER BY 6, 11
