SELECT X.COMPRADOR, 
       'R$ '||TO_CHAR(Y.LIMITE,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') LIMITE, 
       'R$ '||TO_CHAR(Y.VLRUTILIZADO,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') UTILIZADO_NORMAL, 
       'R$ '||TO_CHAR(Y.VALORLIBERADOSENHA,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') LIBERADO_POR_SENHA,
       'R$ '||TO_CHAR(VLRTOTALUTIL,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_UTILIZADO, 
       'R$ '||TO_CHAR(VLRDISPONIVEL,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') DISPONIVEL
 FROM CONSINCO.NAGV_LIMITECOMPRADOR Y INNER JOIN CONSINCO.MAX_COMPRADOR X ON X.SEQCOMPRADOR = Y.SEQCOMPRADOR
 
 ORDER BY 1; 
