SELECT DISTINCT BS.SEQPRODUTO MATERIAL, DESCCOMPLETA, F.SEQFORNECEDOR||' - '||G.NOMERAZAO FORNEC_PRINC,
      (SELECT DECODE(MIN(STATUSCOMPRA), 'A','ATIVO','I','INATIVO','SUSPENSO') FROM MRL_PRODUTOEMPRESA E WHERE E.SEQPRODUTO = BS.SEQPRODUTO) STATUS_COMPRA,
      (SELECT DECODE(MIN(STATUSVENDA), 'A','ATIVO','I','INATIVO') FROM MRL_PRODEMPSEG S WHERE S.QTDEMBALAGEM = 1 AND S.SEQPRODUTO = BS.SEQPRODUTO) STATUS_VENDA,
      (SELECT SUM(ESTQLOJA + ESTQDEPOSITO) FROM MRL_PRODUTOEMPRESA S WHERE S.SEQPRODUTO = BS.SEQPRODUTO) ESTOQUE_VOL,
      (SELECT SUM(ESTQLOJA + ESTQDEPOSITO) FROM MRL_PRODUTOEMPRESA S WHERE S.SEQPRODUTO = BS.SEQPRODUTO) * PRECOVALIDNORMAL ESTOQUE_PR_VENDA,
      (SELECT SUM(ESTQLOJA + ESTQDEPOSITO) FROM MRL_PRODUTOEMPRESA S WHERE S.SEQPRODUTO = BS.SEQPRODUTO) * E.CMULTVLRNF ESTOQUE_CTO,
      -- Impostos
      ROUND(E.CMULTVLRNF,4) ULT_CTO_NF, 
      ROUND(E.CMULTCREDICMSEMP,4) ICMS_ENT,
      T.PERALIQUOTA ALIQ_ICMS_SAI, 
      ROUND(E.CMULTIPI,4) IPI_ENT, 
      ROUND(E.CMULTCREDPIS,4) PIS_ENT, 
      ROUND(E.CMULTCREDCOFINS,4) COFINS_ENT,
      ROUND(E.CMULTICMSST,4) ICMSST_ENT, 
      --
      CODCEST CEST, FM.CODNBMSH NCM, S.PRECOVALIDNORMAL PRECO_VENDA_UNIT, FD.MARGEMLUCRODIVISAO MARGEM_CAD,
      (SELECT ROUND(MGMPRECOVALIDO,2) FROM MAXV_MGMBASEPRODSEG Y WHERE Y.SEQPRODUTO = BS.SEQPRODUTO AND Y.NROEMPRESA = S.NROEMPRESA AND Y.NROSEGMENTO = S.NROSEGMENTO AND Y.QTDEMBALAGEM = 1) MARGEM_REAL

  FROM NAGT_BASE_PRODSAIDAST BS INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = BS.SEQPRODUTO
                                INNER JOIN MAP_FAMFORNEC F ON F.SEQFAMILIA = P.SEQFAMILIA AND F.PRINCIPAL = 'S'
                                INNER JOIN GE_PESSOA G ON G.SEQPESSOA = F.SEQFORNECEDOR
                                INNER JOIN MRL_PRODUTOEMPRESA E ON E.SEQPRODUTO = BS.SEQPRODUTO AND NROEMPRESA = :NR1
                                INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = E.NROEMPRESA
                                INNER JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = BS.SEQPRODUTO AND S.NROEMPRESA = E.NROEMPRESA AND S.NROSEGMENTO = M.NROSEGMENTOPRINC AND QTDEMBALAGEM = 1
                                INNER JOIN MAP_FAMILIA FM ON FM.SEQFAMILIA = P.SEQFAMILIA
                                INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = P.SEQFAMILIA
                                INNER JOIN MAP_TRIBUTACAOUF T ON T.NROTRIBUTACAO = FD.NROTRIBUTACAO AND T.UFCLIENTEFORNEC = 'SP' AND T.UFEMPRESA = 'SP' AND T.NROREGTRIBUTACAO = 0 AND T.TIPTRIBUTACAO = 'SN'
                                
 WHERE 1=1
