SELECT X.SEQPROMOCAO,
       X.NROEMPRESA LOJA,
       X.PROMOCAO DESCRICAO_PROMOC,
       TO_CHAR(X.DTAINICIO, 'DD/MM/YYYY') DTAINICIO,
       TO_CHAR(X.DTAFIM, 'DD/MM/YYYY') DTAFIM,
       X.NROSEGMENTO||' - '||O.SEGMENTO SEGMENTO
       
  FROM MRL_PROMOCAO X INNER JOIN MON_SEGMENTO O ON O.nrosegmento = X.NROSEGMENTO
                      
 WHERE 1=1 
       AND X.DTAFIM = :DT2
AND X.NROEMPRESA IN (#LS1)
       AND (SELECT COUNT(XI.SEQPRODUTO) FROM MRL_PROMOCAOITEM XI INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                                                                 INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA
                                                                 INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = F.SEQCOMPRADOR
             WHERE XI.SEQPROMOCAO = X.SEQPROMOCAO AND XI.NROEMPRESA = X.NROEMPRESA AND XI.STATUS = 'A' AND C.COMPRADOR IN (#LS2)) > 0
       
 ORDER BY 2,1;
 
