SELECT DISTINCT USUARIOMAQUINA, A.USUALTERACAO, OPERACAO, DTAHORAALTERACAOLOG,
       SEQPRODUTO, QTDLIMITEVERBA, OBSERVACAO
FROM CONSINCO.MRL_CUSTOVERBA_LOG A WHERE SEQVERBA = 7 AND NROEMPRESA = 8 AND CODIGOVERBA = '1748868L7'
