-- QRP em https://github.com/GiulianoGMS/QRPs/blob/main/RelPromocCombinadas.QRP

SELECT * FROM (WITH
Brindes AS (
    SELECT 
        X.SEQPROMOCPDV, P.DESCCOMPLETA DESCCOMPLETA, 
        X.DESCRICAO||' - Período - De: '||TO_CHAR(X.DTAINICIO, 'DD/MM/YYYY')||' Até: '||TO_CHAR(X.DTAFIM, 'DD/MM/YYYY') TIT_PROMOC, XE.NROEMPRESA LJ,
        XI.SEQGRUPO,
        XI.SEQPRODUTO,
        ROW_NUMBER() OVER (PARTITION BY X.SEQPROMOCPDV ORDER BY XI.SEQPRODUTO) AS RN, G.QTDITEMGRUPO, 
        CASE WHEN DECODE(XI.PRECOITEM, 0, S.PRECOVALIDNORMAL - (S.PRECOVALIDNORMAL * XI.PERCDESCONTO) / 100, PRECOITEM) < 0.01 THEN 0.01 ELSE
          DECODE(XI.PRECOITEM, 0, S.PRECOVALIDNORMAL - (S.PRECOVALIDNORMAL * XI.PERCDESCONTO) / 100, PRECOITEM) END PRECOITEM
    FROM MFL_PROMOCAOPDV X INNER JOIN MFL_PROMOCPDVITEM XI ON XI.SEQPROMOCPDV = X.SEQPROMOCPDV
                           INNER JOIN MFL_PROMOCPDVEMP XE  ON XE.SEQPROMOCPDV = X.SEQPROMOCPDV
                           INNER JOIN MFL_PROMOCPDVGRUPO G ON G.SEQPROMOCPDV = X.SEQPROMOCPDV AND G.SEQGRUPO = XI.SEQGRUPO
                           INNER JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = XI.SEQPRODUTO AND S.NROEMPRESA = XE.NROEMPRESA AND S.QTDEMBALAGEM = 1
                           INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
    WHERE X.STATUS = 'A'
      AND XI.STATUS = 'A'
      AND XE.STATUS = 'A'
      AND S.NROSEGMENTO = (SELECT C.NROSEGMENTOPRINC FROM MAX_EMPRESA C WHERE C.NROEMPRESA = XE.NROEMPRESA)
      AND XE.NROEMPRESA = #LS1
      AND XI.TIPOITEMPROMOC = 'P'
      AND :DT1 BETWEEN DTAINICIO AND DTAFIM
),
Normais AS (
    SELECT 
        X.SEQPROMOCPDV, P.DESCCOMPLETA, X.DESCRICAO||' - Período - De: '||TO_CHAR(X.DTAINICIO, 'DD/MM/YYYY')||' Até: '||TO_CHAR(X.DTAFIM, 'DD/MM/YYYY') TIT_PROMOC, XE.NROEMPRESA LJ,
        XI.SEQGRUPO,
        XI.SEQPRODUTO,
        ROW_NUMBER() OVER (PARTITION BY X.SEQPROMOCPDV ORDER BY XI.SEQPRODUTO) AS RN, QTDITEMGRUPO, S.PRECOVALIDNORMAL PRECOITEM
    FROM MFL_PROMOCAOPDV X INNER JOIN MFL_PROMOCPDVITEM XI ON XI.SEQPROMOCPDV = X.SEQPROMOCPDV
                           INNER JOIN MFL_PROMOCPDVEMP XE  ON XE.SEQPROMOCPDV = X.SEQPROMOCPDV
                           INNER JOIN MFL_PROMOCPDVGRUPO G ON G.SEQPROMOCPDV = X.SEQPROMOCPDV AND G.SEQGRUPO = XI.SEQGRUPO
                           INNER JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = XI.SEQPRODUTO AND S.NROEMPRESA = XE.NROEMPRESA AND S.QTDEMBALAGEM = 1
                           INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
    WHERE X.STATUS = 'A'
      AND XI.STATUS = 'A'
      AND XE.STATUS = 'A'
      AND S.NROSEGMENTO = (SELECT C.NROSEGMENTOPRINC FROM MAX_EMPRESA C WHERE C.NROEMPRESA = XE.NROEMPRESA)
      AND XE.NROEMPRESA = #LS1
      AND XI.TIPOITEMPROMOC = 'N'
      AND :DT1 BETWEEN DTAINICIO AND DTAFIM
)
SELECT 
    P.SEQPROMOCPDV||' - '||P.TIT_PROMOC PROMOCAO, P.LJ, 'De: '||TO_CHAR(:DT1, 'DD/MM/YYYY')||' Até: '||TO_CHAR(:DT2, 'DD/MM/YYYY') DATA,
    L.SEQPRODUTO Item_Normal, L.DESCCOMPLETA DescNormal, L.QTDITEMGRUPO QTD_NORMAL, CASE WHEN L.PRECOITEM > 0 THEN 'R$ ' ELSE NULL END || TO_CHAR(L.PRECOITEM,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') PRECO_N,
    P.SEQPRODUTO Item_Brinde, P.DESCCOMPLETA DescBrinde, P.QTDITEMGRUPO QTD_BRINDE, CASE WHEN P.PRECOITEM > 0 THEN 'R$ ' ELSE NULL END || TO_CHAR(P.PRECOITEM,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') PRECO_P
    
FROM Brindes P FULL JOIN Normais L ON L.SEQPROMOCPDV = P.SEQPROMOCPDV AND L.RN = P.RN

ORDER BY L.SEQPROMOCPDV, L.RN);

