SELECT P.SEQPRODUTO SKU, DESCCOMPLETA,
       CASE WHEN EXISTS (SELECT 1 FROM MAP_FAMFORNEC FC INNER JOIN GE_PESSOA G ON G.SEQPESSOA = FC.SEQFORNECEDOR
                      WHERE FC.SEQFAMILIA = P.SEQFAMILIA
                        AND G.UF = 'EX') THEN 'IMP DIRETA' ELSE 'IMP INDIRETA' END TIPO_IMPORTACAO
                        
  FROM MAP_PRODUTO P INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                     INNER JOIN MAP_FAMATRIBUTO A ON A.SEQFAMILIA = F.SEQFAMILIA
                     
                     WHERE A.DESCATRIBUTO = 'Produto Importado'

ORDER BY 2
