SELECT CASE WHEN F.SEQGERCOMPRA IS NULL THEN 'Ped Avulso: '||XX.NROPEDIDOSUPRIM||' - '||GG.NOMERAZAO ELSE F.SEQGERCOMPRA||' - '||GG.NOMERAZAO END LOTE_FORNEC_PED,
       DTALANCAMENTO,
       USULANCAMENTO,
       SUM(VALOR) VALOR
  FROM MAC_CCLIMCOMPRA XX INNER JOIN MSU_PEDIDOSUPRIM P ON P.NROPEDIDOSUPRIM = XX.NROPEDIDOSUPRIM AND XX.NROEMPRESA = P.NROEMPRESA
                           LEFT JOIN MAC_GERCOMPRA G ON G.SEQGERCOMPRA = P.SEQGERCOMPRA 
                           LEFT JOIN MAC_GERCOMPRAFORN F ON F.SEQGERCOMPRA = G.SEQGERCOMPRA
                           LEFT JOIN GE_PESSOA GG ON GG.SEQPESSOA = F.SEQFORNECEDOR OR P.SEQFORNECEDOR = GG.SEQPESSOA
                          
  
 WHERE XX.SEQCOMPRADOR = 295
   AND DTALANCAMENTO >= DATE '2025-05-01'
     
 GROUP BY DTALANCAMENTO, USULANCAMENTO, XX.SEQCOMPRADOR, 
          CASE WHEN F.SEQGERCOMPRA IS NULL THEN 'Ped Avulso: '||XX.NROPEDIDOSUPRIM||' - '||GG.NOMERAZAO ELSE F.SEQGERCOMPRA||' - '||GG.NOMERAZAO END
 
 ORDER BY 2 DESC;

------------ Antiga

SELECT *
FROM MAC_CCLIMCOMPRA XX  
 WHERE XX.SEQCOMPRADOR = 295
 AND DTALANCAMENTO >= DATE '2025-05-01'
 AND NROPEDIDOSUPRIM IN (SELECT DISTINCT NROPEDIDOSUPRIM FROM MSU_PEDIDOSUPRIM Z WHERE SEQGERCOMPRA IN (373080))
ORDER BY DTAHORLANCAMENTO DESC;
