SELECT NVL(CUST.NROACORDOAGRUP, A.NROACORDO) NROACORDO,
       A.SEQFORNECEDOR SEQFORNEC, MAX(A.RESPACORDONOME) RESP, MAX(A.RESPACORDODOCTO) RESP_DOCTO,
       G.NOMERAZAO RAZAO_FORN, G.CIDADE||' - '||G.UF CIDADE_FORN, G.LOGRADOURO||' '||G.NROLOGRADOURO END_FORNEC, 
       FC5CPFCNPJMASK(G.NROCGCCPF, G.DIGCGCCPF, 'J') CNPJ_FORN,
       M.NOMERAZAO RAZAO_EMP, M.CIDADE ||' - '||M.UF CIDADE_EMP,  M.LOGRADOURO||' '||M.NROLOGRADOURO|| ' - '||M.BAIRRO END_EMP,
       FC5CPFCNPJMASK(M.NROCGCCPF, M.DIGCGCCPF, 'J') CNPJ_EMP,
      'R$ '||TO_CHAR(SUM(A.VLRACORDO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR, 
       RPAD(FC5EXTENSO(SUM(A.VLRACORDO)),66,'*') VALOR_EXTENSO,
      'ACORDO REF. PEDIDO(S): '||LISTAGG(CUST.NROPEDIDOSUPRIM, ' - ') WITHIN GROUP (ORDER BY CUST.NROPEDIDOSUPRIM) PEDIDOS,
       A.REFERENCIAACORDO, TO_CHAR(SYSDATE, 'DD "de" Month "de" YYYY', 'NLS_DATE_LANGUAGE = Portuguese') DATA_HOJE,
       COMPRADOR
         
  FROM MSU_ACORDOPROMOC A INNER JOIN MAC_TIPOACORDO B ON A.CODTIPOACORDO = B.CODTIPOACORDO
                          LEFT  JOIN MRL_FORMAPAGTO C ON A.NROFORMAPAGTO = C.NROFORMAPAGTO
                          INNER JOIN GE_PESSOA G      ON G.SEQPESSOA = A.SEQFORNECEDOR
                          INNER JOIN ESP_ACORDOPROMOCPEDIDO CUST ON CUST.NROACORDO = A.NROACORDO -- Customizada Acordos Agrupados
                          INNER JOIN GE_PESSOA M      ON M.SEQPESSOA = CUST.NROEMPRESAACORDOAGRUP
                          INNER JOIN MAX_COMPRADOR CO ON CO.SEQCOMPRADOR = A.SEQCOMPRADOR

 WHERE 1=1 
   AND CUST.NROACORDOAGRUP = (SELECT NROACORDOAGRUP FROM ESP_ACORDOPROMOCPEDIDO A1 WHERE A1.NROACORDO = 24900)
   
   GROUP BY G.NOMERAZAO, G.CIDADE, G.LOGRADOURO, G.NROLOGRADOURO, G.NROCGCCPF, G.DIGCGCCPF, G.UF, A.SEQFORNECEDOR, 
            M.NOMERAZAO, M.CIDADE, M.LOGRADOURO, M.NROLOGRADOURO, M.NROCGCCPF, M.DIGCGCCPF, M.UF, M.BAIRRO, A.REFERENCIAACORDO, COMPRADOR, NVL(CUST.NROACORDOAGRUP, A.NROACORDO)
            
