SELECT P.SEQPROMOCPDV COD,
       P.DESCRICAO DESC_PROMOCAO,
       P.DTAINICIO,
       P.DTAFIM, DI.SEQPRODUTO PLU, PR.DESCCOMPLETA DESC_PROD,
       TO_CHAR(SUM(DI.VLRITEM) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_BRUTO, 
       TO_CHAR(SUM(DI.VLRDESCONTO) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_DESCONTO, 
       TO_CHAR((SUM(DI.VLRITEM) - SUM(DI.VLRDESCONTO)) * SUM(DI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_COM_DESC,
       SUM(DI.QUANTIDADE) QUANTIDADE_TOTAL

  FROM MFL_PROMOCAOPDV P INNER JOIN MFL_DFITEM DI ON DI.SEQPROMOCPDV = P.SEQPROMOCPDV AND DI.STATUSITEM != 'C'
                         INNER JOIN MFL_PROMOCPDVITEM PI ON PI.SEQPROMOCPDV = P.SEQPROMOCPDV AND PI.SEQPRODUTO = DI.SEQPRODUTO
                         INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = DI.SEQPRODUTO

 WHERE 1 = 1
   AND DTAINICIO > SYSDATE - 100
   AND VLRDESCONTO > 0

GROUP BY P.SEQPROMOCPDV, P.DESCRICAO, P.DTAINICIO, P.DTAFIM, DI.SEQPRODUTO, PR.DESCCOMPLETA
