-- Estoque Por Palete

SELECT Z.NROEMPRESA, Z.SEQPRODUTO PLU, DESCCOMPLETA, TO_NUMBER(ESTQLOJA) EST_UNIT, ROUND(ESTQLOJA / C.PADRAOEMBCOMPRA) ESTQ_CXS, --PALETELASTRO, PALETEALTURA,
       CASE WHEN PALETELASTRO > 0 AND PALETEALTURA > 0 THEN
         ROUND((ESTQLOJA / C.PADRAOEMBCOMPRA) / (A.PALETELASTRO * A.PALETEALTURA),2)
       ELSE NULL END ESTOQUE_EM_PLTS
       
  FROM MRL_PRODUTOEMPRESA Z INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = Z.SEQPRODUTO
                            INNER JOIN MRL_PRODEMPRESAWM   A ON A.SEQPRODUTO = Z.SEQPRODUTO AND A.NROEMPRESA = Z.NROEMPRESA
                            INNER JOIN MAP_FAMDIVISAO C ON C.SEQFAMILIA = P.SEQFAMILIA 
 WHERE Z.ESTQLOJA > 0
   AND Z.NROEMPRESA = 56

ORDER BY 4 DESC
