ALTER SESSION SET current_schema = CONSINCO;

SELECT * FROM (
SELECT * FROM 
(SELECT C.APELIDO, I.SEQPRODUTO, K.DESCCOMPLETA, I.PRECOVALIDNORMAL, I.PRECOVALIDNORMAL / QTDEMBALAGEM PRECO_UNI1,
       (SELECT II.PRECOVALIDNORMAL / QTDEMBALAGEM PR_UNI
  FROM MRL_PRODEMPSEG II LEFT JOIN MAP_PRODUTO KK ON II.SEQPRODUTO = KK.SEQPRODUTO 
 WHERE II.NROEMPRESA = 54 AND STATUSVENDA = 'A' AND II.NROSEGMENTO = 7 AND  PRECOVALIDNORMAL != 0 AND QTDEMBALAGEM > 1 AND II.SEQPRODUTO NOT IN (248414,836135)
 AND II.SEQPRODUTO = I.SEQPRODUTO) PRECO_ATACADO_UNI,
        I.PRECOVALIDNORMAL - (SELECT II.PRECOVALIDNORMAL / QTDEMBALAGEM PR_UNI
  FROM MRL_PRODEMPSEG II LEFT JOIN MAP_PRODUTO KK ON II.SEQPRODUTO = KK.SEQPRODUTO
 WHERE II.NROEMPRESA = 54 AND STATUSVENDA = 'A' AND II.NROSEGMENTO = 7 AND  PRECOVALIDNORMAL != 0 AND QTDEMBALAGEM > 1 AND II.SEQPRODUTO NOT IN (248414,836135)
 AND II.SEQPRODUTO = I.SEQPRODUTO) DIF,
 ROUND(((I.PRECOVALIDNORMAL - (SELECT II.PRECOVALIDNORMAL / QTDEMBALAGEM PR_UNI
  FROM MRL_PRODEMPSEG II LEFT JOIN MAP_PRODUTO KK ON II.SEQPRODUTO = KK.SEQPRODUTO
 WHERE II.NROEMPRESA = 54 AND STATUSVENDA = 'A' AND II.NROSEGMENTO = 7 AND  PRECOVALIDNORMAL != 0 AND QTDEMBALAGEM > 1 AND II.SEQPRODUTO NOT IN (248414,836135)
 AND II.SEQPRODUTO = I.SEQPRODUTO)) * 100) / I.PRECOVALIDNORMAL,2) PERC
 
  FROM MRL_PRODEMPSEG I LEFT JOIN MAP_PRODUTO K ON I.SEQPRODUTO = K.SEQPRODUTO
                        LEFT JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = K.SEQFAMILIA
                        LEFT JOIN MAX_COMPRADOR C  ON C.SEQCOMPRADOR = F.SEQCOMPRADOR
 WHERE I.NROEMPRESA = 54 AND STATUSVENDA = 'A' AND I.NROSEGMENTO = 7 AND  PRECOVALIDNORMAL != 0 AND I.SEQPRODUTO IN (
SELECT J.SEQPRODUTO FROM MRL_PRODEMPSEG J WHERE J.NROEMPRESA = 54 AND J.NROSEGMENTO = 7 AND STATUSVENDA = 'A' AND J.QTDEMBALAGEM > 1) AND I.QTDEMBALAGEM = 1
) 
WHERE PRECO_UNI1 != PRECO_ATACADO_UNI 

) 

WHERE PERC >= 5 
ORDER BY 1,3,8 DESC
