SELECT C.CATEGORIAN1, C.CATEGORIAN2, C.CATEGORIAN3, 
       X.SEQPRODUTO PLU, P.DESCCOMPLETA, X.PALETELASTRO LASTRO, X.PALETELASTRO * X.PALETEALTURA PALETE,
       E.PERCVARIACAOSUG PERC_ARRED
       
  FROM MRL_PRODEMPRESAWM X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO
                           INNER JOIN MAP_FAMFORNEC F ON F.SEQFAMILIA = P.SEQFAMILIA
                           INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA
                           INNER JOIN MRL_PRODUTOEMPRESA E ON E.NROEMPRESA = X.NROEMPRESA AND E.SEQPRODUTO = X.SEQPRODUTO
   
 WHERE X.NROEMPRESA = 507
   AND F.SEQFORNECEDOR = 115549
