ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT A.NROEMPRESA EMPRESA, D.DESCSEGMENTO SEGMENTO, A.SEQPRODUTO PLU, B.SEQFAMILIA, DESCCOMPLETA DESCRICAO, PRECOBASENORMAL PRECO, 
       CONSINCO.NAGF_CUSTOFAMFORNECPRINC(B.SEQFAMILIA,CASE WHEN A.NROEMPRESA IN (36,53) THEN 'RJ' ELSE 'SP' END,1) CUSTO,
       ROUND(CONSINCO.FC5MARGEMPRECO(A.SEQPRODUTO, A.NROEMPRESA, A.NROSEGMENTO, QTDEMBALAGEM,CONSINCO.NAGF_CUSTOFAMFORNECPRINC(B.SEQFAMILIA,
                                                                                             CASE WHEN A.NROEMPRESA IN (36,53) THEN 'RJ' ELSE 'SP' END,1),PRECOBASENORMAL),2) MARGEM,
       E.CATEGORIA_NIVEL_1 CATEGORIA
       
 FROM CONSINCO.MRL_PRODEMPSEG A INNER JOIN MAP_PRODUTO B              ON A.SEQPRODUTO  = B.SEQPRODUTO 
                                LEFT JOIN  MRL_PRODUTOEMPRESA F       ON F.NROEMPRESA  = A.NROEMPRESA AND F.SEQPRODUTO = A.SEQPRODUTO
                                INNER JOIN MON_EMPRESASEGMENTO C      ON A.NROEMPRESA  = C.NROEMPRESA AND A.NROSEGMENTO = C.NROSEGMENTO AND C.ATIVO = 'S'
                                INNER JOIN CONSINCO.MAD_SEGMENTO D    ON D.NROSEGMENTO = A.NROSEGMENTO 
                                LEFT JOIN  QLV_CATEGORIA@CONSINCODW E ON B.SEQFAMILIA  = E.SEQFAMILIA
                                LEFT JOIN  MAP_FAMILIA G              ON B.SEQFAMILIA  = G.SEQFAMILIA
 WHERE STATUSVENDA  = 'A'
   AND QTDEMBALAGEM = 1
   AND E.CATEGORIA_NIVEL_1 = :LS1
   AND A.NROEMPRESA IN (:LS2)
   AND B.SEQFAMILIA = :NR1
      
 ORDER BY 4 ASC
