SELECT DISTINCT X.SEQPRODUTO COD_PROD, 
       TO_CHAR((SELECT LISTAGG(CODACESSO, ', ') WITHIN GROUP (ORDER BY CODACESSO)
          FROM (SELECT DISTINCT C.CODACESSO
                  FROM MAP_PRODCODIGO C
                 WHERE C.SEQPRODUTO = X.SEQPRODUTO
                   AND C.TIPCODIGO = 'E'
                   AND C.INDUTILVENDA = 'S'))) COD_EAN,
       DESCCOMPLETA, DESCCOMPLETA, SUM(ESTQLOJA) ESTQLOJAS, 
       MAX(PRECOVALIDNORMAL) PRECO_DE, 
       ROUND((MAX(PRECOVALIDNORMAL) - ((MAX(PRECOVALIDNORMAL) / 100) * 30)),2) PRECO_PARA, 
      '30%' PERC_DESC,
      (MAX(PRECOVALIDNORMAL) / 100) * 30 TOT_DESC
       
  FROM MRL_PRODUTOEMPRESA X INNER JOIN MAP_PRODUTO A    ON A.SEQPRODUTO   = X.SEQPRODUTO
                            INNER JOIN MAX_EMPRESA M    ON M.NROEMPRESA   = X.NROEMPRESA
                            INNER JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO   = X.SEQPRODUTO 
                                                       AND S.NROSEGMENTO  = M.NROSEGMENTOPRINC
                                                       AND S.NROEMPRESA   = X.NROEMPRESA
                                                       AND S.QTDEMBALAGEM = 1
                             LEFT JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = X.SEQPRODUTO AND C.TIPCODIGO = 'E' AND C.INDUTILVENDA = 'S'
 WHERE X.ESTQLOJA > 0
   AND EXISTS(SELECT 1 FROM DIM_CATEGORIA@CONSINCODW B WHERE A.SEQFAMILIA = B.SEQFAMILIA AND B.CATEGORIAN3 = 'VINHO')

GROUP BY X.SEQPRODUTO, DESCCOMPLETA

ORDER BY 2
