WITH margemMAX AS (SELECT 30 Percentual, --<< passar o percentual max de divergencia de faixa aqui
                          56 NroEmpresa  --<< NroEMpresa da consulta
                     FROM DUAL)

SELECT COMPRADOR, CATEGORIAN3, PLU, DESCCOMPLETA, ESTQLOJA,
       QTD_EMB1 QTD1, PRECO_UNI_EMB1,
       QTD_EMB2 QTD2, PRECO_UNI_EMB2, PRECO_UNI_EMB1 - PRECO_UNI_EMB2 DIF,
       QTD_EMB3 QTD3, PRECO_UNI_EMB3, PRECO_UNI_EMB1 - PRECO_UNI_EMB3 DIF,
       QTD_EMB4 QTD4, PRECO_UNI_EMB4, PRECO_UNI_EMB1 - PRECO_UNI_EMB4 DIF
       
  FROM (

SELECT COMPRADOR, SUB.SEQPRODUTO PLU, DESCCOMPLETA, ESTQLOJA,
       MAX(CASE WHEN RN = 1 THEN QTDEMBALAGEM END) QTD_EMB1,
       MAX(CASE WHEN RN = 1 THEN ROUND(PRECOVALIDNORMAL/QTDEMBALAGEM,2) END) PRECO_UNI_EMB1,
       MAX(CASE WHEN RN = 2 THEN QTDEMBALAGEM END) QTD_EMB2,
       MAX(CASE WHEN RN = 2 THEN ROUND(PRECOVALIDNORMAL/QTDEMBALAGEM,2) END) PRECO_UNI_EMB2,
       MAX(CASE WHEN RN = 3 THEN QTDEMBALAGEM END) QTD_EMB3,
       MAX(CASE WHEN RN = 3 THEN ROUND(PRECOVALIDNORMAL/QTDEMBALAGEM,2) END) PRECO_UNI_EMB3,
       MAX(CASE WHEN RN = 4 THEN QTDEMBALAGEM END) QTD_EMB4,
       MAX(CASE WHEN RN = 4 THEN ROUND(PRECOVALIDNORMAL/QTDEMBALAGEM,2) END) PRECO_UNI_EMB4, CATEGORIAN3
           
  FROM (SELECT SEQPRODUTO,
               QTDEMBALAGEM,
               PRECOVALIDNORMAL,
               ROW_NUMBER() OVER(PARTITION BY SEQPRODUTO ORDER BY QTDEMBALAGEM) AS RN, X.NROEMPRESA
          FROM MRL_PRODEMPSEG X INNER JOIN MAX_EMPRESA EM ON EM.NROEMPRESA = X.NROEMPRESA AND X.NROSEGMENTO = EM.NROSEGMENTOPRINC
                                INNER JOIN margemMAX ON margemMAX.Nroempresa = X.NROEMPRESA
         WHERE 1=1
           AND STATUSVENDA = 'A'
           AND PRECOVALIDNORMAL > 0
           AND EXISTS (SELECT 1 FROM MRL_PRODUTOEMPRESA A WHERE A.NROEMPRESA = X.NROEMPRESA AND A.STATUSCOMPRA = 'A' AND A.SEQPRODUTO = X.SEQPRODUTO)
       )
           
           SUB INNER JOIN MAP_PRODUTO P     ON P.SEQPRODUTO = SUB.SEQPRODUTO 
               INNER JOIN MAP_FAMILIA F     ON F.SEQFAMILIA = P.SEQFAMILIA
               INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = F.SEQFAMILIA
               INNER JOIN MAX_COMPRADOR M   ON M.SEQCOMPRADOR = FD.SEQCOMPRADOR
               INNER JOIN MRL_PRODUTOEMPRESA A ON A.SEQPRODUTO = SUB.SEQPRODUTO AND A.NROEMPRESA = SUB.NROEMPRESA
               INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA
           
 GROUP BY SUB.SEQPRODUTO, COMPRADOR, DESCCOMPLETA, ESTQLOJA, C.CATEGORIAN3) LEFT JOIN margemMAX ON 1=1
 
 WHERE 1=1
   AND (((PRECO_UNI_EMB1 - PRECO_UNI_EMB2) / PRECO_UNI_EMB1) * 100 > margemMAX.Percentual
    OR  ((PRECO_UNI_EMB1 - PRECO_UNI_EMB3) / PRECO_UNI_EMB1) * 100 > margemMAX.Percentual
    OR  ((PRECO_UNI_EMB1 - PRECO_UNI_EMB4) / PRECO_UNI_EMB1) * 100 > margemMAX.Percentual)
 
 ORDER BY 1,2
