SELECT * FROM (

WITH 

BASE AS
 (SELECT NROEMPRESA,
         MEDVDIAGERAL,
         MEDVDIAGERAL / SUM(MEDVDIAGERAL) OVER() PERC,
         FLOOR(&VL * MEDVDIAGERAL / SUM(MEDVDIAGERAL) OVER()) CX,
         (&VL * MEDVDIAGERAL / SUM(MEDVDIAGERAL) OVER()) -
         FLOOR(&VL * MEDVDIAGERAL / SUM(MEDVDIAGERAL) OVER()) FRACAO
         
    FROM (SELECT A.NROEMPRESA, A.MEDVDIAGERAL
            FROM MRL_PRODUTOEMPRESA A
           WHERE SEQPRODUTO = 458689
             AND MEDVDIAGERAL > 0
           ORDER BY MEDVDIAGERAL DESC) --ORDER BY MEDVDIAGERAL DESC)
   WHERE ROWNUM <= 3), -- Aqui pego só as 3 maiores do rank
   
COM_SOBRA AS
 (SELECT BASE.*,
         ROW_NUMBER() OVER(ORDER BY FRACAO DESC) RANK_SOBRA, -- Rankeia pra descobrir onde vai a caixa que sobrar
         (&VL - SUM(CX) OVER()) SOBRAM
    FROM BASE)
        
SELECT NROEMPRESA,
       MEDVDIAGERAL,
       CX + CASE WHEN RANK_SOBRA <= SOBRAM THEN 1 ELSE 0 END CAIXAS_FINAIS
  FROM COM_SOBRA

 );
 
