SELECT X.COMPRADOR, 
       TO_CHAR(Y.LIMITE,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') LIMITE, 
       TO_CHAR(Y.VLRUTILIZADO,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRUTILIZADONORMAL, 
       TO_CHAR(Y.VALORLIBERADOSENHA,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRLIBERADOSENHA,
       TO_CHAR(VLRTOTALUTIL,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRTOTALUTIL, 
       TO_CHAR(VLRDISPONIVEL,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRDISPONIVEL
 FROM CONSINCO.NAGV_LIMITECOMPRADOR Y INNER JOIN CONSINCO.MAX_COMPRADOR X ON X.SEQCOMPRADOR = Y.SEQCOMPRADOR
 
 ORDER BY 1
