SELECT 
    P.SEQPROMOCPDV COD_PROMOC,
    P.DESCRICAO DESC_PROMOCAO,
    TO_CHAR(P.DTAINICIO, 'DD/MM/YYYY') DTAINICIO,
    TO_CHAR(P.DTAFIM, 'DD/MM/YYYY') DTAFIM, 
    DI.SEQPRODUTO PLU,
    DI.CODPRODUTO EAN, 
    PR.DESCCOMPLETA DESC_PROD,
    TO_CHAR(SUM(DI.VLRITEM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_BRUTO, 
    TO_CHAR(SUM(VLRDESCONTO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_DESCONTO, 
    TO_CHAR(SUM((DI.VLRITEM - DI.VLRDESCONTO)), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL_COM_DESC,
    /*TRUNC((TRUNC(SUM(DI.QUANTIDADE)))/ (SELECT SUM(QTDITEMGRUPO) FROM MFL_PROMOCPDVGRUPO AA WHERE AA.SEQPROMOCPDV = P.SEQPROMOCPDV)) QTD_DESC,*/
    ROUND(SUM(VLRDESCONTO) / TRUNC(MAX(VLRITEM) * MAX(PI.PERCDESCONTO) / 100,2)) QTD_DESC,
    SUM(DI.QUANTIDADE) QUANTIDADE_TOTAL
    
FROM 
    MFL_PROMOCAOPDV P 
    INNER JOIN MFL_DFITEM DI ON DI.SEQPROMOCPDV = P.SEQPROMOCPDV AND DI.STATUSITEM != 'C' 
    INNER JOIN MFL_DOCTOFISCAL D ON D.SEQNF = DI.SEQNF
    INNER JOIN MFL_PROMOCPDVITEM PI ON PI.SEQPROMOCPDV = P.SEQPROMOCPDV AND PI.SEQPRODUTO = DI.SEQPRODUTO AND PI.TIPOITEMPROMOC = 'P'
    INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = DI.SEQPRODUTO

WHERE 1=1
   AND P.SEQPROMOCPDV = :NR1
   AND DI.NROEMPRESA IN (#LS1)
   AND D.DTAMOVIMENTO BETWEEN :DT1 AND :DT2
   
HAVING ROUND(SUM(VLRDESCONTO) / TRUNC(MAX(VLRITEM) * MAX(PI.PERCDESCONTO) / 100,2)) > 0
GROUP BY 
    P.SEQPROMOCPDV, P.DESCRICAO, P.DTAINICIO, P.DTAFIM, DI.SEQPRODUTO, PR.DESCCOMPLETA, DI.CODPRODUTO

UNION ALL

SELECT 
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL 
FROM DUAL

UNION ALL

SELECT COD_PROMOC COD, DESC_PROMOCAO, DTAINICIO, DTAFIM, NULL, NULL, NULL, 
       TO_CHAR(SUM(VALOR_TOTAL_BRUTO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''),
       TO_CHAR(SUM(TOTAL_DESCONTO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), 
       TO_CHAR(SUM(VALOR_TOTAL_COM_DESC), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), 
       SUM(QTD_DESC), SUM(QUANTIDADE_TOTAL)

FROM (

SELECT 
    P.SEQPROMOCPDV COD_PROMOC,
    P.DESCRICAO DESC_PROMOCAO,
    TO_CHAR(P.DTAINICIO, 'DD/MM/YYYY') DTAINICIO,
    TO_CHAR(P.DTAFIM, 'DD/MM/YYYY') DTAFIM, 
    DI.SEQPRODUTO PLU,
    DI.CODPRODUTO EAN, 
    PR.DESCCOMPLETA DESC_PROD,
    SUM(DI.VLRITEM) VALOR_TOTAL_BRUTO, 
    SUM(VLRDESCONTO) TOTAL_DESCONTO, 
    SUM((DI.VLRITEM - DI.VLRDESCONTO)) VALOR_TOTAL_COM_DESC,
    /*TRUNC((TRUNC(SUM(DI.QUANTIDADE)))/ (SELECT SUM(QTDITEMGRUPO) FROM MFL_PROMOCPDVGRUPO AA WHERE AA.SEQPROMOCPDV = P.SEQPROMOCPDV)) QTD_DESC,*/
    ROUND(SUM(VLRDESCONTO) / TRUNC(MAX(VLRITEM) * MAX(PI.PERCDESCONTO) / 100,2)) QTD_DESC,
    SUM(DI.QUANTIDADE) QUANTIDADE_TOTAL
    
FROM 
    MFL_PROMOCAOPDV P 
    INNER JOIN MFL_DFITEM DI ON DI.SEQPROMOCPDV = P.SEQPROMOCPDV AND DI.STATUSITEM != 'C' 
    INNER JOIN MFL_DOCTOFISCAL D ON D.SEQNF = DI.SEQNF
    INNER JOIN MFL_PROMOCPDVITEM PI ON PI.SEQPROMOCPDV = P.SEQPROMOCPDV AND PI.SEQPRODUTO = DI.SEQPRODUTO AND PI.TIPOITEMPROMOC = 'P'
    INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = DI.SEQPRODUTO

WHERE 1=1
   AND P.SEQPROMOCPDV = :NR1
   AND DI.NROEMPRESA IN (#LS1)
   AND D.DTAMOVIMENTO BETWEEN :DT1 AND :DT2
   
HAVING ROUND(SUM(VLRDESCONTO) / TRUNC(MAX(VLRITEM) * MAX(PI.PERCDESCONTO) / 100,2)) > 0
GROUP BY 
    P.SEQPROMOCPDV, P.DESCRICAO, P.DTAINICIO, P.DTAFIM, DI.SEQPRODUTO, PR.DESCCOMPLETA, DI.CODPRODUTO) 

GROUP BY
    COD_PROMOC, DESC_PROMOCAO, DTAINICIO, DTAFIM;
    
    SELECT NUMERODF, SEQPRODUTO, QUANTIDADE, VLRITEM, VLRDESCONTO FROM MFL_DFITEM XI WHERE 1=1 and SEQPROMOCPDV = 2437 AND STATUSITEM != 'C';

