SELECT COMPRADOR, PLU, DESCCOMPLETA, ESTQLOJA,
       QTD_EMB1 QTD1, PRECO_UNI_EMB1,
       QTD_EMB2 QTD2, PRECO_UNI_EMB2, PRECO_UNI_EMB1 - PRECO_UNI_EMB2 DIF,
       QTD_EMB3 QTD3, PRECO_UNI_EMB3, PRECO_UNI_EMB1 - PRECO_UNI_EMB3 DIF,
       QTD_EMB4 QTD4, PRECO_UNI_EMB4, PRECO_UNI_EMB1 - PRECO_UNI_EMB4 DIF
       
  FROM (

SELECT COMPRADOR, SUB.SEQPRODUTO PLU, DESCCOMPLETA, ESTQLOJA,
       MAX(CASE WHEN RN = 1 THEN QTDEMBALAGEM END) QTD_EMB1,
       MAX(CASE WHEN RN = 1 THEN ROUND(PRECOVALIDNORMAL/QTDEMBALAGEM,2) END) PRECO_UNI_EMB1,
       MAX(CASE WHEN RN = 2 THEN QTDEMBALAGEM END) QTD_EMB2,
       MAX(CASE WHEN RN = 2 THEN ROUND(PRECOVALIDNORMAL/QTDEMBALAGEM,2) END) PRECO_UNI_EMB2,
       MAX(CASE WHEN RN = 3 THEN QTDEMBALAGEM END) QTD_EMB3,
       MAX(CASE WHEN RN = 3 THEN ROUND(PRECOVALIDNORMAL/QTDEMBALAGEM,2) END) PRECO_UNI_EMB3,
       MAX(CASE WHEN RN = 4 THEN QTDEMBALAGEM END) QTD_EMB4,
       MAX(CASE WHEN RN = 4 THEN ROUND(PRECOVALIDNORMAL/QTDEMBALAGEM,2) END) PRECO_UNI_EMB4
           
  FROM (SELECT SEQPRODUTO,
               QTDEMBALAGEM,
               PRECOVALIDNORMAL,
               ROW_NUMBER() OVER(PARTITION BY SEQPRODUTO ORDER BY QTDEMBALAGEM) AS RN
          FROM MRL_PRODEMPSEG X 
         WHERE NROEMPRESA = 56 
           AND NROSEGMENTO = 4 
           AND STATUSVENDA = 'A'
           AND EXISTS (SELECT 1 FROM MRL_PRODUTOEMPRESA A WHERE A.NROEMPRESA = X.NROEMPRESA AND A.STATUSCOMPRA = 'A' AND A.SEQPRODUTO = X.SEQPRODUTO) -- Mix 56
       )
           
           SUB INNER JOIN MAP_PRODUTO P     ON P.SEQPRODUTO = SUB.SEQPRODUTO 
               INNER JOIN MAP_FAMILIA F     ON F.SEQFAMILIA = P.SEQFAMILIA
               INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = F.SEQFAMILIA
               INNER JOIN MAX_COMPRADOR M   ON M.SEQCOMPRADOR = FD.SEQCOMPRADOR
               INNER JOIN MRL_PRODUTOEMPRESA A ON A.SEQPRODUTO = SUB.SEQPRODUTO AND A.NROEMPRESA = 56
           
 GROUP BY SUB.SEQPRODUTO, COMPRADOR, DESCCOMPLETA, ESTQLOJA)
 
 WHERE 1=1
 
 ORDER BY 1
