SELECT TO_CHAR(X.DTAHORINCLUSAO, 'MM/YYYY') DATA,
       COMPRADOR,
       COUNT(DISTINCT CASE
           WHEN (SELECT SUM(CASE WHEN AA.QTDPEDIDA > 0 AND AA.QTDPEDIDA = AA.QTDSUGERIDAFORNEC THEN 1 ELSE 0 END)
                 FROM MAC_GERCOMPRAITEM AA
                WHERE AA.SEQGERCOMPRA = X.SEQGERCOMPRA
           )
           /
           NULLIF((SELECT SUM(CASE WHEN AA.QTDPEDIDA > 0 THEN 1 ELSE 0 END)
                     FROM MAC_GERCOMPRAITEM AA
                    WHERE AA.SEQGERCOMPRA = X.SEQGERCOMPRA
               ),
               0
           ) >= 0.50
           THEN X.SEQGERCOMPRA
       END) QTD_LOTE_SUG_ACAT,
       COUNT(DISTINCT CASE
           WHEN (SELECT SUM(CASE WHEN AA.QTDPEDIDA > 0 AND AA.QTDPEDIDA = AA.QTDSUGERIDAFORNEC THEN 1 ELSE 0 END)
                 FROM MAC_GERCOMPRAITEM AA
                WHERE AA.SEQGERCOMPRA = X.SEQGERCOMPRA
           )
           /
           NULLIF((SELECT SUM(CASE WHEN AA.QTDPEDIDA > 0 THEN 1 ELSE 0 END)
                     FROM MAC_GERCOMPRAITEM AA
                    WHERE AA.SEQGERCOMPRA = X.SEQGERCOMPRA
               ),
               0
           ) < 0.50
           THEN X.SEQGERCOMPRA
       END)  QTD_LOTE_MANUAL,
     --  COUNT(DISTINCT CASE WHEN XI.QTDPEDIDA != XI.QTDSUGERIDAFORNEC AND XI.QTDPEDIDA > 0 THEN X.SEQGERCOMPRAEND) QTD_LOTE_MANUAL,
       SUM(CASE WHEN XI.QTDPEDIDA  = XI.QTDSUGERIDAFORNEC AND QTDPEDIDA > 0 THEN 1 ELSE 0 END) QTDITEM_SUG_ACATADA,
       SUM(CASE WHEN XI.QTDPEDIDA != XI.QTDSUGERIDAFORNEC AND QTDPEDIDA > 0 THEN 1 ELSE 0 END) QTDITEM_MANUAL

  FROM MAC_GERCOMPRA X INNER JOIN MAC_GERCOMPRAITEM XI ON XI.SEQGERCOMPRA = X.SEQGERCOMPRA
                       INNER JOIN MAP_PRODUTO P        ON P.SEQPRODUTO = XI.SEQPRODUTO
                       INNER JOIN MAP_FAMDIVISAO F     ON F.SEQFAMILIA = P.SEQFAMILIA
                       INNER JOIN MAX_COMPRADOR C      ON F.SEQCOMPRADOR = C.SEQCOMPRADOR

 WHERE X.DTAHORINCLUSAO >= DATE '2026-01-01'
   AND X.TIPOLOTE = 'C'
   AND X.SITUACAOLOTE = 'F'

 GROUP BY TO_CHAR(X.DTAHORINCLUSAO, 'MM/YYYY'),
          COMPRADOR

 ORDER BY 1 DESC;
