SELECT P.SEQPRODUTO PLU, P.SEQFAMILIA COD_FAMILIA, DESCCOMPLETA, C.CODACESSO EAN, F.SEQFORNECEDOR||' - '||NOMERAZAO FORNEC_PRINCIPAL, CATEGORIAN1
  FROM MAP_PRODUTO P INNER JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = P.SEQPRODUTO AND TIPCODIGO = 'E' AND C.INDUTILVENDA = 'S'
                     INNER JOIN MAP_FAMFORNEC  F ON F.SEQFAMILIA = P.SEQFAMILIA AND F.PRINCIPAL = 'S'
                     INNER JOIN GE_PESSOA      G ON G.SEQPESSOA = F.SEQFORNECEDOR
                     INNER JOIN DIM_CATEGORIA@CONSINCODW CA ON CA.SEQFAMILIA = P.SEQFAMILIA
                     
                     WHERE CATEGORIAN1 IN (#LS1)
                       AND EXISTS (SELECT 1 FROM MAP_FAMFORNEC CC WHERE CC.SEQFAMILIA = P.SEQFAMILIA AND CC.SEQFORNECEDOR = :NR1)
                     ORDER BY 3
