ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;
 
SELECT DISTINCT 
     /*L.M014_VL_TOTAL_BRUTO VLR_TOT, M014_VL_OUTRAS_DESPESAS VLR_DESP, L.M014_VL_QTDE_TRIB QTD_UNI, */
     /*CONSINCO.NAGF_CUSTOFAMFORNEC(P.SEQFAMILIA, 'SP',1, 455003) CUSTO_TAB,*/
       TO_NUMBER(SUBSTR(ROUND(((M014_VL_OUTRAS_DESPESAS / M014_VL_QTDE_TRIB) / CONSINCO.NAGF_CUSTOFAMFORNEC(P.SEQFAMILIA, 'SP',1, 455003)) * 100,5),0,6)) PERCENTUAL,
       X.SEQPRODUTO PLU, DESCCOMPLETA,
      (SELECT NOMERAZAO FROM GE_PESSOA G WHERE SEQPESSOA = 455003) FORNEC
    /*(M014_VL_TOTAL_BRUTO / NVL(L.M014_VL_OUTRAS_DESPESAS,0)), X.SEQPRODUTO*/
   
  FROM TMP_M000_NF K INNER JOIN TMP_M014_ITEM L  ON L.M000_ID_NF = K.M000_ID_NF
                     INNER JOIN MAP_PRODCODIGO X ON X.CODACESSO  = L.M014_CD_EAN_TRIB AND X.TIPCODIGO IN ('E')
                     INNER JOIN MAP_PRODUTO P    ON P.SEQPRODUTO = X.SEQPRODUTO
  
 WHERE EXISTS (SELECT DISTINCT 1
                 FROM CONSINCO.MLF_AUXNOTAFISCAL A,
                      CONSINCO.MLF_AUXNFITEM     B
                WHERE A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                  AND  A.SEQPESSOA IN (SELECT SEQPESSOA FROM GE_PESSOA X WHERE NROCGCCPF LIKE 
                                   '%'||(SELECT SUBSTR(NROCGCCPF,0,8) FROM GE_PESSOA XX WHERE SEQPESSOA = 455003)||'%')
                  AND A.DTAEMISSAO >= SYSDATE - 7
                  AND A.NFECHAVEACESSO = K.M000_NR_CHAVE_ACESSO)
                                      
ORDER BY DESCCOMPLETA
                                       
