UPDATE CONSINCO.MRL_PRODEMPSEG A SET 
   A.PRECOBASENORMAL  = A.QTDEMBALAGEM * (SELECT DISTINCT PRECOBASENORMAL  FROM CONSINCO.MRL_PRODEMPSEG B 
                                          WHERE B.SEQPRODUTO = A.SEQPRODUTO AND B.QTDEMBALAGEM = 1 AND NROSEGMENTO IN (2,5) AND B.NROEMPRESA = A.NROEMPRESA),
   A.PRECOGERNORMAL   = A.QTDEMBALAGEM * (SELECT DISTINCT PRECOGERNORMAL   FROM CONSINCO.MRL_PRODEMPSEG B 
                                          WHERE B.SEQPRODUTO = A.SEQPRODUTO AND B.QTDEMBALAGEM = 1 AND NROSEGMENTO IN (2,5) AND B.NROEMPRESA = A.NROEMPRESA),
   A.PRECOVALIDNORMAL = A.QTDEMBALAGEM * (SELECT DISTINCT PRECOVALIDNORMAL FROM CONSINCO.MRL_PRODEMPSEG B 
                                          WHERE B.SEQPRODUTO = A.SEQPRODUTO AND B.QTDEMBALAGEM = 1 AND NROSEGMENTO IN (2,5) AND B.NROEMPRESA = A.NROEMPRESA)

WHERE NROSEGMENTO IN (2,5) --AND NROEMPRESA NOT IN (31,41,53) 
  AND A.SEQPRODUTO = 230802 AND A.NROEMPRESA = 4;
  
  COMMIT;
  
SELECT A.SEQPRODUTO, A.QTDEMBALAGEM, A.NROSEGMENTO, A.NROEMPRESA, A.STATUSVENDA, A.PRECOBASENORMAL, A.PRECOGERNORMAL, A.PRECOVALIDNORMAL, 
       ROUND((A.PRECOBASENORMAL / A.QTDEMBALAGEM),2) PRECO_UNI, A.USUALTERACAO, A.DTAALTERACAO

FROM CONSINCO.MRL_PRODEMPSEG A 
WHERE  NROSEGMENTO IN (2,5) AND NROEMPRESA NOT IN (31,41,53)  AND NROEMPRESA = 4--  AND SEQPRODUTO = 230802
  AND (PRECOBASENORMAL / QTDEMBALAGEM) NOT IN
 (SELECT DISTINCT PRECOBASENORMAL FROM CONSINCO.MRL_PRODEMPSEG B WHERE B.SEQPRODUTO = A.SEQPRODUTO AND B.QTDEMBALAGEM = 1 AND NROSEGMENTO IN (2,5))
 
