SELECT X.SEQREGRA || ' - ' || X.DESCRICAO REGRA,
       A.NROEMPRESA LOJA, B.SEQPRODUTO SKU, D.DESCCOMPLETA DESC_PRODUTO,
       SUM(B.QUANTIDADE) QTDE,
       SUM(B.VLRITEM) VLR_ITEM,
       SUM(NVL(B.VLRDESCONTO, 0)) VLR_DESCONTO
              
  FROM MFL_DOCTOFISCAL    A,
       MFL_DFITEM         B,
       MAX_EMPRESA        C,
       MAP_PRODUTO        D,
       MAP_FAMEMBALAGEM   E,
       MRL_FORMAPAGTO     F,
       MRL_CUSTODIAFAM    Y,
       MRL_CUSTODIA       Z,
       MFL_REGRAINCENTIVO X,
       MAP_PRODUTO        PRODBASE
 WHERE A.NUMERODF = B.NUMERODF
       AND A.NROEMPRESA = B.NROEMPRESA
       AND A.SERIEDF = B.SERIEDF
       AND A.NROSERIEECF = B.NROSERIEECF
       AND A.NROEMPRESA = C.NROEMPRESA
       AND B.SEQPRODUTO = D.SEQPRODUTO
       AND D.SEQPRODUTOBASE = PRODBASE.SEQPRODUTO(+)
       AND NVL(PRODBASE.SEQFAMILIA, D.SEQFAMILIA) = E.SEQFAMILIA
       AND B.QTDEMBALAGEM = E.QTDEMBALAGEM
       AND A.NROFORMAPAGTO = F.NROFORMAPAGTO
       AND A.NROEMPRESA = Z.NROEMPRESA
       AND Y.SEQFAMILIA = Z.SEQFAMILIA
       AND Y.DTAENTRADASAIDA = Z.DTAENTRADASAIDA
       AND Y.NROEMPRESA = Z.NROEMPRESA
       AND NVL(PRODBASE.SEQFAMILIA, D.SEQFAMILIA) = Z.SEQFAMILIA
       AND NVL(PRODBASE.SEQPRODUTO, D.SEQPRODUTO) = Z.SEQPRODUTO
       AND A.DTAMOVIMENTO = Z.DTAENTRADASAIDA
       AND B.SEQREGRAINCENTIVO = X.SEQREGRA
       AND Y.VLRTOTALVDA != 0
       AND Z.VLRTOTALVDA != 0
       AND B.SEQREGRAINCENTIVO IS NOT NULL
       AND B.SEQREGRAINCENTIVO != 0
       AND A.NROEMPRESA IN (#LS1)
      
       AND A.NROFORMAPAGTO IN (92,25,93) 
       AND A.DTAMOVIMENTO BETWEEN X.DTAINICIO AND X.DTAFIM
       AND X.SEQREGRA IN (:NR1)

 GROUP BY X.SEQREGRA || ' - ' || X.DESCRICAO, A.NROEMPRESA, B.SEQPRODUTO, D.DESCCOMPLETA
 
 ORDER BY 2,1,4
