SELECT NROEMPRESA, COUNT(SEQLOGPRECO) QTD_ALTERACOES 
  FROM CONSINCO.MAD_PRODLOGPRECO A 
 WHERE --SEQPRODUTO = 5500 
       A.DTAHORALTERACAO BETWEEN DATE '2022-01-01' AND DATE '2022-03-31'
   AND QTDEMBALAGEM = 1
   AND NROEMPRESA NOT IN (31,41)
   
GROUP BY NROEMPRESA

UNION ALL

SELECT NROEMPRESA, COUNT(SEQLOGPRECO) QTD_ALTERACOES 
  FROM CONSINCO.MAD_PRODLOGPRECO A 
 WHERE --SEQPRODUTO = 5500 
       A.DTAHORALTERACAO BETWEEN DATE '2022-01-01' AND DATE '2022-03-31'
   --AND QTDEMBALAGEM = 1
   AND NROEMPRESA IN (31,41)
   
GROUP BY NROEMPRESA

ORDER BY 1
