ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT 
       DISTINCT GP.FANTASIA EMP, P.PROMOCAO, P.SEQPROMOCAO COD_PROMOC, PI.SEQPRODUTO PLU, X.SEQFAMILIA FAMILIA, X.DESCCOMPLETA DESC_PROD,
       TO_CHAR(DTAINICIO, 'DD/MM/YYYY') DTAINICIO, TO_CHAR(DTAFIM, 'DD/MM/YYYY') DTAFIM,
       SEQFORNECEDOR|| ' - ' ||NOMERAZAO FORNEC, 
       CASE WHEN SYSDATE BETWEEN DTAINICIO AND DTAFIM AND PI.STATUS != 'I'
         THEN 'ATIVA' ELSE 'INATIVA' END STATUS_ATUAL_PROMOC, PI.PRECOPROMOCIONAL

  FROM MRL_PROMOCAOITEM PI INNER JOIN MRL_PROMOCAO P      ON P.SEQPROMOCAO = PI.SEQPROMOCAO
                           INNER JOIN MAP_PRODUTO  X      ON X.SEQPRODUTO  = PI.SEQPRODUTO
                           INNER JOIN MAP_FAMFORNEC F     ON F.SEQFAMILIA  = X.SEQFAMILIA 
                           INNER JOIN GE_PESSOA G         ON G.SEQPESSOA   = F.SEQFORNECEDOR
                           INNER JOIN GE_EMPRESA GP       ON GP.NROEMPRESA = P.NROEMPRESA 
                     
 WHERE P.DTAINICIO >= :DT1
   AND P.DTAFIM    <= :DT2
   AND F.SEQFORNECEDOR = :NR1
   AND P.NROEMPRESA IN (#LS1)
  
 ORDER BY 1,2,5
