ALTER SESSION SET current_schema = CONSINCO;

SELECT ORIGEM, A.SEQPRODUTO,D.SEQFAMILIA, B.DESCSEGMENTO,  MAX(A.DTAHORALTERACAO) DATAHR_ALTERACAO, USUALTERACAO, 
       A.PRECO,-- CASE WHEN A.APROVADOREPROVADO IS NULL THEN 'Ainda não aprovado' ELSE A.APROVADOREPROVADO END STATUS,
       A.QTDEMBALAGEM, TO_CHAR((A.PRECO / A.QTDEMBALAGEM), 'FM99G999D00') Preco_Unitario, A.VLRCUSTO
       
FROM CONSINCO.MAD_PRODLOGPRECO A JOIN CONSINCO.MAD_SEGMENTO B ON A.NROSEGMENTO = B.NROSEGMENTO
     LEFT JOIN MAP_PRODSIMILAR C                              ON A.SEQPRODUTO = C.SEQPRODUTO
     LEFT JOIN MAP_PRODUTO D                                  ON A.SEQPRODUTO = D.SEQPRODUTO -- Adicionado Seqfamilia
      WHERE 
      -- C.SEQSIMILARIDADE = 726
      -- A.SEQPRODUTO IN (206477 )
      -- A.QTDEMBALAGEM = 1
      -- B.NROSEGMENTO = 1
      -- A.NROEMPRESA = 51
      -- A.QTDEMBALAGEM = 1
      -- AND D.SEQFAMILIA = 66502
      -- AND USUALTERACAO = 'JLIMA'
      
GROUP BY ORIGEM, B.DESCSEGMENTO,A.SEQPRODUTO,D.SEQFAMILIA, A.PRECO, APROVADOREPROVADO, USUALTERACAO, A.QTDEMBALAGEM,(A.PRECO / A.QTDEMBALAGEM), VLRCUSTO
ORDER BY 5 DESC
