SELECT NROACORDO, NROEMPRESA, DESCACORDO, DECODE(SITUACAOACORDO, 'C','SIM', 'NÃO') CANCELADO, 
       USUINCLUSAO, TO_CHAR(DTAINCLUSAO, 'DD/MM/YYYY') DTAINCLUSAO, Z.USUCANCELAMENTO, TO_CHAR(Z.DTACANCELAMENTO, 'DD/MM/YYYY') DTACANCELAMENTO, DESCCANCELAMENTO, G.MODULO||' - '||G.DESCRICAO MODULO
  FROM CONSINCO.MSU_ACORDOPROMOC Z LEFT JOIN CONSINCO.GE_APLICACAO G ON G.CODAPLICACAO = Z.LINKCODAPP
  
   WHERE Z.NROACORDO = :NR1
