-- Insere em MLFV_AUXNOTAFISCALINCONS

SELECT DISTINCT(X.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                X.NUMERONF,
                X.NROEMPRESA,
                0   AS SEQAUXNFITEM,
                'B' AS BLOQAUTOR,
                67  AS CODINCONSISTENC,
                'Comprador não possúi limite disponível. Total NF: R$ '||TO_CHAR(VLRTOTALNF,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''')||' Valor Disponível: R$ '||
                 TO_CHAR(VLRDISPONIVEL,'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''')||' Entre em contato com o Departamento Comercial.' AS MENSAGEM
                 
  FROM MLF_AUXNOTAFISCAL X INNER JOIN MLF_AUXNFITEM Y ON Y.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
                           INNER JOIN MAP_PRODUTO   P ON P.SEQPRODUTO = Y.SEQPRODUTO
                           INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA
                           INNER JOIN NAGV_LIMITECOMPRADOR NV ON NV.SEQCOMPRADOR = F.SEQCOMPRADOR
                           INNER JOIN MLF_AUXNFINCONSISTENCIA A ON A.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
                           
 WHERE A.CODINCONSIST IN (7) 
   AND A.AUTORIZADA = 'N'        
   AND A.TIPOINCONSIST = 'P' 
   AND X.VLRTOTALNF > VLRDISPONIVEL 
