SELECT *
FROM MAC_CCLIMCOMPRA XX  
 WHERE XX.SEQCOMPRADOR = 2 
 AND DTALANCAMENTO >= DATE '2023-05-01'
 AND NROPEDIDOSUPRIM IN (SELECT DISTINCT NROPEDIDOSUPRIM FROM MSU_PEDIDOSUPRIM Z WHERE SEQGERCOMPRA IN (236802))
ORDER BY DTAHORLANCAMENTO DESC
