SELECT DISTINCT SEQIDENTIFICA SEQPROMOCAO, SEQIDENTIFICA2 NROEMPRESA, CAMPO, DESCCAMPO, 
        DECODE(VLRANTERIOR,'A','Ativo','I','Inativo',VLRANTERIOR) VLRANTERIOR, 
        DECODE(SUBSTR(VLRATUAL, 1, INSTR(VLRATUAL, '-') - 1),'A','Ativo','I ','Inativo',SUBSTR(VLRATUAL, 1, INSTR(VLRATUAL, '-') - 1))   VLRATUAL,
        USUAUDITORIA USU_ALTERACAO, TRIM(REGEXP_SUBSTR(VLRATUAL, '.:[^,]+')) NOME, TO_CHAR(DTAHORAUDITORIA, 'DD/MM/YYYY HH24:MI:SS') DATA_ALTERACAO
        
   FROM CONSINCO.MAP_AUDITORIA Z 
   
   WHERE 1=1 
     AND Z.TABELA LIKE 'MRL_PROMOCAO%'
     AND SEQIDENTIFICA = :NR1
     AND SEQIDENTIFICA2 IN (#LS1)

ORDER BY TO_CHAR(DTAHORAUDITORIA, 'DD/MM/YYYY HH24:MI:SS') DESC
