ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.SEQPRODUTO, DESCCOMPLETA, 
  --   502, 
       X2.ESTQDEPOSITO EST_502,
       NVL(TO_NUMBER(X2.CMULTVLRNF),0) CT_UVN_502,
       NVL(TO_NUMBER(FMSU_CUSTOCOMPRAATUAL(X.SEQFAMILIA,1,X2.NROEMPRESA,'S','SP','TF',X2.NROEMPRESA)),0) TAB_502,
       CASE WHEN NVL(TO_NUMBER(X2.CMULTVLRNF),0) = NVL(FMSU_CUSTOCOMPRAATUAL(X.SEQFAMILIA,1,X2.NROEMPRESA,'S','SP','TF',X2.NROEMPRESA),0)
              OR X2.ESTQDEPOSITO = 0
            THEN 'OK' ELSE 'Custo Diferente' END  DIF,
  --   503
       X3.ESTQDEPOSITO EST_503,
       NVL(TO_NUMBER(X3.CMULTVLRNF),0) CT_UVN_503,
       NVL(TO_NUMBER(FMSU_CUSTOCOMPRAATUAL(X.SEQFAMILIA,1,X3.NROEMPRESA,'S','SP','TF',X3.NROEMPRESA)),0) TAB_503,
       CASE WHEN NVL(TO_NUMBER(X3.CMULTVLRNF),0) = NVL(FMSU_CUSTOCOMPRAATUAL(X.SEQFAMILIA,1,X3.NROEMPRESA,'S','SP','TF',X3.NROEMPRESA),0)
              OR X3.ESTQDEPOSITO = 0
            THEN 'OK' ELSE 'Custo Diferente' END  DIF,
       CASE WHEN GREATEST(NVL(X2.DTAULTENTRADA, DATE '2000-01-01'), NVL(X3.DTAULTENTRADA, DATE '2000-01-01')) = DATE '2000-01-01' THEN NULL
            ELSE GREATEST(NVL(X2.DTAULTENTRADA, DATE '2000-01-01'), NVL(X3.DTAULTENTRADA, DATE '2000-01-01')) END DTA_ULT_ENTRADA,
       CASE WHEN NOT EXISTS (SELECT 1 FROM MRL_PRODUTOEMPRESA LJ 
                                     WHERE LJ.NROEMPRESA < 100 
                                       AND LJ.SEQPRODUTO = X.SEQPRODUTO
                                       AND LJ.ESTQLOJA > 0) 
             AND (X2.ESTQDEPOSITO > 0 OR X3.ESTQDEPOSITO > 0)
            THEN 'Sem estoque nas lojas!' ELSE 'Ok' END Validador_Estoque
      
  FROM MAP_PRODUTO X INNER JOIN MRL_PRODUTOEMPRESA X2 ON X2.SEQPRODUTO = X.SEQPRODUTO AND X2.NROEMPRESA = 502
                     INNER JOIN MRL_PRODUTOEMPRESA X3 ON X3.SEQPRODUTO = X.SEQPRODUTO AND X3.NROEMPRESA = 503
                     
 WHERE EXISTS (SELECT 1
          FROM MAP_FAMFORNEC F
         WHERE F.SEQFORNECEDOR IN
               (SELECT SEQPESSOA FROM GE_PESSOA G WHERE UF = 'EX')
               AND F.SEQFAMILIA = X.SEQFAMILIA)

ORDER BY 3 DESC;
