SELECT CAMPO, DESCCAMPO, VLRANTERIOR VLR_ANTERIOR, SUBSTR(VLRATUAL,0,INSTR(VLRATUAL, 'Usuário') -3) NOVO_VLR, 
       Z.USUAUDITORIA, TO_CHAR(Z.DTAHORAUDITORIA, 'DD/MM/YYYY HH24:MI:SS') DATA_ALTERACAO
       
  FROM MAP_AUDITORIA Z
 WHERE Z.SEQIDENTIFICA = :NR1
   AND DTAAUDITORIA BETWEEN :DT1 AND :DT2
   AND CAMPO = 'OBSENCARTE'
   
 ORDER BY DTAHORAUDITORIA DESC;
