/* Backup */

CREATE TABLE CONSINCO.MRL_PRODEMPSEG_BACKUP AS

SELECT * FROM CONSINCO.MRL_PRODEMPSEG;

/* Equipara preços entre embalagens - Nagumo SP */

UPDATE CONSINCO.MRL_PRODEMPSEG X 
      SET X.PRECOVALIDNORMAL = (SELECT DISTINCT B.PRECOVALIDNORMAL FROM CONSINCO.MRL_PRODEMPSEG B WHERE X.SEQPRODUTO = B.SEQPRODUTO AND X.NROEMPRESA = B.NROEMPRESA AND QTDEMBALAGEM = 1 AND B.NROSEGMENTO = 2) * NVL(X.QTDEMBALAGEM,1),
          X.PRECOGERNORMAL   = (SELECT DISTINCT B.PRECOVALIDNORMAL FROM CONSINCO.MRL_PRODEMPSEG B WHERE X.SEQPRODUTO = B.SEQPRODUTO AND X.NROEMPRESA = B.NROEMPRESA AND QTDEMBALAGEM = 1 AND B.NROSEGMENTO = 2) * NVL(X.QTDEMBALAGEM,1),
          X.PRECOBASENORMAL  = (SELECT DISTINCT B.PRECOVALIDNORMAL FROM CONSINCO.MRL_PRODEMPSEG B WHERE X.SEQPRODUTO = B.SEQPRODUTO AND X.NROEMPRESA = B.NROEMPRESA AND QTDEMBALAGEM = 1 AND B.NROSEGMENTO = 2) * NVL(X.QTDEMBALAGEM,1),
          X.USUALTERACAO     = 'EQUIP_EMB'
                            
WHERE NROEMPRESA NOT IN (36,53,31,41,54) AND SEQPRODUTO IN (
          /* Apenas os códigos em que o preço das embalagens > 1 diferem do preço unitário */
          SELECT DISTINCT A.SEQPRODUTO
          FROM CONSINCO.MRL_PRODEMPSEG A LEFT JOIN (SELECT B.PRECOVALIDNORMAL / B.QTDEMBALAGEM PE, B.* FROM CONSINCO.MRL_PRODEMPSEG B WHERE B.QTDEMBALAGEM > 1 AND NROSEGMENTO = 2) B 
          ON B.SEQPRODUTO = A.SEQPRODUTO AND B.NROEMPRESA = X.NROEMPRESA    
          WHERE A.QTDEMBALAGEM = 1 AND A.PRECOVALIDNORMAL != B.PE
          AND A.NROEMPRESA = X.NROEMPRESA
          AND PE != 0)
 AND X.PRECOVALIDNORMAL != 0;

COMMIT;

/* Confere se ainda existe algum preço divergente - Nsgumo SP */

SELECT A.SEQPRODUTO, B.QTDEMBALAGEM, A.PRECOBASENORMAL, A.PRECOGERNORMAL, A.PRECOVALIDNORMAL, B.PE PRECO_MULT
FROM CONSINCO.MRL_PRODEMPSEG A LEFT JOIN (SELECT B.PRECOVALIDNORMAL / B.QTDEMBALAGEM PE, B.* FROM CONSINCO.MRL_PRODEMPSEG B WHERE B.QTDEMBALAGEM > 1 AND NROSEGMENTO = 2) B 
           ON B.SEQPRODUTO = A.SEQPRODUTO AND B.NROEMPRESA = A.NROEMPRESA
           
WHERE A.QTDEMBALAGEM = 1 AND A.PRECOVALIDNORMAL != ROUND(B.PE,2)
  AND A.NROEMPRESA NOT IN (36,53,31,41,54) AND PE != 0 
  AND A.PRECOVALIDNORMAL != 0;
  
/* Equipara preços Nagumo SP para Ecommerce */

UPDATE CONSINCO.MRL_PRODEMPSEG X 
      SET X.PRECOVALIDNORMAL = (SELECT DISTINCT B.PRECOVALIDNORMAL FROM CONSINCO.MRL_PRODEMPSEG B WHERE X.SEQPRODUTO = B.SEQPRODUTO AND X.NROEMPRESA = B.NROEMPRESA AND QTDEMBALAGEM = 1 AND B.NROSEGMENTO = 2) * NVL(X.QTDEMBALAGEM,1),
          X.PRECOGERNORMAL   = (SELECT DISTINCT B.PRECOVALIDNORMAL FROM CONSINCO.MRL_PRODEMPSEG B WHERE X.SEQPRODUTO = B.SEQPRODUTO AND X.NROEMPRESA = B.NROEMPRESA AND QTDEMBALAGEM = 1 AND B.NROSEGMENTO = 2) * NVL(X.QTDEMBALAGEM,1),
          X.PRECOBASENORMAL  = (SELECT DISTINCT B.PRECOVALIDNORMAL FROM CONSINCO.MRL_PRODEMPSEG B WHERE X.SEQPRODUTO = B.SEQPRODUTO AND X.NROEMPRESA = B.NROEMPRESA AND QTDEMBALAGEM = 1 AND B.NROSEGMENTO = 2) * NVL(X.QTDEMBALAGEM,1),
          X.USUALTERACAO     = 'EQUIP_EMB'
          
WHERE X.NROEMPRESA NOT IN (36,53,31,41,54) AND SEQPRODUTO IN (
          /* Apenas os códigos em que o preço das embalagens > 1 diferem do preço unitário */
          SELECT DISTINCT A.SEQPRODUTO
          FROM CONSINCO.MRL_PRODEMPSEG A LEFT JOIN (SELECT B.PRECOVALIDNORMAL / B.QTDEMBALAGEM PE, B.* FROM CONSINCO.MRL_PRODEMPSEG B WHERE B.QTDEMBALAGEM > 1 AND NROSEGMENTO = 5) B 
          ON B.SEQPRODUTO = A.SEQPRODUTO AND B.NROEMPRESA = X.NROEMPRESA    
          WHERE A.QTDEMBALAGEM = 1 AND A.PRECOVALIDNORMAL != B.PE
          AND A.NROEMPRESA  = X.NROEMPRESA
          AND PE != 0)
 AND X.PRECOVALIDNORMAL != 0;

COMMIT;

/* Confere se ainda existe algum preço divergente - Ecommerce */

SELECT A.SEQPRODUTO, B.QTDEMBALAGEM, A.PRECOBASENORMAL, A.PRECOGERNORMAL, A.PRECOVALIDNORMAL, B.PE PRECO_MULT
FROM CONSINCO.MRL_PRODEMPSEG A LEFT JOIN (SELECT B.PRECOVALIDNORMAL / B.QTDEMBALAGEM PE, B.* FROM CONSINCO.MRL_PRODEMPSEG B WHERE B.QTDEMBALAGEM > 1 AND NROSEGMENTO = 5) B 
           ON B.SEQPRODUTO = A.SEQPRODUTO AND B.NROEMPRESA = A.NROEMPRESA
           
WHERE A.QTDEMBALAGEM = 1 AND A.PRECOVALIDNORMAL != ROUND(B.PE,2)
  AND A.NROEMPRESA NOT IN (36,53,31,41,54) AND PE != 0 
  AND A.PRECOVALIDNORMAL != 0;
