SELECT         TO_CHAR(A.DTAAUDITORIA,'DD/MM/YYYY') AS DTAAUDITORIA,
               A.CAMPO, 
               A.DESCCAMPO, 
               B.SEQPRODUTO, 
               B.DESCCOMPLETA,
       DECODE (E.FINALIDADEFAMILIA,
       'P', 'MATÉRIA-PRIMA',
       'B', 'BRINDE',
       'U', 'MATERIAL DE USO E CONSUMO',
       'A', 'ATIVO IMOBILIZADO',
       'S', 'SERVIÇOS',
       'G', 'SEGURO',
       'F', 'FRETE',
       'D', 'DESPESAS',
       'V', 'APROVEITAMENTO',
       'L', 'VALE/RECIBO',
       'E', 'EMBALAGEM',
       'C', 'PRODUTO EM PROCESSO',
       'Q', 'PRODUTO ACABADO',
       'T', 'SUBPRODUTO',
       'I', 'PRODUTO INTERMEDIÁRIO',
       'O', 'OUTROS INSUMOS',
       'J', 'ADJUDICAÇÃO CRED ICMS',
       'N', 'REST CRED TRIB',
       'M', 'COMPLEMENTO ANTECIPADO',
       'X', 'GARANTIA ESTENDIDA',
       'Z', 'VALE GÁS',
       'R', 'MERCADORIA PARA REVENDA') AS FINALIDADE_FAMILIA, C.SEQFORNECEDOR||' - '||D.NOMERAZAO FORNECEDOR

FROM CONSINCO.MAP_AUDITORIA A INNER JOIN CONSINCO.MAP_PRODUTO B ON (A.SEQIDENTIFICA = B.SEQPRODUTO)
                              LEFT JOIN CONSINCO.MAP_FAMFORNEC C ON (B.SEQFAMILIA = C.SEQFAMILIA) AND C.PRINCIPAL = 'S'
                              INNER JOIN CONSINCO.MAP_FAMDIVISAO E ON (B.SEQFAMILIA = E.SEQFAMILIA)
                              LEFT JOIN CONSINCO.GE_PESSOA D ON (C.SEQFORNECEDOR = D.SEQPESSOA)
WHERE A.CAMPO = 'STATUSCOMPRA'
AND A.VLRATUAL LIKE 'A%'
AND A.DTAAUDITORIA BETWEEN DATE '2022-12-01' AND SYSDATE
GROUP BY       A.DTAAUDITORIA,
               A.CAMPO, 
               A.DESCCAMPO, 
               B.SEQPRODUTO, 
               B.DESCCOMPLETA,
               E.FINALIDADEFAMILIA, C.SEQFORNECEDOR||' - '||D.NOMERAZAO
ORDER BY 1;
