 SELECT X.NROEMPRESA EMP,
        TO_CHAR(X.DTAHORLANCTO, 'DD/MM/YYYY') DTA_ENTRADA,
        X.NUMERONF, X.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, 
        FVALORTOTALNF(X.ROWID, 'N') VLR_TOTAL,
        CASE WHEN DESCRICAO LIKE 'FID%' THEN F.PERCENTUAL ELSE 0 END PERC_FID,
        CASE WHEN DESCRICAO LIKE 'FID%' THEN SUM(F.PERCENTUAL * F.VLTTOTALITEM / 100) ELSE 0 END VLR_FIDELIDADE,
        CASE WHEN DESCRICAO LIKE 'LOG%' THEN F.PERCENTUAL ELSE 0 END PERC_LOG,
        CASE WHEN DESCRICAO LIKE 'LOG%' THEN SUM(F.PERCENTUAL * F.VLTTOTALITEM / 100) ELSE 0 END VLR_LOGISTICO
        
        
   FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI           ON X.SEQNF = XI.SEQNF
                         INNER JOIN MLF_DESCFINACONTRATO F  ON F.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL        AND F.SEQITEMNF = XI.SEQITEMNF AND F.LINKERP = X.LINKERP AND F.PERCENTUAL > 0
                         INNER JOIN MGC_CONTRATODESCONTO CF ON CF.SEQCONTRATODESCONTO = F.SEQCONTRATODESCONTO AND (CF.DESCRICAO LIKE 'FID%' OR CF.DESCRICAO LIKE 'LOG%')
                         INNER JOIN GE_PESSOA G             ON G.SEQPESSOA = X.SEQPESSOA
                         INNER JOIN FI_TITULO T             ON T.NROTITULO = X.NUMERONF AND T.NROEMPRESA = X.NROEMPRESA AND T.SEQPESSOA = X.SEQPESSOA AND T.LINKERP = X.LINKERP
                         INNER JOIN FI_COMPLTITULO CT       ON CT.SEQTITULO = T.SEQTITULO

  WHERE 1=1
    AND X.NROEMPRESA IN (#LS1)
    AND TRUNC(X.DTAHORLANCTO) BETWEEN :DT1 AND :DT2
    
  GROUP BY X.NROEMPRESA, TO_CHAR(X.DTAHORLANCTO, 'DD/MM/YYYY'), X.NUMERONF, X.SEQPESSOA||' - '||G.NOMERAZAO, X.ROWID, DESCRICAO, PERCENTUAL
