SELECT DISTINCT A.NROEMPRESA EMP,
       TO_CHAR(A.DTALANCTO, 'DD/MM/YYYY') DATA_OP, DECODE(A.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       A.CODOPERACAO COD, A.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE B WHERE B.SEQCTACORRENTE = A.SEQCTACORRENTE)   CONTA_MOVTO, 
       TO_CHAR(A.VLRLANCAMENTO, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR
       
  FROM FI_CTACORLANCA A LEFT JOIN FI_CTACORLANCA B ON B.NROPROCESSO = A.NROPROCESSO 

WHERE A.NROEMPRESA IN (#LS1) 
    AND B.OPCANCELADA IS NULL 
    AND A.DTALANCTO BETWEEN :DT1 AND :DT2                                          
    AND A.CODOPERACAO IN (SELECT DISTINCT TRIM(REGEXP_SUBSTR(:LT1, '[^,]+', 1, LEVEL)) AS SEPARA_ESPECIE
                            FROM DUAL
                         CONNECT BY REGEXP_SUBSTR(:LT1, '[^,]+', 1, LEVEL) IS NOT NULL)
    
    ORDER BY 1,2,5 DESC,3 DESC
