
SELECT 'NORMAL' TIPO_TIT, A.NROTITULO, A.NROEMPRESA, A.SEQPESSOA, A.CODESPECIE,
                                                     TO_CHAR(A.VLRORIGINAL,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRORIGINAL,
                                                     TO_CHAR(B.VLROPERACAO,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLROPERACAO, NROPROCESSO
  FROM FI_TITULO A LEFT JOIN CONSINCO.FI_TITOPERACAO B ON A.SEQTITULO = B.SEQTITULO
 WHERE 1=1
   AND B.CODOPERACAO IN (61)
   AND A.DTAMOVIMENTO BETWEEN :DT1 AND :DT2
 
 UNION ALL
 
SELECT 'GERADO' TIPO_TIT, A.NROTITULO, A.NROEMPRESA, A.SEQPESSOA, A.CODESPECIE,
                                                     TO_CHAR(A.VLRORIGINAL,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRORIGINAL,
                                                     TO_CHAR(B.VLROPERACAO,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLROPERACAO, NROPROCESSO
  FROM FI_TITULO A LEFT JOIN CONSINCO.FI_TITOPERACAO B ON A.SEQTITULO = B.SEQTITULO
 WHERE 1=1
   AND NROPROCESSO IN (SELECT NROPROCESSO
  FROM FI_TITULO A LEFT JOIN CONSINCO.FI_TITOPERACAO B ON A.SEQTITULO = B.SEQTITULO
 WHERE 1=1
   AND B.CODOPERACAO IN (61)
   AND A.DTAMOVIMENTO BETWEEN :DT1 AND :DT2)
   AND B.CODOPERACAO IN (53)    

 ORDER BY NROPROCESSO, 1
