SELECT DISTINCT RE.SEQREDE, RE.DESCRICAO, CD.PERCDESCONTO, C.SEQCONTRATO, C.DESCRICAO, DECODE(C.STATUS, 'A','Ativo','I','Inativo') STATUS_CONTRATO
  FROM GE_PESSOA GE LEFT JOIN  GE_REDEPESSOA R ON R.SEQPESSOA = GE.SEQPESSOA
                    INNER JOIN GE_REDE RE      ON RE.SEQREDE = R.SEQREDE
                    INNER JOIN MGC_CONTRATO  C ON C.SEQREDE = R.SEQREDE
                    INNER JOIN MGC_CONTRATODESCONTO CD ON CD.SEQCONTRATO = C.SEQCONTRATO

 WHERE SUBSTR(NROCGCCPF,0,6) IN (
SELECT SUBSTR(CGCFORNEC,0,6) FROM MAP_PRODCODIGO WHERE TIPCODIGO = 'F' AND SEQPRODUTO IN (SELECT SEQPRODUTO
                                                                        FROM MAP_PRODUTO X WHERE X.SEQFAMILIA IN (SELECT SEQFAMILIA FROM DIM_CATEGORIA@CONSINCODW A WHERE A.CATEGORIAN1 = 'HORTIFRUTI')))
                                                                        

  AND GE.SEQPESSOA > 999
  /*AND C.SEQCONTRATO = 1603*/
  AND CD.INDDESCGERAL = 'S'
  /*AND C.STATUS = 'A'*/
  
  ORDER BY 2
