SELECT NUMERONF, NROEMPRESA, DTA_EMISSAO, DATA_RECBTO, USUARIO_LIBEROU, FORNECEDOR, VLRITEM VLR_TOTAL, TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') PRAZO_LANCTO, TO_CHAR(PRAZO_PEDIDO, 'DD/MM/YYYY') PRAZO_PEDIDO, DTAVENCIMENTO - PRAZO_PEDIDO DIFERENCA FROM (

SELECT DISTINCT B.NUMERONF, B.NROEMPRESA, TO_CHAR(B.DTARECEBIMENTO, 'DD/MM/YYYY') DATA_RECBTO, NVL(APELIDO, C.NOME) USUARIO_LIBEROU, G.NOMERAZAO FORNECEDOR,
       F.DTAVENCIMENTO, TO_CHAR(B.DTAEMISSAO, ' DD/MM/YYYY') DTA_EMISSAO, (
       SELECT SUM(VLRITEM) FROM MLF_NFITEM X WHERE X.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL) VLRITEM,
       DECODE(MF.INDPZOPAGAMENTO, 'F', 
                  DECODE(MF.TIPODTABASEVENCTO, 'E', B.DTAEMISSAO, 'R', B.DTARECEBIMENTO, 'S', B.DTASAIDA) +
                  CASE WHEN X.PZOPAGAMENTO LIKE '%/%' THEN REGEXP_SUBSTR(REPLACE(X.PZOPAGAMENTO, '/',' '), '(\S*)(\s)',1)
                       ELSE X.PZOPAGAMENTO END,
                  FMAD_CALCDTAVENCTO((DECODE(MF.TIPODTABASEVENCTO, 'E', B.DTAEMISSAO, 'R', B.DTARECEBIMENTO, 'S', B.DTASAIDA)), MF.INDPZOPAGAMENTO,
                  CASE WHEN X.PZOPAGAMENTO LIKE '%/%' THEN REGEXP_SUBSTR(REPLACE(X.PZOPAGAMENTO, '/',' '), '(\S*)(\s)',1)
                       ELSE X.PZOPAGAMENTO END, NULL)) PRAZO_PEDIDO
                         
FROM MLF_AUXNFINCONSISTENCIA A LEFT JOIN MLF_NOTAFISCAL B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                               LEFT JOIN FI_TITULO F ON F.NROTITULO = B.NUMERONF AND F.NROEMPRESA = B.NROEMPRESA AND F.SEQPESSOA = B.SEQPESSOA
                               LEFT JOIN MLF_NFITEM D ON D.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                               LEFT JOIN GE_USUARIO C ON A.USUAUTORIZOU = C.CODUSUARIO
                               LEFT JOIN MAX_COMPRADOR MC ON MC.CODUSUARIO = A.USUAUTORIZOU
                               LEFT JOIN GE_PESSOA G ON B.SEQPESSOA = G.SEQPESSOA
                               LEFT JOIN MSU_PSITEMRECEBIDO MP ON MP.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                               LEFT JOIN MSU_PEDIDOSUPRIM X ON X.NROPEDIDOSUPRIM = MP.NROPEDIDOSUPRIM 
                               LEFT JOIN MAF_FORNECDIVISAO MF   ON MF.SEQFORNECEDOR   = X.SEQFORNECEDOR

WHERE DESCRICAO = 'Prazo de Vencimento Informado MENOR que o Prazo do Pedido'
  AND A.AUTORIZADA = 'S'
  AND B.DTARECEBIMENTO BETWEEN :DT1 AND :DT2
  
  ORDER BY 2,1 DESC ) Z WHERE (DTAVENCIMENTO - PRAZO_PEDIDO) < 0

ORDER BY 4,5 
