ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, NROEMPRESA LOJA, CODESPECIE ESPECIE, NROTITULO TITULO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') VENCIMENTO, 
       TO_CHAR(X.VLRORIGINAL, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRORIGINAL, DECODE(ABERTOQUITADO, 'A','Aberto','Q','Quitado') STATUS
  FROM CONSINCO.FI_TITULO X INNER JOIN CONSINCO.GE_PESSOA G ON X.SEQPESSOA = G.SEQPESSOA
 WHERE 1=1
   AND X.CODESPECIE IN ('ACORDO','ACORIM','ACRCOM','ACRDIV','ACRING','ACRINT','ACRLOG','ACRMKT','ACRPRE','ACRTRO','DEVREC')
   AND DTAVENCIMENTO BETWEEN TRUNC(ADD_MONTHS(SYSDATE, 1), 'MM')AND TRUNC(ADD_MONTHS(SYSDATE, 2), 'MM')
   AND X.SITUACAO != 'C'
   
   ORDER BY G.NOMERAZAO 

