SELECT QTD_TOTAL_TITULOS, QTD_VENCIDO, VALOR_ABERTO, FORNECEDOR FROM (

SELECT COUNT(NROTITULO) QTD_TOTAL_TITULOS, 
       COUNT(CASE WHEN X.DTAVENCIMENTO < SYSDATE THEN 1 ELSE NULL END) QTD_VENCIDO,
       TO_CHAR(SUM(VLRNOMINAL - VLRPAGO), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_ABERTO,
       SUM(VLRNOMINAL - VLRPAGO) ORDENADOR,
       G.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR
       
FROM CONSINCO.FI_TITULO X LEFT JOIN CONSINCO.GE_PESSOA G ON X.SEQPESSOA = G.SEQPESSOA

WHERE X.CODESPECIE = 'DEVREC'
  AND X.ABERTOQUITADO = 'A'
  
  GROUP BY G.SEQPESSOA, G.NOMERAZAO
  
  ORDER BY 4 DESC)
  
  
