ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT MSU_PEDIDOSUPRIM.NROPEDIDOSUPRIM NRO_PEDIDO, MLF_NFITEM.NUMERONF , A.NROEMPRESA,  
       TO_CHAR(NVL(FVALORTOTALNF(X.ROWID, 'N'), 0), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''')VLR_TOTAL, 
       MSU_PEDIDOSUPRIM.SEQFORNECEDOR||' - '||(SELECT DISTINCT NOMERAZAO FROM GE_PESSOA WHERE SEQPESSOA = MSU_PEDIDOSUPRIM.SEQFORNECEDOR) FORNECEDOR,
      (SELECT LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) FROM GE_PESSOA WHERE SEQPESSOA = MSU_PEDIDOSUPRIM.SEQFORNECEDOR) CNPJ_FORNEC
      
FROM MSU_PSITEMRECEBER, 
 MAP_PRODUTO, 
 MSU_PEDIDOSUPRIM, 
 MLF_NFITEM LEFT JOIN MLF_NOTAFISCAL X ON X.NUMERONF = MLF_NFITEM.NUMERONF AND X.NROEMPRESA = MLF_NFITEM.NROEMPRESA,
 (SELECT SUM(A.QTDRECEBIDA) QTDRECEB,
 A.NROPEDIDOSUPRIM, 
 A.NROEMPRESA, 
 A.CENTRALLOJA, 
 A.SEQAUXNOTAFISCAL, 
 A.SEQPRODUTO,
 A.SEQAUXNFITEM
 FROM MSU_PSITEMRECEBIDO A
 WHERE A.NROPEDIDOSUPRIM = :NR1                                  
 GROUP BY A.SEQNROPEDIDOSUPRIM, 
 A.SEQAUXNOTAFISCAL, 
 A.SEQPRODUTO,
 A.NROPEDIDOSUPRIM,
 A.NROEMPRESA, 
 A.CENTRALLOJA,
 A.SEQAUXNFITEM
 ) A 

WHERE 
    MSU_PSITEMRECEBER.NROPEDIDOSUPRIM = A.NROPEDIDOSUPRIM
AND MSU_PSITEMRECEBER.NROEMPRESA      = A.NROEMPRESA
AND MSU_PSITEMRECEBER.CENTRALLOJA     = A.CENTRALLOJA
AND MSU_PSITEMRECEBER.SEQPRODUTO      = MAP_PRODUTO.SEQPRODUTO

AND MSU_PEDIDOSUPRIM.NROPEDIDOSUPRIM = MSU_PSITEMRECEBER.NROPEDIDOSUPRIM
AND MSU_PEDIDOSUPRIM.NROEMPRESA      = MSU_PSITEMRECEBER.NROEMPRESA
AND MSU_PEDIDOSUPRIM.CENTRALLOJA     = MSU_PSITEMRECEBER.CENTRALLOJA

AND NVL(MLF_NFITEM.SEQPRODUTORELACIONADO, MLF_NFITEM.SEQPRODUTO)       = MSU_PSITEMRECEBER.SEQPRODUTO
AND NVL(MLF_NFITEM.SEQPRODUTORELACIONADO, MLF_NFITEM.SEQPRODUTO)       = A.SEQPRODUTO
AND MLF_NFITEM.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
AND MLF_NFITEM.SEQITEMNF  = A.SEQAUXNFITEM
AND MSU_PEDIDOSUPRIM.NROPEDIDOSUPRIM = :NR1                        

ORDER BY 3

--GROUP BY MSU_PEDIDOSUPRIM.NROPEDIDOSUPRIM, MLF_NFITEM.NUMERONF, A.NROEMPRESA
