SELECT X.NROEMPRESA EMPRESA, X.NROTITULO TITULO, G.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR,  
       TO_CHAR(X.DTAVENCIMENTO, 'DD/MM/YYYY') DTA_VENCIMENTO,  CASE WHEN DTAVENCIMENTO < SYSDATE THEN 'Vencido' ELSE 'No Prazo' END SITUACAO_PRAZO, 
       TO_CHAR(X.VLRNOMINAL, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR, X.VLRPAGO

FROM CONSINCO.FI_TITULO X LEFT JOIN CONSINCO.GE_PESSOA G ON X.SEQPESSOA = G.SEQPESSOA

WHERE X.CODESPECIE = 'DEVREC'
  AND X.ABERTOQUITADO = 'A'
  AND X.SEQPESSOA = :NR1 -- 719552
  
