SELECT  DISTINCT X.NROEMPRESA, X.NUMERONF, TO_CHAR(DTAENTRADA, 'DD/MM/YYYY') DTAENTRADA, X.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, 
        TO_CHAR(NVL(ROUND ((SUM(Z.VLRDESCCONTRATO) / (SUM(Z.VLRITEM) - SUM(Z.VLRDESCITEM))) * 100,2),0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')  PERC_DESCNF,
        TO_CHAR(NVL(C.PERCDESCCONTRATO,0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')   PERC_DESCTIT
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM Z ON X.SEQNF = Z.SEQNF 
                        INNER JOIN GE_PESSOA  G ON G.SEQPESSOA = X.SEQPESSOA
                        LEFT JOIN  FI_TITULO  F ON F.NROTITULO = X.NUMERONF AND F.NROEMPRESA = X.NROEMPRESA AND F.SEQPESSOA = X.SEQPESSOA
                        LEFT JOIN  FI_COMPLTITULO C ON C.SEQTITULO = F.SEQTITULO
                        LEFT JOIN  GE_REDEPESSOA PR ON PR.SEQPESSOA = X.SEQPESSOA
                        INNER JOIN GE_REDE       R  ON R.SEQREDE = PR.SEQREDE
 WHERE 1=1 
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND DESCRICAO LIKE '%' || NVL(:LS1, '') || '%'
   
   GROUP BY X.NROEMPRESA, X.NUMERONF ,X.SEQPESSOA, G.NOMERAZAO, C.PERCDESCCONTRATO, TO_CHAR(DTAENTRADA, 'DD/MM/YYYY')
   
   ORDER BY 1,2
