ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT A.NROEMPRESA EMP, M.SEGMENTO, A.SEQPRODUTO PLU, P.CODACESSO EAN, TO_NUMBER(A.QTDEMBALAGEM) QTD_EMB, B.DESCCOMPLETA DESCRICAO, 
       C.PRECOBASENORMAL PRECO_DE, C.PRECOVALIDPROMOC PRECO_PARA, P2.PRECOPPROMOCIONAL PRECO_2, 
       TO_CHAR(DTAINICIOPROM, 'DD/MM/YYYY') DTA_INICIO_PROM, 
       TO_CHAR(DTAFIMPROM   , 'DD/MM/YYYY') DTA_FIM_PROM, MC.COMPRADOR, CATEGORIA_NIVEL_1, CATEGORIA_NIVEL_2, CATEGORIA_NIVEL_3
       
  FROM MAP_PRODUTO B       LEFT JOIN MRL_PROMOCAOITEM    A ON A.SEQPRODUTO = B.SEQPRODUTO
                           LEFT JOIN MRL_PRODEMPSEG C ON C.SEQPRODUTO = A.SEQPRODUTO AND C.NROEMPRESA = A.NROEMPRESA AND C.NROSEGMENTO = A.NROSEGMENTO AND C.QTDEMBALAGEM = A.QTDEMBALAGEM
                          INNER JOIN MON_EMPRESASEGMENTO S ON S.NROEMPRESA = A.NROEMPRESA AND S.NROSEGMENTO = A.NROSEGMENTO 
                           LEFT JOIN MAP_PRODCODIGO P ON P.SEQPRODUTO = A.SEQPRODUTO AND P.TIPCODIGO IN ('E')
                          INNER JOIN MON_SEGMENTO   M ON M.NROSEGMENTO = A.NROSEGMENTO 
                           LEFT JOIN RemarcaPromocoes@infoprocmssql P2 ON to_char(to_number(CODIGOPRODUTO)) = P.CODACESSO AND P2.CODLOJA = A.NROEMPRESA
                           LEFT JOIN QLV_CATEGORIA@CONSINCODW QC ON QC.SEQFAMILIA = B.SEQFAMILIA
                           LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = B.SEQFAMILIA
                           LEFT JOIN MAX_COMPRADOR MC ON MC.SEQCOMPRADOR = FD.SEQCOMPRADOR
                          
 WHERE 1=1
   AND :DT1 BETWEEN DTAINICIOPROM AND DTAFIMPROM
   AND :DT1 BETWEEN DTINICIO AND DTFIM
   AND S.ATIVO = 'S'
   AND A.QTDEMBALAGEM = 1
   AND A.NROEMPRESA IN (#LS1)
   
   ORDER BY 
     B.DESCCOMPLETA ASC
     
