-- Valida titulos nao cancelados, ex Usuario Lancto SBJUNIOR

SELECT * FROM CONSINCO.FI_TITULO X 
 WHERE X.USUALTERACAO = 'SBJUNIOR' 
   AND SEQTITULO NOT IN (SELECT SEQTITULO FROM FI_TITOPERACAO Z WHERE Z.OBSERVACAO LIKE '%Cancelado%') 
   AND SITUACAO != 'C'
