SELECT X.NUMERONF,  X.NROEMPRESA EMPRESA,
       TO_CHAR(X.DTARECEBIMENTO, 'DD/MM/YYYY') DTA_RECEBIMENTO,
       K.DESCRICAO REDE,
       Y.SEQPRODUTO PLU,
       (SELECT Z.DESCCOMPLETA
          FROM CONSINCO.MAP_PRODUTO Z
         WHERE Z.SEQPRODUTO = Y.SEQPRODUTO) PRODUTO,
         
       NAGF_QTDITEMNF(Y.SEQNF, Y.SEQPRODUTO, 'Q') QTD_NF,
       NAGF_QTDITEMNF(Y.SEQNF, Y.SEQPRODUTO, 'V') VLR_NF,
       NVL(SUM(E.QTDRECEBIDA) / Y.QTDEMBALAGEM, 0) QTD_PEDIDO,
       
       ROUND( CASE WHEN SUM(E.VLRPRODUTO) IS NULL THEN 0 ELSE
       SUM(F.VLREMBITEM) / COUNT(DISTINCT(NVL(E.NROPEDIDOSUPRIM,1))) END,2) VLR_PEDIDO,
       
       ROUND(CASE WHEN SUM(E.VLRPRODUTO) IS NULL THEN 
         0 ELSE
        (SUM(F.VLREMBITEM) / COUNT(DISTINCT(NVL(E.NROPEDIDOSUPRIM,1)))) END -
         NAGF_QTDITEMNF(Y.SEQNF, Y.SEQPRODUTO, 'V') ,2) 
       RESULTADO,
         
       ROUND ( 
             
         CASE WHEN SUM(E.VLRPRODUTO) IS NULL THEN 
        (NAGF_QTDITEMNF(Y.SEQNF, Y.SEQPRODUTO, 'Q') * NAGF_QTDITEMNF(Y.SEQNF, Y.SEQPRODUTO, 'V')) * -1 
         ELSE
        ((NVL(SUM(E.QTDRECEBIDA) / Y.QTDEMBALAGEM, 0)) * SUM(F.VLREMBITEM) / COUNT(DISTINCT(NVL(E.NROPEDIDOSUPRIM,1)))) -
        (NAGF_QTDITEMNF(Y.SEQNF, Y.SEQPRODUTO, 'Q') * NAGF_QTDITEMNF(Y.SEQNF, Y.SEQPRODUTO, 'V')) END, 2 ) CALC         
       
  FROM CONSINCO.MLF_NOTAFISCAL X INNER JOIN CONSINCO.MLF_NFITEM Y         ON (X.SEQNF = Y.SEQNF)
                                  LEFT JOIN CONSINCO.MSU_PSITEMRECEBIDO E ON (E.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL AND E.SEQAUXNFITEM = Y.SEQITEMNF AND E.SEQPRODUTO = Y.SEQPRODUTO)
                                  LEFT JOIN CONSINCO.MSU_PSITEMRECEBER F  ON (F.NROPEDIDOSUPRIM = E.NROPEDIDOSUPRIM AND F.NROEMPRESA = E.NROEMPRESA AND F.CENTRALLOJA = E.CENTRALLOJA AND E.SEQPRODUTO = F.SEQPRODUTO)
                                  LEFT JOIN CONSINCO.GE_REDEPESSOA W      ON (W.SEQPESSOA = X.SEQPESSOA)
                                  LEFT JOIN CONSINCO.GE_REDE K            ON (K.SEQREDE = W.SEQREDE)

 WHERE X.TIPNOTAFISCAL = 'E'
   AND X.NROEMPRESA   IN (501, 502, 503, 504, 505, 506, 507, 508)
   AND K.DESCRICAO    IN (#LS1)
   AND X.CODGERALOPER IN (1)
   AND X.DTARECEBIMENTO BETWEEN :DT1 AND :DT2
   
 GROUP BY X.NROEMPRESA,
          K.DESCRICAO,
          X.DTARECEBIMENTO,
          Y.SEQPRODUTO, 
          Y.QTDEMBALAGEM, X.NUMERONF, Y.SEQNF
          
          ORDER BY 1,5;
