ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.NROEMPRESA EMP, X.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, X.NUMERONF, 
       TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO,
       XI.SEQPRODUTO PLU, DESCCOMPLETA DESC_PRODUTO
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM  XI ON X.SEQNF = XI.SEQNF
                        INNER JOIN GE_PESSOA   G  ON G.SEQPESSOA = X.SEQPESSOA
                        INNER JOIN MAP_PRODUTO P  ON P.SEQPRODUTO = XI.SEQPRODUTO
 WHERE X.SEQPESSOA IN (SELECT SEQPESSOA FROM GE_REDEPESSOA RP WHERE RP.SEQREDE IN (
                       SELECT SEQREDE   FROM GE_REDE          WHERE DESCRICAO = :LS1))
   
   AND 1=1
   AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2
   AND X.STATUSNF != 'C'

   ORDER BY 1,3,2
 
