ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Busca Fornecedores em regras de factorings

SELECT DISTINCT X.SEQPESSOA, G.NOMERAZAO FORNECEDOR, F.DESCRICAO DESC_FILTRO, D.DESCRICAO DESC_REGRA, LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0) CNPJ_REGRA,
       CASE WHEN LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0) = 000000000000 THEN 'DIVERSOS' ELSE FF.NOMERAZAO END FACTORING
  FROM FI_FORNECEDOR X INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                        LEFT JOIN FI_DDAFILTRO F ON F.SEQFILTRO = X.SEQFILTRODDA
                        LEFT JOIN FI_DDAREGRA  D ON D.SEQFILTRO = F.SEQFILTRO
                        LEFT JOIN FI_DDAREGRADETALHE R ON R.SEQREGRA = D.SEQREGRA 
                        LEFT JOIN GE_PESSOA FF ON LPAD(FF.NROCGCCPF,12,0)||LPAD(FF.DIGCGCCPF,2,0) = LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0)
                        
 WHERE X.SEQFILTRODDA != 0
   AND R.NROCNPJCPF IS NOT NULL
 
 ORDER BY G.NOMERAZAO 
