CREATE OR REPLACE VIEW NAGV_ESPECIES_FILTRO_TIT AS 
SELECT CODESPECIE ESPECIE FROM FI_ESPECIE X WHERE CODESPECIE IN ('AGUA','ALUGPG','ATIVO','ATVEFU','COFINS','COSIND','CRIPAG','CSLL','DESP','DIVSOC','DUPP',
        'DVRBEC','ENERGI','ESPORT','FATDMC','FATICD','FGTS','FGTSQT','FRETE','GNRE','ICMS',
        'IMPOST','INSS','INSSNF','INTANG','IOFRETE','IPI','IPTU','IR','IRRFFP','IRRFNP',
        'ISSQN','ISSQNP','ISSST','LEIROU','PCCNF','PIS','PROCIV','RECARG','RETSOC','SEGURO',
        'SERVPJ','SUPERT','VLDESC')
        
        ORDER BY 1
        
        
SELECT TO_CHAR(DTAVENCIMENTO, 'MM') MES,
       TO_CHAR(DTAVENCIMENTO, 'YYYY') ANO,
       COUNT(NROTITULO) QTD_TITULOS, CODESPECIE ESPECIE
  FROM FI_TITULO X
 WHERE X.OBRIGDIREITO = 'O'
   AND X.DTAVENCIMENTO BETWEEN DATE '2024-01-01' AND DATE '2025-03-31'
   AND ABERTOQUITADO = 'Q'
   AND CODESPECIE IN
       (#LS1)

 GROUP BY TO_CHAR(DTAVENCIMENTO, 'MM'), TO_CHAR(DTAVENCIMENTO, 'YYYY'), CODESPECIE

 ORDER BY 2, 1

