SELECT /*+ ORDERED */  * FROM (
SELECT LA.NROEMPRESA EMP_CTB, TO_CHAR(LA.DTALANCTO, 'DD/MM/YYYY') DATA,
       LA.TIPOLANCTO TP,
       CASE WHEN LA.CODOPERACAO IN (452,948) THEN 11100200101 ELSE CASE WHEN LA.TIPOLANCTO IN ('D', 'H', 'C') THEN 
          CASE WHEN LA.TIPOLANCTO = 'D' THEN DB.CONTADB
               WHEN LA.TIPOLANCTO = 'C' THEN DT.CONTADB END ELSE DB.CONTACR END END PARTIDA,  
       CASE WHEN LA.CODOPERACAO IN (452,948) THEN 11200100004 ELSE CASE WHEN LA.TIPOLANCTO IN ('D', 'H', 'C') THEN 
         CASE WHEN LA.TIPOLANCTO = 'H' THEN DB.CONTADB 
           WHEN LA.TIPOLANCTO = 'D' THEN NVL(DC.CONTACR, DT.CONTACR)
           WHEN LA.TIPOLANCTO = 'C' THEN NVL(DB.CONTACR,DB.CONTACR) END ELSE NVL(DT.CONTADB, DC.CONTADB) END END
           C_PARTIDA,
       CASE WHEN ROW_NUMBER() OVER(PARTITION BY LA.NROPROCESSO, LA.CODOPERACAO ORDER BY LA.NROPROCESSO ASC,3, O.CODOPERACAO) = 1 OR LA.CODOPERACAO IN (134,122,123,124,145,401,252,452,948) THEN
       LA.VLRLANCAMENTO ELSE 0 END VLRLANCAMENTO,
       LA.HISTORICO,
       LA.NROPROCESSO,  
       LA.CODOPERACAO COD_OP,
       CTA.NROCONTA||CTA.DIGCONTA NROCONTA, 'Loja '||LPAD(CTA.NROEMPRESA,3,0)||' '||CTA.DESCRICAO CONTA,
       F.NROEMPRESA EMP_TIT, F.NROTITULO||CASE WHEN F.NROPARCELA IS NULL THEN NULL ELSE '-'||F.NROPARCELA END TIT_REF, 
       G.SEQPESSOA COD_FORN, G.NOMERAZAO FORNECEDOR,
       O.CODOPERACAO COD_OP_TIT,
       NVL(O.VLROPERACAO, LA.VLRLANCAMENTO) VLROP_BRUTO, 
       CASE WHEN LA.TIPOLANCTO = 'H' THEN 0 ELSE NVL(CASE WHEN O.CODOPERACAO IN (29,23) THEN 0 ELSE O.VLROPERACAO END, LA.VLRLANCAMENTO) END VLROP_CTB,
       COALESCE(DB.HISTORICO, DC.HISTORICO, DT.HISTORICO, T.HISTORICO) OBSERVACAO, 0 DIF
       
  FROM FI_CTACORLANCA LA LEFT JOIN FI_CONTABILIZACAO A ON A.SEQLANCTO = LA.SEQLANCTO AND LA.NROEMPRESA = A.NROEMPRESA AND A.NROPROCESSO = LA.NROPROCESSO AND DEBCRED = LA.TIPOLANCTO
                        INNER JOIN FI_CTACORRENTE CTA  ON CTA.SEQCTACORRENTE = LA.SEQCTACORRENTE
                         LEFT JOIN FI_TITOPERACAO O    ON O.NROPROCESSO = LA.NROPROCESSO AND LA.CODOPERACAO NOT IN (452,948,122,123,137,124,131) AND LA.TIPOLANCTO != 'H' AND NVL(O.OPCANCELADA, 'X') != 'C'
                         LEFT JOIN FI_TITULO F         ON F.SEQTITULO = O.SEQTITULO
                         LEFT JOIN GE_PESSOA G         ON G.SEQPESSOA = F.SEQPESSOA
                         LEFT JOIN CTV_LANCAMENTO DB   ON DB.PROCESSOCTB = LA.NROPROCESSO AND DB.NROEMPRESA = LA.NROEMPRESA AND DB.VALOR = NVL(O.VLROPERACAO, LA.VLRLANCAMENTO) 
                                                                                          AND(DB.CONTADB IS NOT NULL AND LA.TIPOLANCTO IN ('D','H') OR DB.CONTACR IS NOT NULL AND LA.TIPOLANCTO = 'C')
                         LEFT JOIN CTV_LANCAMENTO DC   ON DC.PROCESSOCTB = LA.NROPROCESSO AND DC.NROEMPRESA = LA.NROEMPRESA AND DC.VALOR = O.VLROPERACAO
                                                                                          AND(DC.CONTACR IS NOT NULL AND LA.TIPOLANCTO IN ('D','H') OR DC.CONTADB IS NOT NULL AND LA.TIPOLANCTO = 'C')
                         LEFT JOIN CTV_LANCAMENTO DT   ON DT.PROCESSOCTB = LA.NROPROCESSO AND DT.NROEMPRESA = LA.NROEMPRESA AND DT.VALOR = LA.VLRLANCAMENTO
                                                                                          AND(DT.CONTACR IS NOT NULL AND LA.TIPOLANCTO IN ('D','H') OR DT.CONTADB IS NOT NULL AND LA.TIPOLANCTO = 'C')
                         LEFT JOIN FI_CONTABILIZACAO T ON T.NROPROCESSO = LA.NROPROCESSO AND T.NROEMPRESA = LA.NROEMPRESA AND T.VALOR = F.VLRNOMINAL AND T.CTACONTABIL = DB.CONTADB
                                 
 WHERE 1=1
   AND LA.NROEMPRESA = #LS1
   AND LA.DTALANCTO BETWEEN :DT1 AND :DT2
   AND CTA.TIPOCONTA = 'B'
   AND CTA.DESCRICAO NOT LIKE '%INV%'
   AND LA.CODOPERACAO != 400
   AND NVL(LA.OPCANCELADA, 'X') != 'C'
   
UNION ALL

SELECT LOJA, DATA, 'S' TP, NULL, NULL, 0, 'Subtotal por Processo', NROPROCESSO, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 
      'Valor Lancto: '||TO_CHAR(SUM(VLRLANCAMENTO),   'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
 ||' | Valor CTB: '   ||TO_CHAR(SUM(VLROPERACAO_CTB), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
 ||' | Dif.: '        ||TO_CHAR(SUM(VLRLANCAMENTO) - SUM(VLROPERACAO_CTB), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''),
       SUM(VLRLANCAMENTO) - SUM(VLROPERACAO_CTB) DIF
 
 FROM (

SELECT LA.NROEMPRESA LOJA, TO_CHAR(LA.DTALANCTO, 'DD/MM/YYYY') DATA,
       NULL PARTIDA,   
       NULL C_PARTIDA,
       LA.TIPOLANCTO TP,
       CASE WHEN ROW_NUMBER() OVER(PARTITION BY LA.NROPROCESSO, LA.CODOPERACAO ORDER BY LA.NROPROCESSO ASC,3, O.CODOPERACAO) = 1 OR LA.CODOPERACAO IN (134,122,123,124,145,401,252,452,948) THEN 
       LA.VLRLANCAMENTO ELSE 0 END VLRLANCAMENTO,
       LA.HISTORICO,
       LA.NROPROCESSO,
       LA.CODOPERACAO COD_OP,
       NULL CONTA,
       NULL TIT_REF, 
       NVL(O.VLROPERACAO, LA.VLRLANCAMENTO) VLROPERACAO_BRUTO, 
       CASE WHEN LA.TIPOLANCTO = 'H' THEN 0 ELSE NVL(CASE WHEN O.CODOPERACAO IN (29,23) THEN 0 ELSE O.VLROPERACAO * CASE WHEN O.CODOPERACAO = 114 THEN -1 ELSE 1 END 
         END, LA.VLRLANCAMENTO) END VLROPERACAO_CTB,
       O.OBSERVACAO OPERACAO
       
  FROM FI_CTACORLANCA LA LEFT JOIN FI_CONTABILIZACAO A ON A.SEQLANCTO = LA.SEQLANCTO AND LA.NROEMPRESA = A.NROEMPRESA AND A.NROPROCESSO = LA.NROPROCESSO AND DEBCRED = LA.TIPOLANCTO
                         LEFT JOIN FI_TITOPERACAO O    ON O.NROPROCESSO = LA.NROPROCESSO AND LA.CODOPERACAO NOT IN (452,948,122,123,137,124,131) AND LA.TIPOLANCTO != 'H' AND NVL(O.OPCANCELADA, 'X') != 'C'
                        INNER JOIN FI_CTACORRENTE CTA  ON CTA.SEQCTACORRENTE = LA.SEQCTACORRENTE

 WHERE 1=1
   AND LA.NROEMPRESA = #LS1
   AND LA.DTALANCTO BETWEEN :DT1 AND :DT2
   AND CTA.TIPOCONTA = 'B'
   AND CTA.DESCRICAO NOT LIKE '%INV%'
   AND LA.CODOPERACAO != 400
   AND NVL(LA.OPCANCELADA, 'X') != 'C'
   
   ) 
   GROUP BY LOJA, DATA, NROPROCESSO
   )
   WHERE COD_OP != 400

   ORDER BY 2, NROPROCESSO, 3,6 DESC;
   
