SELECT * FROM (

WITH cte_NRODI AS (SELECT NUMERODI FROM CONSINCO.MAD_PIPROCIMPORTACAO PD
                                  WHERE PD.NROPROCIMPORTACAO = :NR2)

SELECT XX1.*,
 /*Select de Subtototais*/
      (SELECT 'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
  FROM FI_TITULO X 
 WHERE X.NROTITULO    IN (062025) AND NROEMPRESA IN (502,503) AND SITUACAO != 'C' AND CODESPECIE = 'ANTPGI') TOT_TIT_GER,
 /******/
      (SELECT 'R$ '||TO_CHAR(SUM(VLRORIGINAL * DECODE(OBRIGDIREITO, 'D',-1,'O',1)),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
  FROM FI_TITULO X 
 WHERE X.NRODOCUMENTO = 062025  AND NROEMPRESA IN (502,503) AND SITUACAO != 'C' AND X.OBSERVACAO NOT LIKE '%SEGURO%') TOT_DESP_GER,
 /******/
      (SELECT 'R$ '||TO_CHAR(SUM(ZX.VALORLIQ),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.OR_NFVENCIMENTO ZX ON ZX.SEQNOTA = ZZ.SEQNOTA   
 WHERE ZZ.DTAEMISSAO > SYSDATE - 365
   AND (UPPER(REPLACE(ZZ.OBSERVACAO, '-','/')) LIKE UPPER('%'||(SELECT TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 1)) FP FROM dual)||'%')
    OR UPPER(REPLACE(ZZ.OBSERVACAO, '-','/')) LIKE UPPER('%'||(SELECT CASE WHEN TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 2)) IS NOT NULL 
                                                         THEN TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 2)) ELSE 'X_GLN' END FP FROM dual)||'%'))) TOT_ORC_GER,
 /******/
 
 /*Diferenca*/
 
'R$ '||TO_CHAR(((SELECT SUM(VLRORIGINAL)
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO    IN (062025) AND NROEMPRESA IN (502,503) AND SITUACAO != 'C')  -
 /******/
      (SELECT SUM(VLRORIGINAL * DECODE(OBRIGDIREITO, 'D',-1,'O',1))
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA   
 WHERE X.NRODOCUMENTO = 062025  AND NROEMPRESA IN (502,503) AND SITUACAO != 'C' AND X.OBSERVACAO NOT LIKE '%SEGURO%')  -
 /******/
      (SELECT SUM(ZX.VALORLIQ)
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.OR_NFVENCIMENTO ZX ON ZX.SEQNOTA = ZZ.SEQNOTA       
 WHERE ZZ.DTAEMISSAO > SYSDATE - 365
   AND (UPPER(REPLACE(ZZ.OBSERVACAO, '-','/')) LIKE UPPER('%'||(SELECT TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 1)) FP FROM dual)||'%')
    OR UPPER(REPLACE(ZZ.OBSERVACAO, '-','/')) LIKE UPPER('%'||(SELECT CASE WHEN TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 2)) IS NOT NULL 
                                                         THEN TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 2)) ELSE 'X_GLN' END FP FROM dual)||'%')))
                                                           
  /* Creditos */ -
  (SELECT NVL(SUM(VLRLANCAMENTO),0) FROM FI_CTACORLANCA F
   WHERE 1=1 
     AND UPPER(HISTORICO) LIKE '%TÍTULO(S): '||SUBSTR(TO_CHAR(TO_NUMBER('062025')),INSTR(TO_CHAR(TO_NUMBER('062025')),',') +1,10)||'%'
     AND TIPOLANCTO = 'C'
     AND NROEMPRESA IN (502,503)
     AND F.DTALANCTO > SYSDATE - 365) 
  /* Debitos */ +
  (SELECT NVL(SUM(VLRLANCAMENTO),0) FROM FI_CTACORLANCA F
   WHERE  1=1 
     AND UPPER(HISTORICO) LIKE '%TÍTULO(S): '||SUBSTR(TO_CHAR(TO_NUMBER('062025')),INSTR(TO_CHAR(TO_NUMBER('062025')),',') +1,10)||'%'
     AND TIPOLANCTO = 'D'
     AND NROEMPRESA IN (502,503)
     AND F.DTALANCTO > SYSDATE - 365)) 
                                                           ,  
                                                           'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') DIFERENCA,
  /* Termina Diferenca*/
  /* Nota Aberta */
  
 (SELECT ICMS   FROM NAGV_NOTAABERTA_IMP NA INNER JOIN cte_NRODI ON NUMERODI = NA.NRODECLARAIMPORT) ICMS,
 (SELECT PIS    FROM NAGV_NOTAABERTA_IMP NA INNER JOIN cte_NRODI ON NUMERODI = NA.NRODECLARAIMPORT) PIS,
 (SELECT COFINS FROM NAGV_NOTAABERTA_IMP NA INNER JOIN cte_NRODI ON NUMERODI = NA.NRODECLARAIMPORT) COFINS,
 (SELECT II     FROM NAGV_NOTAABERTA_IMP NA INNER JOIN cte_NRODI ON NUMERODI = NA.NRODECLARAIMPORT) II,
 (SELECT AFRMM  FROM NAGV_NOTAABERTA_IMP NA INNER JOIN cte_NRODI ON NUMERODI = NA.NRODECLARAIMPORT) AFRMM,
 (SELECT OUTRAS FROM NAGV_NOTAABERTA_IMP NA INNER JOIN cte_NRODI ON NUMERODI = NA.NRODECLARAIMPORT) OUTRAS,
  
  /* Termina Nota Aberta */
 
  (SELECT 'Referência: DI: '||PD.NUMERODI||' - Data de Registro: '||TO_CHAR(DTAREGISTRO, 'DD/MM/YYYY') REF_DI
          FROM consinco.MAD_DI PD INNER JOIN cte_NRODI ON cte_NRODI.NUMERODI = PD.NUMERODI) REF_DI,
          
  (SELECT PD.NUMERODI FROM CONSINCO.MAD_PIPROCIMPORTACAO PD INNER JOIN cte_NRODI ON cte_NRODI.NUMERODI = PD.NUMERODI)  NRO_DI,
  '        Dossie - Conferência '||'#LT1' NRO_EMB,
  
  /* Creditos */
  (SELECT 'R$ '||TO_CHAR(NVL(SUM(VLRLANCAMENTO),0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') FROM FI_CTACORLANCA F
   WHERE  1=1 
     AND UPPER(HISTORICO) LIKE '%TÍTULO(S): '||SUBSTR(TO_CHAR(TO_NUMBER('062025')),INSTR(TO_CHAR(TO_NUMBER('062025')),',') +1,10)||'%'
     AND TIPOLANCTO = 'C'
     AND NROEMPRESA IN (502,503)
     AND F.DTALANCTO > SYSDATE - 365) CREDITOS,
  /* Debitos */
  (SELECT 'R$ '||TO_CHAR(NVL(SUM(VLRLANCAMENTO),0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') FROM FI_CTACORLANCA F
   WHERE  1=1 
     AND UPPER(HISTORICO) LIKE '%TÍTULO(S): '||SUBSTR(TO_CHAR(TO_NUMBER('062025')),INSTR(TO_CHAR(TO_NUMBER('062025')),',') +1,10)||'%'
     AND TIPOLANCTO = 'D'
     AND NROEMPRESA IN (502,503)
     AND F.DTALANCTO > SYSDATE - 365) DEBITOS
     
  FROM (
  
  /*Select do Grid*/
  
SELECT * FROM (
 SELECT 'TITULO' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, 062025 PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_ORIGINAL, 
       'R$ '||TO_CHAR(VLRPAGO,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_QUITADO,
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, 
       OBSERVACAO, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 1 S
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO IN (062025) AND NROEMPRESA IN (502,503) AND SITUACAO != 'C' AND X.OBRIGDIREITO = 'D'  ORDER BY 9)
 
  UNION ALL
SELECT 'TITULO', NULL ,NULL, NULL, 'TOTAL DE TITULOS GERADOS', NULL, NULL, 
       'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), 
       'R$ '||TO_CHAR(SUM(VLRPAGO),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_QUITADO, NULL, NULL, NULL, NULL, NULL, 1
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO IN (062025) AND NROEMPRESA IN (502,503) AND SITUACAO != 'C' AND CODESPECIE = 'ANTPGI'

  UNION ALL

SELECT * FROM (
  
SELECT 'DESP_IMP' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, NRODOCUMENTO PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       'R$ '||TO_CHAR(VLRPAGO,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_QUITADO,
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, SUBSTR(OBSERVACAO,15) OBS, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 2
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = 062025 AND NROEMPRESA IN (502,503) AND SITUACAO != 'C' AND X.OBSERVACAO NOT LIKE '%SEGURO%'

ORDER BY 11
 
)

  UNION ALL
SELECT 'DESP_IMP', NULL ,NULL, NULL, 'TOTAL DE DESPESAS GERADAS', NULL, NULL,
       'R$ '||TO_CHAR(SUM(VLRORIGINAL * DECODE(OBRIGDIREITO, 'D',-1,'O',1)),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''),
       'R$ '||TO_CHAR(SUM(VLRPAGO * DECODE(OBRIGDIREITO, 'D',-1,'O',1)),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), NULL, NULL, NULL, NULL, NULL, 2
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = 062025 AND NROEMPRESA IN (502,503) AND SITUACAO != 'C' AND X.OBSERVACAO NOT LIKE '%SEGURO%'
 
 UNION ALL
SELECT 'ORCAMENTO' TIPO, CG.CODESPECIE CODESPECIE,
       CG.SEQTITULO,
       ZZ.NROEMPRESA, ZZ.SEQPESSOA||' - '||GG.NOMERAZAO FORNECEDOR, ZZ.NRONOTA, 062025 PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       'R$ '||TO_CHAR(VLRPAGO,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_QUITADO,
       TO_CHAR(ZZ.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO,
       TO_CHAR(ZZ.DTAVENCINICIAL, 'DD/MM/YYYY') DTAVENCIMENTO, REPLACE(ZZ.OBSERVACAO, '-','/') OBS,
       'OBR' OD,
       DECODE(CG.ABERTOQUITADO, 'A', 'ABERTO' , 'QUITADO') SITUACAO, 3
       
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.GE_PESSOA GG ON GG.SEQPESSOA = ZZ.SEQPESSOA
                                INNER JOIN CONSINCO.OR_NFVENCIMENTO ZX ON ZX.SEQNOTA = ZZ.SEQNOTA
                                LEFT JOIN  FI_TITULO CG          ON CG.NROTITULO = ZZ.NRONOTA 
                                                                AND CG.NROEMPRESA = ZZ.NROEMPRESA 
                                                                AND CG.SEQPESSOA = ZZ.SEQPESSOA
                                                                AND CG.LINKERP = ZZ.LINKERP
 WHERE ZZ.DTAEMISSAO > SYSDATE - 365
   AND (UPPER(REPLACE(ZZ.OBSERVACAO, '-','/')) LIKE UPPER('%'||(SELECT TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 1)) FP FROM dual)||'%')
    OR UPPER(REPLACE(ZZ.OBSERVACAO, '-','/')) LIKE UPPER('%'||(SELECT CASE WHEN TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 2)) IS NOT NULL 
                                                         THEN TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 2)) ELSE 'X_GLN' END FP FROM dual)||'%'))
 
  UNION ALL
SELECT 'ORCAMENTO', NULL ,NULL, NULL, 'TOTAL NFS DESP NACIONAIS', NULL, NULL,
       'R$ '||TO_CHAR(SUM(CG.VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       'R$ '||TO_CHAR(SUM(CG.VLRPAGO),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR2 ,NULL, NULL, NULL, NULL, NULL, 3
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.GE_PESSOA GG ON GG.SEQPESSOA = ZZ.SEQPESSOA
                                INNER JOIN CONSINCO.OR_NFVENCIMENTO ZX ON ZX.SEQNOTA = ZZ.SEQNOTA
                                LEFT JOIN  FI_TITULO CG          ON CG.NROTITULO = ZZ.NRONOTA 
                                                                AND CG.NROEMPRESA = ZZ.NROEMPRESA 
                                                                AND CG.SEQPESSOA = ZZ.SEQPESSOA
                                                                AND CG.LINKERP = ZZ.LINKERP
                                
 WHERE ZZ.DTAEMISSAO > SYSDATE - 365
   AND (UPPER(REPLACE(ZZ.OBSERVACAO, '-','/')) LIKE UPPER('%'||(SELECT TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 1)) FP FROM dual)||'%')
    OR UPPER(REPLACE(ZZ.OBSERVACAO, '-','/')) LIKE UPPER('%'||(SELECT CASE WHEN TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 2)) IS NOT NULL
                                                         THEN TRIM(REGEXP_SUBSTR('#LT1', '[^,]+', 1, 2)) ELSE 'X_GLN' END FP FROM dual)||'%'))
 
 UNION ALL
SELECT 'NF' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, 062025 PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       'R$ '||TO_CHAR(VLRPAGO,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_QUITADO,
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, NULL OBSERVACAO, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 4
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
  
/* WHERE X.NROTITULO IN (SELECT C.NUMERONF FROM MLF_NOTAFISCAL C
         WHERE EXISTS (SELECT 1 
                         FROM MAD_ADICAO B INNER JOIN MAD_DI A ON A.NUMERODI = B.NUMERODI
                        WHERE B.SEQAUXNOTAFISCAL = C.SEQAUXNOTAFISCAL
                          AND A.NROPROCIMPORTACAO = :NR2
                          AND X.SEQPESSOA = C.SEQPESSOA
                           OR A.NUMERODI = C.NRODECLARAIMPORT AND C.CODGERALOPER = 44
                           AND X.SEQPESSOA = C.SEQPESSOA))*/
                           
 WHERE EXISTS (SELECT 1 FROM MLF_NOTAFISCAL C
         WHERE EXISTS (SELECT 1 
                         FROM MAD_ADICAO B INNER JOIN MAD_DI A ON A.NUMERODI = B.NUMERODI
                        WHERE B.SEQAUXNOTAFISCAL = C.SEQAUXNOTAFISCAL
                          AND A.NROPROCIMPORTACAO = :NR2
                          AND X.SEQPESSOA = C.SEQPESSOA
                           OR A.NUMERODI = C.NRODECLARAIMPORT AND C.CODGERALOPER = 44
                           AND A.NROPROCIMPORTACAO = :NR2
                           AND X.SEQPESSOA = C.SEQPESSOA)
                           
                           AND C.NUMERONF = X.NROTITULO 
                           AND (C.LINKERP = X.LINKERP OR X.CODESPECIE = 'IMPCON'))
           
   AND NROEMPRESA IN (502,503) AND X.SITUACAO NOT IN ('C')
   AND ORIGEMDOC = 'INTE'
   AND UF = 'EX'
       
) XX1)
