SELECT A.NROEMPRESA LOJA, TO_CHAR(A.DTACONTABILIZA, 'DD/MM/YYYY') DATA,
       D.CONTADB PARTIDA,   /*D.VALOR VALOR_P,*/
       C.CONTACR C_PARTIDA,/* C.VALOR VALOR_CP,*/
       A.VALOR,
       A.HISTORICO,
       A.NROPROCESSO PROCESSO, CTA.NROCONTA||CTA.DIGCONTA NROCONTA, 'Loja '||LPAD(CTA.NROEMPRESA,3,0)||' '||CTA.DESCRICAO CONTA
       
  FROM FI_CONTABILIZACAO A INNER JOIN CTV_LANCAMENTO D ON A.NROPROCESSO = D.PROCESSOCTB AND A.CTACONTABIL = D.CONTADB
                           INNER JOIN CTV_LANCAMENTO C ON A.NROPROCESSO = C.PROCESSOCTB AND C.TIPOENTIDADECR = 'BC'
                           INNER JOIN FI_CTACORLANCA LA ON A.SEQLANCTO = LA.SEQLANCTO AND LA.NROEMPRESA = A.NROEMPRESA AND A.NROPROCESSO = LA.NROPROCESSO
                           INNER JOIN FI_CTACORRENTE CTA ON CTA.SEQCTACORRENTE = LA.SEQCTACORRENTE

 WHERE 1=1
   AND A.TABLINK IN ('C/C', 'DEV')
   AND D.ORIGEM = 'FI' AND C.ORIGEM = 'FI'
   AND A.DEBCRED = 'D'
   AND A.NROEMPRESA IN (#LS1)
   AND DTACONTABILIZA BETWEEN :DT1 AND :DT2
   
 ORDER BY A.NROPROCESSO ASC;
