ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Busca apenas requisicoes que estao configuradas com Origem Desp = Matriz/Rede (Customizacao)

SELECT X.NROEMPRESA, NRONOTA, SERIE, R.NROREQUISICAO, X.SEQPESSOA||' - '||(SELECT NOMERAZAO FROM GE_PESSOA G WHERE G.SEQPESSOA = X.SEQPESSOA) FORNECEDOR,
       TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') DTA_ENTRADA, X.VALOR
  FROM OR_NFDESPESA X INNER JOIN OR_REQUISICAO R ON R.SEQREQUISICAO = X.REQUISICOES
                      INNER JOIN ESP_OR_ALTERAORIGEMDESPESA CUST ON CUST.SEQREQUISICAO = R.SEQREQUISICAO
 WHERE 1=1
   AND X.NROEMPRESA IN (#LS1)
   AND CUST.CODORIGDESPESA = 1
   AND DTAENTRADA BETWEEN :DT1 AND :DT2
   
   ORDER BY X.NROEMPRESA, DTAENTRADA, NRONOTA
