ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT FI_INTTITULO.ORIGEM,
       FI_INTTITULO.NROTITULO || '-' || FI_INTTITULO.SERIETITULO || '/' ||
       FI_INTTITULO.NROPARCELA TITULO,
       FI_INTTITULO.USUALTERACAO,
       FI_INTTITULO.NROEMPRESA,
       FI_INTTITULO.CODESPECIE,
       TO_CHAR(FI_INTTITULO.DTAMOVIMENTO, 'DD/MM/YYYY') DTAMOVIMENTO,
       FI_INTTITULO.VLRORIGINAL,
       TO_CHAR(FI_INTTITULO.DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO,
       GE_PESSOA.SEQPESSOA || '-' || GE_PESSOA.NOMERAZAO,
       TO_CHAR(FI_REJEITADO.DTAALTERACAO, 'DD/MM/YYYY HH24:MI') DTA_HORA

  FROM FI_INTTITULO, GE_PESSOA, FI_REJEITADO
 WHERE 1 = 1
  -AND FI_INTTITULO.NROEMPRESA IN (#LS1)
   AND GE_PESSOA.SEQPESSOA(+) = FI_INTTITULO.CODPESSOA
   AND FI_INTTITULO.SEQINTTITULO = FI_REJEITADO.CODLINK
   AND TRUNC(FI_REJEITADO.DTAALTERACAO) BETWEEN :DT1 AND :DT2
