SELECT DISTINCT C.NROPROCIMPORTACAO NRO_PROCESSO, NUMERONF, X.NROEMPRESA
  FROM MLF_NOTAFISCAL X INNER JOIN MAD_ADICAO B ON B.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
                        INNER JOIN MAD_DI C     ON C.NUMERODI = B.NUMERODI
                               
 WHERE NUMERONF IN (#LT1)
