-- QRP em https://github.com/GiulianoGMS/QRPs/blob/main/RelExtTransitoria.QRP

SELECT EMPRESA EMP, 
       CASE WHEN CONTA IS NULL THEN NULL ELSE EMPRESA END EMPRESA, 
       CASE WHEN LENGTH(CONTA) < 5 THEN '0,28% Sobre o Total' ELSE CONTA END CONTA, DTA_LANCTO, OPERACAO, DETALHE, VLR_LANCTO FROM (

SELECT A.NROEMPRESA EMPRESA, B.DESCRICAO||' - '||A.SEQCTACORRENTE CONTA, TO_CHAR(A.DTALANCTO, 'DD/MM/YYYY') DTA_LANCTO,
       A.CODOPERACAO OPERACAO, 
       CASE WHEN LENGTH(HISTORICO) > 70 THEN SUBSTR(HISTORICO,0,70)||'...' ELSE HISTORICO END DETALHE, 
       'R$ '||TO_CHAR(A.VLRLANCAMENTO, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_LANCTO, 1 ODR

  FROM FI_CTACORLANCA A LEFT JOIN FI_CTACORRENTE B ON A.SEQCTACORRENTE = B.SEQCTACORRENTE
                        LEFT JOIN FI_GRUPOCONTACORRENTE C ON B.SEQGRUPO = C.SEQGRUPO
                        LEFT JOIN FI_OPERACAO D ON A.CODOPERACAO = D.CODOPERACAO
                       INNER JOIN GE_EMPRESA E ON E.NROEMPRESA = A.NROEMPRESA
       
 WHERE 1=1 
   AND 2=2 
   AND E.STATUS = 'A'
   AND DTALANCTO BETWEEN :DT1 AND :DT2
   AND B.TIPOCONTA = 'T'
   AND B.SITUACAO = 'A'
   AND A.CODOPERACAO = 960
   AND A.SEQCTACORRENTE IN (SELECT SEQCTACORRENTE
                              FROM FI_CTACORRENTE
                             WHERE TIPOCONTA = 'T'
                               AND NROEMPRESA IN (SELECT G.NROEMPRESA
                                                    FROM GE_EMPRESA G
                                                   WHERE G.STATUS = 'A'
                                                     AND G.NROEMPRESA IN (#LS1))
                               AND FI_CTACORRENTE.SITUACAO = 'A'
                               AND DESCRICAO LIKE 'TRANSITORIA GUIA CARRO FORTE%')
   AND OPCANCELADA IS NULL
   AND TIPOLANCTO != 'H'

UNION ALL

SELECT A.NROEMPRESA EMPRESA, NULL A, NULL B, NULL C,
       'Valor Total:',
       'R$ '||TO_CHAR(SUM(A.VLRLANCAMENTO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') SALDO, 2 ODR

  FROM FI_CTACORLANCA A LEFT JOIN FI_CTACORRENTE B ON A.SEQCTACORRENTE = B.SEQCTACORRENTE
                        LEFT JOIN FI_GRUPOCONTACORRENTE C ON B.SEQGRUPO = C.SEQGRUPO
                        LEFT JOIN FI_OPERACAO D ON A.CODOPERACAO = D.CODOPERACAO
                       INNER JOIN GE_EMPRESA E ON E.NROEMPRESA = A.NROEMPRESA
       
 WHERE 1=1
   AND 2=2
   AND E.STATUS = 'A'
   AND DTALANCTO BETWEEN :DT1 AND :DT2
   AND B.TIPOCONTA = 'T'
   AND B.SITUACAO = 'A'
   AND A.CODOPERACAO = 960
   AND A.SEQCTACORRENTE IN (SELECT SEQCTACORRENTE
                              FROM FI_CTACORRENTE
                             WHERE TIPOCONTA = 'T'
                               AND NROEMPRESA IN (SELECT G.NROEMPRESA
                                                    FROM GE_EMPRESA G
                                                   WHERE G.STATUS = 'A'
                                                     AND G.NROEMPRESA IN (#LS1))
                               AND FI_CTACORRENTE.SITUACAO = 'A'
                               AND DESCRICAO LIKE 'TRANSITORIA GUIA CARRO FORTE%')
   AND OPCANCELADA IS NULL
   AND TIPOLANCTO != 'H'
       
GROUP BY A.NROEMPRESA, B.DESCRICAO||' - '||A.SEQCTACORRENTE

UNION ALL

SELECT A.NROEMPRESA EMPRESA, 
       CASE WHEN DECODE(:LS2, 'Apenas 0.28%', '0.28%:') = '0.28%:' THEN TO_CHAR(A.NROEMPRESA) ELSE NULL END, 
       CASE WHEN DECODE(:LS2, 'Apenas 0.28%', '0.28%:') = '0.28%:' THEN TO_CHAR(A.DTALANCTO, 'MM/YYYY') ELSE NULL END, 
       CASE WHEN DECODE(:LS2, 'Apenas 0.28%', '0.28%:') = '0.28%:' THEN A.CODOPERACAO ELSE NULL END,
       '0.28%:',
       'R$ '||TO_CHAR((SUM(A.VLRLANCAMENTO) * 0.28) / 100, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') SALDO, 3 ODR

  FROM FI_CTACORLANCA A LEFT JOIN FI_CTACORRENTE B ON A.SEQCTACORRENTE = B.SEQCTACORRENTE
                        LEFT JOIN FI_GRUPOCONTACORRENTE C ON B.SEQGRUPO = C.SEQGRUPO
                        LEFT JOIN FI_OPERACAO D ON A.CODOPERACAO = D.CODOPERACAO
                       INNER JOIN GE_EMPRESA E ON E.NROEMPRESA = A.NROEMPRESA
       
 WHERE 1=1 
   AND 2=2 
   AND E.STATUS = 'A'
   AND DTALANCTO BETWEEN :DT1 AND :DT2
   AND B.TIPOCONTA = 'T'
   AND B.SITUACAO = 'A'
   AND A.CODOPERACAO = 960
   AND A.SEQCTACORRENTE IN (SELECT SEQCTACORRENTE
                              FROM FI_CTACORRENTE
                             WHERE TIPOCONTA = 'T'
                               AND NROEMPRESA IN (SELECT G.NROEMPRESA
                                                    FROM GE_EMPRESA G
                                                   WHERE G.STATUS = 'A'
                                                     AND G.NROEMPRESA IN (#LS1))
                               AND FI_CTACORRENTE.SITUACAO = 'A'
                               AND DESCRICAO LIKE 'TRANSITORIA GUIA CARRO FORTE%')
   AND OPCANCELADA IS NULL
   AND TIPOLANCTO != 'H'
       
GROUP BY A.NROEMPRESA,  B.DESCRICAO||' - '||A.SEQCTACORRENTE,  TO_CHAR(A.DTALANCTO, 'MM/YYYY'), A.CODOPERACAO
/*
UNION ALL

SELECT A.NROEMPRESA EMPRESA, NULL, NULL,
       NULL,
       'Valor Líquido NF:',
       'R$ '||TO_CHAR(SUM(A.VLRLANCAMENTO) - ((SUM(A.VLRLANCAMENTO) * 0.28) / 100), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') SALDO, 4 ODR

  FROM FI_CTACORLANCA A LEFT JOIN FI_CTACORRENTE B ON A.SEQCTACORRENTE = B.SEQCTACORRENTE
                        LEFT JOIN FI_GRUPOCONTACORRENTE C ON B.SEQGRUPO = C.SEQGRUPO
                        LEFT JOIN FI_OPERACAO D ON A.CODOPERACAO = D.CODOPERACAO
                       INNER JOIN GE_EMPRESA E ON E.NROEMPRESA = A.NROEMPRESA
       
 WHERE 1=1
   AND 2=2
   AND E.STATUS = 'A'
   AND DTALANCTO BETWEEN :DT1 AND :DT2
   AND B.TIPOCONTA = 'T'
   AND B.SITUACAO = 'A'
   AND A.CODOPERACAO = 960
   AND A.SEQCTACORRENTE IN (SELECT SEQCTACORRENTE
                              FROM FI_CTACORRENTE
                             WHERE TIPOCONTA = 'T'
                               AND NROEMPRESA IN (SELECT G.NROEMPRESA
                                                    FROM GE_EMPRESA G
                                                   WHERE G.STATUS = 'A'
                                                     AND G.NROEMPRESA IN (#LS1))
                               AND FI_CTACORRENTE.SITUACAO = 'A'
                               AND DESCRICAO LIKE 'TRANSITORIA GUIA CARRO FORTE%')
   AND OPCANCELADA IS NULL
   AND TIPOLANCTO != 'H'
       
GROUP BY A.NROEMPRESA, B.DESCRICAO||' - '||A.SEQCTACORRENTE*/

ORDER BY 1, 7)

WHERE 1=1 AND DECODE(:LS2, 'Apenas 0.28%', '0.28%:') = DETALHE OR :LS2 = 'Detalhado' AND 1=1

       
GROUP BY A.NROEMPRESA, B.DESCRICAO||' - '||A.SEQCTACORRENTE

ORDER BY 1, 7)
