SELECT * FROM (
SELECT LA.NROEMPRESA EMP_CTB, TO_CHAR(LA.DTALANCTO, 'DD/MM/YYYY') DATA,
       LA.TIPOLANCTO TP,
       CASE WHEN LA.CODOPERACAO = 452 THEN 11100200101 ELSE (SELECT MAX(CONTADB) CT FROM CTV_LANCAMENTO A WHERE A.PROCESSOCTB = LA.NROPROCESSO AND NROEMPRESA = LA.NROEMPRESA) END PARTIDA,  
       CASE WHEN LA.CODOPERACAO = 452 THEN 11200100004 ELSE 
         NVL((SELECT MAX(CONTACR) CT FROM CTV_LANCAMENTO A WHERE A.PROCESSOCTB = LA.NROPROCESSO AND NROEMPRESA = LA.NROEMPRESA AND A.VALOR = O.VLROPERACAO),    -- Pega C_PARTIDA Filho
             (SELECT MAX(CONTACR) CT FROM CTV_LANCAMENTO A WHERE A.PROCESSOCTB = LA.NROPROCESSO AND NROEMPRESA = LA.NROEMPRESA AND A.VALOR = LA.VLRLANCAMENTO)) -- Pega C_PARTIDA Pai
          END C_PARTIDA,
       CASE WHEN ROW_NUMBER() OVER(PARTITION BY LA.NROPROCESSO, LA.CODOPERACAO ORDER BY LA.NROPROCESSO ASC,3, O.CODOPERACAO) = 1 THEN 
       LA.VLRLANCAMENTO ELSE 0 END VLRLANCAMENTO,
       LA.HISTORICO,
       LA.NROPROCESSO,  
       LA.CODOPERACAO COD_OP,
       CTA.NROCONTA||CTA.DIGCONTA NROCONTA, 'Loja '||LPAD(CTA.NROEMPRESA,3,0)||' '||CTA.DESCRICAO CONTA,
       F.NROEMPRESA EMP_TIT, F.NROTITULO||CASE WHEN F.NROPARCELA IS NULL THEN NULL ELSE '-'||F.NROPARCELA END TIT_REF, 
       O.CODOPERACAO COD_OP_TIT,
       NVL(O.VLROPERACAO, LA.VLRLANCAMENTO) VLROP_BRUTO, 
       CASE WHEN LA.TIPOLANCTO = 'H' THEN 0 ELSE NVL(CASE WHEN O.CODOPERACAO = 29 THEN 0 ELSE O.VLROPERACAO END, LA.VLRLANCAMENTO) END VLROP_CTB,
       CASE WHEN O.OBSERVACAO IS NULL THEN NULL ELSE '* '||O.OBSERVACAO END OBSERVACAO, 0 DIF
       
  FROM FI_CTACORLANCA LA LEFT JOIN FI_CONTABILIZACAO A ON A.SEQLANCTO = LA.SEQLANCTO AND LA.NROEMPRESA = A.NROEMPRESA AND A.NROPROCESSO = LA.NROPROCESSO AND DEBCRED = LA.TIPOLANCTO
                        INNER JOIN FI_CTACORRENTE CTA  ON CTA.SEQCTACORRENTE = LA.SEQCTACORRENTE
                         LEFT JOIN FI_TITOPERACAO O    ON O.NROPROCESSO = LA.NROPROCESSO AND LA.CODOPERACAO != 452 AND LA.CODOPERACAO NOT IN (122,123) AND LA.TIPOLANCTO != 'H' 
                         LEFT JOIN FI_TITULO F         ON F.SEQTITULO = O.SEQTITULO
                                 
 WHERE 1=1
   AND LA.NROEMPRESA IN (9)
   AND LA.DTALANCTO = DATE '2025-03-31'
   AND CTA.NROCONTA = 13490
   
UNION ALL

SELECT LOJA, DATA, 'S' TP, NULL, NULL, 0, 'Subtotal por Processo', NROPROCESSO, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, 
      'Valor Lancto: '||TO_CHAR(SUM(VLRLANCAMENTO),   'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
 ||' | Valor CTB: '   ||TO_CHAR(SUM(VLROPERACAO_CTB), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
 ||' | Dif.: '        ||TO_CHAR(SUM(VLRLANCAMENTO) - SUM(VLROPERACAO_CTB), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''),
       SUM(VLRLANCAMENTO) - SUM(VLROPERACAO_CTB) DIF
 
 FROM (

SELECT LA.NROEMPRESA LOJA, TO_CHAR(LA.DTALANCTO, 'DD/MM/YYYY') DATA,
       NULL PARTIDA,   
       NULL C_PARTIDA,
       LA.TIPOLANCTO TP,
       CASE WHEN ROW_NUMBER() OVER(PARTITION BY LA.NROPROCESSO, LA.CODOPERACAO ORDER BY LA.NROPROCESSO ASC,3, O.CODOPERACAO) = 1 THEN 
       LA.VLRLANCAMENTO ELSE 0 END VLRLANCAMENTO,
       LA.HISTORICO,
       LA.NROPROCESSO,
       LA.CODOPERACAO COD_OP,
       CTA.NROCONTA||CTA.DIGCONTA NROCONTA, 'Loja '||LPAD(CTA.NROEMPRESA,3,0)||' '||CTA.DESCRICAO CONTA,
       F.NROTITULO||CASE WHEN F.NROPARCELA IS NULL THEN NULL ELSE '-'||F.NROPARCELA END TIT_REF, 
       NVL(O.VLROPERACAO, LA.VLRLANCAMENTO) VLROPERACAO_BRUTO, 
       CASE WHEN LA.TIPOLANCTO = 'H' THEN 0 ELSE NVL(CASE WHEN O.CODOPERACAO = 29 THEN 0 ELSE O.VLROPERACAO END, LA.VLRLANCAMENTO) END VLROPERACAO_CTB,
       O.OBSERVACAO OPERACAO
       
  FROM FI_CTACORLANCA LA LEFT JOIN FI_CONTABILIZACAO A ON A.SEQLANCTO = LA.SEQLANCTO AND LA.NROEMPRESA = A.NROEMPRESA AND A.NROPROCESSO = LA.NROPROCESSO AND DEBCRED = LA.TIPOLANCTO
                        INNER JOIN FI_CTACORRENTE CTA  ON CTA.SEQCTACORRENTE = LA.SEQCTACORRENTE
                         LEFT JOIN FI_TITOPERACAO O    ON O.NROPROCESSO = LA.NROPROCESSO AND LA.CODOPERACAO != 452 AND LA.CODOPERACAO NOT IN (122,123) AND LA.TIPOLANCTO != 'H' 
                         LEFT JOIN FI_TITULO F         ON F.SEQTITULO = O.SEQTITULO
                                 
 WHERE 1=1
   AND LA.NROEMPRESA IN (9)
   AND LA.DTALANCTO = DATE '2025-03-31'
   AND CTA.NROCONTA = 13490
   
   ) 
   GROUP BY LOJA, DATA, NROPROCESSO
   )

   ORDER BY 2, NROPROCESSO, 3,6 DESC;
   
