ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT NROEMPRESA EMP, CODOPERACAO, HISTORICO RAZAO, 
       TO_CHAR(DTALANCTO, 'DD/MM/YYYY') DTA_CREDITO, VLRLANCAMENTO
  FROM FI_CTACORLANCA F

 WHERE 1=1 
   AND F.NROEMPRESA IN (#LS1)
   AND F.TIPOLANCTO IN ('D', 'C')
   AND F.OPCANCELADA IS NULL
   AND F.DTALANCTO BETWEEN :DT1 AND :DT2
   AND F.CODOPERACAO = 174
   AND HISTORICO LIKE '%ANCORA%'
   
 ORDER BY DTALANCTO, 1
