/*
QRP em https://github.com/GiulianoGMS/QRPs/blob/main/RelDossieImportacao.QRP
*/

SELECT XX1.*,
 /*Select de Subtototais*/
      (SELECT 'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO    = 182024 AND NROEMPRESA = 502 AND SITUACAO != 'C') TOT_TIT_GER,
 /******/
      (SELECT 'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = 62124  AND NROEMPRESA = 503 AND SITUACAO != 'C') TOT_DESP_GER,
 /******/
      (SELECT 'R$ '||TO_CHAR(SUM(ZZ.VALOR),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.GE_PESSOA GG ON GG.SEQPESSOA = ZZ.SEQPESSOA       
 WHERE UPPER(ZZ.OBSERVACAO) LIKE UPPER('%EMB18/2024%')) TOT_ORC_GER,
 /******/
 /*Diferenca*/
'R$ '||TO_CHAR(((SELECT SUM(VLRORIGINAL)
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO    = 182024 AND NROEMPRESA = 502 AND SITUACAO != 'C')  -
 /******/
      (SELECT SUM(VLRORIGINAL)
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA   
 WHERE X.NRODOCUMENTO = 62124  AND NROEMPRESA = 503 AND SITUACAO != 'C')  -
 /******/
      (SELECT SUM(ZZ.VALOR)
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.GE_PESSOA GG ON GG.SEQPESSOA = ZZ.SEQPESSOA       
 WHERE UPPER(ZZ.OBSERVACAO) LIKE UPPER('%EMB18/2024%'))),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') DIFERENCA
 
  FROM (
  
  /*Select do Grid*/
  
SELECT * FROM (
 SELECT 'TITULO' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, 62124 PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, 
       OBSERVACAO, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 1 S
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO = 182024 AND NROEMPRESA = 502 AND SITUACAO != 'C' AND X.OBRIGDIREITO = 'D' ORDER BY 9)
 
  UNION ALL
SELECT 'TITULO', NULL ,NULL, NULL, 'TOTAL DE TITULOS GERADOS', NULL, NULL, 
       'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), NULL, NULL, NULL, NULL, NULL, 1
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO = 182024 AND NROEMPRESA = 502 AND SITUACAO != 'C'

  UNION ALL
SELECT 'DESP_IMP' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, NRODOCUMENTO PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, SUBSTR(OBSERVACAO,15) OBS, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 2
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = 62124 AND NROEMPRESA = 503 AND SITUACAO != 'C'
 
  UNION ALL
SELECT 'DESP_IMP', NULL ,NULL, NULL, 'TOTAL DE DESPESAS GERADAS', NULL, NULL,
       'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), NULL, NULL, NULL, NULL, NULL, 2
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = 62124 AND NROEMPRESA = 503 AND SITUACAO != 'C'
 
 UNION ALL
SELECT 'ORCAMENTO' TIPO, CG.CODESPECIE CODESPECIE,
       CG.SEQTITULO,
       ZZ.NROEMPRESA, ZZ.SEQPESSOA||' - '||GG.NOMERAZAO FORNECEDOR, ZZ.NRONOTA, 62124 PROCESSO,
       'R$ '||TO_CHAR(ZZ.VALOR,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(ZZ.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO,
       TO_CHAR(ZZ.DTAVENCINICIAL, 'DD/MM/YYYY') DTAVENCIMENTO, ZZ.OBSERVACAO OBS,
       'OBR' OD,
       DECODE(ZZ.SITUACAO, 'I', 'QUITADO' , 'ABERTO') SITUACAO, 3
       
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.GE_PESSOA GG ON GG.SEQPESSOA = ZZ.SEQPESSOA
                                LEFT JOIN  FI_TITULO CG          ON CG.NROTITULO = ZZ.NRONOTA 
                                                                AND CG.NROEMPRESA = ZZ.NROEMPRESA 
                                                                AND CG.SEQPESSOA = ZZ.SEQPESSOA
                                                                AND CG.LINKERP = ZZ.LINKERP
 WHERE UPPER(ZZ.OBSERVACAO) LIKE UPPER('%EMB18/2024%')
 
  UNION ALL
SELECT 'ORCAMENTO', NULL ,NULL, NULL, 'TOTAL NFS DESP NACIONAIS', NULL, NULL,
       'R$ '||TO_CHAR(SUM(ZZ.VALOR),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, NULL, NULL, NULL, NULL, NULL, 3
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.GE_PESSOA GG ON GG.SEQPESSOA = ZZ.SEQPESSOA
                                
 WHERE UPPER(ZZ.OBSERVACAO) LIKE UPPER('%EMB18/2024%')
 
 UNION ALL
 SELECT 'NF' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, 62124 PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, NULL OBSERVACAO, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 4
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO = 1814 AND NROEMPRESA = 503 AND X.SITUACAO != 'C'
 
) XX1
