/*
QRP em https://github.com/GiulianoGMS/QRPs/blob/main/RelDossieImportacao.QRP
*/


SELECT XX1.*,
 /*Select de Subtototais*/
      (SELECT 'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
  FROM FI_TITULO X 
 WHERE X.NROTITULO    = #NR1 AND NROEMPRESA = 502 AND SITUACAO != 'C') TOT_TIT_GER,
 /******/
      (SELECT 'R$ '||TO_CHAR(SUM(VLRORIGINAL * DECODE(OBRIGDIREITO, 'D',-1,'O',1)),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
  FROM FI_TITULO X 
 WHERE X.NRODOCUMENTO = #NR2  AND NROEMPRESA = 503 AND SITUACAO != 'C') TOT_DESP_GER,
 /******/
      (SELECT 'R$ '||TO_CHAR(SUM(ZX.VALORLIQ),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.OR_NFVENCIMENTO ZX ON ZX.SEQNOTA = ZZ.SEQNOTA   
 WHERE UPPER(ZZ.OBSERVACAO) LIKE UPPER('%'||'#LT1'||'%')) TOT_ORC_GER,
 /******/
 /*Diferenca*/
'R$ '||TO_CHAR(((SELECT SUM(VLRORIGINAL)
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO    = #NR1 AND NROEMPRESA = 502 AND SITUACAO != 'C')  -
 /******/
      (SELECT SUM(VLRORIGINAL * DECODE(OBRIGDIREITO, 'D',-1,'O',1))
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA   
 WHERE X.NRODOCUMENTO = #NR2  AND NROEMPRESA = 503 AND SITUACAO != 'C')  -
 /******/
      (SELECT SUM(ZX.VALORLIQ)
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.OR_NFVENCIMENTO ZX ON ZX.SEQNOTA = ZZ.SEQNOTA       
 WHERE UPPER(ZZ.OBSERVACAO) LIKE UPPER('%'||'#LT1'||'%'))),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') DIFERENCA,
 
  (SELECT 'Referência: DI: '||NUMERODI||' - Data de Registro: '||TO_CHAR(DTAREGISTRO, 'DD/MM/YYYY') REF_DI
          FROM consinco.MAD_DI WHERE NUMERODI = (SELECT NUMERODI
                                                   FROM CONSINCO.MAD_PIPROCIMPORTACAO PD
                                                  WHERE PD.NROPROCIMPORTACAO = :NR2))  REF_DI,
  (SELECT NUMERODI
                                                   FROM CONSINCO.MAD_PIPROCIMPORTACAO PD
                                                  WHERE PD.NROPROCIMPORTACAO = :NR2)  NRO_DI   ,
  'Dossie - Conferência '||'#LT1' NRO_EMB   
 
  FROM (
  
  /*Select do Grid*/
  
SELECT * FROM (
 SELECT 'TITULO' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, #NR2 PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, 
       OBSERVACAO, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 1 S
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO = #NR1 AND NROEMPRESA = 502 AND SITUACAO != 'C' AND X.OBRIGDIREITO = 'D' ORDER BY 9)
 
  UNION ALL
SELECT 'TITULO', NULL ,NULL, NULL, 'TOTAL DE TITULOS GERADOS', NULL, NULL, 
       'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), NULL, NULL, NULL, NULL, NULL, 1
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO = #NR1 AND NROEMPRESA = 502 AND SITUACAO != 'C'

  UNION ALL

SELECT * FROM (
  
SELECT 'DESP_IMP' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, NRODOCUMENTO PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, SUBSTR(OBSERVACAO,15) OBS, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 2
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = #NR2 AND NROEMPRESA = 503 AND SITUACAO != 'C'

ORDER BY 11
 
)

  UNION ALL
SELECT 'DESP_IMP', NULL ,NULL, NULL, 'TOTAL DE DESPESAS GERADAS', NULL, NULL,
       'R$ '||TO_CHAR(SUM(VLRORIGINAL * DECODE(OBRIGDIREITO, 'D',-1,'O',1)),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), NULL, NULL, NULL, NULL, NULL, 2
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = #NR2 AND NROEMPRESA = 503 AND SITUACAO != 'C'
 
 UNION ALL
SELECT 'ORCAMENTO' TIPO, CG.CODESPECIE CODESPECIE,
       CG.SEQTITULO,
       ZZ.NROEMPRESA, ZZ.SEQPESSOA||' - '||GG.NOMERAZAO FORNECEDOR, ZZ.NRONOTA, #NR2 PROCESSO,
       'R$ '||TO_CHAR(ZX.VALORLIQ,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(ZZ.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO,
       TO_CHAR(ZZ.DTAVENCINICIAL, 'DD/MM/YYYY') DTAVENCIMENTO, ZZ.OBSERVACAO OBS,
       'OBR' OD,
       DECODE(CG.SITUACAO, 'A', 'QUITADO' , 'ABERTO') SITUACAO, 3
       
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.GE_PESSOA GG ON GG.SEQPESSOA = ZZ.SEQPESSOA
                                INNER JOIN CONSINCO.OR_NFVENCIMENTO ZX ON ZX.SEQNOTA = ZZ.SEQNOTA
                                LEFT JOIN  FI_TITULO CG          ON CG.NROTITULO = ZZ.NRONOTA 
                                                                AND CG.NROEMPRESA = ZZ.NROEMPRESA 
                                                                AND CG.SEQPESSOA = ZZ.SEQPESSOA
                                                                AND CG.LINKERP = ZZ.LINKERP
 WHERE UPPER(ZZ.OBSERVACAO) LIKE UPPER('%'||'#LT1'||'%')
 
  UNION ALL
SELECT 'ORCAMENTO', NULL ,NULL, NULL, 'TOTAL NFS DESP NACIONAIS', NULL, NULL,
       'R$ '||TO_CHAR(SUM(ZX.VALORLIQ),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, NULL, NULL, NULL, NULL, NULL, 3
  FROM CONSINCO.OR_NFDESPESA ZZ INNER JOIN CONSINCO.GE_PESSOA GG ON GG.SEQPESSOA = ZZ.SEQPESSOA
                                INNER JOIN CONSINCO.OR_NFVENCIMENTO ZX ON ZX.SEQNOTA = ZZ.SEQNOTA
                                
 WHERE UPPER(ZZ.OBSERVACAO) LIKE UPPER('%'||'#LT1'||'%')
 
 UNION ALL
 SELECT 'NF' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, #NR2 PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, NULL OBSERVACAO, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 4
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
  
 WHERE X.NROTITULO IN (SELECT C.NUMERONF FROM MLF_NOTAFISCAL C
         WHERE EXISTS (SELECT 1 
                         FROM MAD_ADICAO B INNER JOIN MAD_DI A ON A.NUMERODI = B.NUMERODI
                        WHERE B.SEQAUXNOTAFISCAL = C.SEQAUXNOTAFISCAL
                          AND A.NROPROCIMPORTACAO = :NR2))
           
   AND NROEMPRESA = 503 AND X.SITUACAO NOT IN ('C','X')
 
) XX1
