-- QRP em https://github.com/GiulianoGMS/QRPs/blob/main/RelDossieImportacao.QRP

SELECT * FROM (
 SELECT 'TITULO' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, 52524 PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, 
       OBSERVACAO, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 1 S
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO = 32023 AND NROEMPRESA = 502 AND SITUACAO != 'C' ORDER BY 9)
 
  UNION ALL
SELECT 'TITULO', NULL ,NULL, NULL, 'TOTAL TITULOS', NULL, NULL, 
       'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), NULL, NULL, NULL, NULL, NULL, 1
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO = 32023 AND NROEMPRESA = 502 AND SITUACAO != 'C'

  UNION ALL
SELECT 'DESP_IMP' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, NRODOCUMENTO PROCESSO,
       'R$ '||TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, SUBSTR(OBSERVACAO,15) OBS, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 2
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = 52524 AND NROEMPRESA = 503 AND SITUACAO != 'C'
 
  UNION ALL
SELECT 'DESP_IMP', NULL ,NULL, NULL, 'TOTAL DESPESAS GERADAS', NULL, NULL,
       'R$ '||TO_CHAR(SUM(VLRORIGINAL),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), NULL, NULL, NULL, NULL, NULL, 2
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NRODOCUMENTO = 52524 AND NROEMPRESA = 503 AND SITUACAO != 'C'
 
 UNION ALL
 SELECT 'NF' TIPO, CODESPECIE, SEQTITULO, NROEMPRESA EMP, X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, NROTITULO, 52524 PROCESSO,
       TO_CHAR(VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTAVENCIMENTO, NULL OBSERVACAO, 
       DECODE(OBRIGDIREITO, 'O', 'OBR', 'D', 'DIR') OD, 
       DECODE(X.ABERTOQUITADO, 'A', 'ABERTO', 'Q', 'QUITADO') SITUACAO, 3
  FROM FI_TITULO X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
 WHERE X.NROTITULO = 456 AND NROEMPRESA = 503
