SELECT LINHA, EMISSAO_ACO, NRO_ACORDO, DESCRICAO DESC_ACO, PARCELA, DTAVENCIMENTO VENCTO_PARCELA, DTAQUITACAO, INFO_QUIT, COMPRADOR, COD_FORNECEDOR, VLR_ACORDO, VLR_PARCELA, VLR_ABERTO, VLR_OPERACAO, REDE

  FROM (

SELECT SEQTITULO, 'TIT' LINHA, X.DATA_EMISSAO EMISSAO_ACO, X.NRO_ACORDO, X.DESCACORDO DESCRICAO, NROPARCELA||'/'||QTDPARCELA PARCELA, F.DTAVENCIMENTO, NULL DTAQUITACAO, NULL INFO_QUIT, X.COMPRADOR, X.COD_FORNECEDOR,
       X.VLR_ACORDO, F.VLRORIGINAL VLR_PARCELA, F.VLRORIGINAL - F.VLRPAGO VLR_ABERTO, NULL VLR_OPERACAO, R.DESCRICAO REDE
  FROM FI_TITULO F INNER JOIN NAGV_TAE_ACORDOS_V4 X     ON X.NRO_ACORDO = F.NROTITULO AND F.NROEMPRESA = NVL(X.NROEMPRACORDOPROMOC,X.NRO_EMPRESA) AND F.SITUACAO != 'C' AND F.SEQPESSOA = X.COD_FORNECEDOR
                   INNER JOIN CONSINCO.GE_REDEPESSOA RP ON RP.SEQPESSOA = X.COD_FORNECEDOR
                   INNER JOIN CONSINCO.GE_REDE R        ON R.SEQREDE    = RP.SEQREDE
  
 WHERE  (F.NROTITULO = 748745)
   AND F.CODESPECIE LIKE 'AC%'

UNION ALL

SELECT F.SEQTITULO, 'OPE', X.DATA_EMISSAO, X.NRO_ACORDO, X.DESCACORDO DESCRICAO, NROPARCELA||'/'||QTDPARCELA PARCELA, F.DTAVENCIMENTO, 
       NVL((SELECT MAX(F1.DTAEMISSAO) FROM FI_TITULO F1 WHERE F1.SEQTITULO = (SELECT MAX(SEQTITULO) FROM FI_TITOPERACAO O2 WHERE O2.NROPROCESSO = O.NROPROCESSO) AND CODESPECIE IN ('ANTREC')), O.DTAOPERACAO) DTAQUITACAO,
       O.OBSERVACAO, X.COMPRADOR, F.SEQPESSOA, NULL VLR_ACORDO, NULL VLR_PARCELA, NULL VLR_ABERTO, O.VLROPERACAO, R.DESCRICAO REDE
  FROM FI_TITULO F INNER JOIN NAGV_TAE_ACORDOS_V4 X     ON X.NRO_ACORDO = F.NROTITULO AND F.NROEMPRESA = NVL(X.NROEMPRACORDOPROMOC,X.NRO_EMPRESA) AND F.SITUACAO != 'C' AND F.SEQPESSOA = X.COD_FORNECEDOR
                   INNER JOIN CONSINCO.GE_REDEPESSOA RP ON RP.SEQPESSOA = X.COD_FORNECEDOR
                   INNER JOIN CONSINCO.GE_REDE R        ON R.SEQREDE    = RP.SEQREDE
                   INNER JOIN FI_TITOPERACAO O          ON O.SEQTITULO = F.SEQTITULO
  
 WHERE (F.NROTITULO = 748745)
   AND O.OPCANCELADA IS NULL
   AND CODOPERACAO = 28
   AND F.CODESPECIE LIKE 'AC%'
   
   ORDER BY 1, 2 DESC
   ); 
   
  
