SELECT X.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, F.SEQCONTRATO CONTRATO,
    SUM(FVALORTOTALNF(X.ROWID, 'N')) VLR_TOTAL_NFS_BRUTO,
    SUM(FVALORTOTALNF(X.ROWID, 'N')) - SUM(NVL(CF.PERCDESCONTO * F.VLTTOTALITEM / 100,0)) - SUM(NVL(CL.PERCDESCONTO * F.VLTTOTALITEM / 100,0)) VLR_TOTAL_NFS_LIQ,

    MAX(CASE WHEN CF.SEQCONTRATODESCONTO IS NOT NULL 
             THEN CF.PERCDESCONTO END) PERC_FID,

    SUM(CASE WHEN CF.SEQCONTRATODESCONTO IS NOT NULL 
             THEN (CF.PERCDESCONTO * F.VLTTOTALITEM / 100) 
        END) VLR_FIDELIDADE,

    MAX(CASE WHEN CL.SEQCONTRATODESCONTO IS NOT NULL 
             THEN CL.PERCDESCONTO END) PERC_LOG,

    SUM(CASE WHEN CL.SEQCONTRATODESCONTO IS NOT NULL 
             THEN (CL.PERCDESCONTO * F.VLTTOTALITEM / 100)
        END) VLR_LOGISTICO,
        
    CATEGORIAN1 CATEGORIA, CATEGORIAN2 SUBCATEGORIA
        
   FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI           ON X.SEQNF = XI.SEQNF
                         INNER JOIN MLF_DESCFINACONTRATO F  ON F.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL        AND F.SEQITEMNF = XI.SEQITEMNF AND F.LINKERP = X.LINKERP AND F.PERCENTUAL > 0
                          LEFT JOIN MGC_CONTRATODESCONTO CF ON CF.SEQCONTRATODESCONTO = F.SEQCONTRATODESCONTO AND CF.DESCRICAO LIKE 'FID%'
                          LEFT JOIN MGC_CONTRATODESCONTO CL ON CL.SEQCONTRATODESCONTO = F.SEQCONTRATODESCONTO AND CL.DESCRICAO LIKE '%LOG%'
                         INNER JOIN GE_PESSOA G             ON G.SEQPESSOA = X.SEQPESSOA
                         INNER JOIN MAP_PRODUTO P           ON P.SEQPRODUTO = XI.SEQPRODUTO
                         INNER JOIN DIM_CATEGORIA@CONSINCODW D ON D.SEQFAMILIA = P.SEQFAMILIA
                        
  WHERE 1=1
    AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2
    AND X.SEQPESSOA IN (SELECT SEQPESSOA FROM GE_REDEPESSOA RP WHERE RP.SEQREDE = (SELECT SEQREDE FROM GE_REDE R WHERE R.DESCRICAO = #LS1))    
    
  GROUP BY X.NROEMPRESA, X.SEQPESSOA||' - '||G.NOMERAZAO, CATEGORIAN1, CATEGORIAN2, F.SEQCONTRATO
