SELECT F.NROEMPRESA, F.SEQPESSOA||' - '||NOMERAZAO FORNEC, F.NROTITULO, 
       SUBSTR(A.OBSERVACAO, INSTR(A.OBSERVACAO, 'De') + 3, 10) DE,
       SUBSTR(A.OBSERVACAO, INSTR(A.OBSERVACAO, 'para') + 6, 10) PARA,
       A.USUALTERACAO, 
       TO_CHAR(A.DTAALTERACAO, 'DD/MM/YYYY') DTAALTERACAO, F.NROPARCELA, 
       TO_CHAR(F.VLRORIGINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR
  FROM CONSINCO.FI_MOVOCOR A INNER JOIN FI_TITULO F    ON F.SEQTITULO = A.SEQIDENTIFICA 
                             INNER JOIN FI_OCRFINANC O ON O.CODOCORRENCIA = A.CODOCORRENCIA
                             INNER JOIN GE_PESSOA G    ON G.SEQPESSOA = F.SEQPESSOA
                                    
 WHERE 1=1
 
   AND F.DTAALTERACAO BETWEEN :DT1 AND :DT2
   AND A.CODOCORRENCIA = 5
   AND F.OBRIGDIREITO  = 'O'
   AND A.OBSERVACAO LIKE '%para  %'
   AND A.USUALTERACAO IN (SELECT CODUSUARIO
                            FROM GE_USUARIO
                           WHERE TIPOUSUARIO = 'U'
                             AND SEQUSUARIO IN (SELECT USUARIO FROM GE_MEMBRO WHERE GRUPO = '576'))
 
ORDER BY 2,1, DTAALTERACAO;

 
 
