/*
Cálculo realizado:

- Sistema calcula o TOTAL de LUCRATIVIDADE (VENDA - CUSTO)
- Em seguida, calcula 80% deste valor
- Obtem a quantidade de itens equivalente aos 80%
- Obtem 20% do total de itens sendo estes os maiores valores/lucros.

*/

ALTER SESSION SET current_schema = CONSINCO;

SELECT * FROM (

SELECT ROW_NUMBER() OVER(ORDER BY TOTAL DESC) AS SEQ, SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE, 
       CATEGORIA, TOTAL, TO_CHAR(ACUMULADO,'FM999G999D90') ACUMULADO 

FROM (

SELECT SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL,
      (SUM(SUM(TOTAL)) OVER (ORDER BY TOTAL DESC
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) ACUMULADO

FROM (
    
SELECT A.SEQPRODUTO, DESCCOMPLETA, 
      SUM(QTDOPERACAO) QTD_VENDA,
      TO_CHAR((SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)),'FM999G999D90') LUCRATIVIDADE,
      G.CATEGORIA,
      (SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)) AS TOTAL

FROM  FATOG_VENDADIA A JOIN (SELECT SEQPRODUTO, DESCCOMPLETA, SEQFAMILIA FROM MAP_PRODUTO) B ON A.SEQPRODUTO = B.SEQPRODUTO,
      MAP_CATEGORIA  G JOIN MAP_FAMDIVCATEG H ON G.SEQCATEGORIA = H.SEQCATEGORIA
WHERE DTAOPERACAO = DATE '2022-02-27'
      AND A.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
      AND B.SEQFAMILIA = H.SEQFAMILIA
      AND H.SEQCATEGORIA = G.SEQCATEGORIA
      AND G.TIPCATEGORIA = 'C'
      AND G.NIVELHIERARQUIA = 1
      AND STATUSCATEGOR = 'A'
      AND H.STATUS = 'A'
      AND G.CATEGORIA  = 'LIMPEZA'
GROUP BY A.SEQPRODUTO, DESCCOMPLETA, CATEGORIA,(REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 1))
ORDER BY (SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)) DESC 

)

GROUP BY SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL
     ORDER BY TOTAL DESC
     
   )
   WHERE ACUMULADO < 
   
   (SELECT  SUM(80*SUM(TOTAL))/100

FROM (

SELECT SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL,
      (SUM(SUM(TOTAL)) OVER (ORDER BY TOTAL DESC
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) ACUMULADO

FROM (
    
SELECT A.SEQPRODUTO, DESCCOMPLETA, 
      SUM(QTDOPERACAO) QTD_VENDA,
      TO_CHAR((SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)),'FM999G999D90') LUCRATIVIDADE,
      G.CATEGORIA,
      (SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)) AS TOTAL

FROM  FATOG_VENDADIA A JOIN (SELECT SEQPRODUTO, DESCCOMPLETA, SEQFAMILIA FROM MAP_PRODUTO) B ON A.SEQPRODUTO = B.SEQPRODUTO,
      MAP_CATEGORIA  G JOIN MAP_FAMDIVCATEG H ON G.SEQCATEGORIA = H.SEQCATEGORIA
WHERE DTAOPERACAO = DATE '2022-02-27'
      AND A.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
      AND B.SEQFAMILIA = H.SEQFAMILIA
      AND H.SEQCATEGORIA = G.SEQCATEGORIA
      AND G.TIPCATEGORIA = 'C'
      AND G.NIVELHIERARQUIA = 1
      AND STATUSCATEGOR = 'A'
      AND H.STATUS = 'A'
      AND G.CATEGORIA  = 'LIMPEZA'
GROUP BY A.SEQPRODUTO, DESCCOMPLETA, CATEGORIA,(REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 1))
ORDER BY (SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)) DESC 

)

GROUP BY SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL
ORDER BY TOTAL DESC
     
   ) 
GROUP BY SEQPRODUTO
)

GROUP BY SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL, ACUMULADO
ORDER BY TOTAL  DESC

) WHERE SEQ < 

((SELECT (20*(COUNT(SEQPRODUTO))/100) FROM 

(

SELECT ROW_NUMBER() OVER(ORDER BY TOTAL DESC) AS SEQ, SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE, 
       CATEGORIA, TOTAL, TO_CHAR(ACUMULADO,'FM999G999D90') ACUMULADO

FROM (

SELECT SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL,
      (SUM(SUM(TOTAL)) OVER (ORDER BY TOTAL DESC
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) ACUMULADO

FROM (
    
SELECT A.SEQPRODUTO, DESCCOMPLETA, 
      SUM(QTDOPERACAO) QTD_VENDA,
      TO_CHAR((SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)),'FM999G999D90') LUCRATIVIDADE,
     G.CATEGORIA,
      (SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)) AS TOTAL

FROM  FATOG_VENDADIA A JOIN (SELECT SEQPRODUTO, DESCCOMPLETA, SEQFAMILIA FROM MAP_PRODUTO) B ON A.SEQPRODUTO = B.SEQPRODUTO,
      MAP_CATEGORIA  G JOIN MAP_FAMDIVCATEG H ON G.SEQCATEGORIA = H.SEQCATEGORIA
WHERE DTAOPERACAO = DATE '2022-02-27'
      AND A.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
      AND B.SEQFAMILIA = H.SEQFAMILIA
      AND H.SEQCATEGORIA = G.SEQCATEGORIA
      AND G.TIPCATEGORIA = 'C'
      AND G.NIVELHIERARQUIA = 1
      AND STATUSCATEGOR = 'A'
      AND H.STATUS = 'A'
      AND CAMINHOCOMPLETO  LIKE '%LIMPEZA%'
GROUP BY A.SEQPRODUTO, DESCCOMPLETA, CATEGORIA,(REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 1))
ORDER BY (SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)) DESC 

)

GROUP BY SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL
     ORDER BY TOTAL DESC
     
   )
   WHERE ACUMULADO < 
   
   (SELECT  SUM(80*SUM(TOTAL))/100

FROM (

SELECT SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL,
      (SUM(SUM(TOTAL)) OVER (ORDER BY TOTAL DESC
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) ACUMULADO

FROM (
    
SELECT A.SEQPRODUTO, DESCCOMPLETA, 
      SUM(QTDOPERACAO) QTD_VENDA,
      TO_CHAR((SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)),'FM999G999D90') LUCRATIVIDADE,
      (REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 1)) CATEGORIA,
      (SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)) AS TOTAL

FROM  FATOG_VENDADIA A JOIN (SELECT SEQPRODUTO, DESCCOMPLETA, SEQFAMILIA FROM MAP_PRODUTO) B ON A.SEQPRODUTO = B.SEQPRODUTO,
      MAP_CATEGORIA  G JOIN MAP_FAMDIVCATEG H ON G.SEQCATEGORIA = H.SEQCATEGORIA
WHERE DTAOPERACAO = DATE '2022-02-27'
      AND A.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
      AND B.SEQFAMILIA = H.SEQFAMILIA
      AND H.SEQCATEGORIA = G.SEQCATEGORIA
      AND G.TIPCATEGORIA = 'C'
      AND G.NIVELHIERARQUIA = 1
      AND STATUSCATEGOR = 'A'
      AND H.STATUS = 'A'
      AND CAMINHOCOMPLETO  LIKE '%LIMPEZA%'
GROUP BY A.SEQPRODUTO, DESCCOMPLETA, CATEGORIA,(REGEXP_SUBSTR (CAMINHOCOMPLETO,'[^\]+', 1, 1))
ORDER BY (SUM(VLROPERACAO) - SUM(VVLRIMPOSTOSAIDA)) - (SUM(VVLRCTOLIQUIDO)) DESC 

)

GROUP BY SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL
ORDER BY TOTAL DESC
     
   ) 
GROUP BY SEQPRODUTO
)
      
GROUP BY SEQPRODUTO, DESCCOMPLETA, LUCRATIVIDADE,CATEGORIA, TOTAL, ACUMULADO
ORDER BY TOTAL  DESC

)))
