ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.NROEMPRESA LOJA, X.SEQPRODUTO, P.DESCCOMPLETA, X.PRECOVALIDNORMAL PRECO_LOJA,
      (SELECT PRECOVALIDNORMAL FROM MRL_PRODEMPSEG E WHERE E.NROEMPRESA = X.NROEMPRESA AND E.NROSEGMENTO IN (5,8) AND E.SEQPRODUTO = X.SEQPRODUTO AND E.QTDEMBALAGEM = X.QTDEMBALAGEM
          AND EXISTS (SELECT 1 FROM MAX_EMPRESASEG SG WHERE NROSEGMENTO IN (5,8) AND NROSEGMENTO = E.NROSEGMENTO AND STATUS = 'A' AND SG.NROEMPRESA = E.NROEMPRESA)) PRECO_ECOMM
  FROM MRL_PRODEMPSEG X INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = X.NROEMPRESA AND X.NROSEGMENTO = M.NROSEGMENTOPRINC
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO
 WHERE X.STATUSVENDA = 'A'
   AND X.PRECOBASENORMAL > 0
   AND EXISTS (SELECT 1 FROM MRL_PRODEMPSEG A 
                WHERE A.NROSEGMENTO IN (5,8) 
                  AND A.NROSEGMENTO != X.NROSEGMENTO
                  AND A.SEQPRODUTO = X.SEQPRODUTO
                  AND A.NROEMPRESA = X.NROEMPRESA
                  AND A.QTDEMBALAGEM = X.QTDEMBALAGEM
                  AND A.PRECOVALIDNORMAL != X.PRECOVALIDNORMAL) 
   AND EXISTS (SELECT 1 FROM MAX_EMPRESASEG SG WHERE NROSEGMENTO IN (5,8) AND STATUS = 'A' AND SG.NROEMPRESA = X.NROEMPRESA)
   AND NVL(P.INDINTEGRAECOMMERCE, 'N') = 'S'
   AND X.QTDEMBALAGEM = 1
   AND X.NROEMPRESA IN (#LS1)
   
   ORDER BY 1,2;
   
