SELECT 0 AS COD, CASE
         WHEN PED.STATUSPEDIDO = 'U' 
           THEN 'PEDIDO EM USO'
         WHEN PED.STATUSPEDIDO = 'F' 
           THEN 'PEDIDO FINALIZADO'
         WHEN PED.STATUSPEDIDO = 'N' 
           THEN 'PEDIDO NOTA FISCAL'
         WHEN PED.STATUSPEDIDO = 'X' 
           THEN 'PEDIDO CANCELADO'
         WHEN PED.STATUSPEDIDO = 'C' 
           THEN 'PEDIDO CONFERIDO AGUARDANDO CLIENTE'
         ELSE 'PEDIDO LIVRE' END AS STATUS_PEDIDO,
         PED.NROPEDCLIENTE AS PEDIDO_ECOMMERCE,
         TO_CHAR(CASE 
           WHEN PAG.NROFORMAPAGTO = 65 OR PAG.NROFORMAPAGTO = 81 
             THEN PAG.VALOR
         ELSE (SELECT ROUND(SUM(ROUND(ITE.QTDPEDIDA * ITE.VLREMBTABPRECO,2)) + 
                      PED.VLRTOTFRETE + PED.VLRDESPACESSORIA,2)
               FROM CONSINCO.ECOMM_PDV_ITEM ITE
               WHERE PED.SEQEDIPEDVENDA = ITE.SEQEDIPEDVENDA)
               END, 'FM999G999G999D90','nls_numeric_characters='',.''') AS VALOR_COMPRA,
         CASE
           WHEN PAG.NROFORMAPAGTO = 65 
             OR PAG.NROFORMAPAGTO = 81 
             THEN 'PAGAMENTO DESCONTO'
             ELSE 'PAGAMENTO CLIENTE'
             END AS DESCRICAO_PAGAMENTO,
         CASE
         WHEN PAG.NROFORMAPAGTO = 77 THEN 'PAGAMENTO EM LOJA'
         WHEN PAG.NROFORMAPAGTO = 79 THEN 'ELO DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 7 THEN 'VALE ALIMENTACAO'
         WHEN PAG.NROFORMAPAGTO = 51 THEN 'MASTERCARD CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 50 THEN 'VISA CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 53 THEN 'AMERICAN EXPRESS CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 6 THEN 'AURA CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 52 THEN 'DINNERS CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 56 THEN 'ELO CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 55 THEN 'HIPERCARD CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 78 THEN 'MASTERCARD DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 58 THEN 'VISA DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 77 THEN 'PAGAMENTO EM LOJA'
         WHEN PAG.NROFORMAPAGTO = 57 THEN 'INFOCARDS'
         WHEN PAG.NROFORMAPAGTO = 35 THEN 'PIX ONLINE'
         WHEN PAG.NROFORMAPAGTO = 524 THEN 'PAGAMENTO IFOOD RETIRA ONLINE'
         WHEN PAG.NROFORMAPAGTO = 523 THEN 'PAGAMENTO IFOOD ENTREGA ONLINE'
         WHEN PAG.NROFORMAPAGTO = 81 THEN 'VOUCHER MARKETING NAGUMO'
         WHEN PAG.NROFORMAPAGTO = 65 THEN 'VOUCHER SITE MERCADO'
         ELSE 'VERIFICAR PAGAMENTO'
       END AS FORMA_PAGAMENTO,
       TO_CHAR(PED.DTAINCLUSAO, 'DD/MM/YYYY') DTAINCLUSAO         
FROM CONSINCO.ECOMM_PDV_VENDA PED INNER JOIN CONSINCO.ECOMM_PDV_PAGTO PAG 
     ON PED.SEQEDIPEDVENDA = PAG.SEQEDIPEDVENDA
WHERE TRUNC(PED.DTAINCLUSAO) BETWEEN :DT1 AND :DT2
/*WHERE TRUNC (PED.DTAINCLUSAO) BETWEEN '15/AUG/2022' AND '15/AUG/2022'*/
      AND PED.NROEMPRESA = 42

UNION ALL

SELECT 1 AS COD ,NULL, 'SUBTOTAL', 

       TO_CHAR(SUM(CASE 
         WHEN PAG.NROFORMAPAGTO = 65 OR PAG.NROFORMAPAGTO = 81 
           THEN PAG.VALOR
         ELSE (SELECT ROUND(SUM(ROUND(ITE.QTDPEDIDA * ITE.VLREMBTABPRECO,2)) + 
           PED.VLRTOTFRETE + PED.VLRDESPACESSORIA,2)
               FROM CONSINCO.ECOMM_PDV_ITEM ITE
               WHERE PED.SEQEDIPEDVENDA = ITE.SEQEDIPEDVENDA)
               END), 'FM999G999G999D90','nls_numeric_characters='',.''') AS VALOR_COMPRA,               
               NULL,
      CASE
         WHEN PAG.NROFORMAPAGTO = 77 THEN 'PAGAMENTO EM LOJA'
         WHEN PAG.NROFORMAPAGTO = 79 THEN 'ELO DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 7 THEN 'VALE ALIMENTACAO'
         WHEN PAG.NROFORMAPAGTO = 51 THEN 'MASTERCARD CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 50 THEN 'VISA CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 53 THEN 'AMERICAN EXPRESS CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 6 THEN 'AURA CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 52 THEN 'DINNERS CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 56 THEN 'ELO CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 55 THEN 'HIPERCARD CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 78 THEN 'MASTERCARD DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 58 THEN 'VISA DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 77 THEN 'PAGAMENTO EM LOJA'
         WHEN PAG.NROFORMAPAGTO = 57 THEN 'INFOCARDS'
         WHEN PAG.NROFORMAPAGTO = 35 THEN 'PIX ONLINE'
         WHEN PAG.NROFORMAPAGTO = 524 THEN 'PAGAMENTO IFOOD RETIRA ONLINE'
         WHEN PAG.NROFORMAPAGTO = 523 THEN 'PAGAMENTO IFOOD ENTREGA ONLINE'
         WHEN PAG.NROFORMAPAGTO = 81 THEN 'VOUCHER MARKETING NAGUMO'
         WHEN PAG.NROFORMAPAGTO = 65 THEN 'VOUCHER SITE MERCADO'
         ELSE 'VERIFICAR PAGAMENTO'
       END AS FORMA_PAGAMENTO,
         NULL 

FROM CONSINCO.ECOMM_PDV_VENDA PED
INNER JOIN CONSINCO.ECOMM_PDV_PAGTO PAG ON PED.SEQEDIPEDVENDA = PAG.SEQEDIPEDVENDA
WHERE TRUNC(PED.DTAINCLUSAO) BETWEEN :DT1 AND :DT2
/*WHERE TRUNC (PED.DTAINCLUSAO) BETWEEN '15/AUG/2022' AND '15/AUG/2022'*/
AND PED.NROEMPRESA = 42

GROUP BY 
         CASE
         WHEN PAG.NROFORMAPAGTO = 77 THEN 'PAGAMENTO EM LOJA'
         WHEN PAG.NROFORMAPAGTO = 79 THEN 'ELO DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 7 THEN 'VALE ALIMENTACAO'
         WHEN PAG.NROFORMAPAGTO = 51 THEN 'MASTERCARD CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 50 THEN 'VISA CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 53 THEN 'AMERICAN EXPRESS CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 6 THEN 'AURA CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 52 THEN 'DINNERS CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 56 THEN 'ELO CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 55 THEN 'HIPERCARD CREDITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 78 THEN 'MASTERCARD DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 58 THEN 'VISA DEBITO ONLINE'
         WHEN PAG.NROFORMAPAGTO = 77 THEN 'PAGAMENTO EM LOJA'
         WHEN PAG.NROFORMAPAGTO = 57 THEN 'INFOCARDS'
         WHEN PAG.NROFORMAPAGTO = 35 THEN 'PIX ONLINE'
         WHEN PAG.NROFORMAPAGTO = 524 THEN 'PAGAMENTO IFOOD RETIRA ONLINE'
         WHEN PAG.NROFORMAPAGTO = 523 THEN 'PAGAMENTO IFOOD ENTREGA ONLINE'
         WHEN PAG.NROFORMAPAGTO = 81 THEN 'VOUCHER MARKETING NAGUMO'
         WHEN PAG.NROFORMAPAGTO = 65 THEN 'VOUCHER SITE MERCADO'
         ELSE 'VERIFICAR PAGAMENTO'       
           END 
  
UNION ALL

SELECT 2 AS COD , NULL, 'TOTAL GERAL',
       TO_CHAR(SUM(CASE 
         WHEN PAG.NROFORMAPAGTO = 65 OR PAG.NROFORMAPAGTO = 81 
           THEN PAG.VALOR
         ELSE (SELECT ROUND(SUM(ROUND(ITE.QTDPEDIDA * ITE.VLREMBTABPRECO,2)) + 
           PED.VLRTOTFRETE + PED.VLRDESPACESSORIA,2)
               FROM CONSINCO.ECOMM_PDV_ITEM ITE
               WHERE PED.SEQEDIPEDVENDA = ITE.SEQEDIPEDVENDA)
               END),'FM999G999G999D90','nls_numeric_characters='',.''') AS VALOR_COMPRA,               
               NULL,NULL, NULL
FROM CONSINCO.ECOMM_PDV_VENDA PED
INNER JOIN CONSINCO.ECOMM_PDV_PAGTO PAG ON PED.SEQEDIPEDVENDA = PAG.SEQEDIPEDVENDA
WHERE TRUNC(PED.DTAINCLUSAO) BETWEEN :DT1 AND :DT2
/*WHERE TRUNC (PED.DTAINCLUSAO) BETWEEN '15/AUG/2022' AND '15/AUG/2022'*/
AND PED.NROEMPRESA = 42

ORDER BY 1,5,6
