SELECT S.NROEMPRESA LOJA, S.SEQPRODUTO PLU, P.DESCCOMPLETA, CATEGORIAN1 CATEGORIA, CATEGORIAN2 SUBCATEGORIA,
       LISTAGG(C.CODACESSO, ', ') WITHIN GROUP (ORDER BY C.SEQPRODUTO) EAN, 
       S.PRECOVALIDNORMAL PRECO_NORMAL, NULLIF(S.PRECOVALIDPROMOC,0) PRECO_PROMOC, MN.PRECOPROMOCAO PRECO_MEU_NAGUMO
       
   FROM MRL_PRODEMPSEG S INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = S.SEQPRODUTO
                         INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = S.NROEMPRESA AND M.NROSEGMENTOPRINC = S.NROSEGMENTO
                          LEFT JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = S.SEQPRODUTO AND C.TIPCODIGO = 'E' AND C.INDUTILVENDA = 'S' AND C.QTDEMBALAGEM = S.QTDEMBALAGEM
                          LEFT JOIN NAGV_BASE_PROMOC_PDV_MN MN ON MN.SEQPRODUTO = S.SEQPRODUTO AND MN.NROEMPRESA = S.NROEMPRESA AND MN.QTDEMBALAGEM = S.QTDEMBALAGEM
                         INNER JOIN DIM_CATEGORIA@CONSINCODW D ON D.SEQFAMILIA = P.SEQFAMILIA
                          
WHERE S.NROEMPRESA IN (#LS1)
  AND STATUSVENDA = 'A'
  AND S.QTDEMBALAGEM = 1
  
GROUP BY S.NROEMPRESA, S.SEQPRODUTO, DESCCOMPLETA, PRECOVALIDNORMAL, PRECOVALIDPROMOC, PRECOPROMOCAO, CATEGORIAN1, CATEGORIAN2
