SELECT E.NROEMPRESA LOJA, TO_CHAR(E.DTAESTOQUE, 'DD/MM/YYYY') DATA, X.SEQPRODUTO PLU, C.CODACESSO EAN, DESCCOMPLETA, E.QTDESTQLOJA, 
       CONSINCO.NAGF_PRECO_DIA_X(E.NROEMPRESA, 
       X.SEQPRODUTO,
       M.NROSEGMENTOPRINC,
       1,
       E.DTAESTOQUE) PRECO_SEGMENTO_PRINC,
       CONSINCO.NAGF_PRECO_DIA_X(E.NROEMPRESA, 
       X.SEQPRODUTO,
       DECODE(M.NROSEGMENTOPRINC,2,5,4,8),
       1,
       E.DTAESTOQUE) PRECO_ECOMMERCE
       
  FROM MAP_PRODUTO X LEFT JOIN  FATO_ESTOQUE E       ON E.SEQPRODUTO = X.SEQPRODUTO
                     LEFT JOIN  MAP_PRODCODIGO C     ON C.SEQPRODUTO = X.SEQPRODUTO AND C.TIPCODIGO = 'E'
                     INNER JOIN MAX_EMPRESA M        ON M.NROEMPRESA = E.NROEMPRESA
                     
 WHERE DESCCOMPLETA LIKE '%'||UPPER('#LT1')||'%'
   AND E.NROEMPRESA = :LS1
   AND E.DTAESTOQUE = :DT1
   
 ORDER BY 5
 
