-- Depara na tabela NAGT_DEPARATKT338869

SELECT A.SEQPRODUTO PLU, DESCCOMPLETA DESC_PRODUTO, NVL(SUM(NVL(X.QTDOPERACAO,0)),0) QTD_VENDIDA, NVL(SUM(NVL(X.VLROPERACAO,0)),0) VLR_VENDA
  FROM NAGT_DEPARATKT338869 A LEFT JOIN FATOG_VENDADIA@CONSINCODW X ON A.SEQPRODUTO = X.SEQPRODUTO
                                                                   AND DTAOPERACAO BETWEEN DATE '2023-10-01' AND DATE '2023-12-31'
                                                                   AND CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
                                                                   
                              INNER JOIN CONSINCO.MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO
 
 GROUP BY A.SEQPRODUTO, DESCCOMPLETA
 ORDER BY A.SEQPRODUTO
