ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ DTA, NROEMPRESA, X.SEQPRODUTO, DESCCOMPLETA,
       (SELECT NVL(PRECO,0) PRECO FROM  
       (SELECT CONSINCO.FMAD_PRECOPROGDATA(A.SEQPRODUTO, A.QTDEMBALAGEM, A.NROSEGMENTO, A.NROEMPRESA, A.DTAPROGALTERACAO) PRECO
          FROM CONSINCO.MAD_PRODLOGPRECO A 
               WHERE A.SEQPRODUTO = X.SEQPRODUTO 
           AND A.NROEMPRESA = X.NROEMPRESA 
           AND A.NROSEGMENTO = X.NROSEGMENTO 
           AND TO_DATE(A.DTAHORALTERACAO, 'DD/MM/YY') <= DTA 
           AND A.QTDEMBALAGEM = X.QTDEMBALAGEM 
           ORDER BY DTAHORALTERACAO DESC)WHERE ROWNUM = 1) PRECO
       
  FROM DIM_TEMPO, MRL_PRODEMPSEG X INNER JOIN MAP_PRODUTO M ON X.SEQPRODUTO = M.SEQPRODUTO
 WHERE 1=1
   AND DTA BETWEEN DATE '2023-06-01' AND SYSDATE 
   AND NROSEGMENTO  = 8 
   AND STATUSVENDA  = 'A' 
   AND NROEMPRESA   = 41
   AND QTDEMBALAGEM = 1 
   
   
   ORDER BY X.SEQPRODUTO, DTA
   
