ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT (SELECT DISTINCT LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) FROM CONSINCO.GE_PESSOA Y WHERE Y.SEQPESSOA = X.SEQPESSOA) CPF,
       X.NROEMPRESA NRO_LOJA, X.NROSEGMENTO NRO_SEGMENTO, X.DTAEMISSAO DATA_VENDA, X.NUMERODF NRO_CUPOM, X.VLRITEM, X.NFECHAVEACESSO
  
  FROM CONSINCO.MFLV_BASENF X WHERE X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
  AND X.DTAEMISSAO > SYSDATE - 1 AND X.NROEMPRESA = 1
