SELECT A.SEQPRODUTO COD_BASE,
       A.DESCCOMPLETA AS DESCRICAO,
       B.SEQPRODUTO   AS COD_RELACIONADO,
       B.DESCCOMPLETA AS DESCRICAO_RELACIONADO
       
FROM MAP_PRODUTO A INNER JOIN MAP_PRODUTO B ON A.SEQPRODUTO = B.SEQPRODUTOBASE

WHERE B.SEQPRODUTOBASE IS NOT NULL
ORDER BY A.DESCCOMPLETA ASC;
