SELECT DISTINCT A.NROEMPRESA, A.CODINVAREA, A.DESCINVAREA, C.CODINVSUBAREA, C.DESCINVSUBAREA 
  FROM CONSINCO.MRL_INVAREA A INNER JOIN CONSINCO.MRL_LOCAL B      ON A.SEQLOCAL = B.SEQLOCAL
                              INNER JOIN CONSINCO.MRL_INVSUBAREA C ON C.CODINVAREA = A.CODINVAREA 
                              
WHERE B.LOCAL = 'LOJA'
  AND A.DESCINVAREA = 'GERAL'
  AND C.DESCINVSUBAREA = 'GERAL'
  
 ORDER BY 1
