SELECT DISTINCT X.NROEMPRESA LOJA, X.NUMERONF, TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTAENTRADA,
       LOCAL, X.SEQPESSOA||' - '||(SELECT NOMERAZAO FROM CONSINCO.GE_PESSOA Z WHERE Z.SEQPESSOA = X.SEQPESSOA) DESTINO, X.USULANCTO, X.OBSERVACAO
  FROM CONSINCO.MLFV_DEVNFITEMFORN DEV INNER JOIN CONSINCO.MLF_NOTAFISCAL X ON DEV.SEQNF = X.SEQNF
  
  WHERE X.DTAEMISSAO BETWEEN :DT1 AND :DT2
    AND X.NROEMPRESA IN (#LS1)
    
    ORDER BY 1,2
