-- Ticket 640953

SELECT A.NROEMPRESA, TO_CHAR(DTAESTOQUE, 'DD/MM/YYYY') DATA_BASE,
       A.SEQPRODUTO COD_PRODUTO, DESCCOMPLETA DESC_PRODUTO, A.QTDESTQLOJA,
      (SELECT SUM(QTDESTQDEPOSITO) FROM FATO_ESTOQUE C WHERE NROEMPRESA > 100 AND C.SEQPRODUTO = A.SEQPRODUTO AND C.DTAESTOQUE = A.DTAESTOQUE) ESTQ_CD,
       ROUND(A.VLRCTOLIQUIDO,2) VLR_CUSTO_LIQ, ROUND(A.VLRCTOBRUTO,2) VLR_CUSTO_BRUTO,
       ROUND(((NAGF_PRECO_DIA_X(A.NROEMPRESA, A.SEQPRODUTO, E.NROSEGMENTOPRINC, 1, A.DTAESTOQUE) - A.VLRCTOBRUTO) / NVL(NULLIF(A.VLRCTOBRUTO,0),0.001)) * 100,2) MARKUP,
       ROUND(((NAGF_PRECO_DIA_X(A.NROEMPRESA, A.SEQPRODUTO, E.NROSEGMENTOPRINC, 1, A.DTAESTOQUE) - A.VLRCTOBRUTO) / NVL(NULLIF(NAGF_PRECO_DIA_X(A.NROEMPRESA, A.SEQPRODUTO, E.NROSEGMENTOPRINC, 1, A.DTAESTOQUE),0),0.001)) * 100,2) MARKDOWN,
       ROUND(CASE WHEN NVL( X.CMULTCUSLIQUIDOEMP, 0 ) - NVL( X.CMULTDCTOFORANFEMP, 0 ) < 0 THEN 0 
            ELSE NVL( X.CMULTCUSLIQUIDOEMP, 0 ) - NVL( X.CMULTDCTOFORANFEMP, 0 ) END,2) CUSTOFISCALUNIT,
       ROUND(CASE WHEN NVL( ( NVL( X.CMULTCUSLIQUIDOEMP, 0 ) - NVL( X.CMULTDCTOFORANFEMP, 0 ) ) * X.ESTQEMPRESA, 0 ) < 0 THEN 0
            ELSE NVL( ( NVL( X.CMULTCUSLIQUIDOEMP, 0 ) - NVL( X.CMULTDCTOFORANFEMP, 0 ) ) * X.ESTQEMPRESA, 0 ) END,2) CUSTOFISCALTOTAL, 
       CATEGORIAN1, CATEGORIAN2 
        
  FROM FATO_ESTOQUE A       INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO
                            INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = A.NROEMPRESA
                            INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA
                            INNER JOIN MRL_PRODUTOEMPRESA X ON X.SEQPRODUTO = A.SEQPRODUTO AND X.NROEMPRESA = A.NROEMPRESA
                            INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA AND F.FINALIDADEFAMILIA = 'R'
                            
 WHERE 1=1
   AND A.NROEMPRESA IN (#LS1)
   AND DTAESTOQUE = :DT1
   AND C.CATEGORIAN1 = #LS2
   
   ORDER BY C.CATEGORIAN1, 3;
 
