ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT SEQPRODUTO PLU, DESCCOMPLETA, 
         CASE WHEN PROPQTDPERDAAUTO   IS NOT NULL THEN 'PERDA AUTO' END
       ||CASE WHEN PROPQTDPERDAAUTO   IS NOT NULL AND PROPQTDPRODUTOBASE IS NOT NULL THEN ' E ' END
       ||CASE WHEN PROPQTDPRODUTOBASE IS NOT NULL THEN 'BAIXA AUTO' END
      PROCESSO_AUTO
  FROM MAP_PRODUTO X WHERE X.PROPQTDPERDAAUTO IS NOT NULL OR X.PROPQTDPRODUTOBASE IS NOT NULL
  
  ORDER BY 2
