ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT SEQPRODUTO PLU, DESCCOMPLETA, 
       TO_CHAR(PROPQTDPRODUTOBASE, 'FM999G999G990D90000', 'NLS_NUMERIC_CHARACTERS='',.''') PROP_QTD_BAIXA_PROD_BASE, 
       TO_CHAR(X.PROPQTDPERDAAUTO, 'FM999G999G990D90000', 'NLS_NUMERIC_CHARACTERS='',.''') PROP_QTD_PERDA_AUTO
  FROM MAP_PRODUTO X WHERE X.PROPQTDPERDAAUTO > 0 OR X.PROPQTDPRODUTOBASE > 0

ORDER BY 2
