SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
 MRLV_INVRELDIVERG_NAG.SEQINVLOTE LOTE,
 MRLV_INVRELDIVERG_NAG.NROEMPRESA LOJA,
 TO_CHAR(CONSINCO.MRLV_INVRELDIVERG_NAG.DTAHORCONGESTOQUE, 'DD/MM/YYYY') DTA_CONGELAMENTO,
 MRLV_INVRELDIVERG_NAG.SEQPRODUTO PLU,
 MRLV_INVRELDIVERG_NAG.DESCCOMPLETA PRODUTO,
 MRLV_INVRELDIVERG_NAG.EMBVENDA EMBALAGEM,
 MRLV_INVRELDIVERG_NAG.QTDCONGELADA * MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM /
 NVL(MRLV_INVRELDIVERG_NAG.PADRAOEMBVENDA, 1) QTDE_CONGELADA,
 (CASE
   WHEN NVL(((SELECT COALESCE(SUM(CC.QTDCONTAGEM3 * CC.QTDEMBALAGEM),
                              SUM(CC.QTDCONTAGEM2 * CC.QTDEMBALAGEM),
                              SUM(CC.QTDCONTAGEM1 * CC.QTDEMBALAGEM),
                              0)
                FROM CONSINCO.MRL_INVCONTAGEM CC
               WHERE CC.SEQINVLOTE = MRLV_INVRELDIVERG_NAG.SEQINVLOTE
                     AND CC.NROEMPRESA = MRLV_INVRELDIVERG_NAG.NROEMPRESA
                     AND CC.SEQPRODUTO = MRLV_INVRELDIVERG_NAG.SEQPRODUTO
                     AND 0 = 0
                     AND NVL(CC.NROLOTEPROD, 0) =
                     NVL(MRLV_INVRELDIVERG_NAG.NROLOTEPROD, 0)
                     AND
                     (CC.CODINVAREA IN
                     (SELECT NUMBER1 FROM CONSINCO.GEX_DADOSTEMPORARIOS) OR
                     NOT EXISTS((SELECT NUMBER1
                                   FROM CONSINCO.GEX_DADOSTEMPORARIOS)))) /
            MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM),
            0) > 0 THEN
    NVL(((SELECT COALESCE(SUM(CC.QTDCONTAGEM3 * CC.QTDEMBALAGEM),
                          SUM(CC.QTDCONTAGEM2 * CC.QTDEMBALAGEM),
                          SUM(CC.QTDCONTAGEM1 * CC.QTDEMBALAGEM),
                          0)
            FROM CONSINCO.MRL_INVCONTAGEM CC
           WHERE CC.SEQINVLOTE = MRLV_INVRELDIVERG_NAG.SEQINVLOTE
                 AND CC.NROEMPRESA = MRLV_INVRELDIVERG_NAG.NROEMPRESA
                 AND CC.SEQPRODUTO = MRLV_INVRELDIVERG_NAG.SEQPRODUTO
                 AND 0 = 0
                 AND NVL(CC.NROLOTEPROD, 0) =
                 NVL(MRLV_INVRELDIVERG_NAG.NROLOTEPROD, 0)
                 AND
                 (CC.CODINVAREA IN
                 (SELECT NUMBER1 FROM CONSINCO.GEX_DADOSTEMPORARIOS) OR
                 NOT
                  EXISTS((SELECT NUMBER1 FROM CONSINCO.GEX_DADOSTEMPORARIOS)))) /
        MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM),
        0)
   ELSE
    0
 END / C.PADRAOEMBVENDA) QTD_CONTAGEM,
 
 ((((SELECT COALESCE(SUM(CC.QTDCONTAGEM3 * CC.QTDEMBALAGEM),
                     SUM(CC.QTDCONTAGEM2 * CC.QTDEMBALAGEM),
                     SUM(CC.QTDCONTAGEM1 * CC.QTDEMBALAGEM),
                     0)
       FROM CONSINCO.MRL_INVCONTAGEM CC
      WHERE CC.SEQINVLOTE = MRLV_INVRELDIVERG_NAG.SEQINVLOTE
            AND CC.NROEMPRESA = MRLV_INVRELDIVERG_NAG.NROEMPRESA
            AND CC.SEQPRODUTO = MRLV_INVRELDIVERG_NAG.SEQPRODUTO
            AND 0 = 0
            AND NVL(CC.NROLOTEPROD, 0) =
            NVL(MRLV_INVRELDIVERG_NAG.NROLOTEPROD, 0)
            AND
            (CC.CODINVAREA IN
            (SELECT NUMBER1 FROM CONSINCO.GEX_DADOSTEMPORARIOS) OR
            NOT EXISTS((SELECT NUMBER1 FROM CONSINCO.GEX_DADOSTEMPORARIOS)))) -
 QTDCONGELADAUNIT) / MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM)) QTDE_DIVERGENTE,
 ROUND(CASE
         WHEN (MRLV_INVRELDIVERG_NAG.QTDCONGELADA *
              MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM /
              NVL(MRLV_INVRELDIVERG_NAG.PADRAOEMBVENDA, 1)) = 0 THEN
          0
         ELSE
          MRLV_INVRELDIVERG_NAG.CUSBRUTCONGELADO
       END,
       2) AS CUSTO_BRUTO,
 ROUND(CASE
         WHEN (MRLV_INVRELDIVERG_NAG.QTDCONGELADA *
              MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM /
              NVL(MRLV_INVRELDIVERG_NAG.PADRAOEMBVENDA, 1)) = 0 THEN
          0
         ELSE
          MRLV_INVRELDIVERG_NAG.CUSLIQCONGELADO
       END,
       2) CUSTO_LIQUIDO,
 CASE
   WHEN (MRLV_INVRELDIVERG_NAG.QTDCONGELADA *
        MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM /
        NVL(MRLV_INVRELDIVERG_NAG.PADRAOEMBVENDA, 1)) = 0 THEN
    0
   ELSE
    MRLV_INVRELDIVERG_NAG.PRECOVDACONGELADO
 END PRECO,
 /* Estoques CDs */
 NAGF_ESTQLOCAL_CD(501,B.SEQPRODUTO,'D') DEP_501,
 NAGF_ESTQLOCAL_CD(501,B.SEQPRODUTO,'O') OUT_501,
 NAGF_ESTQLOCAL_CD(502,B.SEQPRODUTO,'D') DEP_502,
 NAGF_ESTQLOCAL_CD(502,B.SEQPRODUTO,'O') OUT_502,
 NAGF_ESTQLOCAL_CD(503,B.SEQPRODUTO,'D') DEP_503,
 NAGF_ESTQLOCAL_CD(503,B.SEQPRODUTO,'O') OUT_503,
 NAGF_ESTQLOCAL_CD(506,B.SEQPRODUTO,'D') DEP_506,
 NAGF_ESTQLOCAL_CD(506,B.SEQPRODUTO,'O') OUT_506,
 NAGF_ESTQLOCAL_CD(507,B.SEQPRODUTO,'D') DEP_507,
 NAGF_ESTQLOCAL_CD(507,B.SEQPRODUTO,'O') OUT_507,
 NAGF_ESTQLOCAL_CD(508,B.SEQPRODUTO,'D') DEP_508,
 NAGF_ESTQLOCAL_CD(508,B.SEQPRODUTO,'O') OUT_508
 
  FROM CONSINCO.MRLV_INVRELDIVERG_NAG,
       CONSINCO.MAP_PRODUTO           B,
       CONSINCO.MAD_FAMSEGMENTO       C
 WHERE 1 = 1
       AND MRLV_INVRELDIVERG_NAG.NROEMPRESA IN (#LS1)
       AND MRLV_INVRELDIVERG_NAG.SEQPRODUTO = B.SEQPRODUTO
       AND MRLV_INVRELDIVERG_NAG.STATUS != 'C'
       AND B.SEQFAMILIA = C.SEQFAMILIA
       AND C.NROSEGMENTO = MRLV_INVRELDIVERG_NAG.NROSEGMENTO
       AND MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM =
       DECODE(MRLV_INVRELDIVERG_NAG.EXIBE_MENOR_EMB,
                  'S',
                  CONSINCO.FMINEMBFAMILIA(B.SEQFAMILIA),
                  NVL(CONSINCO.FRETEMBINVENT(MRLV_INVRELDIVERG_NAG.SEQPRODUTO,
                                             MRLV_INVRELDIVERG_NAG.SEQINVLOTE,
                                             MRLV_INVRELDIVERG_NAG.NROEMPRESA,
                                             MRLV_INVRELDIVERG_NAG.PADRAOEMBVENDA),
                      MRLV_INVRELDIVERG_NAG.PADRAOEMBVENDA))
       AND
       ((NVL((((SELECT COALESCE(SUM(CC.QTDCONTAGEM3 * CC.QTDEMBALAGEM),
                                SUM(CC.QTDCONTAGEM2 * CC.QTDEMBALAGEM),
                                SUM(CC.QTDCONTAGEM1 * CC.QTDEMBALAGEM),
                                0)
                  FROM CONSINCO.MRL_INVCONTAGEM CC
                 WHERE CC.SEQINVLOTE = MRLV_INVRELDIVERG_NAG.SEQINVLOTE
                       AND CC.NROEMPRESA = MRLV_INVRELDIVERG_NAG.NROEMPRESA
                       AND CC.SEQPRODUTO = MRLV_INVRELDIVERG_NAG.SEQPRODUTO
                       AND 0 = 0
                       AND NVL(CC.NROLOTEPROD, 0) =
                       NVL(MRLV_INVRELDIVERG_NAG.NROLOTEPROD, 0)
                       AND
                       (CC.CODINVAREA IN
                       (SELECT NUMBER1 FROM CONSINCO.GEX_DADOSTEMPORARIOS) OR
                       NOT EXISTS((SELECT NUMBER1
                                     FROM CONSINCO.GEX_DADOSTEMPORARIOS)))) -
             QTDCONGELADAUNIT) / MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM),
             0) != 0) OR (MRLV_INVRELDIVERG_NAG.QTDSEMCONTAGEM <= 0) OR
       (EXISTS
        (SELECT *
            FROM CONSINCO.MRL_INVPRODUTO B
           WHERE MRLV_INVRELDIVERG_NAG.SEQINVLOTE = B.SEQINVLOTE
                 AND MRLV_INVRELDIVERG_NAG.SEQPRODUTO = B.SEQPRODUTO
                 AND MRLV_INVRELDIVERG_NAG.NROEMPRESA = B.NROEMPRESA
                 AND B.QTDCONGELADA <> 0
                 AND NOT EXISTS (SELECT *
                    FROM CONSINCO.MRL_INVCONTAGEM C
                   WHERE B.NROEMPRESA = C.NROEMPRESA
                         AND B.SEQINVLOTE = C.SEQINVLOTE
                         AND B.SEQPRODUTO = C.SEQPRODUTO
                         AND C.QTDCONTAGEM1 = 0))) OR
       (MRLV_INVRELDIVERG_NAG.QTDSEMCONTAGEM > 0 AND
       ((SELECT COALESCE(SUM(CC.QTDCONTAGEM3 * CC.QTDEMBALAGEM),
                           SUM(CC.QTDCONTAGEM2 * CC.QTDEMBALAGEM),
                           SUM(CC.QTDCONTAGEM1 * CC.QTDEMBALAGEM),
                           0)
             FROM CONSINCO.MRL_INVCONTAGEM CC
            WHERE CC.SEQINVLOTE = MRLV_INVRELDIVERG_NAG.SEQINVLOTE
                  AND CC.NROEMPRESA = MRLV_INVRELDIVERG_NAG.NROEMPRESA
                  AND CC.SEQPRODUTO = MRLV_INVRELDIVERG_NAG.SEQPRODUTO
                  AND 0 = 0
                  AND NVL(CC.NROLOTEPROD, 0) =
                  NVL(MRLV_INVRELDIVERG_NAG.NROLOTEPROD, 0)
                  AND
                  (CC.CODINVAREA IN
                  (SELECT NUMBER1 FROM CONSINCO.GEX_DADOSTEMPORARIOS) OR
                  NOT
                   EXISTS((SELECT NUMBER1 FROM CONSINCO.GEX_DADOSTEMPORARIOS)))) /
       MRLV_INVRELDIVERG_NAG.QTDEMBALAGEM) = 0))
       AND UPPER(MRLV_INVRELDIVERG_NAG.DESCINVLOTE) LIKE
       '%' || UPPER('#LT1') || '%'
       AND MRLV_INVRELDIVERG_NAG.DTAHORGERACAO BETWEEN :DT1 AND :DT2
       AND MRLV_INVRELDIVERG_NAG.NIVELHIERARQUIA = 1
       AND MRLV_INVRELDIVERG_NAG.INDVALIDACAO != 'M'
 ORDER BY NULL, MRLV_INVRELDIVERG_NAG.DESCCOMPLETA
