SELECT translate(CODPOS,' .-', ' ')  LOJA_OCORRENCIA
FROM ( 
SELECT '0000000'||LPAD(PC.CODACESSO,13,0)||REPLACE(LPAD(
                   CASE WHEN QTDCONTAGEM3 > 0 THEN QTDDIVERGCONT3
                        WHEN QTDCONTAGEM2 > 0 THEN QTDDIVERGCONT2
                        ELSE QTDDIVERGCONT1
                        END,8,0),'-','') CODPOS,  
                   CASE WHEN QTDCONTAGEM3 > 0 THEN QTDDIVERGCONT3
                        WHEN QTDCONTAGEM2 > 0 THEN QTDDIVERGCONT2
                        ELSE QTDDIVERGCONT1
                        END DIVERG
                       
  FROM CONSINCO.MRLV_INVRELDIVERG A LEFT JOIN (SELECT PCC.SEQPRODUTO, PCC.CODACESSO, ROW_NUMBER() OVER(PARTITION BY PCC.SEQPRODUTO ORDER BY PCC.SEQPRODUTO) ODR FROM
       CONSINCO.MAP_PRODCODIGO PCC WHERE PCC.QTDEMBALAGEM = 1 AND PCC.TIPCODIGO IN ('E', 'B')) PC ON A.SEQPRODUTO = PC.SEQPRODUTO AND PC.ODR = 1
 
 WHERE A.NROEMPRESA = :NR1      
   AND A.SEQINVLOTE = :NR2
   AND A.STATUS != 'C'
   AND A.NIVELHIERARQUIA = 1
   
ORDER BY NULL, A.DESCCOMPLETA) 
 
WHERE DIVERG < 0
