ALTER SESSION SET current_schema = CONSINCO;

SELECT A.SEQMOVTOESTQ, A.TIPLANCTO, A.NROEMPRESA EMP, A.DTAENTRADASAIDA DTA, A.SEQPRODUTO PLU, B.DESCCOMPLETA, A.CODGERALOPER CGO, A.QTDLANCTO, A.VALORVLRNF,
       A.NRODOCUMENTO DOC, A.RECALCUSTOMEDIO, A.DTAHORLANCTO, A.USULANCTO

FROM MRL_LANCTOESTOQUE A LEFT JOIN MAP_PRODUTO B ON A.SEQPRODUTO = B.SEQPRODUTO

WHERE A.NROEMPRESA = 14 AND A.SEQPRODUTO = 42116 AND RECALCUSTOMEDIO = 'S' AND DTAENTRADASAIDA BETWEEN DATE '2021-11-26' AND DATE '2021-11-27' AND NRODOCUMENTO = 715

UNION ALL

SELECT A.SEQMOVTOESTQ, A.TIPLANCTO, A.NROEMPRESA, A.DTAENTRADASAIDA, A.SEQPRODUTO, B.DESCCOMPLETA, A.CODGERALOPER, A.QTDLANCTO, A.VALORVLRNF,
       A.NRODOCUMENTO, A.RECALCUSTOMEDIO, A.DTAHORLANCTO, A.USULANCTO

FROM MRL_LANCTOESTOQUE A LEFT JOIN MAP_PRODUTO B ON A.SEQPRODUTO = B.SEQPRODUTOSó juntei

WHERE A.NROEMPRESA = 14 AND A.SEQPRODUTO = 241763 AND RECALCUSTOMEDIO = 'S' AND DTAENTRADASAIDA BETWEEN DATE '2021-11-26' AND DATE '2021-11-27' AND NRODOCUMENTO = 715

ORDER BY 2  

