SELECT SEQMOVTOESTQ, NRODOCUMENTO, NROEMPRESA EMP, 
       TO_CHAR(DTAHORLANCTO, 'DD/MM/YYYY HH24:MI') DATA_MOVTO, USULANCTO, SEQPRODUTO PLU, SEQPRODUTOBASE PLU_PAI,
       A.CODGERALOPER||' - '||B.DESCRICAO CGO, QTDLANCTO, DECODE(TIPLANCTO, 'S','SAIDA','E','ENTRADA') MOVIMENTACAO

  FROM MRL_LANCTOESTOQUE A INNER JOIN MAX_CODGERALOPER B ON A.CODGERALOPER = B.CODGERALOPER
 WHERE A.NROEMPRESA = :LS1
   AND ((A.SEQPRODUTO = :NR1 AND SEQPRODUTOBASE IS NULL) OR
       A.SEQPRODUTOBASE = :NR1)
   AND A.DTAENTRADASAIDA BETWEEN :DT1 AND :DT2
   
   ORDER BY 4 ASC
