ALTER SESSION SET current_schema = CONSINCO;

SELECT TO_CHAR(A.DTAHORLANCTO, 'DD/MM/YYYY') DATA_LANCTO, DECODE(A.TIPLANCTO, 'S','Entrada','E','Saida') TIPOMOVTO,
       TO_CHAR(A.QTDLANCTO, 'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''') QTD_LANCTO
    FROM   MRL_LANCTOESTOQUE A 
    WHERE  A.SEQPRODUTO = 11259                              
    AND    A.NROEMPRESA = 34
    AND    A.TIPLANCTO IN ('E','S')                          
    AND  A.CODGERALOPER IN (403,503)
    AND A.DTAENTRADASAIDA > DATE '2022-01-01'
    AND A.LOCAL IN (SELECT SEQLOCAL FROM MRL_LOCAL WHERE NROEMPRESA = A.NROEMPRESA AND LOCAL = 'OCORRENCIAS')

UNION ALL

SELECT NULL, NULL, NULL FROM DUAL

UNION ALL

SELECT 'Dta Lote Aberto', 'NRO_LOTE', 'QTD_MOVT' FROM DUAL

UNION ALL

SELECT TO_CHAR(B.DTAHORGERACAO, 'DD/MM/YYYY'), TO_CHAR(B.SEQINVLOTE), 
       TO_CHAR(CASE WHEN QTDCONTAGEM3 > 0 THEN QTDDIVERGCONT3
              WHEN QTDCONTAGEM2 > 0 THEN QTDDIVERGCONT2
              ELSE QTDDIVERGCONT1
              END , 'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''')
                        
FROM CONSINCO.MRLV_INVRELDIVERG B
 WHERE 1=1 AND B.SEQPRODUTO = 11259
   AND B.STATUS = 'G'
   AND B.NIVELHIERARQUIA = 1
   AND NROEMPRESA = 34
   
UNION ALL

SELECT NULL, NULL, NULL FROM DUAL

UNION ALL 

SELECT NULL, 'ESTQ_LOJA', TO_CHAR(ESTQLOJA , 'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''')
FROM MRL_PRODUTOEMPRESA WHERE SEQPRODUTO = 11259 AND NROEMPRESA = 34  

UNION ALL 

SELECT NULL, 'ESTQ_OCORRENCIAS', TO_CHAR(ESTQOUTRO , 'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''')
FROM MRL_PRODUTOEMPRESA WHERE SEQPRODUTO = 11259 AND NROEMPRESA = 34  

UNION ALL

SELECT NULL, NULL, NULL FROM DUAL

UNION ALL

SELECT NULL, 'Codigo Produto:', '11259' FROM DUAL
