SELECT A.NROCARGA, 
       A.ORIGEM,
       A.CODIGO,
       A.PRODUTO DESCRICAO,
       A.EMB,
       SUM(QUANTIDADE / QTDEMBALAGEM) QUANTIDADE,
       /*A.DTAHORMOVIMENTACAO,*/
       B.DESCRICAO ATIVIDADE_SI,
       TO_CHAR(MAX(B.DTAHORFIMTAREFA), 'DD/MM/YYYY HH24:MI:SS') DTAHORFIMATIVIDADE_SI,
       A.SITUACAO

  FROM MLOV_CONSULTASTAGEIN A LEFT JOIN MLOV_CONSULTASTAGEINATIVIDADE B ON A.CODIGO = B.SEQPRODUTO AND A.NROEMPRESA = B.NROEMPRESA AND A.NROCARGA = B.NROCARGARECEB AND A.ETIQUETA = B.NROETQORIGEM AND A.TIPOCARGA = B.TIPOCARGA AND B.CODTIPATIVIDADE = 'SI'

 WHERE A.NROEMPRESA = CODDEPOSITANTE
    
   AND DTAMOVIMENTACAO BETWEEN :DT1 AND :DT2
   AND CODDEPOSITANTE IN (#LS1)
   
   GROUP BY NROCARGA, ORIGEM, CODIGO, PRODUTO, EMB, B.DESCRICAO, SITUACAO
