WITH BASE AS (

   SELECT X.NRO_ACORDO, C.NROTITULO||'-'||C.NROPARCELA  TITULO, C.NROEMPRESA  LJ,
          X.COD_FORNECEDOR, X.FORNECEDOR, X.DATA_EMISSAO, C.DTAINCLUSAO, C.DTAVENCIMENTO, X.VLR_ACORDO,
          C.VLRORIGINAL  VLR_TITULO, C.VLRPAGO, O.OBSERVACAO  OPERACAO, O.VLROPERACAO, O.DTAOPERACAO, F.COLOPERACAO1 OP
        
    FROM NAGV_TAE_ACORDOS_V4 X INNER JOIN FI_TITULO C ON C.NROTITULO = X.NRO_ACORDO AND X.COD_FORNECEDOR = C.SEQPESSOA
                               INNER JOIN FI_TITOPERACAO O ON O.SEQTITULO = C.SEQTITULO AND O.OPCANCELADA IS NULL AND O.CODOPERACAO = 16
                               INNER JOIN FI_OPERACAO F ON F.CODOPERACAO = O.CODOPERACAO
    WHERE X.STATUS = 'Envelope finalizado'
      AND C.SITUACAO != 'C'

    UNION ALL

   SELECT X.NRO_ACORDO, C.NROTITULO||'-'||C.NROPARCELA  TITULO, C.NROEMPRESA  LJ,
          X.COD_FORNECEDOR, X.FORNECEDOR, NULL, NULL, NULL, NULL,
          NULL, NULL, O.OBSERVACAO, O.VLROPERACAO * DECODE(F.COLOPERACAO1, 'N', 1, 'D', -1, 'C', 1, -1), O.DTAOPERACAO, F.COLOPERACAO1 OP
        
    FROM NAGV_TAE_ACORDOS_V4 X INNER JOIN FI_TITULO C ON C.NROTITULO = X.NRO_ACORDO AND X.COD_FORNECEDOR = C.SEQPESSOA
                               INNER JOIN FI_TITOPERACAO O ON O.SEQTITULO = C.SEQTITULO AND O.OPCANCELADA IS NULL AND O.CODOPERACAO != 16
                               INNER JOIN FI_OPERACAO F ON F.CODOPERACAO = O.CODOPERACAO
    WHERE X.STATUS = 'Envelope finalizado'
      AND C.SITUACAO != 'C'
)

SELECT 
  B.NRO_ACORDO,
  B.TITULO,
  B.LJ,
  B.COD_FORNECEDOR  COD_FORNEC,
  B.FORNECEDOR,
  TO_CHAR(B.DATA_EMISSAO, 'DD/MM/YYYY')      DTA_EMISSAO,
  TO_CHAR(B.DTAINCLUSAO,  'DD/MM/YYYY')      DTA_INC_TITULO,
  TO_CHAR(B.DTAVENCIMENTO,'DD/MM/YYYY')      DTA_VENC_TITULO,
  TO_CHAR(B.VLR_ACORDO,  'FM999G999G990D90','NLS_NUMERIC_CHARACTERS='',.''') VLR_ACORDO,
  TO_CHAR(B.VLR_TITULO,  'FM999G999G990D90','NLS_NUMERIC_CHARACTERS='',.''') VLR_TITULO,
  TO_CHAR(B.VLRPAGO,     'FM999G999G990D90','NLS_NUMERIC_CHARACTERS='',.''') VLR_PAGO,
  B.OPERACAO,
  TO_CHAR(B.VLROPERACAO, 'FM999G999G990D90','NLS_NUMERIC_CHARACTERS='',.''') VLR_OPERACAO,
  TO_CHAR(B.DTAOPERACAO , 'DD/MM/YYYY')      DTAOPERACAO,
  TO_CHAR(
    SUM(B.VLROPERACAO) OVER (
      PARTITION BY B.COD_FORNECEDOR
      ORDER BY B.COD_FORNECEDOR ASC, B.TITULO ASC, B.DTAOPERACAO ASC
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ),
    'FM999G999G990D90','NLS_NUMERIC_CHARACTERS='',.'''
  ) AS SALDO
FROM BASE B
WHERE  1=1 AND B.COD_FORNECEDOR = 114190
ORDER BY B.COD_FORNECEDOR ASC, B.TITULO ASC, B.DTAOPERACAO ASC

