SELECT A.CODBARRAETQ ETIQUETA,
       A.NROCARGA, A.SEQPALETECARREG ETQ_CARREG,
       DECODE(A.TIPOCARGA, 'Expedi¿¿o', 'Expedição', A.TIPOCARGA) TIPOCARGA,
       A.TIPESPECIE DESTINO,
       A.SEQPRODUTO PLU,
       P.DESCCOMPLETA DESCRICAO,
       REGEXP_REPLACE(EMBALAGEM, '[^0-9]', '') QTD_EMBALAGEM,
       A.QUANTIDADEEMB,
       REGEXP_REPLACE(EMBALAGEM, '[^0-9]', '') * A.QUANTIDADEEMB QTD_UNIT_TOTAL,
       TO_CHAR(DTARECEBIMENTO, 'DD/MM/YYYY') DTA_RECEBIMENTO,
       TO_CHAR(DTAHORINIAGRUPAMENTO,'DD/MM/YYYY  HH24:MI:SS') INICIO_AGRUPAMENTO,
       TO_CHAR(DTAHORFIMAGRUPAMENTO,'DD/MM/YYYY  HH24:MI:SS') FIM_AGRUPAMENTO,
       (SELECT MAX(X.DTAGERACAONF) FROM MAD_PEDVENDA X WHERE X.SEQPALETECARREG = A.SEQPALETECARREG) FATURAMENTO
       
  FROM MLOV_CONTROLEETQSORTERCARREG A INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO
                                      INNER JOIN MLO_PALETECARREG G ON G.SEQPALETECARREG = A.SEQPALETECARREG

 WHERE A.NROEMPRESA IN (#LS1)
   AND A.DTARECEBIMENTO BETWEEN :DT1 AND :DT2
   
 ORDER BY A.CODBARRAETQ;
 
