SELECT T.NROEMPRESA,
       T.PERIODO,
       T.SEGMENTO,
       'PROTEINAS' CATEGORIA,
       SUM(T.CUPONS) CUPONS
FROM NAGV_CATEGORIATICKETN4@BI T
WHERE T.DATA BETWEEN :DT1 AND :DT2
AND T.NROEMPRESA IN (#LS1)
AND CATEGORIAN1 IN
               ('AÇOUGUE', 'FRIOS E LATICINIOS', 'PEIXARIA', 'HORTIFRUTI')
           AND CATEGORIAN2 IN ('BOVINO',
                               'AVE',
                               'SUINO',
                               'DEFUMADO E CHARQUEADO',
                               'CAPRINO',
                               'REFRIGERADOS',
                               'PRATO PRONTO CONGELADO',
                               'PEIXES',
                               'GRANJEIROS')
              
           AND CATEGORIAN3 IN
               ('BOVINO VACUO',
                'BOVINO MANIPULADO',
                'BOVINO CONGELADO',
                'AVE REFRIGERADA',
                'AVE CONGELADA',
                'SUINO CONGELADO',
                'SUINO REFRIGERADO',
                'CARNE SECA',
                'CAPRINO CONGELADO',
                'EMBUTIDOS E DEFUMADOS',
                'EMPANADOS',
                'HAMBURGUER',
                'PEIXE FRESCO',
                'PEIXE CONGELADO',
                'BACALHAU',
                'PEIXE SALGADO',
                'PETISCO CONGELADO',
                'OVOS')
                
                AND CATEGORIAN4 IN ('CORTES VACUO',
                                    'CORTES BOVINO',
                                    'MIUDO BOVINO',
                                    'BOVINO PRATA',
                                    'ESPETO BOVINO',
                                    'MOIDA CONGELADA',
                                    'CORTES REFRIGERADOS',
                                    'AVE INTEIRA',
                                    'MIUDOS FRANGO',
                                    'CORTES TEMPERADOS',
                                    'ESPETO AVE',
                                    'AVE PRATA',
                                    'CORTES CONGELADOS',
                                    'MIUDO DE FRANGO',
                                    'ORGANICO',
                                    'CORTES SUINOS',
                                    'CORTES SUINO',
                                    'SUINO PRATA',
                                    'DIANTEIRO',
                                    'TRASEIRO',
                                    'COXAO',
                                    'CORTES CORDEIRO',
                                    'LINGUICA',
                                    'SALSICHA',
                                    'BACON',
                                    'CORTE SUINO',
                                    'PEITO DE FRANGO',
                                    'LOMBO',
                                    'STEAK',
                                    'MINI STEAK',
                                    'STEAK ISCA',
                                    'STEAK TIRINHAS',
                                    'TRADICIONAL',
                                    'ESPECIAL',
                                    'CARNE VEGETAL',
                                    'TILAPIA FRESCA',
                                    'SARDINHA FRESCA',
                                    'CAMARAO FRESCO',
                                    'CORVINA FRESCA',
                                    'CAVALINHA FRESCO',
                                    'CACAO FRESCO',
                                    'PESCADA FRESCO',
                                    'SALMAO FRESCO',
                                    'PORQUINHO FRESCO',
                                    'PACU FRESCO',
                                    'GOETE FRESCO',
                                    'BONITO FRESCO',
                                    'OVEVA FRESCO',
                                    'MANJUBA FRESCO',
                                    'PINTADO FRESCO',
                                    'CURIMBATA FRESCO',
                                    'BAGRE FRESCO',
                                    'ATUM FRESCO',
                                    'ANCHOVA FRESCA',
                                    'PARATI FRESCO',
                                    'CARAPAU FRESCO',
                                    'MARIA MOLE FRESCO',
                                    'ABROTEA FRESCO',
                                    'ESPADA FRESCO',
                                    'MANDI FRESCO',
                                    'PALOMBETA',
                                    'TRAIRA FRESCO',
                                    'GALO FRESCO',
                                    'GORDINHO FRESCO',
                                    'TRILHA FRESCO',
                                    'NAMORADO FRESCO',
                                    'SERRA FRESCO',
                                    'PARGO FRESCO',
                                    'ROBALO FRESCO',
                                    'CARAPEBA FRESCO',
                                    'CORIMBA FRESCO',
                                    'CABRINHA FRESCO',
                                    'CEOBA FRESCO',
                                    'PIAPARA FRESCO',
                                    'CASCOTE FRESCO',
                                    'XAREU FRESCO',
                                    'TUCUNARE FRESCO',
                                    'CASTANHA FRESCO',
                                    'ENGUIA FRESCO',
                                    'DOURADA FRESCO',
                                    'PREJEREBA FRWESCO',
                                    'OLHO DE BOI FRESCO',
                                    'OLHO DE CAO FRESCO',
                                    'PANGASIUS',
                                    'PIAU FRESCO',
                                    'SAINT PETER FRESCO',
                                    'MERLUZA CONGELADA',
                                    'TILAPIA CONGELADA',
                                    'CAMARAO',
                                    'PANGA CONGELADO',
                                    'POLACA CONGELADA',
                                    'CACAO CONGELADO',
                                    'SARDINHA CONGELADA',
                                    'SAINT PETER CONGELADO',
                                    'PESCADA CONGELADA',
                                    'PORQUINHO CONGELADO',
                                    'SALMAO CONGELADO',
                                    'CASQUINHA',
                                    'CASCUDO CONGELADO',
                                    'CORVINA CONGELADA',
                                    'TRILHA CONGELADA',
                                    'BACALHAU FRESCO',
                                    'BACALHAU CONGELADO',
                                    'POLACA SALGADO',
                                    'SARDINHA SALGADA',
                                    'MANJUBA SALGADO',
                                    'MERLUZA SALGADO',
                                    'CORIMBA SALGADO',
                                    'CORVINA SALGADA',
                                    'BAGRE SALGADO',
                                    'CACAO SALGADO',
                                    'CURIMBATA SALGADO',
                                    'CAMARAO SALGADO',
                                    'PETISCO BACALHAU',
                                    'EMPANADO',
                                    'BRANCO',
                                    'VERMELHO',
                                    'CAIPIRA',
                                    'CODORNA',
                                    'ESPECIAIS')
GROUP BY T.NROEMPRESA,
       T.PERIODO,
       T.SEGMENTO
