CREATE OR REPLACE VIEW NAGV_FALCONI_HIST_MOVTO_DET_GERAL AS
SELECT CD, SEQPRODUTO, INDENTRADASAIDA, ENDERECO, TIPO_MOVIMENTO, QTD_MOVTO, EMB, DTAHORMOVTO, ORIGEM_DESTINO
       /*MIN(MH) MH, MAX(MVA) MVA*/

  FROM (

SELECT DISTINCT X.CODDEPOSITANTE CD,
       X.SEQPRODUTO,
       INDENTRADASAIDA,
       SubStr( 'End. ' || fc5SelecionaEndereco(X.SEQENDERECO, 'N'), 1, 250 )||' '||S.DESCESPECIE ENDERECO,
       M.DESCRICAO TIPO_MOVIMENTO,
       X.QTDMOVTO / X.QTDEMBALAGEM QTD_MOVTO,
       E.EMBALAGEM||' '||X.QTDEMBALAGEM EMB,
       DTAHORMOVTO,
       CASE WHEN X.TIPMOVTO IN ('R','M') THEN 'End. '||fc5SelecionaEndereco(X.SEQENDERECOORIDEST, 'N')
            WHEN X.TIPMOVTO = 'T' THEN NULL
            ELSE 'Carga '||X.NROCARGA END Origem_Destino, X.SEQENDERECOMOVTO
       /*CASE WHEN MH.CODTIPATIVIDADE = 'MH' THEN T.DTAHORINITAREFA ELSE NULL END MH,
       CASE WHEN MH.CODTIPATIVIDADE = 'MV' AND TIPMV = 'A' THEN T.DTAHORFIMTAREFA ELSE NULL END MVA*/

  FROM MLO_ENDERECOMOVTO X INNER JOIN MLO_PRODUTO P ON X.SEQPRODUTO = P.SEQPRODUTO AND X.CODDEPOSITANTE = P.NROEMPRESA
                           INNER JOIN MLO_TIPOMOVIMENTO M ON M.TIPMOVTO = X.TIPMOVTO
                           INNER JOIN MLO_PRODEMBALAGEM E ON E.SEQPRODUTO = X.SEQPRODUTO AND E.QTDEMBALAGEM = X.QTDEMBALAGEM AND E.NROEMPRESA = P.NROEMPRESA
                           INNER JOIN MLO_ENDERECO ED     ON ED.SEQENDERECO = X.SEQENDERECO
                           INNER JOIN MLO_ESPECIEENDERECO S ON S.ESPECIEENDERECO = ED.ESPECIEENDERECO
                           /*INNER JOIN MLO_ATIVIDADE MH ON MH.SEQENDERECOMOVTO = X.SEQENDERECOMOVTO AND NVL(INDEXCLUSAO, 'N') = 'N' AND MH.NROEMPRESA = X.CODDEPOSITANTE*/
                           /*INNER JOIN MLO_TAREFA T ON T.SEQTAREFA = MH.SEQTAREFA AND T.NROEMPRESA = X.CODDEPOSITANTE AND LPAD(T.MESANO,4,0) = TO_CHAR(X.DTAHORMOVTO, 'MM')||TO_CHAR(X.DTAHORMOVTO, 'YY')*/

 WHERE 1=1

) GROUP BY CD, SEQPRODUTO, INDENTRADASAIDA, ENDERECO, TIPO_MOVIMENTO, QTD_MOVTO, EMB, DTAHORMOVTO, ORIGEM_DESTINO;
