-- Extração igual Analise ABC Consinco

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO; --31/05/2023
select /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/  

E.NROEMPRESA LOJA, REGEXP_SUBSTR(LC2.DESCRICAOLOCALEMPRESA, '(\S*)(\S)') as LOCAL,A.SEQPRODUTO, (SELECT DESCCOMPLETA FROM MAP_PRODUTO Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO) PRODUTO,
DECODE(B.PESAVEL, 'S','KG','N','UN') EMBALAGEM, 1 QTDEMBALAGEM,
round( sum( ( ESTQSELECAO ) / K.QTDEMBALAGEM ), 6 ) 
as QTDTOTAL,

Fc5_Divide( ( sum( ( ( C.CMULTVLRNF + C.CMULTIPI + C.CMULTDESPNF + C.CMULTICMSST + C.CMULTDESPFORANF 
- ( C.CMULTDCTOFORANF - C.CMULTIMPOSTOPRESUM ) + C.VLRDESCTRANSFCB 
- 0 )
* ( case when I2.UTILACRESCCUSTPRODRELAC = 'S' and nvl( A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO ) is not null 
 then coalesce( PR.PERCACRESCCUSTORELACVIG, F_RetAcrescCustoRelac( C.SEQPRODUTO, C.DTAENTRADASAIDA, I2.UTILACRESCCUSTPRODRELAC, PR.PERCACRESCCUSTORELACVIG ) )
 else 1
 end ) ) * ( ESTQSELECAO ) ) ), ( round( sum( ( ESTQSELECAO ) / K.QTDEMBALAGEM ), 6 ) ),
avg /*sum*/( ( ( C.CMULTVLRNF + C.CMULTIPI + C.CMULTDESPNF + C.CMULTICMSST + C.CMULTDESPFORANF 
- ( C.CMULTDCTOFORANF - C.CMULTIMPOSTOPRESUM ) + C.VLRDESCTRANSFCB 
- 0 )
* ( case when I2.UTILACRESCCUSTPRODRELAC = 'S' and nvl( A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO ) is not null 
 then coalesce( PR.PERCACRESCCUSTORELACVIG, F_RetAcrescCustoRelac( C.SEQPRODUTO, C.DTAENTRADASAIDA, I2.UTILACRESCCUSTPRODRELAC, PR.PERCACRESCCUSTORELACVIG ) )
 else 1
 end ) )* k.qtdembalagem ) )
as VLRCTOBRUTOUNIT

from MAP_PRODUTO A, MAP_FAMILIA B,
( select Y.SEQPRODUTO, Y.NROEMPRESA, Y.SEQCLUSTER , Y.SEQLOCAL,
decode( ( ESTQSELECAO ), 0, null, Y.SEQPRODUTO ) SEQPRODUTOCOMESTQ,
Y.PRECO, Y.MENORPRECO, Y.MAIORPRECO, Y.NROGONDOLA, Y.ESTQSELECAO,
Y.QTDPENDPEDCOMPRA, Y.QTDPENDPEDEXPED, 
Y.QTDRESERVADAVDA, Y.QTDRESERVADARECEB, Y.QTDRESERVADAFIXA, 
Y.MEDVDIAPROMOC, Y.MEDVDIAGERAL, Y.MEDVDIAFORAPROMOC, 
Y.CMULTVLRNF, 
Y.CMULTIPI, 
Y.CMULTCREDICMS, 
Y.CMULTICMSST, 
Y.CMULTDESPNF, 
Y.CMULTDESPFORANF, 
Y.CMULTDCTOFORANF, 
nvl( Y.CMULTIMPOSTOPRESUM, 0 ) CMULTIMPOSTOPRESUM,
nvl( Y.CMULTCREDICMSPRESUM, 0 ) CMULTCREDICMSPRESUM,
nvl( Y.CMULTCREDICMSANTECIP, 0 ) CMULTCREDICMSANTECIP,
nvl( Y.CMULTCUSLIQUIDOEMP, 0 ) CMULTCUSLIQUIDOEMP,
nvl( Y.CMULTCREDICMSEMP, 0 ) CMULTCREDICMSEMP,
nvl( Y.CMULTCREDPISEMP, 0 ) CMULTCREDPISEMP,
nvl( Y.CMULTCREDCOFINSEMP, 0 ) CMULTCREDCOFINSEMP,
nvl( Y.CMULTCREDPIS, 0 ) CMULTCREDPIS,
nvl( Y.CMULTCREDCOFINS, 0 ) CMULTCREDCOFINS,
Y.STATUSCOMPRA, Y.STATUSVENDA, 
trunc( sysdate ) - Y.DTAULTENTRADA DIASULTENTRADA, 
nvl( Y.NROSEGPRODUTO, E.NROSEGMENTOPRINC ) NROSEGPRODUTO, 
Y.LOCENTRADA, Y.LOCSAIDA,
nvl( Y.CLASSEABASTQTD, '**Sem Classificação**' ) CLASSEABASTQTD, 
nvl( Y.CLASSEABASTVLR, '**Sem Classificação**' ) CLASSEABASTVLR,
nvl( Y.CMULTVLRCOMPROR, 0 ) CMULTVLRCOMPROR,
nvl( Y.CMULTVLRDESCPISTRANSF, 0 ) CMULTVLRDESCPISTRANSF,
nvl( Y.CMULTVLRDESCCOFINSTRANSF, 0 ) CMULTVLRDESCCOFINSTRANSF,
nvl( Y.CMULTVLRDESCICMSTRANSF, 0 ) CMULTVLRDESCICMSTRANSF, 
nvl( Y.CMULTVLRDESCLUCROTRANSF, 0 ) CMULTVLRDESCLUCROTRANSF,
nvl( Y.CMULTVLRDESCIPITRANSF, 0 ) CMULTVLRDESCIPITRANSF,
nvl( Y.CMULTVLRDESCVERBATRANSF, 0 ) CMULTVLRDESCVERBATRANSF,
nvl( Y.CMULTVLRDESCDIFERENCATRANSF, 0 ) CMULTVLRDESCDIFERENCATRANSF,
nvl( Y.CMULTCREDIPI, 0 ) CMULTCREDIPI, 
trunc( sysdate ) - Y.DTAULTENTRCUSTO DIASULTENTRCUSTO,
( nvl( Y.CMULTVLRDESCPISTRANSF, 0 ) + nvl( Y.CMULTVLRDESCCOFINSTRANSF, 0 ) + nvl( Y.CMULTVLRDESCICMSTRANSF, 0 ) + nvl( Y.CMULTVLRDESCIPITRANSF, 0 )
 + nvl( Y.CMULTVLRDESCLUCROTRANSF, 0 ) + nvl( Y.CMULTVLRDESCVERBATRANSF, 0 ) + nvl( Y.CMULTVLRDESCDIFERENCATRANSF, 0 ) ) VLRDESCTRANSFCB,
Y.SEQSENSIBILIDADE, 
Y.FORMAABASTECIMENTO, case when nvl( Y.CMULTCUSLIQUIDOEMPMRL, 0 ) - nvl( Y.CMULTDCTOFORANFEMPMRL, 0 ) < 0 
 then 0 
 else nvl( Y.CMULTCUSLIQUIDOEMPMRL, 0 ) - nvl( Y.CMULTDCTOFORANFEMPMRL, 0 )
end CUSTOFISCALUNIT, 

case when nvl( ( nvl( Y.CMULTCUSLIQUIDOEMPMRL, 0 ) - nvl( Y.CMULTDCTOFORANFEMPMRL, 0 ) ) * Y.ESTQEMPRESA, 0 ) < 0 
 then 0
 else nvl( ( nvl( Y.CMULTCUSLIQUIDOEMPMRL, 0 ) - nvl( Y.CMULTDCTOFORANFEMPMRL, 0 ) ) * Y.ESTQEMPRESA, 0 ) 
end CUSTOFISCALTOTAL, 


coalesce(
 
 (select ( CUSTOA.QTDESTQINICIALEMP + CUSTOA.QTDENTRADAEMP - CUSTOA.QTDSAIDAEMP)
 from MRL_CUSTODIAEMP CUSTOA
 where CUSTOA.SEQPRODUTO = Y.SEQPRODUTO
 and CUSTOA.NROEMPRESA = Y.NROEMPRESA
 and CUSTOA.DTAENTRADASAIDA = nvl( '31-MAY-2023', sysdate ) ),

 ( select ( CUSTOA.QTDESTQINICIALEMP + CUSTOA.QTDENTRADAEMP - CUSTOA.QTDSAIDAEMP)
 from MRL_CUSTODIAEMP CUSTOA
 where CUSTOA.SEQPRODUTO = Y.SEQPRODUTO
 and CUSTOA.NROEMPRESA = Y.NROEMPRESA
 and CUSTOA.DTAENTRADASAIDA = ( select max( CUSTOB.DTAENTRADASAIDA )
 from MRL_CUSTODIAEMP CUSTOB
 where CUSTOB.SEQPRODUTO = CUSTOA.SEQPRODUTO
 and CUSTOB.NROEMPRESA = CUSTOA.NROEMPRESA
 and CUSTOB.DTAENTRADASAIDA <= nvl( '31-MAY-2023', sysdate ) ) ),

0

 ) ESTQFISCALEMPRESA,

nvl( Y.ESTQEMPRESA, 0 ) ESTQEMPRESA,
 Y.DTAENTRADASAIDA, 
nvl( Y.CMULTVLRDESPFIXA, 0 ) CMULTVLRDESPFIXA,
nvl( Y.CMULTVLRDESCFIXO, 0 ) CMULTVLRDESCFIXO,
nvl( Y.CMULTVLRDESCRESTICMSTRANSF, 0 ) CMULTVLRDESCRESTICMSTRANSF ,

nvl( Y.CMULTVERBACOMPRA, 0 ) CMULTVERBACOMPRA,
nvl( Y.CMULTVERBABONIFINCID, 0 ) CMULTVERBABONIFINCID,
nvl( Y.CMULTVERBABONIFSEMINCID, 0 ) CMULTVERBABONIFSEMINCID,
nvl( Y.CMULTVLRDESCVERBATRANSFSELLIN, 0 ) CMULTVLRDESCVERBATRANSFSELLIN,
nvl( Y.CENTRULTVLRNF, 0 ) CENTRULTVLRNF,
nvl( Y.CENTRULTIPI, 0 ) CENTRULTIPI,
nvl( Y.CENTRULTICMSST, 0 ) CENTRULTICMSST,
nvl( Y.CENTRULTDESPNF, 0 ) CENTRULTDESPNF,
nvl( Y.CENTRULTDESPFORANF, 0 ) CENTRULTDESPFORANF,
nvl( Y.CENTRULTDCTOFORANF, 0 ) CENTRULTDCTOFORANF,
nvl( Y.CENTRULTCREDICMS, 0 ) CENTRULTCREDICMS,
nvl( Y.CENTRULTCREDIPI, 0 ) CENTRULTCREDIPI,
nvl( Y.CENTRULTCREDPIS, 0 ) CENTRULTCREDPIS,
nvl( Y.CENTRULTCREDCOFINS, 0 ) CENTRULTCREDCOFINS,
nvl( Y.QENTRULTCUSTO, 0 ) QENTRULTCUSTO,
Y.INDPOSICAOCATEG,
nvl( Y.CMULTDCTOFORANFEMP, 0 ) CMULTDCTOFORANFEMP,
nvl( Y.ESTQMINIMOLOJA, 0 ) QTDESTOQUEMINIMO, 
nvl( Y.ESTQMAXIMOLOJA, 0 ) QTDESTOQUEMAXIMO,
Y.DTAULTVENDA DTAULTVENDA,
null CLNCUSTOM1, 
null CLNCUSTOM2, 
null CLNCUSTOM3, 
null CLNCUSTOM4, 
null CLNCUSTOM5, 
null CLNCUSTOM6, 
null CLNCUSTOM7, 
null CLNCUSTOM8, 
null CLSCUSTOM9, 
null CLSCUSTOM10, 
null CLSCUSTOM11, 
null CLSCUSTOM12

from 
( select CST.SEQPRODUTO, CST.DTAENTRADASAIDA, CST.NROEMPRESA, PL.SEQLOCAL, 
fEstTipLocalDtaBase( CST.NROEMPRESA, CST.SEQPRODUTO, CST.DTAENTRADASAIDA, 'L, D, T, O', PL.SEQLOCAL, 'S' ) ESTQSELECAO,
 0 QTDPENDPEDCOMPRA, 
 0 QTDPENDPEDEXPED, 
 0 QTDRESERVADAVDA, 
 0 QTDRESERVADARECEB, 
 0 QTDRESERVADAFIXA,
 W.MEDVDIAPROMOC, W.MEDVDIAGERAL, W.MEDVDIAFORAPROMOC,
 nvl( CST.CMDIAVLRNF, 0 ) CMULTVLRNF, 
 nvl( CST.CMDIAIPI, 0 ) CMULTIPI, 
 nvl( CST.CMDIACREDICMS, 0 ) CMULTCREDICMS, 
 nvl( CST.CMDIAICMSST, 0 ) CMULTICMSST, 
 nvl( CST.CMDIADESPNF, 0 ) CMULTDESPNF, 
 nvl( CST.CMDIADESPFORANF, 0 ) CMULTDESPFORANF, 
 nvl( CST.CMDIADCTOFORANF, 0 ) CMULTDCTOFORANF, 
 nvl( CST.CMULTIMPOSTOPRESUM, 0 ) CMULTIMPOSTOPRESUM,
 nvl( CST.CMDIACREDICMSPRESUM, 0 ) CMULTCREDICMSPRESUM, 
 nvl( CST.CMDIACREDICMSANTECIP, 0 ) CMULTCREDICMSANTECIP, 
 0 CMULTCREDICMSEMP, 
 0 CMULTCREDPISEMP, 
 0 CMULTCREDCOFINSEMP, 
 nvl( CST.CMDIACREDPIS, 0 ) CMULTCREDPIS, 
 nvl( CST.CMDIACREDCOFINS, 0 ) CMULTCREDCOFINS, 
 W.STATUSCOMPRA,
 W.DTAULTENTRADA,
 W.NROSEGPRODUTO, W.NROGONDOLA, W.LOCENTRADA, W.LOCSAIDA,
 nvl( decode( CST.QTDVDA, 0, FProdSegPrecoData( CST.SEQPRODUTO, null, null, CST.NROEMPRESA, CST.DTAENTRADASAIDA ), round( CST.VLRTOTALVDA / CST.QTDVDA, 2 ) ), 0 ) PRECO,
 nvl( decode( CST.QTDVDA, 0, CST.VLRTOTALVDA, round( CST.VLRTOTALVDA / CST.QTDVDA, 2 ) ), 0 ) MENORPRECO, 
 nvl( decode( CST.QTDVDA, 0, CST.VLRTOTALVDA, round( CST.VLRTOTALVDA / CST.QTDVDA, 2 ) ), 0 ) MAIORPRECO, 
 'A' STATUSVENDA,
 W.CLASSEABASTQTD, 
 W.CLASSEABASTVLR, 
 W.CMULTVLRCOMPROR,
 nvl( CST.CMDIAVLRDESCPISTRANSF, 0 ) CMULTVLRDESCPISTRANSF,
 nvl( CST.CMDIAVLRDESCCOFINSTRANSF, 0 ) CMULTVLRDESCCOFINSTRANSF,
 nvl( CST.CMDIAVLRDESCICMSTRANSF, 0 ) CMULTVLRDESCICMSTRANSF,
 W.DTAULTENTRCUSTO,
 W.INDAVALINCLUSAO,
 nvl( CST.CMDIACREDIPI, 0 ) CMULTCREDIPI,
 nvl( CST.CMDIAVLRDESCIPITRANSF, 0 ) CMULTVLRDESCIPITRANSF,
 nvl( CST.CMDIAVLRDESCLUCROTRANSF, 0 ) CMULTVLRDESCLUCROTRANSF,
 nvl( CST.CMDIAVLRDESCVERBATRANSF, 0 ) CMULTVLRDESCVERBATRANSF,
 nvl( CST.CMDIAVLRDESCDIFERENCATRANSF, 0 ) CMULTVLRDESCDIFERENCATRANSF,
 nvl( CST.CMDIAVLRDESCRESTICMSTRANSF, 0 ) CMULTVLRDESCRESTICMSTRANSF,
 0 CMULTCREDIPIEMP,
 nvl( ( CST.CMDIAVLRDESCPISTRANSF + CST.CMDIAVLRDESCCOFINSTRANSF + CST.CMDIAVLRDESCICMSTRANSF 
 + CST.CMDIAVLRDESCIPITRANSF + CST.CMDIAVLRDESCLUCROTRANSF + CST.CMDIAVLRDESCVERBATRANSF
 + CST.CMDIAVLRDESCDIFERENCATRANSF ), 0 ) VLRDESCTRANSFCB,
 W.SEQSENSIBILIDADE, W.FORMAABASTECIMENTO,
 nvl( CST.CMDIACUSLIQUIDOEMP, 0 ) CMULTCUSLIQUIDOEMP,
 nvl( CST.CMDIADCTOFORANFEMP, 0 ) CMULTDCTOFORANFEMP, 
 nvl( CST.ESTQEMPRESA, 0 ) ESTQEMPRESA, 
 nvl( CST.CMDIAVLRDESCFIXO, 0 ) CMULTVLRDESCFIXO, 
 nvl( CST.CMDIAVLRDESPFIXA, 0 ) CMULTVLRDESPFIXA, 
 W.SEQCLUSTER,
 fPadraoEmbVenda2( CST.SEQFAMILIA, '1' ) QTDEMBALAGEMSEG,
 W.ESTQLOJA, 
 W.ESTQDEPOSITO, 
 W.ESTQTROCA, 
 W.ESTQALMOXARIFADO, 
 W.ESTQOUTRO, 
 nvl( W.ESTQTERCEIRO, 0 ) ESTQTERCEIRO,
 nvl( CST.CMDIAVERBACOMPRA, 0 ) CMULTVERBACOMPRA,
 nvl( CST.CMDIAVERBABONIFINCID, 0 ) CMULTVERBABONIFINCID,
 nvl( CST.CMDIAVERBABONIFSEMINCID, 0 ) CMULTVERBABONIFSEMINCID,
 nvl( CST.CMDIAVLRDESCVERBATRANSFSELLIN, 0 ) CMULTVLRDESCVERBATRANSFSELLIN,
 nvl( W.CENTRULTVLRNF, 0 ) CENTRULTVLRNF,
 nvl( W.CENTRULTIPI, 0 ) CENTRULTIPI,
 nvl( W.CENTRULTICMSST, 0 ) CENTRULTICMSST,
 nvl( W.CENTRULTDESPNF, 0 ) CENTRULTDESPNF,
 nvl( W.CENTRULTDESPFORANF, 0 ) CENTRULTDESPFORANF,
 nvl( W.CENTRULTDCTOFORANF, 0 ) CENTRULTDCTOFORANF,
 nvl( W.CENTRULTCREDICMS, 0 ) CENTRULTCREDICMS,
 nvl( W.CENTRULTCREDIPI, 0 ) CENTRULTCREDIPI,
 nvl( W.CENTRULTCREDPIS, 0 ) CENTRULTCREDPIS,
 nvl( W.CENTRULTCREDCOFINS, 0 ) CENTRULTCREDCOFINS,
 nvl( W.QENTRULTCUSTO, 0 ) QENTRULTCUSTO,
 W.INDPOSICAOCATEG,
 nvl( W.ESTQMINIMOLOJA, 0 ) ESTQMINIMOLOJA, 
 nvl( W.ESTQMAXIMOLOJA, 0 ) ESTQMAXIMOLOJA,
 W.DTAULTVENDA DTAULTVENDA,
 nvl( W.CMULTCUSLIQUIDOEMP, 0 ) CMULTCUSLIQUIDOEMPMRL,
 nvl( W.CMULTDCTOFORANFEMP, 0 ) CMULTDCTOFORANFEMPMRL

from ( 
 select rank( ) over ( partition by Y.NROEMPRESA, Y.SEQPRODUTO order by Y.NROEMPRESA, Y.SEQPRODUTO, Y.DTAENTRADASAIDA desc ) as S_RANK,
 Y.SEQPRODUTO,
 Y.DTAENTRADASAIDA,
 Y.NROEMPRESA,
 Y.QTDESTQINICIAL,
 Y.QTDENTRADA,
 Y.QTDSAIDA,
 nvl( ( Y.QTDESTQINICIAL + Y.QTDENTRADA - Y.QTDSAIDA),0 ) as ESTQEMPRESA,
 nvl( Y.QTDSAIDAMEDVENDA, 0 ) as QTDSAIDAMEDVENDA,
 Y.QENTRCUSTO,
 Y.CENTRVLRNF,
 Y.CENTRIPI,
 nvl( Y.CENTRCREDIPI, 0 ) as CENTRCREDIPI,
 Y.CENTRCREDICMS,
 Y.CENTRICMSST,
 Y.CENTRDESPNF,
 Y.CENTRDESPFORANF,
 Y.CENTRDCTOFORANF,
 nvl( Y.CENTRCREDICMSPRESUM, 0 ) as CENTRCREDICMSPRESUM,
 nvl( Y.CENTRCREDICMSANTECIP, 0 ) as CENTRCREDICMSANTECIP,
 nvl( Y.CENTRCREDPIS, 0 ) as CENTRCREDPIS,
 nvl( Y.CENTRCREDCOFINS, 0 ) as CENTRCREDCOFINS,
 Y.CMDIAVLRNF,
 Y.CMDIAIPI,
 Y.CMDIACREDICMS,
 Y.CMDIAICMSST,
 Y.CMDIADESPNF,
 Y.CMDIADESPFORANF,
 Y.CMDIADCTOFORANF,
 nvl( Y.CMDIACREDICMSPRESUM, 0 ) as CMDIACREDICMSPRESUM,
 nvl( Y.CMDIACREDICMSANTECIP, 0 ) as CMDIACREDICMSANTECIP,
 nvl( Y.CMDIACREDPIS, 0 ) as CMDIACREDPIS,
 nvl( Y.CMDIACREDCOFINS, 0 ) as CMDIACREDCOFINS,
 Y.QTDCOMPRA,
 Y.VLRTOTALCOMPRA,
 Y.QTDVDA,
 Y.VLRTOTALVDA,
 Y.VLRCUSLIQUIDOVDA,
 nvl( Y.VLRCUSBRUTOVDA, 0 ) as VLRCUSBRUTOVDA,
 Y.VLRICMSVDA,
 Y.VLRIMPOSTOVDA,
 Y.VLRDESPESAVDA,
 Y.VLRCOMISSAOVDA,
 nvl( Y.VLRDESCFORANFVDA, 0 ) as VLRDESCFORANFVDA,
 nvl( Y.VLRIPIVDA, 0 ) as VLRIPIVDA,
 nvl( Y.VLRISSVDA, 0 ) as VLRISSVDA,
 nvl( Y.VLRPISVDA, 0 ) as VLRPISVDA,
 nvl( Y.VLRCOFINSVDA, 0 ) as VLRCOFINSVDA,
 Y.NRONFCUPOMEMITIDO,
 Y.QTDVERBAVDA,
 Y.VLRVERBAVDA,
 Y.QTDVERBAOUTSAI,
 Y.VLRVERBAOUTSAI,
 Y.SEQFAMILIA,
 nvl( Y.CMDIACREDIPI, 0 ) as CMDIACREDIPI,
 nvl( Y.CMDIAVLRDESPFIXA, 0 ) as CMDIAVLRDESPFIXA,
 nvl( Y.CMDIAVLRDESCFIXO, 0 ) as CMDIAVLRDESCFIXO,
 nvl( Y.CMDIACUSLIQUIDOEMP, 0 ) as CMDIACUSLIQUIDOEMP,
 nvl( Y.CMDIADCTOFORANFEMP, 0 ) as CMDIADCTOFORANFEMP,
 nvl( Y.CMDIAVLRDESCDIFERENCATRANSF, 0 ) as CMDIAVLRDESCDIFERENCATRANSF,
 nvl( Y.CMDIAVLRDESCVERBATRANSF, 0 ) as CMDIAVLRDESCVERBATRANSF,
 nvl( Y.CMDIAVLRDESCLUCROTRANSF, 0 ) as CMDIAVLRDESCLUCROTRANSF,
 nvl( Y.CMDIAVLRDESCIPITRANSF, 0 ) as CMDIAVLRDESCIPITRANSF,
 nvl( Y.CMDIAVLRDESCICMSTRANSF, 0 ) as CMDIAVLRDESCICMSTRANSF,
 nvl( Y.CMDIAVLRDESCCOFINSTRANSF, 0 ) as CMDIAVLRDESCCOFINSTRANSF,
 nvl( Y.CMDIAVLRDESCPISTRANSF, 0 ) as CMDIAVLRDESCPISTRANSF,
 nvl( Y.CMDIAVLRDESCRESTICMSTRANSF, 0 ) as CMDIAVLRDESCRESTICMSTRANSF,
 NVL(Y.CMDIAVERBACOMPRA, 0) as CMDIAVERBACOMPRA,
 NVL(Y.CMDIAVERBABONIFINCID, 0) as CMDIAVERBABONIFINCID,
 NVL(Y.CMDIAVERBABONIFSEMINCID, 0) as CMDIAVERBABONIFSEMINCID,
 NVL(Y.CMDIAVLRDESCVERBATRANSFSELLIN, 0) as CMDIAVLRDESCVERBATRANSFSELLIN,
 NVL( Y.CMULTIMPOSTOPRESUM, 0 ) as CMULTIMPOSTOPRESUM
 from MRL_CUSTODIA Y
 where Y.NROEMPRESA in ( 1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,57,301,501,502,503,504,505,506,600,601,602,603,999 )
 and Y.DTAENTRADASAIDA between trunc( to_date( '31-MAY-2023'), 'MM' ) and '31-MAY-2023'
 
 ) CST, MRL_PRODUTOEMPRESA W , MRL_PRODLOCAL PL

where CST.S_RANK = 1
and CST.NROEMPRESA in ( 1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,57,301,501,502,503,504,505,506,600,601,602,603,999 )
and CST.DTAENTRADASAIDA between trunc( to_date( '31-MAY-2023'), 'MM' ) and '31-MAY-2023'
and W.NROEMPRESA = CST.NROEMPRESA
and W.SEQPRODUTO = CST.SEQPRODUTO 
 and pl.nroempresa (+) = w.nroempresa 
 and pl.seqproduto (+) = w.seqproduto 
) Y , MAX_EMPRESA E 
where E.NROEMPRESA = Y.NROEMPRESA 
 

 

) C, 
MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E, MAD_PARAMETRO J3, 
MAX_DIVISAO I2, MAP_CLASSIFABC Z2, MAD_FAMSEGMENTO H, MAP_REGIMETRIBUTACAO RT
 , MAP_TRIBUTACAOUF T3 , MAPV_PISCOFINSTRIBUT SS , MRLV_LOCALABC LC2 , MAD_SEGMENTO SE, MAP_PRODACRESCCUSTORELAC PR, MAP_FAMDIVCATEG FDC,map_categoria cat
where A.SEQPRODUTO = C.SEQPRODUTO
and B.SEQFAMILIA = A.SEQFAMILIA 
and C.NROEMPRESA in ( 1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,57,301,501,502,503,504,505,506,600,601,602,603,999 )
and D.SEQFAMILIA = A.SEQFAMILIA 
and D.NRODIVISAO = E.NRODIVISAO
and K.SEQFAMILIA = D.SEQFAMILIA 
and K.QTDEMBALAGEM = 1
and E.NROEMPRESA = C.NROEMPRESA
and J3.NROEMPRESA = E.NROEMPRESA 
and I2.NRODIVISAO = E.NRODIVISAO 
and I2.NRODIVISAO = D.NRODIVISAO
and Z2.NROSEGMENTO = H.NROSEGMENTO 
and Z2.CLASSIFCOMERCABC = H.CLASSIFCOMERCABC 
and Z2.NROSEGMENTO = SE.NROSEGMENTO 
and A.SEQPRODUTOBASE IS NULL
 
and T3.NROTRIBUTACAO = D.NROTRIBUTACAO 
and T3.UFEMPRESA = nvl( E.UFFORMACAOPRECO, E.UF ) 
and T3.UFCLIENTEFORNEC = E.UF
and T3.TIPTRIBUTACAO = decode( I2.TIPDIVISAO, 'V', 'SN', 'SC' ) 
and T3.NROREGTRIBUTACAO = nvl( E.NROREGTRIBUTACAO, 0 ) 
and a.seqfamilia = fdc.seqfamilia
and cat.nrodivisao = e.nrodivisao
and fdc.seqcategoria = cat.seqcategoria
and fdc.nrodivisao = cat.nrodivisao
and b.seqfamilia = a.seqfamilia
and cat.nivelhierarquia = 1
and cat.statuscategor in ('A','F')
and fdc.status = 'A'
and cat.tipcategoria = 'M' 
and C.SEQPRODUTO = PR.SEQPRODUTO(+) 
and C.DTAENTRADASAIDA = PR.DTAMOVIMENTACAO(+) 
and SS.NROEMPRESA = E.NROEMPRESA
and SS.NROTRIBUTACAO = T3.NROTRIBUTACAO 
and SS.UFEMPRESA = T3.UFEMPRESA
and SS.UFCLIENTEFORNEC = T3.UFCLIENTEFORNEC
and SS.TIPTRIBUTACAO = T3.TIPTRIBUTACAO
and SS.NROREGTRIBUTACAO = T3.NROREGTRIBUTACAO 
and SS.SEQFAMILIA = B.SEQFAMILIA and LC2.SEQLOCAL = C.SEQLOCAL
 and LC2.NROEMPRESA = C.NROEMPRESA and LC2.TIPLOCAL in ('L',' D', 'T','O') and H.SEQFAMILIA = A.SEQFAMILIA and H.NROSEGMENTO = E.NROSEGMENTOPRINC and T3.NROREGTRIBUTACAO = RT.NROREGTRIBUTACAO

and ( ESTQSELECAO ) != 0 
group by E.NROEMPRESA, A.SEQPRODUTO,
E.NOMEREDUZIDO,
LC2.SKLOCAL,
LC2.DESCRICAOLOCALEMPRESA, B.PESAVEL,
E.NOMEREDUZIDO || ' : ' || LC2.DESCRICAOLOCALEMPRESA,
to_number( null ),
to_number( null ),
to_number( null ),
null
having round( round( sum( ( ESTQSELECAO ) / K.QTDEMBALAGEM ), 6 ) , 6 ) != 0

ORDER BY 3,1,2
