ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;
  
SELECT DTAVDA DATA_VENDA, TO_CHAR(TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15), 'HH24:MI')||' - '||
       TO_CHAR((TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15) + '0.011'), 'HH24:MI')
       AS QUARTO_DE_HORA,
       NROEMPRESA, SUM(X.QTDITEM) QTDITEM, SUM(X.VLRITEM)-- * SUM(X.QTDITEM) 
       FATURAMENTO, COUNT(DISTINCT NRODOCTO) QTD_CUPONS
       
FROM MAXV_ABCDISTRIBBASE X

 WHERE X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911) 
   AND X.NROEMPRESA = 1 AND TRUNC(X.DTAVDA) = TRUNC(SYSDATE) -- AND X.SEQPRODUTO IN (455190,484480,227033,227031)
 
GROUP BY TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15),
      DTAVDA, NROEMPRESA
      
      ORDER BY TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15);
