ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;
  
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ CATEGORIAN3, DTAVDA DATA_VENDA, 
       TO_CHAR( TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15), 'HH24:MI')||' - '||
       TO_CHAR((TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15) + '0.011'), 'HH24:MI')
    AS QUARTO_DE_HORA,
       NROEMPRESA, SUM(X.QTDITEM) QTDITEM, TO_CHAR(SUM(X.VLRITEM), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''')FATURAMENTO, 
       COUNT(DISTINCT NRODOCTO) QTD_CUPONS
       
FROM CONSINCO.MAXV_ABCDISTRIBBASE_NAG X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO
                                        INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA

 WHERE X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911) 
   AND NROEMPRESA IN (:LS2)
   AND TRUNC(X.DTAVDA) BETWEEN :DT1 AND :DT2
   AND C.CATEGORIAN3 = :LS1
 
GROUP BY TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15),
      DTAVDA, NROEMPRESA, CATEGORIAN3
      
      ORDER BY NROEMPRESA, TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15);  
      
      SELECT DISTINCT CATEGORIAN3 FROM DIM_CATEGORIA@CONSINCODW WHERE CATEGORIAN3 IS NOT NULL
