ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT C.NUMERONF, X.NROPEDIDOSUPRIM NROPEDIDO, B.SEQPRODUTO, FI.QUANTIDADE QTD_NF,
       DECODE(F.TIPPEDIDOCOMPRA, 'T','Transferencia','C','Compra','E','Bonif','Outros') TIPO,
       A.NROEMPRESA LOJA, TO_CHAR(A.DTAHORGERACAO, 'DD/MM/YYYY') DATA,
       CASE WHEN YY.CODINCONSIST IS NOT NULL THEN 'Sim' ELSE 'Não' END Liberado_Por_Senha,
       DECODE (nvl(B.SEQATIVIDADEUSUARIO, 0), 0, 'MANUAL', 'COLETOR') AS TIPO_CONFERENCIA,
       YY.CODINCONSIST COD_INCONSISTENCIA,
       YY.DESCRICAO INCOSISTENCIA,
       YY.USUAUTORIZOU AUTORIZADOR,
       U.NOME NOME_AUTORIZADOR,
       TO_CHAR(YY.DTAAUTORIZOU,'DD/MM/YYYY')  DTA_AUTORIZACAO,
       UPPER(F.JUSTIFACEITEPEDIDO) JUSTIFICATIVA,
       CASE WHEN DV.NUMERONF IS NULL THEN NULL ELSE 'NF: '||DV.NUMERONF||CASE WHEN DI.SEQPRODUTO IS NULL THEN NULL ELSE ' - Item: '||DI.SEQPRODUTO END END DEV, DI.QUANTIDADE QTD_DEV
                                                                                                                                                                                                                                                                                                                                                                                
FROM   MAD_CARGARECEB A LEFT JOIN MAD_CARGARECEBNF C ON C.NROCARGARECEB = A.NROCARGARECEB AND C.NROEMPRESA = A.NROEMPRESA
                        LEFT JOIN MLF_NOTAFISCAL   F ON F.NROINTERNORECEB = A.NROCARGARECEB AND F.NUMERONF = C.NUMERONF
                        LEFT JOIN MLF_NFITEM      FI ON FI.SEQAUXNOTAFISCAL = F.SEQAUXNOTAFISCAL  
                        LEFT JOIN MSU_PSITEMRECEBIDO X ON X.SEQAUXNOTAFISCAL = F.SEQAUXNOTAFISCAL AND X.NROEMPRESA = F.NROEMPRESA
                       INNER JOIN MAX_CODGERALOPER Z ON Z.CODGERALOPER = F.CODGERALOPER AND Z.TIPCGO = 'E' AND Z.TIPDOCFISCAL != 'D'
                        LEFT JOIN MAD_CARGARECITEM B ON A.NROCARGARECEB = B.NROCARGARECEB AND A.NROEMPRESA = B.NROEMPRESA AND B.SEQPRODUTO = FI.SEQPRODUTO
                        LEFT JOIN MLF_AUXNFINCONSISTENCIA YY ON YY.SEQAUXNOTAFISCAL = F.SEQAUXNOTAFISCAL AND YY.SEQAUXNFITEM = FI.SEQITEMNF
                        LEFT JOIN GE_USUARIO U ON (U.CODUSUARIO = YY.USUAUTORIZOU)
                        LEFT JOIN MLF_NOTAFISCAL  DV ON DV.SEQNFREF = F.SEQNF
                        LEFT JOIN MLF_NFITEM      DI ON DI.SEQNF = DV.SEQNF AND DI.SEQPRODUTO = FI.SEQPRODUTO 
                                                              
WHERE  DTAHORGERACAO BETWEEN :DT1 AND :DT2
  AND  A.NROCARGARECEB = B.NROCARGARECEB 
  AND  A.NROEMPRESA = B.NROEMPRESA 
  AND  F.MODELONF != 0
  AND  A.NROEMPRESA IN (#LS1)
  
ORDER 
   BY A.NROEMPRESA, C.NUMERONF, B.SEQPRODUTO

-- V2


SELECT DISTINCT C.NUMERONF, X.NROPEDIDOSUPRIM NROPEDIDO, B.SEQPRODUTO, FI.QUANTIDADE QTD_NF,
       DECODE(F.TIPPEDIDOCOMPRA, 'T','Transferencia','C','Compra','E','Bonif','Outros') TIPO,
       A.NROEMPRESA LOJA, TO_CHAR(A.DTAHORGERACAO, 'DD/MM/YYYY') DATA,
       CASE WHEN YY.CODINCONSIST IS NOT NULL THEN 'Sim' ELSE 'Não' END Liberado_Por_Senha,
       DECODE (nvl(B.SEQATIVIDADEUSUARIO, 0), 0, 'MANUAL', 'COLETOR') AS TIPO_CONFERENCIA,
       YY.CODINCONSIST COD_INCONSISTENCIA,
       YY.DESCRICAO INCOSISTENCIA,
       YY.USUAUTORIZOU AUTORIZADOR,
       U.NOME NOME_AUTORIZADOR,
       TO_CHAR(YY.DTAAUTORIZOU,'DD/MM/YYYY')  DTA_AUTORIZACAO,
       CASE WHEN U.NOME IS NULL THEN NULL ELSE UPPER(F.JUSTIFACEITEPEDIDO) END JUSTIFICATIVA,
       CASE WHEN DI.NUMERONF IS NULL THEN NULL ELSE 'NF: '||DI.NUMERONF||CASE WHEN DI.SEQPRODUTO IS NULL THEN NULL ELSE ' - Item: '||DI.SEQPRODUTO END END DEV, DI.QUANTIDADE QTD_DEV
                                                                                                                                                                                                                                                                                                                                                                                
FROM   MAD_CARGARECEB A LEFT JOIN MAD_CARGARECEBNF C   ON C.NROCARGARECEB     = A.NROCARGARECEB    AND C.NROEMPRESA = A.NROEMPRESA
                        LEFT JOIN MLF_NOTAFISCAL   F   ON F.NROINTERNORECEB   = A.NROCARGARECEB    AND F.NUMERONF = C.NUMERONF
                        LEFT JOIN MLF_NFITEM      FI   ON FI.SEQAUXNOTAFISCAL = F.SEQAUXNOTAFISCAL  
                        LEFT JOIN MSU_PSITEMRECEBIDO X ON X.SEQAUXNOTAFISCAL  = F.SEQAUXNOTAFISCAL AND X.NROEMPRESA = F.NROEMPRESA AND X.SEQPRODUTO = FI.SEQPRODUTO
                       INNER JOIN MAX_CODGERALOPER Z   ON Z.CODGERALOPER      = F.CODGERALOPER     AND Z.TIPCGO = 'E' AND Z.TIPDOCFISCAL != 'D'
                        LEFT JOIN MAD_CARGARECITEM B   ON A.NROCARGARECEB     = B.NROCARGARECEB    AND A.NROEMPRESA = B.NROEMPRESA AND B.SEQPRODUTO = FI.SEQPRODUTO
                        LEFT JOIN MLF_AUXNFINCONSISTENCIA YY ON YY.SEQAUXNFITEM = FI.SEQITEMNF     AND YY.SEQAUXNOTAFISCAL = F.SEQAUXNOTAFISCAL 
                        LEFT JOIN GE_USUARIO       U   ON U.CODUSUARIO        = YY.USUAUTORIZOU
                        LEFT JOIN MLF_NFITEM      DI   ON DI.SEQNFREF         = FI.SEQNF           AND DI.SEQPRODUTO = FI.SEQPRODUTO AND NOT EXISTS (SELECT 1 FROM MLF_NOTAFISCAL CC WHERE CC.SEQNF = DI.SEQNF AND STATUSNF = 'C')
                                                              
WHERE  1=1 
  AND  DTAHORGERACAO BETWEEN :DT1 AND :DT2
  AND  A.NROCARGARECEB = B.NROCARGARECEB 
  AND  A.NROEMPRESA = B.NROEMPRESA 
  AND  F.MODELONF != 0
  AND  A.NROEMPRESA IN (#LS1)
  AND  F.STATUSNF != 'C'
  
ORDER 
   BY A.NROEMPRESA, C.NUMERONF, B.SEQPRODUTO
