SELECT  TO_CHAR(A.DTAOPERACAO, 'MM/YYYY') AS DATA,
        A.NROEMPRESA,
        A.SEQPRODUTO,
        B.DESCCOMPLETA,
       (SELECT X.FANTASIA FROM CONSINCO.GE_PESSOA X WHERE X.SEQPESSOA = (SELECT X.SEQFORNECEDOR FROM CONSINCO.MAP_FAMFORNEC X WHERE X.SEQFAMILIA = B.SEQFAMILIA AND X.PRINCIPAL = 'S')) FORNECEDOR_PRINCIPAL,
        CASE WHEN (SELECT PESAVEL FROM CONSINCO.MAP_FAMILIA X WHERE X.SEQFAMILIA = B.SEQFAMILIA) = 'S' THEN 'KG' ELSE 'UN' END EMBALAGEM,
        1 QTDEMBALAGEM,
        SUM(A.QTDLANCTO) QTDLANCTO,
        DECODE(A.TIPLANCTO, 'S', 'SAIDA', 'ENTRADA') AS LANCTO,
        ROUND(SUM(A.VLRTOTLANCTOBRT),2) VLRTOTALCTOBRT ,
        F.LOCAL,
        DECODE(D.TIPUSO,
              'I',
              DECODE(NVL(D.TIPCLASSINTERNO, 'N'),
                     'C','CONSUMO PRÓPRIO',
                     'P','PERDA OU QUEBRA',
                     'R','FURTO OU ROUBO',
                     'A','AVARIA',
                     'NORMAL'),
              NULL) AS TIPOLANCT, A.CODGERALOPER ||'-'|| D.DESCRICAO AS CGO
        
   FROM  CONSINCO.FATO_MOVTOESTQ A INNER JOIN MAP_PRODUTO      B ON A.SEQPRODUTO = B.SEQPRODUTO 
                                   INNER JOIN MAX_CODGERALOPER D ON A.CODGERALOPER = D.CODGERALOPER
                                   INNER JOIN MRL_LOCAL        F ON A.SEQLOCAL = F.SEQLOCAL AND A.NROEMPRESA = F.NROEMPRESA

  WHERE 1=1
  -- Teste
    AND A.DTAOPERACAO BETWEEN DATE '2022-05-01' AND DATE '2023-05-31'
    /*AND A.SEQPRODUTO = 5500
    AND A.NROEMPRESA = 1*/
    
    AND A.CODGERALOPER IN (SELECT CODGERALOPER FROM CONSINCO.MAX_CODGERALOPER Z WHERE  NVL(TIPDOCFISCAL, 'X') NOT IN ('C') AND Z.GERALTERACAOESTQ = 'S')
    
  GROUP BY TO_CHAR(A.DTAOPERACAO, 'MM/YYYY'), A.NROEMPRESA, A.SEQPRODUTO, B.DESCCOMPLETA, B.SEQFAMILIA, A.TIPLANCTO, F.LOCAL, D.TIPUSO, A.CODGERALOPER, D.DESCRICAO, D.TIPCLASSINTERNO
  
  ORDER BY 1,2,3
