SELECT TO_CHAR(X.DTAESTOQUE,'DD/MM/YYYY') DATA,
       X.NROEMPRESA LOJA,
       X.SEQPRODUTO SEQPRODUTO,
       Y.DESCCOMPLETA PRODUTO,
       CASE WHEN Z.PESAVEL = 'S' THEN 'KG' ELSE 'UN' END EMBALAGEM,
       1 QTDEMBALAGEM,
       TO_CHAR((X.QTDESTQLOJA),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')     ESTOQUE_LOJA,
       TO_CHAR((X.QTDESTQDEPOSITO),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ESTOQUE_DEPOSITO,
       TO_CHAR((X.QTDESTQTROCA),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')    ESTOQUE_AVARIA,
       TO_CHAR((X.QTDESTQOUTRO),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')    ESTOQUE_OCORRENCIAS,
      -- TO_CHAR(X.VLRPRECOVDA,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')     PRECO_VENDA,
       TO_CHAR((X.VLRCTOLIQUIDO),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')   CUSTO_LIQUIDO,
       TO_CHAR((X.VLRCTOBRUTO),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')     CUSTO_BRUTO
       
  FROM CONSINCO.FATO_ESTOQUE X INNER JOIN CONSINCO.MAP_PRODUTO Y ON (X.SEQPRODUTO = Y.SEQPRODUTO)
                               INNER JOIN CONSINCO.MAP_FAMILIA Z ON Z.SEQFAMILIA = Y.SEQFAMILIA
                               
 WHERE X.DTAESTOQUE = DATE '2022-04-30' OR X.DTAESTOQUE = DATE '2023-04-30' OR X.DTAESTOQUE = DATE '2022-05-31' OR X.DTAESTOQUE = DATE '2023-05-31'
   
--GROUP BY TO_CHAR(X.DTAESTOQUE,'DD/MM/YYYY'), NROEMPRESA, X.SEQPRODUTO, DESCCOMPLETA, PESAVEL

ORDER BY 1,2,3
