SELECT      TO_CHAR(DTAOPERACAO, 'MM') MES, X.NROEMPRESA LOJA, 
            NVL(SUM(X.CONTDOCTOPROMOC),0) QTD_CUPONS_VDAPROMOC, NVL(SUM(X.QTDPROMOC),0) QTD_VDAITENS_PROMOC,
            NVL(SUM(X.CONTDOCTO),0) QTD_CUPONS_VDANORMAL,       NVL(SUM(X.QTDOPERACAO),0) QTD_VDAITENS_NORMAL,
            NULL,                                               
            TO_CHAR(NVL(SUM(X.VLRPROMOC),0),   'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_VDA_PROMOC,
            TO_CHAR(NVL(SUM(X.VLROPERACAO),0), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_VDA_NORMAL,        
            NULL,
            TO_CHAR(NVL(SUM(X.VVLRCTOBRUTO),0),'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_CTOBRUTO_NORMAL,     
            TO_CHAR(NVL(SUM(X.VLRVERBAVDA),0), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VERBAS_COMERCIAIS,                    
            NULL,                                               
            TO_CHAR(NVL(SUM(X.VVLRCTOLIQUIDO),0), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_CTOLIQ_NORMAL, 
            TO_CHAR(ROUND(SUM(X.VLROPERACAO) - SUM(X.VVLRCTOLIQUIDO) - (SUM(X.VLRICMS) + SUM(X.VLRIPI) + SUM(X.VLRCOFINS) 
            + SUM(X.VVLRIMPOSTOSAIDA) + SUM(X.VLRDESPOPERACIONALITEM) + SUM(X.VLRCOMISSAO)),2),
                                               'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_LUCRAT_PERIODO

FROM FATOG_VENDAMES X LEFT JOIN DIM_CATEGORIA XD
WHERE X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)

AND DTAOPERACAO BETWEEN TRUNC (SYSDATE,'MM')
                    AND TRUNC(LAST_DAY(SYSDATE))
                    
GROUP BY TO_CHAR(DTAOPERACAO, 'MM'), X.NROEMPRESA

ORDER BY 1
