ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       TO_CHAR(X.DTARECEBIMENTO, 'DD/MM/YYYY') AS DATA_RECEBIMENTO,
       X.NROEMPRESA AS LOJA_RECEBIMENTO, X.NUMERONF NF,
       X.SEQPESSOA AS CD_EXPEDICAO, XI.SEQPRODUTO SEQPRODUTO,
       XI.QUANTIDADE AS QTD_RECEBIDA_UN,
       XI.EMBALAGEM || ' ' || LPAD(NVL(K.QTDRECEBIDA, XI.QUANTIDADE) / XI.QTDEMBALAGEM, 5, 0) ||
       ' - ' || LPAD(XI.QTDEMBALAGEM, 5, 0) AS QTD_RECEBIDA_CXS,
       K.NROPEDIDOSUPRIM AS NRO_PEDIDO_ABASTECIMENTO, Z.NROPEDFORNECEDOR AS NRO_PEDIDO_TRANSFERENCIA,
       (SELECT L.NROPEDFORNECEDOR
          FROM MSU_PEDIDOSUPRIM L
         WHERE L.NROPEDIDOSUPRIM = Z.NROPEDFORNECEDOR) NRO_PEDIDO_COMPRA,
       TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DATA_FATURAMENTO
       
  FROM MSU_PEDIDOSUPRIM Z LEFT JOIN MSU_PSITEMRECEBIDO K ON Z.NROPEDIDOSUPRIM = K.NROPEDIDOSUPRIM AND Z.NROEMPRESA = K.NROEMPRESA AND Z.CENTRALLOJA = K.CENTRALLOJA
                          LEFT JOIN MLF_NOTAFISCAL     X ON X.SEQAUXNOTAFISCAL = K.SEQAUXNOTAFISCAL AND X.NROEMPRESA = K.NROEMPRESA
                          LEFT JOIN MLF_NFITEM        XI ON X.SEQNF = XI.SEQNF AND XI.SEQPRODUTO = K.SEQPRODUTO
                       
 WHERE EXISTS (SELECT 1
                 FROM DWNAGT_DADOSEMPRESA@BI Z 
                WHERE Z.TIPO = 'CD'
                  AND Z.NROEMPRESA = Z.NROEMPRESA)
                  
   AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2

UNION   

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       NULL DATA_RECEBIMENTO,
       X.NROEMPRESA AS LOJA_RECEBIMENTO, X.NUMERONF NF,
       X.SEQPESSOA AS CD_EXPEDICAO, XI.SEQPRODUTO SEQPRODUTO,
       XI.QUANTIDADE AS QTD_RECEBIDA_UN,
       EM.EMBALAGEM || ' ' || LPAD(XI.QUANTIDADE / XI.QTDEMBALAGEM, 5, 0) ||
       ' - ' || LPAD(XI.QTDEMBALAGEM, 5, 0) AS QTD_RECEBIDA_CXS,
       R.NROPEDIDOSUPRIM AS NRO_PEDIDO_ABASTECIMENTO, Z.NROPEDFORNECEDOR AS NRO_PEDIDO_TRANSFERENCIA,
       (SELECT L.NROPEDFORNECEDOR
          FROM MSU_PEDIDOSUPRIM L
         WHERE L.NROPEDIDOSUPRIM = Z.NROPEDFORNECEDOR) NRO_PEDIDO_COMPRA,
       TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DATA_FATURAMENTO
       
  FROM MSU_PEDIDOSUPRIM Z   LEFT JOIN MSU_PSITEMRECEBER  R ON R.NROPEDIDOSUPRIM = Z.NROPEDIDOSUPRIM AND R.NROEMPRESA = Z.NROEMPRESA AND Z.CENTRALLOJA = R.CENTRALLOJA
                            LEFT JOIN MLF_AUXNFITEM     XI ON XI.NROPEDIDOSUPRIM = Z.NROPEDIDOSUPRIM AND XI.SEQPRODUTO = R.SEQPRODUTO
                            LEFT JOIN MLF_AUXNOTAFISCAL X  ON X.SEQAUXNOTAFISCAL = XI.SEQAUXNOTAFISCAL AND X.NROEMPRESA = Z.NROEMPRESA 
                            LEFT JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                            LEFT JOIN MAP_FAMEMBALAGEM EM ON EM.SEQFAMILIA = P.SEQFAMILIA AND EM.QTDEMBALAGEM = XI.QTDEMBALAGEM
  
 WHERE EXISTS (SELECT 1
                 FROM DWNAGT_DADOSEMPRESA@BI Z
                WHERE Z.TIPO = 'CD'
                  AND Z.NROEMPRESA = Z.NROEMPRESA)
                  
   AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2;
