ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT A.NROEMPRESA, A.SEQPRODUTO CODIGO_PRODUTO, DESCCOMPLETA PRODUTO, C.CODACESSO EAN,
       TO_CHAR(A.DTAULTENTRADA, 'DD/MM/YYYY') DTAULTENTRADA,
       TO_CHAR(A.DTAULTCOMPRA,  'DD/MM/YYYY') DTAULTCOMPRA,
       DECODE(A.STATUSCOMPRA, 'A', 'Ativo', 'S', 'Suspenso', 'I', 'Inativo') STATUSCOMPRA,
       DECODE(G.STATUSVENDA, 'A', 'Ativo', 'I', 'Inativo') STATUSVENDA,
       CA.CATEGORIAN1, CA.CATEGORIAN2, CA.CATEGORIAN3, CA.CATEGORIAN4, CA.CATEGORIAN5,
       E.ALTURA, E.LARGURA, E.PROFUNDIDADE, D.PADRAOEMBCOMPRA

  FROM MRL_PRODUTOEMPRESA A INNER JOIN MAP_PRODUTO B      ON A.SEQPRODUTO  = B.SEQPRODUTO
                            LEFT JOIN  MAP_PRODCODIGO C   ON C.SEQPRODUTO  = A.SEQPRODUTO AND C.TIPCODIGO = 'E'
                            INNER JOIN MAX_EMPRESA M      ON M.NROEMPRESA  = A.NROEMPRESA
                            INNER JOIN MRL_PRODEMPSEG G   ON G.SEQPRODUTO  = A.SEQPRODUTO AND G.NROEMPRESA = A.NROEMPRESA AND G.NROSEGMENTO = M.NROSEGMENTOPRINC
                            LEFT JOIN  DIM_CATEGORIA CA   ON CA.SEQFAMILIA = B.SEQFAMILIA
                            LEFT JOIN  MAP_FAMEMBALAGEM E ON E.SEQFAMILIA  = B.SEQFAMILIA AND E.QTDEMBALAGEM = 1
                            INNER JOIN MAP_FAMDIVISAO D   ON D.SEQFAMILIA  = B.SEQFAMILIA 
                            
WHERE A.NROEMPRESA IN (#LS1)
