ALTER SESSION SET current_schema = CONSINCO;

SELECT G.FANTASIA,-- :DT1 DATA, :LS1 BANCO, 
       NULL DATA, NULL BANCO,
       SALDO_INICIAL, VINCULADA, CARRO_FORTE, PAGTO_BCO, 
       DEPOSITOS, TRIBUTOS, RISCO_SACADO, TROCO, TRANSFERENCIAS, SALDO, TOTAL_DEBITADO
FROM GE_EMPRESA G LEFT JOIN (

SELECT DISTINCT NROEMPRESA, DTAOPERACAO, REGEXP_SUBSTR(C.DESCRICAO, '(\S*)(\s)') BANCO, NULL SALDO_INICIAL,
        TO_CHAR((SELECT SUM(VLROPERACAO) FROM FI_TITOPERACAO AA, FI_OPERACAO BB, FI_CTACORRENTE CC
                WHERE  AA.CODOPERACAO = BB.CODOPERACAO
                AND    AA.SEQCTACORRENTE = CC.SEQCTACORRENTE
                AND    BB.TABELA1 = 'T'
                AND    BB.COLOPERACAO1 = 'P'
                AND    AA.OPCANCELADA IS NULL
                AND    AA.SEQCTACORRENTE IS NOT NULL
                AND    AA.DTAOPERACAO = A.DTAOPERACAO
                AND    CC.NROEMPRESA = C.NROEMPRESA
                AND    AA.OBSERVACAO = 'Recebimento em Conta Corrente Baixa automática de cartão'
                AND    REGEXP_SUBSTR(CC.DESCRICAO, '(\S*)(\s)') = REGEXP_SUBSTR(C.DESCRICAO, '(\S*)(\s)')
                AND    ANOTACAO IS NULL), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') AS VINCULADA,
                NULL CARRO_FORTE,
        TO_CHAR((SELECT SUM(VLROPERACAO) FROM FI_TITOPERACAO AA, FI_OPERACAO BB, FI_CTACORRENTE CC
                WHERE  AA.CODOPERACAO = BB.CODOPERACAO
                AND    AA.SEQCTACORRENTE = CC.SEQCTACORRENTE
                AND    BB.TABELA1 = 'T'
                AND    BB.COLOPERACAO1 = 'P'
                AND    AA.OPCANCELADA IS NULL
                AND    AA.SEQCTACORRENTE IS NOT NULL
                AND    AA.DTAOPERACAO = A.DTAOPERACAO
                AND    CC.NROEMPRESA = C.NROEMPRESA
                AND    REGEXP_SUBSTR(CC.DESCRICAO, '(\S*)(\s)') = REGEXP_SUBSTR(C.DESCRICAO, '(\S*)(\s)')
                AND (UPPER(AA.ANOTACAO) LIKE '%CONCOD%' OR UPPER(AA.ANOTACAO) LIKE '%TTBCOD%')), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') AS PAGTO_BCO,
        TO_CHAR((SELECT SUM(VLROPERACAO) FROM FI_TITOPERACAO AA, FI_OPERACAO BB, FI_CTACORRENTE CC
                WHERE  AA.CODOPERACAO = BB.CODOPERACAO
                AND    AA.SEQCTACORRENTE = CC.SEQCTACORRENTE
                AND    BB.TABELA1 = 'T'
                AND    BB.COLOPERACAO1 = 'P'
                AND    AA.OPCANCELADA IS NULL
                AND    AA.SEQCTACORRENTE IS NOT NULL
                AND    AA.DTAOPERACAO = A.DTAOPERACAO
                AND    CC.NROEMPRESA = C.NROEMPRESA
                AND    REGEXP_SUBSTR(CC.DESCRICAO, '(\S*)(\s)') = REGEXP_SUBSTR(C.DESCRICAO, '(\S*)(\s)')
                AND (UPPER(AA.ANOTACAO) LIKE '%TDS%' OR UPPER(AA.ANOTACAO) LIKE '%DCC%' OR UPPER(AA.ANOTACAO) LIKE '%CCC%')), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') AS DEPOSITOS,
                NULL TRIBUTOS,
        TO_CHAR((SELECT SUM(VLROPERACAO) FROM FI_TITOPERACAO AA, FI_OPERACAO BB, FI_CTACORRENTE CC
                WHERE  AA.CODOPERACAO = BB.CODOPERACAO
                AND    AA.SEQCTACORRENTE = CC.SEQCTACORRENTE
                AND    BB.TABELA1 = 'T'
                AND    BB.COLOPERACAO1 = 'P'
                AND    AA.OPCANCELADA IS NULL
                AND    AA.SEQCTACORRENTE IS NOT NULL
                AND    AA.DTAOPERACAO = A.DTAOPERACAO
                AND    CC.NROEMPRESA = C.NROEMPRESA
                AND    REGEXP_SUBSTR(CC.DESCRICAO, '(\S*)(\s)') = REGEXP_SUBSTR(C.DESCRICAO, '(\S*)(\s)')
                AND (UPPER(AA.ANOTACAO) LIKE '%TTOCOD%')), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') AS RISCO_SACADO,
                NULL TROCO, NULL TRANSFERENCIAS, NULL SALDO,
        TO_CHAR((SELECT SUM(VLROPERACAO) FROM FI_TITOPERACAO AA, FI_OPERACAO BB, FI_CTACORRENTE CC
                WHERE  AA.CODOPERACAO = BB.CODOPERACAO
                AND    AA.SEQCTACORRENTE = CC.SEQCTACORRENTE
                AND    BB.TABELA1 = 'T'
                AND    BB.COLOPERACAO1 = 'P'
                AND    AA.OPCANCELADA IS NULL
                AND    AA.SEQCTACORRENTE IS NOT NULL
                AND    AA.DTAOPERACAO = A.DTAOPERACAO
                AND    CC.NROEMPRESA = C.NROEMPRESA
                AND    AA.OBSERVACAO NOT LIKE '%Recebimento%'
                AND AA.CODESPECIEANT NOT LIKE '%QTPRP%'
                AND    REGEXP_SUBSTR(CC.DESCRICAO, '(\S*)(\s)') = REGEXP_SUBSTR(C.DESCRICAO, '(\S*)(\s)')), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') AS TOTAL_DEBITADO

FROM    FI_TITOPERACAO A,
        FI_OPERACAO    B,
        FI_CTACORRENTE C 
 WHERE  A.CODOPERACAO = B.CODOPERACAO
 AND    A.SEQCTACORRENTE = C.SEQCTACORRENTE
 AND    B.TABELA1 = 'T'
 AND    B.COLOPERACAO1 = 'P'
 AND    A.OPCANCELADA IS NULL
 AND    A.SEQCTACORRENTE IS NOT NULL
 AND    A.DTAOPERACAO = DATE '2022-07-26'
 AND C.DESCRICAO LIKE '%BRADESCO%') X --('%'||#LS1||'%')) X 
 ON G.NROEMPRESA = X.NROEMPRESA

ORDER BY 1
