ALTER SESSION SET current_schema = CONSINCO;

--SELECT * FROM GEV_PESSOACADASTRO
--WHERE SEQREDE = 4 

SELECT SUSP_LIB, NRO_TITULO, SERIE, PARCELA, ESPECIE, EMP, PESSOA, 
       TO_CHAR(DATA_VENCIMENTO, 'DD-MM-YYYY') DATA_VENCIMENTO,
       TO_CHAR(DATA_PROGRAMADA, 'DD-MM-YYYY') DATA_PROGRAMADA,
       TO_CHAR(VLR_ABERTO,'FM999G999G999D90') VLR_ABERTO,
       USUARIO_SUSP_LIB, 
       TO_CHAR(DATA_HORA_SUSP_LIB, 'DD-MM-YYYY HH:MI:SS') DATA_HORA_SUSP_LIB, MOTIVO

FROM (
SELECT CASE WHEN NVL(FI_TITULO.SUSPLIB,'L') = 'S' THEN 'Suspenso' ELSE 'Liberado' END Susp_Lib, FI_TITULO.SEQPESSOA,
        FI_TITULO.NROTITULO NRO_TITULO, FI_TITULO.SERIETITULO SERIE, FI_TITULO.NROPARCELA PARCELA, FI_TITULO.CODESPECIE ESPECIE,
        FI_TITULO.NROEMPRESA EMP, FI_TITULO.SEQPESSOA COD_PESSOA, GE_PESSOA.NOMERAZAO || '-' || GE_PESSOA.SEQPESSOA PESSOA,
        FI_TITULO.DTAVENCIMENTO DATA_VENCIMENTO, FI_TITULO.DTAPROGRAMADA DATA_PROGRAMADA, FI_TITULO.VLRNOMINAL - FI_TITULO.VLRPAGO VLR_ABERTO,
        FI_TITULO.USUALTERACAOSUSPLIB USUARIO_SUSP_LIB, FI_TITULO.DTAALTERACAOSUSPLIB DATA_HORA_SUSP_LIB,
        FI_TITSUSPENSOLIBERADOMTV.DESCRICAO MOTIVO, B.seqrede                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

FROM FI_TITULO, GE_PESSOA, FI_TITSUSPENSOLIBERADOMTV, GEV_PESSOACADASTRO B
 
WHERE   FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA 
    AND FI_TITULO.SEQPESSOA = B.SEQPESSOA
    AND FI_TITULO.SEQMOTIVOSUSPLIB = FI_TITSUSPENSOLIBERADOMTV.SEQMOTIVO(+) 
    AND FI_TITULO.ABERTOQUITADO = 'A' 
    AND FI_TITULO.SITUACAO != 'S'
    AND FI_TITULO.CODESPECIE IN ('DUPP', 'GNRE') 
    AND FI_TITULO.OBRIGDIREITO = 'O'
    AND FI_TITULO.NROEMPRESA IN (#LS1)         
    AND NOT EXISTS 
   
   (SELECT 1 
FROM  FI_PROGPAGAMENTO 
WHERE FI_PROGPAGAMENTO.SEQTITULO = FI_TITULO.SEQTITULO 
    AND NVL(FI_PROGPAGAMENTO.SITUACAO,'N') = 'N' )
    AND NOT EXISTS 
    
   (SELECT 1 
FROM FI_AUTPAGTO  
WHERE   FI_AUTPAGTO.SEQTITULO = FI_TITULO.SEQTITULO )  
    AND FI_TITULO.DTAPROGRAMADA BETWEEN  :DT1 AND :DT2                        
   
ORDER BY FI_TITULO.NROTITULO, FI_TITULO.SERIETITULO, FI_TITULO.NROPARCELA, GE_PESSOA.NOMERAZAO )

WHERE TO_CHAR(SEQREDE) IN (CASE WHEN (:NR1) = 0 THEN 
      TO_CHAR(SEQREDE) ELSE (:NR1) END)
      
      AND 
      
      TO_CHAR(COD_PESSOA) IN (CASE WHEN (:NR2) = 0 THEN
      TO_CHAR(COD_PESSOA) ELSE (:NR2) END)

ORDER BY NRO_TITULO, SERIE, PARCELA, PESSOA
