ALTER SESSION SET current_schema = CONSINCO;

-- Consulta script FN Titulos não vinculados por código

SELECT DISTINCT GE.NROEMPRESA FROM CONSINCO.GE_EMPRESA GE ,CONSINCO.FIV_DDATITULOSBUSCA a
  WHERE LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0) = LPAD(A.NROCNPJCPFSACADO,12,0)||LPAD(A.DIGCNPJCPFSACADO,2,0)
  AND LPAD(A.NROCNPJCPF,12,0)||LPAD(A.DIGCNPJCPF,2,0) IN  (SELECT LPAD(PE.Nrocgccpf,12,0)||LPAD(PE.Digcgccpf,2,0)  
   FROM CONSINCO.GE_PESSOA PE WHERE  PE.SEQPESSOA IN (116336))
  
  ORDER BY 1
  
-- Consulta CPNJ FORNECEDOR
  
   SELECT LPAD(PE.Nrocgccpf,12,0)||LPAD(PE.Digcgccpf,2,0), PE.NOMERAZAO  
   FROM CONSINCO.GE_PESSOA PE WHERE NOMERAZAO LIKE '%JBS%' --PE.SEQPESSOA IN (116336)
   ORDER BY 1
   
   UNION ALL
   
-- Consulta CNPJ titulos

   SELECT LPAD(A.NROCNPJCPF,12,0)||LPAD(A.DIGCNPJCPF,2,0) AD
   FROM CONSINCO.FIV_DDATITULOSBUSCA a
   WHERE (LPAD(A.NROCNPJCPF,12,0)||LPAD(A.DIGCNPJCPF,2,0)) LIKE '%162650%'
   
-- Consulta SEQPESSOA + CNPJ Fornecedor 

   SELECT SEQPESSOA, NOMERAZAO, LPAD(PE.Nrocgccpf,12,0)||LPAD(PE.Digcgccpf,2,0)
   FROM GE_PESSOA PE
   WHERE NOMERAZAO LIKE '%JBS%' 
   AND LPAD(PE.Nrocgccpf,12,0)||LPAD(PE.Digcgccpf,2,0) = 02916265000160
   ORDER By 1
   
-- Consulta REDE  
 
   SELECT * FROM GEV_PESSOACADASTRO WHERE REDE LIKE '%JBS%'
   ORDER BY 1 129962
