ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Apuracao Verbas - Dina

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       TO_CHAR(N.DTAENTRADA, 'MM/YYYY') MES_ANO,
       TO_CHAR(NVL(ROUND(SUM(D.VLRDESCONTO), 2), 0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')  VLR_DESCONTO_CONTRATO

  FROM MGC_CONTRATO C,
       MLF_NOTAFISCAL N,
       MLF_NFITEM I,
       (SELECT SEQCONTRATODESCONTO,
               SEQCONTRATO,
               SEQAUXNOTAFISCAL,
               LINKERP,
               SEQITEMNF,
               ROUND(SUM(PERCENTUAL * VLTTOTALITEM / 100), 5) VLRDESCONTO -- RP 153233
          FROM MLF_DESCFINACONTRATO
         GROUP BY SEQCONTRATO,
                  SEQAUXNOTAFISCAL,
                  LINKERP,
                  SEQITEMNF,
                  SEQCONTRATODESCONTO) D,
       GE_PESSOA P
 WHERE D.SEQCONTRATO = C.SEQCONTRATO
   AND N.SEQAUXNOTAFISCAL = D.SEQAUXNOTAFISCAL
   AND I.SEQAUXNOTAFISCAL = D.SEQAUXNOTAFISCAL
   AND P.SEQPESSOA = N.SEQPESSOA
   AND N.LINKERP = D.LINKERP
   AND I.SEQITEMNF = D.SEQITEMNF
   AND N.TIPNOTAFISCAL = 'E'
   AND N.DTAENTRADA BETWEEN '01-JAN-2024' AND '30-APR-2024'
   AND EXISTS (SELECT 1
          FROM MGC_CONTRATODESCONTO A
         WHERE A.SEQCONTRATO = C.SEQCONTRATO)
 GROUP BY TO_CHAR(N.DTAENTRADA, 'MM/YYYY')
 ORDER BY 1
