ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Ja define o periodo que vai ser utilizado em ambos os selects

WITH CTE_DATAS AS (SELECT DATE '2024-01-01' INICIO, DATE '2024-03-31' FIM FROM DUAL)

SELECT SEQFORNECEDOR, FORNEC, TIPO_ACORDO, 
       TO_CHAR(VLR_ACORDO_TOT, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_TOTAL_ACORDOS,
       VLRPAGO, VLRABERTO, TOTAL_ACORDOS, TOT_ABERTOS, TOT_QUITADOS

FROM (

SELECT SEQFORNECEDOR, FORNEC, TIPO_ACORDO, 
       SUM(VLR_ACORDO_TOT) VLR_ACORDO_TOT,
       TO_CHAR(SUM(VLRPAGO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')        VLRPAGO, 
       TO_CHAR(SUM(VLRABERTO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')      VLRABERTO, 
       SUM(TOTAL_ACORDOS) TOTAL_ACORDOS,
       SUM(TOT_ABERTOS)   TOT_ABERTOS,
       SUM(TOT_QUITADOS)  TOT_QUITADOS
       
       FROM (

SELECT D.SEQPESSOA SEQFORNECEDOR, B.NOMERAZAO FORNEC,
       NVL(D.CODESPECIE, T.CODESPECIE) ||' - '|| T.DESCRICAO TIPO_ACORDO,
       SUM(ROUND(NVL(D.VLRORIGINAL,A.VLRACORDO), 2))VLR_ACORDO_TOT,
       SUM(D.VLRPAGO) VLRPAGO,
       SUM(D.VLRORIGINAL) - SUM(D.VLRPAGO) VLRABERTO,
       COUNT(NROACORDO) TOTAL_ACORDOS,
       CASE WHEN ABERTOQUITADO = 'A' THEN COUNT(NROACORDO) ELSE 0 END TOT_ABERTOS,
       CASE WHEN ABERTOQUITADO = 'Q' THEN COUNT(NROACORDO) ELSE 0 END TOT_QUITADOS
                
  FROM MSU_ACORDOPROMOC A INNER JOIN GE_PESSOA B     ON A.SEQFORNECEDOR = B.SEQPESSOA
                          INNER JOIN(SELECT NROTITULO, SUM(VLRORIGINAL) VLRORIGINAL, SUM(VLRPAGO) VLRPAGO, CODESPECIE, SEQPESSOA, DTAINCLUSAO, ABERTOQUITADO, NROEMPRESA
                                      FROM FI_TITULO DD 
                                     WHERE DD.SITUACAO != 'C'
                                      GROUP BY NROTITULO, CODESPECIE, SEQPESSOA, DTAINCLUSAO, ABERTOQUITADO, NROEMPRESA) D 
                                                                                                               ON D.SEQPESSOA = A.SEQFORNECEDOR
                                                                                                              AND D.NROTITULO = A.NROACORDO
                                                                                                              AND D.NROEMPRESA = A.NROEMPRACORDOPROMOC
                          INNER JOIN MAC_TIPOACORDO T ON T.CODTIPOACORDO = A.CODTIPOACORDO
 WHERE 1=1
   AND NVL(A.STATUSACORDO, 'X')   != 'C'
   AND NVL(A.SITUACAOACORDO, 'X') NOT IN ('R','C')
   AND D.DTAINCLUSAO BETWEEN (SELECT INICIO FROM CTE_DATAS) AND (SELECT FIM FROM CTE_DATAS)
   AND D.CODESPECIE NOT IN ('DUPP', 'DEVREC')
    
GROUP BY D.SEQPESSOA, NOMERAZAO, NVL(D.CODESPECIE, T.CODESPECIE) ||' - '|| T.DESCRICAO, ABERTOQUITADO, D.NROEMPRESA

UNION ALL

SELECT FC.SEQPESSOA, NOMERAZAO, DECODE(CODESPECIE,'CONTRT','CONTRT - CONTRATO RETORNO/FIDELIDADE', 'CONTLG','CONTLG - CONTRATO LOGISTICO', 'DEVREC','DEVREC - DEVOLUCAO A RECEBER'),
       SUM(ROUND(VLRORIGINAL, 2))VLR_ACORDO_TOT,
       SUM(VLRPAGO) VLRPAGO,
       SUM(VLRORIGINAL) - SUM(VLRPAGO) VLRABERTO,
       COUNT(NROTITULO) TOTAL_ACORDOS,
       CASE WHEN ABERTOQUITADO = 'A' THEN COUNT(NROTITULO) ELSE 0 END TOT_ABERTOS,
       CASE WHEN ABERTOQUITADO = 'Q' THEN COUNT(NROTITULO) ELSE 0 END TOT_QUITADOS
         
  FROM FI_TITULO FC INNER JOIN GE_PESSOA B ON B.SEQPESSOA = FC.SEQPESSOA
 WHERE 1=1
   AND FC.DTAINCLUSAO BETWEEN (SELECT INICIO FROM CTE_DATAS) AND (SELECT FIM FROM CTE_DATAS)
   AND CODESPECIE IN ('CONTRT', 'CONTLG', 'DEVREC') 
   AND FC.SITUACAO != 'C'
               
GROUP BY FC.SEQPESSOA, NOMERAZAO,  ABERTOQUITADO, CODESPECIE)

GROUP BY SEQFORNECEDOR, FORNEC, TIPO_ACORDO

ORDER BY 4 DESC) 


