SELECT DISTINCT TO_CHAR(U.DATA, 'MM/YYYY') MES, G.NOMERAZAO FORNECEDOR, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0) CNPJ_FORNEC, F.DESCRICAO DESC_FILTRO,
       TO_CHAR(SUM(FI.VLRORIGINAL),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')  VLR_TOTAL, COUNT(FI.SEQTITULO) QTD_TITULOS

  FROM FI_FORNECEDOR X LEFT JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA 
                        LEFT JOIN FI_DDAFILTRO F ON F.SEQFILTRO = X.SEQFILTRODDA
                        LEFT JOIN FI_DDAREGRA  D ON D.SEQFILTRO = F.SEQFILTRO
                        LEFT JOIN FI_DDAREGRADETALHE R ON R.SEQREGRA = D.SEQREGRA 
                        LEFT JOIN GE_PESSOA FF ON LPAD(FF.NROCGCCPF,12,0)||LPAD(FF.DIGCGCCPF,2,0) = LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0)
                        LEFT JOIN FI_LOGREGRADDAUTIL U ON U.SEQREGRA = D.SEQREGRA 
                        LEFT JOIN FI_TITULO FI ON FI.SEQTITULO = U.SEQTITULO AND FI.SITUACAO != 'C' AND FI.ABERTOQUITADO = 'Q'
                        
 WHERE X.SEQFILTRODDA != 0 
   AND R.NROCNPJCPF IS NOT NULL
   AND TRUNC(U.DATA) > DATE '2023-01-01'
   AND TO_CHAR(U.DATA, 'MM') IN (#LS1)

 HAVING SUM(FI.VLRORIGINAL) > 0 
   
 GROUP BY G.NOMERAZAO, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0), F.DESCRICAO  ,TO_CHAR(U.DATA, 'MM/YYYY')
   
 ORDER BY G.NOMERAZAO, TO_CHAR(U.DATA, 'MM/YYYY') 
