SELECT SEQMOVOCR, X.CODOCORRENCIA, DESCRICAO, OBSERVACAO, X.DTAALTERACAO, X.USUALTERACAO
  FROM FI_MOVOCOR X, FI_OCRFINANC Y
  
 WHERE X.CODOCORRENCIA = Y.CODOCORRENCIA 
   AND X.SEQIDENTIFICA =  -- SEQTITULO  
