SELECT SEQIMPORTACAO, A.NRODOCUMENTO, A.DESCFORNECEDOR, A.DTAVENCIMENTO, A.VALORCOMDESCONTO, A.VALORABATIMENTO, A.SEQTITULO, A.NROCNPJCPF||A.DIGCNPJCPF CNPJ
FROM CONSINCO.FIV_DDATITULOSBUSCA A 
WHERE A.SEQTITULO IN (SELECT SEQTITULO FROM CONSINCO.FI_TITULO B WHERE B.NRODOCUMENTO = 155044 AND NROEMPRESA = 501 )

