ALTER SESSION SET current_schema = CONSINCO;

SELECT DISTINCT D.DESCRICAO, D.SEQFILTRO

FROM FI_DDAREGRADETALHE A LEFT JOIN FI_DDAREGRA C ON A.SEQREGRA = C.SEQREGRA
                          LEFT JOIN FI_DDAFILTRO D ON C.SEQFILTRO = D.SEQFILTRO
                          LEFT JOIN FI_DDAVARIAVEL B ON A.SEQVARIAVEL = B.SEQVARIAVEL
       
WHERE B.SEQVARIAVEL IN (3,7)

ORDER BY 1 ASC;
