SELECT NROTITULO||'/'||X.NROPARCELA TITULO_PARC, NROEMPRESA EMPRESA, CODESPECIE, 
       TO_CHAR(VLRORIGINAL, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_ORIGINAL, 
       TO_CHAR(VLRNOMINAL, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_NOMINAL,
       TO_CHAR(VLRPAGO, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_PAGO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTA_VENCIMENTO, 
       DECODE(ABERTOQUITADO, 'A','Aberto','Q','Quitado') STATUS, OBSERVACAO
  FROM CONSINCO.FI_TITULO X WHERE UPPER(X.OBSERVACAO) LIKE '%BAIX%' AND UPPER(X.OBSERVACAO) LIKE '%OP%' AND UPPER(X.OBSERVACAO) NOT LIKE '%DEVOL%'
                              AND X.SITUACAO != 'C'
                              AND DTAVENCIOMENTO BETWEEN :DT1 AND :DT2
                              AND NROEMPRESA IN (#LS1)
  
  ORDER BY 8, DTAVENCIMENTO DESC
