SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ DISTINCT TO_CHAR(U.DATA, 'MM/YYYY') MES, G.SEQPESSOA,
       G.NOMERAZAO FORNECEDOR, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0) CNPJ_FORNEC,
      (SELECT LISTAGG(DISTINCT COMPRADOR, ', ') WITHIN GROUP (ORDER BY FF.SEQFORNECEDOR) 
                  FROM MAX_COMPRADOR C INNER JOIN MAP_FAMDIVISAO F ON F.SEQCOMPRADOR = C.SEQCOMPRADOR
                                       INNER JOIN MAP_FAMFORNEC FF ON FF.SEQFAMILIA = F.SEQFAMILIA
        WHERE FF.SEQFORNECEDOR = X.SEQPESSOA) COMPRADORES,
       REGEXP_SUBSTR(D.DESCRICAO, '/(.+)', 1, 1, NULL, 1) FACTORING,
       TO_CHAR(SUM(FI.VLRORIGINAL),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')  VLR_TOTAL, COUNT(FI.SEQTITULO) QTD_TITULOS

  FROM FI_FORNECEDOR X INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                        LEFT JOIN FI_DDAFILTRO F ON F.SEQFILTRO = X.SEQFILTRODDA
                        LEFT JOIN FI_DDAREGRA  D ON D.SEQFILTRO = F.SEQFILTRO
                        LEFT JOIN FI_DDAREGRADETALHE R ON R.SEQREGRA = D.SEQREGRA 
                        LEFT JOIN GE_PESSOA FF ON LPAD(FF.NROCGCCPF,12,0)||LPAD(FF.DIGCGCCPF,2,0) = LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0)
                        LEFT JOIN FI_LOGREGRADDAUTIL U ON U.SEQREGRA = D.SEQREGRA 
                        LEFT JOIN FI_TITULO FI ON FI.SEQTITULO = U.SEQTITULO AND FI.SITUACAO != 'C' AND FI.ABERTOQUITADO = 'Q'
                        
  WHERE X.SEQFILTRODDA != 0 
   AND R.NROCNPJCPF IS NOT NULL
   AND EXISTS (SELECT 1 FROM FI_LOGREGRADDAUTIL L WHERE L.DATA >= :DT1 - 30 AND L.SEQREGRA = D.SEQREGRA)
   AND TRUNC(U.DATA) BETWEEN :DT1 AND :DT2
   AND D.DESCRICAO NOT LIKE '%NU%'
   AND D.DESCRICAO NOT LIKE '%NUBANK%'
   AND D.DESCRICAO NOT LIKE '%CORA%'
   AND D.DESCRICAO NOT LIKE '%PJBANK%'
   AND D.DESCRICAO NOT LIKE '%PJ BANK%'
   AND D.DESCRICAO NOT LIKE '%PAGAR ME%'
   AND D.DESCRICAO NOT LIKE '%PAGARME%'
   AND D.DESCRICAO NOT LIKE '%ML BANK%'
   AND D.DESCRICAO NOT LIKE '%MLBANK%'
   AND D.DESCRICAO NOT LIKE '%FILIAL%'
   AND D.DESCRICAO NOT LIKE '%PAGAR.ME%'
   AND D.DESCRICAO NOT LIKE '%ALEONE%'
   AND D.DESCRICAO NOT LIKE '%NEON%'
   AND D.DESCRICAO NOT LIKE '%SAFE2PAY%'
  AND D.DESCRICAO NOT LIKE '%PAGHIPER%'
 
 HAVING SUM(FI.VLRORIGINAL) > 0 
   
 GROUP BY TO_CHAR(U.DATA, 'MM/YYYY'), G.NOMERAZAO, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0), REGEXP_SUBSTR(D.DESCRICAO, '/(.+)', 1, 1, NULL, 1), F.DESCRICAO, G.SEQPESSOA, X.SEQPESSOA
 
 ORDER BY G.NOMERAZAO, TO_CHAR(U.DATA, 'MM/YYYY');
