SELECT DISTINCT TO_CHAR(U.DATA, 'MM/YYYY') MES, X.SEQPESSOA, G.NOMERAZAO FORNECEDOR, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0) CNPJ_FORNEC, 
       F.DESCRICAO DESC_FILTRO, 
       SUBSTR(D.DESCRICAO, INSTR(D.DESCRICAO, '/') + 1) DESC_REGRA, 
       LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0) CNPJ_REGRA,
       CASE WHEN LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0) = 000000000000 THEN 'DIVERSOS' ELSE FF.NOMERAZAO END RAZAO_CNPJ_REGRA,
       TO_CHAR(SUM(FI.VLRORIGINAL),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')  VLR_TOTAL, COUNT(FI.SEQTITULO) QTD_TITULOS

  FROM FI_FORNECEDOR X INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                        LEFT JOIN FI_DDAFILTRO F ON F.SEQFILTRO = X.SEQFILTRODDA
                        LEFT JOIN FI_DDAREGRA  D ON D.SEQFILTRO = F.SEQFILTRO
                        LEFT JOIN FI_DDAREGRADETALHE R ON R.SEQREGRA = D.SEQREGRA 
                        LEFT JOIN GE_PESSOA FF ON LPAD(FF.NROCGCCPF,12,0)||LPAD(FF.DIGCGCCPF,2,0) = LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0)
                        LEFT JOIN FI_LOGREGRADDAUTIL U ON U.SEQREGRA = D.SEQREGRA 
                        LEFT JOIN FI_TITULO FI ON FI.SEQTITULO = U.SEQTITULO AND FI.SITUACAO != 'C' AND FI.ABERTOQUITADO = 'Q'
                        
 WHERE X.SEQFILTRODDA != 0 
   AND R.NROCNPJCPF IS NOT NULL
   AND EXISTS (SELECT 1 FROM FI_LOGREGRADDAUTIL L WHERE L.DATA >= DATE '2023-01-01' AND L.SEQREGRA = D.SEQREGRA)
   
   AND TRUNC(U.DATA) >= DATE '2024-01-01'
   AND TO_CHAR(U.DATA, 'MM') IN (#LS1)
   
   AND FF.NOMERAZAO NOT LIKE '%NUBANK%'
   AND FF.NOMERAZAO NOT LIKE '%CORA%'
   AND FF.NOMERAZAO NOT LIKE '%NEON%'
   AND FF.NOMERAZAO NOT LIKE '%PJBANK%'
   AND FF.NOMERAZAO NOT LIKE '%PAGHIPER%'
   AND FF.NOMERAZAO NOT LIKE '%MERCADO PAGO%'
   AND FF.NOMERAZAO NOT LIKE '%NU PAG%'
   AND FF.NOMERAZAO NOT LIKE '%PAGSEGURO%'
   AND FF.NOMERAZAO NOT LIKE '%PAGAR%ME%'
      
 HAVING SUM(FI.VLRORIGINAL) > 0 
   
 GROUP BY TO_CHAR(U.DATA, 'MM/YYYY'), G.NOMERAZAO, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0), F.DESCRICAO, X.SEQPESSOA, D.DESCRICAO, LPAD(R.NROCNPJCPF,12,0)||LPAD(R.DIGCNPJCPF,2,0), FF.NOMERAZAO
 
 ORDER BY G.NOMERAZAO, TO_CHAR(U.DATA, 'MM/YYYY')
