SELECT NROTITULO||'/'||X.NROPARCELA TITULO_PARC, C.SEQPESSOA||' - '||C.NOMERAZAO FORNECEDOR, NROEMPRESA EMPRESA, CODESPECIE, 
       TO_CHAR(VLRORIGINAL, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_ORIGINAL, 
       TO_CHAR(VLRNOMINAL,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_NOMINAL,
       TO_CHAR(VLRPAGO,     'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_PAGO, 
       TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DTA_VENCIMENTO, 
       DECODE(ABERTOQUITADO, 'A','Aberto','Q','Quitado')||CASE WHEN ABERTOQUITADO = 'A' THEN NULL 
       WHEN Z.DTAOPERACAO IS NULL THEN ' - BANCO' ELSE ' - OP. MANUAL ('||Z.CODOPERACAO||')' END STATUS, X.OBSERVACAO
         
  FROM CONSINCO.FI_TITULO X LEFT JOIN CONSINCO.GE_PESSOA C ON X.SEQPESSOA = C.SEQPESSOA
                            LEFT JOIN CONSINCO.FI_TITOPERACAO Z ON X.SEQTITULO = Z.SEQTITULO AND  Z.OPCANCELADA IS NULL AND Z.CODOPERACAO IN (191,197,180)
                            
  WHERE UPPER(X.OBSERVACAO) LIKE '%BAIX%' AND UPPER(X.OBSERVACAO) LIKE '%OP%' AND UPPER(X.OBSERVACAO) NOT LIKE '%DEVOL%'
                              AND X.SITUACAO != 'C'
                              AND DTAVENCIOMENTO BETWEEN :DT1 AND :DT2
                              AND NROEMPRESA IN (#LS1)
                              
  ORDER BY DTAVENCIMENTO DESC, NROEMPRESA
  
