SELECT SEQIMPORTACAO, A.NRODOCUMENTO, A.DESCFORNECEDOR, A.DTAVENCIMENTO, A.VALORCOMDESCONTO, A.VALORABATIMENTO, A.SEQTITULO, B.NROTITULO, A.NROCNPJCPF||A.DIGCNPJCPF CNPJ
FROM CONSINCO.FIV_DDATITULOSBUSCA A LEFT JOIN CONSINCO.FI_TITULO B ON A.SEQTITULO = B.SEQTITULO
WHERE A.DTAVENCIMENTO = DATE '2022-11-03' AND VALORCOMDESCONTO = 3777.59
