-- Criar a inconsistência na CONSINCO.MAD_CRITICAPEDCONFIG 

-- Inserir o select em MADV_CRITICAPEDVENDA

UNION ALL -- Giuliano - Solicitação Neides Ticket 104571 - 01/10/2022

/* Bloqueia Forma Pagto Mesma Razão para emissões entre CNPJs raizes distintos */

SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'VERIFICAR FORMA PAGTO' CODCRITICA
   FROM CONSINCO.MAD_PEDVENDA A LEFT JOIN MRL_FORMAPAGTO D ON A.NROFORMAPAGTO = D.NROFORMAPAGTO
   WHERE D.FORMAPAGTO LIKE '%MESMA RAZ_O%'
   AND (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = A.NROEMPRESA) !=
       (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = A.SEQPESSOA)
       
UNION ALL

/* Bloqueia Forma Pagto Razão Diferente para emissões entre CNPJs raizes iguais */
       
SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'VERIFICAR FORMA PAGTO' CODCRITICA
   FROM CONSINCO.MAD_PEDVENDA A LEFT JOIN MRL_FORMAPAGTO D ON A.NROFORMAPAGTO = D.NROFORMAPAGTO
   WHERE D.FORMAPAGTO LIKE '%RAZ_O DIF%'
   AND (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = A.NROEMPRESA) =
       (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = A.SEQPESSOA)
       
       ;

/* Consulta Empresas com mesmo CNPJ RAIZ */

SELECT * FROM GE_PESSOA WHERE SUBSTR(LPAD(NROCGCCPF,12,0),1,8) =
       (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = 31)
