SELECT DISTINCT X.NROEMPRESA, X.NUMERONF, X.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, XI.SEQPRODUTO, DESCCOMPLETA DESCRICAO, 
       XI.EMBALAGEM||' - '||XI.QTDEMBALAGEM EMB_NF, C.QTDEMBALAGEM EMB_TRIB_C5
  FROM CONSINCO.MLF_NOTAFISCAL X INNER JOIN CONSINCO.MLF_NFITEM XI ON XI.SEQNF = X.SEQNF 
                                 INNER JOIN CONSINCO.GE_PESSOA  G  ON G.SEQPESSOA = X.SEQPESSOA
                                 INNER JOIN CONSINCO.MAP_PRODUTO A ON A.SEQPRODUTO = XI.SEQPRODUTO
                                  LEFT JOIN CONSINCO.MAP_PRODCODIGO C ON C.SEQPRODUTO = XI.SEQPRODUTO AND C.INDEANTRIBNFE = 'S' AND TIPCODIGO = 'E'
 WHERE 1=1
   AND XI.QTDEMBALAGEM != 1
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND NOT EXISTS (SELECT 1 FROM CONSINCO.MAP_PRODCODIGO P WHERE P.INDEANTRIBNFE = 'S' AND P.SEQPRODUTO = XI.SEQPRODUTO AND P.QTDEMBALAGEM = XI.QTDEMBALAGEM)
   AND X.SEQPESSOA > 999
   AND X.NROEMPRESA IN (#LS1)
   
   ORDER BY X.NROEMPRESA, X.NUMERONF
