ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.NROEMPRESA,TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO,  TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') DTAENTRADA,
       TO_CHAR(B.DTAVENCTO, 'DD/MM/YYYY') DTAVENCIMENTO,
       NRONOTA, A.NOMERAZAO NOMERAZAO, LPAD(A.NROCGCCPF,12,0)||LPAD(A.DIGCGCCPF,2,0) CNPJ, NULL COD_NAD_REND,
       X.CODHISTORICO NATUREZA, X.VALOR VALOR_NF, B.VALOR VALOR_PARC,
       D.VALOR IRRF, 
       CASE WHEN D.VALOR IS NOT NULL THEN X.ALIQIR ELSE NULL END ALIQIR, 
       CASE WHEN D.VALOR IS NOT NULL THEN TO_CHAR(X.DTAVENCTOIR, 'DD/MM/YYYY') ELSE NULL END VENC_IRRF, 
       CASE WHEN D.VALOR IS NOT NULL THEN X.CODRECDARFIRRF ELSE NULL END CODIGO_IR,
       ROUND((B.VALOR / 100 * X.ALIQPIS),  2) VLRPIS,     TO_CHAR(X.ALIQPIS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQPIS, 
       ROUND((B.VALOR / 100 * X.ALIQCOFINS),2) VLRCOFINS, TO_CHAR(X.ALIQCOFINS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQCOFINS,
       ROUND((B.VALOR / 100 * X.ALIQCSSLL) ,2) VLRCSSLL,  TO_CHAR(X.ALIQCSSLL, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQCSSLL,
       C.VALOR TOTAL_PCC, TO_CHAR(C.DTAVENCIMENTO, 'DD/MM/YYYY') VENC_PCC, 
       COALESCE(X.CODRECDARFPISRET,X.CODRECDARFPISRET,
                                   X.CODRECDARFCOFINSRET,
                                   X.CODRECDARFCSLLRET,
                                   X.CODRECDARFIRRF,
                                   X.CODRECDARFIRRFPESFIS) COD_PCC,
       B.NROPARCELA
       
   FROM OR_NFDESPESA X INNER JOIN GE_PESSOA A       ON A.SEQPESSOA = X.SEQPESSOA
                       INNER JOIN OR_NFVENCIMENTO B ON X.SEQNOTA   = B.SEQNOTA AND X.NROEMPRESA = B.NROEMPRESA
                       LEFT  JOIN OR_NFDESPIMPOSTOS C ON C.SEQNOTA = X.SEQNOTA AND C.NROPARCELA = B.NROPARCELA AND C.CODESPECIEIMP = 'PCCNF'
                       LEFT JOIN  OR_NFDESPIMPOSTOS D ON D.SEQNOTA = X.SEQNOTA AND D.NROPARCELA = B.NROPARCELA AND D.CODESPECIEIMP = 'IRRFNF'
 WHERE 1=1 
   AND COALESCE(ALIQPIS, ALIQCOFINS, ALIQCSSLL, X.ALIQIR) IS NOT NULL 
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
