ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT A.NROEMPRESA EMP,
       A.DTALANCTO DATA_OP1, DECODE(A.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       A.CODOPERACAO COD1, A.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE B WHERE B.SEQCTACORRENTE = A.SEQCTACORRENTE)   CONTA_MOVTO, A.VLRLANCAMENTO VLR1,
       
       B.DTALANCTO DATA_OP2, DECODE(B.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       B.CODOPERACAO COD2, B.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE BB WHERE BB.SEQCTACORRENTE = B.SEQCTACORRENTE) CAIXA_COFRE, B.VLRLANCAMENTO VLR2,
       
       C.DTALANCTO DATA_OP3, DECODE(C.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       C.CODOPERACAO COD3, C.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE BB WHERE BB.SEQCTACORRENTE = C.SEQCTACORRENTE) CAIXA_COFRE, C.VLRLANCAMENTO VLR3,
       
       D.DTALANCTO DATA_OP4, DECODE(D.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       D.CODOPERACAO COD4, D.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE BB WHERE BB.SEQCTACORRENTE = D.SEQCTACORRENTE) CONTA_CAIXA, D.VLRLANCAMENTO VLR4,
       
       E.DTALANCTO DATA_OP5, DECODE(E.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       E.CODOPERACAO COD5, E.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE BB WHERE BB.SEQCTACORRENTE = E.SEQCTACORRENTE) CONTA_BCO,   E.VLRLANCAMENTO VLR5,
       
       F.DTALANCTO DATA_OP6, DECODE(F.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       F.CODOPERACAO COD6, F.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE BB WHERE BB.SEQCTACORRENTE = F.SEQCTACORRENTE)  CONTA_BCO,  F.VLRLANCAMENTO VLR6,
       
       G.DTALANCTO DATA_OP7, DECODE(G.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       G.CODOPERACAO COD7, G.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE BB WHERE BB.SEQCTACORRENTE = G.SEQCTACORRENTE)  CONTA_BCO,  G.VLRLANCAMENTO VLR7,
       
       H.DTALANCTO DATA_OP8, DECODE(H.TIPOLANCTO, 'D','Débito','C','Crédito') TIPO_LANCTO,
       H.CODOPERACAO COD8, H.SEQCTACORRENTE||'-'||(SELECT DESCRICAO FROM FI_CTACORRENTE BB WHERE BB.SEQCTACORRENTE = H.SEQCTACORRENTE)  CONTA_BCO,  H.VLRLANCAMENTO VLR8,
        
       (A.VLRLANCAMENTO - C.VLRLANCAMENTO) - E.VLRLANCAMENTO COMPARATIVO_VLR
       
  FROM FI_CTACORLANCA A LEFT JOIN FI_CTACORLANCA B ON B.NROPROCESSO = A.NROPROCESSO AND B.OPCANCELADA IS NULL AND B.CODOPERACAO = 920 -- CREDITO CAIXA COFRE
                        LEFT JOIN FI_CTACORLANCA C ON C.TIPOLANCTO = 'D' AND C.DTALANCTO = B.DTALANCTO +1 AND C.NROEMPRESA = A.NROEMPRESA AND C.CODOPERACAO = 109 -- DEBITO CAIXA COFRE
                        LEFT JOIN FI_CTACORLANCA D ON D.TIPOLANCTO = 'C' AND D.DTALANCTO = B.DTALANCTO +1 AND D.NROEMPRESA = A.NROEMPRESA AND D.CODOPERACAO = 109 -- CREDITO CAIXA
                        LEFT JOIN FI_CTACORLANCA E ON E.TIPOLANCTO = 'D' AND E.DTALANCTO = B.DTALANCTO +1 AND E.NROEMPRESA = A.NROEMPRESA AND E.CODOPERACAO = 133 AND E.VLRLANCAMENTO = A.VLRLANCAMENTO - C.VLRLANCAMENTO
                        LEFT JOIN FI_CTACORLANCA F ON F.TIPOLANCTO = 'C' AND F.DTALANCTO = B.DTALANCTO +1 AND F.NROEMPRESA = A.NROEMPRESA AND F.CODOPERACAO = 133 AND F.VLRLANCAMENTO = A.VLRLANCAMENTO - C.VLRLANCAMENTO -- DEBIDO BCO
                        LEFT JOIN FI_CTACORLANCA G ON G.TIPOLANCTO = 'D' AND G.DTALANCTO = B.DTALANCTO +1 AND G.NROEMPRESA = A.NROEMPRESA AND G.CODOPERACAO = 134 AND G.VLRLANCAMENTO = A.VLRLANCAMENTO - C.VLRLANCAMENTO -- DEBIDO BCO
                        LEFT JOIN FI_CTACORLANCA H ON H.TIPOLANCTO = 'C' AND H.DTALANCTO = B.DTALANCTO +1 AND H.NROEMPRESA = A.NROEMPRESA AND H.CODOPERACAO = 134 AND H.VLRLANCAMENTO = A.VLRLANCAMENTO - C.VLRLANCAMENTO -- DEBIDO BCO



WHERE   A.NROEMPRESA = 2
    AND A.DTALANCTO BETWEEN DATE '2023-04-01' AND DATE '2023-04-30'                                                 
    AND NOT EXISTS
        (SELECT  1
         FROM  FI_CTACORCONC
         WHERE FI_CTACORCONC.SEQLANCTO = A.SEQLANCTO) 
    AND A.TIPOLANCTO IN('D', 'C')  
    AND A.OPCANCELADA IS NULL
    AND A.CODOPERACAO IN (921) 
