ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT *
  FROM MAP_PRODUTO X INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = X.SEQFAMILIA
                     INNER JOIN MAP_FAMFORNEC FC ON FC.SEQFAMILIA = X.SEQFAMILIA
                     INNER JOIN MAP_TRIBUTACAOUF UF ON UF.NROTRIBUTACAO = FD.NROTRIBUTACAO
                     INNER JOIN MAF_FORNECEDOR F ON F.SEQFORNECEDOR = FC.SEQFORNECEDOR
                     INNER JOIN GE_PESSOA GE ON GE.SEQPESSOA = FC.SEQFORNECEDOR
 WHERE 1=1
 AND GE.UF = 'EX'
 AND UF.UFCLIENTEFORNEC = 'EX'
 AND (NVL(NULLIF(UF.PERPISDIF,0),1.65) = 1.65    AND UF.SITUACAONFPIS NOT IN (73,70)
   OR NVL(NULLIF(UF.PERCOFINSDIF,0),7.60) = 7.60 AND UF.SITUACAONFCOFINS NOT IN (73,70))
 AND UF.NROREGTRIBUTACAO = 8 -- Importacao Direta
 AND UF.UFEMPRESA = 'SP'
 AND UF.TIPTRIBUTACAO = DECODE(NVL(FC.TIPFORNECEDORFAM,F.TIPFORNECEDOR) , 'I', 'EI', 'D', 'ED') 
 
 ORDER BY 3
 
