SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'FORMA PAGTO INCORRETA - VERIFICAR' CODCRITICA
   FROM CONSINCO.MAD_PEDVENDA A LEFT JOIN MRL_FORMAPAGTO D ON A.NROFORMAPAGTO = D.NROFORMAPAGTO
   WHERE D.FORMAPAGTO LIKE '%MESMA RAZ_O%'
   AND (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = A.NROEMPRESA) !=
       (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = A.SEQPESSOA);
       
UNION ALL
       
SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'FORMA PAGTO INCORRETA - VERIFICAR' CODCRITICA
   FROM CONSINCO.MAD_PEDVENDA A LEFT JOIN MRL_FORMAPAGTO D ON A.NROFORMAPAGTO = D.NROFORMAPAGTO
   WHERE D.FORMAPAGTO LIKE '%RAZ_O DIF%'
   AND (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = A.NROEMPRESA) =
       (SELECT DISTINCT SUBSTR(LPAD(NROCGCCPF,12,0),1,8) FROM GE_PESSOA WHERE SEQPESSOA = A.SEQPESSOA);
