SELECT XX.NOMEREDUZIDO,
       TO_CHAR(A.SEQPESSOA)||' - '||
       TO_CHAR(B.NOMERAZAO) FORNECEDOR,
       TO_CHAR(A.DTAENTRADA, 'MM') MES_ENTRADA,
       TO_CHAR(SUM(X.VLRITEM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')  VALOR_TOTAL,
       TO_CHAR(SUM(X.VLRFUNRURALITEM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_FUNRURAL
       
  FROM CONSINCO.MLF_NOTAFISCAL A,
       CONSINCO.GE_PESSOA      B,
       CONSINCO.MLF_NFITEM     X,
       CONSINCO.MAX_EMPRESA    XX
 WHERE A.SEQPESSOA = B.SEQPESSOA
   AND A.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
   AND B.SEQPESSOA = X.SEQPESSOA
   AND XX.NROEMPRESA = A.NROEMPRESA
   AND A.STATUSNF != 'C'
   AND XX.NROEMPRESA = X.NROEMPRESA
   AND XX.NOMEREDUZIDO IN (#LS1)
   AND A.CODGERALOPER IN (200,203,900,928)
   AND A.DTAENTRADA BETWEEN :DT1 AND :DT2
   
 GROUP BY A.SEQPESSOA,
          XX.NOMEREDUZIDO,
          B.NOMERAZAO,
          TO_CHAR(A.DTAENTRADA, 'MM')
