SELECT LPAD(T.NROCGCCPF,12,0)||LPAD(T.DIGCGCCPF,2,0) CNPJ_TOMADOR,   T.NOMERAZAO NOME_TOMADOR,
       LPAD(P.NROCGCCPF,12,0)||LPAD(P.DIGCGCCPF,2,0) CNPJ_PRESTADOR, P.NOMERAZAO NOME_PRESTADOR,
       X.NRONOTA, X.DTAEMISSAO, XI.CODPRODUTO COD_SERVICO, PD.DESCCOMPLETA DESC_SERVICO,
       X.VALOR VALOR_NOTA, NVL(X.VLRPIS,0) VLRPIS, NVL(X.VLRCOFINS,0) VLRCOFINS
  
  FROM OR_NFDESPESA X INNER JOIN OR_NFITENSDESPESA XI ON XI.SEQNOTA = X.SEQNOTA
                      INNER JOIN GE_PESSOA T ON T.SEQPESSOA = X.NROEMPRESA
                      INNER JOIN GE_PESSOA P ON P.SEQPESSOA = X.SEQPESSOA
                      INNER JOIN MAP_PRODUTO PD ON PD.SEQPRODUTO = XI.CODPRODUTO
                      
 WHERE X.CGO IN (6,11)
   AND X.DTAENTRADA BETWEEN SYSDATE - 365 AND SYSDATE
   AND X.SITUACAO = 'I'
      
UNION ALL

SELECT LPAD(T.NROCGCCPF,12,0)||LPAD(T.DIGCGCCPF,2,0) CNPJ_TOMADOR,   T.NOMERAZAO NOME_TOMADOR,
       LPAD(P.NROCGCCPF,12,0)||LPAD(P.DIGCGCCPF,2,0) CNPJ_PRESTADOR, P.NOMERAZAO NOME_PRESTADOR,
       X.NUMERONF, X.DTAEMISSAO, TO_CHAR(XI.SEQPRODUTO) COD_SERVIÇO, PD.DESCCOMPLETA DESC_SERVIÇO,
       FVALORTOTALNF(X.ROWID, 'N') VALOR, NVL(X.VLRPIS,0), NVL(X.VLRCOFINS,0)
       
  FROM MLF_NOTAFISCAL X INNER JOIN GE_PESSOA P ON P.SEQPESSOA = SEQPESSOATOMADORNFSE
                        INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
                        INNER JOIN MAP_PRODUTO PD ON PD.SEQPRODUTO = XI.SEQPRODUTO
                        INNER JOIN GE_PESSOA T ON T.SEQPESSOA = X.NROEMPRESA
                        
 WHERE CODGERALOPER IN (6,11)
   --AND X.NROEMPRESA IN (507)
   AND STATUSNF != 'C'
   AND X.DTAEMISSAO BETWEEN SYSDATE - 365 AND SYSDATE
