ALTER SESSION SET current_schema = CONSINCO;

select X.CAIXA_ENTRADA,
       X.ANO,
       X.MES,
       X.Cod_PART_IP,
       X.Cod_PART_IT,
       sum(X.TOT_VS) TOT_VS,
       sum(X.TOT_ISS) TOT_ISS,
       sum(X.TOT_OUTROS) TOT_OUTROS,
       X.EMISSAO,
       max(x.DTA_ALTERACAO) DTA_ALTERACAO
from CONSINCO.NAGV_CARTOESITWORKS_V2 X
where x.EMISSAO = :LT1
and x.CAIXA_ENTRADA in (SELECT lpad(Z.nrocgc,12,0)||lpad(Z.digcgc,2,0) FROM CONSINCO.GE_EMPRESA Z WHERE Z.NROEMPRESA IN (#LS1))
group by X.CAIXA_ENTRADA,
       X.ANO,
       X.MES,
       X.Cod_PART_IP,
       X.Cod_PART_IT,
           X.EMISSAO 

UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL  
       
         
UNION ALL

SELECT NULL, NULL, NULL, NULL, 'TOTAL', (
SELECT sum(X.TOT_VS) TOT_VS
  from CONSINCO.NAGV_CARTOESITWORKS_V2 X
where x.EMISSAO = :LT1
and x.CAIXA_ENTRADA in (SELECT lpad(Z.nrocgc,12,0)||lpad(Z.digcgc,2,0) FROM CONSINCO.GE_EMPRESA Z WHERE Z.NROEMPRESA IN (#LS1))),

(
SELECT sum(X.TOT_ISS) TOT_ISS
  from CONSINCO.NAGV_CARTOESITWORKS_V2 X
where x.EMISSAO = :LT1
and x.CAIXA_ENTRADA in (SELECT lpad(Z.nrocgc,12,0)||lpad(Z.digcgc,2,0) FROM CONSINCO.GE_EMPRESA Z WHERE Z.NROEMPRESA IN (#LS1))),
(
SELECT sum(X.TOT_OUTROS) TOT_OUTROS 
  from CONSINCO.NAGV_CARTOESITWORKS_V2 X
where x.EMISSAO = :LT1
and x.CAIXA_ENTRADA in (SELECT lpad(Z.nrocgc,12,0)||lpad(Z.digcgc,2,0) FROM CONSINCO.GE_EMPRESA Z WHERE Z.NROEMPRESA IN (#LS1)))

      ,NULL, NULL FROM DUAL
