-- Adicionar em MLFV_AUXNOTAFISCALINCONS

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT --(X.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                b.SEQPRODUTO PLU, X.NUMERONF,
                X.NROEMPRESA,
               /* 0   AS SEQAUXNFITEM,
                'L' AS BLOQAUTOR,
                80  AS CODINCONSISTENC,
                */
                L.M014_VL_QTDE_TRIB qTrib,
                L.M014_DS_UNID_TRIB uTrib,
                FD.PADRAOEMBCOMPRA                
      
  FROM CONSINCO.MLF_AUXNOTAFISCAL X INNER JOIN CONSINCO.MLF_AUXNFITEM B ON X.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                 INNER JOIN TMP_M000_NF K         ON K.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                                 INNER JOIN TMP_M014_ITEM L       ON L.M000_ID_NF = K.M000_ID_NF  AND L.M014_NR_ITEM = B.SEQITEMNFXML
                                 INNER JOIN MAP_PRODCODIGO X2     ON X2.SEQPRODUTO = B.SEQPRODUTO
                                 INNER JOIN MAP_PRODUTO P         ON P.SEQPRODUTO = B.SEQPRODUTO
                                 INNER JOIN MAP_FAMILIA F         ON F.SEQFAMILIA = P.SEQFAMILIA
                                 INNER JOIN MAP_FAMDIVISAO FD     ON FD.SEQFAMILIA = P.SEQFAMILIA

WHERE 1=1 
  AND X.DTAEMISSAO > SYSDATE - 10
  AND NVL(F.PESAVEL, 'N') = 'N'
  AND MOD(L.M014_VL_QTDE_TRIB,FD.PADRAOEMBCOMPRA) != 0
  AND X.SEQPESSOA > 999
  
