SELECT M.NROEMPRESA LOJA, TO_CHAR(VALOR_CREDITO,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_CREDITO, CASE WHEN VALOR_CREDITO IS NOT NULL THEN 'Apurada' ELSE 'Não Apurada' END STATUS_APURACAO, DTA DTA_ULT_APURACAO
  FROM (
SELECT X.NROEMPRESA LOJA, SUM(X.VALORDOCREDITO) VALOR_CREDITO, MAX(X.DTAATUALIZACUSTO) DTA
  FROM MRL_NFAPURAIMPOSTO X WHERE X.SEQCENARIO = 13
 GROUP BY X.NROEMPRESA) A  RIGHT JOIN MAX_EMPRESA M ON M.NROEMPRESA = A.LOJA 
 ORDER BY 1
