-- Criar crítica em MAD_CRITICAPEDCONFIG 
-- Inserir select em consinco.MADV_CRITICAPEDVENDA
-- Ticket 644720
-- Adicionado por Giuliano em 28/10/2025
-- CGO 261 nao permitido para lojas que nao forem UF RJ

SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'CGO 261 perm. apenas para RJ' CODCRITICA
   FROM CONSINCO.MAD_PEDVENDA A INNER JOIN MAD_PEDVENDAITEM I ON I.NROPEDVENDA = A.NROPEDVENDA AND I.NROEMPRESA = A.NROEMPRESA
                                INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
                                INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA

   WHERE 1=1
   AND A.SITUACAOPED != 'C' 
   AND A.CODGERALOPER = 261
   AND A.SEQPESSOA NOT IN (36,53)
   AND A.DTAINCLUSAO >= SYSDATE - 30
