SELECT DISTINCT X.NROEMPRESA EMPRESA, X.NUMERONF, X.SEQPESSOA||' - '||(SELECT NOMERAZAO FROM CONSINCO.GE_PESSOA Y WHERE Y.SEQPESSOA = X.SEQPESSOA) FORNECEDOR,
       TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') DTAENTRADA, TO_CHAR(X.DTAHORLANCTO, 'DD/MM/YYYY') DTALANCTO, X.DTAENTRADA - X.DTAEMISSAO DIF_DIAS, X.CODGERALOPER CGO, 
       CASE WHEN A.NROCARGARECEB IN (SELECT DISTINCT NROCARGARECEB FROM CONSINCO.MAD_CARGARECITEM Z 
                                      WHERE Z.NROEMPRESA = X.NROEMPRESA AND SEQATIVIDADEUSUARIO IS NULL AND NROCARGARECEB = A.NROCARGARECEB) 
                                 OR C.NROCARGARECEB IS NULL THEN 'MANUAL' ELSE 'COLETOR' END TIPO_CONFERENCIA
       
 FROM CONSINCO.MLF_NOTAFISCAL X LEFT JOIN CONSINCO.MAD_CARGARECEBNF C ON C.NUMERONF = X.NUMERONF           AND C.NROEMPRESA = X.NROEMPRESA
                                LEFT JOIN CONSINCO.MAD_CARGARECEB   A ON A.NROEMPRESA = C.NROEMPRESA       AND A.NROCARGARECEB = C.NROCARGARECEB
                                LEFT JOIN CONSINCO.MAD_CARGARECITEM B ON B.NROCARGARECEB = A.NROCARGARECEB AND B.NROEMPRESA = A.NROEMPRESA
WHERE X.SEQPESSOA < 999 

  AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
  AND X.NROEMPRESA IN (#LS1) 
  AND X.TIPNOTAFISCAL = 'E'
  AND X.CODGERALOPER IN (SELECT CODGERALOPER FROM CONSINCO.MAX_CODGERALOPER MC WHERE MC.TIPUSO = 'R')
  AND X.NROEMPRESA != X.SEQPESSOA
ORDER BY 1,2,3

