ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT X.SEQPRODUTO PLU, DESCCOMPLETA DESCRICAO, INDEANTRIBNFE EAN_TRIB_DANFE 

  FROM MAP_PRODCODIGO X LEFT JOIN MAP_PRODUTO M ON X.SEQPRODUTO = M.SEQPRODUTO

 WHERE X.SEQPRODUTO NOT IN (SELECT DISTINCT SEQPRODUTO FROM MAP_PRODCODIGO Z WHERE Z.TIPCODIGO = 'E' AND Z.INDEANTRIBNFE = 'S' AND Z.SEQPRODUTO = X.SEQPRODUTO)
   AND X.TIPCODIGO = 'E'
   AND X.SEQPRODUTO IS NOT NULL

       ORDER BY 2 ASC
