SELECT EMPRESA, PARTICIPANTE, NOME_PARTICIPANTE_PAGAMENTO, PARTICIPANTE_TRANS, NOME2 NOME_PARTICIPANTE_TRANS, 
       TOTAL_BRUTO_VENDAS,
       TOTAL_PREST_SERV,
       TO_CHAR(:DT1, 'DD/MM/YYYY') DATA_INICIAL, TO_CHAR(:DT2, 'DD/MM/YYYY') DATA_FINAL
     
  FROM (
SELECT :NR1 EMPRESA, COD_PART_IP PARTICIPANTE,
       CASE WHEN COD_PART_IP = '60701190280700' THEN 'BANCO ITAU'
            WHEN COD_PART_IP = '90400888153135' THEN 'BANCO SANTANDER'
            WHEN COD_PART_IP = '60746948150270' THEN 'BANCO BRADESCO'
            WHEN COD_PART_IP = '00000000695823' THEN 'BANCO DO BRASIL' ELSE 
       G1.NOMERAZAO END NOME_PARTICIPANTE_PAGAMENTO, COD_PART_IT PARTICIPANTE_TRANS, G2.NOMERAZAO NOME2,
       SUM(TOT_VS) TOTAL_BRUTO_VENDAS, SUM(TOT_ISS) TOTAL_PREST_SERV 
  FROM CONSINCO.NAGV_CARTOESITWORKS_V2 X LEFT JOIN CONSINCO.GE_PESSOA G1 ON LPAD(G1.NROCGCCPF,12,0)||LPAD(G1.DIGCGCCPF,2,0) = X.COD_PART_IP AND G1.STATUS = 'A'
                                         LEFT JOIN CONSINCO.GE_PESSOA G2 ON LPAD(G2.NROCGCCPF,12,0)||LPAD(G2.DIGCGCCPF,2,0) = X.COD_PART_IT
                                         
WHERE TO_DATE(EMISSAO, 'MM-YYYY') BETWEEN :DT1 AND :DT2 AND X.CAIXA_ENTRADA IN (SELECT LPAD(Z.NROCGC,12,0)||LPAD(Z.DIGCGC,2,0) FROM CONSINCO.GE_EMPRESA Z WHERE Z.NROEMPRESA IN (:NR1))

GROUP BY COD_PART_IP, G1.NOMERAZAO, COD_PART_IT, G2.NOMERAZAO) 

ORDER BY 2

          
          
