ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT NROEMPRESA EMPRESA, NUMERONF, (SELECT COUNT(SEQPRODUTO) FROM MLF_NFITEM XI WHERE XI.SEQNF = X.SEQNF) QTD_ITENS,
       X.SEQPESSOA||' - '||(SELECT NOMERAZAO FROM GE_PESSOA G WHERE G.SEQPESSOA = X.SEQPESSOA) FORNECEDOR, 
       TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') DATA_ENTRADA, X.USULANCTO, 'MREBOUCAS' USUALTERACAO
  FROM MLF_NOTAFISCAL X 
 WHERE 1=1
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
   AND EXISTS (SELECT 1 FROM MLF_AUXNOTAFISCAL_LOG L WHERE SEQNF = X.SEQNF AND USUALTERACAO = 'MREBOUCAS')

-- SELECT * FROM MLF_AUXNOTAFISCAL_LOG WHERE NUMERONF = 1471683 AND NROEMPRESA = 1
