-- Compara Lancto x Emissoes

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       NUMERONF, X.SEQPRODUTO, DESCCOMPLETA, VL VLR_LANCTO, VE VLR_EMITIDO, VE - VL DIF, QTD FROM (
SELECT LISTAGG(NUMERODF, ', ') WITHIN GROUP (ORDER BY NUMERODF) NUMERONF, A.SEQPRODUTO, (SELECT NVL(ROUND(SUM(Z.VALORLANCTOBRT * QTDLANCTO),2),0)
               FROM FATO_PERDA Z
              WHERE Z.NROEMPRESA =  14
                AND CODGERALOPER IN (20,30,33,34,35,41,46,47,62,63,66,90,91,110,111,112,113,114,263)
                AND Z.DTAOPERACAO BETWEEN DATE '2024-08-01' AND DATE '2024-08-31'
                AND Z.SEQPRODUTO = A.SEQPRODUTO) VL, SUM(VLRITEM) VE, SUM(QUANTIDADE) QTD
                
  FROM MFLV_BASEDFITEM A
    
 WHERE A.NUMERODF IN (42318,42319,42320,42322,42287,42289,42290,42291,42292,42293,42296,42303,42326)
   AND A.DTAEMISSAO BETWEEN DATE '2024-09-01' AND DATE '2024-09-20'
   AND CODGERALOPER IN (806,807)
   AND NROEMPRESA = 14

GROUP BY  A.SEQPRODUTO) X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO

 WHERE 1=1 AND VL != VE

----

-- ========= cTE ==========--

-- Compara Lancto x Emissoes

WITH cteEmpresa AS (SELECT 42           NROEMPRESA,
                      DATE '2025-07-01' INICIO,
                      DATE '2025-07-31' FIM,
                           34           CGO
                      FROM DUAL)

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       NUMERONF, X.SEQPRODUTO, DESCCOMPLETA, VL VLR_LANCTO, VE VLR_EMITIDO, VE - VL DIF, QTD QTD_NFE, QTD_LANCTO FROM (
       
SELECT LISTAGG(NUMERODF, ', ') WITHIN GROUP (ORDER BY NUMERODF) NUMERONF, A.SEQPRODUTO, (SELECT NVL(ROUND(SUM(Z.VALORLANCTOBRT * QTDLANCTO),2),0)
               FROM FATO_PERDA Z INNER JOIN cteEmpresa x ON x.NROEMPRESA = Z.NROEMPRESA AND Z.DTAOPERACAO BETWEEN INICIO AND FIM AND CODGERALOPER = x.CGO
              WHERE 1=1
                AND Z.SEQPRODUTO = A.SEQPRODUTO) VL, SUM(VLRITEM) VE, SUM(QUANTIDADE) QTD, 
              (SELECT NVL(ROUND(SUM(QTDLANCTO),2),0)
               FROM FATO_PERDA Z INNER JOIN cteEmpresa x ON x.NROEMPRESA = Z.NROEMPRESA AND Z.DTAOPERACAO BETWEEN INICIO AND FIM AND CODGERALOPER = x.CGO
              WHERE 2=2
                AND Z.SEQPRODUTO = A.SEQPRODUTO) QTD_LANCTO
                
  FROM MFLV_BASEDFITEM A INNER JOIN cteEmpresa x ON x.NROEMPRESA = A.NROEMPRESA
    
 WHERE A.NUMERODF   IN (23976) -- Inserir o numero das NFs emitidas referente ao CGO de perda da busca
   AND CODGERALOPER IN (806,807)

GROUP BY  A.SEQPRODUTO) X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO

 WHERE 1=1 AND VL != VE;
