SELECT X.SEQPESSOA COD_FORNEC,
       LISTAGG(DISTINCT X.NUMERONF, ', ') WITHIN GROUP (ORDER BY 1) NFS,
       XI.SEQPRODUTO PLU, P.DESCCOMPLETA, C.CCLASSTRIBCBS cClassTrib_C5, I.M014_DS_CCLASSTRIBCBS cClassTrib_XML,
       C.CENARIOCBS, C.CENARIOIBSUF
  FROM MLF_NOTAFISCAL X INNER JOIN TMP_M000_NF N ON N.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO 
                        INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
                        INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA 
                        INNER JOIN MAP_PRODCODIGO F ON F.SEQPRODUTO = XI.SEQPRODUTO AND F.TIPCODIGO = 'F' AND G.NROCGCCPF LIKE '%'||F.CGCFORNEC||'%'
                        INNER JOIN NAGV_PDV_CCT C ON C.SEQPRODUTO = XI.SEQPRODUTO
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = Xi.SEQPRODUTO
                        INNER JOIN TMP_M014_ITEM I ON I.M000_ID_NF = N.M000_ID_NF AND UPPER(F.CODACESSO)  = UPPER(I.M014_CD_PRODUTO) 
                        
 WHERE X.DTAEMISSAO BETWEEN :DT1 AND :DT2
   AND X.SEQPESSOA > 999
   AND X.NROEMPRESA IN (#LS1)
   AND NVL(C.CCLASSTRIBCBS,0) != NVL(I.M014_DS_CCLASSTRIBCBS,0)
   GROUP BY X.SEQPESSOA, XI.SEQPRODUTO, P.DESCCOMPLETA, C.CCLASSTRIBCBS, I.M014_DS_CCLASSTRIBCBS, C.CENARIOCBS, C.CENARIOIBSUF
   ORDER BY 4
