CREATE TABLE CONSINCO.MAP_PAUTAUFLOG_BACKUP AS 

SELECT * FROM CONSINCO.MAP_PAUTAUFLOG;
       
UPDATE CONSINCO.MAP_PAUTAUFLOG A SET A.TIPCALCPAUTA = 'M',
                            A.DTAALTERACAO = SYSDATE,
                            A.USUALTERACAO = 'TICKET_72781'
 WHERE DTAFIM >= SYSDATE ;
   
COMMIT;
