SELECT DISTINCT A.NROEMPRESA, A.SEQPESSOA||' - '||NOMERAZAO FORNEC, A.NUMERONF, CODGERALOPER CGO, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, TO_CHAR(DTAENTRADA, 'DD/MM/YYYY') DTAENTRADA, B.SEQPRODUTO,
       DESCCOMPLETA, L.M014_CD_EAN_TRIB COD_XML
       
  FROM CONSINCO.MLF_NOTAFISCAL A INNER JOIN CONSINCO.MLF_NFITEM B ON A.SEQNF = B.SEQNF
                                 INNER JOIN TMP_M000_NF K         ON K.M000_NR_CHAVE_ACESSO = A.NFECHAVEACESSO
                                 INNER JOIN TMP_M014_ITEM L       ON L.M000_ID_NF = K.M000_ID_NF  AND L.M014_NR_ITEM = B.SEQITEMNFXML
                                  LEFT JOIN MAP_PRODCODIGO X2     ON X2.SEQPRODUTO = B.SEQPRODUTO AND X2.TIPCODIGO = 'E' AND LPAD(X2.CODACESSO,13,0) = LPAD(NVL(L.M014_CD_EAN_TRIB,0),13,0)
                                 INNER JOIN MAP_PRODUTO P         ON P.SEQPRODUTO = B.SEQPRODUTO
                                 INNER JOIN GE_PESSOA G           ON G.SEQPESSOA = A.SEQPESSOA
                                 INNER JOIN MAP_FAMDIVISAO FD     ON FD.SEQFAMILIA = P.SEQFAMILIA

WHERE NOT EXISTS (SELECT 1 FROM MAP_PRODCODIGO X 
                   WHERE X.SEQPRODUTO = B.SEQPRODUTO 
                   AND LPAD(X.CODACESSO,13,0) = LPAD(NVL(L.M014_CD_EAN_TRIB,0),13,0) 
                   AND X.TIPCODIGO = 'E'
                   AND X.INDUTILVENDA = 'S')
        
  AND A.CODGERALOPER = 1
  AND A.SEQPESSOA > 999
  AND A.NROEMPRESA IN (#LS1)
  AND A.DTAENTRADA BETWEEN :DT1 AND :DT2
  AND FD.FINALIDADEFAMILIA = 'R'

--

SELECT DISTINCT X.NROEMPRESA, X.NUMERONF, X.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, XI.SEQPRODUTO, DESCCOMPLETA DESCRICAO, 
       XI.EMBALAGEM||' - '||XI.QTDEMBALAGEM EMB_NF, C.QTDEMBALAGEM EMB_TRIB_C5
  FROM CONSINCO.MLF_NOTAFISCAL X INNER JOIN CONSINCO.MLF_NFITEM XI ON XI.SEQNF = X.SEQNF 
                                 INNER JOIN CONSINCO.GE_PESSOA  G  ON G.SEQPESSOA = X.SEQPESSOA
                                 INNER JOIN CONSINCO.MAP_PRODUTO A ON A.SEQPRODUTO = XI.SEQPRODUTO
                                  LEFT JOIN CONSINCO.MAP_PRODCODIGO C ON C.SEQPRODUTO = XI.SEQPRODUTO AND C.INDEANTRIBNFE = 'S' AND TIPCODIGO = 'E'
 WHERE 1=1
   AND XI.QTDEMBALAGEM != 1
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND NOT EXISTS (SELECT 1 FROM CONSINCO.MAP_PRODCODIGO P WHERE P.INDEANTRIBNFE = 'S' AND P.SEQPRODUTO = XI.SEQPRODUTO AND P.QTDEMBALAGEM = XI.QTDEMBALAGEM)
   AND X.SEQPESSOA > 999
   AND X.NROEMPRESA IN (#LS1)
   
   ORDER BY X.NROEMPRESA, X.NUMERONF
