SELECT DISTINCT X.NROEMPRESA, X.NUMERONF, X.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, XI.SEQPRODUTO, DESCCOMPLETA DESCRICAO, 
       TT.M014_DS_UNID_COM EMB_XML, XI.EMBALAGEM EMB_LANCTO
  FROM CONSINCO.MLF_NOTAFISCAL X INNER JOIN CONSINCO.MLF_NFITEM XI ON XI.SEQNF = X.SEQNF 
                                 INNER JOIN CONSINCO.GE_PESSOA  G  ON G.SEQPESSOA = X.SEQPESSOA
                                 INNER JOIN CONSINCO.MAP_PRODUTO A ON A.SEQPRODUTO = XI.SEQPRODUTO
                                  LEFT JOIN CONSINCO.TMP_M000_NF T  ON  T.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO 
                                  LEFT JOIN CONSINCO.TMP_M014_ITEM TT ON TT.M000_ID_NF = T.M000_ID_NF AND TT.M014_NR_ITEM = XI.SEQITEMNF
 WHERE 1=1
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.SEQPESSOA  > 999
   AND X.NROEMPRESA IN (#LS1)
   AND    (UPPER(M014_DS_UNID_COM) IN ('UN','UNI','KG','UNID') 
       AND UPPER(XI.EMBALAGEM) NOT IN ('UN','UNI','KG','UNID') OR 
                UPPER(M014_DS_UNID_COM) NOT IN ('UN','UNI','KG','UNID') 
            AND UPPER(XI.EMBALAGEM) IN         ('UN','UNI','KG','UNID'))
   AND UPPER(M014_DS_UNID_COM) IN ('SC','SACO') 
       AND UPPER(XI.EMBALAGEM) NOT IN ('CX')
  /* AND CASE WHEN UPPER(TT.M014_DS_UNID_COM) IN ('CX','FD','PT','PCT','EMB','PCTE','SC','PCTS','PACOTE','PACOT','LT','LTA','LTS','LV','LP','LITRO','LI','LATA','FARDO','CXA') OR 
        UPPER(TT.M014_DS_UNID_COM) LIKE 'SD%' THEN 'CX' ELSE TT.M014_DS_UNID_COM END != 
       CASE WHEN UPPER(XI.EMBALAGEM)        IN ('CX','FD','PT','PCT','EMB','PCTE','SC','PCTS','PACOTE','PACOT','LT','LTA','LTS','LV','LP','LITRO','LI','LATA','FARDO','CXA') OR 
        UPPER(TT.M014_DS_UNID_COM) LIKE 'SD%' THEN 'CX' ELSE XI.EMBALAGEM END*/
  
   ORDER BY X.NROEMPRESA, X.NUMERONF
