SELECT SEQIDENTIFICA COD_PRODUTO, DESCCOMPLETA, DESCCAMPO, NVL(SUBSTR(VLRATUAL, 0,INSTR(VLRATUAL, ' -') -1), VLRATUAL) CODIGO, TO_CHAR(X.DTAAUDITORIA, 'DD/MM/YYYY') DTA_AUDITORIA, X.USUAUDITORIA
  FROM MAP_AUDITORIA X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQIDENTIFICA
                       INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA AND F.FINALIDADEFAMILIA IN ('U','A')
 WHERE CAMPO = 'CODACESSO'
   AND DESCCAMPO IN ('Inclusão do código de acesso', 'Exclusão do código de acesso')
   AND TRUNC(X.DTAAUDITORIA) BETWEEN :DT1 AND :DT2
