SELECT CI.SEQCENARIO CODCENARIO,
       CI.DESCRICAO,
       CI.ORIENTACAO,
       TO_CHAR(CI.DTAINICIALVALIDADE, 'DD/MM/YYYY') DTAINICIO_VALID,
       TO_CHAR(CI.DTAFINALVALIDADE, 'DD/MM/YYYY') DTAFIM_VALIDADE,
       TO_CHAR(CI.DTAHORINCLUSAO, 'DD/MM/YYYY HH24:MI') DTAHORINCLUSAO,
       CI.STATUS,
       CI.PONTOSBUSCA,
       CI.USUINCLUSAO,
       TO_CHAR(CI.DTAHORULTIMAALTERACAO, 'DD/MM/YYYY HH24:MI') DTAHORALTERACAO,
       CI.USUULTIMAALTERACAO,
       CI.SEQIMPOSTO
       
  FROM CONSINCO.CCT_CENARIO CI
 WHERE 1 = 1
   AND CI.SEQCENARIO IN (#LS1)
