-- Criar crítica em MAD_CRITICAPEDCONFIG
-- Inserir select em MADV_CRITICAPEDVENDA

-- Ticket 645053
-- Adicionado por Giuliano em 23/10/2025
-- CGO 64 barra Uso Ativo/Consumo

SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'Revenda/Embal. Nao Perm CGO 60' CODCRITICA
   FROM CONSINCO.MAD_PEDVENDA A INNER JOIN MAD_PEDVENDAITEM I ON I.NROPEDVENDA = A.NROPEDVENDA AND I.NROEMPRESA = A.NROEMPRESA
                                INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
                                INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA

   WHERE 1=1
   AND A.SITUACAOPED != 'C'
   AND F.FINALIDADEFAMILIA IN ('R','E')
   AND A.CODGERALOPER = 60
   AND A.DTAINCLUSAO >= SYSDATE - 30
