SELECT A.CAIXAENTRADA,
       A.CNPJCPFEMITENTE,
       A.SERIE,
       A.TIPO,
       SUM(A.VLR_LIQUIDO)    VLR_LIQUIDO,
       SUM(A.VLR_TOTAL)      VLR_TOTAL,
       SUM(A.VLR_DESCONTOS)  VLR_DESCONTOS,
       SUM(A.VLR_ACRESCIMOS) VLR_ACRESCIMOS,
       A.DTA_EMISSAO,
       A.DTA_LANCTO,
       TO_CHAR(A.DTA_ALTERACAO, 'DD/MM/YYYY') DTA_ALTERACAO,
       A.CODPRODUTO,
       A.DESCRICAO
  FROM CONSINCO.NAGV_LOCACAOITWORKS
  
  WHERE DTA_LANCTO BETWEEN :DT1 AND :DT2

AND CAIXAENTRADA IN (SELECT LPAD(A.NROCGC,12,0)||LPAD(A.DIGCGC,2,0) FROM CONSINCO.GE_EMPRESA A WHERE A.NROEMPRESA IN (#LS1))

GROUP BY 
       A.CAIXAENTRADA,
       A.CNPJCPFEMITENTE,
       A.SERIE,
       A.TIPO,
       A.DTA_EMISSAO,
       A.DTA_LANCTO,
       TO_CHAR(A.DTA_ALTERACAO, 'DD/MM/YYYY'),
       A.CODPRODUTO,
       A.DESCRICAO
       
 ORDER BY DTA_LANCTO DESC
