SELECT A.NROEMPRESA,
          TO_CHAR(A.DTAENTRADA, 'DD/MM/YYYY') DTAENTRADA, D.SEQFAMILIA,
          A.NUMERONF,
          C.NOMERAZAO,
          B.SEQPRODUTO,
          B.QUANTIDADE, 
          D.DESCCOMPLETA,
          L.M014_DM_ORIG_ICMS CODORIGEM_XML, 
          NVL((SELECT SUBSTR(VLRATUAL,0,1) FROM (SELECT * 
                 FROM CONSINCO.MAP_AUDITORIA X 
                WHERE TABELA = 'MAP_FAMDIVISAO' 
                  AND CAMPO = 'CODORIGEMTRIB' 
                  AND SEQIDENTIFICA =  V.SEQFAMILIA 
                  AND X.DTAAUDITORIA < A.DTAENTRADA 
                  ORDER BY DTAAUDITORIA DESC)
                  WHERE ROWNUM = 1), V.CODORIGEMTRIB) CODORIGEM_C5
             
    FROM CONSINCO.MLF_NOTAFISCAL A INNER JOIN CONSINCO.TMP_M000_NF K ON K.M000_NR_CHAVE_ACESSO = A.NFECHAVEACESSO
                                   INNER JOIN CONSINCO.MLF_NFITEM B  ON B.SEQNF = A.SEQNF AND B.NROEMPRESA = A.NROEMPRESA 
                                   INNER JOIN CONSINCO.TMP_M014_ITEM L ON L.M000_ID_NF = K.M000_ID_NF AND L.M014_CD_PRODUTO = B.SEQPRODUTO
                                   INNER JOIN CONSINCO.GE_PESSOA C ON A.SEQPESSOA = C.SEQPESSOA
                                   INNER JOIN CONSINCO.MAP_PRODUTO D ON D.SEQPRODUTO = B.SEQPRODUTO
                                   INNER JOIN CONSINCO.MAP_FAMDIVISAO V ON V.SEQFAMILIA = D.SEQFAMILIA
 WHERE 1=1
   AND A.TIPNOTAFISCAL = 'E'
   AND A.NROEMPRESA IN (#LS1)
   AND B.SEQPRODUTO = :NR1
   AND A.DTAENTRADA BETWEEN  :DT1 AND :DT2
   
   ORDER BY DTAENTRADA DESC,A.NROEMPRESA, A.NUMERONF
   
   
   
