SELECT DISTINCT A.NROEMPRESA, A.SEQPESSOA||' - '||NOMERAZAO FORNEC, A.NUMERONF, CODGERALOPER CGO, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, TO_CHAR(DTAENTRADA, 'DD/MM/YYYY') DTAENTRADA, B.SEQPRODUTO,
       DESCCOMPLETA, L.M014_CD_EAN_TRIB COD_XML, X2.CODACESSO EAN_UCC_CADASTRO
      
  FROM CONSINCO.MLF_NOTAFISCAL A INNER JOIN CONSINCO.MLF_NFITEM B ON A.SEQNF = B.SEQNF
                                 INNER JOIN TMP_M000_NF K         ON K.M000_NR_CHAVE_ACESSO = A.NFECHAVEACESSO
                                 INNER JOIN TMP_M014_ITEM L       ON L.M000_ID_NF = K.M000_ID_NF  AND L.M014_NR_ITEM = B.SEQITEMNFXML
                                 INNER JOIN MAP_PRODCODIGO X2     ON X2.SEQPRODUTO = B.SEQPRODUTO
                                 INNER JOIN MAP_PRODUTO P         ON P.SEQPRODUTO = B.SEQPRODUTO
                                 INNER JOIN GE_PESSOA G           ON G.SEQPESSOA = A.SEQPESSOA
                                 INNER JOIN MAP_FAMDIVISAO FD     ON FD.SEQFAMILIA = P.SEQFAMILIA

WHERE 1=1 
  AND NOT EXISTS (SELECT 1 FROM MAP_PRODCODIGO X 
                   WHERE X.SEQPRODUTO = B.SEQPRODUTO 
                   AND LPAD(X.CODACESSO,14,0) = LPAD(NVL(L.M014_CD_EAN_TRIB,0),14,0) 
                   AND X.TIPCODIGO = 'E'
                   AND X.INDUTILVENDA = 'S')
       
  AND A.CODGERALOPER = 1
  AND A.SEQPESSOA > 999
  AND A.NROEMPRESA IN (#LS1)
  AND A.DTAENTRADA BETWEEN :DT1 AND :DT2
  AND FD.FINALIDADEFAMILIA = 'R'
  AND X2.TIPCODIGO = 'E'
  AND X2.INDUTILVENDA = 'S'
  AND LPAD(X2.CODACESSO,14,0) != LPAD(NVL(L.M014_CD_EAN_TRIB,0),14,0)
