-- Alteração na CONSINCO.MLFV_AUXNOTAFISCALINCONS
-- Ticket 204660 - Adicionado por Giuliano - Solic Danielle 30/03
-- Regra: Trava Cod Origem XML = 0 e C5 1,2,3,8 || OU || XML: 2,3,7 e C5 0,4,5,7

SELECT DISTINCT (A.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                A.NUMERONF,
                A.NROEMPRESA,
                0   AS SEQAUXNFITEM,
                'L' AS BLOQAUTOR,
                65  AS CODINCONSISTENC,
                'Produto: '||B.SEQPRODUTO||' com Cod. Origem incorreto, abrir chamado para o Depto. Fiscal Cad. Trib. para correção - XML: '||L.M014_DM_ORIG_ICMS||' - C5: '||D.CODORIGEMTRIB  MENSAGEM

  FROM CONSINCO.MLF_AUXNOTAFISCAL A INNER JOIN CONSINCO.MLF_AUXNFITEM B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                    INNER JOIN CONSINCO.MAP_PRODUTO C ON B.SEQPRODUTO = C.SEQPRODUTO
                                    INNER JOIN CONSINCO.MAP_FAMILIA E ON E.SEQFAMILIA = C.SEQFAMILIA
                                    INNER JOIN CONSINCO.MAP_FAMDIVISAO D ON D.SEQFAMILIA = E.SEQFAMILIA
                                    INNER JOIN TMP_M000_NF K ON (K.M000_NR_CHAVE_ACESSO = A.NFECHAVEACESSO)
                                    INNER JOIN TMP_M014_ITEM L ON (L.M000_ID_NF = K.M000_ID_NF AND L.M014_NR_ITEM = B.SEQITEMNFXML)

WHERE L.M014_DM_ORIG_ICMS = 0        AND D.CODORIGEMTRIB IN (1,2,3,8)   AND A.SEQPESSOA > 999
   OR L.M014_DM_ORIG_ICMS IN (1,2,3,8) AND D.CODORIGEMTRIB IN (0,4,5,7) AND A.SEQPESSOA > 999
;
