-- Adicionado por Giuliano
-- 21/08/2025 - Ticket 621463
-- Críticas de FCP incorreto

SELECT DISTINCT (X.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                X.NUMERONF,
                X.NROEMPRESA,
                0   AS SEQAUXNFITEM,
                'L' AS BLOQAUTOR,
                91  AS CODINCONSISTENC,
               'Base FCP Distrib Incorreta - Prod.: '||XI.SEQPRODUTO||'  Valor na NF: '||TO_CHAR(BASEFCPDISTRIB,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')||
               ' - Valor Correto: '||TO_CHAR(XI.BASICMSSTDISTRIB,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')||
               ' | Entre em contato com Departamento Fiscal' MENSAGEM

  FROM MLF_AUXNOTAFISCAL X INNER JOIN MLF_AUXNFITEM XI ON X.SEQAUXNOTAFISCAL = XI.SEQAUXNOTAFISCAL

WHERE 1=1
 AND X.DTAEMISSAO >= SYSDATE - 30
 AND X.SEQPESSOA > 999
 AND NVL(XI.BASEFCPDISTRIB,0) > 0
 AND NVL(XI.BASEFCPDISTRIB,0) != NVL(XI.BASICMSSTDISTRIB,0)
