ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT EMPRESA, PARTICIPANTE, NOME_PART_PAGTO, PARTICIP_TRANS, NOME_PART_TRANSACAO,
       -- SUM para agrupar com o tratamento das empresas do grupo
       TO_CHAR(SUM(TOTAL_BRUTO_VENDAS), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')        TOTAL_BRUTO_VENDAS,
       TO_CHAR(SUM(TOTAL_PRESTACOES_SERVICOS), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_PRESTACOES_SERVICOS,
       TO_CHAR(:DT1, 'DD/MM/YYYY') DATA INICIAL, 
       TO_CHAR(:DT2, 'DD/MM/YYYY') DATA_FINAL,
       TO_CHAR(SUBTOTAL_VENDAS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')   SUBTOTAL_VENDAS,
       TO_CHAR(SUBTOTAL_SERVICOS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') SUBTOTAL_SERVICOS, 
       TO_CHAR(SUBTOTAL_VENDAS + SUBTOTAL_SERVICOS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL
  FROM (
SELECT EMPRESA, 
       -- Tratamento CNPJ Bradesco  - Empresas do Grupo - Ticket 175866
       CASE WHEN PARTICIPANTE IN (SELECT LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0)
                                    FROM GE_PESSOA WHERE SEQPESSOA < 999) THEN '60746948150270' ELSE PARTICIPANTE END PARTICIPANTE,
       -- Tratamento Razão Bradesco - Empresas do Grupo - Ticket 175866
       CASE WHEN PARTICIPANTE IN (SELECT LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) 
                                    FROM GE_PESSOA WHERE SEQPESSOA < 999) THEN 'BRADESCO S.A'   ELSE NOME_PART_PAGTO END NOME_PART_PAGTO, 
       PARTICIP_TRANS, NOME_PART_TRANSACAO,
       TOTAL_BRUTO_VENDAS, 
       TOTAL_PRESTACOES_SERVICOS, 
       
       -- Select para pegar o subtotal de vendas e montar o relatorio QRP
      (SELECT SUM(TOTAL_BRUTO_VENDAS)
         FROM (SELECT CASE WHEN A.NROEMPRESA >= 500 THEN 0 ELSE SUM(A.VLRORIGINAL) END TOTAL_BRUTO_VENDAS

        FROM CONSINCO.FI_TITULO A
        INNER JOIN CONSINCO.GE_PESSOA  B ON (A.SEQPESSOA  = B.SEQPESSOA)
        INNER JOIN CONSINCO.GE_EMPRESA C ON (A.NROEMPRESA = C.NROEMPRESA)
        LEFT  JOIN CONSINCO.GE_PESSOA  D ON LPAD(D.NROCGCCPF,12,0)||LPAD(D.DIGCGCCPF,2,0) = (
             CASE WHEN A.CODESPECIE IN ('IFOOD','IFOPDV') THEN LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0)
                  WHEN A.CODESPECIE IN ('CCECOM','CDECOM','TKECOM') THEN '14071169000147'
                  ELSE NULL END)
        WHERE A.CODESPECIE IN ('CARDEB', 'CARTAO', 'TICKET', 'CCECOM', 'CDECOM', 'TKECOM','IFOOD','IFOPDV','SERVRC','AMERIC')
          AND A.SITUACAO   != 'C'     
          AND B.SEQPESSOA  NOT IN (1457426,942508) -- 942508 será tratado no subtotal de serviços
          AND A.DTAEMISSAO BETWEEN :DT1 AND :DT2
          AND A.NROEMPRESA = :NR1  
          GROUP BY A.NROEMPRESA, CODESPECIE
          
        UNION ALL -- Vendas em Boletos Ticket 150453
    
        SELECT SUM(X.VLRORIGINAL)
        FROM FI_TITULO X INNER JOIN FI_ESPECIE K ON (K.CODESPECIE = X.CODESPECIE AND X.NROEMPRESAMAE = K.NROEMPRESAMAE )
                         INNER JOIN GE_EMPRESA C ON (C.NROEMPRESA = X.NROEMPRESA)
                         INNER JOIN GE_PESSOA B ON (X.SEQPESSOA = B.SEQPESSOA)
        WHERE X.OBRIGDIREITO = 'D'
        AND EXISTS (SELECT 1 FROM FI_COMPLTITULO Y WHERE X.SEQTITULO = Y.SEQTITULO AND  Y.CODBARRA IS NOT NULL)
        AND X.SEQPESSOA <> C.SEQPESSOA AND X.SEQPESSOA NOT IN (942508)
        AND X.CODESPECIE NOT IN ('SERVRC') -- Já é tratado na view do CD de Serviços
        AND X.APPORIGEM = 'F'              -- Apenas origem de faturamento, demais são extratos PDV e não devem ir
        AND X.SITUACAO != 'C'              
        AND NVL(K.ESPDEVOLUCAO,'N') = 'N'  -- Não seja Devolução
        AND X.NROEMPRESA = :NR1
        AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2

        UNION ALL -- Vendas em PIX Ticket 150453

        SELECT SUM(T.VLRLANCAMENTO), NULL
               
        FROM FI_CTACORLANCA T INNER JOIN FI_CTACORRENTE X ON (T.SEQCTACORRENTE = X.SEQCTACORRENTE)
                              INNER JOIN GE_EMPRESA Z ON (Z.NROEMPRESA = T.NROEMPRESA)
                              LEFT JOIN GE_PESSOA C ON X.SEQPESSOANOTA = C.SEQPESSOA
        WHERE 1=1
        AND X.TIPOCONTA = 'B'            -- Apenas credito na bancaria
        AND T.CODOPERACAO IN (452, 948)  -- Apenas operação PIX
        AND T.ORIGEMDOC = 'TSN'          -- Apenas Origem Tesouraria
        AND T.OPCANCELADA IS NULL
        AND T.NROEMPRESA = :NR1
        AND T.DTALANCTO BETWEEN :DT1 AND :DT2)) SUBTOTAL_VENDAS, -- Fim Subtotal Vendas
        
       -- Select para pegar o subtotal de serviços e montar o relatorio QRP
       (SELECT SUM(TOTAL_PREST_SERV) FROM (

        SELECT CASE WHEN A.CODESPECIE IN ('SERVRC') THEN SUM(NVL(A.VLRORIGINAL,0)) ELSE 0 END TOTAL_PREST_SERV

        FROM CONSINCO.FI_TITULO A
        INNER JOIN CONSINCO.GE_PESSOA B  ON (A.SEQPESSOA = B.SEQPESSOA)
        INNER JOIN CONSINCO.GE_EMPRESA C ON (A.NROEMPRESA = C.NROEMPRESA)
        LEFT  JOIN CONSINCO.GE_PESSOA D ON LPAD(D.NROCGCCPF,12,0)||LPAD(D.DIGCGCCPF,2,0) = (
             CASE WHEN A.CODESPECIE IN ('IFOOD','IFOPDV') THEN LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0)
                  WHEN A.CODESPECIE IN ('CCECOM','CDECOM','TKECOM') THEN '14071169000147'
                  ELSE NULL END)
        WHERE A.CODESPECIE IN ('CARDEB', 'CARTAO', 'TICKET', 'CCECOM', 'CDECOM', 'TKECOM','IFOOD','IFOPDV','SERVRC','AMERIC')
          AND A.SITUACAO != 'C'     AND B.SEQPESSOA NOT IN (1457426,942508) -- 942508 + será tratada no union abaixo
          AND A.DTAEMISSAO BETWEEN :DT1 AND :DT2
          AND A.NROEMPRESA = :NR1 
          
          GROUP BY  CODESPECIE
          
        UNION ALL -- Apenas retorna os dados de cartões que foram recebidos das administaroads que pagaram o escationamento com cartão
          
        SELECT SUM(NVL(A.VLRORIGINAL,0)) TOT_ISS

        FROM CONSINCO.FI_TITULO A INNER JOIN CONSINCO.GE_PESSOA B ON (A.SEQPESSOA = B.SEQPESSOA)
                                 INNER JOIN CONSINCO.GE_EMPRESA C ON (A.NROEMPRESA = C.NROEMPRESA)

        WHERE 1=1
        AND A.SITUACAO != 'C'
        AND A.DTAEMISSAO BETWEEN :DT1 AND :DT2
        -- Não repetir os títulos
        AND A.SEQTITULO IN (
        SELECT K.SEQTITULO FROM CONSINCO.FI_TITOPERACAO K WHERE K.CODOPERACAO IN (18) AND K.NROPROCESSO IN ( SELECT X.NROPROCESSO
        FROM CONSINCO.FI_TITOPERACAO X WHERE X.CODESPECIEANT = 'SERVRC' AND X.OPCANCELADA IS NULL 
        AND X.CODOPERACAO = 20 AND X.NROEMPRCTAPARTIDA NOT IN (501))) -- Apenas títulos recebidos em cartão das notas de estacionamento
        
     )) SUBTOTAL_SERVICOS -- Fim Subtotal Serviços
    
-- Início do select normal da view

FROM (
SELECT Y.* FROM (

SELECT * FROM (

SELECT NROEMPRESA EMPRESA , PARTICIPANTE, NOME_PART_PAGTO, PARTICIP_TRANS, NOME_PART_TRANSACAO, 
       SUM(TOTAL_BRUTO_VENDAS) TOTAL_BRUTO_VENDAS, 
       SUM(TOTAL_PRESTACOES_SERVICOS) TOTAL_PRESTACOES_SERVICOS 
       
       FROM ( 

SELECT A.NROEMPRESA, LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0) PARTICIPANTE,
       SUBSTR(B.NOMERAZAO,1,32) NOME_PART_PAGTO,
       CASE WHEN A.CODESPECIE IN ('IFOOD','IFOPDV') THEN LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0)
            WHEN A.CODESPECIE IN ('CCECOM','CDECOM','TKECOM') THEN '14071169000147'
              ELSE NULL END PARTICIP_TRANS,
       SUBSTR(D.NOMERAZAO,1,32) NOME_PART_TRANSACAO,
       CASE WHEN A.NROEMPRESA >= 500 THEN 0 ELSE SUM(A.VLRORIGINAL) END TOTAL_BRUTO_VENDAS,
       CASE WHEN A.CODESPECIE IN ('SERVRC') THEN SUM(NVL(A.VLRORIGINAL,0)) ELSE 0 END 
       TOTAL_PRESTACOES_SERVICOS

  FROM CONSINCO.FI_TITULO A
  INNER JOIN CONSINCO.GE_PESSOA B  ON (A.SEQPESSOA = B.SEQPESSOA)
  INNER JOIN CONSINCO.GE_EMPRESA C ON (A.NROEMPRESA = C.NROEMPRESA)
  LEFT  JOIN CONSINCO.GE_PESSOA D ON LPAD(D.NROCGCCPF,12,0)||LPAD(D.DIGCGCCPF,2,0) = (
       CASE WHEN A.CODESPECIE IN ('IFOOD','IFOPDV') THEN LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0)
            WHEN A.CODESPECIE IN ('CCECOM','CDECOM','TKECOM') THEN '14071169000147'
            ELSE NULL END)

  WHERE A.CODESPECIE IN ('CARDEB', 'CARTAO', 'TICKET', 'CCECOM', 'CDECOM', 'TKECOM','IFOOD','IFOPDV','SERVRC','AMERIC')
    AND A.SITUACAO != 'C'     
    AND B.SEQPESSOA NOT IN (1457426,942508) -- 942508 será tratado no select de serviços
    AND A.DTAEMISSAO BETWEEN :DT1 AND :DT2
    AND A.NROEMPRESA = :NR1
    
GROUP BY LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0), B.NOMERAZAO, A.CODESPECIE, D.NOMERAZAO, A.NROEMPRESA

   UNION ALL  -- Apenas retorna os dados de cartões que foram recebidos das administaroads que pagaram o escationamento com cartão
   
   SELECT A.NROEMPRESA,

         LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0) COD_PART_IP,
         B.NOMERAZAO, NULL, NULL,
         0 ,
         SUM(NVL(A.VLRORIGINAL,0)) TOT_ISS

      FROM CONSINCO.FI_TITULO A INNER JOIN CONSINCO.GE_PESSOA B ON (A.SEQPESSOA = B.SEQPESSOA)
                                INNER JOIN CONSINCO.GE_EMPRESA C ON (A.NROEMPRESA = C.NROEMPRESA)

   WHERE 1=1
   AND A.SITUACAO != 'C'
   AND A.DTAEMISSAO BETWEEN :DT1 AND :DT2
   AND A.SEQTITULO IN (
   SELECT K.SEQTITULO FROM CONSINCO.FI_TITOPERACAO K WHERE K.CODOPERACAO IN (18) AND K.NROPROCESSO IN ( SELECT X.NROPROCESSO
   FROM CONSINCO.FI_TITOPERACAO X WHERE X.CODESPECIEANT = 'SERVRC' AND X.OPCANCELADA IS NULL 
   AND X.CODOPERACAO = 20 AND X.NROEMPRCTAPARTIDA NOT IN (501))) -- Apenas títulos recebidos em cartão das notas de estacionamento
   
   GROUP BY  LPAD(C.NROCGC,12,0)||LPAD(C.DIGCGC,2,0) ,  TO_CHAR(A.DTAEMISSAO, 'YYYY'), TO_CHAR(A.DTAEMISSAO, 'MM'), LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0), B.NOMERAZAO, A.CODESPECIE,A.NROEMPRESA,TO_CHAR(A.DTAEMISSAO, 'MM-YYYY')
   )

   GROUP BY NROEMPRESA, PARTICIPANTE, NOME_PART_PAGTO, PARTICIP_TRANS, NOME_PART_TRANSACAO

   ) ORDER BY 2) Y

 UNION ALL  -- Vendas em Boletos Ticket 150453

   SELECT X.NROEMPRESA, 
          LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0), 
          SUBSTR(B.NOMERAZAO,1,32),
          NULL, NULL,
          SUM(X.VLRORIGINAL) TOT_VS,
          0   TOT_ISS

   FROM FI_TITULO X INNER JOIN FI_ESPECIE K ON (K.CODESPECIE = X.CODESPECIE AND X.NROEMPRESAMAE = K.NROEMPRESAMAE )
                                INNER JOIN GE_EMPRESA C ON (C.NROEMPRESA = X.NROEMPRESA)
                                INNER JOIN GE_PESSOA B ON (X.SEQPESSOA = B.SEQPESSOA)
   WHERE X.OBRIGDIREITO = 'D'
   AND EXISTS (SELECT 1 FROM FI_COMPLTITULO Y WHERE X.SEQTITULO = Y.SEQTITULO AND  Y.CODBARRA IS NOT NULL)
   AND X.SEQPESSOA <> C.SEQPESSOA
   AND X.CODESPECIE NOT IN ('SERVRC') -- Já é tratado na view do CD de Serviços
   AND X.APPORIGEM = 'F'              -- Apenas origem de faturamento, demais são extratos PDV e não devem ir
   AND NVL(K.ESPDEVOLUCAO,'N') = 'N'  -- Não seja Devolução
   AND X.NROEMPRESA = :NR1
   AND X.SITUACAO != 'C'
   AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2     
   GROUP BY  NOMERAZAO,LPAD(C.NROCGC,12,0)||LPAD(C.DIGCGC,2,0) ,  TO_CHAR(X.DTAEMISSAO, 'YYYY'), TO_CHAR(X.DTAEMISSAO, 'MM'), LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0), X.CODESPECIE,X.NROEMPRESA,TO_CHAR(X.DTAEMISSAO, 'MM-YYYY')

   
 UNION ALL -- Vendas em PIX Ticket 150453

   SELECT T.NROEMPRESA, LPAD(Z.NROCGC,12,0)||LPAD(Z.DIGCGC,2,0), 
          SUBSTR(C.NOMERAZAO,1,32), NULL, NULL,
          SUM(T.VLRLANCAMENTO),
          0 

   FROM FI_CTACORLANCA T INNER JOIN FI_CTACORRENTE X ON (T.SEQCTACORRENTE = X.SEQCTACORRENTE)
                                                INNER JOIN GE_EMPRESA Z ON (Z.NROEMPRESA = T.NROEMPRESA)
                                                LEFT JOIN GE_PESSOA C ON T.NROEMPRESA = C.SEQPESSOA
   WHERE 1=1
   AND X.TIPOCONTA = 'B'           -- Apenas credito na bancaria
   AND T.CODOPERACAO IN (452, 948) -- Apenas operações PIX
   AND T.ORIGEMDOC = 'TSN'         -- Apenas origem Tesouraria
   AND T.OPCANCELADA IS NULL
   AND T.NROEMPRESA = :NR1
   AND T.DTALANCTO BETWEEN :DT1 AND :DT2
   GROUP BY NOMERAZAO,LPAD(Z.NROCGC,12,0)||LPAD(Z.DIGCGC,2,0) ,  
   TO_CHAR(T.DTALANCTO, 'YYYY'), TO_CHAR(T.DTALANCTO, 'MM'),  T.NROEMPRESA,TO_CHAR(T.DTALANCTO, 'MM-YYYY') 

   ) X ) ZZ

GROUP BY EMPRESA, PARTICIPANTE, NOME_PART_PAGTO, PARTICIP_TRANS, NOME_PART_TRANSACAO,
         SUBTOTAL_VENDAS, 
         SUBTOTAL_SERVICOS

ORDER BY 3 ASC
