SELECT DISTINCT X.NROEMPRESA, X.NUMERONF, X.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, XI.SEQPRODUTO, DESCCOMPLETA DESCRICAO, 
       TT.M014_DS_UNID_COM EMB_XML, TO_NUMBER(TT.M014_VL_QTDE_COM) QTD_EMB_XML, 
       XI.EMBALAGEM EMB_LANCTO, TO_NUMBER(QUANTIDADE / XI.QTDEMBALAGEM) QTD_EMB_LANCTO
  FROM CONSINCO.MLF_NOTAFISCAL X INNER JOIN CONSINCO.MLF_NFITEM XI ON XI.SEQNF = X.SEQNF 
                                 INNER JOIN CONSINCO.GE_PESSOA  G  ON G.SEQPESSOA = X.SEQPESSOA
                                 INNER JOIN CONSINCO.MAP_PRODUTO A ON A.SEQPRODUTO = XI.SEQPRODUTO
                                  LEFT JOIN CONSINCO.TMP_M000_NF T  ON  T.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO 
                                  LEFT JOIN CONSINCO.TMP_M014_ITEM TT ON TT.M000_ID_NF = T.M000_ID_NF AND TT.M014_NR_ITEM = XI.SEQITEMNF
 WHERE 1=1
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.SEQPESSOA  > 999
   AND X.NROEMPRESA IN (#LS1)
   AND TT.M014_VL_QTDE_COM != (QUANTIDADE / XI.QTDEMBALAGEM)
  
   ORDER BY X.NROEMPRESA, X.NUMERONF
