SELECT P.SEQPRODUTO COD_PRODUTO, F.CODNBMSH NCM, FD.CODORIGEMTRIB, ROUND(X.PERACRESCST,2) MVA
   FROM MAP_PRODUTO P INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                      INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = F.SEQFAMILIA
                      INNER JOIN MAP_TRIBUTACAOUF X ON X.NROTRIBUTACAO = FD.NROTRIBUTACAO AND X.UFEMPRESA = 'SP' AND UFCLIENTEFORNEC = 'SP' AND X.TIPTRIBUTACAO = 'EI' AND X.NROREGTRIBUTACAO = 0
                      
                      AND EXISTS (SELECT 1 FROM MRL_PRODEMPSEG S WHERE S.SEQPRODUTO = P.SEQPRODUTO AND S.STATUSVENDA = 'A')
                      
