SELECT COD_NATUREZA, DESC_NATUREZA, FORNECEDOR, CIDADE, 
       INDCALCISSQN,     TO_CHAR(ALIQISSQN,    'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQISSQN, 
       INDCALCIRPESFIS,  TO_CHAR(ALIQIRPESFIS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQIRPESFIS, 
       INDCALCIRPESJUR,  TO_CHAR(ALIQIRPESJUR, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQIRPESJUR, 
       INDCALCINSSJUR,   TO_CHAR(ALIQINSSJUR,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQINSSJUR, 
       INDCALCPISCOFINS, TO_CHAR(ALIQ_PIS,     'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQ_PIS, TO_CHAR(ALIQ_COFINS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQ_COFINS, 
       INDCALCCSLL,      TO_CHAR(ALIQCSSLL,    'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ALIQCSSLL
       
 FROM (

SELECT A.CODHISTORICO COD_NATUREZA,
       DESCRICAO DESC_NATUREZA,
       C.SEQPESSOA || ' - ' || C.NOMERAZAO FORNECEDOR,
       B.CIDADE || ' - ' || B.UF CIDADE,
       A.INDCALCISSQN,
       A.ALIQISSQN,
       A.INDCALCIRPESFIS,
       CASE WHEN A.INDCALCIRPESFIS = 'S' THEN D.ALIQIRPESFIS END ALIQIRPESFIS,
       A.INDCALCIR INDCALCIRPESJUR,
       CASE WHEN A.INDCALCIR = 'S' THEN D.ALIQIR END ALIQIRPESJUR,
       A.INDCALCINSSJUR,
       A.ALIQINSSJUR,
       A.INDCALCPISCOFINSRET INDCALCPISCOFINS,
       CASE WHEN A.INDCALCPISCOFINSRET = 'S' THEN O.PERCPIS END ALIQ_PIS,
       CASE WHEN A.INDCALCPISCOFINSRET = 'S' THEN O.PERCCOFINS END ALIQ_COFINS,
       A.INDCALCCSLL, CASE WHEN A.INDCALCCSLL = 'S' THEN O.PERCCSSLL END ALIQCSSLL
       
  FROM RF_PARAMNATNFDESP_FORN A INNER JOIN GE_CIDADE B ON A.SEQCIDADE = B.SEQCIDADE
                                INNER JOIN GE_PESSOA C ON C.SEQPESSOA = A.SEQFORNECEDOR
                                INNER JOIN RF_PARAMNATNFDESP D ON D.CODHISTORICO = A.CODHISTORICO
                                INNER JOIN OR_PARAMETRO O ON O.NROEMPRESA = A.NROEMPRESA
  
  
 WHERE 1=1 
   AND A.NROEMPRESA = '601'
   )
   WHERE COALESCE(NULLIF(ALIQISSQN,0),
                  NULLIF(ALIQIRPESFIS,0), 
                  NULLIF(ALIQIRPESJUR,0), 
                  NULLIF(ALIQINSSJUR,0), 
                  NULLIF(ALIQ_PIS,0), 
                  NULLIF(ALIQ_COFINS,0), 
                  NULLIF(ALIQCSSLL,0)) IS NOT NULL
   

ORDER BY 1,3
