SELECT DISTINCT CODGERALOPER CGO, A.DESCRICAO,

DECODE(TIPUSO,'R','Recebimento','E','Emissão NF','I','Operação Interna') TIPO_DE_USO,  
DECODE(TIPCGO, 'E','Entrada','S','Saida') TIPO, 
DECODE(STATUS, 'A','Ativo','I','Inativo')STATUS, 
CASE WHEN A.CODESPECIEFIN IS NULL THEN NULL ELSE A.CODESPECIEFIN||' - '||B.DESCRICAO END ESPECIE,
DECODE(A.GERALTERACAOESTQ,'S','Sim','N','Não') Gera_Alt_Est,
DECODE(A.INDGERADEBCREDPIS,'S','Sim','N','Não') GERA_DEB_CRED_PIS,
DECODE(A.INDGERADEBCREDCOFINS,'S','Sim','N','Não') GERA_DEB_CRED_COFINS,
DECODE(NVL(A.INDESTORNAICMSBASEPISCOFINS,'N'), 'S','Sim','N','Não') Subtrai_ICMS_PIS_COF

FROM CONSINCO.MAX_CODGERALOPER A LEFT JOIN CONSINCO.FI_ESPECIE B ON A.CODESPECIEFIN = B.CODESPECIE

ORDER BY 1 ASC

SELECT * FROM CONSINCO.MAP_PRODCODIGO WHERE TIPCODIGO = 'E'
