 SELECT * FROM MAP_FAMILIA MF INNER JOIN MAP_FAMFORNEC FC ON FC.SEQFAMILIA = MF.SEQFAMILIA
                              INNER JOIN GE_PESSOA GE ON GE.SEQPESSOA = FC.SEQFORNECEDOR
  WHERE 1=1 
    AND UF = 'EX'
    AND NVL(MF.ALIQUOTAIPI,0) > 0
    AND (MF.PERISENTOIPI IS NULL
     OR MF.PEROUTROIPI IS NULL
     OR MF.PERALIQUOTAIPI IS NULL
     OR NVL(MF.PERBASEIPI,0) = 0)
