-- Critica de devolucao
-- Inserir o select em ESPV_CRITICADEVNFFORN

CREATE OR REPLACE VIEW ESPV_CRITICADEVNFFORN AS
SELECT A.IDSESSION,
       A.INST_ID,
       A.SEQNFDEVFORNEC,
       A.SEQPRODUTO,
       1 CODCRITICA,
       'Não é permitido a emissão para mesma razão neste CGO, verifique!' MENSAGEM,
       'B' INDBLOQUEIOLIBERA
  FROM MFLX_NFDEVFORNEC A INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = A.NROEMPRESA
 WHERE 1=1
   AND A.CODGERALOPER = 211
   AND EXISTS (SELECT 1 FROM MAX_EMPRESA D
                WHERE D.NROEMPRESA = A.SEQFORNECEDOR
                  AND SUBSTR((LPAD(E.NROCGC,13,0)),0,9)= SUBSTR((LPAD(D.NROCGC,13,0)),0,9));
