-- Adicionar em MLFV_AUXNOTAFISCALINCONS
-- Ticket 432832 - Adicionado por Giuliano em 29/07/2024
-- Regra para EX - Valida se o Pis/Cofins estão corretos

SELECT DISTINCT (X.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                X.NUMERONF,
                X.NROEMPRESA,
                0   AS SEQAUXNFITEM,
                'B' AS BLOQAUTOR,
                81  AS CODINCONSISTENC,
                '(EX) Aliquota de PIS/COFINS divergentes. Entrar em contato com Depto Cadastro Tributário'

  FROM MLF_AUXNOTAFISCAL X INNER JOIN MLF_AUXNFITEM XI ON X.SEQAUXNOTAFISCAL = XI.SEQAUXNOTAFISCAL
                           INNER JOIN MAP_PRODUTO XP ON XP.SEQPRODUTO = XI.SEQPRODUTO
                           INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = XP.SEQFAMILIA
                           INNER JOIN MAP_FAMFORNEC FC ON FC.SEQFAMILIA = XP.SEQFAMILIA
                           INNER JOIN MAP_TRIBUTACAOUF UF ON UF.NROTRIBUTACAO = FD.NROTRIBUTACAO
                           INNER JOIN MAF_FORNECEDOR F ON F.SEQFORNECEDOR = FC.SEQFORNECEDOR
                           INNER JOIN GE_PESSOA GE ON GE.SEQPESSOA = FC.SEQFORNECEDOR
       WHERE 1=1
       AND GE.UF = 'EX'
       AND UF.UFCLIENTEFORNEC = 'EX'
       AND (NVL(NULLIF(UF.PERPISDIF,0),1.65)    = 1.65 AND NVL(UF.SITUACAONFPIS,0) NOT IN (73,70)
         OR NVL(NULLIF(UF.PERCOFINSDIF,0),7.60) = 7.60  AND NVL(UF.SITUACAONFPIS,0) NOT IN (73,70))
       AND UF.NROREGTRIBUTACAO = 8 -- Importacao Direta
       AND UF.UFEMPRESA = 'SP'
       AND UF.TIPTRIBUTACAO = DECODE(NVL(FC.TIPFORNECEDORFAM,F.TIPFORNECEDOR) , 'I', 'EI', 'D', 'ED')
       AND X.CODGERALOPER IN (43,5)
       AND X.NROEMPRESA IN (502,503)
