SELECT * FROM CONSINCO.MAD_CRITICAPEDCONFIG FOR UPDATE; -- Cod Critica adicionadas aqui

-- Giuliano em 02/01/25 -- Solic Neides Ticket 508168
-- Funcao NAGF_BUSCAULTENT_ATIVO valida a ultima entrada e retorna o CGO correto
-- Se o CGO utilizado for diferente da Function, retorna para criticar

SELECT X.NROPEDVENDA, X.NROEMPRESA,  'CGO correto nesta operação: '||NAGF_BUSCAULTENT_ATIVO(X.NROEMPRESA, XI.SEQPRODUTO) CRITICA, XI.SEQPRODUTO
       
  FROM MAD_PEDVENDA X INNER JOIN MAD_PEDVENDAITEM XI ON XI.NROPEDVENDA = X.NROPEDVENDA
                      INNER JOIN MAP_PRODUTO P       ON P.SEQPRODUTO = XI.SEQPRODUTO
                      INNER JOIN MAP_FAMDIVISAO F    ON F.SEQFAMILIA = P.SEQFAMILIA
  
 WHERE 1=1
   AND X.CODGERALOPER IN (10,78)
   AND F.FINALIDADEFAMILIA = 'A'
   AND X.DTAINCLUSAO > SYSDATE - 20
 
   AND NAGF_BUSCAULTENT_ATIVO(X.NROEMPRESA, XI.SEQPRODUTO) != X.CODGERALOPER;
