-- Entradas

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT XI.SEQPRODUTO PLU, DESCCOMPLETA, TO_CHAR(SUM(XI.VLRITEM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRITEM
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON X.SEQNF = XI.SEQNF
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                        
 WHERE EXISTS (SELECT 7 FROM DIM_CATEGORIA@CONSINCODW C WHERE CATEGORIAN1 = 'AÇOUGUE' AND C.SEQFAMILIA = P.SEQFAMILIA)
   AND X.DTAENTRADA BETWEEN DATE '2024-01-01' AND DATE '2024-02-28'
   AND X.STATUSNF != 'C'
   
   GROUP BY XI.SEQPRODUTO, DESCCOMPLETA
   
   ORDER BY 2 

-- Saídas - Venda PDV

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT P.SEQPRODUTO, P.DESCCOMPLETA, TO_CHAR(SUM(DI.VLRITEM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRITEM
  FROM PDV_DOCTO D INNER JOIN PDV_DOCTOITEM DI ON D.SEQDOCTO = DI.SEQDOCTO

                   INNER JOIN MAP_PRODCODIGO PC ON PC.CODACESSO = DI.CODACESSO
                   INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = PC.SEQPRODUTO
                        
 WHERE EXISTS (SELECT 1 FROM DIM_CATEGORIA@CONSINCODW C WHERE CATEGORIAN1 = 'AÇOUGUE' AND C.SEQFAMILIA = P.SEQFAMILIA)
   AND D.DTAHORAMOVTO BETWEEN DATE '2024-01-01' AND DATE '2024-02-28'
   AND D.STATUSDOCTO != 'C'
   AND D.CODGERALOPER = 810
   
   GROUP BY P.SEQPRODUTO, DESCCOMPLETA
   
   ORDER BY 2
  
