-- Entradas

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT TO_CHAR(X.DTAENTRADA, 'MM') MES, XI.SEQPRODUTO PLU, DESCCOMPLETA, TO_CHAR(SUM(XI.VLRITEM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRITEM,
       F.NROTRIBUTACAO, MAX(T.PERALIQUOTA) ALIQUOTA
       
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI      ON X.SEQNF = XI.SEQNF
                        INNER JOIN MAP_PRODUTO P      ON P.SEQPRODUTO = XI.SEQPRODUTO
                        INNER JOIN MAP_FAMDIVISAO F   ON F.SEQFAMILIA = P.SEQFAMILIA
                         LEFT JOIN MAP_TRIBUTACAOUF T ON T.NROTRIBUTACAO = F.NROTRIBUTACAO AND T.NROREGTRIBUTACAO = 0 AND T.UFCLIENTEFORNEC IN ('SP','RJ') AND T.UFEMPRESA IN ('SP','RJ') AND T.TIPTRIBUTACAO IN ('EI','ED')
                        
 WHERE EXISTS (SELECT 7 FROM DIM_CATEGORIA@CONSINCODW C WHERE CATEGORIAN1 = 'AÇOUGUE' AND C.SEQFAMILIA = P.SEQFAMILIA)
   AND X.DTAENTRADA BETWEEN DATE '2024-01-01' AND DATE '2024-02-28'
   AND X.STATUSNF != 'C'
   
   GROUP BY TO_CHAR(X.DTAENTRADA, 'MM'), XI.SEQPRODUTO, DESCCOMPLETA, F.NROTRIBUTACAO
   
   ORDER BY 1,3

-- Saídas - Venda PDV

ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT TO_CHAR(DTAHORAMOVTO, 'MM') MES, P.SEQPRODUTO, P.DESCCOMPLETA, TO_CHAR(SUM(DI.VLRITEM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRITEM,
       F.NROTRIBUTACAO, MAX(T.PERALIQUOTA) ALIQUOTA
  FROM PDV_DOCTO D INNER JOIN PDV_DOCTOITEM DI ON D.SEQDOCTO = DI.SEQDOCTO
                   INNER JOIN MAP_PRODCODIGO PC  ON PC.CODACESSO = DI.CODACESSO
                   INNER JOIN MAP_PRODUTO P      ON P.SEQPRODUTO = PC.SEQPRODUTO
                   INNER JOIN MAP_FAMDIVISAO F   ON F.SEQFAMILIA = P.SEQFAMILIA
                    LEFT JOIN MAP_TRIBUTACAOUF T ON T.NROTRIBUTACAO = F.NROTRIBUTACAO AND T.NROREGTRIBUTACAO = 0 AND T.UFCLIENTEFORNEC IN ('SP','RJ') AND T.UFEMPRESA IN ('SP','RJ') AND T.TIPTRIBUTACAO IN ('SC','SN')
                   
 WHERE EXISTS (SELECT 1 FROM DIM_CATEGORIA@CONSINCODW C WHERE CATEGORIAN1 = 'AÇOUGUE' AND C.SEQFAMILIA = P.SEQFAMILIA)
   AND D.DTAHORAMOVTO BETWEEN DATE '2024-01-01' AND DATE '2024-02-28'
   AND D.STATUSDOCTO != 'C'
   AND D.CODGERALOPER = 810
   
   GROUP BY TO_CHAR(DTAHORAMOVTO, 'MM'), P.SEQPRODUTO, DESCCOMPLETA, F.NROTRIBUTACAO
   
   ORDER BY 1,3
  
