SELECT DISTINCT SEQPRODUTO PLU, DESCCOMPLETA DESCRICAO, C.VLRANTERIOR COD_ORIGEM_ANTERIOR, NVL(REGEXP_SUBSTR(C.VLRATUAL, '(\S*)(\s)'),B.CODORIGEMTRIB) COD_ORIGEM_ATUAL, TO_CHAR(C.DTAAUDITORIA, 'DD/MM/YYYY') DTA_AUTERACAO
  FROM MAP_PRODUTO A INNER JOIN MAP_FAMDIVISAO B ON A.SEQFAMILIA = B.SEQFAMILIA
                      LEFT JOIN MAP_AUDITORIA  C ON C.SEQIDENTIFICA = B.SEQFAMILIA AND C.TABELA = 'MAP_FAMDIVISAO' AND C.CAMPO LIKE '%ORIGEM%'
                                                AND C.DTAHORAUDITORIA >= (SELECT MAX(DTAHORAUDITORIA)
                                                                            FROM MAP_AUDITORIA X WHERE X.SEQIDENTIFICA = B.SEQFAMILIA AND TABELA = 'MAP_FAMDIVISAO' AND CAMPO LIKE '%ORIGEM%')
                    
 WHERE SEQPRODUTO = :NR1
