SELECT DECODE(T.TIPTRIBUTACAO, 'EI', 'Entada Industria', 'ED', 'Entrada Distribuidor', 'EM', 'Entrada Microempresa', 'SC', 'Saida Contribuinte', 'SN', 'Saida Não Contrinuinte') TIPO_TRIBUTACAO,
       T.NROTRIBUTACAO, T.UFEMPRESA UF_EMPRESA, T.UFCLIENTEFORNEC UF_FORNEC_CLIENTE, P.SEQPRODUTO COD_PRODUTO, DESCCOMPLETA DESC_PRODUTO, FF.DESCRICAO TIPO_DE_ITEM,
       F.SEQFAMILIA COD_FAMILIA, F.FAMILIA DESC_FAMILIA, F.CODNBMSH NCM, 
       T.SITUACAONF CST_ICMS, T.PERALIQUOTA ALIQ_ICMS, T.PERALIQUOTAST ALIQ_ICMSST,
       CASE WHEN T.TIPTRIBUTACAO IN ('EI','ED','EM') THEN F.SITUACAONFIPI    ELSE F.SITUACAONFIPISAI    END CST_IPI, 
       CASE WHEN T.TIPTRIBUTACAO IN ('EI','ED','EM') THEN F.ALIQUOTAIPI      ELSE F.PERALIQUOTAIPI      END ALIQ_IPI,
       CASE WHEN T.TIPTRIBUTACAO IN ('EI','ED','EM') THEN F.SITUACAONFPIS    ELSE F.SITUACAONFPISSAI    END CST_PIS, 
       CASE WHEN T.TIPTRIBUTACAO IN ('EI','ED','EM') THEN F.SITUACAONFCOFINS ELSE F.SITUACAONFCOFINSSAI END CST_COFINS, 
       CC.CSTIBSUF CST_IBS, CC.CSTCBS CST_CBS, CC.CCLASSTRIBIBSUF CCLASSTRIB, CC.PERALIQIBSUF ALIQ_IBS, CC.PERALIQCBS ALIQ_CBS
       
  FROM MAP_PRODUTO P INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                     INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = P.SEQFAMILIA
                     INNER JOIN MAP_FINALIDADEFAMILIA FF ON FF.FINALIDADEFAMILIA = FD.FINALIDADEFAMILIA
                      LEFT JOIN PDV_CENARIOPRODUTO CC ON CC.SEQPRODUTO = P.SEQPRODUTO AND CC.CIDADE = 'SAO PAULO'
                     INNER JOIN MAP_TRIBUTACAOUF T ON T.NROTRIBUTACAO = FD.NROTRIBUTACAO

WHERE P.SEQPRODUTO = 262581
  AND TIPTRIBUTACAO IN ('EI','ED','EM','SN','SC') 
  AND T.NROREGTRIBUTACAO = 0 
  AND UFEMPRESA IN ('SP','RJ')
  AND (TIPTRIBUTACAO IN ('SC','SN') AND UFCLIENTEFORNEC IN ('SP','RJ') OR TIPTRIBUTACAO NOT IN ('SC','SN'))
  
  ORDER BY 1 DESC;
