
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       NUMERONF, X.SEQPRODUTO, DESCCOMPLETA, VL VLR_LANCTO, VE VLR_EMITIDO, VE - VL DIF, QTD FROM (
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       LISTAGG(NUMERODF, ', ') WITHIN GROUP (ORDER BY NUMERODF) NUMERONF, A.SEQPRODUTO, (SELECT NVL(ROUND(SUM(Z.VALORLANCTOBRT * QTDLANCTO),2),0)
               FROM FATO_PERDA Z
              WHERE Z.NROEMPRESA =  21
                AND CODGERALOPER IN (21,33,41,66,110,111,112,113,114)
                AND Z.DTAOPERACAO BETWEEN DATE '2023-12-01' AND DATE '2023-12-31'
                AND Z.SEQPRODUTO = A.SEQPRODUTO) VL, SUM(VLRITEM) VE, SUM(QUANTIDADE) QTD
                
  FROM MFLV_BASEDFITEM A
    
 WHERE A.NUMERODF IN (53264, 53281, 53284)
   AND A.DTAEMISSAO BETWEEN DATE '2024-01-16' AND DATE '2024-01-17'
   AND CODGERALOPER = 806
   AND NROEMPRESA = 21 

GROUP BY  A.SEQPRODUTO) X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO

 WHERE 1=1 AND VL != VE
