SELECT X.NROPEDVENDA, X.NROEMPRESA, Z.SEQPESSOA EMPDESTINO, X.CODCRITICA, DTAGERACAO, Z.USUINCLUSAO, Z.DTAINCLUSAO, Z.ORIGEMPEDIDO, Y.DESCORIGEMPEDIDO
  FROM CONSINCO.MAD_CRITICAPEDVENDA X INNER JOIN CONSINCO.MAD_PEDVENDA Z ON X.NROPEDVENDA = Z.NROPEDVENDA
                                      INNER JOIN CONSINCO.MADV_ORIGEMPEDIDO Y ON Y.ORIGEMPEDIDO = Z.ORIGEMPEDIDO
 WHERE X.CODCRITICA LIKE '%PAGTO%'
   AND Z.ORIGEMPEDIDO = 'T'
   AND Z.SITUACAOPED != 'C'

ORDER BY DTAINCLUSAO DESC
