SELECT X.NROTRIBUTACAO, 
       LISTAGG(DISTINCT UFEMPRESA, ', ') WITHIN GROUP (ORDER BY NROTRIBUTACAO) UF_EMP,
       LISTAGG(DISTINCT UFCLIENTEFORNEC, ', ') WITHIN GROUP (ORDER BY NROTRIBUTACAO) UFS,
       LISTAGG(DISTINCT(DECODE(TIPTRIBUTACAO, 'EI','Entrada Industria','ED','Entrada Distrib','EM','Entrada Micro Emp')),', ') WITHIN GROUP (ORDER BY NROTRIBUTACAO) TIPO_TRIB, 
       LISTAGG(DISTINCT(R.DESCRICAO),', ') WITHIN GROUP (ORDER BY NROTRIBUTACAO) REGIME, PERALIQICMSDIFER
  FROM MAP_TRIBUTACAOUF X INNER JOIN MON_REGIMETRIBUTACAO R ON R.NROREGTRIBUTACAO = X.NROREGTRIBUTACAO
 WHERE 1=1
   AND NVL(PERALIQICMSDIFER,0) > 0
 
GROUP BY X.NROTRIBUTACAO, PERALIQICMSDIFER
ORDER BY 1
 
