SELECT /*Ticket 509959*/ X.NROTRIBUTACAO, T.TRIBUTACAO DESCRICAO_TRIB, 
       LISTAGG(R.DESCRICAO||' - Emp: '||X.UFEMPRESA||' - UF: '||X.UFCLIENTEFORNEC, ', ') 
           WITHIN GROUP (ORDER BY X.NROTRIBUTACAO) REGIMES, 
       SITUACAONF, BASEFCPST, PERALIQFCPST
  FROM MAP_TRIBUTACAOUF X INNER JOIN MON_REGIMETRIBUTACAO R ON R.NROREGTRIBUTACAO = X.NROREGTRIBUTACAO
                          INNER JOIN MAP_TRIBUTACAO T       ON T.NROTRIBUTACAO = X.NROTRIBUTACAO
 WHERE X.TIPTRIBUTACAO = 'SC'
   AND X.SITUACAONF IN ('010','070')
   AND (X.BASEFCPST IS NULL OR X.PERALIQFCPST IS NULL)
   AND R.ATIVO = 'S'
   AND UFEMPRESA = 'SP'
   AND UFCLIENTEFORNEC = 'RJ'
   
   GROUP BY X.NROTRIBUTACAO, T.TRIBUTACAO, SITUACAONF, BASEFCPST, PERALIQFCPST
   ORDER BY 1
