-- Novo - View na Consinco

SELECT X.NROEMPRESA LOJA,
       X.CNPJ_EMP CNPJ,
       X.DTAENTRADA,
       X.DTAVENCIMENTO,
       X.NRONOTA NF,
       X.NOMERAZAO RAZAO,
       X.COD_NAT_REND COD_REND,
       TO_CHAR(X.VALOR_NF_COMISSAO, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF,
       TO_CHAR(X.VALOR_PARC, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_PARC,
       TO_CHAR(CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.IRRF       ELSE NULL END, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') IR,
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VENC_IRRF  ELSE NULL END VENC_IR,
       TO_CHAR(CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.TOTAL_PCC  ELSE NULL END, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') PCC,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VENC_PCC   ELSE NULL END VENC_PCC

FROM NAGV_ITWORKS_REINF_IR_PCC X

 WHERE (TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 OR  TO_DATE(VENC_PCC, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2)
   AND LPAD(NROEMPRESA,3,0) IN (#LS1) 
   AND LPAD(NROEMPRESA,3,0) IN (SELECT NROEMPRESA FROM CONSINCO.GE_EMPRESA X WHERE X.MATRIZ IN (#LS2))
   
ORDER BY 1,4

-- Old

SELECT X.NROEMPRESA,
       X.CNPJ_EMP,
       X.DTAEMISSAO,
       X.DTAENTRADA,
       X.DTAVENCIMENTO,
       X.NRONOTA,
       X.NOMERAZAO,
       X.COD_NAT_REND,
       X.VALOR_NF_COMISSAO,
       X.VALOR_PARC,
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.IRRF       ELSE NULL END IRRF,
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.ALIQIR     ELSE NULL END ALIQIR,
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VENC_IRRF  ELSE NULL END VENC_IRRF,
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.CODIGO_IR  ELSE NULL END CODIGO_IR,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VLRPIS     ELSE NULL END VLRPIS,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.ALIQPIS    ELSE NULL END ALIQPIS,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VLRCOFINS  ELSE NULL END VLRCOFINS,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.ALIQCOFINS ELSE NULL END ALIQCOFINS,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VLRCSSLL   ELSE NULL END VLRCSSLL,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.ALIQCSSLL  ELSE NULL END ALIQCSSLL,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.TOTAL_PCC  ELSE NULL END TOTAL_PCC,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VENC_PCC   ELSE NULL END VENC_PCC,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.COD_PCC    ELSE NULL END COD_PCC 

FROM NAGV_ITWORKS_REINF_IR_PCC X

 WHERE (TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 OR  TO_DATE(VENC_PCC, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2)
   AND LPAD(NROEMPRESA,3,0) IN (#LS1) 
   AND LPAD(NROEMPRESA,3,0) IN (SELECT NROEMPRESA FROM CONSINCO.GE_EMPRESA X WHERE X.MATRIZ IN (#LS2))
   
ORDER BY 1,4
