SELECT :NR1 ANOPVA, :NR2 MESPVA, LPAD(:NR3,2,0) MOT_INV,
       X.PLU PRODUTO, X.QTD_UTIL_APUR QTDE, X.VLR_TOT_MERC VALORINFORMADO, X.VLR_TOT_MERC VALORINFORMADOIR, 
       'MUDANCA TRIBUTACAO' TXT_COMPL, U.SITUACAONF CST_ICMS, X.BASECALCICMSST BASE_ICMS, x.VLR_CREDITO VL_ICMS
  FROM NAGV_APURACAO_LAYOUT_FIS_CAT28 X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.PLU
                                        INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA
                                        INNER JOIN MAP_TRIBUTACAOUF U ON U.NROTRIBUTACAO = F.NROTRIBUTACAO AND U.UFEMPRESA = 'SP' AND UFCLIENTEFORNEC = 'SP' AND U.Tiptributacao = 'SN' AND U.NROREGTRIBUTACAO = 0
 WHERE 1=1
   AND X.DTA = :DT1
   AND NROEMPRESA IN (#LS1)
   ORDER BY 1;
