ALTER SESSION SET current_schema = CONSINCO;

SELECT DISTINCT A.CODHISTORICO COD_NAT, C.DESCRICAO DESC_NATUREZA, A.CODPRODUTO COD_PLU, 
       (SELECT DISTINCT B.DESCRICAO FROM ORV_PRODUTO B WHERE A.CODPRODUTO = B.CODPRODUTO ) DESC_PRODUTO, A.CODSERVICO COD_SERVICO

FROM RF_PARAMNATNFDESP A LEFT JOIN ABA_HISTORICO C ON A.CODHISTORICO = C.SEQHISTORICO
                         
WHERE A.CGO = 6 
