ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Adicionar em MLFV_AUXNOTAFISCALINCONS
-- Ticket 431411 - Giuliano em 19/08/2024 - Solic Danielle

-- Regra 1

SELECT  DISTINCT --(X.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                b.SEQPRODUTO PLU, X.NUMERONF,
                X.NROEMPRESA,
                --0   AS SEQAUXNFITEM,
                --'L' AS BLOQAUTOR,
                --80  AS CODINCONSISTENC,
                --*/
                L.M014_VL_QTDE_TRIB qTrib,
                L.M014_DS_UNID_TRIB uTrib,
                L.M014_VL_QTDE_COM uCom,
                L.M014_DS_UNID_COM qCom,
                FD.PADRAOEMBCOMPRA,
                CD.CATEGORIAN1
      
  FROM CONSINCO.MLF_AUXNOTAFISCAL X INNER JOIN CONSINCO.MLF_AUXNFITEM B ON X.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                 INNER JOIN TMP_M000_NF K         ON K.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                                 INNER JOIN TMP_M014_ITEM L       ON L.M000_ID_NF = K.M000_ID_NF  AND L.M014_NR_ITEM = B.SEQITEMNFXML
                                 INNER JOIN MAP_PRODCODIGO X2     ON X2.SEQPRODUTO = B.SEQPRODUTO
                                 INNER JOIN MAP_PRODUTO P         ON P.SEQPRODUTO = B.SEQPRODUTO
                                 INNER JOIN MAP_FAMILIA F         ON F.SEQFAMILIA = P.SEQFAMILIA
                                 INNER JOIN MAP_FAMDIVISAO FD     ON FD.SEQFAMILIA = P.SEQFAMILIA
                                 INNER JOIN DIM_CATEGORIA@CONSINCODW CD ON CD.SEQFAMILIA = P.SEQFAMILIA

WHERE 1=1 
  --AND X.DTAEMISSAO > SYSDATE - 10
  AND NVL(F.PESAVEL, 'N') = 'N'
  --AND MOD(L.M014_VL_QTDE_TRIB,FD.PADRAOEMBCOMPRA) != 0
  AND L.M014_DS_UNID_COM = 'CX' 
  AND L.M014_VL_QTDE_COM * FD.PADRAOEMBCOMPRA != L.M014_VL_QTDE_TRIB
  AND X.SEQPESSOA > 999 
  AND CATEGORIAN1 IN ('HIGIENE E PERFUMARIA', 'LIMPEZA')
  
-- Regra 2

SELECT  DISTINCT --(X.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                b.SEQPRODUTO PLU, X.NUMERONF,
                X.NROEMPRESA,
                --0   AS SEQAUXNFITEM,
                --'L' AS BLOQAUTOR,
                --80  AS CODINCONSISTENC,
                --*/
                L.M014_VL_QTDE_TRIB qTrib,
                L.M014_DS_UNID_TRIB uTrib,
                L.M014_VL_QTDE_COM uCom,
                L.M014_DS_UNID_COM qCom,
                FD.PADRAOEMBCOMPRA,
                CD.CATEGORIAN1, X2.QTDEMBALAGEM EMB_PROD_FORNEC
      
  FROM CONSINCO.MLF_AUXNOTAFISCAL X INNER JOIN CONSINCO.MLF_AUXNFITEM B ON X.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                 INNER JOIN TMP_M000_NF K         ON K.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                                 INNER JOIN TMP_M014_ITEM L       ON L.M000_ID_NF  = K.M000_ID_NF  AND L.M014_NR_ITEM = B.SEQITEMNFXML
                                 INNER JOIN GE_PESSOA G           ON G.SEQPESSOA   = X.SEQPESSOA
                                 INNER JOIN MAP_PRODCODIGO X2     ON X2.SEQPRODUTO = B.SEQPRODUTO AND LPAD(CGCFORNEC,7,0) = SUBSTR(G.NROCGCCPF,0,7)
                                 INNER JOIN MAP_PRODUTO P         ON P.SEQPRODUTO  = B.SEQPRODUTO
                                 INNER JOIN MAP_FAMILIA F         ON F.SEQFAMILIA  = P.SEQFAMILIA
                                 INNER JOIN MAP_FAMDIVISAO FD     ON FD.SEQFAMILIA = P.SEQFAMILIA
                                 INNER JOIN DIM_CATEGORIA@CONSINCODW CD ON CD.SEQFAMILIA = P.SEQFAMILIA

WHERE 1=1 
  --AND X.DTAEMISSAO > SYSDATE - 10
  AND NVL(F.PESAVEL, 'N') = 'N'
  AND L.M014_DS_UNID_COM LIKE 'UN%' 
  AND X2.QTDEMBALAGEM > 1
  AND X.SEQPESSOA > 999 
  AND CATEGORIAN1 IN ('HIGIENE E PERFUMARIA', 'LIMPEZA')
