ALTER SESSION SET current_schema = CONSINCO;

SELECT SEQPESSOA EMP_DESTINO,'NF Não Importada' STATUS, NROEMPRESA EMITENTE, NUMERONF, DTAEMISSAO
  FROM MLF_NOTAFISCAL A LEFT JOIN MAX_CODGERALOPER C ON A.CODGERALOPER = C.CODGERALOPER
 WHERE A.TIPNOTAFISCAL = 'S' 
   AND DTAEMISSAO >= SYSDATE - 20
   AND SEQPESSOA < 999 
   AND DTAENTRADA IS NULL
   AND SEQPESSOA != NROEMPRESA
   AND STATUSNF != 'C'
   AND NUMERONF NOT IN (SELECT NUMERONF FROM MLF_NOTAFISCAL B WHERE B.TIPNOTAFISCAL = 'E' 
                         AND SEQPESSOA < 999 
                         AND DTAENTRADA IS NOT NULL 
                         AND B.SEQPESSOA = A.NROEMPRESA
                         AND STATUSNF != 'C')
                         
UNION ALL

SELECT D.NROEMPRESA DESTINO, 
       DECODE(D.INDPROCESSAMENTO, 'G', 'NF em Conferência', 'L', 'NF Liberada, Conferência Não Iniciada', 'NF Gerada, Processo Não Iniciado'),
       D.SEQPESSOA EMITENTE, D.NUMERONF, D.DTAEMISSAO
  FROM MLF_AUXNOTAFISCAL D LEFT JOIN MAX_CODGERALOPER C ON D.CODGERALOPER = C.CODGERALOPER
 WHERE SEQPESSOA < 999 AND NUMERONF != 0
 
 ORDER BY 1,2,5
   
