SELECT DISTINCT X.NROEMPRESA LOJA, X.NUMERONF, TO_CHAR(COALESCE(AX.DTAHORLANCTO, NF.DTAHORLANCTO, DATALOG), 'DD/MM/YYYY') DATA_LANCTO, DESCRICAO MOTIVO,
       CASE 
         WHEN X.CODINCONSIST IN (5,6,7,8,11,12,42,139,64,56)
             AND X.TIPOINCONSIST = 'N'
             AND X.SEQAUXNFITEM  = 0 
            OR X.CODINCONSIST IN (59)
             AND X.TIPOINCONSIST = 'N'
             AND X.SEQAUXNFITEM  <> 0
          THEN 'FISCAL'
         WHEN (X.TIPOINCONSIST = 'N' AND X.CODINCONSIST IN (45,143,144,145,152,185,165,187,188,189,190,191,192,193,194,195,49,43,11,12,13,80,129,58)
            OR X.TIPOINCONSIST = 'P' AND X.CODINCONSIST IN (1,176,177))
             AND X.SEQAUXNFITEM <> 0  
            OR X.CODINCONSIST IN (61)
             AND TIPOINCONSIST = 'N'
             AND X.SEQAUXNFITEM = 0
          THEN 'CADASTRO' 
         WHEN X.CODINCONSIST IN (3,4,7,75,166,167) 
             AND X.TIPOINCONSIST = 'P'
             AND X.SEQAUXNFITEM <> 0
            OR X.CODINCONSIST IN (3)
             AND X.TIPOINCONSIST = 'V'
             AND X.SEQAUXNFITEM = 0
            OR X.CODINCONSIST IN (139)
             AND X.TIPOINCONSIST = 'N'
             AND X.SEQAUXNFITEM <> 0
          THEN 'COMERCIAL'
         WHEN X.CODINCONSIST IN (15)
             AND X.TIPOINCONSIST = 'V'
            OR X.CODINCONSIST IN (267,268)
            AND X.TIPOINCONSIST = 'N'
          THEN 'RECEBIMENTO'
              END TIPO_INCONSISTENCIA,
       NVL(M1.COMPRADOR,
       (SELECT M2.COMPRADOR FROM MAX_COMPRADOR M2 WHERE M2.SEQCOMPRADOR = (
               SELECT MAX(SEQCOMPRADOR) FROM MAP_FAMDIVISAO C WHERE C.SEQFAMILIA = (
                      SELECT SEQFAMILIA FROM MAP_PRODUTO PR WHERE PR.SEQPRODUTO = (
                             SELECT MAX(SEQPRODUTO) FROM (SELECT SEQPRODUTO FROM MLF_AUXNFITEM XX WHERE XX.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
                                                          UNION ALL
                                                          SELECT SEQPRODUTO FROM MLF_NFITEM YY WHERE YY.SEQNF = X.SEQNF
                                                          UNION ALL
                                                          SELECT SEQPRODUTO FROM MFL_DFITEM ZZ WHERE ZZ.SEQNF = X.SEQNF)))))) COMPRADOR, 
       X.SEQPESSOA||' - '||NOMERAZAO FORNECEDOR, X.SEQPRODUTO PLU, PR.DESCCOMPLETA DESCRICAO/*, TO_CHAR(X.DATALOG, 'DD/MM/YYYY') DTALOG*/
       
  FROM NAGT_INCONSISTRECEBTO_LOG X INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                                   LEFT JOIN  MSU_PSITEMRECEBIDO P ON P.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL AND P.SEQPESSOA = X.SEQPESSOA AND P.NROEMPRESA = X.NROEMPRESA
                                   LEFT JOIN  MSU_PEDIDOSUPRIM  PS ON PS.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM AND PS.NROEMPRESA = P.NROEMPRESA 
                                   LEFT JOIN  MAX_COMPRADOR     M1 ON M1.SEQCOMPRADOR    = PS.SEQCOMPRADOR
                                   LEFT JOIN  MAP_PRODUTO       PR ON PR.SEQPRODUTO      = X.SEQPRODUTO 
                                   LEFT JOIN  MLF_AUXNOTAFISCAL AX ON AX.SEQNF = X.SEQNF OR AX.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
                                   LEFT JOIN  MLF_NOTAFISCAL    NF ON NF.SEQNF = X.SEQNF OR NF.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL

 WHERE 1=1
   AND NVL(AX.DTAHORLANCTO, NF.DTAHORLANCTO) BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
                                   
  ORDER BY 1, 2 ,8  DESC, X.SEQPRODUTO
