ALTER SESSION SET current_schema = CONSINCO;
DELETE FROM NAGT_ENTRADAPISCOFINS A WHERE A.FORNECEDOR = 'I' AND A.CST_SAIDAFORNECEDOR = 49 AND A.CST_ENTRANAGUMO = 73 AND TIPO = 'N';
COMMIT;
INSERT INTO NAGT_ENTRADAPISCOFINS A VALUES ('SI','49','73','N');

COMMIT; 
SELECT * FROM NAGT_ENTRADAPISCOFINS B


