SELECT A.SEQPRODUTO PLU, DESCCOMPLETA, A.SEQFAMILIA COD_FAMILIA, COMPRADOR, DESCATRIBUTO ATRIBUTO, TO_CHAR(A.DTAHORINCLUSAO, 'DD/MM/YYYY') DTAINCLUSAO, A.USUARIOINCLUSAO, F.CODNBMSH NCM, F.PERIMPOSTOIMPORT ALIQUOTA_II
      
  FROM MAP_PRODUTO A INNER JOIN MAP_FAMDIVISAO C ON C.SEQFAMILIA = A.SEQFAMILIA
                     INNER JOIN MAX_COMPRADOR CC ON CC.SEQCOMPRADOR = C.SEQCOMPRADOR
                     LEFT JOIN MAP_FAMATRIBUTO D ON D.SEQFAMILIA = A.SEQFAMILIA
                     INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = A.SEQFAMILIA
                     
WHERE A.DTAHORINCLUSAO BETWEEN :DT1 AND :DT2
  AND (CC.COMPRADOR = 'IMPORTADOS'
   OR D.DESCATRIBUTO = 'Produto Importado')
  AND EXISTS (SELECT 1 FROM MAP_FAMFORNEC FC INNER JOIN GE_PESSOA G ON G.SEQPESSOA = FC.SEQFORNECEDOR
                      WHERE FC.SEQFAMILIA = A.SEQFAMILIA
                        AND G.UF = 'EX')
   
ORDER BY 2
