SELECT * FROM (WITH BASE AS (

    SELECT LOJA, PERIODO, CGO, DESCRICAO, VALOR, O4, CASE WHEN O4 IS NOT NULL THEN NULL ELSE ROWNUM END O5, 
       TO_CHAR(NOTAS_EMITIDAS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') NOTAS_EMITIDAS, 
       DT1

 FROM (

          SELECT CASE WHEN LOJA IS NULL THEN 'LOJA' ELSE TO_CHAR(LOJA) END LOJA, 
                 CASE WHEN DATA_INICIO IS NULL AND LOJA IS NULL THEN 'PERIODO' ELSE
                   CASE WHEN DATA_INICIO IS NOT NULL THEN TO_CHAR(DATA_INICIO, 'DD/MM/YY')||' até '||TO_CHAR(DATA_FIM, 'DD/MM/YY') 
                      WHEN DATA_INICIO IS NULL AND LOJA IS NOT NULL THEN 'Emissão: '||TO_CHAR(DATA_FIM, 'DD/MM/YYYY') ELSE NULL END END PERIODO,
                 CASE WHEN CGO IS NULL THEN 'CGO' ELSE TO_CHAR(CGO) END CGO, 
                 CASE WHEN DESCRICAO IS NULL THEN 'DESCRICAO' ELSE DESCRICAO END DESCRICAO, 
                 CASE WHEN VALOR IS NULL THEN 'VALOR' ELSE TO_CHAR(VALOR,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') END VALOR,
                TO_CHAR(DATA_INICIO, 'DD/MM/YY')||' até '||TO_CHAR(DATA_FIM, 'DD/MM/YY')  DT1, NULL,
                  (SELECT ROUND(SUM(F.VLRCONTABIL),2)
                     FROM MFLV_BASENF F WHERE F.NROEMPRESA IN (#LS1) AND F.CODGERALOPER IN (806,807,918,919) AND F.STATUSDF != 'C' AND F.STATUSNFE = 4
                      AND EXTRACT (MONTH FROM DTAEMISSAO) = DECODE(:NR1,12,0,:NR1) 
                      AND EXTRACT (YEAR FROM DTAEMISSAO) = DECODE(:NR1,12,:NR2 +1,:NR2)) NOTAS_EMITIDAS,
                
                  NULL, O1, O2, O3, O4
                 
           FROM(

          SELECT NULL O1, 'B' O2, '2' O3, NULL O4, F.NROEMPRESA LOJA, TRUNC(F.DTAEMISSAO, 'MM') DATA_INICIO, LAST_DAY(TRUNC(F.DTAEMISSAO, 'MM')) DATA_FIM, 
                 F.CODGERALOPER CGO, Y.DESCRICAO, ROUND(SUM(F.VLRCONTABIL),2) VALOR
          FROM MFLV_BASENF F LEFT JOIN DIM_CODGERALOPER Y ON F.CODGERALOPER = Y.CODGERALOPER
          WHERE F.NROEMPRESA IN (#LS1) AND F.CODGERALOPER IN(806,918) AND F.STATUSDF != 'C' AND F.STATUSNFE = 4
          AND EXTRACT (MONTH FROM DTAEMISSAO) = DECODE(:NR1,12,0,:NR1)
          AND EXTRACT (YEAR FROM DTAEMISSAO) = DECODE(:NR1,12,:NR2 +1,:NR2)
          GROUP BY  F.NROEMPRESA, F.CODGERALOPER, Y.DESCRICAO, TRUNC(F.DTAEMISSAO, 'MM')

            UNION ALL

          SELECT NULL, 'D' O2,'4' O3, NULL O4, F.NROEMPRESA, TRUNC(F.DTAEMISSAO, 'MM') , LAST_DAY(TRUNC(F.DTAEMISSAO, 'MM')), 
                 F.CODGERALOPER, Y.DESCRICAO, ROUND(SUM(F.VLRCONTABIL),2) VALOR
          FROM MFLV_BASENF F LEFT JOIN DIM_CODGERALOPER Y ON F.CODGERALOPER = Y.CODGERALOPER
          WHERE F.NROEMPRESA IN (#LS1) AND F.CODGERALOPER IN(807,919) AND F.STATUSDF != 'C' AND F.STATUSNFE = 4
          AND EXTRACT (MONTH FROM DTAEMISSAO) = DECODE(:NR1,12,0,:NR1)
          AND EXTRACT (YEAR FROM DTAEMISSAO) = DECODE(:NR1,12,:NR2 +1,:NR2)
          GROUP BY  F.NROEMPRESA, F.CODGERALOPER, Y.DESCRICAO, TRUNC(F.DTAEMISSAO, 'MM')

            UNION ALL

          SELECT DISTINCT NULL, 'B'||F.NUMERODF O2,'3' O3, NULL O4, F.NROEMPRESA, NULL, F.DTAEMISSAO, F.CODGERALOPER, 'NRO NF: '||F.NUMERODF, F.VLRCONTABIL
          FROM MFLV_BASENF F WHERE F.NROEMPRESA IN (#LS1) AND F.CODGERALOPER IN (806,918) AND F.STATUSDF != 'C' AND F.STATUSNFE = 4
          AND EXTRACT (MONTH FROM DTAEMISSAO) = DECODE(:NR1,12,0,:NR1)
          AND EXTRACT (YEAR FROM DTAEMISSAO) = DECODE(:NR1,12,:NR2 +1,:NR2)

            UNION ALL

          SELECT DISTINCT NULL, 'D'||F.NUMERODF O2, '5' O3, NULL O4, F.NROEMPRESA, NULL, F.DTAEMISSAO, F.CODGERALOPER, 'NRO NF: '||F.NUMERODF, F.VLRCONTABIL 
          FROM MFLV_BASENF F WHERE F.NROEMPRESA IN (#LS1) AND F.CODGERALOPER IN (807,919) AND F.STATUSDF != 'C' AND F.STATUSNFE = 4
          AND EXTRACT (MONTH FROM DTAEMISSAO) = DECODE(:NR1,12,0,:NR1)
          AND EXTRACT (YEAR FROM DTAEMISSAO) = DECODE(:NR1,12,:NR2 +1,:NR2) 



            UNION ALL

          SELECT NULL, 'C' O2, NULL, '2' O4, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

          )

          ORDER BY 11,12)
    ),
    
    CNT AS (
      SELECT COUNT(*) AS QTD FROM BASE
      )
      
      SELECT * FROM BASE
      WHERE (SELECT QTD FROM CNT) > 1

      UNION ALL

      SELECT 
         TO_CHAR(#LS1) LOJA,
         NULL  PERIODO,
         NULL  CGO,
         NULL  DESCRICAO,
         NULL  VALOR,
         NULL  O4,
         NULL  O5,
         NULL  NOTAS_EMITIDAS,
         (SELECT TO_CHAR(MIN(DTA), 'DD/MM/YYYY')||' até '||TO_CHAR(MAX(DTA), 'DD/MM/YYYY') FROM DIM_TEMPO X WHERE ANO = DECODE(:NR1,12,:NR2 +1,:NR2) AND MES = DECODE(:NR1,12,0,:NR1))  DT1
      FROM DUAL
      WHERE (SELECT QTD FROM CNT) <= 1);
