SELECT * FROM (

SELECT LOJA, CNPJ,  TO_CHAR(:DT1, 'DD/MM/YYYY')||' à '||TO_CHAR(:DT2, 'DD/MM/YYYY') DATA, RAZAO,
       TO_CHAR(SUM(VALOR_NF),  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF, 
       TO_CHAR(SUM(VALOR_PARC),'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_PARC, 
       CODIGO_IR,
       TO_CHAR(SUM(IR),        'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') IR, 
       COD_PCC,
       TO_CHAR(SUM(PCC),       'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') PCC

  FROM ( 

SELECT X.NROEMPRESA LOJA,
       X.CNPJ_EMP CNPJ,
       X.DTAENTRADA,
       X.DTAVENCIMENTO, 
       X.NRONOTA NF,
       X.NOMERAZAO RAZAO,
       X.COD_NAT_REND COD_REND,
       X.VALOR_NF_COMISSAO VALOR_NF,
       X.VALOR_PARC VALOR_PARC,
       CODIGO_IR,
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.IRRF       ELSE NULL END IR,
               CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VENC_IRRF  ELSE NULL END VENC_IR,
       COD_PCC,
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.TOTAL_PCC  ELSE NULL END PCC,
               CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN X.VENC_PCC   ELSE NULL END VENC_PCC

FROM CONSINCO.NAGV_ITWORKS_REINF_IR_PCC X

 WHERE (TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 OR TO_DATE(VENC_PCC, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2)
   AND LPAD(NROEMPRESA,3,0) IN (#LS1) 
   AND LPAD(NROEMPRESA,3,0) IN (SELECT NROEMPRESA FROM CONSINCO.GE_EMPRESA X WHERE X.MATRIZ IN (#LS2))
   
) A 

GROUP BY LOJA, CNPJ, RAZAO, CODIGO_IR, COD_PCC

ORDER BY 1) 

  UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

  UNION ALL 

SELECT NULL, NULL, NULL, 'TOTAL',
       TO_CHAR(SUM(VALOR_NF),   'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''),
       TO_CHAR(SUM(VALOR_PARC), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''),
       NULL,
       TO_CHAR(SUM(IR),         'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''),
       NULL, 
       TO_CHAR(SUM(PCC),        'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
  FROM ( 
SELECT SUM(X.VALOR_NF_COMISSAO) VALOR_NF,
       SUM(X.VALOR_PARC) VALOR_PARC, 
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN SUM(X.IRRF)       ELSE NULL END IR, 
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN SUM(X.TOTAL_PCC)  ELSE NULL END PCC

FROM CONSINCO.NAGV_ITWORKS_REINF_IR_PCC X

 WHERE (TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 OR TO_DATE(VENC_PCC, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2)
   AND LPAD(NROEMPRESA,3,0) IN (#LS1) 
   AND LPAD(NROEMPRESA,3,0) IN (SELECT NROEMPRESA FROM CONSINCO.GE_EMPRESA X WHERE X.MATRIZ IN (#LS2))
   
   GROUP BY TO_DATE(VENC_IRRF, 'DD/MM/YYYY'), TO_DATE(VENC_PCC,  'DD/MM/YYYY'))

  UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

  UNION ALL 

SELECT NULL, NULL, NULL, 'SUBTOTAL - COD IR: '||CODIGO_IR,
       NULL,
       NULL,
       NULL,
       TO_CHAR(SUM(IR),         'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''),
       NULL, 
       NULL
  FROM ( 
SELECT SUM(X.VALOR_NF_COMISSAO) VALOR_NF,
       SUM(X.VALOR_PARC) VALOR_PARC, 
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN SUM(X.IRRF)       ELSE NULL END IR, 
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN SUM(X.TOTAL_PCC)  ELSE NULL END PCC, CODIGO_IR

FROM CONSINCO.NAGV_ITWORKS_REINF_IR_PCC X

 WHERE (TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 OR TO_DATE(VENC_PCC, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2)
   AND LPAD(NROEMPRESA,3,0) IN (#LS1) 
   AND LPAD(NROEMPRESA,3,0) IN (SELECT NROEMPRESA FROM CONSINCO.GE_EMPRESA X WHERE X.MATRIZ IN (#LS2))
   AND X.CODIGO_IR IS NOT NULL
   
   GROUP BY TO_DATE(VENC_IRRF, 'DD/MM/YYYY'), TO_DATE(VENC_PCC,  'DD/MM/YYYY'), CODIGO_IR) GROUP BY CODIGO_IR
   
UNION ALL 

SELECT NULL, NULL, NULL, 'SUBTOTAL - COD PCC: '||COD_PCC,
       NULL,
       NULL, 
       NULL,
       NULL,
       NULL, 
       TO_CHAR(SUM(PCC),        'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
  FROM ( 
SELECT SUM(X.VALOR_NF_COMISSAO) VALOR_NF,
       SUM(X.VALOR_PARC) VALOR_PARC, 
       CASE WHEN TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN SUM(X.IRRF)       ELSE NULL END IR, 
       CASE WHEN TO_DATE(VENC_PCC,  'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 THEN SUM(X.TOTAL_PCC)  ELSE NULL END PCC, X.COD_PCC

FROM CONSINCO.NAGV_ITWORKS_REINF_IR_PCC X

 WHERE (TO_DATE(VENC_IRRF, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2 OR TO_DATE(VENC_PCC, 'DD/MM/YYYY') BETWEEN :DT1 AND :DT2)
   AND LPAD(NROEMPRESA,3,0) IN (#LS1) 
   AND LPAD(NROEMPRESA,3,0) IN (SELECT NROEMPRESA FROM CONSINCO.GE_EMPRESA X WHERE X.MATRIZ IN (#LS2))
   AND X.COD_PCC IS NOT NULL
   
   GROUP BY TO_DATE(VENC_IRRF, 'DD/MM/YYYY'), TO_DATE(VENC_PCC,  'DD/MM/YYYY'), COD_PCC) GROUP BY COD_PCC
      

  
