ALTER SESSION SET current_schema = CONSINCO;

SELECT MP.SEQPRODUTO, MP.DESCCOMPLETA, FA.SEQFAMILIA, FA.CODNBMSH NCM FROM MAP_FAMILIA FA JOIN MAP_PRODUTO MP ON FA.SEQFAMILIA = MP.SEQFAMILIA

WHERE CODNBMSH LIKE '3001%' /* NCMs */
      OR CODNBMSH LIKE '3002%'
      OR CODNBMSH LIKE '3003%'
      OR CODNBMSH LIKE '3004%'
      OR CODNBMSH LIKE '3005%'
      OR CODNBMSH LIKE '3006%'
      
ORDER BY FA.CODNBMSH, FA.SEQFAMILIA;
