ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT SEQPRODUTO PLU, DESCCOMPLETA DESCRICAO, C.VLRANTERIOR COD_ORIGEM_ANTERIOR, NVL(REGEXP_SUBSTR(C.VLRATUAL, '(\S*)(\s)'),B.CODORIGEMTRIB) COD_ORIGEM_NOVO, TO_CHAR(C.DTAAUDITORIA, 'DD/MM/YYYY') DTA_AUTERACAO
  FROM MAP_PRODUTO A INNER JOIN MAP_FAMDIVISAO B ON A.SEQFAMILIA = B.SEQFAMILIA
                      LEFT JOIN MAP_AUDITORIA  C ON C.SEQIDENTIFICA = B.SEQFAMILIA AND C.TABELA = 'MAP_FAMDIVISAO' AND C.CAMPO LIKE '%ORIGEM%'
                                       
                    
 WHERE 1=1 
   AND SEQPRODUTO = :NR1
   AND C.DTAAUDITORIA > TRUNC(SYSDATE) - 180
   
   ORDER BY TO_CHAR(C.DTAAUDITORIA, 'DD/MM/YYYY') DESC
