ALTER SESSION SET current_schema = CONSINCO;

SELECT DISTINCT DTAALTERACAO, A.USUALTERACAO, A.PERTRIBUTADO PERC_TRIBUTADO, A.PERISENTO PERC_ISENTO, A.PEROUTRO PERC_OUTROS
FROM CONSINCO.MAP_TRIBUTACAOUFHIST A 
WHERE A.NROTRIBUTACAO = 810 
  AND TIPTRIBUTACAO = 'SC'
  AND UFEMPRESA = 'SP'
ORDER BY A.DTAALTERACAO DESC
