
SELECT NROEMPRESA LOJA, 
       TO_CHAR(VLR, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') NOTAS_EMITIDAS, 
       TO_CHAR(OPERACOES_INTERNAS, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') OPERACOES_INTERNAS, 
       TO_CHAR(OPERACOES_INTERNAS - VLR, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') DIFERENCA,
       'Mês: '||:NR1||' Ano: '||:NR2
       
       FROM (
       
SELECT NROEMPRESA, SUM(VLRCONTABIL) VLR, (SELECT ROUND(SUM(X.VALORLANCTOBRT *X.QTDLANCTO),2) VALOR
                                        FROM FATO_PERDA X INNER JOIN DIM_CODGERALOPER Y ON (X.CODGERALOPER = Y.CODGERALOPER)
                                       WHERE X.NROEMPRESA = XX.NROEMPRESA
                                         AND Y.CODGERALOPER NOT IN (49,269,270,271,272,273,274)
                                         AND EXTRACT (MONTH FROM DTAOPERACAO) = :NR1
                                         AND EXTRACT (YEAR  FROM DTAOPERACAO) = :NR2
                                    GROUP BY X.NROEMPRESA) OPERACOES_INTERNAS

FROM (      

SELECT A.NROEMPRESA, SUM((B.VLRITEM + NVL(B.VLRACRESCIMO, 0) - NVL(B.VLRDESCONTO, 0) - NVL(B.VLRDESCINCONDIC, 0))) VLRCONTABIL
FROM   MFL_DOCTOFISCAL A INNER JOIN MFL_DFITEM B ON A.NUMERODF = B.NUMERODF AND A.SERIEDF = B.SERIEDF AND A.NROSERIEECF = B.NROSERIEECF AND A.NROEMPRESA = B.NROEMPRESA
WHERE 
    EXTRACT (MONTH FROM A.DTAMOVIMENTO) = DECODE(:NR1,12,0,:NR1) +1 
AND EXTRACT (YEAR  FROM A.DTAMOVIMENTO) = DECODE(:NR1,12,2023,:NR2)
AND A.CODGERALOPER IN (806,807,918,919)
AND A.STATUSDF != 'C'
GROUP BY A.NROEMPRESA

UNION ALL

SELECT C.NROEMPRESA, SUM((D.VLRITEM + CASE WHEN C.INDCONSIDFRETEDESPTRIB = 'N' THEN
                             D.VLRDESPTRIBUTITEM + NVL(D.VLRFRETENANF,0)
                        ELSE
                             D.VLRDESPTRIBUTITEM
                        END + D.VLRDESPNTRIBUTITEM + D.VLRIPI +
            D.VLRICMSST - D.VLRDESCITEM - D.VLRFUNRURALITEM - NVL(D.VLRDESCSUFRAMA, 0))) VLRCONTABIL
FROM   MLF_NOTAFISCAL C INNER JOIN MLF_NFITEM D ON C.NUMERONF = D.NUMERONF AND C.SEQPESSOA = D.SEQPESSOA AND C.SERIENF = D.SERIENF 
                                               AND C.TIPNOTAFISCAL = D.TIPNOTAFISCAL AND C.NROEMPRESA = D.NROEMPRESA AND NVL(C.SEQNF, 0) = NVL(D.SEQNF, NVL(C.SEQNF, 0))

WHERE  
    EXTRACT (MONTH FROM C.DTAEMISSAO) = DECODE(:NR1,12,0,:NR1) +1 
AND EXTRACT (YEAR  FROM C.DTAEMISSAO) = DECODE(:NR1,12,2023,:NR2)
AND C.CODGERALOPER IN (806,807,918,919)
AND C.STATUSNF != 'C'
GROUP BY C.NROEMPRESA

) XX GROUP BY NROEMPRESA ) ORDER BY 1 ASC 
