CREATE OR REPLACE VIEW CONSINCO.NAGV_LOCACAOITWORKS AS
(

SELECT  O.SEQNOTA SEQUENCIANF,
       (SELECT LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0)       FROM CONSINCO.GE_EMPRESA GE WHERE SEQPESSOA = O.NROEMPRESA) CAIXAENTRADA,
       (SELECT LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0)   FROM CONSINCO.GE_PESSOA G  WHERE SEQPESSOA = O.SEQPESSOA) CNPJCPFEMITENTE,
       O.SERIE, O.NRONOTA, 'ENTRADA' TIPO, VLRLIQNOTA VLR_LIQUIDO, O.VALOR VLR_TOTAL,
       O.VLRDESCONTOS VLR_DESCONTOS, O.VLRACRESCIMOS VLR_ACRESCIMOS,
       O.DTAEMISSAO DTA_EMISSAO, O.DTAENTRADA DTA_LANCTO, O.DTAALTERACAO DTA_ALTERACAO, X.CODPRODUTO,
       (SELECT DISTINCT DESCRICAO FROM ORV_PRODUTO Y WHERE Y.CODPRODUTO = X.CODPRODUTO) DESCRICAO

FROM CONSINCO.OR_NFDESPESA O LEFT JOIN CONSINCO.RF_PARAMNATNFDESP X ON X.CODHISTORICO = O.CODHISTORICO

WHERE O.CODHISTORICO IN (266,1065)

--ORDER BY DTAENTRADA DESC
)
;

SELECT * FROM CONSINCO.NAGV_LOCACAOITWORKS

WHERE DTA_LANCTO BETWEEN :DT1 AND :DT2

AND CAIXAENTRADA IN (SELECT LPAD(A.NROCGC,12,0)||LPAD(A.DIGCGC,2,0) FROM CONSINCO.GE_EMPRESA A WHERE A.NROEMPRESA = :LS1)

ORDER BY DTA_LANCTO DESC
