ALTER SESSION SET current_schema = CONSINCO;

SELECT  A.SEQFAMILIA FAMILIA, MA.FAMILIA DESCRICAO, A.CODORIGEMTRIB, MP.DESCRICAO 
FROM CONSINCO.MAP_FAMDIVISAO A LEFT JOIN CONSINCO.MAP_TRIBUTACAO B ON A.NROTRIBUTACAO = B.NROTRIBUTACAO
                               LEFT JOIN CONSINCO.MAP_FAMILIA MA ON A.SEQFAMILIA = MA.SEQFAMILIA
                               LEFT JOIN MAX_ATRIBUTOFIXO MP ON MP.LISTA = A.CODORIGEMTRIB AND  TIPATRIBUTOFIXO = 'ORIGEMMERCADORIA' 
                               
WHERE CODORIGEMTRIB = :NR1
