CREATE OR REPLACE VIEW CONSINCO.NAGV_LOCACAOITWORKS AS

(
SELECT (SELECT LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0)       FROM CONSINCO.GE_EMPRESA GE WHERE SEQPESSOA = O.NROEMPRESA) CAIXAENTRADA,
       O.DTAENTRADA DTA_LANCTO,
       (SELECT LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0)   FROM CONSINCO.GE_PESSOA G   WHERE SEQPESSOA = O.SEQPESSOA) CNPJCPFEMITENTE,
       X.CODPRODUTO,
       SUM(O.VALOR) VLR_TOTAL,
       TO_DATE('01/01/0001 00:00:00', 'DD/MM/YYYY HH24:MI:SS')  DTA_ALTERACAO

FROM CONSINCO.OR_NFDESPESA O LEFT JOIN CONSINCO.RF_PARAMNATNFDESP X ON X.CODHISTORICO = O.CODHISTORICO
   WHERE O.CODHISTORICO IN (266,1065)
   
   GROUP BY
   O.NROEMPRESA, O.SEQPESSOA,
   DTAENTRADA, CODPRODUTO
   
)
;
