SELECT TIPO SITUACAO, SEQFAMILIA, FAMILIA DESCRICAO_FAMILIA, CODORIGEMTRIB, NROTRIBUTACAO, TRIBUTACAO FROM (

SELECT '1' COD, 'IMP/IM.D com origem NAC' TIPO, A.SEQFAMILIA, MA.FAMILIA, A.CODORIGEMTRIB, A.NROTRIBUTACAO, B.TRIBUTACAO
FROM CONSINCO.MAP_FAMDIVISAO A LEFT JOIN CONSINCO.MAP_TRIBUTACAO B ON A.NROTRIBUTACAO = B.NROTRIBUTACAO
                               LEFT JOIN CONSINCO.MAP_FAMILIA MA ON A.SEQFAMILIA = MA.SEQFAMILIA

WHERE (UPPER(TRIBUTACAO) LIKE '%IMP%' OR UPPER(TRIBUTACAO) LIKE '%IM.D%') AND CODORIGEMTRIB NOT IN (1,2,3,8) AND UPPER(TRIBUTACAO) NOT LIKE '%LIMP%'
   OR UPPER(TRIBUTACAO) LIKE '%IMP.LIMP%'                                 AND CODORIGEMTRIB NOT IN (1,2,3,8)
/* OR UPPER(TRIBUTACAO) LIKE '%IM.D%'     AND CODORIGEMTRIB NOT IN (1,2,3,8) AND UPPER(TRIBUTACAO) NOT LIKE '%LIMP%'*/

UNION ALL

SELECT '2', 'NAC com origem IMP' TIPO, A.SEQFAMILIA, MA.FAMILIA, A.CODORIGEMTRIB, A.NROTRIBUTACAO, B.TRIBUTACAO
FROM CONSINCO.MAP_FAMDIVISAO A LEFT JOIN CONSINCO.MAP_TRIBUTACAO B ON A.NROTRIBUTACAO = B.NROTRIBUTACAO
                               LEFT JOIN CONSINCO.MAP_FAMILIA MA ON A.SEQFAMILIA = MA.SEQFAMILIA
                               
WHERE TRIBUTACAO NOT LIKE '%IMP%'   AND CODORIGEMTRIB NOT IN (0,4,5,6,7) AND TRIBUTACAO NOT LIKE '%IM.D%'
   OR TRIBUTACAO NOT LIKE '%IM.D%'  AND CODORIGEMTRIB NOT IN (0,4,5,6,7) AND TRIBUTACAO NOT LIKE 'IMP%'
   OR TRIBUTACAO     LIKE '%LIMP%'  AND CODORIGEMTRIB NOT IN (0,4,5,6,7) AND TRIBUTACAO NOT LIKE 'IMP%'

ORDER BY 1,6)

WHERE COD IN (DECODE(:LS1,'Tributação IMP com origem Nacional','1','Tributação Nacional com origem IMP','2',3))
          OR  DECODE(:LS1,'Tributação IMP com origem Nacional','1','Tributação Nacional com origem IMP','2',3) = 3;
   
