-- Ticket 509709 
-- Regra 1
-- Entradas no Rio com fornec tanto RJ quanto CDs ou Lojas SP

SELECT DISTINCT 'Entrada RJ + CDs (Ou Lojas SP)' TIPO_REGRA, XI.SEQPRODUTO PLU, DESCCOMPLETA
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON X.SEQNF = XI.SEQNF
                        INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
 WHERE X.NROEMPRESA IN (36,53) 
   AND G.UF = 'RJ'
   AND X.SEQPESSOA > 999
   AND X.STATUSNF != 'C'
   AND X.TIPNOTAFISCAL = 'E'
   AND EXISTS -- Puxa o que tambem teve entrada dos CDs
      (SELECT 1 FROM MLF_NOTAFISCAL XX INNER JOIN MLF_NFITEM XXI ON XX.SEQNF = XXI.SEQNF
               WHERE XX.SEQPESSOA NOT IN (36,53)
                 AND XX.SEQPESSOA < 999
                 AND XX.STATUSNF != 'C'
                 AND XX.TIPNOTAFISCAL = 'E'
                 AND XXI.SEQPRODUTO = XI.SEQPRODUTO
                 AND XX.NROEMPRESA = X.NROEMPRESA;
-- Regra 2
-- Com entradas != 'RJ' e sem nenhuma entrada RJ

SELECT DISTINCT 'Sem entradas RJ' TIPO_REGRA, XI.SEQPRODUTO PLU, DESCCOMPLETA
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON X.SEQNF = XI.SEQNF
                        INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
 WHERE X.NROEMPRESA IN (36,53) 
   AND G.UF != 'RJ'
   AND X.STATUSNF != 'C'
   AND X.TIPNOTAFISCAL = 'E'
   AND NOT EXISTS -- Puxa o que nao teve entrada pelo RJ
      (SELECT 1 FROM MLF_NOTAFISCAL XX INNER JOIN MLF_NFITEM XXI ON XX.SEQNF = XXI.SEQNF
                                       INNER JOIN GE_PESSOA  GG  ON GG.SEQPESSOA = XX.SEQPESSOA
               WHERE XX.SEQPESSOA NOT IN (36,53)
                 AND GG.UF = 'RJ'
                 AND XX.STATUSNF != 'C'
                 AND XX.TIPNOTAFISCAL = 'E'
                 AND XXI.SEQPRODUTO = XI.SEQPRODUTO
                 AND XX.NROEMPRESA = X.NROEMPRESA)
