SELECT A.NUMERONF, A.CODGERALOPER CGO, A.NROEMPRESA, A.DTAENTRADA, 
       A.SEQPESSOA||' - '||E.NOMERAZAO FORNECEDOR,
       B.SEQPRODUTO, C.DESCCOMPLETA DESCRICAO, C.SEQFAMILIA, D.ALIQUOTAIPI IPI_FAMILIA
FROM MLF_NOTAFISCAL A LEFT JOIN CONSINCO.MLF_NFITEM B  ON A.NUMERONF = B.NUMERONF AND A.NROEMPRESA = B.NROEMPRESA AND A.SEQNF = B.SEQNF
                      LEFT JOIN CONSINCO.MAP_PRODUTO C ON C.SEQPRODUTO = B.SEQPRODUTO
                      LEFT JOIN CONSINCO.MAP_FAMILIA D ON D.SEQFAMILIA = C.SEQFAMILIA 
                      LEFT JOIN CONSINCO.GE_PESSOA E ON A.SEQPESSOA = E.SEQPESSOA
WHERE A.CODGERALOPER IN (239,208) 
  AND A.DTAENTRADA BETWEEN SYSDATE - 180 AND SYSDATE
  
ORDER BY 3,4
