-- Adicionar SELECT em MADV_CRITICAPEDVENDA;
-- Configurar em MAD_CRITICAPEDCONFIG; 

-- Ticket 622626
-- Adicionado por Giuliano em 25/08/2025
-- Nao Permite Uso Consumo/Insumo ou Ativo no CGO 93

SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'Ins/Cons/Ativo Nao Perm CGO 93' CODCRITICA
   FROM CONSINCO.MAD_PEDVENDA A INNER JOIN MAD_PEDVENDAITEM I ON I.NROPEDVENDA = A.NROPEDVENDA AND I.NROEMPRESA = A.NROEMPRESA
                                INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
                                INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA

   WHERE 1=1
   AND A.SITUACAOPED != 'C'
   AND F.FINALIDADEFAMILIA IN ('A','O','U')
   AND A.CODGERALOPER = 93
;
