ALTER SESSION SET current_schema = CONSINCO;
SELECT * FROM (
SELECT * FROM (
SELECT PARTICIPANTE, NOME_PART_PAGTO, PARTICIP_TRANS, NOME_PART_TRANSACAO, TO_CHAR(SUM(TOTAL_BRUTO_VENDAS),        'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_BRUTO_VENDAS, 
                                                                           TO_CHAR(SUM(TOTAL_PRESTACOES_SERVICOS), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL_PRESTACOES_SERVICOS FROM (
SELECT LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0) PARTICIPANTE,
       SUBSTR(B.NOMERAZAO,1,35) NOME_PART_PAGTO,
       CASE WHEN A.CODESPECIE IN ('IFOOD','IFOPDV') THEN LPAD(B.NROCGCCPF,12,0)||lpad(B.DIGCGCCPF,2,0)
            WHEN A.CODESPECIE IN ('CCECOM','CDECOM','TKECOM') THEN '14071169000147'
              ELSE NULL END PARTICIP_TRANS,
       SUBSTR(D.NOMERAZAO,1,35) NOME_PART_TRANSACAO,
       CASE WHEN A.NROEMPRESA >= 500 THEN 0 ELSE SUM(A.VLRORIGINAL) END TOTAL_BRUTO_VENDAS,
       CASE WHEN A.CODESPECIE IN ('SERVRC') THEN SUM(NVL(A.VLRORIGINAL,0)) ELSE 0 END TOTAL_PRESTACOES_SERVICOS

  FROM CONSINCO.FI_TITULO A
  INNER JOIN consinco.ge_pessoa b  on (a.seqpessoa = b.seqpessoa)
  INNER JOIN consinco.ge_empresa c on (a.nroempresa = c.nroempresa)
  LEFT  JOIN CONSINCO.GE_PESSOA D ON LPAD(D.NROCGCCPF,12,0)||LPAD(D.DIGCGCCPF,2,0) = (
       CASE WHEN A.CODESPECIE IN ('IFOOD','IFOPDV') THEN LPAD(B.NROCGCCPF,12,0)||lpad(B.DIGCGCCPF,2,0)
            WHEN A.CODESPECIE IN ('CCECOM','CDECOM','TKECOM') THEN '14071169000147'
            ELSE NULL END)
  where a.codespecie in ('CARDEB', 'CARTAO', 'TICKET', 'CCECOM', 'CDECOM', 'TKECOM','IFOOD','IFOPDV','SERVRC')
    and a.situacao != 'C'     and B.SEQPESSOA NOT IN (1458426)
    and a.dtaemissao BETWEEN :DT1 AND :DT2
    and A.NROEMPRESA = :NR1

    GROUP BY LPAD(B.NROCGCCPF,12,0)||LPAD(B.DIGCGCCPF,2,0), B.NOMERAZAO, A.CODESPECIE, D.NOMERAZAO, A.NROEMPRESA
)


GROUP BY PARTICIPANTE, NOME_PART_PAGTO, PARTICIP_TRANS, NOME_PART_TRANSACAO
) ORDER BY 2)

UNION ALL

SELECT NULL, NULl, NULL, NULl, NULL, NULL FROM DUAL

UNION ALL

SELECT NULL, NULL, NULL, 'SUBTOTAL:', TO_CHAR(SUM(TOTAL_BRUTO_VENDAS), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.'''), 
                                      TO_CHAR(SUM(TOTAL_PREST_SERV),   'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') FROM (
SELECT CASE WHEN A.NROEMPRESA >= 500 THEN 0 ELSE SUM(A.VLRORIGINAL) END TOTAL_BRUTO_VENDAS,
       CASE WHEN A.CODESPECIE IN ('SERVRC') THEN SUM(NVL(A.VLRORIGINAL,0)) ELSE 0 END TOTAL_PREST_SERV

  FROM CONSINCO.FI_TITULO A
  INNER JOIN consinco.ge_pessoa b  on (a.seqpessoa = b.seqpessoa)
  INNER JOIN consinco.ge_empresa c on (a.nroempresa = c.nroempresa)
  LEFT  JOIN CONSINCO.GE_PESSOA D ON LPAD(D.NROCGCCPF,12,0)||LPAD(D.DIGCGCCPF,2,0) = (
       CASE WHEN A.CODESPECIE IN ('IFOOD','IFOPDV') THEN LPAD(B.NROCGCCPF,12,0)||lpad(B.DIGCGCCPF,2,0)
            WHEN A.CODESPECIE IN ('CCECOM','CDECOM','TKECOM') THEN '14071169000147'
            ELSE NULL END)
  where a.codespecie in ('CARDEB', 'CARTAO', 'TICKET', 'CCECOM', 'CDECOM', 'TKECOM','IFOOD','IFOPDV','SERVRC')
    and a.situacao != 'C'     and B.SEQPESSOA NOT IN (1458426)
    and a.dtaemissao BETWEEN :DT1 AND :DT2
    AND A.NROEMPRESA = :NR1 
    
    GROUP BY A.NROEMPRESA, CODESPECIE)
    
UNION ALL 

SELECT NULL, NULL, NULL, 'TOTAL:', TO_CHAR(TOTAL, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') TOTAL, NULL 
FROM (
SELECT SUM(A.VLRORIGINAL) TOTAL  
FROM CONSINCO.FI_TITULO A
  INNER JOIN consinco.ge_pessoa b  on (a.seqpessoa = b.seqpessoa)
  INNER JOIN consinco.ge_empresa c on (a.nroempresa = c.nroempresa)
  LEFT  JOIN CONSINCO.GE_PESSOA D ON LPAD(D.NROCGCCPF,12,0)||LPAD(D.DIGCGCCPF,2,0) = (
       CASE WHEN A.CODESPECIE IN ('IFOOD','IFOPDV') THEN LPAD(B.NROCGCCPF,12,0)||lpad(B.DIGCGCCPF,2,0)
            WHEN A.CODESPECIE IN ('CCECOM','CDECOM','TKECOM') THEN '14071169000147'
            ELSE NULL END)
  where a.codespecie in ('CARDEB', 'CARTAO', 'TICKET', 'CCECOM', 'CDECOM', 'TKECOM','IFOOD','IFOPDV','SERVRC')
    and a.situacao != 'C'     and B.SEQPESSOA NOT IN (1458426)
    and a.dtaemissao BETWEEN :DT1 AND :DT2
    AND A.NROEMPRESA = :NR1)
