ALTER SESSION SET current_schema = CONSINCO;

SELECT A.CODGERALOPER CGO, DESCRICAO, TO_DATE(DTA, 'DD/MM/YYYY') DATA_ULTMOVTO
FROM MAX_CODGERALOPER A LEFT JOIN (

SELECT CODGERALOPER, MAX(DTA) DTA FROM 
(
SELECT CODGERALOPER, MAX(B.DTAINCLUSAO) dta FROM MAD_PEDVENDA B GROUP BY CODGERALOPER
UNION ALL
SELECT CODGERALOPER, MAX(DTAEMISSAO) FROM MLFV_BASENFE GROUP BY CODGERALOPER 
UNION ALL
SELECT CODGERALOPER, MAX(DTAOPERACAO) FROM FATO_PERDA@CONSINCODW GROUP BY CODGERALOPER
UNION ALL
SELECT CODGERALOPER, MAX(DTAMOVIMENTO) DTA FROM MFL_DOCTOFISCAL WHERE DTAMOVIMENTO > SYSDATE - 100 GROUP BY CODGERALOPER 
UNION ALL
SELECT A.CGO, MAX(A.DTAENTRADA) FROM CONSINCO.OR_NFDESPESA A GROUP BY CGO
UNION ALL
SELECT C.CODGERALOPER, MAX(C.DTAOPERACAO) FROM FATO_MOVTOESTQ@CONSINCODW C GROUP BY CODGERALOPER
UNION ALL
SELECT CODGERALOPER, MAX(A.DTAEMISSAO) FROM CONSINCO.MLF_NOTAFISCAL A GROUP BY CODGERALOPER

) GROUP BY CODGERALOPER) B ON B.CODGERALOPER = A.CODGERALOPER

ORDER BY 1

