SELECT 'Entrada' TIPO, X.NROEMPRESA LOJA, SUM(FVALORTOTALNF(X.ROWID, 'N')) VALOR_TOTAL_NF, SUM(XI.VLRICMS) ICMS, SUM(XI.VLRPIS) PIS, SUM(XI.VLRCOFINS) COFINS, 
       SUM(XI.VLRIMPOSTOCBS) CBS, SUM(XI.VLRIMPOSTOIBSUF) IBS_UF, SUM(XI.VLRIMPOSTOIBSMUN) IBS_MUN,
       SUM(XI.VLRIMPOSTOIS) VLR_IS, SUM(XI.VLRFCPST) FCP_ST, SUM(XI.VLRIPI) IPI
       
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
 WHERE X.NUMERONF = 1344554 
   AND X.NROEMPRESA = 507
   AND X.TIPNOTAFISCAL = 'E'
 GROUP BY X.NROEMPRESA
 
UNION ALL

SELECT 'Saida' TIPO, X.NROEMPRESA LOJA, SUM(FVALORTOTALNF(X.ROWID, 'N')) VALOR_TOTAL_NF, SUM(XI.VLRICMS) ICMS, SUM(XI.VLRPIS) PIS, SUM(XI.VLRCOFINS) COFINS, 
       SUM(XI.VLRIMPOSTOCBS) CBS, SUM(XI.VLRIMPOSTOIBSUF) IBS_UF, SUM(XI.VLRIMPOSTOIBSMUN) IBS_MUN,
       SUM(XI.VLRIMPOSTOIS) VLR_IS, SUM(XI.VLRFCPST) FCP_ST, SUM(XI.VLRIPI) IPI
       
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
 WHERE X.DTAEMISSAO >= SYSDATE - 10
   AND X.TIPNOTAFISCAL = 'S'
   AND ROWNUM <= 50
 GROUP BY X.NROEMPRESA
 
UNION ALL

SELECT 'Saida' TIPO, X.NROEMPRESA LOJA, SUM(FVALORTOTALNF(X.ROWID, 'D')) VALOR_TOTAL_NF, SUM(XI.VLRICMS) ICMS, SUM(XI.VLRPIS) PIS, SUM(XI.VLRCOFINS) COFINS, 
       SUM(XI.VLRIMPOSTOCBS) CBS, SUM(XI.VLRIMPOSTOIBSUF) IBS_UF, SUM(XI.VLRIMPOSTOIBSMUN) IBS_MUN,
       SUM(XI.VLRIMPOSTOIS) VLR_IS, SUM(XI.VLRFCPST) FCP_ST, SUM(XI.VLRIPI) IPI
       
  FROM MFL_DOCTOFISCAL X INNER JOIN MFL_DFITEM XI ON XI.SEQNF = X.SEQNF
 WHERE X.DTAMOVIMENTO >= SYSDATE - 10
   AND ROWNUM <= 50
 GROUP BY X.NROEMPRESA
