-- Select: MADV_CRITICAPEDVENDA
-- Config: MAD_CRITICAPEDCONFIG

-- Ticket 691854
-- Giuliano 24/02/26

SELECT DISTINCT G.NROPEDVENDA, G.NROEMPRESA, 'Rej. Fis. Trib + Origem + Aliq' CODCRITICA
FROM mad_pedvendaitem G INNER JOIN MAD_PEDVENDA H ON G.NROPEDVENDA = H.NROPEDVENDA
                        INNER JOIN GE_PESSOA G1 ON G1.SEQPESSOA = H.SEQPESSOA
                        INNER JOIN GE_PESSOA G2 ON G2.SEQPESSOA = H.NROEMPRESA

-- Primeiro filtra import
WHERE (G.SEQPRODUTO IN (SELECT DISTINCT A.SEQPRODUTO FROM MAP_PRODUTO A WHERE A.SEQPRODUTO = G.SEQPRODUTO AND A.SEQFAMILIA IN
                      (SELECT DISTINCT B.SEQFAMILIA FROM MAP_FAMDIVISAO B
                      INNER JOIN CONSINCO.MAP_TRIBUTACAO C ON B.NROTRIBUTACAO = C.NROTRIBUTACAO
                      INNER JOIN MAP_TRIBUTACAOUF T ON T.NROTRIBUTACAO = B.NROTRIBUTACAO AND T.NROREGTRIBUTACAO = 0 AND T.UFEMPRESA = G2.UF AND T.UFCLIENTEFORNEC = G1.UF AND T.TIPTRIBUTACAO = 'SC' AND T.UFEMPRESA != T.UFCLIENTEFORNEC
                       

WHERE ((UPPER(TRIBUTACAO) LIKE '%IMP%' OR UPPER(TRIBUTACAO) LIKE 'IM%')      AND CODORIGEMTRIB  IN (1,2,3,6,7,8) AND UPPER(TRIBUTACAO) NOT LIKE '%LIMP%'
   OR   UPPER(TRIBUTACAO) LIKE '%IMP.LIMP%'                                  AND CODORIGEMTRIB  IN (1,2,3,6,7,8))
  AND T.PERALIQUOTA != 4))
  
  OR 
-- Depois filtra nacional
  G.SEQPRODUTO IN (SELECT DISTINCT A.SEQPRODUTO FROM MAP_PRODUTO A WHERE A.SEQPRODUTO = G.SEQPRODUTO AND A.SEQFAMILIA IN
                      (SELECT DISTINCT B.SEQFAMILIA FROM MAP_FAMDIVISAO B
                      INNER JOIN CONSINCO.MAP_TRIBUTACAO C ON B.NROTRIBUTACAO = C.NROTRIBUTACAO
                      INNER JOIN MAP_TRIBUTACAOUF T ON T.NROTRIBUTACAO = B.NROTRIBUTACAO AND T.NROREGTRIBUTACAO = 0 AND T.UFEMPRESA = G2.UF AND T.UFCLIENTEFORNEC = G1.UF AND T.TIPTRIBUTACAO = 'SC' AND T.UFEMPRESA != T.UFCLIENTEFORNEC
                       

WHERE (UPPER(TRIBUTACAO) NOT LIKE '%IM%' AND CODORIGEMTRIB IN (0,4,5,6)
  AND T.PERALIQUOTA = 4))))
   
 AND G.DTAINCLUSAO > SYSDATE - 10
 AND H.SITUACAOPED NOT IN ('C','F') 
 AND (H.NROEMPRESA IN (36,53) OR H.SEQPESSOA IN (36,53))
