ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT A.NROEMPRESA EMP, L.LOCAL, P.SEQPRODUTO||' - '||P.DESCCOMPLETA PRODUTO,
       QTDLANCTO, VALORVLRNF, A.CODGERALOPER||' - '||O.DESCRICAO CGO,
        DTAENTRADASAIDA DTA_LANCTO ,DTAHORGERACAO DTA_ESTORNO, USUGERACAO USU_ESTORNO

  FROM MRL_LANCTOESTQEXC A  INNER JOIN MAP_PRODUTO P ON A.SEQPRODUTO = P.SEQPRODUTO
                            INNER JOIN MRL_LOCAL   L ON L.SEQLOCAL = A.LOCAL AND A.NROEMPRESA = L.NROEMPRESA
                            INNER JOIN MAX_CODGERALOPER O ON O.CODGERALOPER = A.CODGERALOPER

 WHERE 1=1
      
   AND TRUNC(DTAHORLANCTO) > DATE '2024-01-01'
   --AND A.NROEMPRESA = '1'
   AND EXTRACT (MONTH FROM DTAHORLANCTO) != EXTRACT (MONTH FROM DTAHORGERACAO)
   AND A.CODGERALOPER IN (110,111,112,113,114,115,20,21,24,25,258,259,263,269,270,271,272,273,274,30,33,34,35,41,46,47,49,549,551,62,63,66,71,73,90,91)
   
  AND EXTRACT (DAY FROM DTAHORGERACAO) >= 15 -- Apenas apos o dia 15 causa problema
   
 ORDER BY A.NROEMPRESA,
          A.DTAENTRADASAIDA,
          A.NRODOCUMENTO,
          A.NRONFCUPOM,
          A.SEQPRODUTO

