-- Inserir crítica na CONSINCO.MAD_CRITICAPEDCONFIG 

UNION ALL -- Giuliano - Solic. Simone Ticket 245643 | 14/06/2023
          -- Bloqueia emissão para UF != SP pelo CGO 48

SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'CGO não perm. emissão FORA SP' CODCRITICA
   FROM CONSINCO.MAD_PEDVENDA A LEFT JOIN MRL_FORMAPAGTO D ON A.NROFORMAPAGTO = D.NROFORMAPAGTO
                                LEFT JOIN GE_PESSOA B      ON A.SEQPESSOA = B.SEQPESSOA
   WHERE 1=1
   AND B.UF != 'SP'
   AND A.SITUACAOPED != 'C'
   AND A.DTAINCLUSAO > SYSDATE - 50
   AND CODGERALOPER IN (48)
