SELECT * FROM (

SELECT DISTINCT C.NROEMPRESA EMPRESA, A.SEQPRODUTO PLU, A.DESCCOMPLETA DESCRICAO, 
       TO_CHAR(C.PRECOVDANORMAL,  'FM999G999G999D90', 'nls_numeric_characters='',.''') PRECO_VDA, 
       TO_CHAR(C.VLRCUSTOLIQUIDO, 'FM999G999G999D90', 'nls_numeric_characters='',.''') CUSTO_GERENCIAL, ROUND(C.MGMPRECOMINVDAEMPRESA,2) MARGEM, 
       ROUND(SUM(D.VLRTOTALVDA) - SUM(D.VLRCUSLIQUIDOVDA) - (SUM(D.VLRICMSVDA) + SUM(D.VLRPISVDA) + SUM(D.VLRCOFINSVDA) + SUM(D.VLRIMPOSTOVDA) + SUM(D.VLRDESPESAVDA) + SUM(D.VLRCOMISSAOVDA)),2) TOTAL_LUCRAT_PERIODO,
       ROUND((ROUND(SUM(D.VLRTOTALVDA) - SUM(D.VLRCUSLIQUIDOVDA) - (SUM(D.VLRICMSVDA) + SUM(D.VLRPISVDA) + SUM(D.VLRCOFINSVDA) + SUM(D.VLRIMPOSTOVDA) + SUM(D.VLRDESPESAVDA) + SUM(D.VLRCOMISSAOVDA)),2) *100) / 
       (CASE WHEN SUM(D.VLRTOTALVDA) = 0 THEN 1 ELSE (SUM(D.VLRTOTALVDA) - SUM(D.VLRCUSLIQUIDODEVOL)) END),2) MARGEM_LUCRAT_PERIODO,
       TO_CHAR(D.DTAENTRADASAIDA, 'DD-MM-YYYY') DATA_MOVTO
       
FROM CONSINCO.MAP_PRODUTO A INNER JOIN CONSINCO.MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO AND B.TIPCODIGO   = 'B' 
                            INNER JOIN CONSINCO.MAXV_MGMBASEPRODSEG C ON A.SEQPRODUTO = C.SEQPRODUTO AND C.STATUSVENDA = 'A' AND C.NROSEGMENTO = 2 AND C.NROEMPRESA IN (#LS1)
                            INNER JOIN CONSINCO.MRL_CUSTODIA D   ON D.SEQPRODUTO = C.SEQPRODUTO AND D.NROEMPRESA = C.NROEMPRESA AND D.DTAENTRADASAIDA BETWEEN :DT1 AND :DT2
                            
WHERE (A.DESCCOMPLETA LIKE 'PAD%' OR A.DESCCOMPLETA LIKE 'ROT%')

GROUP BY C.NROEMPRESA, A.SEQPRODUTO, A.DESCCOMPLETA , C.PRECOVDANORMAL, C.VLRCUSTOLIQUIDO, C.MGMPRECOMINVDAEMPRESA, D.DTAENTRADASAIDA

ORDER BY 3 ASC)

WHERE DESCRICAO IN (DECODE (#LS2, 'Padaria', 'PAD%', 'Rotisserie', 'ROT%','X'))
   OR DECODE (#LS2, 'Padaria', 'PAD%', 'Rotisserie', 'ROT%','X') = 'X'

