-- Adicionar crítica em ESPV_CRITICADEVNFFORN

-- Ticket 628760
-- Adicionado por Giuliano em13/11/2025
-- Validacao Emissao CGOs x Local

SELECT A.IDSESSION,
       A.INST_ID,
       A.SEQNFDEVFORNEC,
       A.SEQPRODUTO,
       8 CODCRITICA,
       'CGO '||A.CODGERALOPER||' Não permitido para emissão através do local '||LOCAL MENSAGEM,
       'B' INDBLOQUEIOLIBERA
  FROM MFLX_NFDEVFORNEC A INNER JOIN MRL_LOCAL B ON B.SEQLOCAL = A.SEQLOCAL AND B.NROEMPRESA = A.NROEMPRESA
 WHERE 1=1
   AND A.CODGERALOPER IN (811,927) AND B.LOCAL = 'AVARIA'
    OR A.CODGERALOPER IN (934,933) AND B.LOCAL = 'LOJA'
