-- QRP em https://github.com/GiulianoGMS/QRPs/blob/main/RelBaseCupom_v2.QRP

SELECT TO_CHAR(:LS1) LOJA,
       MFL_DOCTOFISCAL.NUMERODF NRONF,
       TO_CHAR(MFL_DOCTOFISCAL.DTAMOVIMENTO, 'DD/MM/YYYY') AS DTAEMISSAO,
       MFL_DOCTOFISCAL.CODGERALOPER CGO,
       GE_PESSOA.NOMERAZAO FORNECEDOR,
       TO_CHAR(SUM(MFL_DFITEM.VLRITEM + MFL_DFITEM.VLRACRESCIMO -
                   MFL_DFITEM.VLRDESCONTO),
               'FM999999999999990D00') AS TOTAL,
       TO_CHAR(:DT1, 'DD/MM/YYYY') AS INICIO,
       TO_CHAR(:DT2, 'DD/MM/YYYY') AS FIM,
       MFL_DOCTOFISCAL.NFREFERENCIANRO CUPOM_REF,
       (SELECT TO_CHAR(MAX(A.DTAHORAEMISSAO), 'DD/MM/YYYY')
          FROM PDV_DOCTO A
         WHERE A.CHAVEACESSO =
               (SELECT C.NFECHAVEACESSO
                  FROM MFL_DOCTOFISCAL C
                 WHERE C.SEQNF = MFL_DOCTOFISCAL.SEQNFREF)) DTA_CUPOM

  FROM MFL_DOCTOFISCAL, MFL_DFITEM, MAX_EMPRESA, GE_PESSOA

 WHERE MFL_DFITEM.NUMERODF = MFL_DOCTOFISCAL.NUMERODF
   AND MFL_DFITEM.SERIEDF = MFL_DOCTOFISCAL.SERIEDF
   AND MFL_DFITEM.NROSERIEECF = MFL_DOCTOFISCAL.NROSERIEECF
   AND MFL_DFITEM.NROEMPRESA = MFL_DOCTOFISCAL.NROEMPRESA
   AND MAX_EMPRESA.NROEMPRESA = MFL_DOCTOFISCAL.NROEMPRESA
   AND GE_PESSOA.SEQPESSOA = MFL_DOCTOFISCAL.SEQPESSOA
   AND MFL_DOCTOFISCAL.DTAMOVIMENTO BETWEEN :DT1 AND :DT2
   AND MFL_DOCTOFISCAL.NROEMPRESA IN (:LS1)
   AND MFL_DOCTOFISCAL.CODGERALOPER IN (#LS2)
   AND MFL_DOCTOFISCAL.STATUSDF != 'C'
 GROUP BY MFL_DOCTOFISCAL.NUMERODF,
          MFL_DOCTOFISCAL.DTAMOVIMENTO,
          MFL_DOCTOFISCAL.CODGERALOPER,
          GE_PESSOA.NOMERAZAO,
          MFL_DOCTOFISCAL.NFREFERENCIANRO,
          MFL_DOCTOFISCAL.SEQNFREF

UNION

SELECT TO_CHAR(:LS1) LOJA,
       MLF_NOTAFISCAL.NUMERONF NRONF,
       TO_CHAR(MLF_NOTAFISCAL.DTASAIDA, 'DD-MM-YYYY') DTAEMISSAO,
       MLF_NOTAFISCAL.CODGERALOPER CGO,
       GE_PESSOA.NOMERAZAO FORNECEDOR,
       TO_CHAR(SUM((MLF_NFITEM.VLRITEM + CASE
                     WHEN MLF_NOTAFISCAL.INDCONSIDFRETEDESPTRIB = 'N' THEN
                      MLF_NFITEM.VLRDESPTRIBUTITEM + MLF_NFITEM.VLRFRETENANF
                     ELSE
                      MLF_NFITEM.VLRDESPTRIBUTITEM
                   END + MLF_NFITEM.VLRDESPNTRIBUTITEM + MLF_NFITEM.VLRIPI +
                   DECODE(NVL(MLF_NFITEM.LANCAMENTOST, 'C'),
                           'O',
                           0,
                           'S',
                           0,
                           MLF_NFITEM.VLRICMSST) - MLF_NFITEM.VLRDESCITEM -
                   NVL(MLF_NFITEM.VLRDESCSUFRAMA, 0))),
               'FM999999999999990D00') AS VALOR_TOTAL,
       TO_CHAR(:DT1, 'DD/MM/YYYY') AS INICIO,
       TO_CHAR(:DT2, 'DD/MM/YYYY') AS FIM,
       MLF_NOTAFISCAL.NFREFERENCIANRO,
       (SELECT TO_CHAR(MAX(A.DTAHORAEMISSAO), 'DD/MM/YYYY')
          FROM PDV_DOCTO A
         WHERE A.CHAVEACESSO =
               (SELECT C.NFECHAVEACESSO
                  FROM MFL_DOCTOFISCAL C
                 WHERE C.SEQNF = MLF_NOTAFISCAL.SEQNFREF))

  FROM MLF_NOTAFISCAL, MLF_NFITEM, MAX_EMPRESA, GE_PESSOA, MAX_CODGERALOPER

 WHERE MLF_NFITEM.NUMERONF = MLF_NOTAFISCAL.NUMERONF
   AND MLF_NFITEM.SERIENF = MLF_NOTAFISCAL.SERIENF
   AND MLF_NFITEM.TIPNOTAFISCAL = MLF_NOTAFISCAL.TIPNOTAFISCAL
   AND MLF_NFITEM.NROEMPRESA = MLF_NOTAFISCAL.NROEMPRESA
   AND MLF_NFITEM.SEQPESSOA = MLF_NOTAFISCAL.SEQPESSOA
   AND MLF_NFITEM.SEQNF = MLF_NOTAFISCAL.SEQNF
   AND MAX_EMPRESA.NROEMPRESA = MLF_NOTAFISCAL.NROEMPRESA
   AND GE_PESSOA.SEQPESSOA = MLF_NOTAFISCAL.SEQPESSOA
   AND MAX_CODGERALOPER.CODGERALOPER = MLF_NOTAFISCAL.CODGERALOPER
   AND (MLF_NOTAFISCAL.TIPNOTAFISCAL = 'S' OR
       (MLF_NOTAFISCAL.TIPNOTAFISCAL = 'E' AND
       MAX_CODGERALOPER.TIPUSO = 'E'))
      
   AND (MLF_NOTAFISCAL.DTAENTRADA BETWEEN :DT1 AND :DT2 OR
       (MLF_NOTAFISCAL.DTAEMISSAO BETWEEN :DT1 AND :DT2 AND
       MLF_NOTAFISCAL.DTAENTRADA IS NULL))
   AND MLF_NOTAFISCAL.NROEMPRESA IN (:LS1)
   AND MLF_NOTAFISCAL.CODGERALOPER IN (#LS2)
   AND MLF_NOTAFISCAL.STATUSNF != 'C'
 GROUP BY MLF_NOTAFISCAL.CODGERALOPER,
          GE_PESSOA.NOMERAZAO,
          MLF_NOTAFISCAL.NFREFERENCIANRO,
          MLF_NOTAFISCAL.SEQNFREF,
          MLF_NOTAFISCAL.NROEMPRESA,
          MLF_NOTAFISCAL.SEQPESSOA,
          MLF_NOTAFISCAL.NUMERONF,
          TO_CHAR(MLF_NOTAFISCAL.DTASAIDA, 'DD-MM-YYYY')

 ORDER BY NRONF, DTAEMISSAO
