CREATE TABLE NAGT_BASE_665322 (SEQPRODUTO NUMBER(30));

SELECT DISTINCT B.SEQPRODUTO PLU, DESCCOMPLETA, F.SEQFORNECEDOR||' - '||G.NOMERAZAO FORNEC,
       CASE WHEN EXISTS (SELECT 1 FROM MLF_GNRE G WHERE G.SEQAUXNOTAFISCAL = XI.SEQAUXNOTAFISCAL AND TIPOGUIA IN ('R','G')) THEN 'C/Guia' ELSE NULL END GNRE
         
  FROM NAGT_BASE_665322 B INNER JOIN MRL_PRODUTOEMPRESA E ON E.SEQPRODUTO = B.SEQPRODUTO 
                           LEFT JOIN MLF_NFITEM XI ON XI.SEQNF = E.SEQNFULTENTRADA AND XI.SEQPRODUTO = B.SEQPRODUTO
                          INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = B.SEQPRODUTO
                          INNER JOIN MAP_FAMFORNEC F ON F.SEQFAMILIA = P.SEQFAMILIA AND F.PRINCIPAL = 'S'
                          INNER JOIN GE_PESSOA G ON G.SEQPESSOA = F.SEQFORNECEDOR;
