SELECT TIPO SITUACAO, PLU, DESCCOMPLETA DESCRICAO_PROD, STATUS_VENDA, SEQFAMILIA,/* FAMILIA DESCRICAO_FAMILIA, */
       'COD. ORIGEM: '||CODORIGEMTRIB||' - TRIBUTACAO: '||NROTRIBUTACAO||' - '||TRIBUTACAO DADOS_FISCAIS FROM (

SELECT '1' COD, 'IMP com origem NAC' TIPO, A.SEQFAMILIA, MA.FAMILIA, A.CODORIGEMTRIB, A.NROTRIBUTACAO, B.TRIBUTACAO, MP.SEQPRODUTO PLU, MP.DESCCOMPLETA,
       CASE WHEN MP.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = MP.SEQPRODUTO AND Z.STATUSVENDA = 'A')  THEN 'ATIVO' 
                ELSE 'INATIVO' END STATUS_VENDA
                  
FROM CONSINCO.MAP_FAMDIVISAO A LEFT JOIN CONSINCO.MAP_TRIBUTACAO B ON A.NROTRIBUTACAO = B.NROTRIBUTACAO
                               LEFT JOIN CONSINCO.MAP_FAMILIA MA ON A.SEQFAMILIA = MA.SEQFAMILIA
                               LEFT JOIN CONSINCO.MAP_PRODUTO MP ON MA.SEQFAMILIA = MP.SEQFAMILIA

WHERE UPPER(TRIBUTACAO) LIKE '%IMP%'      AND CODORIGEMTRIB NOT IN (1,2,3,7,6,8) AND UPPER(TRIBUTACAO) NOT LIKE '%LIMP%'
   OR UPPER(TRIBUTACAO) LIKE '%IMP.LIMP%' AND CODORIGEMTRIB NOT IN (1,2,3,7,6,8) 

UNION ALL

SELECT '2', 'NAC com origem IMP' TIPO, A.SEQFAMILIA, MA.FAMILIA, A.CODORIGEMTRIB, A.NROTRIBUTACAO, B.TRIBUTACAO, MP.SEQPRODUTO PLU, MP.DESCCOMPLETA,
       CASE WHEN MP.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM CONSINCO.DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = MP.SEQPRODUTO AND Z.STATUSVENDA = 'A')  THEN 'ATIVO' 
                ELSE 'INATIVO' END STATUS_VENDA
FROM CONSINCO.MAP_FAMDIVISAO A LEFT JOIN CONSINCO.MAP_TRIBUTACAO B ON A.NROTRIBUTACAO = B.NROTRIBUTACAO
                               LEFT JOIN CONSINCO.MAP_FAMILIA MA ON A.SEQFAMILIA = MA.SEQFAMILIA
                               LEFT JOIN CONSINCO.MAP_PRODUTO MP ON MA.SEQFAMILIA = MP.SEQFAMILIA
                               
WHERE TRIBUTACAO NOT LIKE '%IMP%'   AND CODORIGEMTRIB IN (1,2,3,7,6,8)
   OR TRIBUTACAO     LIKE '%LIMP%'  AND CODORIGEMTRIB IN (1,2,3,7,6,8) AND TRIBUTACAO NOT LIKE 'IMP%'

ORDER BY 1,6)

WHERE COD IN (DECODE(:LS1,'Tributação IMP com origem Nacional','1','Tributação Nacional com origem IMP','2',3)) AND STATUS_VENDA = 'ATIVO'
          OR DECODE(:LS1,'Tributação IMP com origem Nacional','1','Tributação Nacional com origem IMP','2',3) = 3 AND STATUS_VENDA = 'ATIVO';
