SELECT NUMEROCONTRANOTA,
       NFPRODUTOR,
       NOMEREDUZIDO,
       CGO,
       CODIGO,
       FORNECEDOR,
       DTAENTRADA,
       VALORNF,
       VALORNFDEV,
       TO_CHAR(:DT1,'DD/MM/YYYY') AS inicio,
       TO_CHAR(:DT2,'DD/MM/YYYY') AS fim

FROM(
SELECT A.NUMERONF NUMEROCONTRANOTA,
       A.NFREFERENCIANRO NFPRODUTOR,
       XX.NOMEREDUZIDO,
       A.CODGERALOPER CGO,
       TO_CHAR(A.SEQPESSOA) CODIGO,
       TO_CHAR(B.NOMERAZAO) FORNECEDOR,
       TO_CHAR(A.DTAENTRADA, 'DD/MM/YYYY') DTAENTRADA,
       SUM(X.VLRTOTALITEM) VALORNF,
       NULL VALORNFDEV
  FROM CONSINCO.MLF_NOTAFISCAL A, CONSINCO.GE_PESSOA B, CONSINCO.MLF_NFITEM X, CONSINCO.MAX_EMPRESA XX
 WHERE A.SEQPESSOA = B.SEQPESSOA
   AND A.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
   AND B.SEQPESSOA = X.SEQPESSOA
   AND XX.NROEMPRESA = A.NROEMPRESA
   AND A.STATUSNF != 'C'
   AND XX.NROEMPRESA = X.NROEMPRESA
   AND XX.NOMEREDUZIDO IN (#LS1)
   AND A.CODGERALOPER IN (200, 203, 19,255,81,82,83,84,85)
   AND A.DTAENTRADA BETWEEN :DT1 AND :DT2
 GROUP BY A.NUMERONF,
          A.NFREFERENCIANRO,
          A.NROEMPRESA,
          A.SEQPESSOA,
          A.CODGERALOPER,
          XX.NOMEREDUZIDO,
          B.NOMERAZAO,
          A.DTAENTRADA

UNION ALL

SELECT A.NUMERONF NUMEROCONTRANOTA,
       A.NFREFERENCIANRO NFPRODUTOR,
       XX.NOMEREDUZIDO,
       A.CODGERALOPER CGO,
       TO_CHAR(A.SEQPESSOA) CODIGO,
       TO_CHAR(Z.NOMERAZAO) FORNECEDOR,
       TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') DTAENTRADA,
        SUM(X.VLRTOTALITEM) VALORNF,
       SUM(X.VLRITEM + NVL(X.VLRFCPST,0) + X.VLRIPI + X.VLRICMSST + X.VLRDESPNTRIBUTITEM + NVL(X.VLRDESPTRIBUTITEM,0))-SUM(X.VLRDESCITEM) VALORNFDEV

  FROM CONSINCO.MLF_NOTAFISCAL A
 INNER JOIN CONSINCO.MLF_NFITEM X
    ON (A.NUMERONF = X.NUMERONF AND A.SERIENF = X.SERIENF AND
       A.NROEMPRESA = X.NROEMPRESA AND A.SEQPESSOA = X.SEQPESSOA)
 INNER JOIN CONSINCO.GE_EMPRESA XX
    ON (A.NROEMPRESA = XX.NROEMPRESA)
 INNER JOIN CONSINCO.GE_PESSOA Z
    ON (Z.SEQPESSOA = A.SEQPESSOA)
   AND A.STATUSNF != 'C'
   AND EXISTS (SELECT *
          FROM CONSINCO.MLF_NOTAFISCAL B
         WHERE A.SEQNFREF = B.SEQNF
           AND B.CODGERALOPER IN (200,203,255,81,82,83,84,85))
   AND XX.NOMEREDUZIDO IN (#LS1)
   AND A.CODGERALOPER IN (802, 853,255)
   AND A.DTAEMISSAO BETWEEN :DT1 AND :DT2
   GROUP BY A.NUMERONF,
          A.NFREFERENCIANRO,
          A.NROEMPRESA,
          A.SEQPESSOA,
          A.CODGERALOPER,
          XX.NOMEREDUZIDO,
          Z.NOMERAZAO,
          A.DTAEMISSAO

UNION ALL

SELECT NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       SUM(X.VLRITEM + X.VLRACRESCIMO - X.VLRDESCONTO) VALORNFDEV
  FROM CONSINCO.MFL_DOCTOFISCAL A
 INNER JOIN CONSINCO.MFL_DFITEM X
    ON (A.SEQNF = X.SEQNF)
 INNER JOIN CONSINCO.GE_EMPRESA XX
    ON (A.NROEMPRESA = XX.NROEMPRESA)
 INNER JOIN CONSINCO.GE_PESSOA Z
    ON (Z.SEQPESSOA = A.SEQPESSOA)
   AND A.STATUSDF != 'C'
   AND EXISTS (SELECT *
          FROM CONSINCO.MLF_NOTAFISCAL B
         WHERE A.SEQNFREF = B.SEQNF
           AND B.CODGERALOPER IN (200,255,81,82,83,84,85))
   AND XX.NOMEREDUZIDO IN (#LS1)
   AND A.CODGERALOPER IN (853,255)
   AND A.DTAMOVIMENTO BETWEEN :DT1 AND :DT2)

 ORDER BY 1, 3, 7;
 
