SELECT * FROM (WITH FUROS AS
 (SELECT NROEMPRESA, SERIE, NUM_ANT + 1 AS INICIO_FURO, NUMERO - 1 AS FIM_FURO
    FROM (SELECT NROEMPRESA,
                 SERIE,
                 NUMERO,
                 LAG(NUMERO) OVER(PARTITION BY NROEMPRESA, SERIE ORDER BY NUMERO) AS NUM_ANT
            FROM (SELECT NROEMPRESA, A.SERIENF AS SERIE, NUMERONF AS NUMERO
                    FROM MLF_NOTAFISCAL A
                    JOIN MAX_CODGERALOPER C ON C.CODGERALOPER = A.CODGERALOPER
                   WHERE A.DTAEMISSAO BETWEEN TRUNC(SYSDATE - 30) AND
                         TRUNC(SYSDATE)
                         AND A.MODELONF <> 65
                         AND C.TIPUSO = 'E'
AND A.SERIENF != 'NFS'
                         AND NROEMPRESA IN (#LS1)
                  
                  UNION ALL
                  
                  SELECT NROEMPRESA, SERIEDF, NUMERODF
                    FROM MFL_DOCTOFISCAL
                   WHERE DTAMOVIMENTO BETWEEN TRUNC(SYSDATE - 30) AND
                         TRUNC(SYSDATE)
                         AND NROEMPRESA IN (#LS1)
                         AND MODELODF != '65'))
   WHERE NUMERO - NUM_ANT > 1)
SELECT TO_CHAR(F.NROEMPRESA) LOJA, F.SERIE, TO_CHAR(F.INICIO_FURO + LEVEL - 1) AS NF_FALTANTE
  FROM FUROS F
CONNECT BY LEVEL <= (F.FIM_FURO - F.INICIO_FURO + 1)
           AND PRIOR F.NROEMPRESA = F.NROEMPRESA
           AND PRIOR F.SERIE = F.SERIE
           AND PRIOR F.INICIO_FURO = F.INICIO_FURO
           AND PRIOR SYS_GUID() IS NOT NULL

UNION ALL

SELECT DECODE('#LS1', NULL,'Todas', #LS1) NROEMPRESA, NULL SERIE, 'SEM FUROS' NF_FALTANTE
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM FUROS))
