-- Adicionar em CONSINCO.MLFV_AUXNOTAFISCALINCONS
-- Adicionado por Giuliano para tratar CodOrigem EX -17/01/24
-- PD EXIBE_ORIGEM_MERCADORIA

SELECT DISTINCT (A.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
                A.NUMERONF,
                A.NROEMPRESA,
                0   AS SEQAUXNFITEM,
                'B' AS BLOQAUTOR,
                76  AS CODINCONSISTENC,
                'Cod. Origem da Mercadoria Oriunda EX deve ser 1. PLU: '||B.SEQPRODUTO MENSAGEM

  FROM CONSINCO.MLF_AUXNOTAFISCAL A INNER JOIN CONSINCO.MLF_AUXNFITEM B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                    INNER JOIN CONSINCO.GE_PESSOA G ON G.SEQPESSOA = A.SEQPESSOA
WHERE G.UF = 'EX'
  AND A.CODGERALOPER IN (43,5)
  AND CODORIGEMTRIB != 1
