-- Inserir codicritica 'TRIB. DIVERGENTE DA ORIGEM' em CONSINCO.MAD_CRITICAPEDCONFIG 

-- Inserir select com a crítica  em CONSINCO.MADV_CRITICAPEDVENDA

UNION ALL

SELECT DISTINCT G.NROPEDVENDA, G.NROEMPRESA FROM mad_pedvendaitem G LEFT JOIN MAD_PEDVENDA H ON G.NROPEDVENDA = H.NROPEDVENDA
WHERE G.SEQPRODUTO IN (SELECT DISTINCT A.SEQPRODUTO FROM MAP_PRODUTO A WHERE A.SEQPRODUTO = G.SEQPRODUTO AND A.SEQFAMILIA IN
                      (SELECT DISTINCT B.SEQFAMILIA FROM MAP_FAMDIVISAO B
                      LEFT JOIN CONSINCO.MAP_TRIBUTACAO C ON B.NROTRIBUTACAO = C.NROTRIBUTACAO

WHERE UPPER(TRIBUTACAO) LIKE '%IMP%'      AND CODORIGEMTRIB IN (0,4,5,6,7) AND UPPER(TRIBUTACAO) NOT LIKE '%LIMP%'
   OR UPPER(TRIBUTACAO) LIKE '%IMP.LIMP%' AND CODORIGEMTRIB IN (0,4,5,6,7)))
 AND G.DTAINCLUSAO > SYSDATE - 100
 AND H.SITUACAOPED NOT IN ('C','F')
;
