SELECT DISTINCT A.SEQPRODUTO,  X.SEQPESSOA, TIPFORNECEDOR FORN, UF, B.TRIBANTIGA TRIB_ANTIGA, B.TRIBNOVA TRIB_NOVA, Z.PERALIQUOTA ALIQ_INTERNA, NVL(Y.PERALIQUOTA,0) ALIQ_INTEREST

  FROM NAGT_BASE_PRODST A INNER JOIN MRL_PRODUTOEMPRESA E ON E.SEQPRODUTO = A.SEQPRODUTO
                          INNER JOIN MLF_NOTAFISCAL X     ON X.SEQNF = E.SEQNFULTENTRCUSTO
                          INNER JOIN GE_PESSOA G          ON G.SEQPESSOA = X.SEQPESSOA
                          INNER JOIN MAP_PRODUTO P        ON P.SEQPRODUTO = A.SEQPRODUTO
                          INNER JOIN MAP_FAMDIVISAO F     ON F.SEQFAMILIA = P.SEQFAMILIA
                          INNER JOIN NAGT_DEPARA_TRIBUT_ST B ON B.TRIBNOVA = F.NROTRIBUTACAO
                          INNER JOIN MAF_FORNECEDOR FF    ON FF.SEQFORNECEDOR = X.SEQPESSOA
                          INNER JOIN MAF_FORNECDIVISAO FD ON FD.SEQFORNECEDOR = FF.SEQFORNECEDOR
                           LEFT JOIN MAP_TRIBUTACAOUF Y   ON Y.NROTRIBUTACAO = B.TRIBANTIGA AND Y.NROREGTRIBUTACAO = FD.NROREGTRIBUTACAO AND Y.UFCLIENTEFORNEC = G.UF AND Y.UFEMPRESA = 'SP' AND Y.TIPTRIBUTACAO = DECODE(FF.TIPFORNECEDOR, 'I','EI','D','ED') AND UFCLIENTEFORNEC != UFEMPRESA
                          INNER JOIN MAP_TRIBUTACAOUF Z   ON Z.NROTRIBUTACAO = B.TRIBANTIGA AND Z.NROREGTRIBUTACAO = FD.NROREGTRIBUTACAO AND Z.UFCLIENTEFORNEC = 'SP' AND Z.UFEMPRESA = 'SP' AND Z.TIPTRIBUTACAO = DECODE(FF.TIPFORNECEDOR, 'I','EI','D','ED')
                         
 WHERE E.NROEMPRESA = 1 AND X.SEQPESSOA > 999;

SELECT DISTINCT A.SEQPRODUTO||';'||Z.PERALIQUOTA||';'||NVL(Y.PERALIQUOTA,0) LINHA_ARQ

  FROM NAGT_BASE_PRODST A INNER JOIN MRL_PRODUTOEMPRESA E ON E.SEQPRODUTO = A.SEQPRODUTO
                          INNER JOIN MLF_NOTAFISCAL X     ON X.SEQNF = E.SEQNFULTENTRCUSTO
                          INNER JOIN GE_PESSOA G          ON G.SEQPESSOA = X.SEQPESSOA
                          INNER JOIN MAP_PRODUTO P        ON P.SEQPRODUTO = A.SEQPRODUTO
                          INNER JOIN MAP_FAMDIVISAO F     ON F.SEQFAMILIA = P.SEQFAMILIA
                          INNER JOIN NAGT_DEPARA_TRIBUT_ST B ON B.TRIBNOVA = F.NROTRIBUTACAO
                          INNER JOIN MAF_FORNECEDOR FF    ON FF.SEQFORNECEDOR = X.SEQPESSOA
                          INNER JOIN MAF_FORNECDIVISAO FD ON FD.SEQFORNECEDOR = FF.SEQFORNECEDOR
                           LEFT JOIN MAP_TRIBUTACAOUF Y   ON Y.NROTRIBUTACAO = B.TRIBANTIGA AND Y.NROREGTRIBUTACAO = FD.NROREGTRIBUTACAO AND Y.UFCLIENTEFORNEC = G.UF AND Y.UFEMPRESA = 'SP' AND Y.TIPTRIBUTACAO = DECODE(FF.TIPFORNECEDOR, 'I','EI','D','ED') AND UFCLIENTEFORNEC != UFEMPRESA
                          INNER JOIN MAP_TRIBUTACAOUF Z   ON Z.NROTRIBUTACAO = B.TRIBANTIGA AND Z.NROREGTRIBUTACAO = FD.NROREGTRIBUTACAO AND Z.UFCLIENTEFORNEC = 'SP' AND Z.UFEMPRESA = 'SP' AND Z.TIPTRIBUTACAO = DECODE(FF.TIPFORNECEDOR, 'I','EI','D','ED')
                         
 WHERE E.NROEMPRESA = 1;
