SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       X.NROEMPRESA  LOJA, 'ENTRADA' TIPO_LANCTO, NRONOTA NF, X.SERIE SERIE_NF, 
       G.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0) CNPJ_FORNEC,
       TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') LANCAMENTO, 
       L.M014_DS_PRODUTO DESC_PROD_XML,
       (SELECT SUM(LL.M014_VL_QTDE_COM) FROM TMP_M014_ITEM LL WHERE LL.M000_ID_NF = L.M000_ID_NF AND LL.M014_DS_PRODUTO = L.M014_DS_PRODUTO) QUANTIDADE,
       TO_CHAR((SELECT SUM(LL.M014_VL_TOTAL_BRUTO) FROM TMP_M014_ITEM LL WHERE LL.M000_ID_NF = L.M000_ID_NF AND LL.M014_DS_PRODUTO = L.M014_DS_PRODUTO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_ITEM, 
       TO_CHAR(X.VALOR, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF
       
 FROM OR_NFDESPESA X INNER JOIN OR_NFITENSDESPESA I ON I.SEQNOTA = X.SEQNOTA AND I.NROEMPRESA = X.NROEMPRESA
                     INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
                     INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                     INNER JOIN TMP_M000_NF C ON C.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                     INNER JOIN TMP_M014_ITEM L ON L.M000_ID_NF = C.M000_ID_NF 

 WHERE EXISTS (SELECT 1 FROM MAP_FAMDIVISAO Z WHERE Z.FINALIDADEFAMILIA = 'A' AND Z.SEQFAMILIA = P.SEQFAMILIA)
   AND SITUACAO = 'I'
   AND X.NROEMPRESA IN (#LS1)
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   
   GROUP BY X.NROEMPRESA, NRONOTA, X.SERIE,  G.SEQPESSOA||' - '||G.NOMERAZAO, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0), TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY'),
            X.VALOR, M014_DS_PRODUTO, L.M000_ID_NF
      
   ORDER BY 1,2;
  
