-- Ticket 594535

SELECT X.NROEMPRESA  LOJA, 'ENTRADA' TIPO_LANCTO, NRONOTA NF, X.SERIE SERIE_NF, 
       G.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0) CNPJ_FORNEC,
       TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') LANCAMENTO, 
       I.SEQPRODUTO COD_PROD_C5, DESCCOMPLETA DESC_PROD_C5, L.M014_DS_PRODUTO DESC_PROD_XML,
       SUM(L.M014_VL_QTDE_COM) QUANTIDADE,
       TO_CHAR(SUM(L.M014_VL_TOTAL_BRUTO), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_ITEM, 
       TO_CHAR(X.VALOR, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF
       
 FROM OR_NFDESPESA X INNER JOIN OR_NFITENSDESPESA I ON I.SEQNOTA = X.SEQNOTA AND I.NROEMPRESA = X.NROEMPRESA
                      INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
                      INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                       LEFT JOIN TMP_M000_NF C ON C.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                       LEFT JOIN TMP_M014_ITEM L ON L.M000_ID_NF = C.M000_ID_NF

 WHERE EXISTS (SELECT 1 FROM MAP_FAMDIVISAO Z WHERE Z.FINALIDADEFAMILIA = 'A' AND Z.SEQFAMILIA = P.SEQFAMILIA)
   AND SITUACAO = 'I'
   AND X.NROEMPRESA IN (#LS1)
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   
   GROUP BY X.NROEMPRESA, NRONOTA, SERIE, DTAENTRADA, I.SEQPRODUTO, DESCCOMPLETA, VALOR, G.SEQPESSOA||' - '||G.NOMERAZAO, LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0), M014_DS_PRODUTO
   
   ORDER BY 1,2;
