SELECT DISTINCT X.NROEMPRESA, X.SEQPRODUTO PLU, DESCCOMPLETA PRODUTO, CODACESSO EAN, D.MARCA,
       Y.ESTQLOJA, 
         Y.ESTQDEPOSITO,  
           Y.ESTQTROCA, 
             Y.ESTQOUTRO,
       TO_CHAR(Y.DTAULTENTRADA, 'DD/MM/YYYY') AS DTAULTENTRADA,
         TO_CHAR(Y.DTAULTCOMPRA,  'DD/MM/YYYY') AS DTAULTCOMPRA,
           TO_CHAR(A.DTAHORINCLUSAO,'DD/MM/YYYY') AS DTAHORINCLUSAO,
       DECODE(X.STATUSCOMPRA,'A','ATIVO','I','INATIVO','S','SUSPENSO') STATUS_COMPRA,
       DECODE(X.STATUSVENDA, 'A','ATIVO','I','INATIVO','S','SUSPENSO') STATUS_VENDA,
       F.CATEGORIAN1 CATEGORIANVL01,
         F.CATEGORIAN2 CATEGORIANVL02,
           F.CATEGORIAN3 CATEGORIANVL03,
             F.CATEGORIAN4 CATEGORIANVL04,
                F.CATEGORIAN5 CATEGORIANVL05,
       G.ALTURA, 
         G.LARGURA, 
           G.PROFUNDIDADE,
             GC.PADRAOEMBCOMPRA,
       Y.CMULTVLRNF CUSTO, CASE WHEN NVL(PS.PRECOGERPROMOC,0) = 0 THEN NVL(PS.PRECOGERNORMAL,0) ELSE PS.PRECOGERPROMOC END PRECO_VDA


 FROM CONSINCO.DIM_PRODUTOEMPRESA X INNER JOIN CONSINCO.MAP_PRODUTO    A ON A.SEQPRODUTO = X.SEQPRODUTO
                                     LEFT JOIN CONSINCO.MAP_PRODCODIGO B ON B.SEQPRODUTO = A.SEQPRODUTO AND B.TIPCODIGO = 'E'
                                    INNER JOIN CONSINCO.MAP_FAMILIA    C ON C.SEQFAMILIA = A.SEQFAMILIA 
                                     LEFT JOIN CONSINCO.MAP_MARCA      D ON D.SEQMARCA   = C.SEQMARCA
                                     LEFT JOIN CONSINCO.MRL_PRODUTOEMPRESA Y ON Y.NROEMPRESA  = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO 
                                     LEFT JOIN CONSINCO.DIM_CATEGORIA      F ON F.SEQFAMILIA  = C.SEQFAMILIA
                                     LEFT JOIN CONSINCO.MAP_FAMEMBALAGEM   G ON A.SEQFAMILIA  = G.SEQFAMILIA AND G.QTDEMBALAGEM = B.QTDEMBALAGEM
                                     LEFT JOIN CONSINCO.MAP_FAMDIVISAO    GC ON GC.SEQFAMILIA = A.SEQFAMILIA
                                     LEFT JOIN CONSINCO.MRL_PRODEMPSEG    PS ON PS.NROEMPRESA = X.NROEMPRESA AND PS.SEQPRODUTO = X.SEQPRODUTO AND PS.QTDEMBALAGEM = 1
  WHERE 1=1
    AND X.NROEMPRESA  IN  (#LS1)
    AND F.CATEGORIAN3 IN  (#LS2)
            
