ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.SEQPRODUTO PLU, DESCCOMPLETA PRODUTO, CODACESSO EAN, D.MARCA,
       SUM(Y.ESTQLOJA) ESTQLOJA, 
         SUM(Y.ESTQDEPOSITO) ESTQDEPOSITO,  
           SUM(Y.ESTQTROCA) ESTQTROCA, 
             SUM(Y.ESTQOUTRO) ESTQOUTRO,
       TO_CHAR(MAX(Y.DTAULTENTRADA), 'DD/MM/YYYY') AS DTAULTENTRADA,
         TO_CHAR(MAX(Y.DTAULTCOMPRA),  'DD/MM/YYYY') AS DTAULTCOMPRA,
           TO_CHAR(MAX(A.DTAHORINCLUSAO),'DD/MM/YYYY') AS DTAHORINCLUSAO,
       DECODE(MIN(X.STATUSCOMPRA),'A','ATIVO','I','INATIVO','S','SUSPENSO') STATUS_COMPRA,
       DECODE(MIN(X.STATUSVENDA), 'A','ATIVO','I','INATIVO','S','SUSPENSO') STATUS_VENDA,
       F.CATEGORIAN1 CATEGORIANVL01,
         F.CATEGORIAN2 CATEGORIANVL02,
           F.CATEGORIAN3 CATEGORIANVL03,
             F.CATEGORIAN4 CATEGORIANVL04,
                F.CATEGORIAN5 CATEGORIANVL05,
       G.ALTURA, 
         G.LARGURA, 
           G.PROFUNDIDADE,
             GC.PADRAOEMBCOMPRA,
       AVG(Y.CMULTVLRNF) CUSTO, AVG(CASE WHEN NVL(PS.PRECOGERPROMOC,0) = 0 THEN NVL(PS.PRECOGERNORMAL,0) ELSE PS.PRECOGERPROMOC END) PRECO_VDA,
       SUM(QTDOPERACAO) QTD_VDA_SEMESTRE, SUM(VLROPERACAO) VLR_VDA_SEMESTRE, SUM(QTDPROMOC) QTD_VDA_PROMOC, SUM(VLRPROMOC) VLR_VDA_PROMOC


 FROM CONSINCO.DIM_PRODUTOEMPRESA X INNER JOIN CONSINCO.MAP_PRODUTO    A ON A.SEQPRODUTO = X.SEQPRODUTO
                                     LEFT JOIN CONSINCO.MAP_PRODCODIGO B ON B.SEQPRODUTO = A.SEQPRODUTO AND B.TIPCODIGO = 'E'
                                    INNER JOIN CONSINCO.MAP_FAMILIA    C ON C.SEQFAMILIA = A.SEQFAMILIA 
                                     LEFT JOIN CONSINCO.MAP_MARCA      D ON D.SEQMARCA   = C.SEQMARCA
                                     LEFT JOIN CONSINCO.MRL_PRODUTOEMPRESA Y ON Y.NROEMPRESA  = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO 
                                     LEFT JOIN CONSINCO.DIM_CATEGORIA      F ON F.SEQFAMILIA  = C.SEQFAMILIA
                                     LEFT JOIN CONSINCO.MAP_FAMEMBALAGEM   G ON A.SEQFAMILIA  = G.SEQFAMILIA AND G.QTDEMBALAGEM = B.QTDEMBALAGEM
                                     LEFT JOIN CONSINCO.MAP_FAMDIVISAO    GC ON GC.SEQFAMILIA = A.SEQFAMILIA
                                     LEFT JOIN CONSINCO.MRL_PRODEMPSEG    PS ON PS.NROEMPRESA = X.NROEMPRESA AND PS.SEQPRODUTO = X.SEQPRODUTO AND PS.QTDEMBALAGEM = 1
                                     LEFT JOIN FATOG_VENDADIA@CONSINCODW  VD ON VD.SEQPRODUTO = X.SEQPRODUTO AND VD.NROEMPRESA = X.NROEMPRESA AND VD.DTAOPERACAO > SYSDATE - 150
  WHERE 1=1
    AND F.CATEGORIAN3 IN  (#LS2)

GROUP BY  X.SEQPRODUTO, DESCCOMPLETA, CODACESSO, D.MARCA,
       F.CATEGORIAN1 ,
         F.CATEGORIAN2 ,
           F.CATEGORIAN3 ,
             F.CATEGORIAN4 ,
                F.CATEGORIAN5 ,
       G.ALTURA, 
         G.LARGURA, 
           G.PROFUNDIDADE,
             GC.PADRAOEMBCOMPRA
            
ORDER BY 1,3

