SELECT * FROM (
SELECT DISTINCT E.NROEMPRESA EMP, E.SEQPRODUTO PLU, QP.PRODUTO DESCRICAO, NVL(SUM(QTDOPERACAO),0) QTD_VENDA, NVL(E.QTDESTOQUE,0) QTD_ESTOQUE, QC.COMPRADOR_CADASTRO COMPRADOR,
       CASE WHEN E.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA@CONSINCODW Z WHERE Z.SEQPRODUTO = E.SEQPRODUTO AND Z.STATUSCOMPRA = 'A') THEN 'ATIVO' 
            WHEN E.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA@CONSINCODW Z WHERE Z.SEQPRODUTO = E.SEQPRODUTO AND Z.STATUSCOMPRA = 'S') THEN 'SUSPENSO'
            ELSE 'INATIVO' END STATUS_COMPRA,
       CASE WHEN E.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA@CONSINCODW Z WHERE Z.SEQPRODUTO = E.SEQPRODUTO AND Z.STATUSVENDA = 'A') THEN 'ATIVO' 
            WHEN E.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA@CONSINCODW Z WHERE Z.SEQPRODUTO = E.SEQPRODUTO AND Z.STATUSVENDA = 'S') THEN 'SUSPENSO'
            ELSE 'INATIVO' END STATUS_VENDA,
       Y.MARCA, QP.FORNECEDOR_PRINCIPAL, C.CATEGORIAN3

FROM FATO_ESTOQUE@CONSINCODW E
  LEFT JOIN FATOG_VENDADIA@CONSINCODW FV ON E.SEQPRODUTO  = FV.SEQPRODUTO AND E.NROEMPRESA = FV.NROEMPRESA 
    AND FV.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
    AND FV.DTAOPERACAO BETWEEN :DT1 -30 AND :DT1
  LEFT JOIN DIM_PRODUTO@CONSINCODW Y    ON Y.SEQPRODUTO = E.SEQPRODUTO
  LEFT JOIN DIM_CATEGORIA@CONSINCODW C  ON C.SEQFAMILIA  = Y.SEQFAMILIA
  LEFT JOIN QLV_CATEGORIA@CONSINCODW QC ON QC.SEQFAMILIA = C.SEQFAMILIA
  LEFT JOIN QLV_PRODUTO@CONSINCODW QP   ON QP.SEQPRODUTO = E.SEQPRODUTO
   
WHERE E.DTAESTOQUE = TRUNC(SYSDATE -1)
  AND QP.SEQFORNECEDOR_PRINCIPAL IN (#LS1)
  AND C.CATEGORIAN3 IN (#LS2)
  
GROUP BY E.NROEMPRESA, E.SEQPRODUTO, QP.PRODUTO, COMPRADOR_CADASTRO, QTDESTOQUE, Y.MARCA, FORNECEDOR_PRINCIPAL,CATEGORIAN3
ORDER BY 2,1
) WHERE STATUS_COMPRA LIKE (DECODE ('#LS3','ATIVO','%ATIVO%', 'INATIVO','%INATIVO%','SUSPENSO','%SUSPENSO%','%%'))
