ALTER SESSION SET current_schema = CONSINCO;

SELECT C.SEQPRODUTO PLU, C.DESCCOMPLETA DESCRICAO, D.CODACESSO EAN,
       A.SEQMARCA NUMERO_MARCA, MARCA, DECODE(TIPOMARCA, 'N','Normal','p','Primeiro Preço','M','Marca Própria','R','Regional') Tipo_Marca, DECODE(STATUS, 'A','Ativo','I','Inativo') STATUS 
  FROM CONSINCO.MAP_MARCA A LEFT JOIN MAP_FAMILIA B ON A.SEQMARCA = B.SEQMARCA
                            LEFT JOIN MAP_PRODUTO C ON B.SEQFAMILIA = C.SEQFAMILIA
                            LEFT JOIN MAP_PRODCODIGO D ON D.SEQPRODUTO = C.SEQPRODUTO AND D.TIPCODIGO = 'E'
  ORDER BY 2;
