SELECT  * FROM (

SELECT C.SEQPRODUTO PLU, C.DESCCOMPLETA DESCRICAO, D.CODACESSO EAN,
       A.SEQMARCA NUMERO_MARCA, MARCA, DECODE(TIPOMARCA, 'N','Normal','p','Primeiro Preço','M','Marca Própria','R','Regional') Tipo_Marca, DECODE(STATUS, 'A','Ativo','I','Inativo') STATUS 
  FROM CONSINCO.MAP_MARCA A LEFT JOIN CONSINCO.MAP_FAMILIA B ON A.SEQMARCA = B.SEQMARCA
                            LEFT JOIN CONSINCO.MAP_PRODUTO C ON B.SEQFAMILIA = C.SEQFAMILIA
                            LEFT JOIN CONSINCO.MAP_PRODCODIGO D ON D.SEQPRODUTO = C.SEQPRODUTO AND D.TIPCODIGO = 'E')
                            
          WHERE PLU IS NOT NULL
  ORDER BY 2;
