SELECT  fBuscaEANProdutomaior(A.seqproduto) EAN, A.PRODUTO, A.MARCA,
        CASE WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSCOMPRA = 'A') THEN 'ATIVO' 
            WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSCOMPRA = 'S') THEN 'SUSPENSO'
            ELSE 'INATIVO' END STATUS_COMPRA,
       CASE WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSVENDA = 'A') THEN 'ATIVO' 
            WHEN A.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = A.SEQPRODUTO AND Z.STATUSVENDA = 'S') THEN 'SUSPENSO'
            ELSE 'INATIVO' END STATUS_VENDA,
        QC.COMPRADOR_CADASTRO COMPRADOR,
        QC.categoria_nivel_1, QC.categoria_nivel_2, QC.categoria_nivel_3, QC.categoria_nivel_4, QC.categoria_nivel_5

FROM QLV_PRODUTO A LEFT JOIN QLV_CATEGORIA QC ON A.SEQFAMILIA = QC.SEQFAMILIA

ORDER BY 2 ASC
