SELECT X.NROEMPRESA LOJA, X.SEQPRODUTO PLU, P.DESCCOMPLETA, MARCA,
       LISTAGG(CODACESSO, ', ') WITHIN GROUP (ORDER BY X.SEQPRODUTO) EAN,
       DECODE(STATUSCOMPRA, 'A', 'Ativo', 'S', 'Suspenso', 'I', 'Inativo') STATUS_COMPRA,
       CATEGORIAN1, CATEGORIAN2, CATEGORIAN3, X.ESTQLOJA, 
       TO_CHAR(X.DTAULTVENDA, 'DD/MM/YYYY') DTA_ULTVENDA, TO_CHAR(X.DTAULTENTRADA, 'DD/MM/YYYY') DTA_ULTENTRADA

  FROM MRL_PRODUTOEMPRESA X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO
                            INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA
                             LEFT JOIN MAP_PRODCODIGO PC ON PC.SEQPRODUTO = X.SEQPRODUTO AND PC.TIPCODIGO = 'E' AND INDUTILVENDA = 'S'
                            INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                            INNER JOIN MAP_MARCA M ON M.SEQMARCA = F.SEQMARCA
                             
 WHERE NROEMPRESA = 56
   AND STATUSCOMPRA = 'A'

GROUP BY X.NROEMPRESA, X.SEQPRODUTO, P.DESCCOMPLETA, DECODE(STATUSCOMPRA, 'A', 'Ativo', 'S', 'Suspenso', 'I', 'Inativo'),
      CATEGORIAN1, CATEGORIAN2, CATEGORIAN3, X.DTAULTVENDA, X.DTAULTENTRADA, X.ESTQLOJA, MARCA
      
ORDER BY 3
