ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT 'Liberado por Senha' SITUACAO, X.NROEMPRESA, X.NUMERONF, XI.SEQPRODUTO, DESCCOMPLETA DESC_PRODUTO, 
       TO_NUMBER(PR.QTDEMBALAGEM) EMB_PED,PI.QTDRECEBIDA QTD_PED,
       TO_NUMBER(XI.QTDEMBALAGEM) EMB_NF, XI.QUANTIDADE  QTD_NF,
       ROUND(((XI.QUANTIDADE - PI.QTDRECEBIDA) / QTDRECEBIDA) * 100,2) "PERCENTUAL_DIF_%",
       PI.VLRPRODUTO CUSTO_ITEM, COMPRADOR, L.DESCRICAO CRITICA, L.USUAUTORIZOU USUARIO_RESP
       
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                        INNER JOIN MLF_AUXNFINCONSISTENCIA L ON L.SEQAUXNOTAFISCAL = XI.SEQAUXNOTAFISCAL AND L.SEQAUXNFITEM = XI.SEQITEMNF  AND L.AUTORIZADA = 'S'
                        LEFT  JOIN MSU_PSITEMRECEBIDO PI     ON PI.NUMERONF = X.NUMERONF                 AND PI.SEQPRODUTO  = XI.SEQPRODUTO AND PI.NROEMPRESA = X.NROEMPRESA AND PI.SEQPESSOA = X.SEQPESSOA
                        INNER JOIN MSU_PSITEMRECEBER  PR     ON PR.NROPEDIDOSUPRIM = PI.NROPEDIDOSUPRIM  AND PR.SEQPRODUTO  = PI.SEQPRODUTO
                        INNER JOIN MSU_PEDIDOSUPRIM   PS     ON PS.NROPEDIDOSUPRIM = PI.NROPEDIDOSUPRIM
                        INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = PS.SEQCOMPRADOR
                        
 WHERE X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
   AND L.CODINCONSIST = 75
   
   UNION ALL
   
SELECT DISTINCT 'Pedido Adicionado' SITUACAO, X.NROEMPRESA, X.NUMERONF, XI.SEQPRODUTO, DESCCOMPLETA DESC_PRODUTO, 
       TO_NUMBER(PR.QTDEMBALAGEM) EMB_PED,PI.QTDRECEBIDA QTD_PED,
       TO_NUMBER(XI.QTDEMBALAGEM) EMB_NF, XI.QUANTIDADE  QTD_NF,
       ROUND(((XI.QUANTIDADE - PI.QTDRECEBIDA) / QTDRECEBIDA) * 100,2) "PERCENTUAL_DIF_%",
       PI.VLRPRODUTO CUSTO_ITEM, COMPRADOR, L.DESCRICAO CRITICA, PS.USUINCLUSAO
       
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                        INNER JOIN NAGT_INCONSISTRECEBTO_LOG L ON L.SEQNF = XI.SEQNF AND L.SEQAUXNFITEM = XI.SEQITEMNF
                        LEFT  JOIN MSU_PSITEMRECEBIDO PI     ON PI.NUMERONF = X.NUMERONF                 AND PI.SEQPRODUTO  = XI.SEQPRODUTO AND PI.NROEMPRESA = X.NROEMPRESA AND PI.SEQPESSOA = X.SEQPESSOA
                        INNER JOIN MSU_PSITEMRECEBER  PR     ON PR.NROPEDIDOSUPRIM = PI.NROPEDIDOSUPRIM  AND PR.SEQPRODUTO  = PI.SEQPRODUTO
                        INNER JOIN MSU_PEDIDOSUPRIM   PS     ON PS.NROPEDIDOSUPRIM = PI.NROPEDIDOSUPRIM
                        INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = PS.SEQCOMPRADOR
                        
 WHERE X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
   AND L.CODINCONSIST = 75
   AND NOT EXISTS (SELECT 1 FROM MLF_AUXNFINCONSISTENCIA L WHERE L.SEQAUXNOTAFISCAL = XI.SEQAUXNOTAFISCAL AND L.SEQAUXNFITEM = XI.SEQITEMNF  AND L.AUTORIZADA = 'S')
   AND X.STATUSNF != 'C'
   AND PS.DTAHORINCLUSAO > X.DTARECEBIMENTO
   
   ORDER BY 2,3,4
