SELECT DISTINCT X.NROEMPRESA,
                X.NUMERONF,
                X.SEQPESSOA || ' - ' || G.NOMERAZAO FORNECEDOR,
                XI.SEQPRODUTO,
                DESCCOMPLETA DESCRICAO,
                TT.M014_DS_UNID_COM EMB_NF,
                XI.EMBALAGEM EMB_LANCTO,
                FB.EMBALAGEM EMB_PED, (SELECT COMPRADOR FROM CONSINCO.MAX_COMPRADOR CO WHERE CO.SEQCOMPRADOR = P.SEQCOMPRADOR) COMPRADOR,
                P.USUINCLUSAO USU_FAT, (SELECT NOME FROM CONSINCO.GE_USUARIO GE WHERE GE.CODUSUARIO = P.USUINCLUSAO) NOME_USU_FAT
                
FROM CONSINCO.MLF_NOTAFISCAL X INNER JOIN CONSINCO.MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
                               INNER JOIN CONSINCO.GE_PESSOA  G  ON G.SEQPESSOA = X.SEQPESSOA
                               INNER JOIN CONSINCO.MAP_PRODUTO A ON A.SEQPRODUTO = XI.SEQPRODUTO
                                LEFT JOIN CONSINCO.TMP_M000_NF T  ON  T.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                                LEFT JOIN CONSINCO.TMP_M014_ITEM TT ON TT.M000_ID_NF = T.M000_ID_NF AND TT.M014_NR_ITEM = XI.SEQITEMNF
                               INNER JOIN CONSINCO.MSU_PSITEMRECEBIDO F ON F.NUMERONF = X.NUMERONF AND F.NROEMPRESA = X.NROEMPRESA AND F.SEQPRODUTO = XI.SEQPRODUTO 
                               INNER JOIN CONSINCO.MSU_PSITEMRECEBER FI ON FI.NROPEDIDOSUPRIM = F.NROPEDIDOSUPRIM AND FI.NROEMPRESA = F.NROEMPRESA AND FI.SEQPRODUTO = F.SEQPRODUTO
                                LEFT JOIN CONSINCO.MAP_FAMEMBALAGEM FB ON FB.QTDEMBALAGEM = FI.QTDEMBALAGEM AND FB.SEQFAMILIA = A.SEQFAMILIA 
                                LEFT JOIN CONSINCO.MSU_PEDIDOSUPRIM P ON P.NROPEDIDOSUPRIM = FI.NROPEDIDOSUPRIM
                                
WHERE 1=1
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.SEQPESSOA  > 999
   AND X.NROEMPRESA IN (#LS1)

   ORDER BY X.NROEMPRESA,
            X.NUMERONF
            
