SELECT DISTINCT X.NROEMPRESA, 
       TO_CHAR(:DT1, 'DD/MM/YYYY')|| ' Até ' ||TO_CHAR(:DT2,'DD/MM/YYYY') PERIODO, 
       G.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, X.CODGERALOPER CGO,
       COUNT(DISTINCT CASE
        WHEN NVL(NVL(T.M000_DS_PEDIDO, I.M014_NR_PED_COMP), 0)     LIKE '%' || PED.NROPEDIDOSUPRIM || '%' THEN P.SEQPRODUTO
       END) AS QTD_ITENS_PED_OK_XML,
       COUNT(DISTINCT CASE
        WHEN NVL(NVL(T.M000_DS_PEDIDO, I.M014_NR_PED_COMP), 0) NOT LIKE '%' || PED.NROPEDIDOSUPRIM || '%' THEN P.SEQPRODUTO
       END) AS QTD_ITENS_PED_INCORRETO_XML,
       CASE WHEN X.CODGERALOPER IN (1,2,101,121,128,900) THEN 'Sim'
            WHEN X.CODGERALOPER IN (14,59,67,107,116,117,126,127,139,206,652,816) THEN 'Não' END PRECISA_PED
       
  FROM CONSINCO.MLF_NOTAFISCAL X LEFT JOIN CONSINCO.TMP_M000_NF   T ON T.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                       INNER JOIN CONSINCO.TMP_M014_ITEM I ON I.M000_ID_NF = T.M000_ID_NF
                        LEFT JOIN CONSINCO.GE_PESSOA     G ON G.SEQPESSOA = X.SEQPESSOA
                       INNER JOIN CONSINCO.MLF_NFITEM   XI ON XI.SEQNF = X.SEQNF
                        LEFT JOIN CONSINCO.MSU_PSITEMRECEBIDO P ON P.NUMERONF = XI.NUMERONF AND P.NROEMPRESA = XI.NROEMPRESA AND P.SEQPRODUTO = XI.SEQPRODUTO
                        LEFT JOIN CONSINCO.MSU_PEDIDOSUPRIM PED ON PED.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM AND PED.NROEMPRESA = P.NROEMPRESA
                        LEFT JOIN CONSINCO.MAX_COMPRADOR M ON M.SEQCOMPRADOR = PED.SEQCOMPRADOR
                        
 WHERE X.DTAEMISSAO BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
   AND X.SEQPESSOA > 999
   AND X.STATUSNF != 'C'
   
   GROUP BY X.NROEMPRESA, G.SEQPESSOA||' - '||G.NOMERAZAO, X.CODGERALOPER
   
   ORDER BY 3,1
   
