ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT X.NROEMPRESA, X.NUMERONF, G.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, 
       TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTA_EMISSAO, PED.NROPEDIDOSUPRIM NRO_PEDIDO, PED.VLRTOTPEDIDO VLR_PEDIDO, 
       CASE WHEN PED.NROPEDIDOSUPRIM IS NULL THEN NULL ELSE 'FATURADO' END SITUACAO_PED, COMPRADOR, PED.USUINCLUSAO,
       CASE WHEN NVL(NVL(T.M000_DS_PEDIDO, I.M014_NR_PED_COMP),0) = '0' 
        THEN 'SEM PED XML' ELSE 'OK' END PED_XML,
       CASE WHEN PED.NROPEDIDOSUPRIM IS NULL THEN 'SEM PED C5' ELSE 'OK' END PED_C5
       
  FROM MLF_NOTAFISCAL X LEFT JOIN CONSINCO.TMP_M000_NF   T ON T.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                       INNER JOIN CONSINCO.TMP_M014_ITEM I ON I.M000_ID_NF = T.M000_ID_NF
                        LEFT JOIN CONSINCO.GE_PESSOA     G ON G.SEQPESSOA = X.SEQPESSOA
                       INNER JOIN CONSINCO.MLF_NFITEM   XI ON XI.SEQNF = X.SEQNF
                        LEFT JOIN CONSINCO.MSU_PSITEMRECEBIDO P ON P.NUMERONF = XI.NUMERONF AND P.NROEMPRESA = XI.NROEMPRESA AND P.SEQPRODUTO = XI.SEQPRODUTO
                        LEFT JOIN CONSINCO.MSU_PEDIDOSUPRIM PED ON PED.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM AND PED.NROEMPRESA = P.NROEMPRESA
                        LEFT JOIN CONSINCO.MAX_COMPRADOR M ON M.SEQCOMPRADOR = PED.SEQCOMPRADOR
                        
 WHERE X.DTAEMISSAO BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
   AND X.SEQPESSOA > 999
   AND X.STATUSNF != 'C'
   
