ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT AX.NROEMPRESA LOJA, AX.NUMERONF, AI.SEQPRODUTO PLU, X.DESCRICAO, AX.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR,
       TO_CHAR(AX.DTAEMISSAO, 'DD/MM/YYYY') DTA_EMISSAO, TO_CHAR(AX.DTAENTRADA, 'DD/MM/YYYY') DTA_ENTRADA       

FROM MLF_AUXNFINCONSISTENCIA X INNER JOIN MLF_AUXNOTAFISCAL AX ON AX.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
                                LEFT JOIN MLF_AUXNFITEM     AI ON AI.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL AND AI.SEQAUXNFITEM = X.SEQAUXNFITEM
                               INNER JOIN GE_PESSOA         G  ON G.SEQPESSOA = AX.SEQPESSOA 
 WHERE NUMERONF != 0
   AND X.AUTORIZADA = 'N'
   AND   ( X.CODINCONSIST IN (3,4,7,75,166,167) 
       AND X.TIPOINCONSIST = 'P'
       AND X.SEQAUXNFITEM <> 0
        OR X.CODINCONSIST IN (3)
       AND X.TIPOINCONSIST = 'V'
       AND X.SEQAUXNFITEM = 0
        OR X.CODINCONSIST IN (139)
       AND X.TIPOINCONSIST = 'N'
       AND X.SEQAUXNFITEM <> 0 )
   AND AX.SEQPESSOA = :NR1
       ORDER BY 1,2,3
