
 SELECT DISTINCT X.NROEMPRESA, X.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, C.COMPRADOR, X.NUMERONF,
        SUM((TO_NUMBER(REPLACE(REGEXP_SUBSTR(B.DESCRICAO,'[0-9]+(\.[0-9]+)?'),'.',',')) * QUANTIDADE) - 
            (TO_NUMBER(REPLACE(REGEXP_SUBSTR(SUBSTR(B.DESCRICAO,100),'[0-9]+(\.[0-9]+)?'),'.',',')) * QUANTIDADE)) VLR_DIF_PED_NF,
        B.USUAUTORIZOU USU_AUTORIZACAO, TO_CHAR(B.DTAAUTORIZOU, 'DD/MM/YYYY HH24:MI') DTA_AUTORIZACAO, X.JUSTIFACEITEPEDIDO
       
  FROM CONSINCO.MLF_NOTAFISCAL X INNER JOIN CONSINCO.MLF_NFITEM XI    ON XI.SEQNF = X.SEQNF
                                 INNER JOIN CONSINCO.MLF_AUXNFINCONSISTENCIA B ON B.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL AND B.SEQAUXNFITEM = XI.SEQITEMNF AND B.AUTORIZADA = 'S'
                                 INNER JOIN CONSINCO.GE_PESSOA G      ON G.SEQPESSOA = X.SEQPESSOA
                                 INNER JOIN CONSINCO.MAP_PRODUTO M    ON M.SEQPRODUTO = XI.SEQPRODUTO
                                 INNER JOIN CONSINCO.MAP_FAMDIVISAO F ON F.SEQFAMILIA = M.SEQFAMILIA
                                 INNER JOIN CONSINCO.MAX_COMPRADOR C  ON C.SEQCOMPRADOR = F.SEQCOMPRADOR
                                                                  
 WHERE 1=1
   AND X.STATUSNF     != 'C'
   AND B.TIPOINCONSIST = 'P'
   AND B.CODINCONSIST  =  4
   AND B.AUTORIZADA    = 'S'
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1) 
   
   GROUP BY X.NROEMPRESA, X.NUMERONF, B.USUAUTORIZOU, TO_CHAR(B.DTAAUTORIZOU, 'DD/MM/YYYY HH24:MI'), X.SEQPESSOA, G.NOMERAZAO, C.COMPRADOR, JUSTIFACEITEPEDIDO
   

