SELECT COUNT(DISTINCT NUMERONF) QTD_NFS,
       ROUND(COUNT(DISTINCT NUMERONF) / (SELECT COUNT (NROEMPRESA) FROM CONSINCO.MAX_EMPRESA)) MEDIA_NF_LJ,
       COUNT(DISTINCT SEQPRODUTO) QTD_PROD,
       ROUND(COUNT(DISTINCT SEQPRODUTO) / (SELECT COUNT (NROEMPRESA) FROM CONSINCO.MAX_EMPRESA)) MEDIA_PROD_LJ,
       TO_CHAR(DATALOG, 'MM') MES
  FROM CONSINCO.NAGT_INCONSISTRECEBTO_LOG X  
 WHERE CODINCONSIST IN (75,3) 
   AND EXISTS (SELECT 1 FROM MAP_PRODUTO A INNER JOIN CONSINCO.MAP_FAMILIA B ON B.SEQFAMILIA = A.SEQFAMILIA
                       WHERE A.SEQPRODUTO = X.SEQPRODUTO
                         AND B.PESAVEL = 'S') -- Pesaveis
                         
  AND DATALOG >= DATE '2024-01-01'
  
GROUP BY  TO_CHAR(DATALOG, 'MM')

ORDER BY 5
