SELECT DISTINCT X.NROEMPRESA, X.NUMERONF, G.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, X.CODGERALOPER CGO,
       TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTA_EMISSAO, PED.NROPEDIDOSUPRIM NRO_PEDIDO, PED.VLRTOTPEDIDO VLR_PEDIDO, 
       CASE WHEN PED.NROPEDIDOSUPRIM IS NULL THEN NULL ELSE 'FATURADO' END SITUACAO_PED, COMPRADOR, PED.USUINCLUSAO,
       CASE WHEN NVL(NVL(T.M000_DS_PEDIDO, I.M014_NR_PED_COMP),0) = '0' 
        THEN 'SEM PED XML' ELSE 'OK' END PED_XML,
       CASE WHEN PED.NROPEDIDOSUPRIM IS NULL THEN 'SEM PED C5' ELSE 'OK' END PED_C5,
       CASE WHEN X.CODGERALOPER IN (1,2,101,121,128,900) THEN 'Sim'
            WHEN X.CODGERALOPER IN (14,59,67,107,116,117,126,127,139,206,652,816) THEN 'Não' END PRECISA_PED
       
  FROM CONSINCO.MLF_NOTAFISCAL X LEFT JOIN CONSINCO.TMP_M000_NF   T ON T.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                       INNER JOIN CONSINCO.TMP_M014_ITEM I ON I.M000_ID_NF = T.M000_ID_NF
                        LEFT JOIN CONSINCO.GE_PESSOA     G ON G.SEQPESSOA = X.SEQPESSOA
                       INNER JOIN CONSINCO.MLF_NFITEM   XI ON XI.SEQNF = X.SEQNF
                        LEFT JOIN CONSINCO.MSU_PSITEMRECEBIDO P ON P.NUMERONF = XI.NUMERONF AND P.NROEMPRESA = XI.NROEMPRESA AND P.SEQPRODUTO = XI.SEQPRODUTO
                        LEFT JOIN CONSINCO.MSU_PEDIDOSUPRIM PED ON PED.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM AND PED.NROEMPRESA = P.NROEMPRESA
                        LEFT JOIN CONSINCO.MAX_COMPRADOR M ON M.SEQCOMPRADOR = PED.SEQCOMPRADOR
                        
 WHERE X.DTAEMISSAO BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
   AND X.SEQPESSOA > 999
   AND X.STATUSNF != 'C'
   
UNION ALL

SELECT DISTINCT X.NROEMPRESA, X.NUMERONF, G.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, X.CODGERALOPER CGO,
       TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTA_EMISSAO, PED.NROPEDIDOSUPRIM NRO_PEDIDO, PED.VLRTOTPEDIDO VLR_PEDIDO, 
       CASE WHEN PED.NROPEDIDOSUPRIM IS NULL THEN NULL ELSE 'FATURADO' END SITUACAO_PED, COMPRADOR, PED.USUINCLUSAO,
       CASE WHEN NVL(NVL(T.M000_DS_PEDIDO, I.M014_NR_PED_COMP),0) = '0' 
        THEN 'SEM PED XML' ELSE 'OK' END PED_XML,
       CASE WHEN PED.NROPEDIDOSUPRIM IS NULL THEN 'SEM PED C5' ELSE 'OK' END PED_C5,
       CASE WHEN X.CODGERALOPER IN (1,2,101,121,128,900) THEN 'Sim'
            WHEN X.CODGERALOPER IN (14,59,67,107,116,117,126,127,139,206,652,816) THEN 'Não' END PRECISA_PED
       
  FROM CONSINCO.MLF_AUXNOTAFISCAL X LEFT JOIN CONSINCO.TMP_M000_NF   T ON T.M000_NR_CHAVE_ACESSO = X.NFECHAVEACESSO
                       INNER JOIN CONSINCO.TMP_M014_ITEM I ON I.M000_ID_NF = T.M000_ID_NF
                        LEFT JOIN CONSINCO.GE_PESSOA     G ON G.SEQPESSOA = X.SEQPESSOA
                       INNER JOIN CONSINCO.MLF_AUXNFITEM   XI ON XI.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
                        LEFT JOIN CONSINCO.MSU_PSITEMRECEBIDO P ON P.NUMERONF = X.NUMERONF AND P.NROEMPRESA = X.NROEMPRESA AND P.SEQPRODUTO = XI.SEQPRODUTO
                        LEFT JOIN CONSINCO.MSU_PEDIDOSUPRIM PED ON PED.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM AND PED.NROEMPRESA = P.NROEMPRESA
                        LEFT JOIN CONSINCO.MAX_COMPRADOR M ON M.SEQCOMPRADOR = PED.SEQCOMPRADOR
                        
 WHERE X.DTAEMISSAO BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1)
   AND X.SEQPESSOA > 999
   AND X.STATUSNF != 'C'
   
