SELECT  /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/  
       TO_CHAR(X.DTAESTOQUE, 'DD/MM/YYYY') DATA, 
       X.NROEMPRESA LOJA, SEQPRODUTO SKU, 
       NAGF_PRECO_DIA_X_TIPO(X.NROEMPRESA, X.SEQPRODUTO, E.NROSEGMENTOPRINC, 1, X.DTAESTOQUE, 'N') PRECO_DE,
       NAGF_PRECO_DIA_X_TIPO(X.NROEMPRESA, X.SEQPRODUTO, E.NROSEGMENTOPRINC, 1, X.DTAESTOQUE, 'P') PRECO_PARA
        
  FROM FATO_ESTOQUE X INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = X.NROEMPRESA
 WHERE X.NROEMPRESA IN (#LS1)
   AND DTAESTOQUE  BETWEEN :DT1 AND :DT2
   AND NAGF_PRECO_DIA_X_TIPO(X.NROEMPRESA, X.SEQPRODUTO, E.NROSEGMENTOPRINC, 1, X.DTAESTOQUE, 'P') > 0

ORDER BY 1,2,3
