ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT CATEGORIAN1, SUM(JAN) JAN,   SUM(FEV) FEV,
                    SUM(MAR) MAR,   SUM(ABR) ABR,
                    SUM(MAI) MAI,   SUM(JUN) JUN,
                    SUM(AGO) AGO,   SUM(SETEM) SETEM,
                    SUM(OUTU) OUTU, SUM(NOV) NOV,
                    SUM(DEZ) DEZ
                    
                    FROM (

SELECT/*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       CATEGORIAN1, 
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 1
             AND EXTRACT (MONTH FROM DTAFIM)    = 1  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END JAN,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 2
             AND EXTRACT (MONTH FROM DTAFIM)    = 2  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END FEV,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 3
             AND EXTRACT (MONTH FROM DTAFIM)    = 3  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END MAR,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 4
             AND EXTRACT (MONTH FROM DTAFIM)    = 4  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END ABR,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 5
             AND EXTRACT (MONTH FROM DTAFIM)    = 5  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END MAI,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 6
             AND EXTRACT (MONTH FROM DTAFIM)    = 6  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END JUN,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 7
             AND EXTRACT (MONTH FROM DTAFIM)    = 7  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END JUL,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 8
             AND EXTRACT (MONTH FROM DTAFIM)    = 8  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END AGO,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 9
             AND EXTRACT (MONTH FROM DTAFIM)    = 9  THEN COUNT(DISTINCT(B.SEQPRODUTO)) END SETEM,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 10
             AND EXTRACT (MONTH FROM DTAFIM)    = 10 THEN COUNT(DISTINCT(B.SEQPRODUTO)) END OUTU,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 11
             AND EXTRACT (MONTH FROM DTAFIM)    = 11 THEN COUNT(DISTINCT(B.SEQPRODUTO)) END NOV,
       CASE WHEN EXTRACT (MONTH FROM DTAINICIO) = 12
             AND EXTRACT (MONTH FROM DTAFIM)    = 12 THEN COUNT(DISTINCT(B.SEQPRODUTO)) END DEZ

   FROM MRL_PROMOCAO A INNER JOIN MRL_PROMOCAOITEM B ON A.NROEMPRESA = B.NROEMPRESA  AND A.SEQPROMOCAO = B.SEQPROMOCAO AND A.CENTRALLOJA = B.CENTRALLOJA AND A.NROSEGMENTO = B.NROSEGMENTO
                       INNER JOIN MAP_PRODUTO      C ON C.SEQPRODUTO = B.SEQPRODUTO
                       INNER JOIN MAP_FAMDIVISAO   D ON D.SEQFAMILIA = C.SEQFAMILIA
                       INNER JOIN DIM_CATEGORIA@CONSINCODW E ON E.SEQFAMILIA = C.SEQFAMILIA                       

  WHERE 1=1
    AND B.STATUS != 'I'
    AND DTAINICIO >= DATE '2024-01-01' AND DTAFIM <= DATE '2025-01-01'
        
   GROUP BY CATEGORIAN1, DTAINICIO, DTAFIM
   
   ORDER BY 2 DESC
   ) GROUP BY CATEGORIAN1
