SELECT DISTINCT A.NROEMPRESA, A.SEQPROMOCAO, (SELECT COUNT(DISTINCT SEQPRODUTO) FROM MRL_PROMOCAOITEM B WHERE A.NROEMPRESA = B.NROEMPRESA  AND A.SEQPROMOCAO = B.SEQPROMOCAO AND A.CENTRALLOJA = B.CENTRALLOJA AND A.NROSEGMENTO = B.NROSEGMENTO) QTDITENS, 
       PROMOCAO DESCRICAO_PROMO, 
       TO_CHAR(DTAINICIO, 'DD/MM/YYYY') DTAINICIO,, TO_CHAR(DTAFIM, 'DD/MM/YYYY') DTAFIM, B.SEQPRODUTO, DESCCOMPLETA DESC_PRODUTO
  
  FROM MRL_PROMOCAO A INNER JOIN MRL_PROMOCAOITEM B ON A.NROEMPRESA = B.NROEMPRESA  AND A.SEQPROMOCAO = B.SEQPROMOCAO AND A.CENTRALLOJA = B.CENTRALLOJA AND A.NROSEGMENTO = B.NROSEGMENTO
                      INNER JOIN MAP_PRODUTO X ON B.SEQPRODUTO = X.SEQPRODUTO
                      
WHERE DTAINICIO >= :DT1 AND DTAFIM <= :DT2
  AND A.NROEMPRESA IN (#LS1)

ORDER BY 2,1
