SELECT * FROM (

SELECT Y.NOMEREDUZIDO ORIGEM,
       G.NOMEREDUZIDO DESTINO,
       X.NUMERODF NF,
       X.CODGERALOPER CG0,
       O.DESCRICAO DESCRICAO_CGO,
       TO_CHAR(X.DTAHOREMISSAO,'DD/MM/YYYY') DATA_EMISSAO,
      'NF PENDENTE DE RECEBIMENTO'STATUS,
       FVALORTOTALNF(X.ROWID,'D') VLR_NOTA,
       CASE WHEN XX.NUMERONF IS NULL THEN 'N' ELSE 'S' END MATOU_OP
FROM MFL_DOCTOFISCAL X INNER JOIN GE_EMPRESA Y ON (X.NROEMPRESA = Y.NROEMPRESA)
                                                  INNER JOIN GE_EMPRESA G ON (G.NROEMPRESA = X.SEQPESSOA)
                                                  INNER JOIN MAX_CODGERALOPER O ON (O.CODGERALOPER = X.CODGERALOPER)
                                                  LEFT JOIN MLF_NOTAFISCAL XX   ON X.NUMERODF  = XX.NFREFERENCIANRO
                                                        AND XX.CODGERALOPER IN (202,16,69,135,22,141,12,169,135,27,23,26,953,923)
                                                        AND XX.SEQPESSOA    < 999
                                                        AND XX.DTAEMISSAO   >= :DT1
                                                        AND X.NROEMPRESA   = XX.SEQPESSOA 
                                                        AND XX.STATUSNF != 'C'
WHERE 1=1
  AND EXISTS (SELECT 1 FROM DWNAGT_DADOSEMPRESA Z WHERE X.SEQPESSOA = Z.NROEMPRESA AND Z.TIPO='LOJA')
  AND X.DTAMOVIMENTO BETWEEN :DT1 AND :DT2
  AND X.MODELODF NOT IN ('65','59')
  AND X.SEQPESSOA IN (#LS1)
  AND NOT EXISTS (SELECT 1 FROM OR_NFDESPESA K WHERE K.NRONOTA = X.NUMERODF AND K.NROEMPRESA = X.SEQPESSOA AND K.SITUACAO = 'I' AND K.SEQPESSOA = X.NROEMPRESA)
  AND X.CODGERALOPER NOT IN (807,806,918)
  AND X.STATUSDF = 'V'
  AND X.STATUSNFE = 4 /* AUTORIZADAS */
  AND NOT EXISTS (SELECT 1 FROM MLF_NOTAFISCAL H WHERE H.NFECHAVEACESSO = X.NFECHAVEACESSO)

ORDER BY 6 )

WHERE MATOU_OP IN (DECODE(:LS2, 'SIM', 'S', 'NÃO', 'N')) OR NVL(:LS2,'T') = 'T'
