ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.SEQGERCOMPRA NROLOTE, DESCRITIVO, 
       TO_CHAR(X.DTAHORINCLUSAO, 'DD/MM/YYYY HH24:MI') USUINCLUSAO, 
       TO_CHAR(X.DTAHORFECHAMENTO, 'DD/MM/YYYY HH24:MI') DTAFECHAMENTO, 
       TO_CHAR(DTAGERPEDIDO, 'DD/MM/YYYY') DTAFATURAMENTO,
       USUGERPEDIDO USUFATURAMENTO, NROEMPRESA, XI.SEQPRODUTO PLU, DESCCOMPLETA DESC_PROD,
       CASE WHEN XI.DTAHORALTERACAO - X.DTAHORINCLUSAO > 0.042 THEN 
       TO_CHAR(XI.DTAHORALTERACAO, 'DD/MM/YYYY HH24:MI') ELSE NULL END DTA_ALTERACAO,
       QTDPEDIDA, 
       ROUND((TFVLRCUSTOBRUTO) * XI.QTDPEDIDA,2) VALOR,

       CASE WHEN NVL(QTDPEDIDA,0) = 0 THEN NULL ELSE QTDEMBALAGEM END QTDEMBALAGEM
       
  FROM MAC_GERCOMPRA X INNER JOIN CONSINCO.MAC_GERCOMPRAITEM XI ON X.SEQGERCOMPRA = XI.SEQGERCOMPRA
                       INNER JOIN CONSINCO.MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                       
 WHERE X.SEQGERCOMPRA IN (#LT1)

ORDER BY 1,NROEMPRESA
