SELECT
    P.SEQPRODUTO        AS PLU,
    P.DESCCOMPLETA,
    E.NROEMPRESA        AS LOJA,
    E.ESTQLOJA + E.ESTQDEPOSITO ESTOQUE,

    /* Janeiro */
    SUM(CASE WHEN V.DTAOPERACAO >= TRUNC(SYSDATE,'YYYY')
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 1)
             THEN V.QTDOPERACAO END) AS JAN,

    /* Fevereiro */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 1)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 2)
             THEN V.QTDOPERACAO END) AS FEV,

    /* Março */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 2)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 3)
             THEN V.QTDOPERACAO END) AS MAR,

    /* Abril */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 3)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 4)
             THEN V.QTDOPERACAO END) AS ABR,

    /* Maio */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 4)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 5)
             THEN V.QTDOPERACAO END) AS MAI,

    /* Junho */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 5)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 6)
             THEN V.QTDOPERACAO END) AS JUN,

    /* Julho */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 6)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 7)
             THEN V.QTDOPERACAO END) AS JUL,

    /* Agosto */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 7)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 8)
             THEN V.QTDOPERACAO END) AS AGO,

    /* Setembro */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 8)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 9)
             THEN V.QTDOPERACAO END) AS SETEMB,

    /* Outubro */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 9)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'),10)
             THEN V.QTDOPERACAO END) AS OUTUBR,

    /* Novembro */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'),10)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'),11)
             THEN V.QTDOPERACAO END) AS NOV,

    /* Dezembro */
    SUM(CASE WHEN V.DTAOPERACAO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'),11)
              AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'),12)
             THEN V.QTDOPERACAO END) AS DEZ,

    /* Margem */
    CASE WHEN E.NROEMPRESA < 100 THEN
      (SELECT ROUND(MGMPRECOVALIDO,2) FROM MAXV_MGMBASEPRODSEG Y WHERE Y.SEQPRODUTO = P.SEQPRODUTO AND Y.NROEMPRESA = E.NROEMPRESA AND Y.NROSEGMENTO = M.NROSEGMENTOPRINC AND Y.QTDEMBALAGEM = 1) END MARGEM,
    PRECOVALIDNORMAL

FROM MAP_PRODUTO P INNER JOIN MRL_PRODUTOEMPRESA E ON E.SEQPRODUTO = P.SEQPRODUTO
                   INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = E.NROEMPRESA
                   INNER JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = P.SEQPRODUTO AND S.NROEMPRESA = E.NROEMPRESA AND S.QTDEMBALAGEM = 1 AND S.NROSEGMENTO = M.NROSEGMENTOPRINC

LEFT JOIN FATOG_VENDADIA V
  ON V.SEQPRODUTO = P.SEQPRODUTO
 AND V.NROEMPRESA = E.NROEMPRESA
 AND V.DTAOPERACAO >= TRUNC(SYSDATE,'YYYY')
 AND V.DTAOPERACAO <  ADD_MONTHS(TRUNC(SYSDATE,'YYYY'),12)
 AND EXISTS (
       SELECT 1
         FROM NAGV_BASE_CGO_FINALIDADE C
        WHERE C.CGO_LIST = V.CODGERALOPER
          AND C.TIPO = 'V'
 )

WHERE P.SEQPRODUTO = 5500
GROUP BY
    P.SEQPRODUTO,
    P.DESCCOMPLETA,
    E.NROEMPRESA, M.NROSEGMENTOPRINC, E.ESTQLOJA + E.ESTQDEPOSITO, PRECOVALIDNORMAL
ORDER BY
    2, 1;
