SELECT DISTINCT S.NROPEDIDOSUPRIM NRO_PEDIDO,
       TO_CHAR(S.DTAHORINCLUSAO, 'DD/MM/YYYY') DTA_INCLUSAO,
       TO_CHAR(S.DTAEMISSAO, 'DD/MM/YYYY') DTA_FATURAMENTO,
       DECODE(S.TIPPEDIDOSUPRIM, 'B', 'Bonif. Incidência Custo',
                          'E', 'Bonif. Sem Incid. Custo',
                          'C', 'Compra',
                          'F', 'Cotação',
                          'M', 'Modelo de Compra',
                          'O', 'Modelo de Cotação',
                          'T', 'Transferência Interna',
                          'A', 'Abastecimento Automatico') TIPO_LOTE,
       S.USUINCLUSAO, 
       C.COMPRADOR,
       S.SEQFORNECEDOR||' - '||NOMERAZAO FORNEC,
       S.NROEMPRESA,
       SR.SEQPRODUTO PLU,
       P.DESCCOMPLETA DESC_PRODUTO,
       SR.QTDAPROVADA - SR.QTDTOTCANCELADA QUANTIDADE_UNI,
      ((NVL(SR.VLREMBITEM,0)+NVL(SR.VLREMBIPI,0)+NVL(SR.VLREMBICMSST,0)+NVL(SR.VLREMBDESPESA,0)+NVL(SR.VLREMBFRETE,0)-NVL(SR.VLREMBVERBACOMPRA,0)-NVL(SR.VLREMBDESCONTO,0)) /SR.QTDEMBALAGEM) * (NVL(SR.QTDAPROVADA,SR.QTDSOLICITADA) - SR.QTDTOTCANCELADA) VALOR_TOT_PED_EMP,
      ((NVL(SR.VLREMBITEM,0)+NVL(SR.VLREMBIPI,0)+NVL(SR.VLREMBICMSST,0)+NVL(SR.VLREMBDESPESA,0)+NVL(SR.VLREMBFRETE,0)-NVL(SR.VLREMBVERBACOMPRA,0)-NVL(SR.VLREMBDESCONTO,0)) /SR.QTDEMBALAGEM)    VALOR_ITEM_UNITARIO,
      ((NVL(SR.VLREMBITEM,0)+NVL(SR.VLREMBIPI,0)+NVL(SR.VLREMBICMSST,0)+NVL(SR.VLREMBDESPESA,0)+NVL(SR.VLREMBFRETE,0)-NVL(SR.VLREMBVERBACOMPRA,0)-NVL(SR.VLREMBDESCONTO,0)) /SR.QTDEMBALAGEM) * (SR.QTDAPROVADA - SR.QTDTOTCANCELADA) VALOR_ITEM_TOTAL
       
  FROM CONSINCO.MSU_PEDIDOSUPRIM S 
                       LEFT JOIN CONSINCO.MSU_PSITEMRECEBER  SR ON SR.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND SR.NROEMPRESA = S.NROEMPRESA
                       INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = S.SEQCOMPRADOR
                       INNER JOIN GE_PESSOA GE ON GE.SEQPESSOA = S.SEQFORNECEDOR
                       INNER JOIN CONSINCO.MAP_PRODUTO P ON P.SEQPRODUTO = SR.SEQPRODUTO
                       
 WHERE 1=1
   AND SR.STATUSITEM != 'C'
   AND TRUNC(S.DTAHORINCLUSAO) BETWEEN :DT1 AND :DT2
   AND COMPRADOR IN ('INSUMO') 
   
