ALTER SESSION SET current_schema = CONSINCO;

SELECT G.NROEMPRESA EMP, :NR1 PLU, (SELECT DESCCOMPLETA FROM MAP_PRODUTO WHERE SEQPRODUTO = :NR1) DESCRICAO,  
       SUM(QT) ENTRADA, TO_CHAR(SUM(SM), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_BRUTO, 
       TO_CHAR((SUM(SM) / SUM(QT)), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_UNI, SUM(QTDLANCTO) CONSUMO, E.ESTQLOJA
       

FROM GE_EMPRESA G LEFT JOIN

(SELECT DISTINCT  X.SEQPRODUTO PLU, X.NROEMPRESA EMP, X.CODGERALOPER CGO, X.QTDLANCTO, 
       (VALORLANCTOBRT * QTDLANCTO) VLR_BRUTO
        FROM FATO_PERDA@CONSINCODW X INNER JOIN dim_codgeraloper@CONSINCODW y ON (x.codgeraloper = y.codgeraloper)
        WHERE SEQPRODUTO IN (:NR1)
        AND DTAOPERACAO BETWEEN :DT1 AND :DT2
        AND Y.CODGERALOPER IN (49,66)
       
) X ON EMP = G.NROEMPRESA
                
        LEFT JOIN (SELECT C.NROEMPRESA NROEMP, C.SEQPRODUTO, SUM(C.QTDITEM) QT, SUM(C.VLRITEM) SM FROM FATO_COMPRA@CONSINCODW C 
                   WHERE C.SEQPRODUTO IN (:NR1) AND DTAENTRADA BETWEEN :DT1 AND :DT2
                   AND C.CODGERALOPER IN (2,59,65,652)
                   GROUP BY NROEMPRESA, SEQPRODUTO, TO_CHAR(C.DTAENTRADA, 'MM')) Y ON NROEMPRESA = Y.NROEMP
        LEFT JOIN MRL_PRODUTOEMPRESA E ON E.SEQPRODUTO = X.PLU AND E.NROEMPRESA = X.EMP

WHERE G.NROEMPRESA != 999

GROUP BY G.NROEMPRESA, PLU, E.ESTQLOJA
ORDER BY 1 ASC
