SELECT EMPRESA, FORNEC, NUMERONF, 
       TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO, 
       TO_CHAR(DTAENTRADA, 'DD/MM/YYYY') DTAENTRADA, 
       SKU, DESC_PROD, CATEGORIAN2, CATEGORIAN3, VLTTOTALITEM, SUM(VLR_FIDELIDADE) VLR_FIDELIDADE, SUM(VLR_LOGISTICO) VLR_LOGISTICO, 
       TO_CHAR(PZO_PAGTO, 'DD/MM/YYYY') PZO_PAGTO

  FROM (

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       X.NROEMPRESA EMPRESA, X.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, X.NUMERONF, X.DTAEMISSAO, 
       NVL(X.DTAENTRADA, X.DTAHORLANCTO) DTAENTRADA, XI.SEQPRODUTO SKU,
       DESCCOMPLETA DESC_PROD,
       CATEGORIAN2, CATEGORIAN3,
       F.VLTTOTALITEM,
       CASE WHEN CF.DESCRICAO LIKE 'FID%'  THEN SUM(F.PERCENTUAL * F.VLTTOTALITEM / 100) ELSE 0 END VLR_FIDELIDADE,
       CASE WHEN CF.DESCRICAO LIKE '%LOG%' THEN SUM(F.PERCENTUAL * F.VLTTOTALITEM / 100) ELSE 0 END VLR_LOGISTICO,
       V.DTAVENCIMENTO PZO_PAGTO

  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                        INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA
                        INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                        INNER JOIN MRL_TITULOFIN V ON V.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL AND V.NROTITULO = X.NUMERONF AND V.SEQPESSOA = X.SEQPESSOA
                         LEFT JOIN MLF_DESCFINACONTRATO F  ON F.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL        AND F.SEQITEMNF = XI.SEQITEMNF AND F.LINKERP = X.LINKERP AND F.PERCENTUAL > 0
                         LEFT JOIN MGC_CONTRATODESCONTO CF ON CF.SEQCONTRATODESCONTO = F.SEQCONTRATODESCONTO AND (CF.DESCRICAO LIKE 'FID%' OR CF.DESCRICAO LIKE '%LOG%')
                        
 WHERE X.SEQPESSOA   > 999
   AND X.CODGERALOPER IN (SELECT CODGERALOPER FROM NAGV_BASE_CGO_FINALIDADE CGO WHERE CGO.TIPO = 'C')
   AND C.CATEGORIAN1 = 'HORTIFRUTI'
   AND STATUSNF      = 'V'
   AND X.DTAEMISSAO  BETWEEN :DT1 AND :DT2
   
   GROUP BY X.NROEMPRESA, X.SEQPESSOA||' - '||G.NOMERAZAO, X.NUMERONF, X.DTAEMISSAO, NVL(X.DTAENTRADA, X.DTAHORLANCTO), XI.SEQPRODUTO, DESCCOMPLETA, CF.DESCRICAO, V.DTAVENCIMENTO, F.VLTTOTALITEM, CATEGORIAN2, CATEGORIAN3
   )
   
   GROUP BY EMPRESA, FORNEC, NUMERONF, DTAEMISSAo, DTAENTRADA, SKU, DESC_PROD, PZO_PAGTO, VLTTOTALITEM, CATEGORIAN2, CATEGORIAN3
   ORDER BY 1,3
