ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT A.NROEMPRESA, A.SEQPROMOCAO, (SELECT COUNT(DISTINCT SEQPRODUTO) FROM MRL_PROMOCAOITEM B WHERE A.NROEMPRESA = B.NROEMPRESA  AND A.SEQPROMOCAO = B.SEQPROMOCAO AND A.CENTRALLOJA = B.CENTRALLOJA AND A.NROSEGMENTO = B.NROSEGMENTO) QTDITENS, 
       PROMOCAO DESCRICAO_PROMO, DTAINICIO, DTAFIM, B.SEQPRODUTO, DESCCOMPLETA DESC_PRODUTO
  
  FROM MRL_PROMOCAO A INNER JOIN MRL_PROMOCAOITEM B ON A.NROEMPRESA = B.NROEMPRESA  AND A.SEQPROMOCAO = B.SEQPROMOCAO AND A.CENTRALLOJA = B.CENTRALLOJA AND A.NROSEGMENTO = B.NROSEGMENTO
                      INNER JOIN MAP_PRODUTO X ON B.SEQPRODUTO = X.SEQPRODUTO
                      
WHERE SYSDATE BETWEEN DTAINICIO AND DTAFIM AND DTAFIM < SYSDATE + 100
  AND A.NROEMPRESA = 51 

ORDER BY 1 
