ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT TO_CHAR(:DT1, 'DD/MM/YYYY') ||' à '|| TO_CHAR(:DT2, 'DD/MM/YYYY') PERIODO,
       X.SEQPESSOA COD_FORNECEDOR, NOMERAZAO FORNECEDOR,
       C.CATEGORIAN1, C.CATEGORIAN2, COMPRADOR, ROUND(AVG(XV.DTAVENCIMENTO - XV.DTAEMISSAO)) PRAZO_MED_PAGTO
       
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
                        INNER JOIN GE_PESSOA G ON X.SEQPESSOA = G.SEQPESSOA
                        INNER JOIN MAP_PRODUTO P ON XI.SEQPRODUTO = P.SEQPRODUTO
                         LEFT JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA
                         LEFT JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA
                         LEFT JOIN MAX_COMPRADOR CM ON CM.SEQCOMPRADOR = F.SEQCOMPRADOR 
                        INNER JOIN CONSINCO.MRL_TITULOFIN XV ON XV.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
 WHERE 1=1
   AND X.DTAENTRADA BETWEEN :DT1 AND :DT2
   AND X.SEQPESSOA > 999
   AND XV.OBRIGDIREITO = 'O'
   AND X.STATUSNF != 'C'

GROUP BY X.SEQPESSOA, NOMERAZAO, CATEGORIAN1, CATEGORIAN2, COMPRADOR

ORDER BY 2 ASC

