ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.SEQGERCOMPRA NROLOTE, DESCRITIVO, 
       FO.SEQFORNECEDOR COD_FORNEC, NOMERAZAO FORNEC,
       TO_CHAR(X.DTAHORINCLUSAO, 'DD/MM/YYYY HH24:MI') USUINCLUSAO, 
       TO_CHAR(X.DTAHORFECHAMENTO, 'DD/MM/YYYY HH24:MI') DTAFECHAMENTO, 
       TO_CHAR(DTAGERPEDIDO, 'DD/MM/YYYY') DTAFATURAMENTO,
       USUGERPEDIDO USUFATURAMENTO, XI.NROEMPRESA, XI.SEQPRODUTO PLU, DESCCOMPLETA DESC_PROD,
       CASE WHEN XI.DTAHORALTERACAO - X.DTAHORINCLUSAO > 0.042
         THEN TO_CHAR(XI.DTAHORALTERACAO, 'DD/MM/YYYY HH24:MI') ELSE NULL END DTA_ALTERACAO,
       QTDPEDIDA QTD_UNI_PEDIDA, 
       CASE WHEN NVL(QTDPEDIDA,0) = 0 
         THEN NULL ELSE QTDEMBALAGEM END QTDEMBALAGEM, ROUND((TFVLRCUSTOBRUTO) * XI.QTDPEDIDA,2) VALOR,
       CASE WHEN NVL(QTDPEDIDA,0) =0
         THEN NULL ELSE S.NROPEDIDOSUPRIM END PEDIDO,
       F.NUMERONF, TO_CHAR(F.DTAHORLANCTO, 'DD/MM/YYYY') DTA_RECEBIMENTO
       
  FROM MAC_GERCOMPRA X INNER JOIN CONSINCO.MAC_GERCOMPRAITEM XI ON X.SEQGERCOMPRA = XI.SEQGERCOMPRA
                       INNER JOIN MAC_GERCOMPRAFORN FO ON FO.SEQGERCOMPRA = X.SEQGERCOMPRA
                       INNER JOIN GE_PESSOA GE ON GE.SEQPESSOA = FO.SEQFORNECEDOR
                       INNER JOIN CONSINCO.MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                       LEFT JOIN CONSINCO.MSU_PEDIDOSUPRIM S ON S.SEQGERCOMPRA = X.SEQGERCOMPRA AND S.NROEMPRESA = XI.NROEMPRESA
                       LEFT JOIN CONSINCO.MSU_PSITEMRECEBIDO SI ON SI.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND SI.NROEMPRESA = S.NROEMPRESA AND SI.SEQPRODUTO = XI.SEQPRODUTO AND QTDCANCELADA = 0
                       LEFT JOIN MLF_NOTAFISCAL F ON F.SEQAUXNOTAFISCAL = SI.SEQAUXNOTAFISCAL
                       
 WHERE X.SEQGERCOMPRA IN (320715)
   AND XI.SITUACAOITEM != 'C'
   
ORDER BY 1, S.NROEMPRESA

-- Old

SELECT X.SEQGERCOMPRA NROLOTE, DESCRITIVO, 
       TO_CHAR(X.DTAHORINCLUSAO, 'DD/MM/YYYY HH24:MI') USUINCLUSAO, 
       TO_CHAR(X.DTAHORFECHAMENTO, 'DD/MM/YYYY HH24:MI') DTAFECHAMENTO, 
       TO_CHAR(DTAGERPEDIDO, 'DD/MM/YYYY') DTAFATURAMENTO,
       USUGERPEDIDO USUFATURAMENTO, NROEMPRESA, XI.SEQPRODUTO PLU, DESCCOMPLETA DESC_PROD,
       CASE WHEN XI.DTAHORALTERACAO - X.DTAHORINCLUSAO > 0.042 THEN 
       TO_CHAR(XI.DTAHORALTERACAO, 'DD/MM/YYYY HH24:MI') ELSE NULL END DTA_ALTERACAO,
       QTDPEDIDA, 
       ROUND((TFVLRCUSTOBRUTO) * XI.QTDPEDIDA,2) VALOR,

       CASE WHEN NVL(QTDPEDIDA,0) = 0 THEN NULL ELSE QTDEMBALAGEM END QTDEMBALAGEM
       
  FROM MAC_GERCOMPRA X INNER JOIN CONSINCO.MAC_GERCOMPRAITEM XI ON X.SEQGERCOMPRA = XI.SEQGERCOMPRA
                       INNER JOIN CONSINCO.MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                       
 WHERE X.SEQGERCOMPRA IN (#LT1)

ORDER BY 1,NROEMPRESA
