SELECT NROEMPRESA, NAGF_BUSCAQTDITENSPROMOC(1,:NR1,EMP.NROEMPRESA) JANEIRO,
                   NAGF_BUSCAQTDITENSPROMOC(2,:NR1,EMP.NROEMPRESA) FEVEREIRO,
                   NAGF_BUSCAQTDITENSPROMOC(3,:NR1,EMP.NROEMPRESA) MARCO,
                   NAGF_BUSCAQTDITENSPROMOC(4,:NR1,EMP.NROEMPRESA) ABRIL,
                   NAGF_BUSCAQTDITENSPROMOC(5,:NR1,EMP.NROEMPRESA) MAIO,
                   NAGF_BUSCAQTDITENSPROMOC(6,:NR1,EMP.NROEMPRESA) JUNHO,
                   NAGF_BUSCAQTDITENSPROMOC(7,:NR1,EMP.NROEMPRESA) JULHO,
                   NAGF_BUSCAQTDITENSPROMOC(8,:NR1,EMP.NROEMPRESA) AGOSTO,
                   NAGF_BUSCAQTDITENSPROMOC(9,:NR1,EMP.NROEMPRESA) SETEMBRO,
                   NAGF_BUSCAQTDITENSPROMOC(10,:NR1,EMP.NROEMPRESA) OUTUBRO,
                   NAGF_BUSCAQTDITENSPROMOC(11,:NR1,EMP.NROEMPRESA) NOVEMBRO,
                   NAGF_BUSCAQTDITENSPROMOC(12,:NR1,EMP.NROEMPRESA) DEZZEMBRO
                   
  FROM MAX_EMPRESA EMP
