SELECT E.NROEMPRESA LOJA, TO_CHAR(E.DTAESTOQUE, 'DD/MM/YYYY') DATA, X.SEQPRODUTO PLU, DESCCOMPLETA, E.QTDESTQLOJA, 
       CONSINCO.NAGF_PRECO_DIA_X(E.NROEMPRESA, 
       X.SEQPRODUTO,
       M.NROSEGMENTOPRINC,
       1,
       E.DTAESTOQUE) PRECO_DIA,
       /*CONSINCO.NAGF_PRECO_DIA_X(E.NROEMPRESA, 
       X.SEQPRODUTO,
       DECODE(M.NROSEGMENTOPRINC,2,5,4,8),
       1,
       E.DTAESTOQUE) PRECO_ECOMMERCE*/
       (SELECT ROUND(MGMPRECOVALIDO,2) FROM MAXV_MGMBASEPRODSEG Y WHERE Y.SEQPRODUTO = X.SEQPRODUTO AND Y.NROEMPRESA = E.NROEMPRESA AND Y.NROSEGMENTO = M.NROSEGMENTOPRINC AND Y.QTDEMBALAGEM = 1) MARGEM
       
  FROM MAP_PRODUTO X LEFT JOIN  FATO_ESTOQUE E       ON E.SEQPRODUTO = X.SEQPRODUTO
                     INNER JOIN MAX_EMPRESA M        ON M.NROEMPRESA = E.NROEMPRESA
                     
 WHERE DESCCOMPLETA LIKE '%'||UPPER('#LT1')||'%'
   AND E.NROEMPRESA IN (#LS1)
   AND E.DTAESTOQUE BETWEEN :DT1 AND :DT2
   
 ORDER BY 1,2
 
