ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT A.SEQPEDIDOIMPORT NRO_PED,
       A.SEQPRODUTO PLU,
       C.CODACESSO REF,
       A.QTDEMBALAGEM,
       D.PESOLIQUIDO,
       A.QTDSOLICITADA QTD_PED,
       A.SEQFAMILIA FAM,
       A.VLRDESPADUANEIRA,
       B.DESCCOMPLETA,
       A.VLRITEM,
       A.VLRITEMCUSTO,
       A.PERALIQIPI,
       A.VLRPAUTAIPI,
       A.VLRIPI,
       A.PERIMPOSTIMPORT,
       A.VLRIMPIMPORT,
       A.VLRPIS,
       A.VLRCOFINS,
       A.VLRICMS,
       A.VLRICMSST,
       A.VLRDESPESA,
       A.VLRDESPESAFORA,
       A.VLRFCPICMS,
       A.VLRFCPST
  FROM MAD_PIPEDIMPORTPROD A INNER JOIN MAP_PRODUTO B      ON A.SEQPRODUTO = B.SEQPRODUTO
                              LEFT JOIN MAP_PRODCODIGO C   ON C.SEQPRODUTO = A.SEQPRODUTO 
                                                          AND C.TIPCODIGO = 'F'
                             INNER JOIN MAP_FAMEMBALAGEM D ON D.SEQFAMILIA = B.SEQFAMILIA
                                                          AND D.QTDEMBALAGEM = A.QTDEMBALAGEM
 WHERE 1 = 1
   AND A.SEQPEDIDOIMPORT = '1598'
   
ORDER BY 10 DESC
