SELECT * FROM (
SELECT X.SEQGERCOMPRA LOTE, TO_CHAR(DTAGERPEDIDO, 'DD/MM/YYYY') DTAGERPEDIDO,
       DESCRITIVO, 'MARKETING' COMPRADOR, Z.SEQFORNECEDOR||' - '||(SELECT NOMERAZAO FROM CONSINCO.GE_PESSOA G WHERE G.SEQPESSOA = Z.SEQFORNECEDOR) FORNECEDOR,  
       M.FANTASIA LOJA, QTDPEDIDA QTD_UNID,/* CASE WHEN QTDPEDIDA > 0 THEN QTDPEDIDA / I.QTDEMBALAGEM||' x '||QTDEMBALAGEM||' '||I.EMBCOMPRA END QTD_EMB,*/ 
       /*CASE WHEN QTDPEDIDA > 0 THEN TO_CHAR(TFVALORTOTALNF * QTDEMBALAGEM, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') END VLR_UNIT_EMB,*/
       TO_CHAR(QTDPEDIDA  * TFVALORTOTALNF, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_TOTAL
 
  FROM CONSINCO.MAC_GERCOMPRA X LEFT JOIN CONSINCO.MAC_GERCOMPRAFORN Z ON Z.SEQGERCOMPRA = X.SEQGERCOMPRA
                                LEFT JOIN CONSINCO.MAC_GERCOMPRAITEM I ON X.SEQGERCOMPRA = I.SEQGERCOMPRA
                                INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = I.NROEMPRESA
 WHERE 1=1
   AND X.SITUACAOLOTE != 'C'
   AND X.SEQCOMPRADOR = 290 
   
   AND X.SEQGERCOMPRA = :NR1
   AND NVL(QTDPEDIDA,0) >= CASE WHEN :LS1 = 'Exceto Lojas Zeradas' THEN 1 ELSE NVL(QTDPEDIDA,0) END
   
ORDER BY M.NROEMPRESA ASC)

UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

UNION ALL

SELECT NULL, NULL,
       NULL,NULL, NULL,  
       'Totais:' a, SUM(QTDPEDIDA) QTD_UNID, TO_CHAR(SUM(QTDPEDIDA  * TFVALORTOTALNF), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_TOTAL
 
  FROM CONSINCO.MAC_GERCOMPRA X LEFT JOIN CONSINCO.MAC_GERCOMPRAFORN Z ON Z.SEQGERCOMPRA = X.SEQGERCOMPRA
                                LEFT JOIN CONSINCO.MAC_GERCOMPRAITEM I ON X.SEQGERCOMPRA = I.SEQGERCOMPRA
                                INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = I.NROEMPRESA
 WHERE 1=1
   AND X.SITUACAOLOTE != 'C'
   AND X.SEQCOMPRADOR = 290 
   
   AND X.SEQGERCOMPRA = :NR1
   AND NVL(QTDPEDIDA,0) >= CASE WHEN :LS1 = 'Exceto Lojas Zeradas' THEN 1 ELSE NVL(QTDPEDIDA,0) END
