-- Lua | Lucratividade Anual

SELECT TO_CHAR(DATA, 'YYYY') ANO,
       'R$  '||TO_CHAR(SUM(VLR_VENDA),'FM9G999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''')      VLR_VENDA, 
       'R$ '||TO_CHAR(SUM(VLR_LUCRATIVIDADE),'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_LUCRATIVIDADE
FROM NAGT_APP_VENDASCATEGORIA@CONSINCODW A WHERE DATA >= DATE '2020-01-01'
GROUP BY TO_CHAR(DATA, 'YYYY')

ORDER BY 1 ASC
