SELECT P.SEQPRODUTO PLU, DESCCOMPLETA, P.SEQFAMILIA COD_FAMILIA,
       LISTAGG(C.CODACESSO, ', ') WITHIN GROUP (ORDER BY C.SEQPRODUTO) EANS, MARCA
       
  FROM MAP_PRODUTO P LEFT JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = P.SEQPRODUTO AND C.TIPCODIGO = 'E' AND QTDEMBALAGEM = 1
                     INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                     INNER JOIN MAP_MARCA M   ON M.SEQMARCA = F.SEQMARCA
                     
 WHERE EXISTS (SELECT 1
          FROM MAP_PRODUTO Z
         WHERE Z.SEQFAMILIA = P.SEQFAMILIA
               AND Z.SEQPRODUTO = :NR1)
               
GROUP BY P.SEQPRODUTO, DESCCOMPLETA, P.SEQFAMILIA, MARCA
