ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT R.NROREQUISICAO REQUISICAO, DECODE (R.STATUS,
                'L','Autorizada','A','Aguardando ',
                'F','Finalizada','R','Rejeitada') STATUS_REQ,
       NRONOTA NUMERONF, (SELECT NOMERAZAO FROM GE_PESSOA G WHERE G.SEQPESSOA = X.SEQPESSOA) FORNECEDOR, 
       LPAD(M.NROCGC,12,0)||LPAD(M.DIGCGC,2,0) CNPJ_EMPRESA, X.NROEMPRESA LOJA, 
       TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY')    DTAEMISSAO,
       TO_CHAR(V.DTAVENCTO, 'DD/MM/YYYY') DTAVENCIMENTO,
       TO_CHAR(X.VALOR, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF,
       Z.DESCRICAO DESCRICAO_PRODUTO, 
       TO_CHAR(Z.VLRTOTAL / Z.QUANTIDADE, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_UNITARIO,
       Z.QUANTIDADE,
       TO_CHAR(Z.VLRTOTAL, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_PRODUTO0
       
  FROM OR_NFDESPESA X INNER JOIN OR_NFITENSDESPESA Z ON X.SEQNOTA = Z.SEQNOTA AND X.NROEMPRESA = Z.NROEMPRESA
                      INNER JOIN MAX_EMPRESA       M ON M.NROEMPRESA = X.NROEMPRESA 
                      INNER JOIN OR_NFVENCIMENTO   V ON V.SEQNOTA = X.SEQNOTA AND V.NROEMPRESA = X.NROEMPRESA
                      INNER JOIN CONSINCO.OR_REQUISICAO R ON R.SEQREQUISICAO = X.REQUISICOES
                      INNER JOIN CONSINCO.MAX_COMPRADOR B ON B.SEQCOMPRADOR = R.SEQCOMPRADOR
                      INNER JOIN CONSINCO.OR_REQPLANILHALANCTO E ON E.SEQREQUISICAO = R.SEQREQUISICAO
 WHERE 1=1
   AND X.NROEMPRESA IN (#LS1)
   AND B.COMPRADOR IN ('MORGANA','MARKETING','BRUNO NAGUMO')
   AND E.TIPOCONTAB = 'D'
   AND E.PERCRATEIO > 0
   AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2

ORDER BY X.NROEMPRESA, NRONOTA
