ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT NROEMPRESA, SUM(A) QTD_FORA_ENC, SUM(B) QTD_DENTRO_ENC FROM (
SELECT X.NROEMPRESA, 
       CASE WHEN X.SEQPRODUTO NOT IN (SELECT Z.SEQPRODUTO FROM MRL_ENCARTE XX INNER JOIN CONSINCO.MRL_ENCARTEPRODUTO Z ON XX.SEQENCARTE = Z.SEQENCARTE 
                                                                              INNER JOIN CONSINCO.MRL_ENCARTEEMP Y     ON Y.SEQENCARTE = Z.SEQENCARTE
                                                                              WHERE Z.SEQPRODUTO = X.SEQPRODUTO AND Y.NROEMPRESA = X.NROEMPRESA AND X.DTAHORAPROVREPROV BETWEEN DTAINICIO AND DTAFIM) 
         THEN 1 ELSE 0 END A,
       CASE WHEN X.SEQPRODUTO IN     (SELECT Z.SEQPRODUTO FROM MRL_ENCARTE XX INNER JOIN CONSINCO.MRL_ENCARTEPRODUTO Z ON XX.SEQENCARTE = Z.SEQENCARTE 
                                                                              INNER JOIN CONSINCO.MRL_ENCARTEEMP Y     ON Y.SEQENCARTE = Z.SEQENCARTE
                                                                              WHERE Z.SEQPRODUTO = X.SEQPRODUTO AND Y.NROEMPRESA = X.NROEMPRESA AND X.DTAHORAPROVREPROV BETWEEN DTAINICIO AND DTAFIM)
         THEN 1 ELSE 0 END B

  FROM MAD_PRODLOGPRECO X
 
 WHERE X.NROSEGMENTO IN (SELECT NROSEGMENTOPRINC FROM MAX_EMPRESA Z WHERE X.NROEMPRESA = Z.NROEMPRESA)
   AND DTAHORALTERACAO BETWEEN DATE '2023-05-01' AND DATE '2023-05-31'
   AND QTDEMBALAGEM = 1
   AND X.SEQPROMOCAO IS NOT NULL
   AND X.DTAHORAPROVREPROV IS NOT NULL 
   AND X.NROEMPRESA < 100
    
   GROUP BY SEQPRODUTO, X.SEQPROMOCAO, X.NROEMPRESA, DTAHORAPROVREPROV)
   
   GROUP BY NROEMPRESA
   
   ORDER BY NROEMPRESA
   
   SELECT COUNT(DISTINCT SEQPRODUTO), COUNT(DISTINCT G.SEQENCARTE) FROM MRL_ENCARTE G INNER JOIN MRL_ENCARTEPRODUTO H ON H.SEQENCARTE = G.SEQENCARTE
   WHERE G.DTAALTERACAO BETWEEN DATE '2023-05-01' AND DATE '2023-05-31'
