SELECT DISTINCT NROACORDO, A.NROEMPRESA LOJA, SEQFORNECEDOR||' - '||(SELECT NOMERAZAO FROM CONSINCO.GE_PESSOA B WHERE B.SEQPESSOA = A.SEQFORNECEDOR) FORNECEDOR, 
       DESCACORDO DESCRICAO_ACORDO, TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') EMISSAO, TO_CHAR(A.DTAVENCIMENTO, 'DD/MM/YYYY') VENCIMENTO, 
       TO_CHAR(A.DTAINCLUSAO, 'DD/MM/YYYY') INCLUSAO, USUINCLUSAO USUINCLUSAO,
       TO_CHAR(VLRACORDO, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_ACORDO,
      (SELECT TO_CHAR(SUM(NVL(C.VLRPAGO,0)), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
          FROM CONSINCO.FI_TITULO C WHERE 1=1 
                                      AND A.NROACORDO = C.NROTITULO 
                                      AND A.SEQFORNECEDOR = C.SEQPESSOA 
                                      AND C.SITUACAO != 'C'
                                      AND C.CODESPECIE = 'ACRMKT') VLRPAGO,
       (SELECT TO_CHAR(SUM(NVL(C.VLRORIGINAL,0) - NVL(C.VLRPAGO,0)), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')
          FROM CONSINCO.FI_TITULO C WHERE 1=1 
                                      AND A.NROACORDO = C.NROTITULO 
                                      AND A.SEQFORNECEDOR = C.SEQPESSOA 
                                      AND C.SITUACAO != 'C'
                                      AND C.CODESPECIE = 'ACRMKT') VLR_EM_ABERTO
                                      
       
  FROM CONSINCO.MSU_ACORDOPROMOC A 
 WHERE 1=1
   AND CODTIPOACORDO = 2 
   AND SITUACAOACORDO = 'F'
   AND A.DTAEMISSAO BETWEEN DATE '2023-04-01' AND DATE '2023-05-30'
 
 ORDER BY TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY')  DESC, 4 ASC
 
 
