-- Hash em específico:

SELECT /*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*/ X.SEQPESSOA ID, CPF_CODIFICADO, CPF_ORIGINAL, A.NOMERAZAO
  FROM (SELECT /*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*/ SEQPESSOA,
               REPLACE(RAWTOHEX(DBMS_OBFUSCATION_TOOLKIT.MD5(INPUT => UTL_RAW.CAST_TO_RAW(NVL(LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0),0)))),
                        'CFCD208495D565EF66E7DFF9F98764DA',
                       '') CPF_CODIFICADO,
               LPAD(NROCGCCPF, 9, 0) || LPAD(DIGCGCCPF, 2, 0) CPF_ORIGINAL
          FROM GE_PESSOA B WHERE B.FISICAJURIDICA = 'F') X INNER JOIN GE_PESSOA A ON A.SEQPESSOA = X.SEQPESSOA
          
 WHERE CPF_CODIFICADO = 'D88AC1990A5AD45BF5BEEC0AD465AD1E'

-- Cadastro Geral a partir do De/Para

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/  X.SEQPESSOA ID, CPF_CODIFICADO, CPF_ORIGINAL, A.NOMERAZAO
  FROM (SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/  SEQPESSOA,
               REPLACE(RAWTOHEX(DBMS_OBFUSCATION_TOOLKIT.MD5(INPUT => UTL_RAW.CAST_TO_RAW(NVL(LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0),0)))),
                        'CFCD208495D565EF66E7DFF9F98764DA',
                       '') CPF_CODIFICADO,
               LPAD(NROCGCCPF, 9, 0) || LPAD(DIGCGCCPF, 2, 0) CPF_ORIGINAL
          FROM CONSINCO.GE_PESSOA B 
          INNER JOIN CONSINCO.NAGT_CPFCODTRANSAC DC ON DC.COD = 
          REPLACE(RAWTOHEX(DBMS_OBFUSCATION_TOOLKIT.MD5(INPUT => UTL_RAW.CAST_TO_RAW(NVL(LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0),0)))),
                        'CFCD208495D565EF66E7DFF9F98764DA',
                       '')
          ) X INNER JOIN CONSINCO.GE_PESSOA A ON A.SEQPESSOA = X.SEQPESSOA 
          
