SELECT NROACORDO, NROEMPRESA, (SELECT NOMERAZAO FROM CONSINCO.GE_PESSOA B WHERE B.SEQPESSOA = A.SEQFORNECEDOR)||' - '||SEQFORNECEDOR FORNECEDOR, 
       DESCACORDO DESCRICAO_ACORDO, TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') DATA_VENCIMENTO, 
       TO_CHAR(VLRACORDO, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_ACORDO, TO_CHAR(DTAINCLUSAO, 'DD/MM/YYYY') DATA_INCLUSAO, USUINCLUSAO USUARIO_INCLUSAO
  FROM CONSINCO.MSU_ACORDOPROMOC A 
 WHERE CODTIPOACORDO = 2 
   AND SITUACAOACORDO != 'C'
   AND DTAEMISSAO BETWEEN :DT1 AND :DT2
 
 ORDER BY DTAEMISSAO DESC, 4 ASC
