SELECT DISTINCT F.NROEMPRESA EMPRESA, F.NRODOCUMENTO, F.NROPARCELA||' \ '||F.QTDPARCELA PARCELA,
       F.CODESPECIE ESPECIE, G.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR,
       TO_CHAR(F.DTAEMISSAO, 'DD-MM-YYYY') DATA_EMISSAO,
       TO_CHAR(F.VLRORIGINAL, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRORIGINAL,
       DECODE(F.ABERTOQUITADO,'A','Aberto','Q','Quitado') STATUS_TIT

FROM FI_TITULO F  INNER JOIN GE_PESSOA G ON F.SEQPESSOA = G.SEQPESSOA

WHERE F.CODESPECIE = 'ACRMKT'
  AND F.DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND F.ABERTOQUITADO LIKE (DECODE(:LS1, 'Aberto','A','Quitado','Q','%%'))
  
ORDER BY 1,2,3
