SELECT DISTINCT X.SEQFORNECEDOR COD_FORNEC, NOMERAZAO RAZAO_FORNEC, LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) CNPJ_FORNEC,
                DECODE(X.TIPFORNECEDOR, 'I','Industria', 'D','Distribuidor', 'Prestador de Serviços') TIPO_FORNEC,
                
                (SELECT SUM(C.VLRPAGO) FROM FI_TITULO C
                  WHERE C.SEQPESSOA = X.SEQFORNECEDOR AND C.DTAINCLUSAO >= DATE '2025-01-01' 
                    AND C.CODESPECIE IN (SELECT CODESPECIE FROM MAC_TIPOACORDO) AND C.SITUACAO != 'C' AND C.DTAVENCIMENTO  < TRUNC(SYSDATE)) VLR_FIN_ACO_VENCIDO_PAGO,
                    
                (SELECT SUM(VLRORIGINAL - C.VLRPAGO) FROM FI_TITULO C
                  WHERE C.SEQPESSOA = X.SEQFORNECEDOR AND C.DTAINCLUSAO >= DATE '2025-01-01' 
                    AND C.CODESPECIE IN (SELECT CODESPECIE FROM MAC_TIPOACORDO A WHERE A.CODESPECIE NOT LIKE 'CO%') AND C.SITUACAO != 'C' AND C.DTAVENCIMENTO  < TRUNC(SYSDATE)) VLR_FIN_ACO_VENCIDO_ABERTO,
                    
                (SELECT SUM(VLRPAGO) FROM FI_TITULO C
                  WHERE C.SEQPESSOA = X.SEQFORNECEDOR AND C.DTAINCLUSAO >= DATE '2025-01-01' 
                    AND C.CODESPECIE IN (SELECT CODESPECIE FROM MAC_TIPOACORDO A WHERE A.CODESPECIE NOT LIKE 'CO%') AND C.SITUACAO != 'C' AND C.DTAVENCIMENTO >= TRUNC(SYSDATE)) VLR_FIN_ACO_A_VENCER_PAGO,
                  
                (SELECT SUM(VLRORIGINAL - VLRPAGO) FROM FI_TITULO C 
                  WHERE C.SEQPESSOA = X.SEQFORNECEDOR AND C.DTAINCLUSAO >= DATE '2025-01-01' 
                    AND C.CODESPECIE IN (SELECT CODESPECIE FROM MAC_TIPOACORDO A WHERE A.CODESPECIE NOT LIKE 'CO%') AND C.SITUACAO != 'C' AND C.DTAVENCIMENTO >= TRUNC(SYSDATE)) VLR_FIN_ACO_A_VENCER_ABERTO,
                    
                (SELECT SUM(VLRORIGINAL - VLRPAGO) FROM FI_TITULO C
                  WHERE C.SEQPESSOA = X.SEQFORNECEDOR AND C.DTAINCLUSAO >= DATE '2025-01-01' 
                    AND C.CODESPECIE IN (SELECT CODESPECIE FROM MAC_TIPOACORDO A WHERE A.CODESPECIE = 'ACRMDN') AND C.SITUACAO != 'C' AND C.DTAVENCIMENTO >= TRUNC(SYSDATE)) VLR_FIN_ACO_A_VENCER_ABERTO_DN,
                    
                (SELECT SUM(VLRPAGO) FROM FI_TITULO C
                  WHERE C.SEQPESSOA = X.SEQFORNECEDOR AND C.DTAINCLUSAO >= DATE '2025-01-01' 
                    AND C.CODESPECIE IN (SELECT CODESPECIE FROM MAC_TIPOACORDO A WHERE A.CODESPECIE = 'ACRMDN') AND C.SITUACAO != 'C' AND C.DTAVENCIMENTO >= TRUNC(SYSDATE)) VLR_FIN_ACO_DN_PAGO
                  
  FROM MAF_FORNECEDOR X INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQFORNECEDOR
 WHERE SEQFORNECEDOR > 999
   AND NOMERAZAO NOT LIKE '%COMPRALJ%'
   AND EXISTS (SELECT 1 FROM MAC_GERCOMPRAFORN A INNER JOIN MAC_GERCOMPRA B ON A.SEQGERCOMPRA = B.SEQGERCOMPRA
                WHERE B.DTAHORINCLUSAO >= DATE '2024-01-01'
                  AND A.SEQFORNECEDOR = X.SEQFORNECEDOR)

 ORDER BY 2;
