SELECT DISTINCT
       X.SEQENCARTE||' - '||X.DESCRICAO INFO_ENCARTE,
       TO_CHAR(NVL(XI.DTAVIGENCIAINI, X.DTAINICIO), 'DD/MM/YYYY') DTA_INICIO,
       TO_CHAR(NVL(XI.DTAVIGENCIAFIM, X.DTAFIM), 'DD/MM/YYYY') DTA_FIM,
       XI.NROPAGINA PAG, NVL(G.NOMEPAGINA, 'SEM_DESC') DESC_PAG,
       CO.COMPRADOR, XI.SEQPRODUTO PLU, 
      (SELECT LISTAGG(CODACESSO, ' ') WITHIN GROUP(ORDER BY SEQPRODUTO)
         FROM MAP_PRODCODIGO E 
        WHERE E.SEQPRODUTO = XI.SEQPRODUTO 
          AND E.TIPCODIGO = 'E') EAN,
       P.DESCCOMPLETA DESCRICAO,
       NOMERAZAO FORNEC,
       CASE WHEN EXISTS (SELECT 1 FROM NAGT_PROD_ACELERADOR ACE WHERE ACE.SEQPRODUTO = XI.SEQPRODUTO
                                                                  AND SYSDATE BETWEEN DTAINICIO AND DTATERMINO) 
                                                                 THEN 'Sim' ELSE 'Não' END ACELERADOR
      

  FROM MRL_ENCARTE X INNER JOIN MRL_ENCARTEPRODUTO XI         ON XI.SEQENCARTE = X.SEQENCARTE
                     LEFT JOIN MRL_ENCARTEPRODUTOPRECO PP     ON PP.SEQENCARTE = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO
                     INNER JOIN MAP_PRODUTO P                 ON P.SEQPRODUTO  = XI.SEQPRODUTO
                     INNER JOIN CONSINCO.MRL_ENCARTENOMEPAG G ON G.SEQENCARTE  = X.SEQENCARTE AND G.NROPAGINA = XI.NROPAGINA
                     INNER JOIN MAP_FAMFORNEC F               ON F.SEQFAMILIA  = P.SEQFAMILIA AND F.PRINCIPAL = 'S'
                     INNER JOIN MAP_FAMDIVISAO C              ON C.SEQFAMILIA  = P.SEQFAMILIA
                     INNER JOIN MAX_COMPRADOR CO              ON CO.SEQCOMPRADOR = C.SEQCOMPRADOR
                     INNER JOIN GE_PESSOA GP                  ON GP.SEQPESSOA  = F.SEQFORNECEDOR
   WHERE 1 = 1
      
   AND X.SEQENCARTE = 30588
   ORDER BY 4,9
