SELECT TO_CHAR(DTAENTRADA, 'MM') MES, TO_CHAR(DTAENTRADA, 'W') SEMANA, 
       TO_CHAR(DTAENTRADA, 'DD/MM/YYYY')     DTA_LANCTO, 
       TO_CHAR(R.DTAINCLUSAO, 'DD/MM/YYYY')  DTA_REQUISICAO, 
       DECODE(R.STATUS, 'A',' Aguardando Autorização','F','Finalizada','L','Liberada','R','Rejeitada') STATUS,
       R.USUINCLUSAO, R.USUAUTORIZACAO,
       A.SEQPESSOA||' - '||G.NOMERAZAO FORNEC,
       Y.SEQPRODUTO||' - '||DESCCOMPLETA PRODUTO, 
       ROUND(X.VLRTOTAL / (QUANTIDADE),2) VLR_UNIT_PROD, (X.VLRTOTAL) VLR_TOTAL_PROD, (TO_NUMBER(QUANTIDADE)) QTD_PROD
       
  FROM CONSINCO.OR_NFDESPESA A INNER JOIN CONSINCO.OR_NFITENSDESPESA X ON X.SEQNOTA      = A.SEQNOTA
                      INNER JOIN CONSINCO.MAP_PRODUTO Y       ON X.CODPRODUTO   = Y.SEQPRODUTO 
                      INNER JOIN CONSINCO.GE_PESSOA G         ON G.SEQPESSOA = A.SEQPESSOA
                      LEFT JOIN  CONSINCO.OR_REQUISICAO R     ON R.SEQREQUISICAO = A.REQUISICOES
                      
 WHERE A.SEQPESSOA = :NR1 
   AND DTAENTRADA BETWEEN :DT1 AND :DT2
   AND DECODE(R.STATUS, 'A',' Aguardando Autorização','F','Finalizada','L','Liberada','R','Rejeitada') IN (#LS1)
   
   ORDER BY 3
   
   /* Old
   
   SELECT TO_CHAR(DTAENTRADA, 'MM') MES, TO_CHAR(DTAENTRADA, 'W') SEMANA, A.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, 
       Y.SEQPRODUTO||' - '||DESCCOMPLETA PRODUTO, 
       ROUND(SUM(X.VLRTOTAL) / SUM(QUANTIDADE),2) VLR_UNIT_PROD, SUM(X.VLRTOTAL) VLR_TOTAL_PROD, SUM(TO_NUMBER(QUANTIDADE)) QTD_PROD
       
  FROM OR_NFDESPESA A INNER JOIN CONSINCO.OR_NFITENSDESPESA X ON X.SEQNOTA      = A.SEQNOTA
                      INNER JOIN CONSINCO.MAP_PRODUTO Y       ON X.CODPRODUTO   = Y.SEQPRODUTO 
                      INNER JOIN CONSINCO.GE_PESSOA G         ON G.SEQPESSOA = A.SEQPESSOA
                      
 WHERE A.SEQPESSOA = :NR1 
   AND DTAENTRADA BETWEEN :DT1 AND :DT2
   
   GROUP BY TO_CHAR(DTAENTRADA, 'MM'), TO_CHAR(DTAENTRADA, 'W'), A.SEQPESSOA||' - '||G.NOMERAZAO, 
            Y.SEQPRODUTO||' - '||DESCCOMPLETA
   
   ORDER BY 1,4,2
   
   */
