ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT SEQPRODUTO PLU, DESCCOMPLETA DESCRICAO, 
       CATEGORIAN1, CATEGORIAN2, CATEGORIAN3, CATEGORIAN4, CATEGORIAN5
  FROM MAP_PRODUTO X INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = X.SEQFAMILIA
 
WHERE DESCCOMPLETA LIKE UPPER('%'||NVL(:LT1, 'XXXXXXXXX')||'%')
   OR X.SEQPRODUTO = NVL(:NR1, 9999999999)
   OR EXISTS (SELECT 1 
                FROM MAP_PRODCODIGO PC 
               WHERE PC.TIPCODIGO = 'E' 
                 AND PC.CODACESSO = NVL(:NR2, 999999) 
                 AND PC.SEQPRODUTO = X.SEQPRODUTO)

ORDER BY 2 ASC
