ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT TO_CHAR(DTAENTRADA, 'MM') MES, TO_CHAR(DTAENTRADA, 'W') SEMANA, A.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, 
       Y.SEQPRODUTO||' - '||DESCCOMPLETA PRODUTO, 
       ROUND(SUM(X.VLRTOTAL) / SUM(QUANTIDADE),2) VLR_UNIT_PROD, SUM(X.VLRTOTAL) VLR_TOTAL_PROD, SUM(TO_NUMBER(QUANTIDADE)) QTD_PROD
       
  FROM OR_NFDESPESA A INNER JOIN CONSINCO.OR_NFITENSDESPESA X ON X.SEQNOTA      = A.SEQNOTA
                      INNER JOIN CONSINCO.MAP_PRODUTO Y       ON X.CODPRODUTO   = Y.SEQPRODUTO 
                      INNER JOIN CONSINCO.GE_PESSOA G         ON G.SEQPESSOA = A.SEQPESSOA
                      
 WHERE A.SEQPESSOA = 1100644 
   AND DTAENTRADA BETWEEN DATE '2024-01-01' AND DATE '2024-03-31'
   
   GROUP BY TO_CHAR(DTAENTRADA, 'MM'), TO_CHAR(DTAENTRADA, 'W'), A.SEQPESSOA||' - '||G.NOMERAZAO, 
            Y.SEQPRODUTO||' - '||DESCCOMPLETA
   
   ORDER BY 1,4,2
