SELECT X.SEQGERCOMPRA LOTE, X.DTAHORINCLUSAO, X.USUINCLUSAO, TO_CHAR(DTAGERPEDIDO, 'DD/MM/YYYY') DTAGERPEDIDO, USUGERPEDIDO,
       DESCRITIVO, 'MARKETING' COMPRADOR, Z.SEQFORNECEDOR||' - '||(SELECT NOMERAZAO FROM CONSINCO.GE_PESSOA G WHERE G.SEQPESSOA = Z.SEQFORNECEDOR) FORNECEDOR,  
       TO_CHAR(SUM(QTDPEDIDA  * TFVALORTOTALNF), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_TOTAL
 
  FROM CONSINCO.MAC_GERCOMPRA X LEFT JOIN CONSINCO.MAC_GERCOMPRAFORN Z ON Z.SEQGERCOMPRA = X.SEQGERCOMPRA
                                LEFT JOIN CONSINCO.MAC_GERCOMPRAITEM I ON X.SEQGERCOMPRA = I.SEQGERCOMPRA
 WHERE 1=1
   AND X.SITUACAOLOTE != 'C'
   AND X.SEQCOMPRADOR = 290 
   AND X.DTAHORINCLUSAO BETWEEN SYSDATE - 5 AND SYSDATE
   
   GROUP BY X.SEQGERCOMPRA, X.DTAHORINCLUSAO, X.USUINCLUSAO, DTAGERPEDIDO, USUGERPEDIDO, DESCRITIVO, Z.SEQFORNECEDOR
   
