SELECT /*+ PARALLEL(8) */ X.SEQPRODUTO PLU, Y.DESCCOMPLETA,
       SUM(X.QTDOPERACAO) QTY, SUM(X.VLROPERACAO) VLR
          
FROM FATOG_VENDADIA X INNER JOIN CONSINCO.MAP_PRODUTO Y ON (X.SEQPRODUTO = Y.SEQPRODUTO)
                           
WHERE 1=1

AND X.DTAOPERACAO >= SYSDATE  - (365 * 2)
AND EXISTS (SELECT 1 FROM MAP_FAMILIA F INNER JOIN MAP_MARCA Z ON Z.SEQMARCA = F.SEQMARCA AND Z.MARCA = 'NAGUMO' AND Z.STATUS = 'A' AND F.SEQFAMILIA = Y.SEQFAMILIA )
AND CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911,76)

GROUP BY X.SEQPRODUTO, DESCCOMPLETA;

