CREATE OR REPLACE VIEW CONSINCO.NAGF_ANALISEGERCOMPRA AS

SELECT B.NROEMPRESA, A.SEQGERCOMPRA NROLOTE, C.SEQFORNECEDOR, F.NOMERAZAO FORNECEDOR,
       B.SEQPRODUTO, D.DESCCOMPLETA DESCRICAO, E.COMPRADOR,
       B.EMBCOMPRA, TO_NUMBER(QTDEMBALAGEM) QTD_EMB, NVL(B.QTDPEDIDA / B.QTDEMBALAGEM,0) QTDPEDIDA, NVL(TO_NUMBER(B.QTDPEDIDA),0) QTDPEDIDA_UNI, NVL(TO_NUMBER(B.ESTQATUAL),0) ESTOQUE,
       NVL(TO_NUMBER(B.QTDPEDIDA),0) + NVL(TO_NUMBER(B.ESTQATUAL),0) TOTAL
       
  FROM CONSINCO.MAC_GERCOMPRA A INNER JOIN CONSINCO.MAC_GERCOMPRAITEM B ON A.SEQGERCOMPRA = B.SEQGERCOMPRA
                                INNER JOIN CONSINCO.MAC_GERCOMPRAFORN C ON A.SEQGERCOMPRA = C.SEQGERCOMPRA
                                INNER JOIN CONSINCO.MAP_PRODUTO D       ON B.SEQPRODUTO   = D.SEQPRODUTO
                                INNER JOIN CONSINCO.MAX_COMPRADOR E     ON E.SEQCOMPRADOR = A.SEQCOMPRADOR
                                INNER JOIN CONSINCO.GE_PESSOA F         ON F.SEQPESSOA    = C.SEQFORNECEDOR
 WHERE 1=1
   AND A.SITUACAOLOTE = 'F'
   AND A.DTAGERPEDIDO BETWEEN SYSDATE - 90 AND SYSDATE

ORDER BY A.SEQGERCOMPRA, B.SEQPRODUTO, NROEMPRESA;
 
SELECT * FROM CONSINCO.NAGF_ANALISEGERCOMPRA X WHERE X.SEQFORNECEDOR = 115204
