CREATE OR REPLACE VIEW NAGV_APURACAO_LAYOUT_FIS_CAT28 AS

SELECT X.NROEMPRESA, X.SEQPRODUTO PLU, P.DESCCOMPLETA, F.CODNBMSH NCM, F.CODCEST, X.QUANTIDADEESTOQUE QTD_ESTQ, 
       SUM(X.QTDNF) QTD_UTIL_APUR, SUM((XI.VLRITEM / XI.QTDECONFERIDA) * X.QTDNF) VLR_TOT_MERC,
       SUM(X.BASCALCICMSST) BASECALCICMSST, SUM(X.VALORDOCREDITO) VLR_CREDITO, MAX(X.PERCREDCICMSST) PERCICMSST, MAX(X.DTAATUALIZACUSTO) DTA
       
  FROM MRL_NFAPURAIMPOSTO X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO
                            INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                            INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF AND XI.SEQPRODUTO = X.SEQPRODUTO
  WHERE 1=1
  GROUP BY X.NROEMPRESA, X.SEQPRODUTO, P.DESCCOMPLETA, F.CODNBMSH, F.CODCEST, X.QUANTIDADEESTOQUE
