CREATE OR REPLACE VIEW CONSINCO.NAGV_LIMITECOMPRADOR AS
SELECT SEQCOMPRADOR, NVL(VLRLIMITE,0) LIMITE, NVL(VLRUTILIZADO,0) VLRUTILIZADO, NVL(VALORLIBERADOSENHA,0) VALORLIBERADOSENHA, NVL(VLRUTILIZADO,0) + NVL(VALORLIBERADOSENHA,0) VLRTOTALUTIL,
       NVL(VLRLIMITE,0) - (NVL(VLRUTILIZADO,0) + NVL(VALORLIBERADOSENHA,0))VLRDISPONIVEL
  FROM (
SELECT SEQCOMPRADOR, VLRLIMITE, VLRUTILIZADO, (SELECT SUM(X.VLRITEM) FROM CONSINCO.MLF_AUXNFINCONSISTENCIA Y INNER JOIN CONSINCO.MLF_AUXNFITEM X ON Y.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
                                                                                                             INNER JOIN CONSINCO.MAP_PRODUTO M ON X.SEQPRODUTO = M.SEQPRODUTO
                                                                                                             INNER JOIN CONSINCO.MAP_FAMDIVISAO F ON F.SEQFAMILIA = M.SEQFAMILIA
                                                WHERE Y.CODINCONSIST IN (7)
                                                  AND Y.AUTORIZADA    = 'S'
                                                  AND Y.TIPOINCONSIST = 'P'
                                                  AND Y.DTAAUTORIZOU BETWEEN XX.DTAINICIO AND XX.DTAFIM
                                                  AND F.SEQCOMPRADOR  = XX.SEQCOMPRADOR
                                              ) VALORLIBERADOSENHA
  FROM CONSINCO.MAC_LIMCOMPRACOMPRADOR XX

 WHERE 1=1
   AND SYSDATE BETWEEN DTAINICIO AND DTAFIM
   AND NVL(VLRLIMITE,0) > 0

 ORDER BY 1);
