-- ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_DASH_ENCARTES AS

-- Giuliano em 20/03/2025
-- Dashboard Adriana/Ronie

SELECT X.SEQENCARTE, DESCRICAO, E.NROEMPRESA, P.SEQPRODUTO, 
       DTA DTA_DIA,  NVL(P.DTAVIGENCIAINI, X.DTAINICIO) INICIO, NVL(P.DTAVIGENCIAFIM, X.DTAFIM) FIM
       
  FROM MRL_ENCARTE X INNER JOIN MRL_ENCARTEEMP E           ON E.SEQENCARTE = X.SEQENCARTE
                     INNER JOIN MAX_EMPRESA M              ON M.NROEMPRESA = E.NROEMPRESA
                      LEFT JOIN MRL_ENCARTEPRODUTO P       ON P.SEQENCARTE = X.SEQENCARTE  
                      LEFT JOIN MRL_ENCARTEPRODUTOPRECO PP ON PP.SEQENCARTE = X.SEQENCARTE
                     INNER JOIN DIM_TEMPO T                ON DTA BETWEEN NVL(P.DTAVIGENCIAINI, X.DTAINICIO) AND NVL(P.DTAVIGENCIAFIM, X.DTAFIM)
                     
 WHERE  1=1--X.SEQENCARTE = 27260
  /* Confere se realmente existe promocao */
   AND EXISTS (SELECT 1 FROM MRL_PROMOCAO PR INNER JOIN MRL_PROMOCAOITEM PI ON PI.SEQPROMOCAO = PR.SEQPROMOCAO
                WHERE PR.NROEMPRESA = E.NROEMPRESA
                  AND (PI.SEQPRODUTO = P.SEQPRODUTO OR PI.SEQPRODUTO = PP.SEQPRODUTO) -- Existe na P ou PP
                  AND PI.STATUS != 'I'
                  AND PI.PRECOPROMOCIONAL > 0
                  AND DTA BETWEEN NVL(PI.DTAINICIOPROM, PR.DTAINICIO) AND NVL(PI.DTAFIMPROM, PR.DTAFIM)) -- Valida cada dia se esta em vigor entre o periodo da promocao
  /* Apenas com preços promocionais */
   AND COALESCE(NULLIF(PP.PRECOPROMOC,0), P.PRECOPROMOCIONAL) >= 0
  
                
ORDER BY 5,4,3;

