SELECT G.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, P.SEQPRODUTO PLU, DESCCOMPLETA DESCRICAO, C.CODACESSO COD_INTERNO
  FROM MAP_PRODUTO P INNER JOIN MAP_FAMFORNEC F ON F.SEQFAMILIA = P.SEQFAMILIA
                     INNER JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = P.SEQPRODUTO AND TIPCODIGO = 'B'
                     INNER JOIN GE_PESSOA G ON G.SEQPESSOA = F.SEQFORNECEDOR
                     
 WHERE F.SEQFORNECEDOR = :NR1
