ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT CASE WHEN ODR1 = 1 THEN PLU_FINAL ELSE NULL END PLU_FINAL,
         CASE WHEN ODR1 = 1 THEN PRODUTOFINAL ELSE NULL END PRODUTOFINAL,
           CASE WHEN ODR1 = 1 THEN TO_CHAR(QTD_FINAL,'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''') ELSE NULL END QTD_FINAL,
             CASE WHEN ODR1 = 1 THEN PLU_COMP ELSE NULL END PLU_COMPONENTE,
               CASE WHEN ODR1 = 1 THEN PRODUTOCOMP ELSE NULL END PRODUTOCOMP,
                 CASE WHEN ODR1 = 1 THEN TO_CHAR(QTD_COMP,'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''') ELSE NULL END QTD_COMP,
                   CASE WHEN ODR1 = 1 THEN TO_CHAR(QTDUNIDPRODUZIDA,'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''') ELSE NULL END QTD_PROD,
                     PLU_COMPREC, PROD_RECEITA, TO_CHAR(QTD_REC,'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''') QTD_PRODREC
 FROM (

SELECT X.SEQPRODUTOFINAL PLU_FINAL, X.PRODUTOFINAL, X.QTDUNIDPRODUZIDA QTD_FINAL, X.SEQPRODUTOCOMP PLU_COMP, X.PRODUTOCOMP, X.QTDUTILIZADA QTD_COMP, Z.SEQPRODUTOCOMP PLU_COMPREC, Z.PRODUTOCOMP PROD_RECEITA, Z.QTDUTILIZADA QTD_REC, Z.QTDUNIDPRODUZIDA,
       ROW_NUMBER() OVER(PARTITION BY Z.SEQPRODUTOFINAL ORDER BY Z.SEQPRODUTOFINAL) ODR1
  FROM MRLV_COMPONENTESRECEITA X LEFT JOIN MRLV_COMPONENTESRECEITA Z ON X.SEQPRODUTOCOMP = Z.SEQPRODUTOFINAL AND X.NROEMPRESA = Z.NROEMPRESA
  
 WHERE X.SEQPRODUTOFINAL = 81030 AND X.NROEMPRESA = 8 ) ;
 
-- SELECT * FROM MRLV_COMPONENTESRECEITA X WHERE X.SEQRECEITARENDTO = 928 AND NROEMPRESA = 8
