ALTER SESSION SET current_schema = CONSINCO;


SELECT DISTINCT D.DESCRICAO, D.SEQFILTRO 


FROM FI_DDAREGRADETALHE A LEFT JOIN FI_DDAREGRA C ON A.SEQREGRA = C.SEQREGRA
                          LEFT JOIN FI_DDAFILTRO D ON C.SEQFILTRO = D.SEQFILTRO
                          LEFT JOIN FI_DDAVARIAVEL B ON A.SEQVARIAVEL = B.SEQVARIAVEL
                          
                          WHERE D.SEQFILTRO NOT IN (


SELECT DISTINCT D.SEQFILTRO

FROM FI_DDAREGRADETALHE A LEFT JOIN FI_DDAREGRA C ON A.SEQREGRA = C.SEQREGRA
                          LEFT JOIN FI_DDAFILTRO D ON C.SEQFILTRO = D.SEQFILTRO
                          LEFT JOIN FI_DDAVARIAVEL B ON A.SEQVARIAVEL = B.SEQVARIAVEL
       
WHERE B.DESCRICAO LIKE '%RAIZ%'
) 
AND D.DESCRICAO != '1 BLOQUEADO'
ORDER BY 1 ASC
