ALTER SESSION SET current_schema = CONSINCO;

SELECT F.SEQPESSOA CODFORNEC, GE.NOMERAZAO, F.SEQFILTRODDA FROM FI_FORNECEDOR F LEFT JOIN GE_PESSOA GE ON F.SEQPESSOA = GE.SEQPESSOA
       WHERE F.SEQFILTRODDA IS NOT NULL AND F.SEQFILTRODDA != 0 
       AND SEQFILTRODDA NOT IN (SELECT DISTINCT FD.SEQFILTRO FROM  FI_DDAFILTRO FD
                                WHERE SEQFILTRO IN (
                                SELECT SEQFILTRO FROM FI_DDAREGRA)) ORDER BY 2
