SELECT M.FANTASIA EMPRESA,
       CASE WHEN F.NRODOCUMENTO||' - '||F.SERIEDOC = F.NROTITULO||' - '||F.SERIETITULO THEN F.NRODOCUMENTO||' - '||F.SERIEDOC ELSE F.NRODOCUMENTO||' - '||F.SERIEDOC||' -  Tít.: '||F.NROTITULO||' - '||F.SERIETITULO END DOCUMENTO,
       F.CODESPECIE, F.SEQPESSOA||' - '||G.NOMERAZAO FORNECEDOR, 
       CASE WHEN EXISTS (SELECT * FROM FI_AUTORIZACAO 
	WHERE	FI_AUTORIZACAO.TABLINK = 'TIT' 
		AND FI_AUTORIZACAO.CODLINK = F.SEQTITULO 
		AND FI_AUTORIZACAO.VALOR = P.VLRPAGAR) THEN 'Assinada - Arquivo Não Gerado' ELSE 'Não Assinada' END STATUS,
       TO_CHAR(F.DTAPROGRAMADA, 'DD-MM-YYYY') DATA_PROGRAMADA, 
       TO_CHAR(F.VLRNOMINAL, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRNOMINAL, 
       TO_CHAR(P.VLRPAGAR,   'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRLIQUIDO, PG.GEROUARQUIVO
 
 FROM CONSINCO.FI_TITULO F LEFT JOIN CONSINCO.GE_PESSOA G        ON F.SEQPESSOA  = G.SEQPESSOA
                           LEFT JOIN CONSINCO.GE_EMPRESA M       ON F.NROEMPRESA = M.NROEMPRESA
                           LEFT JOIN CONSINCO.FI_PROGPAGAMENTO P ON F.SEQTITULO  = P.SEQTITULO
                           LEFT JOIN CONSINCO.FI_PAGTOELETR PG   ON P.SEQENVIO   = PG.SEQENVIO

WHERE P.FORMAPAGTO = 'EL' 
  AND P.DTAPROGRAMACAO BETWEEN :DT1 AND :DT2
  AND EXISTS (  
      SELECT  1 
      FROM  CONSINCO.FI_AUTPAGTO
      WHERE   FI_AUTPAGTO.SEQTITULO = F.SEQTITULO)                   
  AND NVL(P.SITUACAO,'N') = 'N'
  
  AND (
   NOT EXISTS ( SELECT * FROM CONSINCO.FI_PAGTOELETR
   WHERE FI_PAGTOELETR.TABLINK = 'TIT'
     AND FI_PAGTOELETR.CODLINK = F.SEQTITULO 
     AND FI_PAGTOELETR.GEROUARQUIVO = 'S'  
     AND NOT EXISTS ( SELECT 1
            FROM  FI_RETPAGTOELETR X 
            WHERE X.SEQENVIO = FI_PAGTOELETR.SEQENVIO 
              AND X.TIPOMOVIMENTO = 'EST' 
              AND X.ATUALIZOURET = 'S'))
              AND F.SEQTITULO IN 
                 (SELECT SEQTITULO 
                  FROM FI_COMPLTITULO  
                  WHERE (PAGTOBOLETO = 'S' OR PAGTOBOLETO IS NULL))
   OR 
   NOT EXISTS( SELECT  1 
   FROM  CONSINCO.FI_PAGTOELETR 
   WHERE P.SEQENVIO = FI_PAGTOELETR.SEQENVIO
     AND FI_PAGTOELETR.GEROUARQUIVO IS NOT NULL) 
     AND F.SEQTITULO IN ( SELECT SEQTITULO 
           FROM  FI_COMPLTITULO 
           WHERE PAGTOBOLETO = 'N' 
             AND FI_COMPLTITULO.TIPOPAGAMENTO   NOT IN  ('TRI', 'TRB' ) 
             AND FI_COMPLTITULO.FORMAPAGAMENTO NOT IN ('PXT', 'PXQ'))   
   OR
   NOT EXISTS( SELECT  1 
   FROM  CONSINCO.FI_PAGTOELETR 
   WHERE P.SEQENVIO = FI_PAGTOELETR.SEQENVIO 
     AND FI_PAGTOELETR.GEROUARQUIVO IS NOT NULL) 
     AND F.SEQTITULO IN ( SELECT SEQTITULO 
          FROM  FI_COMPLTITULO 
          WHERE PAGTOBOLETO = 'N' 
            AND FI_COMPLTITULO.TIPOPAGAMENTO   IN  ('TRI', 'TRB' ))
   OR
   NOT EXISTS( SELECT  1 
   FROM  CONSINCO.FI_PAGTOELETR 
   WHERE P.SEQENVIO = FI_PAGTOELETR.SEQENVIO 
     AND FI_PAGTOELETR.GEROUARQUIVO IS NOT NULL) 
     AND F.SEQTITULO IN ( SELECT SEQTITULO 
          FROM  FI_COMPLTITULO
          WHERE PAGTOBOLETO = 'N' 
            AND FI_COMPLTITULO.TIPOPAGAMENTO   NOT IN  ('TRI', 'TRB' )  
            AND FI_COMPLTITULO.FORMAPAGAMENTO IN ('PXT', 'PXQ'))
   );
