SELECT * FROM  FI_DDAFILTRO 
WHERE SEQFILTRO IN (
SELECT SEQFILTRO FROM FI_DDAREGRA WHERE
SEQREGRA IN (SELECT SEQREGRA FROM FI_LOGREGRADDAUTIL WHERE SEQTITULO = 
(SELECT SEQTITULO FROM FI_TITULO FI WHERE NRODOCUMENTO = &DOC
                                      AND NROEMPRESA   = &EMP
                                      AND FI.DTAVENCIMENTO = &DTA)))
