SELECT X.NRONOTA, X.NROEMPRESA EMPRESA, X.SEQPESSOA||' - '||
      (SELECT NOMERAZAO FROM GE_PESSOA WHERE SEQPESSOA = X.SEQPESSOA) FORNECEDOR, 
       NVL(Z.MOTIVO, 'Inconsistência não identificada') INCONSISTENCIA,X.USUINCLUSAO USUARIO_INCLUSAO, 
       TO_CHAR(X.DTAINCLUSAO, 'DD/MM/YYYY') DATA_INCLUSAO 

  FROM CONSINCO.OR_NFDESPESA X LEFT JOIN CONSINCO.OR_NFDESPESAINCONSIST Z ON X.SEQNOTA = Z.SEQNOTA

 WHERE Z.DTAASSINOU IS NULL   
   AND X.SITUACAO != 'I' 
   AND DTAINCLUSAO BETWEEN :DT1 AND :DT2
   AND X.NROEMPRESA IN (#LS1) 
 
 ORDER BY 2,1
