ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT E.FANTASIA LOJA, NRONOTA TITULO, NOMERAZAO RAZAO_FORNECEDOR, 
       TO_CHAR(X.DTAVENCINICIAL, 'DD/MM/YYYY') VENCIMENTO, 
       TO_CHAR(X.VALOR, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR, 
       COMPRADOR APROVADOR
       
  FROM OR_NFDESPESA X INNER JOIN GE_PESSOA Z ON X.SEQPESSOA = Z.SEQPESSOA
                      INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = X.NROEMPRESA
                      INNER JOIN OR_REQUISICAO C ON C.NROREQUISICAO = X.REQUISICOES
                      INNER JOIN MAX_COMPRADOR B ON B.SEQCOMPRADOR = C.SEQCOMPRADOR
                      
 WHERE 1=1
   AND X.DTAVENCINICIAL = :DT1
   AND X.NROEMPRESA != 601
   AND COMPRADOR IN (#LS1)
