ALTER SESSION SET current_schema = CONSINCO;

SELECT SITUACAO, A.* FROM CONSINCO.OR_NFDESPESA A WHERE  A.NROEMPRESA = 506 AND A.SEQPESSOA = 117169--.SEQNOTA = 550591

SELECT * FROM LOG_NFDESPESA C WHERE C.SEQNOTA = 550591--IN (SELECT A.SEQNOTA FROM CONSINCO.OR_NFDESPESA A WHERE  A.NROEMPRESA = 506 AND A.SEQPESSOA = 117169)
