ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT X.NRONOTA, X.NROEMPRESA EMPRESA, X.SEQPESSOA||' - '||
      (SELECT NOMERAZAO FROM GE_PESSOA WHERE SEQPESSOA = X.SEQPESSOA) FORNECEDOR, 
       Z.MOTIVO INCONSISTENCIA,X.USUINCLUSAO USUARIO_INCLUSAO, 
       TO_CHAR(X.DTAINCLUSAO, 'DD/MM/YYYY') DATA_INCLUSAO

  FROM OR_NFDESPESA X INNER JOIN OR_NFDESPESAINCONSIST Z ON X.SEQNOTA = Z.SEQNOTA

 WHERE Z.DTAASSINOU IS NULL
   AND X.NROEMPRESA IN (#LS1)
 
 ORDER BY 2,1
