SELECT NROCHECKOUT, X.NUMERODF, X.DTAHOREMISSAO
  FROM MFL_DOCTOFISCAL X INNER JOIN MFL_DFITEM Z ON X.NUMERODF = Z.NUMERODF  AND Z.NROEMPRESA = X.NROEMPRESA  AND Z.SEQNF = X.SEQNF
 WHERE X.NROEMPRESA  =   '1'                             
   AND SEQPRODUTO = 243810  
  -- AND NVL(STATUSDF, 'V')  !=  'C'
ORDER BY X.DTAMOVIMENTO DESC
  
