SELECT DISTINCT A.SEQPRODUTO, B.DESCCOMPLETA, A.QTDEMBALAGEM,
       NVL(COALESCE(NVL(H.PRECOANTNORMAL,A.PRECOANTERIORPERIODO), CONSINCO.FMAD_PRECOPROGDATA(A.SEQPRODUTO, A.QTDEMBALAGEM, A.NROSEGMENTO, A.NROEMPRESA, A.DTAPROGALTERACAO - 1) ), 0) PRECO_ANTERIOR,
      D.PRECOVALIDNORMAL PRECO_NORMAL,
      D.PRECOVALIDPROMOC PRECO_PROMOCIONAL,
       DECODE(NVL(H.PRECOVALIDPROMOC, D.PRECOVALIDPROMOC), 0, NVL(H.PRECOVALIDNORMAL, D.PRECOVALIDNORMAL), NVL(H.PRECOVALIDPROMOC, D.PRECOVALIDPROMOC)) PRECOATUAL,
       TO_CHAR(A.DTAHORALTERACAO, 'DD/MM/YYYY HH24:MI') DATA_ALTERACAO,
       TO_CHAR(( SELECT MAX(P.DTAINICIO)
         FROM    CONSINCO.MRLV_PROMOCAOITEM P
         WHERE   P.SEQPRODUTO = D.SEQPRODUTO
         AND     D.NROEMPRESA        =           P.NROEMPRESA
         AND     D.NROSEGMENTO       =           P.NROSEGMENTO
         AND     D.QTDEMBALAGEM      =           P.QTDEMBALAGEM
         AND     NVL(TRUNC(H.DTAPROGALTERACAO), TRUNC(D.DTAGERACAOPRECO))   BETWEEN P.DTAINICIO AND P.DTAFIM
       ), 'DD/MM/YYYY HH24:MI') DATA_INICIO_PROMO,
       TO_CHAR(( SELECT MAX(P.DTAFIM)
         FROM    CONSINCO.MRLV_PROMOCAOITEM P
         WHERE   P.SEQPRODUTO = D.SEQPRODUTO
         AND     D.NROEMPRESA        =           P.NROEMPRESA
         AND     D.NROSEGMENTO       =           P.NROSEGMENTO
         AND     D.QTDEMBALAGEM      =           P.QTDEMBALAGEM
         AND     NVL(TRUNC(H.DTAPROGALTERACAO), TRUNC(D.DTAGERACAOPRECO))   BETWEEN P.DTAINICIO AND P.DTAFIM
       ), 'DD/MM/YYYY HH24:MI') DATA_FIM_PROMO,
       TO_CHAR(( SELECT MAX(P.DTAGERACAO)
         FROM    CONSINCO.MRLV_PROMOCAOITEM P
         WHERE   P.SEQPRODUTO = D.SEQPRODUTO
         AND     D.NROEMPRESA        =           P.NROEMPRESA
         AND     D.NROSEGMENTO       =           P.NROSEGMENTO
         AND     D.QTDEMBALAGEM      =           P.QTDEMBALAGEM
         AND     NVL(TRUNC(H.DTAPROGALTERACAO), TRUNC(D.DTAGERACAOPRECO))   BETWEEN P.DTAINICIO AND P.DTAFIM
       ), 'DD/MM/YYYY HH24:MI') DATA_GERACAO,
       TO_CHAR(( SELECT MAX(P.DTAINCLUSAO)
         FROM    CONSINCO.MRLV_PROMOCAOITEM P
         WHERE   P.SEQPRODUTO = D.SEQPRODUTO
         AND     D.NROEMPRESA        =           P.NROEMPRESA
         AND     D.NROSEGMENTO       =           P.NROSEGMENTO
         AND     D.QTDEMBALAGEM      =           P.QTDEMBALAGEM
         AND     NVL(TRUNC(H.DTAPROGALTERACAO), TRUNC(D.DTAGERACAOPRECO))   BETWEEN P.DTAINICIO AND P.DTAFIM
       ), 'DD/MM/YYYY HH24:MI') DATA_INCLUSAO
       
FROM   CONSINCO.MAD_PRODLOGPRECO A,   CONSINCO.MAP_PRODUTO B,
       CONSINCO.MAP_FAMILIA C,        CONSINCO.MRL_PRODEMPSEG D,
       CONSINCO.MAP_FAMEMBALAGEM E,   CONSINCO.MRL_PRODUTOEMPRESA F,
       CONSINCO.MRLX_PRODEMPSEGDATA H,CONSINCO.MRL_GONDOLA I, 
       CONSINCO.MAX_EMPRESA M
       
WHERE  B.SEQPRODUTO        =           A.SEQPRODUTO
AND    C.SEQFAMILIA        =           B.SEQFAMILIA
AND    D.SEQPRODUTO        =           A.SEQPRODUTO
AND    D.QTDEMBALAGEM      =           A.QTDEMBALAGEM
AND    D.NROSEGMENTO       =           A.NROSEGMENTO
AND    D.NROEMPRESA        =           A.NROEMPRESA
AND    E.SEQFAMILIA        =           B.SEQFAMILIA
AND    E.QTDEMBALAGEM      =           A.QTDEMBALAGEM
AND    F.SEQPRODUTO        =           A.SEQPRODUTO
AND    F.NROEMPRESA        =           A.NROEMPRESA
AND    D.SEQPRODUTO        =           H.SEQPRODUTO(+)
AND    D.QTDEMBALAGEM      =           H.QTDEMBALAGEM(+)
AND    D.NROEMPRESA        =           H.NROEMPRESA(+)
AND    D.NROSEGMENTO       =           H.NROSEGMENTO(+)

AND    I.NROEMPRESA = A.NROEMPRESA
AND    I.NROGONDOLA = F.NROGONDOLA
AND    M.NROEMPRESA = A.NROEMPRESA
AND    M.NROSEGMENTOPRINC = A.NROSEGMENTO
AND    A.NROEMPRESA IN (#LS1)
AND    A.DTAHORALTERACAO BETWEEN TO_DATE('#LT1', 'DD/MM/YYYY HH24:MI') AND TO_DATE('#LT2', 'DD/MM/YYYY HH24:MI')
AND    A.QTDEMBALAGEM = 1
AND NVL( APROVADOREPROVADO, 'A' ) = 'A'

ORDER BY 2
