ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT A.SEQPRODUTO, B.CODACESSO EAN, A.DESCCOMPLETA DESCRICAO, TRIM(A.QTDEMBALAGEM) QTDEMBALAGEM,
       NVL(CONSINCO.FMAD_PRECOPROGDATA(A.SEQPRODUTO, A.QTDEMBALAGEM, A.NROSEGMENTO, A.NROEMPRESA, A.DTAGERACAOPRECO -2), 0) PRECO_ANTERIOR,
       PRECOVALIDNORMAL PRECO_NORMAL,
       PRECOVALIDPROMOC PRECO_PROMOCIONAL,
       DECODE(PRECOVALIDPROMOC,'0',PRECOVALIDNORMAL,PRECOVALIDPROMOC) PRECOATUAL,
       NULL i,
       TO_CHAR(( SELECT MAX(P.DTAINICIO)
         FROM    CONSINCO.MRLV_PROMOCAOITEM P
         WHERE   P.SEQPRODUTO = A.SEQPRODUTO
         AND     A.NROEMPRESA        =           P.NROEMPRESA
         AND     A.NROSEGMENTO       =           P.NROSEGMENTO
         AND     A.QTDEMBALAGEM      =           P.QTDEMBALAGEM
         AND     TRUNC(A.DTAGERACAOPRECO)   BETWEEN P.DTAINICIO AND P.DTAFIM
       ), 'DD/MM/YYYY') DATA_INICIO_PROMO,
       TO_CHAR(( SELECT MAX(P.DTAFIM)
         FROM    CONSINCO.MRLV_PROMOCAOITEM P
         WHERE   P.SEQPRODUTO = A.SEQPRODUTO
         AND     A.NROEMPRESA        =           P.NROEMPRESA
         AND     A.NROSEGMENTO       =           P.NROSEGMENTO
         AND     A.QTDEMBALAGEM      =           P.QTDEMBALAGEM
         AND     TRUNC(A.DTAGERACAOPRECO)   BETWEEN P.DTAINICIO AND P.DTAFIM
       ), 'DD/MM/YYYY') DATA_FIM_PROMO,
       TO_CHAR(( SELECT MAX(P.DTAINCLUSAO)
         FROM    CONSINCO.MRLV_PROMOCAOITEM P
         WHERE   P.SEQPRODUTO = A.SEQPRODUTO
         AND     A.NROEMPRESA        =           P.NROEMPRESA
         AND     A.NROSEGMENTO       =           P.NROSEGMENTO
         AND     A.QTDEMBALAGEM      =           P.QTDEMBALAGEM
         AND     TRUNC(A.DTAGERACAOPRECO)   BETWEEN P.DTAINICIO AND P.DTAFIM
       ), 'DD/MM/YYYY HH24:MI') DATA_INCLUSAO,
       TO_CHAR(NVL(( SELECT MAX(P.DTAGERACAO)
         FROM    CONSINCO.MRLV_PROMOCAOITEM P
         WHERE   P.SEQPRODUTO = A.SEQPRODUTO
         AND     A.NROEMPRESA        =           P.NROEMPRESA
         AND     A.NROSEGMENTO       =           P.NROSEGMENTO
         AND     A.QTDEMBALAGEM      =           P.QTDEMBALAGEM
         AND     TRUNC(A.DTAGERACAOPRECO)   BETWEEN P.DTAINICIO AND P.DTAFIM
        ),A.DTAGERACAOPRECO), 'DD/MM/YYYY HH24:MI') DATA_GERACAO,
       'De: '||'#LT1'||' Até: '||'#LT2' PERIODO,
       #LS1 EMPRESA

  FROM MRLV_BASEETIQUETAPROD A LEFT JOIN CONSINCO.MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO AND B.TIPCODIGO = 'E'
  
 WHERE NROEMPRESA  IN (#LS1)                               
   AND NROSEGMENTO IN (SELECT X.NROSEGMENTOPRINC FROM MAX_EMPRESA X WHERE X.NROEMPRESA IN (#LS1))              
   AND A.QTDEMBALAGEM  = 1                  
   AND STATUSVENDA   = 'A'  
   AND DECODE(PRECOGERPROMOC, 0, PRECOGERNORMAL, PRECOGERPROMOC)  > 0  
   AND DTAGERACAOPRECO BETWEEN TO_DATE('#LT1', 'DD/MM/YYYY HH24:MI') AND TO_DATE('#LT2', 'DD/MM/YYYY HH24:MI')                                  
   AND DECODE(PRECOGERPROMOC, 0, PRECOGERNORMAL, PRECOGERPROMOC) = DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC)
   AND NVL(CONSINCO.FMAD_PRECOPROGDATA(A.SEQPRODUTO, A.QTDEMBALAGEM, A.NROSEGMENTO, A.NROEMPRESA, A.DTAGERACAOPRECO -2), 0) != DECODE(PRECOVALIDPROMOC,'0',PRECOVALIDNORMAL,PRECOVALIDPROMOC) 
   
 ORDER BY 3 ASC
