-- Monitoramento de Exportacao & Cargas PDV

SELECT 'Monitor - TotalPendenteImportacao' EXPORTACAO_CARGA,
       COUNT(1) QTDE,
       MAX(DTAHOREMISSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_CONTROLEMOVIMENTO
 WHERE STATUS < 2
UNION ALL
SELECT 'Monitor - TotalFALHAImportacao' EXPORTACAO_CARGA,
       COUNT(1) QTDE,
       MAX(DTAHOREMISSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_CONTROLEMOVIMENTO
 WHERE STATUS > 2
UNION ALL
SELECT 'Monitor - TotalIntegrado',
       COUNT(1) QTDE,
       MAX(DTAHORINCLUSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_DOCTO
 WHERE DTAMOVIMENTO = TRUNC(SYSDATE)
       AND REPLICACAO IN ('F')
UNION ALL
SELECT 'ERP - PendenteExportacaoHoje',
       COUNT(1) QTDE,
       MAX(DTAHORINCLUSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_DOCTO
 WHERE DTAMOVIMENTO = TRUNC(SYSDATE)
       AND REPLICACAO IN ('P', 'S')
UNION ALL
SELECT 'ERP - TotalPendenteExportacao',
       COUNT(1) QTDE,
       MAX(DTAHORINCLUSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_DOCTO
 WHERE REPLICACAO IN ('P', 'S')
UNION ALL
SELECT 'ERP - TotalFALHAExportacao',
       COUNT(1) QTDE,
       MAX(DTAHORINCLUSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_DOCTO
 WHERE DTAMOVIMENTO = TRUNC(SYSDATE)
       AND REPLICACAO IN ('E')
UNION ALL
SELECT 'ERP - TotalDocIntegradoHoje',
       COUNT(1) QTDE,
       MAX(DTAHORAINSERCAO) ULTDATAINCLUSAO
  FROM CONSINCO.MFL_DOCTOFISCAL A
 WHERE A.PDVORIGEM = 1
       AND A.APPORIGEM = 7
       AND A.DTAMOVIMENTO = TRUNC(SYSDATE)
UNION ALL
SELECT 'UltCargaPrecoMonitor', 1, MAX(A.DTAHORFINAL) DTAHOREMISSAO
  FROM MONITORPDV.TB_LOGCARGAMONITOR A
 WHERE A.TABELA = 'TB_PRODPRECO'
UNION ALL
SELECT 'CargaPrecoPDV', COUNT(1) QTDE, MAX(A.DTAHOREMISSAO) DTAHOREMISSAO
  FROM MONITORPDV.TB_CONTROLECARGAPDV A
 WHERE A.TABELA = 'TB_PRODPRECO'
       AND STATUS < 2;
