SELECT X.SEQPESSOA COD_PESSOA, NOMERAZAO, C.NROCONDPAGTOPADRAO COND_DIAS_PADRAO, C.PZOPAGTOMAXIMO MAX_DIAS_PAGTO,
       F.FORMAPAGTO, D.INDPRINCIPAL
       
  FROM CONSINCO.GE_PESSOA X INNER JOIN CONSINCO.MRL_CLIENTE C ON C.SEQPESSOA = X.SEQPESSOA
                            INNER JOIN CONSINCO.MRL_CLIENTECREDITO D ON D.SEQPESSOA = X.SEQPESSOA
                            INNER JOIN CONSINCO.MRL_FORMAPAGTO F ON F.NROFORMAPAGTO = D.NROFORMAPAGTO
                             LEFT JOIN CONSINCO.MAD_CONDICAOCLIENTE B ON B.SEQPESSOA = X.SEQPESSOA AND B.NROFORMAPAGTO = D.NROFORMAPAGTO
                        
                    
 WHERE 1=1
   AND X.SEQPESSOA > 999
   AND D.NROFORMAPAGTO = 3 -- 112 é a BOLETO PDV
   -- Abaixo filtra apenas o que nao tem com forma BOLETO PDV como principal
   -- Para ver tudo, comente a linha abaixo
   AND NOT EXISTS (SELECT 1 FROM MRL_CLIENTE C2 INNER JOIN MRL_CLIENTECREDITO D2 ON C2.SEQPESSOA = D2.SEQPESSOA WHERE C2.SEQPESSOA = X.SEQPESSOA AND D2.NROFORMAPAGTO = 112 AND D2.INDPRINCIPAL = 'S')
   --
   ORDER BY 1; 
