ALTER SESSION SET current_schema = CONSINCO;

SELECT TO_CHAR(SUM(VLRPAGO), 'FM999G999G999D90', 'nls_numeric_characters='',.''') VLR_TOTAL,
       BANCO, A.AGENCIA||CASE WHEN A.DIGAGENCIA IS NOT NULL THEN ' - ' ELSE NULL END||A.DIGAGENCIA AGENCIA, 
       A.NROCONTA||' - '||A.DIGCONTA NROCONTA, E.RAZAOSOCIAL

FROM CONSINCO.FIV_TITULOS_QUITADOS A LEFT JOIN GE_BANCO E ON A.BANCO = E.NROBANCO
    WHERE A.DTAPROGRAMADA = DATE '2022-06-13'
      AND BANCO IS NOT NULL
GROUP BY BANCO, A.AGENCIA, A.DIGAGENCIA, A.NROCONTA, A.DIGCONTA, RAZAOSOCIAL;
