ALTER SESSION SET current_schema = CONSINCO;

SELECT DISTINCT C.NROEMPRESA EMPRESA, A.SEQPRODUTO PLU, A.DESCCOMPLETA DESCROCAO, 
       TO_CHAR(C.PRECOVDANORMAL, 'FM999G999G999D90', 'nls_numeric_characters='',.''') PRECO_VDA, 
       TO_CHAR(C.VLRCUSTOLIQUIDO, 'FM999G999G999D90', 'nls_numeric_characters='',.''') CUSTO_GERENCIAL, ROUND(C.MGMPRECOMINVDAEMPRESA,2) MARGEM, ROUND((SUM(D.QTDVDA) * C.MGMPRECOMINVDAEMPRESA),2) LUCRO

FROM CONSINCO.MAP_PRODUTO A LEFT JOIN CONSINCO.MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
                            LEFT JOIN CONSINCO.MAXV_MGMBASEPRODSEG C ON A.SEQPRODUTO = C.SEQPRODUTO AND C.STATUSVENDA = 'A' AND C.NROSEGMENTO = 2
                            LEFT JOIN CONSINCO.MRL_CUSTODIA D   ON A.SEQPRODUTO = D.SEQPRODUTO AND D.NROEMPRESA = C.NROEMPRESA AND D.DTAENTRADASAIDA >= DATE '2022-06-27'
                            
WHERE (A.DESCCOMPLETA LIKE 'PAD%' OR A.DESCCOMPLETA LIKE 'ROT%')
  AND B.TIPCODIGO   = 'B'
  AND A.SEQPRODUTO  = 22583
  AND C.NROEMPRESA  = 2
  
GROUP BY C.NROEMPRESA, A.SEQPRODUTO, A.DESCCOMPLETA , C.PRECOVDANORMAL, C.VLRCUSTOLIQUIDO, C.MGMPRECOMINVDAEMPRESA
ORDER BY 2 ASC;
