ALTER SESSION SET current_schema = CONSINCO;

SELECT    A.DESCFORNECEDOR FORNECEDOR,
       LPAD(a.NROCNPJCPF,12,0)||LPAD(A.DIGCNPJCPF,2,0) CNPJ,
       CASE WHEN LPAD(A.NROCNPJCPF,12,0) = (SELECT MAX(LPAD(D.NROCGCCPF,12,0)) FROM CONSINCO.GE_PESSOA D WHERE D.NROCGCCPF = A.NROCNPJCPF AND D.STATUS = 'A' ) THEN 'S' ELSE 'N' END CNPJ_CADASTRADO,
       (SELECT GE.FANTASIA FROM CONSINCO.GE_EMPRESA GE WHERE LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0) = LPAD(A.NROCNPJCPFSACADO,12,0)||LPAD(A.DIGCNPJCPFSACADO,2,0)) EMPRESA,
       A.NRODOCUMENTO DOCUMENTO,        
TO_CHAR(A.DTAEMISSAO,'DD/MM/YYYY') EMISSAO,
      TO_CHAR(A.DTAVENCIMENTO,'DD/MM/YYYY')  VENCIMENTO,
       a.VALORDOCUMENTO VALOR,
       a.VALORDESCONTO1 DESCONTO1,
       TO_CHAR(a.DTADESCONTO1,'DD/MM/YYYY') DATADESCONTO1,
       a.VALORDESCONTO2 DESCONTO2,
       TO_CHAR(a.DTADESCONTO2,'DD/MM/YYYY') DATADESCONTO2,
A.VALORABATIMENTO,
       A.CODBARRAS CODIGODEBARRAS
FROM CONSINCO.FIV_DDATITULOSBUSCA a inner join CONSINCO.GE_BANCO B ON (A.NROBANCO = B.NROBANCO)
                                    inner join CONSINCO.FI_CTACORRENTE C ON (A.SEQCTACORRENTE = C.SEQCTACORRENTE)
                                     
WHERE 1=1
   AND NVL(a.ACEITO,'N') = 'N'
   AND A.DTAVENCIMENTO BETWEEN DATE '2021-06-01' AND DATE '2022-01-01'
 --  AND  (SELECT GE.NROEMPRESA FROM CONSINCO.GE_EMPRESA GE WHERE LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0) = LPAD(A.NROCNPJCPFSACADO,12,0)||LPAD(A.DIGCNPJCPFSACADO,2,0)) IN (#LT1)
ORDER BY  A.DTAVENCIMENTO, (SELECT GE.FANTASIA FROM CONSINCO.GE_EMPRESA GE WHERE LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0) = LPAD(A.NROCNPJCPFSACADO,12,0)||LPAD(A.DIGCNPJCPFSACADO,2,0)),a.DTAVENCIMENTO
