ALTER SESSION SET current_schema = CONSINCO;

SELECT   NROEMPRESA, 
         TO_CHAR(SALDOATUAL,  'FM999G999G999D90', 'nls_numeric_characters='',.''') SALDO_ATUAL,
         TO_CHAR(VLRPROVPGTO, 'FM999G999G999D90', 'nls_numeric_characters='',.''') PROVISAO_SAIDA, 
         TO_CHAR((SALDOATUAL - VLRPROVPGTO), 'FM999G999G999D90', 'nls_numeric_characters='',.''') Disponível,
         NROBANCO, SEQCTACORRENTE, A.DESCRICAO
  
FROM CONSINCO.FI_CTACORRENTE A

   WHERE TIPOCONTA = 'B' 
     AND SITUACAO  = 'A'
     AND SEQCTACORRENTE IN (SELECT FI_PROGPAGAMENTO.SEQCTACORRENTE 
                             FROM  FI_PROGPAGAMENTO 
                             WHERE FI_PROGPAGAMENTO.FORMAPAGTO = 'EL' 
                             AND   NVL(FI_PROGPAGAMENTO.SITUACAO,'N') = 'N' )
ORDER BY 1;
