
SELECT A.SEQPRODUTO PLU, A.DESCCOMPLETA DESCROCAO

FROM CONSINCO.MAP_PRODUTO A LEFT JOIN CONSINCO.MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
WHERE (DESCCOMPLETA LIKE 'PAD%' OR DESCCOMPLETA LIKE 'ROT%')
  AND B.TIPCODIGO = 'B'
  
ORDER BY 2 ASC;
