SELECT DISTINCT FV.NROEMPRESA EMP, FV.SEQPRODUTO PLI, QP.PRODUTO DESCRICAO, SUM(QTDOPERACAO) QTD_VENDA, NVL(E.QTDESTQTOTLOCAIS,0) QTD_ESTOQUE, QC.COMPRADOR_CADASTRO COMPRADOR,
       CASE WHEN FV.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = FV.SEQPRODUTO AND Z.STATUSCOMPRA = 'A') THEN 'ATIVO' 
            WHEN FV.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = FV.SEQPRODUTO AND Z.STATUSCOMPRA = 'S') THEN 'SUSPENSO'
            ELSE 'INATIVO' END STATUS_COMPRA,
       CASE WHEN FV.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = FV.SEQPRODUTO AND Z.STATUSVENDA = 'A') THEN 'ATIVO' 
            WHEN FV.SEQPRODUTO IN (SELECT Z.SEQPRODUTO FROM DIM_PRODUTOEMPRESA Z WHERE Z.SEQPRODUTO = FV.SEQPRODUTO AND Z.STATUSVENDA = 'S') THEN 'SUSPENSO'
            ELSE 'INATIVO' END STATUS_VENDA,
       Y.MARCA, QP.FORNECEDOR_PRINCIPAL, C.CATEGORIAN3

FROM FATOG_VENDADIA FV 
  LEFT JOIN DIM_PRODUTO Y    ON FV.SEQPRODUTO = Y.SEQPRODUTO
  LEFT JOIN DIM_CATEGORIA C  ON C.SEQFAMILIA  = Y.SEQFAMILIA
  LEFT JOIN QLV_CATEGORIA QC ON QC.SEQFAMILIA = Y.SEQFAMILIA
  LEFT JOIN QLV_PRODUTO QP   ON QP.SEQPRODUTO = FV.SEQPRODUTO
  LEFT JOIN FATO_ESTOQUE E   ON E.SEQPRODUTO  = FV.SEQPRODUTO AND E.NROEMPRESA = FV.NROEMPRESA AND E.DTAESTOQUE = TRUNC(SYSDATE-1)

WHERE FV.NROEMPRESA IN (1,2)
  AND FV.DTAOPERACAO BETWEEN DATE '2022-07-31' AND DATE '2022-07-31'
  AND FV.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
  
GROUP BY FV.NROEMPRESA, FV.SEQPRODUTO, QP.PRODUTO, COMPRADOR_CADASTRO, QTDESTQTOTLOCAIS, Y.MARCA, FORNECEDOR_PRINCIPAL,CATEGORIAN3
ORDER BY 2,1

