ALTER SESSION SET current_schema = CONSINCO;


SELECT FIV_DDATITULOSBUSCA.VALORDOCUMENTO, FIV_DDATITULOSBUSCA.DTAEMISSAO, FIV_DDATITULOSBUSCA.DTAVENCIMENTO, FIV_DDATITULOSBUSCA.SEUNUMERO, 
 FIV_DDATITULOSBUSCA.CODBARRAS, GE_BANCO.NROBANCO || ' - ' || GE_BANCO.RAZAOSOCIAL, FIV_DDATITULOSBUSCA.NROCNPJCPF, FIV_DDATITULOSBUSCA.DIGCNPJCPF,
  FIV_DDATITULOSBUSCA.TIPODOC, SUBSTR(fc5maskcnpjcpf(FIV_DDATITULOSBUSCA.NROCNPJCPF, FIV_DDATITULOSBUSCA.DIGCNPJCPF, DECODE(FIV_DDATITULOSBUSCA.TIPODOC,
   'CNPJ', 'J', 'F') ), 1, 20), FI_CTACORRENTE.SEQCTACORRENTE || ' - ' || FI_CTACORRENTE.DESCRICAO, FIV_DDATITULOSBUSCA.DTAIMPORTACAO, FIV_DDATITULOSBUSCA.NROBANCO, 
     CASE  WHEN GE_PESSOA.SEQPESSOA IS NULL 
          THEN FIV_DDATITULOSBUSCA.DESCFORNECEDOR 
          ELSE GE_PESSOA.NOMERAZAO || ' - ' || GE_PESSOA.SEQPESSOA 
        END , FIV_DDATITULOSBUSCA.DESCFORNECEDOR,   CASE  WHEN GE_PESSOA.SEQPESSOA IS NULL 
          THEN NULL 
          ELSE GE_PESSOA.NOMERAZAO || ' - ' || GE_PESSOA.SEQPESSOA 
        END, DECODE(FIV_DDATITULOSBUSCA.SEQTITULO,NULL,'Não','Sim'), CASE WHEN FIV_DDATITULOSBUSCA.SEQTITULO IS NULL THEN NULL ELSE 
        FI_TITULO.NROTITULO || '-' || FI_TITULO.SERIETITULO || '/' || FI_TITULO.NROPARCELA END, CASE WHEN FIV_DDATITULOSBUSCA.SEQTITULO IS NULL THEN 
        NULL ELSE DECODE(PKG_FINANCEIRO.FIF_TITAUTORIZADOPAGTO(FIV_DDATITULOSBUSCA.SEQTITULO),0,'Não','Sim') END, FIV_DDATITULOSBUSCA.VALORDESCONTO1, 
        FIV_DDATITULOSBUSCA.VALORDOCUMENTO - FIV_DDATITULOSBUSCA.VALORDESCONTO1, FI_TITULO.VLRNOMINAL,   FIV_DDATITULOSBUSCA.VALORDESCONTO3,
CASE WHEN FI_TITULO.SEQTITULO IS NULL THEN 
  NULL 
ELSE  
  NVL(PKG_FINANCEIRO.FIF_DESCONTO(FI_TITULO.SEQTITULO, FI_TITULO.DTAEMISSAO, 'N'), 0)  
END, CASE WHEN FI_TITULO.SEQTITULO IS NULL THEN 
  NULL 
ELSE 
  FI_TITULO.VLRNOMINAL -  
  NVL(PKG_FINANCEIRO.FIF_DESCONTO(FI_TITULO.SEQTITULO, FI_TITULO.DTAEMISSAO, 'N'), 0)  
END, FIV_DDATITULOSBUSCA.NRODOCUMENTO, FI_COMPLTITULO.USUALTCODBARRA, FI_COMPLTITULO.USUASSOCIOUCODBARRA From FIV_DDATITULOSBUSCA,
 GE_BANCO, FI_CTACORRENTE, GE_PESSOA, FI_COMPLTITULO, FI_TITULO 

Where  
  FIV_DDATITULOSBUSCA.NROBANCO = GE_BANCO.NROBANCO  
AND   FIV_DDATITULOSBUSCA.SEQCTACORRENTE = FI_CTACORRENTE.SEQCTACORRENTE 
AND FIV_DDATITULOSBUSCA.SEQPESSOA = GE_PESSOA.SEQPESSOA(+) 
AND FIV_DDATITULOSBUSCA.SEQIMPORTACAO = FI_COMPLTITULO.SEQIMPORTACAODDA(+) 
AND   FIV_DDATITULOSBUSCA.NROLINHA = FI_COMPLTITULO.NROLINHADDA(+) 
AND FI_COMPLTITULO.SEQTITULO = FI_TITULO.SEQTITULO(+) 
AND     FIV_DDATITULOSBUSCA.NROEMPRESAMAE = 601                 
AND FIV_DDATITULOSBUSCA.DTAVENCIMENTO = DATE '2022-07-19'         
AND FI_TITULO.SEQPESSOA = 114433                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    


