ALTER SESSION SET current_schema = CONSINCO;

SELECT GE.SEQPESSOA, GE.NOMERAZAO, F.NRODOCUMENTO DOC_C5, DDA.NRODOCUMENTO
      
       
FROM FI_TITULO F INNER JOIN FI_ESPECIE FI ON F.CODESPECIE = FI.CODESPECIE AND F.NROEMPRESAMAE = FI.NROEMPRESAMAE
                 INNER JOIN GE_PESSOA  GE ON F.SEQPESSOA  = GE.SEQPESSOA
                 INNER JOIN FI_COMPLTITULO  FC ON F.SEQTITULO = FC.SEQTITULO
                 LEFT JOIN CONSINCO.FIV_DDATITULOSBUSCA DDA ON
                 --(TO_CHAR(LPAD((REGEXP_SUBSTR (DDA.NRODOCUMENTO,'[^-]+', 1, 1)),20,0))) = (TO_CHAR(LPAD(F.NRODOCUMENTO,20,0)))
                 F.DTAVENCIMENTO = DDA.DTAVENCIMENTO AND (F.VLRORIGINAL - FC.VLRDESCCONTRATO) = (DDA.VALORDOCUMENTO - DDA.VALORDESCONTO1)
                 
WHERE F.OBRIGDIREITO     = 'O' 
  --AND F.ABERTOQUITADO    = 'A' 
  AND FI.TIPOESPECIE     = 'T' 
  AND F.ABERTOQUITADO   != 'Q'
  AND F.SITUACAO        != 'S'  
  AND NVL(F.SUSPLIB,'L') = 'L'  
  AND FC.CODBARRA         IS NULL     
                   
  AND F.DTAVENCIMENTO BETWEEN DATE '2022-05-01' AND DATE '2022-05-10' 
  AND F.NROEMPRESA        IN (50) 
  
ORDER BY 2;
