ALTER SESSION SET current_schema = CONSINCO;

SELECT D.DESCFORNECEDOR FORNECEDOR,
       LPAD(D.NROCNPJCPF,12,0)||LPAD(D.DIGCNPJCPF,2,0) CNPJ,
       CASE WHEN LPAD(D.NROCNPJCPF,12,0) = (SELECT MAX(LPAD(D.NROCGCCPF,12,0)) FROM CONSINCO.GE_PESSOA D 
            WHERE D.NROCGCCPF = D.NROCNPJCPF AND D.STATUS = 'A' ) THEN 'S' ELSE 'N' END CNPJ_CADASTRADO,
       (SELECT GE.FANTASIA FROM CONSINCO.GE_EMPRESA GE 
            WHERE LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0) = LPAD(D.NROCNPJCPFSACADO,12,0)||LPAD(D.DIGCNPJCPFSACADO,2,0)) EMPRESA,
       CASE WHEN TO_CHAR(D.NRODOCUMENTO)   = TO_CHAR(FI.NRODOCUMENTO||'-'||FI.SERIETITULO)           THEN 'OK' ELSE 'Divergente' END DOCUMENTO,        
       CASE WHEN TO_CHAR(D.DTAEMISSAO,   'DD/MM/YYYY') = TO_CHAR(FI.DTAEMISSAO,   'DD/MM/YYYY')      THEN 'OK' ELSE 'Divergente' END EMISSAO,
       CASE WHEN TO_CHAR(D.DTAVENCIMENTO,'DD/MM/YYYY') = TO_CHAR(FI.DTAVENCIMENTO,'DD/MM/YYYY')      THEN 'OK' ELSE 'Divergente' END VENCIMENTO,
       CASE WHEN D.VALORDOCUMENTO = FI.VLRORIGINAL                                                   THEN 'OK' ELSE 'Divergente' END VALOR,
       CASE WHEN D.VALORDESCONTO1 = FC.VLRDESCCONTRATO                                               THEN 'OK' ELSE 'Divergente' END DESC_CONTRATO,
       D.DTADESCONTO1 DATADESCONTO1,
       D.VALORDESCONTO2 DESCONTO2,
       TO_CHAR(D.DTADESCONTO2, 'DD/MM/YYYY') DATADESCONTO2,
       D.VLRABATIMENTO VALORABATIMENTO,
       D.CODBARRAS CODIGODEBARRAS
       
FROM CONSINCO.FI_DDAARQUIVO DDA
--CONSINCO.FIV_DDATITULOSBUSCA DDA     
                                      INNER JOIN FI_DDAARQTITULO D         ON (DDA.SEQIMPORTACAO = D.SEQIMPORTACAO)                           
                                      INNER JOIN CONSINCO.GE_BANCO       B ON (DDA.NROBANCO = B.NROBANCO)
                                      INNER JOIN CONSINCO.FI_CTACORRENTE C ON (DDA.SEQCTACORRENTE = C.SEQCTACORRENTE)
                                      RIGHT JOIN CONSINCO.FI_TITULO     FI ON (D.SEQTITULO = FI.SEQTITULO)
                                      LEFT  JOIN FI_COMPLTITULO         FC ON (FI.SEQTITULO = FC.SEQTITULO)
                                     
WHERE 1=1
 --  AND NVL(a.ACEITO,'N') = 'N'
   --AND A.NROEMPRESA IN (1,2,3) --(#LS3)
   AND D.SEQTITULO = 514199596 -- A.DTAVENCIMENTO BETWEEN DATE '2022-01-01' AND DATE '2022-10-01'
 --  AND  (SELECT GE.NROEMPRESA FROM CONSINCO.GE_EMPRESA GE WHERE LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0) = LPAD(A.NROCNPJCPFSACADO,12,0)||LPAD(A.DIGCNPJCPFSACADO,2,0)) IN (#LT1)
ORDER BY  D.DTAVENCIMENTO, (SELECT GE.FANTASIA FROM CONSINCO.GE_EMPRESA GE WHERE LPAD(GE.NROCGC,12,0)||LPAD(GE.DIGCGC,2,0) = LPAD(D.NROCNPJCPFSACADO,12,0)||LPAD(D.DIGCNPJCPFSACADO,2,0)),
          D.DTAVENCIMENTO


