SELECT X.SEQPROMOCPDV SEQ_PROMOC, DESCRICAO DESC_PROMOC, XI.SEQPRODUTO||' - '||DESCCOMPLETA PRODUTO, 
       X.STATUS, TO_CHAR(DTAINICIO, 'DD/MM/YYYY') DTAINICIO, TO_CHAR(DTAFIM, 'DD/MM/YYYY') DTAFIM, DECODE(CODPARCEIRO, 700, 'S', 'N') IND_MEUNAGUMO
  FROM MFL_PROMOCAOPDV X INNER JOIN MFL_PROMOCPDVITEM XI ON XI.SEQPROMOCPDV = X.SEQPROMOCPDV
                         INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO

WHERE 1=1
  AND XI.SEQPRODUTO = :NR1
  AND X.DTAFIM BETWEEN :DT1 AND :DT2
  AND X.CODPARCEIRO = CASE WHEN NVL(#LS1,'Não') = 'Sim' THEN 700 ELSE 999 END

