-- QRP em https://github.com/GiulianoGMS/QRPs/blob/main/RelSelloutDataValidade.QRP

SELECT INITCAP(G.NOMERAZAO) FORNEC, 
       X.SEQPRODUTO PLU, DESCCOMPLETA DESCRICAO,
       INITCAP((SELECT COMPRADOR FROM MAX_COMPRADOR C INNER JOIN MAP_FAMDIVISAO Y ON Y.SEQCOMPRADOR = C.SEQCOMPRADOR WHERE Y.SEQFAMILIA = P.SEQFAMILIA)) COMPRADOR,
       TO_CHAR(DTAFIM, 'DD/MM/YYYY') VENCIMENTO,
      'R$ '||TO_CHAR(VLRITEM, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_REBAIXA, 
       SUM(XI.QUANTIDADE) QTD_VDA,
      'R$ '||TO_CHAR(SUM(VLRITEM * XI.QUANTIDADE), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') SELLOUT,
      'R$ '||TO_CHAR(SUM(SUM(VLRITEM * XI.QUANTIDADE)) OVER(), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') SLNF,
       TO_CHAR(SYSDATE - 1, 'DD/MM/YYYY') VENC_INI,
       TO_CHAR(SYSDATE + 1, 'DD/MM/YYYY') VENC_FIM

  FROM MRL_PROMOCESPECIALHIST X INNER JOIN MFL_DFITEM XI     ON XI.SEQPRODUTO  = X.SEQPRODUTO AND XI.CODPRODUTO = X.CODACESSOESPECIAL
                                INNER JOIN MFL_DOCTOFISCAL Z ON Z.SEQNF        = XI.SEQNF
                                INNER JOIN MAP_PRODUTO P     ON P.SEQPRODUTO   = X.SEQPRODUTO
                                INNER JOIN MAP_FAMFORNEC F   ON F.SEQFAMILIA   = P.SEQFAMILIA AND F.PRINCIPAL = 'S'
                                INNER JOIN GE_PESSOA G       ON G.SEQPESSOA    = F.SEQFORNECEDOR 
                                
                                
 WHERE G.SEQPESSOA = 1016500
   AND Z.DTAHOREMISSAO BETWEEN X.DTAINICIO AND X.DTAFIM
   AND Z.STATUSDF != 'C'
   AND X.STATUS = 'A'

GROUP BY G.NOMERAZAO, X.SEQPRODUTO, DESCCOMPLETA, VLRITEM, TO_CHAR(DTAFIM, 'DD/MM/YYYY'), P.SEQFAMILIA
