ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT SUM(A) QTD_ALT, 'TOTAL' EMPRESA FROM (
SELECT COUNT(DISTINCT SEQPRODUTO) A

  FROM MAD_PRODLOGPRECO X 
 
 WHERE NROSEGMENTO IN (SELECT NROSEGMENTOPRINC FROM MAX_EMPRESA Z WHERE X.NROEMPRESA = Z.NROEMPRESA)
   AND DTAHORALTERACAO BETWEEN DATE '2023-05-01' AND SYSDATE
   AND QTDEMBALAGEM = 1
   AND SEQPROMOCAO IS NOT NULL
   AND X.DTAHORAPROVREPROV IS NOT NULL
   AND NROEMPRESA < 100
   
   GROUP BY SEQPRODUTO, SEQPROMOCAO, NROEMPRESA)
      
   UNION ALL
   
   SELECT NULL, NULL FROM DUAL
   
   UNION ALL
   

SELECT SUM(A), TO_CHAR(NROEMPRESA) FROM (
SELECT COUNT(DISTINCT SEQPRODUTO) A, NROEMPRESA

  FROM MAD_PRODLOGPRECO X 
 
 WHERE NROSEGMENTO IN (SELECT NROSEGMENTOPRINC FROM MAX_EMPRESA Z WHERE X.NROEMPRESA = Z.NROEMPRESA)
   AND DTAHORALTERACAO BETWEEN DATE '2023-05-01' AND SYSDATE
   AND QTDEMBALAGEM = 1
   AND SEQPROMOCAO IS NOT NULL
   AND X.DTAHORAPROVREPROV IS NOT NULL
   AND NROEMPRESA < 100
   
   GROUP BY SEQPRODUTO, SEQPROMOCAO, NROEMPRESA
   
   ORDER BY 2)
   
   GROUP BY NROEMPRESA
