ALTER SESSION SET current_schema = CONSINCO;

SELECT B.NROEMPRESA EMPRESA, B.USULANCTO USUARIO, NULL NUMERO_NF, NULL DATA_EMISSAO, 'Total:' FORNECEDOR, 
       TO_CHAR(SUM(C.VLRNOMINAL), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TITULO, TO_CHAR(SUM(C.VLRPAGO), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_PAGO, 
       NULL SITUACAO

FROM FI_TITULO C LEFT JOIN MLF_NOTAFISCAL B ON C.NROTITULO  = B.NUMERONF
                                           AND C.NROEMPRESA = B.NROEMPRESA
                                           AND C.SEQPESSOA  = B.SEQPESSOA
WHERE C.CODESPECIE  = 'DEVREC'
  AND B.NROEMPRESA IN (501,506) AND B.DTAEMISSAO BETWEEN :DT1 AND :DT2 
  AND B.USULANCTO  IN ('ELSILVA','ADUQUES','RSSILVA')
  AND C.SITUACAO   != 'C'
  AND B.CODGERALOPER IN (802,814,927)
  
  GROUP BY B.NROEMPRESA, B.USULANCTO

UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

UNION ALL

SELECT * FROM (

SELECT B.NROEMPRESA EMPRESA, B.USULANCTO USUARIO, B.NUMERONF NUMERO_NF, TO_CHAR(B.DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, C.SEQPESSOA||' - '||
       (SELECT NOMERAZAO FROM GE_PESSOA G WHERE G.SEQPESSOA = C.SEQPESSOA) FORNECEDOR,
       TO_CHAR(C.VLRNOMINAL, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TITULO, 
       TO_CHAR(C.VLRPAGO,    'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_PAGO, 
       DECODE(C.ABERTOQUITADO, 'A','Aberto', 'Q', 'Quitado') SITUACAO

FROM FI_TITULO C LEFT JOIN MLF_NOTAFISCAL B ON C.NROTITULO  = B.NUMERONF
                                           AND C.NROEMPRESA = B.NROEMPRESA
                                           AND C.SEQPESSOA  = B.SEQPESSOA
WHERE C.CODESPECIE  = 'DEVREC'
  AND B.NROEMPRESA IN (501,506) AND B.DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND B.USULANCTO  IN ('ELSILVA','ADUQUES','RSSILVA')
  AND C.SITUACAO   != 'C'
  AND B.CODGERALOPER IN (802,814,927)
  
ORDER BY 2 ASC, 3 ASC) 
