SELECT INITCAP(G.NOMERAZAO) FORNEC, 
       X.SEQPRODUTO PLU, DESCCOMPLETA DESCRICAO,
       INITCAP(COMPRADOR) COMPRADOR,
       TO_CHAR(DTAFIM, 'MM/YYYY') VENCIMENTO,
       SUM(X.QTDESOLICITADA) QTDE

  FROM MRL_PROMOCESPECIALHIST X INNER JOIN MAP_PRODUTO P     ON P.SEQPRODUTO    = X.SEQPRODUTO
                                INNER JOIN MAP_FAMFORNEC F   ON F.SEQFAMILIA    = P.SEQFAMILIA AND F.PRINCIPAL = 'S'
                                INNER JOIN GE_PESSOA G       ON G.SEQPESSOA     = F.SEQFORNECEDOR 
                                INNER JOIN MAP_FAMDIVISAO FC ON FC.SEQFAMILIA   = P.SEQFAMILIA
                                INNER JOIN MAX_COMPRADOR C   ON C.SEQCOMPRADOR  = FC.SEQCOMPRADOR
                                INNER JOIN MAX_EMPRESA E     ON E.NROEMPRESA    = X.NROEMPRESA
                                INNER JOIN MRL_PRODEMPSEG S  ON S.SEQPRODUTO    = X.SEQPRODUTO AND S.NROEMPRESA = X.NROEMPRESA AND S.NROSEGMENTO = E.NROSEGMENTOPRINC AND S.QTDEMBALAGEM = X.QTDEMBALAGEM
                                INNER JOIN MRL_PRODUTOEMPRESA M ON M.SEQPRODUTO = X.SEQPRODUTO AND M.NROEMPRESA = X.NROEMPRESA
                                
 WHERE 1=1
   AND X.STATUS  IN ('A')
   
GROUP BY G.NOMERAZAO, X.SEQPRODUTO, DESCCOMPLETA, COMPRADOR, TO_CHAR(DTAFIM, 'MM/YYYY')
ORDER BY 6 DESC
