-- Consulta NFs com erro no processamento de retorno

ALTER SESSION SET current_schema = CONSINCO;

SELECT NROEMPRESA, SEQNOTAFISCAL, DTALOG, DESCRICAO, ODR, MAX(ODR2) FROM (
SELECT NROEMPRESA, A.SEQNOTAFISCAL, DTALOG, DESCRICAO, 
       ROW_NUMBER() OVER(PARTITION BY A.SEQNOTAFISCAL ORDER BY A.DTALOG) ODR,
       ROW_NUMBER() OVER(PARTITION BY A.SEQNOTAFISCAL ORDER BY A.DTALOG) ODR2
  FROM MFL_NFELOG A, MLFV_BASENFE B
 
WHERE A.SEQNOTAFISCAL = B.SEQNOTAFISCAL AND DTALOG BETWEEN DATE '2023-01-01' AND SYSDATE) C
  WHERE DESCRICAO LIKE '%Erro no processamento do retorno%'

GROUP BY NROEMPRESA, SEQNOTAFISCAL, DTALOG, DESCRICAO, ODR

ORDER BY 3 DESC

--SELECT * FROM MFL_DOCTOFISCAL X WHERE X.SEQNOTAFISCAL = 17074447 
