ALTER SESSION SET current_schema = CONSINCO;

SELECT MLFV_BASENFE.NROEMPRESA EMPRESA, MLFV_BASENFE.NUMERONF, MLFV_BASENFE.SERIENF SERIE, MLFV_BASENFE.DTAEMISSAO DATA_EMISSAO, MLFV_BASENFE.DESCSTATUSNFE STATUS_NFE, 
       DECODE( MLFV_BASENFE.TIPNOTAFISCAL, 'E', 'Entrada', 'Saída' ) ENTRADA_SAIDA, 
       MLFV_BASENFE.TIPNOTAFISCAL, MLFV_BASENFE.VLRTOTAL VALOR_TOTAL, MLFV_BASENFE.SEQPESSOA, GE_PESSOA.SEQPESSOA || ' - ' || GE_PESSOA.NOMERAZAO PESSOA
       
FROM  MLFV_BASENFE RIGHT JOIN GE_PESSOA ON MLFV_BASENFE.SEQPESSOA = GE_PESSOA.SEQPESSOA

WHERE  MLFV_BASENFE.TIPNOTAFISCAL != 'E'
  AND  MLFV_BASENFE.NROEMPRESA IN (#LS1)                     
  AND (((
       MLFV_BASENFE.STATUSNFE IN (1, 5, 10, 11, 12, 13, 19, 99)  
       OR MLFV_BASENFE.STATUSNFE IS NULL)  
       AND MLFV_BASENFE.INDENVIACANCELAMENTO = 'N'  
       AND MLFV_BASENFE.NFENROPROTENVIO IS NULL)  
       OR(MLFV_BASENFE.INDENVIACANCELAMENTO = 'S')
       ) 
AND NOT EXISTS (SELECT 1 
                 FROM MFL_NFELOG X 
                WHERE X.SEQNOTAFISCAL = MLFV_BASENFE.SEQNOTAFISCAL 
                  AND UPPER(X.DESCRICAO) LIKE '%DENEGADA%') 
                  
AND MLFV_BASENFE.MODELO != '65' 
AND   MLFV_BASENFE.APPORIGEM != 26 
AND MLFV_BASENFE.DTAEMISSAO BETWEEN :DT1 AND :DT2

ORDER BY NROEMPRESA, DTAEMISSAO, NUMERONF ;
