ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT SEQMOVTOESTQ, C.NROEMPRESA, DTAENTRADASAIDA, C.SEQPRODUTO, C.CODGERALOPER, C.QTDLANCTO,
       USULANCTO, VALORVLRNF / C.QTDLANCTO,
       C.VALORIPI / C.QTDLANCTO,
       C.VALORICMSST / C.QTDLANCTO,
       C.VALORDESPNF / C.QTDLANCTO,
       C.VALORDESPFORANF/ C.QTDLANCTO,
       NVL(VALORDCTOFORANF, 0) / C.QTDLANCTO,
       (C.VALORVLRNF + C.VALORIPI + C.VALORICMSST + C.VALORDESPNF + C.VALORDESPFORANF - NVL(VALORDCTOFORANF, 0)) / 
        CASE 
            WHEN C.QTDLANCTO > 0 
                THEN C.QTDLANCTO 
            ELSE 1 
        END VLR_UNI_CALCULADO,
        VALORLANCTOBRT VLR_FATOPERDA,
        (C.VALORVLRNF + C.VALORIPI + C.VALORICMSST + C.VALORDESPNF + C.VALORDESPFORANF - NVL(VALORDCTOFORANF, 0)) / 
        CASE 
            WHEN C.QTDLANCTO > 0 
                THEN C.QTDLANCTO 
            ELSE 1 
        END - VALORLANCTOBRT DIF
       
  FROM MRL_LANCTOESTOQUE C LEFT JOIN FATO_PERDA Z ON Z.NROEMPRESA = C.NROEMPRESA AND Z.DTAOPERACAO = DTAENTRADASAIDA AND Z.SEQPRODUTO = C.SEQPRODUTO
 WHERE 1=1 
   AND C.DTAENTRADASAIDA BETWEEN DATE '2023-09-01' AND DATE '2023-09-30'
   -- Apenas Dif
   AND Z.VALORLANCTOBRT != (C.VALORVLRNF + C.VALORIPI + C.VALORICMSST + C.VALORDESPNF + C.VALORDESPFORANF - NVL(VALORDCTOFORANF, 0)) /   
        CASE 
            WHEN C.QTDLANCTO > 0 
                THEN C.QTDLANCTO 
            ELSE 1 
        END
        
  AND USULANCTO LIKE '%TKT%'
  AND C.QTDLANCTO >= 1
  AND C.CODGERALOPER IN  (20,34,30,35,46,47,62,63,263)
  --AND VALORVLRNF = 0   
  
  
