-- Adicionar linha na MAD_CRITICAPEDCONFIG
-- Adicionar select na MADV_CRITICAPEDVENDA

SELECT DISTINCT A.NROPEDVENDA, A.NROEMPRESA, 'Prod REV com CONSUMO-Verifique' CODCRITICA, I.SEQPRODUTO, FINALIDADEFAMILIA
   FROM CONSINCO.MAD_PEDVENDA A INNER JOIN MAD_PEDVENDAITEM I ON I.NROPEDVENDA = A.NROPEDVENDA AND I.NROEMPRESA = A.NROEMPRESA
                                INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
                                INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA

   WHERE 1=1
   AND A.SITUACAOPED != 'C'
   AND F.FINALIDADEFAMILIA = 'R'
   AND A.DTAINCLUSAO >= SYSDATE - 30
   AND EXISTS (SELECT 1 FROM MAD_PEDVENDA AA INNER JOIN MAD_PEDVENDAITEM II ON AA.NROPEDVENDA = II.NROPEDVENDA AND AA.NROEMPRESA = II.NROEMPRESA
                                             INNER JOIN MAP_PRODUTO PP ON PP.SEQPRODUTO = II.SEQPRODUTO
                                             INNER JOIN MAP_FAMDIVISAO O ON O.SEQFAMILIA = PP.SEQFAMILIA
                       WHERE O.FINALIDADEFAMILIA IN ('A','U') AND AA.NROPEDVENDA = A.NROPEDVENDA AND AA.NROEMPRESA = A.NROEMPRESA);
                       
                       SELECT * FROM MAD_CRITICAPEDCONFIG FOR UPDATE
