SELECT EMPRESA, NUMERONF, SERIE, DATA_EMISSAO,STATUS_NFE, ENTRADA_SAIDA, TIPNOTAFISCAL, VALOR_TOTAL, SEQPESSOA, PESSOA

FROM (SELECT MLFV_BASENFE.NROEMPRESA EMPRESA, MLFV_BASENFE.NUMERONF, MLFV_BASENFE.SERIENF SERIE, 
       TO_CHAR(MLFV_BASENFE.DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, MLFV_BASENFE.DESCSTATUSNFE STATUS_NFE, 
       DECODE( MLFV_BASENFE.TIPNOTAFISCAL, 'E', 'Entrada', 'Saída' ) ENTRADA_SAIDA, SEQNOTAFISCAL,
       MLFV_BASENFE.TIPNOTAFISCAL, MLFV_BASENFE.VLRTOTAL VALOR_TOTAL, MLFV_BASENFE.SEQPESSOA, GE_PESSOA.SEQPESSOA || ' - ' || GE_PESSOA.NOMERAZAO PESSOA
       
FROM  CONSINCO.MLFV_BASENFE RIGHT JOIN CONSINCO.GE_PESSOA ON MLFV_BASENFE.SEQPESSOA = GE_PESSOA.SEQPESSOA

WHERE MLFV_BASENFE.NROEMPRESA IN (42)
  AND DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND MLFV_BASENFE.MODELO != '65' 
  AND MLFV_BASENFE.APPORIGEM != 26 
  AND (((
      MLFV_BASENFE.STATUSNFE IN (1, 5, 10, 11, 12, 13, 19, 99)  
      OR MLFV_BASENFE.STATUSNFE IS NULL)  
      AND MLFV_BASENFE.INDENVIACANCELAMENTO = 'N'  
      AND MLFV_BASENFE.NFENROPROTENVIO IS NULL)  
      OR(MLFV_BASENFE.INDENVIACANCELAMENTO = 'S')) 
       
AND DECODE(MLFV_BASENFE.TIPNOTAFISCAL, 'E','Entrada', 'S','Saida') IN ('Saida')

ORDER BY NROEMPRESA, DTAEMISSAO, NUMERONF ) XX

WHERE NOT EXISTS (SELECT 1 
                 FROM CONSINCO.MFL_NFELOG X 
                WHERE X.SEQNOTAFISCAL = XX.SEQNOTAFISCAL 
                  AND UPPER(X.DESCRICAO) LIKE '%DENEGADA%') 
