ALTER SESSION SET current_schema = CONSINCO;

SELECT DISTINCT B.NROEMPRESA EMPRESA, B.NUMERONF, B.SEQPESSOA||' - '||C.NOMERAZAO FORNECEDOR, TO_CHAR(B.DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, A.DESCRICAO INCONSISTENCIA,
                TO_CHAR(F.VLRNOMINAL, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF --CASE WHEN F.VLRNOMINAL IS NOT NULL THEN F.VLRNOMINAL ELSE (SELECT X.VALOR FROM CONSINCO.OR_NFDESPESA X WHERE X.SEQNOTA = B.SEQNF AND X.NROEMPRESA = B.NROEMPRESA) END VALOR
FROM MLF_AUXNFINCONSISTENCIA A LEFT JOIN MLF_NOTAFISCAL B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                               LEFT JOIN FI_TITULO F ON F.NROTITULO = B.NUMERONF AND F.NROEMPRESA = B.NROEMPRESA
                               LEFT JOIN MLF_NFITEM D ON D.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                               LEFT JOIN GE_PESSOA C ON B.SEQPESSOA = C.SEQPESSOA

WHERE A.DESCRICAO LIKE '%Item sem nro do pedido informado' 
  AND A.AUTORIZADA = 'S'
  AND DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND NROEMPRESA IN (#LS1)
 
UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

UNION ALL

SELECT NULL, NULL, NULL, NULL, 'VALOR_TOTAL', TO_CHAR(SUM(
 
F.VLRNOMINAL), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF --CASE WHEN F.VLRNOMINAL IS NOT NULL THEN F.VLRNOMINAL ELSE (SELECT X.VALOR FROM CONSINCO.OR_NFDESPESA X WHERE X.SEQNOTA = B.SEQNF AND X.NROEMPRESA = B.NROEMPRESA) END VALOR
FROM MLF_AUXNFINCONSISTENCIA A LEFT JOIN MLF_NOTAFISCAL B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                               LEFT JOIN FI_TITULO F ON F.NROTITULO = B.NUMERONF AND F.NROEMPRESA = B.NROEMPRESA
                               LEFT JOIN MLF_NFITEM D ON D.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                               LEFT JOIN GE_PESSOA C ON B.SEQPESSOA = C.SEQPESSOA

WHERE A.DESCRICAO LIKE '%Item sem nro do pedido informado' 
  AND A.AUTORIZADA = 'S'
  AND B.DTAEMISSAO > SYSDATE - 10
  AND DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND NROEMPRESA IN (#LS1)
