ALTER SESSION SET current_schema = CONSINCO;

SELECT DISTINCT B.NROEMPRESA EMPRESA, B.NUMERONF, B.SEQPESSOA||' - '||C.NOMERAZAO FORNECEDOR, B.DTAEMISSAO, A.DESCRICAO INCONSISTENCIA 

FROM MLF_AUXNFINCONSISTENCIA A LEFT JOIN  MLF_NOTAFISCAL B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                               LEFT JOIN  GE_PESSOA C ON B.SEQPESSOA = C.SEQPESSOA

WHERE A.DESCRICAO LIKE '%Item sem nro do pedido informado' 
  AND A.AUTORIZADA = 'S'
  AND DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND NROEMPRESA IN (:LS1)
