ALTER SESSION SET current_schema = CONSINCO;

SELECT DISTINCT B.NROEMPRESA EMPRESA, B.NUMERONF, B.SEQPESSOA||' - '||C.NOMERAZAO FORNECEDOR, TO_CHAR(B.DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, A.DESCRICAO INCONSISTENCIA,
                TO_CHAR(F.VLRNOMINAL, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF /*CASE WHEN F.VLRNOMINAL IS NOT NULL THEN F.VLRNOMINAL ELSE (SELECT X.VALOR FROM CONSINCO.OR_NFDESPESA X WHERE X.SEQNOTA = B.SEQNF AND X.NROEMPRESA = B.NROEMPRESA) END VALOR*/
FROM MLF_AUXNFINCONSISTENCIA A LEFT JOIN MLF_NOTAFISCAL B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                               LEFT JOIN FI_TITULO F ON F.NROTITULO = B.NUMERONF AND F.NROEMPRESA = B.NROEMPRESA AND F.SEQPESSOA = B.SEQPESSOA
                               LEFT JOIN MLF_NFITEM D ON D.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                               LEFT JOIN GE_PESSOA C ON B.SEQPESSOA = C.SEQPESSOA

WHERE A.DESCRICAO LIKE '%Item sem nro do pedido informado' 
  AND A.AUTORIZADA = 'S'
  AND B.DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND B.NROEMPRESA IN (#LS1)
/*
UNION ALL

SELECT X.NROEMPRESA, X.NRONOTA, X.SEQPESSOA||' - '||CC.NOMERAZAO FORNECEDOR, TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, 'Data requisição igual data de entrada' INCONSISTENCIA,
       TO_CHAR(X.VALOR, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF
FROM CONSINCO.OR_NFDESPESA X LEFT JOIN CONSINCO.OR_NFDESPESAREQ Y ON X.SEQNOTA = Y.SEQNOTA
                             LEFT JOIN CONSINCO.OR_REQUISICAO Z ON Y.SEQREQUISICAO = Z.SEQREQUISICAO
                             LEFT JOIN GE_PESSOA CC ON X.SEQPESSOA = CC.SEQPESSOA
WHERE X.DTAENTRADA = Z.DTAINCLUSAO
  AND X.DTAEMISSAO BETWEEN SYSDATE -10 AND SYSDATE
  AND X.NROEMPRESA = 17
  */
UNION ALL 

SELECT NULL, NULL, NULL, NULL, 'TOTAL' A, TO_CHAR(SUM(VALOR_NF), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') FROM (

SELECT DISTINCT B.NROEMPRESA EMPRESA, B.NUMERONF, B.SEQPESSOA||' - '||C.NOMERAZAO FORNECEDOR, TO_CHAR(B.DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, A.DESCRICAO INCONSISTENCIA,
                F.VLRNOMINAL VALOR_NF /*CASE WHEN F.VLRNOMINAL IS NOT NULL THEN F.VLRNOMINAL ELSE (SELECT X.VALOR FROM CONSINCO.OR_NFDESPESA X WHERE X.SEQNOTA = B.SEQNF AND X.NROEMPRESA = B.NROEMPRESA) END VALOR*/
FROM MLF_AUXNFINCONSISTENCIA A LEFT JOIN MLF_NOTAFISCAL B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                               LEFT JOIN FI_TITULO F ON F.NROTITULO = B.NUMERONF AND F.NROEMPRESA = B.NROEMPRESA AND F.SEQPESSOA = B.SEQPESSOA
                               LEFT JOIN MLF_NFITEM D ON D.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                               LEFT JOIN GE_PESSOA C ON B.SEQPESSOA = C.SEQPESSOA

WHERE A.DESCRICAO LIKE '%Item sem nro do pedido informado' 
  AND A.AUTORIZADA = 'S'
  AND B.DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND B.NROEMPRESA IN (#LS1)
  
/*
UNION ALL

SELECT X.NROEMPRESA, X.NRONOTA, X.SEQPESSOA||' - '||CC.NOMERAZAO FORNECEDOR, TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, 'Data requisição igual data de entrada' INCONSISTENCIA,
       X.VALOR VALOR_NF
FROM CONSINCO.OR_NFDESPESA X LEFT JOIN CONSINCO.OR_NFDESPESAREQ Y ON X.SEQNOTA = Y.SEQNOTA
                             LEFT JOIN CONSINCO.OR_REQUISICAO Z ON Y.SEQREQUISICAO = Z.SEQREQUISICAO
                             LEFT JOIN GE_PESSOA CC ON X.SEQPESSOA = CC.SEQPESSOA
WHERE X.DTAENTRADA = Z.DTAINCLUSAO
  AND X.DTAEMISSAO BETWEEN SYSDATE -10 AND SYSDATE
  AND X.NROEMPRESA = 17)
*/ )
ORDER BY 1,2

------------------------------------

-- Versão para QRP

SELECT DISTINCT B.NROEMPRESA EMPRESA, B.NUMERONF, B.SEQPESSOA||' - '||C.NOMERAZAO FORNECEDOR, TO_CHAR(B.DTAEMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, A.DESCRICAO INCONSISTENCIA,
                TO_CHAR(F.VLRNOMINAL, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF,
                (SELECT TO_CHAR(SUM(VALOR_NF), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') FROM (

SELECT SUM (DISTINCT F.VLRNOMINAL) VALOR_NF
FROM MLF_AUXNFINCONSISTENCIA A LEFT JOIN MLF_NOTAFISCAL B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                               LEFT JOIN FI_TITULO F ON F.NROTITULO = B.NUMERONF AND F.NROEMPRESA = B.NROEMPRESA AND F.SEQPESSOA = B.SEQPESSOA
                               LEFT JOIN MLF_NFITEM D ON D.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                               LEFT JOIN GE_PESSOA C ON B.SEQPESSOA = C.SEQPESSOA

WHERE A.DESCRICAO LIKE '%Item sem nro do pedido informado' 
  AND A.AUTORIZADA = 'S'
  AND B.DTAEMISSAO =  :DT1 AND :DT2 
  AND B.NROEMPRESA IN (#LS1)
  )) TOTAL
FROM MLF_AUXNFINCONSISTENCIA A LEFT JOIN MLF_NOTAFISCAL B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                               LEFT JOIN FI_TITULO F ON F.NROTITULO = B.NUMERONF AND F.NROEMPRESA = B.NROEMPRESA AND F.SEQPESSOA = B.SEQPESSOA
                               LEFT JOIN MLF_NFITEM D ON D.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                               LEFT JOIN GE_PESSOA C ON B.SEQPESSOA = C.SEQPESSOA

WHERE A.DESCRICAO LIKE '%Item sem nro do pedido informado' 
  AND A.AUTORIZADA = 'S'
  AND B.DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND B.NROEMPRESA IN (#LS1)

ORDER BY 1,2
