ALTER SESSION SET current_schema = CONSINCO;

SELECT X.NROEMPRESA, X.NRONOTA, X.SEQPESSOA||' - '||CC.NOMERAZAO FORNECEDOR, TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') DATA_ENTRADA, 'Data requisição igual data de entrada' INCONSISTENCIA,
       TO_CHAR(X.VALOR, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF
FROM CONSINCO.OR_NFDESPESA X LEFT JOIN CONSINCO.OR_NFDESPESAREQ Y ON X.SEQNOTA = Y.SEQNOTA
                             LEFT JOIN CONSINCO.OR_REQUISICAO Z ON Y.SEQREQUISICAO = Z.SEQREQUISICAO
                             LEFT JOIN GE_PESSOA CC ON X.SEQPESSOA = CC.SEQPESSOA
WHERE X.DTAENTRADA = Z.DTAINCLUSAO 
  AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2 /*BETWEEN SYSDATE -10 AND SYSDATE*/
  AND X.NROEMPRESA = :NR1
  AND X.CGO = 2 
  
UNION ALL

SELECT NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

UNION ALL

SELECT NULL, NULL, NULL, NULL, 'TOTAL :', TO_CHAR(SUM(
       X.VALOR), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF
FROM CONSINCO.OR_NFDESPESA X LEFT JOIN CONSINCO.OR_NFDESPESAREQ Y ON X.SEQNOTA = Y.SEQNOTA
                             LEFT JOIN CONSINCO.OR_REQUISICAO Z ON Y.SEQREQUISICAO = Z.SEQREQUISICAO
                             LEFT JOIN GE_PESSOA CC ON X.SEQPESSOA = CC.SEQPESSOA
WHERE X.DTAENTRADA = Z.DTAINCLUSAO 
  AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2 /*BETWEEN SYSDATE -10 AND SYSDATE*/
  AND X.NROEMPRESA = :NR1
  AND X.CGO = 2 
  
----------------------------------------------------------------------------

-- Versão para QRP

SELECT X.NROEMPRESA, X.NRONOTA, X.SEQPESSOA||' - '||CC.NOMERAZAO FORNECEDOR, TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') DATA_ENTRADA, 'Data requisição igual data de entrada' INCONSISTENCIA,
       TO_CHAR(X.VALOR, 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF,
 (SELECT TO_CHAR(SUM(
       X.VALOR), 'FM999G999G999D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_NF
FROM CONSINCO.OR_NFDESPESA X LEFT JOIN CONSINCO.OR_NFDESPESAREQ Y ON X.SEQNOTA = Y.SEQNOTA
                             LEFT JOIN CONSINCO.OR_REQUISICAO Z ON Y.SEQREQUISICAO = Z.SEQREQUISICAO
                             LEFT JOIN GE_PESSOA CC ON X.SEQPESSOA = CC.SEQPESSOA
WHERE X.DTAENTRADA = Z.DTAINCLUSAO 
  AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND X.NROEMPRESA  IN (#LS1)
  AND X.CGO = 2 ) TOTAL
FROM CONSINCO.OR_NFDESPESA X LEFT JOIN CONSINCO.OR_NFDESPESAREQ Y ON X.SEQNOTA = Y.SEQNOTA
                             LEFT JOIN CONSINCO.OR_REQUISICAO Z ON Y.SEQREQUISICAO = Z.SEQREQUISICAO
                             LEFT JOIN GE_PESSOA CC ON X.SEQPESSOA = CC.SEQPESSOA
WHERE X.DTAENTRADA = Z.DTAINCLUSAO 
  AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2 
  AND X.NROEMPRESA IN (#LS1)
  AND X.CGO = 2 

ORDER BY 1
