SELECT DISTINCT A.NROEMPRESA, A.NROREQUISICAO, A.CODHISTORICO||' - '||E.DESCRICAO NATUREZA,
       TO_CHAR(A.DTAALTERACAO, 'DD/MM/YYYY') DTA_INCLUSAO,
       TO_CHAR(D.DTAVENCIMENTO, 'DD/MM/YYYY') VENCIMENTO,
       A.USUAUTORIZACAO AUTORIZADOR,
       A.VALOR VLR_TOTAL,
      (SELECT NVL(SUM(AA.VALOR), 0)
          FROM OR_NFDESPESA AA, OR_NFDESPESAREQ BB
         WHERE AA.SEQNOTA = BB.SEQNOTA
           AND BB.SEQREQUISICAO = A.SEQREQUISICAO AND TO_CHAR(AA.DTAENTRADA, 'MM') = TO_CHAR(D.DTAVENCIMENTO, 'MM')) UTILIZADO,
       TO_CHAR(D.DTAVENCIMENTO, 'MM') MES,
       TO_CHAR(D.DTAVENCIMENTO, 'YYYY') ANO,
       (A.VALOR -
      (SELECT NVL(SUM(AA.VALOR), 0)
          FROM OR_NFDESPESA AA, OR_NFDESPESAREQ BB
         WHERE AA.SEQNOTA = BB.SEQNOTA
           AND BB.SEQREQUISICAO = A.SEQREQUISICAO AND AA.DTAENTRADA <= D.DTAVENCIMENTO)) VLR_DISPONIVEL,
       DECODE(A.STATUS, 'F','Finalizada', 'A','Aguardando','L','Liberada', 'R','Rejeitada') STATUS_REQUISICAO
      
  FROM OR_REQUISICAO A, GE_PESSOA B, RF_PARAMNATNFDESP C, OR_REQUISICAOVENCTO D, ABA_HISTORICO E

 WHERE A.SEQPESSOA     = B.SEQPESSOA
   AND E.SEQHISTORICO  = A.CODHISTORICO
   AND D.SEQREQUISICAO = A.SEQREQUISICAO
   AND A.CODHISTORICO  = C.CODHISTORICO(+)
   AND A.NROEMPRESA    = C.NROEMPRESA(+)
   AND A.CODHISTORICO IN
       (SELECT A.CODHISTORICO
          FROM RF_PARAMNATNFDESP A
         WHERE A.NROEMPRESA = (SELECT NVL(B.NROEMPRESAHIST, B.NROEMPRESA)
                                 FROM ORV_NROEMPRESAPLANO B
                                WHERE B.NROEMPRESA = A.NROEMPRESA))
   
   AND A.NROEMPRESA IN (#LS1)
   AND A.CODHISTORICO IN (#LT1)
   AND A.DTAALTERACAO BETWEEN :DT1 AND :DT2
   
 ORDER BY NROEMPRESA, TO_CHAR(A.DTAALTERACAO, 'DD/MM/YYYY'), NROREQUISICAO, 9,10
 
