SELECT DISTINCT 'Loja: '||E.NOMEREDUZIDO LOJA, 'Cod: '||#NR1||
       CASE WHEN (SELECT DISTINCT 1 FROM MAP_PRODCODIGO C WHERE TIPCODIGO = 'E' AND CODACESSO = :NR1 OR SEQPRODUTO = :NR1) IS NULL 
         THEN ' Não Cadastrado!' ELSE ' - ' ||(SELECT DISTINCT DESCCOMPLETA FROM MAP_PRODUTO A INNER JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
           WHERE CODACESSO = :NR1 AND TIPCODIGO = 'E' OR A.SEQPRODUTO = :NR1) END
           INFO
         
  FROM MAX_EMPRESA E WHERE NROEMPRESA = :LS1
  
UNION ALL
  
SELECT NULL, NULL FROM DUAL

UNION ALL

SELECT DISTINCT 'Plu/Ean Cadastrado:', CASE WHEN CODACESSO IS NULL THEN 'Não' ELSE 'Sim' END
  FROM MAP_PRODCODIGO C WHERE C.TIPCODIGO = 'E' AND CODACESSO = :NR1  OR SEQPRODUTO = :NR1
  
UNION ALL

SELECT DISTINCT 'Ativo para Venda:', DECODE(S.STATUSVENDA, 'A','Sim','I','Não')
  FROM MRL_PRODEMPSEG S INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = S.NROEMPRESA AND E.NROSEGMENTOPRINC = S.NROSEGMENTO
                        INNER JOIN MAP_PRODCODIGO C ON S.QTDEMBALAGEM = C.QTDEMBALAGEM AND C.SEQPRODUTO = S.SEQPRODUTO AND (CODACESSO = :NR1 AND TIPCODIGO = 'E' OR C.SEQPRODUTO = :NR1)
                        
 WHERE S.NROEMPRESA = :LS1
 
UNION ALL

SELECT DISTINCT 'Estoque:', TO_CHAR(M.ESTQLOJA)||' Unidades'
  FROM MRL_PRODUTOEMPRESA M
 WHERE M.NROEMPRESA = :LS1 
   AND EXISTS (SELECT DISTINCT 1 FROM MAP_PRODCODIGO C WHERE C.SEQPRODUTO = M.SEQPRODUTO AND (CODACESSO = :NR1 AND TIPCODIGO = 'E' OR C.SEQPRODUTO = :NR1))
   
UNION ALL

SELECT DISTINCT 'Preço de Venda Normal:', 'R$ '||TO_CHAR(NVL(S.PRECOVALIDNORMAL,0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
  FROM MRL_PRODEMPSEG S INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = S.NROEMPRESA AND E.NROSEGMENTOPRINC = S.NROSEGMENTO
                        INNER JOIN MAP_PRODCODIGO C ON S.QTDEMBALAGEM = C.QTDEMBALAGEM AND C.SEQPRODUTO = S.SEQPRODUTO AND (CODACESSO = :NR1 AND TIPCODIGO = 'E' OR C.SEQPRODUTO = :NR1)
                        
 WHERE S.NROEMPRESA = :LS1
   AND S.QTDEMBALAGEM = 1
   
UNION ALL

SELECT DISTINCT 'Preço de Venda Promocional:', 'R$ '||TO_CHAR(NVL(S.PRECOVALIDPROMOC,0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
  FROM MRL_PRODEMPSEG S INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = S.NROEMPRESA AND E.NROSEGMENTOPRINC = S.NROSEGMENTO
                        INNER JOIN MAP_PRODCODIGO C ON S.QTDEMBALAGEM = C.QTDEMBALAGEM AND C.SEQPRODUTO = S.SEQPRODUTO AND (CODACESSO = :NR1 AND TIPCODIGO = 'E' OR C.SEQPRODUTO = :NR1)
                        
 WHERE S.NROEMPRESA = :LS1
   AND S.QTDEMBALAGEM = 1
   
UNION ALL

SELECT DISTINCT 'Preço Meu Nagumo:', 'R$ '||TO_CHAR(NVL((MN.PRECOPROMOCAO),0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
  FROM NAGV_BASE_PROMOC_PDV MN INNER JOIN MAP_PRODCODIGO C ON 1 = C.QTDEMBALAGEM AND C.SEQPRODUTO = MN.SEQPRODUTO AND (CODACESSO = :NR1 AND TIPCODIGO = 'E' OR C.SEQPRODUTO = :NR1)
 WHERE MN.CODPARCEIRO = 700
   AND MN.NROEMPRESA = :LS1
 
UNION ALL

SELECT DISTINCT 'Preço Regra de Incentivo:', 'R$ '||TO_CHAR(NVL(P.PRECO_FINAL, 0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
  FROM NAGV_PROMOC_ATIVAS_REGRAPDV P INNER JOIN MAP_PRODCODIGO C ON 1 = C.QTDEMBALAGEM AND C.SEQPRODUTO = P.SEQPRODUTO AND (CODACESSO = :NR1 AND TIPCODIGO = 'E' OR C.SEQPRODUTO = :NR1)
 WHERE P.NROEMPRESA = :LS1
 
UNION ALL
 
SELECT DISTINCT 'Preço CRM/Funcionario:', 'R$ '||TO_CHAR(NVL(P.PRECO_FINAL,0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
 FROM NAGT_CRM_BASE_MP_FUNC P INNER JOIN MAP_PRODCODIGO C ON 1 = C.QTDEMBALAGEM AND C.SEQPRODUTO = P.SKU AND (CODACESSO = :NR1 AND TIPCODIGO = 'E' OR C.SEQPRODUTO = :NR1)
AND P.NRO_EMPRESA = :LS1
 
UNION ALL

SELECT 'Fornecedor Cadastrado:', CASE WHEN (SELECT COUNT(1) FROM MAP_FAMFORNEC Z WHERE SEQFAMILIA = (SELECT DISTINCT SEQFAMILIA FROM MAP_PRODUTO X WHERE SEQPRODUTO = (SELECT DISTINCT SEQPRODUTO FROM MAP_PRODCODIGO C WHERE TIPCODIGO = 'E' AND CODACESSO = :NR1 OR SEQPRODUTO = :NR1))) > 0 
       THEN 'Sim' ELSE 'Produto Sem Fornecedor Cadastrado!' END FROM DUAL
         
