SELECT 'Loja: '||E.NOMEREDUZIDO LOJA, 'Ean: '||#NR1||CASE WHEN (SELECT 1 FROM MAP_PRODCODIGO C WHERE TIPCODIGO = 'E' AND CODACESSO = :NR1) IS NULL THEN ' Não Cadastrado!' END INFO
  FROM MAX_EMPRESA E WHERE NROEMPRESA = :LS1
  
UNION ALL
  
SELECT NULL, NULL FROM DUAL

UNION ALL

SELECT 'Ean Cadastrado:', CASE WHEN CODACESSO IS NULL THEN 'Não' ELSE 'Sim' END
  FROM MAP_PRODCODIGO C WHERE C.TIPCODIGO = 'E' AND CODACESSO = :NR1
  
UNION ALL

SELECT 'Ativo para Venda:', DECODE(S.STATUSVENDA, 'A','Sim','I','Não')
  FROM MRL_PRODEMPSEG S INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = S.NROEMPRESA AND E.NROSEGMENTOPRINC = S.NROSEGMENTO
                        INNER JOIN MAP_PRODCODIGO C ON TIPCODIGO = 'E' AND S.QTDEMBALAGEM = C.QTDEMBALAGEM AND C.SEQPRODUTO = S.SEQPRODUTO AND CODACESSO = :NR1
                        
 WHERE S.NROEMPRESA = :LS1
 
UNION ALL

SELECT 'Estoque:', TO_CHAR(M.ESTQLOJA)||' Unidades'
  FROM MRL_PRODUTOEMPRESA M
 WHERE M.NROEMPRESA = :LS1 
   AND EXISTS (SELECT 1 FROM MAP_PRODCODIGO C WHERE TIPCODIGO = 'E' AND C.SEQPRODUTO = M.SEQPRODUTO AND CODACESSO = :NR1)
