/*Regra para atualização da data: NovaData não pode ser Maior que a data final nem maior que a DataInicio atual */
/*Criado por Giuliano em 16/11/2023*/

    UPDATE CONSINCO.MRL_PROMOCAOITEM PI
       SET PI.DTAINICIOPROM = (SELECT CASE WHEN :DT1 > MAX(P.DTAFIM) OR :DT1 >= MAX(DTAINICIO) OR :DT1 < TRUNC(SYSDATE)
                                      THEN MAX(DTAINICIO) ELSE :DT1 END FROM CONSINCO.MRL_PROMOCAO P WHERE P.SEQPROMOCAO = :NR1),
           PI.USUALTERACAO = (SELECT SYS_CONTEXT ('USERENV','CLIENT_IDENTIFIER')FROM DUAL),
           PI.DTAHORAALTERACAO = SYSDATE
     WHERE SEQPROMOCAO = :NR1
       AND PI.DTAINICIOPROM  != :DT1;
    COMMIT;

    UPDATE CONSINCO.MRL_PROMOCAO P
       SET P.DTAINICIO          = (SELECT CASE WHEN :DT1 > MAX(P.DTAFIM) OR :DT1 >= MAX(DTAINICIO) OR :DT1 < TRUNC(SYSDATE)
                                      THEN MAX(DTAINICIO) ELSE :DT1 END FROM CONSINCO.MRL_PROMOCAO P WHERE P.SEQPROMOCAO = :NR1),
           P.INDGEROUREPLICACAO = NULL,
           P.INDREPLICACAO      = 'S',
           P.USUALTERACAO       = (SELECT SYS_CONTEXT ('USERENV','CLIENT_IDENTIFIER')FROM DUAL),
           P.DTAHORAALTERACAO   = SYSDATE
     WHERE P.SEQPROMOCAO = :NR1
       AND P.CENTRALLOJA = 'M'
       AND DTAINICIO    != :DT1;
    COMMIT;

SELECT CASE WHEN TO_DATE(MAX(DTAINICIO), 'DD/MM/YY') = :DT1 THEN 'Data Alterada Com Sucesso!' 
            ELSE 'Não foi possível alterar a data, valide as informações e tente novamente.' END STATUS
  FROM CONSINCO.MRL_PROMOCAO
 WHERE SEQPROMOCAO = :NR1
 
UNION ALL

SELECT CASE WHEN TO_DATE(MAX(DTAINICIO), 'DD/MM/YY') = :DT1 THEN 'Promoção: '||MAX(A.PROMOCAO)||' - Data inicio: '||TO_DATE(MAX(DTAINICIO), 'DD/MM/YYYY')
            ELSE 'Observação: Não é possível alterar caso a nova data seja maior que a atual ou maior que a data final da promoção' END STATUS
  FROM CONSINCO.MRL_PROMOCAO A
 WHERE SEQPROMOCAO = :NR1;
  
 /*
 UPDATE CONSINCO.MRL_PROMOCAOITEM SET DTAINICIOPROM = DATE '2023-11-19' WHERE SEQPROMOCAO = 166054;
 COMMIT;
 
 UPDATE CONSINCO.MRL_PROMOCAO SET DTAINICIO = DATE '2023-11-19' WHERE SEQPROMOCAO = 166054;
 COMMIT;
 */
