SELECT DISTINCT
       'Loja: ' || E.NOMEREDUZIDO AS LOJA,
       'Cod: ' || :NR1 ||
       CASE
         WHEN NOT EXISTS (
              SELECT 1
                FROM MAP_PRODCODIGO C
               WHERE (C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
                  OR C.SEQPRODUTO = :NR1
         )
         THEN ' Não Cadastrado!'
         ELSE ' - ' ||
              (SELECT A.DESCCOMPLETA
                 FROM MAP_PRODUTO A
                WHERE A.SEQPRODUTO =
                      (SELECT C.SEQPRODUTO
                         FROM MAP_PRODCODIGO C
                        WHERE ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
                               OR C.SEQPRODUTO = :NR1)
                          AND ROWNUM = 1))
       END AS INFO
FROM MAX_EMPRESA E
WHERE E.NROEMPRESA = #LS1

UNION ALL
SELECT NULL, NULL FROM DUAL

UNION ALL
SELECT
       'Plu/Ean Cadastrado:',
       CASE WHEN COUNT(*) > 0 THEN 'Sim' ELSE 'Não' END
FROM MAP_PRODCODIGO C
WHERE (C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
   OR C.SEQPRODUTO = :NR1

UNION ALL
SELECT
       'Ativo para Venda:',
       MIN(DECODE(S.STATUSVENDA,'A','Sim','I','Não'))
FROM MRL_PRODEMPSEG S INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = S.NROEMPRESA AND E.NROSEGMENTOPRINC = S.NROSEGMENTO
INNER JOIN MAP_PRODCODIGO C
        ON C.SEQPRODUTO = S.SEQPRODUTO
       AND C.QTDEMBALAGEM = S.QTDEMBALAGEM
WHERE S.NROEMPRESA = #LS1
  AND ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
       OR C.SEQPRODUTO = :NR1)

UNION ALL
SELECT
       'Segmento Ativo:',
       MIN(DECODE(MS.STATUS,'A','Sim','I','Não'))
FROM MRL_PRODEMPSEG S
INNER JOIN MAD_SEGMENTO MS
        ON MS.NROSEGMENTO = S.NROSEGMENTO
INNER JOIN MAP_PRODCODIGO C
        ON C.SEQPRODUTO = S.SEQPRODUTO
WHERE S.NROEMPRESA = #LS1
  AND ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
       OR C.SEQPRODUTO = :NR1)

UNION ALL
SELECT
       'Departamento:',
       MIN(D.DESCRICAO)
FROM MRL_PRODUTOEMPRESA P
INNER JOIN MRL_DEPARTAMENTO D
        ON D.NROEMPRESA = P.NROEMPRESA
       AND D.NRODEPARTAMENTO = P.NRODEPARTAMENTO
INNER JOIN MAP_PRODCODIGO C
        ON C.SEQPRODUTO = P.SEQPRODUTO
WHERE P.NROEMPRESA = #LS1
  AND ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
       OR C.SEQPRODUTO = :NR1)

UNION ALL
SELECT
       'Fornecedor Cadastrado:',
       CASE WHEN COUNT(*) > 0 THEN 'Sim'
            ELSE 'Produto Sem Fornecedor Cadastrado!'
       END
FROM MAP_FAMFORNEC F
WHERE F.SEQFAMILIA =
      (SELECT P.SEQFAMILIA
         FROM MAP_PRODUTO P
        WHERE P.SEQPRODUTO =
              (SELECT C.SEQPRODUTO
                 FROM MAP_PRODCODIGO C
                WHERE ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
                       OR C.SEQPRODUTO = :NR1)
                  AND ROWNUM = 1))

UNION ALL
SELECT
       'Preço de Venda Normal:',
       'R$ ' || TO_CHAR(
           NVL(MIN(S.PRECOVALIDNORMAL),0),
           'FM999G999G990D90',
           'NLS_NUMERIC_CHARACTERS='',.'''
       )
FROM MRL_PRODEMPSEG S INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = S.NROEMPRESA AND E.NROSEGMENTOPRINC = S.NROSEGMENTO
INNER JOIN MAP_PRODCODIGO C
        ON C.SEQPRODUTO = S.SEQPRODUTO
       AND C.QTDEMBALAGEM = S.QTDEMBALAGEM
WHERE S.NROEMPRESA = #LS1
  AND S.QTDEMBALAGEM = 1
  AND ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
       OR C.SEQPRODUTO = :NR1)

UNION ALL
SELECT
       'Preço de Venda Promocional:',
       'R$ ' || TO_CHAR(
           NVL(MIN(S.PRECOVALIDPROMOC),0),
           'FM999G999G990D90',
           'NLS_NUMERIC_CHARACTERS='',.'''
       )
FROM MRL_PRODEMPSEG S INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = S.NROEMPRESA AND E.NROSEGMENTOPRINC = S.NROSEGMENTO
INNER JOIN MAP_PRODCODIGO C
        ON C.SEQPRODUTO = S.SEQPRODUTO
       AND C.QTDEMBALAGEM = S.QTDEMBALAGEM
WHERE S.NROEMPRESA = #LS1
  AND S.QTDEMBALAGEM = 1
  AND ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
       OR C.SEQPRODUTO = :NR1)

UNION ALL
SELECT
       'Oferta Cartão Nagumo:',
       'R$ ' || TO_CHAR(
           NVL(MIN(A.PRECOINCENTIVOEMB),0),
           'FM999G999G990D90',
           'NLS_NUMERIC_CHARACTERS='',.'''
       )
FROM consinco.NAGV_PROMOC_ATIVAS_REGRAPDV A
INNER JOIN MAP_PRODCODIGO C
        ON C.SEQPRODUTO = A.SEQPRODUTO
WHERE A.NROEMPRESA = #LS1
  AND ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
       OR C.SEQPRODUTO = :NR1)
       
UNION ALL
SELECT
       'Oferta Meu Nagumo:',
       'R$ ' || TO_CHAR(
           NVL(MIN(A.PRECOPROMOCAO),0),
           'FM999G999G990D90',
           'NLS_NUMERIC_CHARACTERS='',.'''
       )
FROM consinco.NAGV_BASE_PROMOC_PDV_MN A
INNER JOIN MAP_PRODCODIGO C
        ON C.SEQPRODUTO = A.SEQPRODUTO
  AND ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
       OR C.SEQPRODUTO = :NR1)

UNION ALL
 
SELECT DISTINCT 'Preço CRM/Funcionario:', 'R$ '||TO_CHAR(NVL(P.PRECO_FINAL,0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') 
 FROM NAGT_CRM_BASE_MP_FUNC P INNER JOIN MAP_PRODCODIGO C ON 1 = C.QTDEMBALAGEM AND C.SEQPRODUTO = P.SKU AND (CODACESSO = :NR1 AND TIPCODIGO = 'E' OR C.SEQPRODUTO = :NR1)
AND P.NRO_EMPRESA = :LS1

UNION ALL
SELECT
       'Última Nota Recebida:',
       X.NUMERONF || ' - ' || TO_CHAR(X.DTARECEBIMENTO,'DD/MM/YYYY')
FROM (
    SELECT DISTINCT
           NF.NUMERONF,
           NVL(NF.DTARECEBIMENTO, NF.DTAENTRADA) AS DTARECEBIMENTO
    FROM MLF_NOTAFISCAL NF
    INNER JOIN MLF_NFITEM NI
            ON NI.NROEMPRESA     = NF.NROEMPRESA
           AND NI.NUMERONF      = NF.NUMERONF
           AND NI.SERIENF       = NF.SERIENF
           AND NI.TIPNOTAFISCAL = NF.TIPNOTAFISCAL
    INNER JOIN MAP_PRODCODIGO C
            ON C.SEQPRODUTO = NI.SEQPRODUTO
    WHERE NF.NROEMPRESA = #LS1
      AND ((C.TIPCODIGO = 'E' AND C.CODACESSO = :NR1)
           OR C.SEQPRODUTO = :NR1)
      AND NVL(NF.DTARECEBIMENTO, NF.DTAENTRADA) IS NOT NULL
    ORDER BY NVL(NF.DTARECEBIMENTO, NF.DTAENTRADA) DESC,
             NF.NUMERONF DESC
) X
WHERE ROWNUM = 1;
