SELECT 'Exe' TP FROM DUAL;

EXECUTE NAGP_UPD_CONTROLE_SELOS_PDV(#LS1, :NR1, :NR2, :DT1, :NR3, :NR4, #LS2);

SELECT TO_CHAR(X.DTAAJUSTE, 'DD/MM/YYYY HH24:MI:SS') DTAAJUSTE,
       X.USUAJUSTE,
       X.NROEMPRESA LOJA,
       X.NROCHECKOUT,
       X.SEQTURNO TURNO,
       X.SELOS_ACEITOS,
       X.SELOS_RECUSADOS,
       X.SELO_INICIAL,
       X.SELO_FINAL,
       X.DIFERENCA,
       TO_CHAR(X.DTAMOVIMENTO, 'DD/MM/YYYY') DTAMOVIMENTO,
       X.OPERADOR,
       X.NOME_OPERADOR FROM NAGT_CONTROLE_SELOS_PDV X
       
WHERE X.NROEMPRESA = #LS1
  AND X.NROCHECKOUT = :NR1
  AND X.SEQTURNO = :NR2
  AND X.DTAMOVIMENTO = :DT1;
