/*SELECT A.CODUSUARIO GRUPO_USUARIO, A.NOME, NULL EMP_USU, NULL ULTIMO_ACESSO
FROM CONSINCO.GE_USUARIO A
WHERE A.TIPOUSUARIO = 'G' 
AND A.CODUSUARIO = 'mtdespusu'
 
UNION ALL

SELECT NULL, NULL, NULL, NULL FROM DUAL

UNION ALL*/

SELECT A.CODUSUARIO NOME_GRUPO,C.NOME NOME_USUARIO, C.CODUSUARIO LOGIN_USUARIO                                                                                                  
FROM CONSINCO.GE_USUARIO A LEFT JOIN CONSINCO.GE_MEMBRO B ON A.SEQUSUARIO = B.GRUPO
                           LEFT JOIN (SELECT *
                           FROM CONSINCO.GE_USUARIO WHERE TIPOUSUARIO = 'U') C ON B.USUARIO = C.SEQUSUARIO
 
WHERE A.TIPOUSUARIO = 'G' 
AND A.CODUSUARIO = 'mtdespusu'

ORDER BY 1,2
 
