SELECT * FROM (

SELECT M.NROEMPRESA, A.SEQPRODUTO PLU, DESCCOMPLETA,
       TO_CHAR(GREATEST(MAX(B.DTAALTERACAO), MAX(B.DTAGERACAOPRECO), MAX(PL.DTAHORALTERACAO)), 'DD/MM/YYYY HH24:MI:SS') DTA_ULTIMA_ALT,
       TO_CHAR(L.DTALOG, 'DD/MM/YYYY HH24:MI:SS') DTA_CARGA, L.USUARIOEXE USUARIO_GEROU, 
       DECODE(NVL(L.INDGERAPDV, 'N'),     'N',' Não', 'P', 'Parcial', 'T', 'Total') IND_GEROU_PDV,
       DECODE(NVL(L.INDGERABALANCA, 'N'), 'N',' Não', 'P', 'Parcial', 'T', 'Total') IND_GEROU_BAL
       
  FROM CONSINCO.MAP_PRODUTO A INNER JOIN CONSINCO.MRL_PRODEMPSEG B    ON A.SEQPRODUTO = B.SEQPRODUTO
                              INNER JOIN CONSINCO.MAX_EMPRESA M       ON M.NROEMPRESA = B.NROEMPRESA AND M.NROSEGMENTOPRINC = B.NROSEGMENTO
                               LEFT JOIN CONSINCO.NAGT_LOG_CARGAPDV L ON L.NROEMPRESA = B.NROEMPRESA 
                               LEFT JOIN CONSINCO.MAP_PRODCODIGO  E   ON E.SEQPRODUTO = A.SEQPRODUTO AND E.QTDEMBALAGEM = B.QTDEMBALAGEM AND E.TIPCODIGO = 'E'
                               LEFT JOIN CONSINCO.MAD_PRODLOGPRECO PL ON PL.SEQPRODUTO  = A.SEQPRODUTO
                                                                     AND PL.NROEMPRESA  = B.NROEMPRESA
                                                                     AND PL.NROSEGMENTO = B.NROSEGMENTO
                                                                     AND PL.QTDEMBALAGEM = B.QTDEMBALAGEM
                              
                              
 WHERE (A.SEQPRODUTO = :NR1 OR E.CODACESSO = :NR2)
   AND B.QTDEMBALAGEM = 1
   AND B.NROEMPRESA = :LS1
   
 GROUP BY M.NROEMPRESA, A.SEQPRODUTO, DESCCOMPLETA, TO_CHAR(L.DTALOG, 'DD/MM/YYYY HH24:MI:SS'), L.USUARIOEXE, L.INDGERAPDV, L.INDGERABALANCA)
 
 WHERE DTA_CARGA >= DTA_ULTIMA_ALT 
   
 ORDER BY 1
