SELECT DISTINCT A.SEQUSUARIO COD_USUARIO, NIVEL, CODUSUARIO USUARIO, NOME,
       AA.SISTEMA ||' > '||AA.MODULO MODULO, AA.CODAPLICACAO, AA.DESCRICAO, 
       LISTAGG(CASE WHEN V.TIPOEMPRESA = 'G' THEN V.NOMEREDUZIDO ELSE TO_CHAR(V.EMPRESA) END, ', ') WITHIN GROUP (ORDER BY CASE WHEN V.TIPOEMPRESA = 'G' THEN V.NOMEREDUZIDO ELSE TO_CHAR(V.EMPRESA) END) LJ_PERM
  FROM GE_PERMISSAO A INNER JOIN GE_USUARIO G ON A.SEQUSUARIO = G.SEQUSUARIO
                      INNER JOIN GEV_EMPGRUPOS V ON V.EMPRESA = A.EMPRESA AND V.TIPOEMPRESA = A.TIPOEMPRESA
                      INNER JOIN GE_APLICACAO AA ON AA.SEQAPLICACAO = A.SEQAPLICACAO
  
 WHERE 1=1
   AND UPPER(G.CODUSUARIO) = #LT1
   
GROUP BY A.SEQUSUARIO, NIVEL, CODUSUARIO , NOME,
         AA.SISTEMA ||' > '||AA.MODULO, AA.CODAPLICACAO, AA.DESCRICAO
   
ORDER BY 5,6;


	                                                                                                               
