SELECT /*+ ORDERED */
       X.NROEMPRESA                                     ,
       X.SEQPRODUTO                                     PRODUCT_CODE,
       FBUSCAEANPRODUTONAG(X.SEQPRODUTO)                CODIGO_BARRA,
       P.DESCCOMPLETA                                   PROD_DESCRIPTION,
       (E.ESTQLOJA + E.ESTQDEPOSITO - E.QTDRESERVADAVDA -
            E.QTDRESERVADARECEB - E.QTDRESERVADAFIXA +
          FC5_ESTQTERCFIN2(E.SEQPRODUTO, E.NROEMPRESA)) ESTOQUE_DISPONIVEL,
       X.PRECOVALIDNORMAL                               NORMAL_PRICE,
       ROUND(X.PRECOVALIDNORMAL * 1.08,2)               NORMAL_PRICE_MKP,
       X.PRECOVALIDPROMOC                               PROMOC_PRICE,
       NVL(X.PRECOVALIDPROMOC, X.PRECOVALIDNORMAL)      ACTUAL_PRICE,
       ROUND(NVL(PROMOC.PRICE, X.PRECOVALIDNORMAL) * 1.08,2) ACTUAL_PRICE_MKP,
       NVL(MN.PRECOPROMOCAO,0)                          MN_PRICE,
       PROMOC.DESCRIPTION                               TIPO_PROMOC_MKP,
       PROMOC.STARTDATETIME_DATE                        PROMOC_STARTDATE,
       PROMOC.ENDDATETIME_DATE                          PROMOC_ENDDATE,
       E.DTAULTVENDA                                    ,
       E.DTAULTENTRCUSTO                                DTAULTENTRADA,
       ROUND(E.MEDVDIAGERAL,2)                          MEDIA_VENDA,
       MARCA                                            ,
       CATEGORIA                                        ,
       fUrl(X.SEQPRODUTO)                               URL,
       CASE WHEN R.SEQPRODUTO IS NOT NULL THEN 'S' ELSE 'N' END EX_PROX_VALID
       
  FROM MRL_PRODEMPSEG X INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO
                        INNER JOIN MRL_PRODUTOEMPRESA E ON E.NROEMPRESA = X.NROEMPRESA AND E.SEQPRODUTO = NVL(P.SEQPRODUTOBASE, X.SEQPRODUTO)
                        INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = X.NROEMPRESA AND X.NROSEGMENTO = M.NROSEGMENTOPRINC
                        INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                        INNER JOIN MAP_FAMDIVCATEG D ON D.SEQFAMILIA = F.SEQFAMILIA AND D.STATUS = 'A'
                         LEFT JOIN NAGV_MENORPROMOCATIVA PROMOC ON PROMOC.SKU = X.SEQPRODUTO AND PROMOC.STOREREFERENCE = X.NROEMPRESA
                         LEFT JOIN NAGV_BASE_PROMOC_PDV MN ON MN.SEQPRODUTO = X.SEQPRODUTO AND MN.NROEMPRESA = X.NROEMPRESA AND MN.CODPARCEIRO = 700
                        INNER JOIN MAP_MARCA   C ON C.SEQMARCA   = F.SEQMARCA
                        INNER JOIN MAP_CATEGORIA T ON T.SEQCATEGORIA = D.SEQCATEGORIA AND T.TIPCATEGORIA = 'M' AND T.STATUSCATEGOR = 'A' AND NIVELHIERARQUIA = 1
                         LEFT JOIN MRL_PROMOCESPECIALHIST R ON R.SEQPRODUTO = X.SEQPRODUTO AND R.NROEMPRESA = X.NROEMPRESA AND TRUNC(SYSDATE) BETWEEN R.DTAINICIO AND R.DTAFIM
                         
 WHERE 1=1
   AND X.QTDEMBALAGEM = 1
   AND X.STATUSVENDA  = 'A'
   AND X.NROEMPRESA   = 1
   AND X.SEQPRODUTO   IN (210523,5500)
 
 ORDER BY 1,2;

CREATE OR REPLACE VIEW NAGV_APURACAO_SELLOUT_VALIDADE AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/  
       MAX(A.QTDESOLICITADA)     QTD_SOLIC,
       NVL(SUM(B.QTDOPERACAO),0) QTD_VENDIDA,
       MAX(DTAFIM)               DTA_VENCTO,
       B.NROEMPRESA, B.SEQPRODUTO
  FROM FATO_VENDA  B INNER JOIN MRL_PROMOCESPECIALHIST A ON B.SEQPRODUTO = A.SEQPRODUTO
                                                         AND B.NROEMPRESA = A.NROEMPRESA
                                                         AND B.DTAOPERACAO BETWEEN DTAINICIO AND DTAFIM
                                                         AND A.CODACESSOESPECIAL = B.CODPRODUTO 
                                                        
 WHERE 1=1
   AND TRUNC(SYSDATE) BETWEEN DTAINICIO AND DTAFIM
 GROUP BY B.NROEMPRESA, B.SEQPRODUTO;
   

SELECT * FROM NAGV_APURACAO_SELLOUT_VALIDADE X
 WHERE X.NROEMPRESA = 1 AND SEQPRODUTO = 210523;
