/* Compara parametros diferentes entre empresas */

ALTER SESSION SET current_schema = CONSINCO;

SELECT * FROM (

SELECT A.PARAMETRO, A.GRUPO, B.NROEMPRESA EMP_A, B.VALOR VALOR_A, A.NROEMPRESA EMP_B, A.VALOR VALOR_B, A.COMENTARIO 
  FROM CONSINCO.MAX_PARAMETRO A LEFT JOIN (
SELECT * FROM CONSINCO.MAX_PARAMETRO 
/*Lado A*/
WHERE NROEMPRESA   = 501
ORDER BY PARAMETRO, NROEMPRESA, GRUPO
) B ON A.PARAMETRO = B.PARAMETRO AND A.GRUPO = B.GRUPO 
/*Lado B*/
WHERE A.NROEMPRESA = 503
AND A.VALOR != B.VALOR
ORDER BY A.PARAMETRO, A.NROEMPRESA, A.GRUPO )

WHERE COMENTARIO LIKE '%PERC%';
