ALTER SESSION SET current_schema = CONSINCO;

/* Embalagem > 1 com  o mesmo preço do unitário */

SELECT * FROM MRL_PRODEMPSEG C WHERE C.NROEMPRESA = 54 AND C.NROSEGMENTO = 7 AND STATUSVENDA = 'A' AND PRECOBASENORMAL > 0 AND SEQPRODUTO IN (

SELECT SEQPRODUTO
  FROM MRL_PRODEMPSEG B WHERE B.NROEMPRESA = 54 AND B.NROSEGMENTO = 7 AND B.QTDEMBALAGEM = 1 AND STATUSVENDA = 'A'
   AND B.SEQPRODUTO IN (SELECT SEQPRODUTO FROM MRL_PRODEMPSEG A
 WHERE A.NROEMPRESA = 54 AND A.NROSEGMENTO = 7 AND A.QTDEMBALAGEM > 1 AND B.PRECOBASENORMAL = A.PRECOBASENORMAL AND STATUSVENDA = 'A'))

ORDER BY 1;

/* Embalagens > 1 alterados pela equiparação da loja 08 */

SELECT * FROM MRL_PRODEMPSEG H WHERE H.NROEMPRESA = 54 AND H.NROSEGMENTO = 7 AND H.STATUSVENDA = 'A' AND H.SEQPRODUTO IN (
SELECT SEQPRODUTO FROM MRL_PRODEMPSEG D WHERE D.NROEMPRESA = 54 AND D.NROSEGMENTO = 7 AND STATUSVENDA = 'A' AND D.QTDEMBALAGEM > 1 
          AND UPPER(MOTIVOPRECOBASE) LIKE '%EQUIP%' AND PRECOBASENORMAL != 0)

ORDER  BY 1;

/* Emb > 1 ativa com unitário inativo */ 

SELECT * FROM MRL_PRODEMPSEG G WHERE G.NROEMPRESA = 54 AND G.NROSEGMENTO = 7 AND SEQPRODUTO IN (
SELECT SEQPRODUTO FROM MRL_PRODEMPSEG F WHERE F.NROEMPRESA = 54 AND F.NROSEGMENTO = 7 AND F.STATUSVENDA = 'I' AND F.QTDEMBALAGEM = 1 AND SEQPRODUTO IN (
SELECT SEQPRODUTO FROM MRL_PRODEMPSEG D WHERE D.NROEMPRESA = 54 AND D.NROSEGMENTO = 7 AND D.STATUSVENDA = 'A' AND SEQPRODUTO IN (  
       SELECT SEQPRODUTO FROM MRL_PRODEMPSEG E WHERE E.NROEMPRESA = 54 AND E.NROSEGMENTO = 7 AND E.STATUSVENDA = 'A' AND D.QTDEMBALAGEM > 1)))

ORDER BY 1;

        
