ALTER SESSION SET current_schema = CONSINCO;

SELECT CODGERALOPER CGO, CODESPECIEFIN ESPECIE, DTAALTERACAO, USUALTERACAO, OSUSER, TERMINAL, MODULE, IPCLIENT , A.GERACARGAAUTO -- A.*
FROM MAX_CODGERALOPERHIST A 

WHERE A.CODGERALOPER = 69
AND A.DTAALTERACAO IS NOT NULL

ORDER BY A.DTAALTERACAO DESC
