ALTER SESSION SET current_schema = CONSINCO;

SELECT DTAMOVIMENTO DATA_EMISSAO, 
       TO_CHAR(sum(vlrvenda), 'FM999G999G999D90', 'nls_numeric_characters='',.''') VENDA

FROM (SELECT TO_CHAR(C.DTAMOVIMENTO, 'DD/MM/YYYY') DTAMOVIMENTO,
               C.NROEMPRESA, SUM(D.VLRITEM) VLRVENDA
      FROM MFL_DOCTOFISCAL C, MFL_DFITEM D
      WHERE C.SEQNF = D.SEQNF
        AND C.NROEMPRESA IN (:NR1)
        AND C.DTAMOVIMENTO BETWEEN :DT1 and :DT2
        AND D.STATUSITEM = 'V'
        AND C.CODGERALOPER IN (810, 910)
      GROUP BY C.DTAMOVIMENTO, C.NROEMPRESA)
        
GROUP BY DTAMOVIMENTO

UNION ALL

SELECT  'Total Geral:' DATA,
        TO_CHAR(sum(vlrvenda), 'FM999G999G999D90', 'nls_numeric_characters='',.''') VENDA

FROM (SELECT TO_CHAR(C.DTAMOVIMENTO, 'MM/YYYY') DTAMOVIMENTO, 
             TO_CHAR(C.DTAMOVIMENTO, 'MM') MES, 
               C.NROEMPRESA, SUM(D.VLRITEM) VLRVENDA
      FROM MFL_DOCTOFISCAL C, MFL_DFITEM D
      WHERE C.SEQNF = D.SEQNF
        AND C.NROEMPRESA IN (:NR1)
        AND C.DTAMOVIMENTO BETWEEN :DT1 and :DT2
        AND D.STATUSITEM = 'V'
        AND C.CODGERALOPER IN (810, 910)
      GROUP BY C.DTAMOVIMENTO, C.NROEMPRESA)

GROUP BY MES
ORDER BY 1;
