ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

/*
SELECT * FROM CONSINCO.MLO_LOTEINVFISICO;
SELECT * FROM CONSINCO.MLO_LOTEINVFISITEM;
SELECT * FROM CONSINCO.MLO_)
SELECT * FROM CONSINCO.MLO_ENDERECO;
SELECT * FROM CONSINCO.MLO_ENDERECOQTDE;
*/
SELECT DISTINCT CODDEPOSITANTE||'-'||A.NROEMPRESA DP_CD,
       A.SEQENDERECO, A.CODRUA, A.NROPREDIO, A.NROAPARTAMENTO, A.NROSALA, 
       A.STATUSENDERECO,
       A.SEQPRODUTO, P.DESCCOMPLETA,
       A.QTDATUAL, 
       A.USUALTERACAO ULT_USUALT,
       A.DTAALTERACAO ULT_DTAALT,
       A.APLALTERACAO ULT_APLALT--, A.ESPECIEENDERECO, D.STATUSLOTEINVFISICO, D.DTAHORINCORPDIVERG, D.USUINCORPDIVERG, C.QTDGERADA, F.QTDCONTADA, INDENDVISITADO
       
  FROM CONSINCO.MLO_ENDERECO A LEFT JOIN MLO_ENDERECOQTDE B   ON A.SEQENDERECO = B.SEQENDERECO
                               LEFT JOIN MLO_LOTEINVFISITEM C ON C.SEQENDERECO = A.SEQENDERECO
                               LEFT JOIN MLO_LOTEINVFISICO D  ON D.SEQLOTE = C.SEQLOTE
                               LEFT JOIN CONSINCO.MLO_LOTEINVFISICOCONTAGEM E  ON E.SEQLOTE = D.SEQLOTE 
                               LEFT JOIN CONSINCO.MLO_LOTEINVFISITEMCONTAGEM F ON F.SEQLOTE = D.SEQLOTE 
                                                                              AND F.SEQPRODUTO = C.SEQPRODUTO 
                                                                              AND F.SEQENDERECO = A.SEQENDERECO
                                                                              AND F.NROCONTAGEM = E.NROCONTAGEM
                               INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO
 WHERE 1=1
   AND 2=2 
   AND NOT EXISTS (SELECT 1
                     FROM CONSINCO.MLO_LOTEINVFISICO X INNER JOIN MLO_LOTEINVFISITEM XI ON X.SEQLOTE = XI.SEQLOTE
                    WHERE 2=2 -- USUGERACAO = 'GIGOMES' pq fiz em homolog pra testar
                      AND XI.SEQENDERECO = A.SEQENDERECO
                      AND X.NROEMPRESA = A.CODDEPOSITANTE
                      AND TRUNC(X.DTAHORGERACAO) BETWEEN DATE '2024-12-01' AND DATE '2024-12-01') -- Datas em que foram gerados os lotes do inventario de novembro
   
  -- AND A.CODRUA = 'BL'
   AND A.QTDATUAL != 0
   AND A.NROEMPRESA IN (507) --NOT IN (504,505)
   --AND A.CODRUA NOT IN ('J','R', 'SEL')
   ORDER BY QTDATUAL DESC;
   
